name = "ge-db-thai"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
assets = { directory = "./public" }
workers_dev = false
routes = [{ pattern = "ge.makeloops.xyz", custom_domain = true }]

[[d1_databases]]
binding = "DB"
database_name = "ge-db-thai"
database_id = "16e05fc9-1a45-4cf3-a0c9-df82e131d020"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "ge-db-assets"
