-- GE Database Thai — Thai Character Name Transliterations
-- Generated by Jingjing Oracle

-- Basic Characters (6)
UPDATE characters SET name_th = 'วอร์ล็อค' WHERE slug = 'Warlock';
UPDATE characters SET name_th = 'ไฟท์เตอร์' WHERE slug = 'Fighter';
UPDATE characters SET name_th = 'มัสเกเทียร์' WHERE slug = 'Musketeer';
UPDATE characters SET name_th = 'สเกาท์' WHERE slug = 'Scout';
UPDATE characters SET name_th = 'วิซาร์ด' WHERE slug = 'Wizard';
UPDATE characters SET name_th = 'เอเลเมนทัลลิสต์' WHERE slug = 'Elementalist';

-- A
UPDATE characters SET name_th = 'อัคลา' WHERE slug = 'Aclla';
UPDATE characters SET name_th = 'อเดลิน่า' WHERE slug = 'Adelina';
UPDATE characters SET name_th = 'เอเดรียน่า' WHERE slug = 'Adriana';
UPDATE characters SET name_th = 'ไอลีน' WHERE slug = 'Eileen';
UPDATE characters SET name_th = 'ไอชา' WHERE slug = 'Aisha';
UPDATE characters SET name_th = 'ไอเธอร์' WHERE slug = 'Aether';
UPDATE characters SET name_th = 'อเลฮานโดร' WHERE slug = 'Alejandro';
UPDATE characters SET name_th = 'เอมี่' WHERE slug = 'Amy';
UPDATE characters SET name_th = 'อองเดร' WHERE slug = 'Andre';
UPDATE characters SET name_th = 'แองเจลิค' WHERE slug = 'Angelic';
UPDATE characters SET name_th = 'แองจี้' WHERE slug = 'Angie';
UPDATE characters SET name_th = 'อาเนีย' WHERE slug = 'Ania';
UPDATE characters SET name_th = 'อานีส' WHERE slug = 'Anies';
UPDATE characters SET name_th = 'อนิตา' WHERE slug = 'Anita';
UPDATE characters SET name_th = 'อังคิตา' WHERE slug = 'Ankita';
UPDATE characters SET name_th = 'อาร์ชบิชอป' WHERE slug = 'Van2';
UPDATE characters SET name_th = 'อโศกะ' WHERE slug = 'Asoka';
UPDATE characters SET name_th = 'แฮร์ริออท แอร์ฮาร์ท' WHERE slug = 'Airheart';

-- B
UPDATE characters SET name_th = 'แบ็คโฮ' WHERE slug = 'Backho';
UPDATE characters SET name_th = 'เบน' WHERE slug = 'Bane';
UPDATE characters SET name_th = 'แบนชี นาตาลี' WHERE slug = 'NatalieRare';
UPDATE characters SET name_th = 'บาร์รอล' WHERE slug = 'Barrel';
UPDATE characters SET name_th = 'แบทเทิลคุก ปานฟิโล' WHERE slug = 'PanfiloBattle';
UPDATE characters SET name_th = 'แบทเทิลสมิธ อิดจ์' WHERE slug = 'IdgeBattle';
UPDATE characters SET name_th = 'แบทเทิลฟิลด์ คล็อด' WHERE slug = 'ClaudeY';
UPDATE characters SET name_th = 'เบ็คกี้' WHERE slug = 'Becky';
UPDATE characters SET name_th = 'เบเดล' WHERE slug = 'Bedel';
UPDATE characters SET name_th = 'เบฮีมอธ' WHERE slug = 'Behemoth';
UPDATE characters SET name_th = 'เบลิธ' WHERE slug = 'Belith';
UPDATE characters SET name_th = 'เบอร์เนลลี' WHERE slug = 'Grace';
UPDATE characters SET name_th = 'แบร์เธ่ แอนด์ ชาร์ลส์' WHERE slug = 'Berthe';
UPDATE characters SET name_th = 'เบียงก้า' WHERE slug = 'Bianca';
UPDATE characters SET name_th = 'บลัดเนวี่ คาโน่' WHERE slug = 'Kano2';
UPDATE characters SET name_th = 'บลูเฟลม ลูดิน' WHERE slug = 'BLudin';
UPDATE characters SET name_th = 'บริดเจ็ท' WHERE slug = 'Brigitte';
UPDATE characters SET name_th = 'บรูนี่' WHERE slug = 'Brunie';
UPDATE characters SET name_th = 'ไบรอัน' WHERE slug = 'Bryan';

-- C
UPDATE characters SET name_th = 'คาเดท เอเดรียน่า' WHERE slug = 'CadetAdriana';
UPDATE characters SET name_th = 'คาเดท เอมี่' WHERE slug = 'AmyRare';
UPDATE characters SET name_th = 'คาเดท เอลิซ่า' WHERE slug = 'Elisa';
UPDATE characters SET name_th = 'คาเดท เลโอเนเล' WHERE slug = 'CLeonele';
UPDATE characters SET name_th = 'คาเดท ร็อบ' WHERE slug = 'CadetRob';
UPDATE characters SET name_th = 'เคส' WHERE slug = 'Kess';
UPDATE characters SET name_th = 'คาลิส' WHERE slug = 'Calyce';
UPDATE characters SET name_th = 'แคนน่า' WHERE slug = 'OrnellaBlack';
UPDATE characters SET name_th = 'แคนนอนชูตเตอร์ แคลร์' WHERE slug = 'ClairCN';
UPDATE characters SET name_th = 'คาร์เมน' WHERE slug = 'Karmen';
UPDATE characters SET name_th = 'คาสซานดร้า' WHERE slug = 'Cassandra';
UPDATE characters SET name_th = 'แคทเธอรีน' WHERE slug = 'CatherineREAL';
UPDATE characters SET name_th = 'แคทเธอรีน (DEX)' WHERE slug = 'CatherineDEX';
UPDATE characters SET name_th = 'แคทเธอรีน (INT)' WHERE slug = 'CatherineINT';
UPDATE characters SET name_th = 'แคทเธอรีน (STR)' WHERE slug = 'CatherineSTR';
UPDATE characters SET name_th = 'แคทเธอรีน ทอร์เช่' WHERE slug = 'CatherineTorsche';
UPDATE characters SET name_th = 'เซซิล' WHERE slug = 'Sesil';
UPDATE characters SET name_th = 'ชาร์ล็อต' WHERE slug = 'Charlotrare';
UPDATE characters SET name_th = 'เชอร์ลิน' WHERE slug = 'Sherlin';
UPDATE characters SET name_th = 'หัวหน้านักเล่นแร่แปรธาตุ เวโรนิฟ' WHERE slug = 'BerroniffRare';
UPDATE characters SET name_th = 'โคลอี้' WHERE slug = 'Chloe';
UPDATE characters SET name_th = 'คริสติน่า' WHERE slug = 'Cristina';
UPDATE characters SET name_th = 'ชุงฮา' WHERE slug = 'Chungha';
UPDATE characters SET name_th = 'เซียล' WHERE slug = 'Ciel';
UPDATE characters SET name_th = 'ทหารราบเมืองอ็อค' WHERE slug = 'Infantry';
UPDATE characters SET name_th = 'แคลร์' WHERE slug = 'Clair';
UPDATE characters SET name_th = 'คล็อด' WHERE slug = 'Claude';
UPDATE characters SET name_th = 'โค้' WHERE slug = 'Coa';
UPDATE characters SET name_th = 'โค้ดเนม C' WHERE slug = 'Chloe2';
UPDATE characters SET name_th = 'โค้ดเนม J' WHERE slug = 'CodeNameJ';
UPDATE characters SET name_th = 'โค้ดเนม L' WHERE slug = 'Leona2';
UPDATE characters SET name_th = 'โค้ดเนม T' WHERE slug = 'Tora2';
UPDATE characters SET name_th = 'โค้ดเนม V' WHERE slug = 'Veatrice2';
UPDATE characters SET name_th = 'ทหารโคอิมบร้า' WHERE slug = 'Trooper';
UPDATE characters SET name_th = 'คอนดัคเตอร์ ริโอ' WHERE slug = 'RioRare';
UPDATE characters SET name_th = 'กงสุล ดีทริช' WHERE slug = 'DiertrichRare';
UPDATE characters SET name_th = 'ครูซ' WHERE slug = 'Cruz';
UPDATE characters SET name_th = 'ครูเซเดอร์ ดาเรีย' WHERE slug = 'DariaRare';
UPDATE characters SET name_th = 'คิวตี้ แคลร์' WHERE slug = 'ClairCG';

-- D
UPDATE characters SET name_th = 'เดซี่' WHERE slug = 'Daisy';
UPDATE characters SET name_th = 'ดาเนฟ' WHERE slug = 'Danev';
UPDATE characters SET name_th = 'ดาเรีย' WHERE slug = 'Daria';
UPDATE characters SET name_th = 'เดลฟิน่า' WHERE slug = 'Delfina';
UPDATE characters SET name_th = 'เดลูก้า' WHERE slug = 'Diluca';
UPDATE characters SET name_th = 'ดีไซเนอร์ คาร์ยาไลเนน' WHERE slug = 'Mi2';
UPDATE characters SET name_th = 'ดีทริช' WHERE slug = 'Diertrichherberthe';
UPDATE characters SET name_th = 'ดิไวน์แฮมเมอร์ ไบรอัน' WHERE slug = 'BryanRare';
UPDATE characters SET name_th = 'โดโลเรส' WHERE slug = 'Dolores';
UPDATE characters SET name_th = 'ดูมสเลฟ' WHERE slug = 'bknight';
UPDATE characters SET name_th = 'ดราเค่น' WHERE slug = 'Drachen';

-- E
UPDATE characters SET name_th = 'เอ็ดเวิร์ด' WHERE slug = 'Eduardo';
UPDATE characters SET name_th = 'เอลิซ่า' WHERE slug = 'ElisaOfficer';
UPDATE characters SET name_th = 'เอลิซาเบธ' WHERE slug = 'Elizabeth';
UPDATE characters SET name_th = 'เอลลี่' WHERE slug = 'Ellie';
UPDATE characters SET name_th = 'เอลลี่ เครก' WHERE slug = 'Ellie2';
UPDATE characters SET name_th = 'เอมิเลีย กูเลียโน่' WHERE slug = 'Emilia';
UPDATE characters SET name_th = 'เอมิเลีย เดอะเซจ' WHERE slug = 'EmiliaSage';
UPDATE characters SET name_th = 'เอ็มไพเรียม จูดิธ' WHERE slug = 'Judith';
UPDATE characters SET name_th = 'เอ็นฟอร์เซอร์ อานีส' WHERE slug = 'Anies2';
UPDATE characters SET name_th = 'เอริก้า' WHERE slug = 'Erica';
UPDATE characters SET name_th = 'อีวา ชารอน' WHERE slug = 'Sharon';
UPDATE characters SET name_th = 'อีวิล' WHERE slug = 'Evil';

-- F
UPDATE characters SET name_th = 'เฟนริร์' WHERE slug = 'Violet2';
UPDATE characters SET name_th = 'ฟรีเซีย' WHERE slug = 'Freesia';
UPDATE characters SET name_th = 'เฟรยา' WHERE slug = 'Valkyrie';
UPDATE characters SET name_th = 'ฟรีเด' WHERE slug = 'Freeday';

-- G
UPDATE characters SET name_th = 'การ์เซีย' WHERE slug = 'Garcia';
UPDATE characters SET name_th = 'เการ่า' WHERE slug = 'Gaura';
UPDATE characters SET name_th = 'กิลทิเน่' WHERE slug = 'Giltine';
UPDATE characters SET name_th = 'กราเซียโล' WHERE slug = 'Gracielo';
UPDATE characters SET name_th = 'แกรนดีส์' WHERE slug = 'Grandies';
UPDATE characters SET name_th = 'คุณยาย' WHERE slug = 'Grandma';
UPDATE characters SET name_th = 'กรูทรูด' WHERE slug = 'Gurtrude';
UPDATE characters SET name_th = 'การ์เดียน อาเนีย' WHERE slug = 'Ania2';
UPDATE characters SET name_th = 'การ์เดียน โค้' WHERE slug = 'CoaRare';
UPDATE characters SET name_th = 'การ์เดียน ลู' WHERE slug = 'LooRare';
UPDATE characters SET name_th = 'การ์เดียน นาร์' WHERE slug = 'NarRare';

-- H
UPDATE characters SET name_th = 'แฮส ลาเบิร์ด' WHERE slug = 'Hass';
UPDATE characters SET name_th = 'เฮคเตอร์' WHERE slug = 'Hektor';
UPDATE characters SET name_th = 'เฮก้า' WHERE slug = 'Heka';
UPDATE characters SET name_th = 'เฮลเลน่า' WHERE slug = 'Hellena';
UPDATE characters SET name_th = 'เฮอร์เมส' WHERE slug = 'Hermes';
UPDATE characters SET name_th = 'เฮย์ราน' WHERE slug = 'Heyran';
UPDATE characters SET name_th = 'ฮิลเดการ์ด' WHERE slug = 'Hildegard';

-- I
UPDATE characters SET name_th = 'อิดจ์ อิมบรูเลีย' WHERE slug = 'Idge';
UPDATE characters SET name_th = 'อิลลูชั่น' WHERE slug = 'Illusion';
UPDATE characters SET name_th = 'ไอออน' WHERE slug = 'Ion';
UPDATE characters SET name_th = 'อิราวัณ' WHERE slug = 'Muathai';
UPDATE characters SET name_th = 'ไอแซค' WHERE slug = 'Isaac';
UPDATE characters SET name_th = 'อิซาเบล' WHERE slug = 'Isabel2';

-- J
UPDATE characters SET name_th = 'เจดี' WHERE slug = 'JD';
UPDATE characters SET name_th = 'จีน่า' WHERE slug = 'Jina';
UPDATE characters SET name_th = 'โจเซฟิน' WHERE slug = 'Josefina';
UPDATE characters SET name_th = 'จูเลีย' WHERE slug = 'Julia';
UPDATE characters SET name_th = 'จูเลีย ดอร์ชเนอร์' WHERE slug = 'Julia2';

-- K
UPDATE characters SET name_th = 'คาเอล' WHERE slug = 'Kael';
UPDATE characters SET name_th = 'คาโน่' WHERE slug = 'Kano';
UPDATE characters SET name_th = 'คาริน' WHERE slug = 'Karin';
UPDATE characters SET name_th = 'แคทเธอรีน เดอะ ซีเนียร์' WHERE slug = 'KatherineSENIOR';
UPDATE characters SET name_th = 'คีรี' WHERE slug = 'Keyris';
UPDATE characters SET name_th = 'คุร์ทอน' WHERE slug = 'Kurton';

-- L
UPDATE characters SET name_th = 'เลดี้ ไนท์' WHERE slug = 'LadyKnight';
UPDATE characters SET name_th = 'เลโอเนเล' WHERE slug = 'Leonele';
UPDATE characters SET name_th = 'เลโอน่า' WHERE slug = 'Leona';
UPDATE characters SET name_th = 'ลิซ่า' WHERE slug = 'Lisa';
UPDATE characters SET name_th = 'ลอร์ด ชาร์ลส์' WHERE slug = 'LordCharles';
UPDATE characters SET name_th = 'ลู' WHERE slug = 'Loo';
UPDATE characters SET name_th = 'ลูดิน' WHERE slug = 'Ludin';
UPDATE characters SET name_th = 'ลูซิเฟอร์' WHERE slug = 'Lucifer';
UPDATE characters SET name_th = 'ลูน่า' WHERE slug = 'Luna';
UPDATE characters SET name_th = 'ลินดอน' WHERE slug = 'Lyndon';

-- M
UPDATE characters SET name_th = 'เอ็ม' WHERE slug = 'M';
UPDATE characters SET name_th = 'แม็กดาเลน่า' WHERE slug = 'Magdalena';
UPDATE characters SET name_th = 'มาร์เซลล่า' WHERE slug = 'Marchetti';
UPDATE characters SET name_th = 'มาร์เกอริต้า' WHERE slug = 'Margherita';
UPDATE characters SET name_th = 'มาเรีย' WHERE slug = 'Maria';
UPDATE characters SET name_th = 'มิ' WHERE slug = 'Mi';
UPDATE characters SET name_th = 'มิฮาอิล' WHERE slug = 'Mikhail';
UPDATE characters SET name_th = 'มิเนอร์วา' WHERE slug = 'Minerva';
UPDATE characters SET name_th = 'มุสซ่า' WHERE slug = 'Moussa';
UPDATE characters SET name_th = 'มิสเตอร์ คิว' WHERE slug = 'MrQ';

-- N
UPDATE characters SET name_th = 'นาร์' WHERE slug = 'Nar';
UPDATE characters SET name_th = 'นาตาลี' WHERE slug = 'Natalie';
UPDATE characters SET name_th = 'นักรบนาวี' WHERE slug = 'NavyGuard';
UPDATE characters SET name_th = 'โนเอล' WHERE slug = 'Noel';
UPDATE characters SET name_th = 'นานา' WHERE slug = 'Nana';

-- O
UPDATE characters SET name_th = 'ออคตาเวีย' WHERE slug = 'Octavia';
UPDATE characters SET name_th = 'ออร์เนลล่า' WHERE slug = 'Ornella';

-- P
UPDATE characters SET name_th = 'ปานฟิโล' WHERE slug = 'Panfilo';
UPDATE characters SET name_th = 'เปเนโลเป' WHERE slug = 'Penelope';
UPDATE characters SET name_th = 'ราชินีโจรสลัด' WHERE slug = 'PirateKing';

-- R
UPDATE characters SET name_th = 'ราชีด' WHERE slug = 'Rashid';
UPDATE characters SET name_th = 'เรย์' WHERE slug = 'Rey';
UPDATE characters SET name_th = 'รีเจนท์ คาเอล' WHERE slug = 'KaelRare2';
UPDATE characters SET name_th = 'เรซิสแตนซ์ เคส' WHERE slug = 'Kess2';
UPDATE characters SET name_th = 'เรซิสแตนซ์ เฮย์ราน' WHERE slug = 'Heyran2';
UPDATE characters SET name_th = 'เรซิสแตนซ์ เจดี' WHERE slug = 'JD2';
UPDATE characters SET name_th = 'ริโอ' WHERE slug = 'Rio';
UPDATE characters SET name_th = 'ร็อบ' WHERE slug = 'Rob';
UPDATE characters SET name_th = 'โรซาลินด์' WHERE slug = 'Rosalind';
UPDATE characters SET name_th = 'รูมิน' WHERE slug = 'Rumin';

-- S
UPDATE characters SET name_th = 'สการ์เล็ท' WHERE slug = 'Scarlet';
UPDATE characters SET name_th = 'เซเลน่า' WHERE slug = 'Selena';
UPDATE characters SET name_th = 'เซเรน' WHERE slug = 'Serene';
UPDATE characters SET name_th = 'ชิริน' WHERE slug = 'Shirin';
UPDATE characters SET name_th = 'ซิเอร่า' WHERE slug = 'Sierra';
UPDATE characters SET name_th = 'ซิกมันด์' WHERE slug = 'Sigmund';
UPDATE characters SET name_th = 'ซิโมน' WHERE slug = 'Simone';
UPDATE characters SET name_th = 'ซิมฟินี่' WHERE slug = 'Symphony';
UPDATE characters SET name_th = 'สเวน' WHERE slug = 'Sven';
UPDATE characters SET name_th = 'โซล' WHERE slug = 'Sol';
UPDATE characters SET name_th = 'โซทิส' WHERE slug = 'Sothis';
UPDATE characters SET name_th = 'สเตลล่า' WHERE slug = 'Stella';
UPDATE characters SET name_th = 'ซัมเมอร์ นาตาลี' WHERE slug = 'NatalieSummer';

-- T
UPDATE characters SET name_th = 'เทสล่า' WHERE slug = 'Tesla';
UPDATE characters SET name_th = 'ทาลี่' WHERE slug = 'Tali';
UPDATE characters SET name_th = 'โทร่า' WHERE slug = 'Tora';
UPDATE characters SET name_th = 'ทริสตัน' WHERE slug = 'Tristan';

-- U
UPDATE characters SET name_th = 'อุลฟรัม' WHERE slug = 'Ulfram';
UPDATE characters SET name_th = 'อุจจา' WHERE slug = 'Uja';

-- V
UPDATE characters SET name_th = 'วาเลเรีย' WHERE slug = 'Valeria';
UPDATE characters SET name_th = 'เวล' WHERE slug = 'Veil';
UPDATE characters SET name_th = 'เวโรนิฟ' WHERE slug = 'Berroniff';
UPDATE characters SET name_th = 'วีกี้' WHERE slug = 'Viki';
UPDATE characters SET name_th = 'วินเซนต์' WHERE slug = 'Vincent';
UPDATE characters SET name_th = 'ไวโอเลท' WHERE slug = 'Violet';
UPDATE characters SET name_th = 'วีแอทริซ' WHERE slug = 'Veatrice';

-- W
UPDATE characters SET name_th = 'ไวท์วูล์ฟ' WHERE slug = 'KaelRare';
UPDATE characters SET name_th = 'วิโนน่า' WHERE slug = 'WinonaEnde';

-- Y
UPDATE characters SET name_th = 'เยกาเนห์' WHERE slug = 'Yeganeh';

-- Z
UPDATE characters SET name_th = 'ซาเวด' WHERE slug = 'Zaved';
UPDATE characters SET name_th = 'ซิซ' WHERE slug = 'Ziz';
-- GE Database Thai — Thai Names Part 2 (remaining 114 characters)

-- I-J
UPDATE characters SET name_th = 'ไอวี่' WHERE slug = 'Ivy';
UPDATE characters SET name_th = 'เจดี' WHERE slug = 'Jd';
UPDATE characters SET name_th = 'แจ็ค' WHERE slug = 'Jack';
UPDATE characters SET name_th = 'ไจน่า' WHERE slug = 'Jaina';
UPDATE characters SET name_th = 'เจน' WHERE slug = 'Jane';
UPDATE characters SET name_th = 'จิน' WHERE slug = 'Jin';
UPDATE characters SET name_th = 'โฮเซ่ คอร์ตาซาร์' WHERE slug = 'Jose';
UPDATE characters SET name_th = 'โจชัว' WHERE slug = 'Joshua';
UPDATE characters SET name_th = 'จูดิธ' WHERE slug = 'JudithRare';
UPDATE characters SET name_th = 'จูเลียน่า' WHERE slug = 'Yuliana';

-- K
UPDATE characters SET name_th = 'เคน' WHERE slug = 'Kein';
UPDATE characters SET name_th = 'คาร์ยาไลเนน' WHERE slug = 'Karjalainen';
UPDATE characters SET name_th = 'เค' WHERE slug = 'Kei';
UPDATE characters SET name_th = 'เควิน' WHERE slug = 'Kevin';
UPDATE characters SET name_th = 'เคิร์นน่า' WHERE slug = 'Kirna';
UPDATE characters SET name_th = 'คิส' WHERE slug = 'Kiss';
UPDATE characters SET name_th = 'เคิร์ท' WHERE slug = 'Dietrich';

-- L
UPDATE characters SET name_th = 'ลาด้า' WHERE slug = 'Rada';
UPDATE characters SET name_th = 'เลดี้ ราเชล' WHERE slug = 'Rachel2';
UPDATE characters SET name_th = 'ลาวาล' WHERE slug = 'Laval';
UPDATE characters SET name_th = 'หัวหน้าราเชล' WHERE slug = 'Rachel2Rare';
UPDATE characters SET name_th = 'เลวีอาธาน' WHERE slug = 'Leviathan';
UPDATE characters SET name_th = 'เลวีน' WHERE slug = 'Levin';
UPDATE characters SET name_th = 'โลเต' WHERE slug = 'Viking';
UPDATE characters SET name_th = 'หลิ่ง' WHERE slug = 'Liung';
UPDATE characters SET name_th = 'โลร่า คอนสแตนส์' WHERE slug = 'Laura';
UPDATE characters SET name_th = 'โลเรน' WHERE slug = 'Lorraine';
UPDATE characters SET name_th = 'ลอร์ช' WHERE slug = 'Lorch';
UPDATE characters SET name_th = 'โลเรต้า' WHERE slug = 'Roreta';
UPDATE characters SET name_th = 'ลินน์' WHERE slug = 'Lynn';
UPDATE characters SET name_th = 'ลิเซ็ท' WHERE slug = 'Lysette';

-- M
UPDATE characters SET name_th = 'เอ็มโบม่า' WHERE slug = 'MBoma';
UPDATE characters SET name_th = 'มาเรีย' WHERE slug = 'MariaMayer';
UPDATE characters SET name_th = 'มารี' WHERE slug = 'Mary';
UPDATE characters SET name_th = 'มีเดียเตอร์ แบร์เธ่' WHERE slug = 'BertheRare';
UPDATE characters SET name_th = 'ไมสเตอร์ ลอร์ช' WHERE slug = 'LorchRare';
UPDATE characters SET name_th = 'ทหารรับจ้าง คาลิส' WHERE slug = 'Calyce2';
UPDATE characters SET name_th = 'เมอเรียล' WHERE slug = 'Meriel';
UPDATE characters SET name_th = 'เมอร์ทิส' WHERE slug = 'Mertis';
UPDATE characters SET name_th = 'มิฮา' WHERE slug = 'Miha';
UPDATE characters SET name_th = 'มิโฮ' WHERE slug = 'Miho';
UPDATE characters SET name_th = 'มิเรย์' WHERE slug = 'Mireille';
UPDATE characters SET name_th = 'มิสะ' WHERE slug = 'Misa';
UPDATE characters SET name_th = 'มิสเตรส เบเซลเรน' WHERE slug = 'Lobaselrane';
UPDATE characters SET name_th = 'มอนโตโร' WHERE slug = 'MontoroPC';
UPDATE characters SET name_th = 'มูน' WHERE slug = 'Moon';

-- N
UPDATE characters SET name_th = 'นาจิบ ชารีฟ' WHERE slug = 'Sharif';
UPDATE characters SET name_th = 'นาวาส' WHERE slug = 'Navas';
UPDATE characters SET name_th = 'เนน่า' WHERE slug = 'Nena';
UPDATE characters SET name_th = 'นีโอ' WHERE slug = 'Neo10';
UPDATE characters SET name_th = 'นิโคล' WHERE slug = 'Nicol';
UPDATE characters SET name_th = 'ไนกี้' WHERE slug = 'Nike';
UPDATE characters SET name_th = 'นิน่า' WHERE slug = 'Nina';

-- O
UPDATE characters SET name_th = 'โอลิเวีย' WHERE slug = 'Olivia';

-- P
UPDATE characters SET name_th = 'แพทริค' WHERE slug = 'Patrick';
UPDATE characters SET name_th = 'ผู้บุกเบิก ควีน แกรนด์มา' WHERE slug = 'Grandies2';
UPDATE characters SET name_th = 'โจรสลัด อเดลิน่า' WHERE slug = 'AdelinaPirate';
UPDATE characters SET name_th = 'ไซคี' WHERE slug = 'Psyche';

-- Q
UPDATE characters SET name_th = 'ควีนเซอร์นี่ โจชัว' WHERE slug = 'Joshua2';

-- R
UPDATE characters SET name_th = 'ราเชล เชฟฟิลด์' WHERE slug = 'Rachel';
UPDATE characters SET name_th = 'ราคิเซีย' WHERE slug = 'Rakicia';
UPDATE characters SET name_th = 'ราล์ฟ' WHERE slug = 'Ralph';
UPDATE characters SET name_th = 'รามิโร' WHERE slug = 'Ramiro';
UPDATE characters SET name_th = 'ราสเซล' WHERE slug = 'Racel';
UPDATE characters SET name_th = 'เรเวน' WHERE slug = 'Raven';
UPDATE characters SET name_th = 'รีปเปอร์ ซาริเอล' WHERE slug = 'Sariel2';
UPDATE characters SET name_th = 'รีเบคก้า' WHERE slug = 'Rebecca';
UPDATE characters SET name_th = 'เร็คเลส เอมิเลีย' WHERE slug = 'EmiliaLunatic';
UPDATE characters SET name_th = 'เรสคิวไนท์' WHERE slug = 'RescueKnight';
UPDATE characters SET name_th = 'เรสคิวออฟฟิเซอร์ โรมิน่า' WHERE slug = 'RominaRare';
UPDATE characters SET name_th = 'ริสกี้' WHERE slug = 'Risky';
UPDATE characters SET name_th = 'ร็อบ เคลเมนส์' WHERE slug = 'RobClemens';
UPDATE characters SET name_th = 'โรมิน่า' WHERE slug = 'Romina';
UPDATE characters SET name_th = 'โรเนร่า' WHERE slug = 'Ronera';
UPDATE characters SET name_th = 'โรซ่า' WHERE slug = 'Rosa';
UPDATE characters SET name_th = 'โรส เดอะสปิริท' WHERE slug = 'Spirit';
UPDATE characters SET name_th = 'โรซี่' WHERE slug = 'Rosie';
UPDATE characters SET name_th = 'รอยัลการ์ด เดลฟิน่า' WHERE slug = 'DelfinaRare';
UPDATE characters SET name_th = 'รูเบียน่า' WHERE slug = 'EileenRare';
UPDATE characters SET name_th = 'รีเจนท์ คาเอล' WHERE slug = 'KaelRare2';

-- S
UPDATE characters SET name_th = 'ซากุระ' WHERE slug = 'SakuraRare';
UPDATE characters SET name_th = 'ซากุระ ฮิเมะ' WHERE slug = 'Sakura';
UPDATE characters SET name_th = 'ซาริเอล' WHERE slug = 'Sariel';
UPDATE characters SET name_th = 'สแคเวนเจอร์ เยกาเนห์' WHERE slug = 'Yeganeh2';
UPDATE characters SET name_th = 'เซเลเน่' WHERE slug = 'Selane';
UPDATE characters SET name_th = 'เซลวา' WHERE slug = 'Selva';
UPDATE characters SET name_th = 'ผู้บัญชาการกองเวทมนตร์ โดโลเรส' WHERE slug = 'Dobaselrane';
UPDATE characters SET name_th = 'ซอลฮวา' WHERE slug = 'Seolhwa';
UPDATE characters SET name_th = 'จ่า บาร์รอล' WHERE slug = 'Barrelrare';
UPDATE characters SET name_th = 'ชารอน เดอะเซจ' WHERE slug = 'Sharon2';
UPDATE characters SET name_th = 'เชอร์รี่' WHERE slug = 'Sherry';
UPDATE characters SET name_th = 'เซียร่า โรส' WHERE slug = 'SierraLosPC';
UPDATE characters SET name_th = 'ซิลาเอน' WHERE slug = 'Ziz2';
UPDATE characters SET name_th = 'ซิลเวอร์แฟลช ลินน์' WHERE slug = 'LynnRare';
UPDATE characters SET name_th = 'ซิริอัส' WHERE slug = 'hknight';
UPDATE characters SET name_th = 'สไนเปอร์ เบอร์เนลลี' WHERE slug = 'GraceSniper';
UPDATE characters SET name_th = 'สโนว์เฟลก แบร์เธ่ แอนด์ ชาร์ลส์' WHERE slug = 'BertheIce';
UPDATE characters SET name_th = 'สโนว์เฟลก เชอร์ลิน' WHERE slug = 'SherlinICE';
UPDATE characters SET name_th = 'สโนว์เฟลก มอนโตโร' WHERE slug = 'IceMontoro';
UPDATE characters SET name_th = 'โซโฮ' WHERE slug = 'Soho';
UPDATE characters SET name_th = 'โซโฮ เดอะวินด์' WHERE slug = 'SohoFighter';
UPDATE characters SET name_th = 'ทหารเมืองรีโบลดูซ์' WHERE slug = 'Soldier';
UPDATE characters SET name_th = 'โซรัง' WHERE slug = 'Sorang';
UPDATE characters SET name_th = 'ซอร์ชา' WHERE slug = 'Sorscha';
UPDATE characters SET name_th = 'โซโซ' WHERE slug = 'Soso';
UPDATE characters SET name_th = 'สปาย โอลิเวีย' WHERE slug = 'SpyOlivia';
UPDATE characters SET name_th = 'ประธานนักเรียน ลูดิน' WHERE slug = 'SLudin';
UPDATE characters SET name_th = 'ผู้บัญชาการสูงสุด คาโน่' WHERE slug = 'Kano2Rare';
UPDATE characters SET name_th = 'ซิลเวสเทีย' WHERE slug = 'Sylvestia';

-- T
UPDATE characters SET name_th = 'ทิบูรอน' WHERE slug = 'Tiburon';
UPDATE characters SET name_th = 'ทอม' WHERE slug = 'Tom';

-- V
UPDATE characters SET name_th = 'วาเลเรีย' WHERE slug = 'Valleria';
UPDATE characters SET name_th = 'วาเลเรีย เวนเดตต้า' WHERE slug = 'Vendetta';
UPDATE characters SET name_th = 'แวน' WHERE slug = 'Van';
UPDATE characters SET name_th = 'วาเนสซ่า' WHERE slug = 'Vanessa';
