UPDATE characters SET bio_th = 'THAI_TEXT' WHERE slug = 'SLUG';
UPDATE characters SET bio_th = 'ในวันที่ Orden พ่ายแพ้ พระเจ้าทรงรู้อยู่แล้วว่า Orden อาจฟื้นคืนชีพได้อีกครั้ง จึงได้ผนึกพลังของพระองค์เองไว้ลึกภายใน Occulta Fortress และบัดนี้เมื่อพลังของ Orden เริ่มทวีความเข้มแข็งขึ้น หญิงลึกลับนาม Aclla ก็ได้ปรากฏตัวขึ้นจากห้วงลึกของ Occulta Fortress' WHERE slug = 'Aclla';
UPDATE characters SET bio_th = 'Adelina อดีตกัปตันโจรสลัด เธอกำลังตามหาคนทรยศที่สังหารเพื่อนร่วมทางของเธอระหว่างเดินทางสู่ทวีปใหม่ เธอมีพลังโจมตีปานกลางแต่ความเร็วในการโจมตีสูง ท่าต่อสู้หนึ่งของเธอช่วยให้เธอใช้ดาบและปืนพร้อมกันได้' WHERE slug = 'Adelina';
UPDATE characters SET bio_th = 'ธิดาของขุนนางผู้ขึ้นใหม่แห่ง Vespanola เธอได้รับตำแหน่งพลเรือเอกที่อายุน้อยที่สุดด้วยผลงานในสมรภูมิทางทะเลและการรบทางน้ำอีกหลายครั้ง เธอถูกส่งไปประจำการในกองเรือพิเศษเพื่อสำรวจ Castilla' WHERE slug = 'Adriana';
UPDATE characters SET bio_th = 'นักขโมยชั้นยอดผู้สร้างความปั่นป่วนทั่ว Illier ผู้คนคิดว่าเธอเป็นคู่แข่งกับ White Wolf แต่ในความเป็นจริงทั้งคู่ทำงานร่วมกันมาเป็นเวลานาน ทุกอย่างเกี่ยวกับเธอล้วนเป็นปริศนา ไม่มีใครรู้ชื่อ อายุ หรือที่มาของเธอ' WHERE slug = 'Eileen';
UPDATE characters SET bio_th = 'นักบวชน้ำที่ถูกพบในสภาพหลับใหลอยู่ในทะเลสาบแห่ง Altria โบราณ กล่าวกันว่า Lada ได้พาเธอออกมาจากทะเลสาบเพื่อติดตาม Orden เธอขี้เกียจและเชื่องช้าอย่างยิ่ง ซึ่งเป็นสิ่งที่ Aclla ไม่ชอบเป็นอย่างยิ่ง...' WHERE slug = 'Aisha';
UPDATE characters SET bio_th = 'หนึ่งในห้าของ Astarte ผู้รับใช้ Star Guardian นาม Atlas เขารอดชีวิตจากการโจมตีของโจรสลัดลึกลับตั้งแต่ยังเป็นเด็ก และเติบโตขึ้นใน Ailis ในฐานะเด็กกำพร้า Atlas ผู้สังเกตเห็นสายตาอันเฉียบแหลมและความสนใจด้านการยิงปืนของ Aither จึงมอบชีวิตใหม่ให้เขาในฐานะ Astarte' WHERE slug = 'Aether';
UPDATE characters SET bio_th = 'Alejandro ชาวประมงแห่ง Coimbra เขาเคยพยายามจับปลาหมึกยักษ์มาแล้วครั้งหนึ่ง มีพลังโจมตีสูงและ HP จำนวนมาก ถนัดการใช้ Great Sword และ Polearm' WHERE slug = 'Alejandro';
UPDATE characters SET bio_th = 'ธิดาคนที่สองของ Marquis Illier Shausen ปฏิบัติหน้าที่เป็นเจ้าหน้าที่ปฏิบัติการของกระทรวง Illier และทำหน้าที่เป็นเสนาธิการของขุนศึกคนใหม่ Evora เพื่อความก้าวหน้าและการเปลี่ยนแปลงของชาติ เธอไม่เพียงแค่เฉียบแหลมและฉลาด แต่ยังมีอุปนิสัยที่เข้มแข็งและเด็ดเดี่ยวอีกด้วย' WHERE slug = 'Amy';
UPDATE characters SET bio_th = 'André Janzur นักออกแบบผู้โด่งดังที่สุดทั้งในดินแดนมาตุภูมิและทวีปใหม่ เขายังเป็นนักสู้รอบด้านที่เลือกใช้ rapier เป็นอาวุธประจำกาย' WHERE slug = 'Andre';
UPDATE characters SET bio_th = 'ผู้พิพากษาฝึกหัดจาก Calum Gradio แห่ง Armonia เธอถูกส่งมอบและเลี้ยงดูโดยคริสตจักรตามคำขอของ White Watcher ผู้ซึ่งเป็นทั้งเพื่อนสนิทและผู้ถูกพิพากษาในช่วงการทดสอบของ Seraph ในยุค Empyrium เธอสืบทอดความว่องไวและความแข็งแกร่งจากพ่อแม่ผู้เป็น White Watcher พร้อมกับเวทมนตร์ศักดิ์สิทธิ์อันทรงพลัง' WHERE slug = 'Angelic';
UPDATE characters SET bio_th = 'หลานสาวของ Jack Angie มีความสามารถในการใช้คำสั่งวาง Trap และก่อสร้าง แต่ไม่สามารถโจมตีตามปกติได้' WHERE slug = 'Angie';
UPDATE characters SET bio_th = 'Ania สูญเสียพ่อแม่ไปในเหตุระเบิดที่ Errac ความเศร้าและความสูญเสียทั้งหมดหล่นจมลึกอยู่ภายใน จนวันหนึ่งมีชายคนหนึ่งมาที่ Errac และกล่าวว่า "ขอโทษ..." และในทันใดนั้นความเศร้าที่ถูกกักเก็บไว้ก็ระเบิดออกมา หลายปีต่อมา Ania และ Nar ได้กลายเป็นนักรบของเมือง' WHERE slug = 'Ania';
UPDATE characters SET bio_th = 'นักบุญแห่ง Armonia ในยุคปัจจุบัน แต่เดิมเธอเป็นเพียงเด็กสาวธรรมดา แต่หลังจาก Ornella จากไป เธอได้กลายเป็นนักบุญ เธอเป็นเพื่อนของ Sirius และ Cepheus' WHERE slug = 'Anies';
UPDATE characters SET bio_th = 'อดีตผลผลิตจากการทดลองชีวภาพของ Montoro และ Truman ที่หลบหนีออกมาจากห้องปฏิบัติการใต้ดินของ Truman เธอพยายามโคลนนิ่ง Hamaan จาก Errac แต่สามารถโคลนได้เพียงครึ่งเดียว ทิ้งรอยแผลเป็นไว้ในตัวเธอเอง' WHERE slug = 'Anita';
UPDATE characters SET bio_th = 'สัตว์ประหลาดที่ถูกสร้างขึ้นจากการทดลองของ Montoro และ Truman หลังจากการสิ้นชีพของ Montoro เธอถูกทอดทิ้งจนกระทั่ง Stratavista ค้นพบเธอ' WHERE slug = 'Ankita';
UPDATE characters SET bio_th = 'ชายผู้ต่อสู้อย่างหนักเพื่อปกป้อง Twisted Armonia จากการล่มสลายและช่วยเหลือผู้คนของเขา' WHERE slug = 'Van2';
UPDATE characters SET bio_th = 'นักดาบหญิงลึกลับที่เดินทางมาจากหมู่เกาะทางตะวันออกไกล เพื่อทดสอบขีดจำกัดของทักษะดาบ Asoka ผู้เย็นชาและมีศักดิ์ศรีสูง ไม่เคยแสดงความเมตตาต่อศัตรูของเธอ' WHERE slug = 'Asoka';
UPDATE characters SET bio_th = 'ชายลึกลับผู้ทำงานให้กับองค์กรลับของรัฐใน Coria เขาแสดงความสนใจอย่างยิ่งในกิจการต่างประเทศ ครอบครองพลังแห่ง Hwoarang Spirits ซึ่งสามารถเพิ่มพลังโจมตีของเขาได้' WHERE slug = 'Backho';
UPDATE characters SET bio_th = 'นักล่าค่าหัวผู้พเนจร นับตั้งแต่หัวหน้าโจรสลัดผู้โด่งดัง Captain Bernardo ได้เสียชีวิต ลูกน้องของเขาก็กระจัดกระจายออกไปใช้ชีวิตของตนเอง และ Bane ยังคงใช้ชีวิตเป็นนักล่าค่าหัวต่อไป' WHERE slug = 'Bane';
UPDATE characters SET bio_th = 'ผู้บัญชาการของกองทัพ Illier ในช่วงเวลาของ Rescue Knights เธอตกอยู่ในความสิ้นหวังเมื่อ Ophelia และ Melissa ที่เสียสละชีวิตเพื่อช่วยเธอและประชาชนในระหว่างการบุกเบิกพื้นที่ Snowfield ไม่ได้รับการยอมรับในผลงานของพวกเขา' WHERE slug = 'NatalieRare';
UPDATE characters SET bio_th = 'Barrel นักแม่นปืนชื่อดังแห่ง Coimbra เป็นทหารผู้ซื่อสัตย์ มี DEX สูงและพลังโจมตีสูง' WHERE slug = 'Barrel';
UPDATE characters SET bio_th = 'อดีตโจรสลัดผู้หันมาเป็นพ่อครัว เขาเคยได้ยินเกี่ยวกับวัตถุดิบแปลกใหม่ในทวีปใหม่และกลายเป็นพ่อครัวประจำเรือเพื่อเดินทางไปที่นั่น' WHERE slug = 'PanfiloBattle';
UPDATE characters SET bio_th = 'Idge เป็นช่างตีเหล็กผู้เชี่ยวชาญอย่างยิ่งจาก Auch เธอสามารถใช้ Great Sword และ Polearm ได้' WHERE slug = 'IdgeBattle';
UPDATE characters SET bio_th = 'ในฐานะวีรบุรุษชื่อดังจากสงครามในมาตุภูมิ Claude เป็นนักรบผู้ยอดเยี่ยมที่มีพลังโจมตีสูง DEF และ HP สูง เขามาพร้อมกับ Job Skill ที่เพิ่มความสามารถให้กับทีม' WHERE slug = 'ClaudeY';
UPDATE characters SET bio_th = 'เจ้าหญิงองค์ที่สามแห่ง Ice Realm ต่างจากพี่สาวสองคนที่เย็นชาและฉลาดหลักแหลม Becky เป็นคนร่าเริงและมีบุคลิกเต็มเปี่ยม' WHERE slug = 'Becky';
UPDATE characters SET bio_th = 'Bedel นักแม่นปืนผู้เคยรับใช้ในหน่วยเดียวกับ Barrol เขาก็สูญเสียภรรยาและลูกๆ ไปในเหตุการณ์ที่ Bristia เช่นกัน' WHERE slug = 'Bedel';
UPDATE characters SET bio_th = 'มันถูกพบครั้งแรกขณะยังมีชีวิตอยู่ในห้วงลึกของ Tierra de los Muertos โดยหน่วยลาดตระเวนแนวหน้าของ Vespanola เมื่อ 300 ปีก่อน หลังจากที่มันก่อความพินาศ มันดูเหมือนจะถูกปราบโดยกลุ่มผู้เชี่ยวชาญการต่อสู้ที่ถูกส่งไปตามคำขอของเจ้าเมือง Cividade' WHERE slug = 'Behemoth';
UPDATE characters SET bio_th = 'หญิงลึกลับที่ปรากฏตัวขึ้นมาโดยไม่มีที่มา สามารถสลับสับเปลี่ยนระหว่างธาตุทั้งสี่ได้พร้อมกัน' WHERE slug = 'Belith';
UPDATE characters SET bio_th = 'Grace Bernelli เป็นสาวสวยผู้เป็นที่นิยม เธอถูกคัดเลือกเข้าร่วมหน่วยบุกเบิกด้วยทักษะการยิงปืนอันยอดเยี่ยมของเธอ' WHERE slug = 'Grace';
UPDATE characters SET bio_th = 'Berthe เป็นลูกสาวของครอบครัวผู้มีเกียรติแห่ง Armonia เธอมีสัตว์เลี้ยงชื่อ Charles ซึ่งเป็นตุ๊กตาผ้าที่มีชีวิต Charles มักพูดในสิ่งที่ Berthe รู้สึกจริงๆ และบางครั้งก็ควบคุมตัวเองไม่ได้' WHERE slug = 'Berthe';
UPDATE characters SET bio_th = 'มือปืนผู้เชี่ยวชาญ พ่อของเธอถูกสังหารในเหตุการณ์สังหารหมู่ที่ Kielce ตั้งแต่เธอยังเด็ก เธอจึงฝึกฝนอย่างหนัก โดยเชื่อว่าทักษะที่พ่อสอนมาจะช่วยชีวิตผู้คนได้มากมาย' WHERE slug = 'Bianca';
UPDATE characters SET bio_th = 'มหาปุโรหิตแห่ง Naval of Blood ผู้ที่อุทิศชีวิตให้กับ Navy จะกลายเป็นปุโรหิตของ Navy และมหาปุโรหิตคือผู้นำสูงสุดของ Navy และผู้ที่เข้าถึงวิถีแห่ง Blood' WHERE slug = 'Kano2';
UPDATE characters SET bio_th = 'Ludin เป็นผู้อาวุโสที่ได้รับความเคารพในหมู่ Mages of the Mystical Order of Phalanx เขาได้ฝึกฝนเวทมนตร์ไฟจนถึงขีดสุด' WHERE slug = 'BLudin';
UPDATE characters SET bio_th = 'หญิงลึกลับที่ปรากฏตัวในหมู่บ้านรกร้าง ไม่มีใครรู้ที่มาของเธอ แต่ฝีมือดาบของเธอนั้นไม่มีใครเทียบได้' WHERE slug = 'Brigitte';
UPDATE characters SET bio_th = 'Brunie เป็นสาวจาก Auch ที่ฝันอยากเป็นนักแม่นปืน เธอชื่นชม Barrol และมุ่งมั่นที่จะฝึกฝนตนเองให้เก่งเท่ากับเขา' WHERE slug = 'Brunie';
UPDATE characters SET bio_th = 'นักสู้แข็งแกร่งจากแดนตะวันออกผู้ฝึกศิลปะการต่อสู้โบราณ เขาตามหาคู่ต่อสู้ที่คู่ควรเพื่อทดสอบความแข็งแกร่งของตนเอง' WHERE slug = 'Bryan';
UPDATE characters SET bio_th = 'Warlock — พวกเขาโจมตีด้วยการผสมผสานระหว่างเวทมนตร์รุกรานและเวทมนตร์ธาตุที่ทรงพลัง การโจมตีแบบวงกว้างอันแข็งแกร่งของพวกเขานำทางในสนามรบและช่วยเหลือสมาชิกในครอบครัวคนอื่นๆ' WHERE slug = 'Warlock';
UPDATE characters SET bio_th = 'Fighter — พวกเขาต่อสู้อยู่แนวหน้าและสามารถใช้อาวุธได้หลากหลายประเภท พวกเขาเป็นตัวละครหลักของทุก MCC หรือ Squad' WHERE slug = 'Fighter';
UPDATE characters SET bio_th = 'Musketeer — พวกเขามีระยะโจมตีที่ไกลที่สุดในบรรดาตัวละครพื้นฐานทั้งหมด พร้อมทักษะการยิงที่ทรงพลัง' WHERE slug = 'Musketeer';
UPDATE characters SET bio_th = 'Scout — ตัวละครที่สำคัญที่สุดในการเล่นแบบกลุ่ม พวกเขามีความสามารถพิเศษในการฟื้นฟู HP ให้กับสมาชิกในครอบครัว' WHERE slug = 'Scout';
UPDATE characters SET bio_th = 'Wizard — พวกเขาใช้เวทมนตร์อันทรงพลังที่สามารถสร้างความเสียหายให้กับศัตรูหลายตัวพร้อมกัน พวกเขามีค่า INT สูงที่สุดในบรรดาตัวละครทั้งหมด' WHERE slug = 'Wizard';
UPDATE characters SET bio_th = 'THAI_TEXT' WHERE slug = 'SLUG';
UPDATE characters SET bio_th = 'Adriana วัยเยาว์ที่เข้าร่วมโครงการนักเรียนนายร้อย เธอฝึกฝนอย่างหนักเพื่อเป็นพลเรือเอกเหมือนตัวเองในอนาคต' WHERE slug = 'CadetAdriana';
UPDATE characters SET bio_th = 'Amy ในวัยนักเรียนนายร้อย ก่อนที่เธอจะกลายเป็นเสนาธิการ แม้ในวัยเยาว์ ความคิดที่เฉียบแหลมของเธอก็เห็นได้ชัดอยู่แล้ว' WHERE slug = 'AmyRare';
UPDATE characters SET bio_th = 'Elisa วัยเยาว์ในช่วงเวลาที่เป็นนักเรียนนายร้อย ต่อมาเธอจะกลายเป็นผู้รักษาและผู้สนับสนุนที่เชี่ยวชาญ' WHERE slug = 'Elisa';
UPDATE characters SET bio_th = 'Leonele ในช่วงการฝึกเป็นนักเรียนนายร้อย ความสามารถในการยิงที่เหนือกว่าคนอื่นของเธอนั้นเห็นได้ชัดแม้ในวัยนักเรียน' WHERE slug = 'CLeonele';
UPDATE characters SET bio_th = 'Rob ในช่วงวัยนักเรียนนายร้อย ทักษะการยิงของเขาโดดเด่นเป็นอย่างมากตั้งแต่อายุยังน้อย' WHERE slug = 'CadetRob';
UPDATE characters SET bio_th = 'Caisse มือปืนจากกองทัพ Illier เธอเชี่ยวชาญในการต่อสู้ระยะไกลด้วยอาวุธปืนหลากหลายชนิด' WHERE slug = 'Kess';
UPDATE characters SET bio_th = 'Calyce ราชินีแห่ง crossbow เธอสามารถใช้ crossbow ได้ทั้งสองมือ เคยเข้าร่วมการแข่งขัน crossbow และชนะอย่างง่ายดาย' WHERE slug = 'Calyce';
UPDATE characters SET bio_th = 'ด้านมืดของ Ornella หลังจากถูกครอบงำด้วยเวทมนตร์มืด เธอได้รับพลังเวทมนตร์อันมหาศาล แต่สูญเสียบุคลิกภาพดั้งเดิมไป' WHERE slug = 'OrnellaBlack';
UPDATE characters SET bio_th = 'Claire ที่เชี่ยวชาญด้านการรบด้วยปืนใหญ่ ทักษะอาวุธหนักของเธอนั้นไม่มีใครเทียบได้ในสนามรบ' WHERE slug = 'ClairCN';
UPDATE characters SET bio_th = 'Carmen หญิงลึกลับที่ปรากฏตัวขึ้นมาจากไหนก็ไม่รู้ เธอใช้ปืนไรเฟิลหนักด้วยความแม่นยำอันน่าสะพรึงกลัว' WHERE slug = 'Karmen';
UPDATE characters SET bio_th = 'นักรบหญิงผู้ใช้อาวุธประจำยาวด้วยพลังอันทำลายล้าง เธอปกป้องผู้อ่อนแอและต่อสู้เพื่อความยุติธรรม' WHERE slug = 'Cassandra';
UPDATE characters SET bio_th = 'Catherine Torsche นักประดิษฐ์อัจฉริยะจาก Torsche Mansion เธอสร้างอุปกรณ์และไอเทมสนับสนุนต่างๆ มากมาย' WHERE slug = 'CatherineREAL';
UPDATE characters SET bio_th = 'Catherine ที่เชี่ยวชาญการต่อสู้แบบ DEX เธอสามารถใช้ทั้งอาวุธปืนและอาวุธระยะประชิดได้อย่างเท่าเทียมกัน' WHERE slug = 'CatherineDEX';
UPDATE characters SET bio_th = 'Catherine ที่เชี่ยวชาญเวทมนตร์แบบ INT เธอถ่ายทอดความอัจฉริยะของตนสู่การโจมตีด้วยธาตุอันทรงพลัง' WHERE slug = 'CatherineINT';
UPDATE characters SET bio_th = 'Catherine ที่เชี่ยวชาญการต่อสู้แบบ STR เธอใช้อาวุธหนักด้วยพลังที่น่าประหลาดใจ' WHERE slug = 'CatherineSTR';
UPDATE characters SET bio_th = 'Catherine Torsche นักประดิษฐ์ผู้ปราดเปรื่อง เธอต่อสู้โดยใช้สิ่งประดิษฐ์และเครื่องจักรที่เธอสร้างขึ้นเอง' WHERE slug = 'CatherineTorsche';
UPDATE characters SET bio_th = 'Cecille นักสู้ที่เชี่ยวชาญ crossbow ความแม่นยำและความเร็วของเธอกับ crossbow นั้นเป็นตำนาน' WHERE slug = 'Sesil';
UPDATE characters SET bio_th = 'Charlotte นักเวทธาตุไฟ เธอค้นพบความสามารถพิเศษของตนกับเวทมนตร์ไฟตั้งแต่อายุยังน้อย' WHERE slug = 'Charlotrare';
UPDATE characters SET bio_th = 'Cherlyn นักเวทหนุ่มสาวที่เชี่ยวชาญเวทมนตร์ไฟและคาถาเวทมนตร์' WHERE slug = 'Sherlin';
UPDATE characters SET bio_th = 'Veronif หัวหน้านักเล่นแร่แปรธาตุ ผู้เชี่ยวชาญด้านการเล่นแร่แปรธาตุที่เก่งที่สุดในทวีปทั้งใบ' WHERE slug = 'BerroniffRare';
UPDATE characters SET bio_th = 'Chloe ผู้ใช้พลังน้ำแข็งลึกลับ อุปนิสัยเย็นชาของเธอสอดคล้องกับธาตุที่เธอถนัด' WHERE slug = 'Chloe';
UPDATE characters SET bio_th = 'Christina ผู้เชี่ยวชาญอาวุธหนัก เธอสามารถจัดการปืนใหญ่ได้อย่างง่ายดายแม้ร่างกายจะเล็ก' WHERE slug = 'Cristina';
UPDATE characters SET bio_th = 'นักดาบหญิงจากแดนตะวันออก เทคนิคดาบอันสง่างามของเธอนั้นทั้งงดงามและอันตราย' WHERE slug = 'Chungha';
UPDATE characters SET bio_th = 'Ciel นักศิลปะการต่อสู้ที่ต่อสู้ด้วยหมัดเปล่า การโจมตีที่รวดเร็วและท่วงท่าคล่องแคล่วทำให้เขาเป็นนักสู้ที่น่าเกรงขาม' WHERE slug = 'Ciel';
UPDATE characters SET bio_th = 'ทหารราบแห่ง City of Auch พวกเขาทำหน้าที่เป็นกำลังหลักของกองกำลังป้องกันเมือง' WHERE slug = 'Infantry';
UPDATE characters SET bio_th = 'Claire นักรบผู้มีความสามารถจาก Auch เธอเชี่ยวชาญทั้ง Great Sword และปืนใหญ่' WHERE slug = 'Clair';
UPDATE characters SET bio_th = 'Claude นักรบในตำนานและวีรบุรุษ เขาเชี่ยวชาญอาวุธประชิดหลายประเภทและมีสถิติทางกายภาพสูง' WHERE slug = 'Claude';
UPDATE characters SET bio_th = 'Coa นักศิลปะการต่อสู้จาก Errac เธอต่อสู้ด้วยเทคนิคการต่อสู้แบบมือเปล่าโบราณ' WHERE slug = 'Coa';
UPDATE characters SET bio_th = 'Code Name C — Chloe เวอร์ชันที่มีพลังน้ำแข็งขั้นสูงและการโจมตีที่ใช้ INT เป็นฐาน' WHERE slug = 'Chloe2';
UPDATE characters SET bio_th = 'Code Name J — ปฏิบัติการลึกลับที่มีพลังยิงหนัก' WHERE slug = 'CodeNameJ';
UPDATE characters SET bio_th = 'Code Name L — Leona ที่กลับมาพร้อมทักษะดาบและความสามารถในการต่อสู้ที่เพิ่มขึ้น' WHERE slug = 'Leona2';
UPDATE characters SET bio_th = 'Code Name T — Tora พร้อมเทคนิคการต่อสู้ด้วย javelin ที่ได้รับการพัฒนาแล้ว' WHERE slug = 'Tora2';
UPDATE characters SET bio_th = 'Code Name V — Veatrice ที่เสริมพลังด้วยเวทมนตร์สายฟ้าอันทรงพลัง' WHERE slug = 'Veatrice2';
UPDATE characters SET bio_th = 'Coimbra Trooper ทหารผู้ซื่อสัตย์แห่ง Coimbra พวกเขาปกป้องเมืองด้วยดาบ โล่ และอาวุธประจำยาว' WHERE slug = 'Trooper';
UPDATE characters SET bio_th = 'Conductor Rio นักดนตรีผู้ใช้พลังแห่งดนตรีสนับสนุนพันธมิตรในการต่อสู้' WHERE slug = 'RioRare';
UPDATE characters SET bio_th = 'Consul Dietrich เจ้าหน้าที่ระดับสูงและนักดาบผู้เชี่ยวชาญ' WHERE slug = 'DiertrichRare';
UPDATE characters SET bio_th = 'Cruise นักดาบที่แสวงหาการแก้แค้น คมดาบของเขาแบกรับน้ำหนักของอดีต' WHERE slug = 'Cruz';
UPDATE characters SET bio_th = 'Crusader Daria นักรบศักดิ์สิทธิ์ผู้ต่อสู้เพื่อปกป้องผู้บริสุทธิ์' WHERE slug = 'DariaRare';
UPDATE characters SET bio_th = 'Cutie Claire เวอร์ชันน่ารักของ Claire ที่ยังคงสร้างความเสียหายได้มากด้วยปืนใหญ่ของเธอ' WHERE slug = 'ClairCG';
UPDATE characters SET bio_th = 'Daisy ผู้ใช้ crossbow ร่าเริงแจ่มใส บุคลิกสดใสของเธอตัดกับความแม่นยำอันน่าสะพรึงกลัว' WHERE slug = 'Daisy';
UPDATE characters SET bio_th = 'THAI_TEXT' WHERE slug = 'SLUG';
UPDATE characters SET bio_th = 'ตัวละครลึกลับใหม่ที่มีทักษะมีดพกยอดเยี่ยม' WHERE slug = 'Danev';
UPDATE characters SET bio_th = 'Daria นักรบหญิงที่ต่อสู้ด้วยทั้งดาบและปืนไรเฟิล เธอทุ่มเทเพื่อปกป้องประชาชน' WHERE slug = 'Daria';
UPDATE characters SET bio_th = 'Delfina นักรบระดับเอลีทที่มีทักษะการต่อสู้อันยอดเยี่ยม' WHERE slug = 'Delfina';
UPDATE characters SET bio_th = 'Diluca นักเวทย์ผู้เชี่ยวชาญด้านคัมภีร์เวทย์และเวทย์มนตร์สนับสนุน' WHERE slug = 'Diluca';
UPDATE characters SET bio_th = 'Designer Karjalainen นักออกแบบแฟชั่นที่เชี่ยวชาญการต่อสู้ด้วยดาบ rapier เช่นกัน' WHERE slug = 'Mi2';
UPDATE characters SET bio_th = 'Dietrich นักดาบฝีมือเยี่ยมผู้รับใช้ในกองทัพ ความทุ่มเทต่อหน้าที่ของเขาไม่มีใครเทียบได้' WHERE slug = 'Diertrichherberthe';
UPDATE characters SET bio_th = 'Divine Hammer Bryan, Bryan ผู้เชี่ยวชาญพลังศักดิ์สิทธิ์แห่งหมัดของตน หมัดของเขาแฝงไว้ด้วยพลังแห่งสวรรค์' WHERE slug = 'BryanRare';
UPDATE characters SET bio_th = 'Dolores นักเวทย์สายฟ้าผู้มีความรู้ลึกซึ้งด้านเวทย์ธาตุ' WHERE slug = 'Dolores';
UPDATE characters SET bio_th = 'Doom Slave นักรบแห่งความมืดผู้ถูกพันธนาการด้วยคำสาปโบราณ เขาต่อสู้ด้วยพลังอันมหาศาลแต่ต้องแลกด้วยราคาที่แสนสาหัส' WHERE slug = 'bknight';
UPDATE characters SET bio_th = 'Drachen อัศวินมังกรผู้ใช้ดาบและโล่ ความสามารถด้านการป้องกันของเขาเป็นที่เลื่องลือ' WHERE slug = 'Drachen';
UPDATE characters SET bio_th = 'Edward นักฟันดาบฝีมือดีผู้ต่อสู้ด้วยความสง่างามและแม่นยำ' WHERE slug = 'Eduardo';
UPDATE characters SET bio_th = 'Elisa เจ้าหน้าที่การแพทย์ผู้รักษาและสนับสนุนเพื่อนร่วมรบในสนามรบ' WHERE slug = 'ElisaOfficer';
UPDATE characters SET bio_th = 'Elizabeth นักเวทย์ธาตุผู้ทรงพลังที่บัญชาการพลังแห่งธรรมชาติ' WHERE slug = 'Elizabeth';
UPDATE characters SET bio_th = 'Ellie มือปืนแม่นยำผู้ใช้ปืนไรเฟิลหนัก การโจมตีระยะไกลของเธอนั้นน่าเกรงขาม' WHERE slug = 'Ellie';
UPDATE characters SET bio_th = 'Ellie Craig เวอร์ชันพัฒนาแล้วของ Ellie พร้อมเทคนิคปืนไรเฟิลหนักที่ปรับปรุงใหม่' WHERE slug = 'Ellie2';
UPDATE characters SET bio_th = 'Emilia Guliano นักเวทย์อเนกประสงค์ที่ทั้งรักษาและโจมตีได้ เธอใช้ไม้เท้าและ rosario' WHERE slug = 'Emilia';
UPDATE characters SET bio_th = 'Emilia the Sage, Emilia ผู้บรรลุจุดสูงสุดแห่งความรู้ทางเวทย์มนตร์' WHERE slug = 'EmiliaSage';
UPDATE characters SET bio_th = 'Empyrium Judith นักรบศักดิ์สิทธิ์ผู้ใช้อาวุธปลายทวน เธอต่อสู้ในนามของ Empyrium' WHERE slug = 'Judith';
UPDATE characters SET bio_th = 'Enforcer Anies, Anies ผู้เสริมพลังด้วยศิลปะการต่อสู้และความสามารถการรบแบบสวมเกราะ' WHERE slug = 'Anies2';
UPDATE characters SET bio_th = 'Erica นักเวทย์ธาตุผู้เชี่ยวชาญธาตุหลายชนิด' WHERE slug = 'Erica';
UPDATE characters SET bio_th = 'Eva Sharon นักเวทย์จากสถาบัน Auch เธอเชี่ยวชาญเวทย์มนตร์ประเภทไม้เท้า' WHERE slug = 'Sharon';
UPDATE characters SET bio_th = 'Evil นักเวทย์มืดผู้โอบรับศิลปะต้องห้าม เวทย์สายฟ้าของเธอทั้งงดงามและน่าเกรงขาม' WHERE slug = 'Evil';
UPDATE characters SET bio_th = 'Fenrir นักรบที่เกิดใหม่พร้อมพลังแห่งหมาป่าในตำนาน เธอใช้อาวุธทื่อด้วยพลังทำลายล้างอันน่าเกรงขาม' WHERE slug = 'Violet2';
UPDATE characters SET bio_th = 'Freesia นักดาบ sabre ผู้คล่องแคล่ว การเคลื่อนไหวอันงดงามของเธอซ่อนไว้ซึ่งการโจมตีที่อันตราย' WHERE slug = 'Freesia';
UPDATE characters SET bio_th = 'Freya นักรบ valkyrie ผู้สืบทอดมาจากตำนาน เธอต่อสู้ด้วย javelin และมีพลังธาตุ' WHERE slug = 'Valkyrie';
UPDATE characters SET bio_th = 'Friede นักดนตรีผู้ใช้พิณ lute เป็นทั้งเครื่องดนตรีและอาวุธ' WHERE slug = 'Freeday';
UPDATE characters SET bio_th = 'Garcia นักสู้แบบสองมือผู้ใช้ทั้งปืนพกและดาบ rapier ด้วยทักษะอันเชี่ยวชาญ' WHERE slug = 'Garcia';
UPDATE characters SET bio_th = 'Gaura นักรบใหม่ที่มีต้นกำเนิดลึกลับและความสามารถการต่อสู้อันยอดเยี่ยม' WHERE slug = 'Gaura';
UPDATE characters SET bio_th = 'Giltine เทพีแห่งความตายผู้ใช้เวทย์กำไลธาตุด้วยพลังอันน่าเกรงขาม' WHERE slug = 'Giltine';
UPDATE characters SET bio_th = 'Gracielo นักศิลปะการต่อสู้ผู้ขึ้นชื่อด้านความเร็วและความคล่องแคล่วอันน่าทึ่ง' WHERE slug = 'Gracielo';
UPDATE characters SET bio_th = 'Grandies นักรบผ่านศึกผู้มากประสบการณ์ ประสบการณ์จากการต่อสู้นับครั้งไม่ถ้วนทำให้เขาเป็นคู่ต่อสู้ที่น่าเกรงขามด้วยดาบและดาบสองมือ' WHERE slug = 'Grandies';
UPDATE characters SET bio_th = 'Grandma อย่าหลงเชื่อรูปลักษณ์ของเธอ เธอใช้ดาบสองมือด้วยความแข็งแกร่งและทักษะอันน่าประหลาดใจ' WHERE slug = 'Grandma';
UPDATE characters SET bio_th = 'Grutrude นักศิลปะการต่อสู้ที่เข้มแข็ง หมัดอันทรงพลังของเธอสามารถทะลุผ่านการป้องกันได้ทุกรูปแบบ' WHERE slug = 'Gurtrude';
UPDATE characters SET bio_th = 'Guardian Ania, Ania ผู้กลายเป็นนักรบผู้พิทักษ์ใช้ tonfa ด้วยความเร็วอันน่าเหลือเชื่อ' WHERE slug = 'Ania2';
UPDATE characters SET bio_th = 'Guardian Coa, Coa ผู้พัฒนาเป็นผู้พิทักษ์ทรงพลังพร้อมเทคนิค knuckle ที่ขั้นสูง' WHERE slug = 'CoaRare';
UPDATE characters SET bio_th = 'Guardian Lu, Lu ผู้เสริมพลังเป็นผู้พิทักษ์ผู้เชี่ยวชาญอาวุธเสี้ยวพระจันทร์' WHERE slug = 'LooRare';
UPDATE characters SET bio_th = 'Guardian Nar, Nar ผู้กลายเป็นนักรบผู้พิทักษ์สวมเกราะหนักและทักษะการต่อสู้ด้วยอาวุธเสี้ยวพระจันทร์' WHERE slug = 'NarRare';
UPDATE characters SET bio_th = 'Harriot Airheart นักบินผู้ชอบผจญภัยที่ต่อสู้ด้วยเทคนิคการรบอันเป็นเอกลักษณ์' WHERE slug = 'Airheart';
UPDATE characters SET bio_th = 'Hass Laburd นักรบใหม่ผู้ใช้ดาบสองมือด้วยความเชี่ยวชาญด้านการป้องกัน' WHERE slug = 'Hass';
UPDATE characters SET bio_th = 'Hector นักรบผ่านศึกผู้เชี่ยวชาญทั้งดาบและปืนลูกซอง รูปแบบการต่อสู้อันหลากหลายทำให้เขาปรับตัวได้ทุกสถานการณ์' WHERE slug = 'Hektor';
UPDATE characters SET bio_th = 'THAI_TEXT' WHERE slug = 'SLUG';
UPDATE characters SET bio_th = 'Heka นักศิลปะการต่อสู้ผู้ทรงพลังจากยุคโบราณ กำปั้นของเธอสิงสถิตพลังของเหล่าเทพเจ้า' WHERE slug = 'Heka';
UPDATE characters SET bio_th = 'Hellena นักธาตุวิทยาผู้เชี่ยวชาญที่สามารถใช้กำไลธาตุทั้งสี่พร้อมกันได้' WHERE slug = 'Hellena';
UPDATE characters SET bio_th = 'Hermes มือปืนผู้เชี่ยวชาญที่ใช้ปืนไรเฟิลหนัก ความเร็วและความแม่นยำของเขาไม่มีใครเทียบได้' WHERE slug = 'Hermes';
UPDATE characters SET bio_th = 'Heyran นักสู้ผู้ชำนาญการซุ่มโจมตี เชี่ยวชาญการต่อสู้ด้วยมีดสั้นและการจู่โจมแบบไม่ทันตั้งตัว' WHERE slug = 'Heyran';
UPDATE characters SET bio_th = 'Hildegard หญิงลึกลับผู้ต่อสู้ด้วยม้วนคาถาวิเศษที่มีพลังอำนาจอันน่าเหลือเชื่อ' WHERE slug = 'Hildegard';
UPDATE characters SET bio_th = 'Idge Imbrulia ช่างตีเหล็กผู้เก่งกาจที่สุดใน Auch เธอต่อสู้ด้วยอาวุธที่ตัวเองตีขึ้นมา ทั้ง Great Swords และ Polearms' WHERE slug = 'Idge';
UPDATE characters SET bio_th = 'Illusion นักสู้ดั่งภูตผีที่การแทงด้วย rapier แทบจะมองไม่เห็นด้วยตาเปล่า' WHERE slug = 'Illusion';
UPDATE characters SET bio_th = 'Ion นักเวทน้ำแข็งที่ดึงพลังจากธาตุแช่แข็ง เวทมนตร์อันเย็นชาของเธอสามารถแช่แข็งศัตรูได้ในพริบตา' WHERE slug = 'Ion';
UPDATE characters SET bio_th = 'Irawan นักมวยไทยจากดินแดนตะวันออก การเตะและการใช้เข่าอันทรงพลังของเขาเลื่องลือไปทั่ว' WHERE slug = 'Muathai';
UPDATE characters SET bio_th = 'Issac นักเวทผู้คร่ำหนังสือที่เชี่ยวชาญม้วนคาถาวิเศษและเวทมนตร์ช่วยเหลือ' WHERE slug = 'Isaac';
UPDATE characters SET bio_th = 'Isabel นักรบที่มีค่าสถิติสมดุลและความสามารถในการต่อสู้ที่หลากหลาย' WHERE slug = 'Isabel2';
UPDATE characters SET bio_th = 'JD นักดาบผู้อเนกประสงค์ที่สามารถใช้อาวุธมีคมได้หลากหลายประเภท' WHERE slug = 'JD';
UPDATE characters SET bio_th = 'Jina นักสู้ผู้เชี่ยวชาญที่มีเทคนิคการต่อสู้อันเป็นเอกลักษณ์' WHERE slug = 'Jina';
UPDATE characters SET bio_th = 'Josefina ผู้เชี่ยวชาญด้านสนับสนุนที่ช่วยเหลือเพื่อนร่วมทีมด้วยการรักษาและการเสริมพลัง' WHERE slug = 'Josefina';
UPDATE characters SET bio_th = 'Julia หญิงนักรบผู้ต่อสู้ด้วยความมุ่งมั่นและทักษะ' WHERE slug = 'Julia';
UPDATE characters SET bio_th = 'Julia Dorchner Julia เวอร์ชันพัฒนาแล้วที่มีความสามารถในการต่อสู้ที่ดียิ่งขึ้น' WHERE slug = 'Julia2';
UPDATE characters SET bio_th = 'Kael นักรบโดดเดี่ยวที่ต่อสู้ด้วยกำปั้น ศิลปะการต่อสู้ของเขาเป็นสิ่งที่เรียนรู้มาด้วยตนเอง' WHERE slug = 'Kael';
UPDATE characters SET bio_th = 'Kano นักบวชแห่ง Navy เขาถ่ายทอดพลังศักดิ์สิทธิ์ผ่านวิถีทางเวทมนตร์' WHERE slug = 'Kano';
UPDATE characters SET bio_th = 'Karin นักสู้ลึกลับผู้มีความสามารถพิเศษอันเป็นเอกลักษณ์' WHERE slug = 'Karin';
UPDATE characters SET bio_th = 'Catherine the Senior มารดาของตระกูล Torsche ภูมิปัญญาและพลังอำนาจของเธอนั้นอยู่เหนือการวัด' WHERE slug = 'KatherineSENIOR';
UPDATE characters SET bio_th = 'Keiri นักสู้สาวผู้มีศักยภาพอันยิ่งใหญ่' WHERE slug = 'Keyris';
UPDATE characters SET bio_th = 'Kurton นักรบผู้ผ่านศึกมามากมายพร้อมประสบการณ์การต่อสู้หลายปี' WHERE slug = 'Kurton';
UPDATE characters SET bio_th = 'Lady Knight หญิงนักรบผู้สูงศักดิ์ที่ต่อสู้ด้วยเกียรติและความงดงาม' WHERE slug = 'LadyKnight';
UPDATE characters SET bio_th = 'Leonele มือปืนผู้เชี่ยวชาญจากกองทัพ เก่งทั้งการใช้ปืนพกและปืนไรเฟิล' WHERE slug = 'Leonele';
UPDATE characters SET bio_th = 'Leona นักดาบหญิงผู้ดุดัน เทคนิคการใช้ดาบของเธอผสานพลังกับความงดงาม' WHERE slug = 'Leona';
UPDATE characters SET bio_th = 'Lisa นักเวทสาวผู้ศึกษาศาสตร์ลี้ลับ' WHERE slug = 'Lisa';
UPDATE characters SET bio_th = 'Lord Charles เจ้าผู้สูงศักดิ์ที่ต่อสู้เพื่อประชาชนของตนด้วยดาบในมือ' WHERE slug = 'LordCharles';
UPDATE characters SET bio_th = 'Lu นักศิลปะการต่อสู้จาก Errac ผู้ใช้อาวุธรูปจันทร์เสี้ยวอันเป็นเอกลักษณ์' WHERE slug = 'Loo';
UPDATE characters SET bio_th = 'Ludin นักเวทไฟจาก Mystical Order of Phalanx ความเชี่ยวชาญด้านไฟของเขานั้นยอดเยี่ยมเป็นพิเศษ' WHERE slug = 'Ludin';
UPDATE characters SET bio_th = 'Lucifer ปิศาจมืดผู้มีพลังอันยิ่งใหญ่ เพียงแค่การปรากฏตัวของเขาก็สร้างความหวาดกลัวให้แก่ศัตรู' WHERE slug = 'Lucifer';
UPDATE characters SET bio_th = 'Luna นักรบแสงจันทร์ผู้มีพลังลึกลับ' WHERE slug = 'Luna';
UPDATE characters SET bio_th = 'Lyndon สุภาพบุรุษนักสู้ที่ผสานความสง่างามเข้ากับทักษะการต่อสู้อันร้ายกาจ' WHERE slug = 'Lyndon';
UPDATE characters SET bio_th = 'M ผู้ปฏิบัติการลึกลับที่ไม่มีใครรู้จักตัวตน ทักษะการต่อสู้ของเธออยู่ในระดับสูงสุด' WHERE slug = 'M';
UPDATE characters SET bio_th = 'Magdalena นักรบศักดิ์สิทธิ์ผู้ต่อสู้ในนามของพระเจ้า' WHERE slug = 'Magdalena';
UPDATE characters SET bio_th = 'Marcella นักรบผู้สูงศักดิ์ที่มีเทคนิคการต่อสู้อันประณีต' WHERE slug = 'Marchetti';
UPDATE characters SET bio_th = 'Margherita นักรบจาก Old Continent ผู้ยึดมั่นในรูปแบบการต่อสู้แบบดั้งเดิม' WHERE slug = 'Margherita';
UPDATE characters SET bio_th = 'Maria หญิงสาวผู้มีความสามารถในการรักษาและจิตใจที่งดงาม' WHERE slug = 'Maria';
UPDATE characters SET bio_th = 'Mi นักออกแบบและนักสู้ด้วย rapier สุนทรียภาพทางศิลปะของเธอสะท้อนออกมาในสไตล์การต่อสู้' WHERE slug = 'Mi';
UPDATE characters SET bio_th = 'Mikhail นักรบผู้แข็งแกร่งจากดินแดนเหนือ สไตล์การต่อสู้หนักของเขาสามารถท่วมท้นคู่ต่อสู้ได้' WHERE slug = 'Mikhail';
UPDATE characters SET bio_th = 'Minerva เทพีแห่งปัญญาผู้ต่อสู้ด้วยสติปัญญาและพลังเวทมนตร์' WHERE slug = 'Minerva';
UPDATE characters SET bio_th = 'THAI_TEXT' WHERE slug = 'SLUG';
UPDATE characters SET bio_th = 'Moussa นักรบจากดินแดนอันไกลโพ้น สไตล์การต่อสู้อันเป็นเอกลักษณ์ของเขาทำให้ฝ่ายตรงข้ามตั้งตัวไม่ทัน' WHERE slug = 'Moussa';
UPDATE characters SET bio_th = 'Mr. Q สุภาพบุรุษลึกลับผู้ซ่อนความสามารถด้านการต่อสู้เอาไว้' WHERE slug = 'MrQ';
UPDATE characters SET bio_th = 'Nar นักรบจาก Errac ผู้ต่อสู้เพื่อปกป้องบ้านเกิดของตน เขากลายเป็นผู้พิทักษ์คู่กับ Ania' WHERE slug = 'Nar';
UPDATE characters SET bio_th = 'Natalie นายทหารหญิงผู้นำด้วยความกล้าหาญและต่อสู้ด้วยความมุ่งมั่น' WHERE slug = 'Natalie';
UPDATE characters SET bio_th = 'Navy Guard ทหารชั้นยอดแห่งกองทัพเรือ ผ่านการฝึกฝนทั้งการต่อสู้ระยะประชิดและระยะไกล' WHERE slug = 'NavyGuard';
UPDATE characters SET bio_th = 'Noel จิตวิญญาณผู้อ่อนโยนที่มีพลังเวทมนตร์อันทรงพลัง' WHERE slug = 'Noel';
UPDATE characters SET bio_th = 'Nana สาวน้อยร่าเริงที่มีความสามารถด้านการต่อสู้อย่างน่าประหลาดใจ' WHERE slug = 'Nana';
UPDATE characters SET bio_th = 'Octavia นักรบผู้สูงศักดิ์ที่ต่อสู้เพื่อเกียรติยศและหน้าที่' WHERE slug = 'Octavia';
UPDATE characters SET bio_th = 'Ornella อดีต Saint แห่ง Armonia เวทมนตร์ศักดิ์สิทธิ์ของเธอเคยเป็นพลังที่แข็งแกร่งที่สุดในแผ่นดิน' WHERE slug = 'Ornella';
UPDATE characters SET bio_th = 'Panfilo อดีตโจรสลัดผู้หันมาเป็นพ่อครัว เขาใช้ทักษะการทำอาหารได้มากพอๆ กับทักษะการต่อสู้' WHERE slug = 'Panfilo';
UPDATE characters SET bio_th = 'Penelope นักสู้ผู้เชี่ยวชาญที่มีทั้งความงดงามและพลังอำนาจ' WHERE slug = 'Penelope';
UPDATE characters SET bio_th = 'The Pirate Queen ราชินีแห่งท้องทะเล ชื่อเสียงของเธอหว่านความกลัวลงในหัวใจของทุกคนที่แล่นเรือ' WHERE slug = 'PirateKing';
UPDATE characters SET bio_th = 'Rashid นักรบจากดินแดนทะเลทราย เทคนิคดาบโค้งของเขาเป็นตำนาน' WHERE slug = 'Rashid';
UPDATE characters SET bio_th = 'Rey นักสู้หนุ่มที่มีศักยภาพซ่อนเร้นรอการปลดปล่อย' WHERE slug = 'Rey';
UPDATE characters SET bio_th = 'Regent Kael Kael ผู้ก้าวขึ้นมาเป็น Regent พร้อมศิลปะการต่อสู้ที่เพิ่มพูนขึ้น' WHERE slug = 'KaelRare2';
UPDATE characters SET bio_th = 'Resistance Caisse Caisse ผู้เข้าร่วมขบวนการต่อต้านพร้อมทักษะการใช้อาวุธปืนที่พัฒนาขึ้น' WHERE slug = 'Kess2';
UPDATE characters SET bio_th = 'Resistance Heyran Heyran ผู้ต่อสู้เพื่อขบวนการต่อต้านพร้อมเทคนิคการใช้มีดสั้นที่เพิ่มพูนขึ้น' WHERE slug = 'Heyran2';
UPDATE characters SET bio_th = 'Resistance JD JD ผู้ต่อสู้เพื่อขบวนการต่อต้านด้วยความเชี่ยวชาญในดาบหลากหลายรูปแบบ' WHERE slug = 'JD2';
UPDATE characters SET bio_th = 'Rio นักดนตรีและนักแสดง เขาใช้พลังแห่งดนตรีเพื่อสร้างแรงบันดาลใจและรักษา' WHERE slug = 'Rio';
UPDATE characters SET bio_th = 'Rob มือปืนผู้เชี่ยวชาญ กระสุนปืนไรเฟิลของเขาไม่เคยพลาดเป้า' WHERE slug = 'Rob';
UPDATE characters SET bio_th = 'Rosalind หญิงสูงศักดิ์ผู้มีพลังการรักษาและจิตใจอันอ่อนโยน' WHERE slug = 'Rosalind';
UPDATE characters SET bio_th = 'Rumin ปราชญ์ผู้รอบรู้ที่มีความรู้ลึกซึ้งด้านเวทมนตร์โบราณ' WHERE slug = 'Rumin';
UPDATE characters SET bio_th = 'Scarlet นักรบดุดันที่ดาบสีแดงของเธอประกาศการปรากฏตัวบนสนามรบ' WHERE slug = 'Scarlet';
UPDATE characters SET bio_th = 'Selena นักบวชหญิงแห่งแสงจันทร์ผู้มีพลังการรักษาอันศักดิ์สิทธิ์' WHERE slug = 'Selena';
UPDATE characters SET bio_th = 'Serene นักรบผู้สงบที่อารมณ์เยือกเย็นของเธอปิดซ่อนทักษะการต่อสู้อันร้ายกาจ' WHERE slug = 'Serene';
UPDATE characters SET bio_th = 'Shirin นักรบจากดินแดนตะวันออกที่มีเทคนิคการต่อสู้อันเป็นเอกลักษณ์' WHERE slug = 'Shirin';
UPDATE characters SET bio_th = 'Sierra นักสู้ผู้เชี่ยวชาญจากดินแดนชายขอบ สัญชาตญาณเอาตัวรอดของเธอเป็นเลิศ' WHERE slug = 'Sierra';
UPDATE characters SET bio_th = 'Sigmund นักรบนักปราชญ์ชื่อดังผู้ผสมผสานความรู้เข้ากับความเชี่ยวชาญด้านการต่อสู้' WHERE slug = 'Sigmund';
UPDATE characters SET bio_th = 'Simone นักสู้ผู้สง่างามที่การเคลื่อนไหวอันงดงามของเธอปิดบังการโจมตีอันร้ายกาจ' WHERE slug = 'Simone';
UPDATE characters SET bio_th = 'Symphony นักรบดนตรีผู้แปรพลังเสียงให้กลายเป็นการโจมตีอันทรงพลัง' WHERE slug = 'Symphony';
UPDATE characters SET bio_th = 'Sven นักรบทางเหนือผู้โด่งดังด้วยความอดทนและพลังอันไม่มีที่สิ้นสุด' WHERE slug = 'Sven';
UPDATE characters SET bio_th = 'Sol นักรบแห่งดวงอาทิตย์ผู้ดึงพลังจากพลังงานสุริยะ' WHERE slug = 'Sol';
UPDATE characters SET bio_th = 'Sothis สิ่งมีชีวิตแห่งสวรรค์ที่มีความสามารถด้านเวทมนตร์อิงดวงดาว' WHERE slug = 'Sothis';
UPDATE characters SET bio_th = 'Stella นักเวทมนตร์ดาวที่พลังจักรวาลของเธอส่องสว่างบนสนามรบ' WHERE slug = 'Stella';
UPDATE characters SET bio_th = 'Summer Natalie Natalie ในชุดฤดูร้อน ยังคงอันตรายเหมือนเดิมทุกประการ' WHERE slug = 'NatalieSummer';
UPDATE characters SET bio_th = 'Tesla อัจฉริยะนักประดิษฐ์ผู้ต่อสู้ด้วยอาวุธที่ใช้พลังงานไฟฟ้า' WHERE slug = 'Tesla';
UPDATE characters SET bio_th = 'Tali นักรบหนุ่มสาวที่มีศักยภาพสู่ความยิ่งใหญ่' WHERE slug = 'Tali';
UPDATE characters SET bio_th = 'Tora นักรบตะวันออกผู้เชี่ยวชาญการขว้างหอก การขว้างของเธอแม่นยำและทรงพลัง' WHERE slug = 'Tora';
UPDATE characters SET bio_th = 'Tristan อัศวินผู้มีเกียรติที่ต่อสู้เพื่อปกป้องอาณาจักร' WHERE slug = 'Tristan';
UPDATE characters SET bio_th = 'Ulfram นักรบดุร้ายผู้ทรงพลังที่ความโกรธของเขาหล่อเลี้ยงพลังอันไม่ธรรมดา' WHERE slug = 'Ulfram';
UPDATE characters SET bio_th = 'THAI_TEXT' WHERE slug = 'SLUG';
UPDATE characters SET bio_th = 'Ujja นักรบจากดินแดนลึกลับที่มีความสามารถในการต่อสู้อันเป็นเอกลักษณ์' WHERE slug = 'Uja';
UPDATE characters SET bio_th = 'Valeria เจ้าหญิงนักรบผู้ต่อสู้เพื่ออิสรภาพของอาณาจักรตน' WHERE slug = 'Valeria';
UPDATE characters SET bio_th = 'Veil นักรบเงาผู้โจมตีจากความมืด การโจมตีของเธอรวดเร็วและเงียบงัน' WHERE slug = 'Veil';
UPDATE characters SET bio_th = 'Veronif นักเล่นแร่แปรธาตุแห่ง Auch ความรู้ด้านยาและวิชาเล่นแร่แปรธาตุของเขาไม่มีใครเทียบได้' WHERE slug = 'Berroniff';
UPDATE characters SET bio_th = 'Viki นักรบอเนกประสงค์ที่สามารถใช้รูปแบบการต่อสู้ได้หลากหลาย' WHERE slug = 'Viki';
UPDATE characters SET bio_th = 'Vincent สุภาพบุรุษนักรบผู้ต่อสู้ด้วยเทคนิคที่ประณีตและท่าทางสง่างามแบบขุนนาง' WHERE slug = 'Vincent';
UPDATE characters SET bio_th = 'Violet นักรบผู้มีอดีตลึกลับและความสามารถในการต่อสู้อันทรงพลัง' WHERE slug = 'Violet';
UPDATE characters SET bio_th = 'Veatrice นักเวทสายฟ้าผู้ทรงพลังด้วยอำนาจไฟฟ้าอันน่าตื่นตะลึง' WHERE slug = 'Veatrice';
UPDATE characters SET bio_th = 'White Wolf นักรบโดดเดี่ยวในตำนานผู้เลื่องชื่อทั่วทั้งทวีป' WHERE slug = 'KaelRare';
UPDATE characters SET bio_th = 'Winona นักรบจากภูมิภาค Ende ที่มีทักษะการต่อสู้อันเป็นเอกลักษณ์' WHERE slug = 'WinonaEnde';
UPDATE characters SET bio_th = 'Yeganeh นักรบจากทะเลทรายทางตะวันออก ทักษะการเอาชีวิตรอดและความสามารถในการต่อสู้ของเธอได้รับการขัดเกลาจากสภาพแวดล้อมที่โหดร้าย' WHERE slug = 'Yeganeh';
UPDATE characters SET bio_th = 'Zaved นักรบมืดผู้มีพลังลึกลับจากอาณาจักรเงา' WHERE slug = 'Zaved';
UPDATE characters SET bio_th = 'Ziz สิ่งมีชีวิตในตำนานผู้ทรงพลังอย่างมหาศาล เพียงการปรากฏตัวของเธอก็บิดเบือนความเป็นจริงได้' WHERE slug = 'Ziz';
UPDATE characters SET bio_th = 'Ivy นักรบแห่งธรรมชาติผู้ดึงพลังจากแผ่นดินและพืชพรรณ' WHERE slug = 'Ivy';
UPDATE characters SET bio_th = 'JD นักดาบผู้เชี่ยวชาญอาวุธใบมีดหลากหลายชนิด' WHERE slug = 'Jd';
UPDATE characters SET bio_th = 'Jack ช่างฝีมือและนักรบผู้ชำนาญ เขาสร้างกับดักและสิ่งก่อสร้างเพื่อใช้ในการต่อสู้' WHERE slug = 'Jack';
UPDATE characters SET bio_th = 'Jaina นักรบเวทมนตร์ผู้มีความสามารถด้านธาตุสองธาตุ' WHERE slug = 'Jaina';
UPDATE characters SET bio_th = 'Jane นักสู้ผู้เดือดดาลด้วยเจตจำนงอันแข็งแกร่งและคมดาบอันคมกริบ' WHERE slug = 'Jane';
UPDATE characters SET bio_th = 'Jin นักศิลปะการต่อสู้จากตะวันออกผู้มีเทคนิคที่รวดเร็วดุจสายฟ้า' WHERE slug = 'Jin';
UPDATE characters SET bio_th = 'Jose Corthasar ขุนนางและนักรบจาก Old Continent' WHERE slug = 'Jose';
UPDATE characters SET bio_th = 'Joshua นักรบนักบวชผู้ทรงพลังที่ผสมผสานเวทมนตร์ศักดิ์สิทธิ์เข้ากับทักษะการต่อสู้' WHERE slug = 'Joshua';
UPDATE characters SET bio_th = 'Judith ในรูปแบบที่เสริมพลังแล้ว ใช้อาวุธด้ามยาวด้วยพลังศักดิ์สิทธิ์ที่ยิ่งใหญ่กว่าเดิม' WHERE slug = 'JudithRare';
UPDATE characters SET bio_th = 'Juliana นักรบผู้มีเทคนิคการต่อสู้ที่ประณีตและความสง่างามแบบขุนนาง' WHERE slug = 'Yuliana';
UPDATE characters SET bio_th = 'Kane นักรบผู้ดุดันที่การฟันดาบของเขาสามารถเจาะผ่านเกราะทุกชนิดได้' WHERE slug = 'Kein';
UPDATE characters SET bio_th = 'Karjalainen นักออกแบบจากภาคเหนือ ทักษะดาบ rapier ของเธอสง่างามพอๆ กับผลงานออกแบบของเธอ' WHERE slug = 'Karjalainen';
UPDATE characters SET bio_th = 'Kei นักรบเงียบขรึมผู้มีพลังแฝงอยู่ภายใน' WHERE slug = 'Kei';
UPDATE characters SET bio_th = 'Kevin นักดาบหนุ่มผู้ฝึกฝนตนเองเพื่อเป็นนักรบผู้ยิ่งใหญ่' WHERE slug = 'Kevin';
UPDATE characters SET bio_th = 'Kirna นักรบลึกลับผู้มีความสามารถทางเวทมนตร์อันเป็นเอกลักษณ์' WHERE slug = 'Kirna';
UPDATE characters SET bio_th = 'Kiss นักสู้ผู้มีเสน่ห์ที่ความงามของเธอเทียบเคียงได้กับความสามารถในการต่อสู้' WHERE slug = 'Kiss';
UPDATE characters SET bio_th = 'Kurt นายทหารและนักดาบผู้ชำนาญ จิตใจเชิงยุทธวิธีของเขาคมคายพอๆ กับดาบของเขา' WHERE slug = 'Dietrich';
UPDATE characters SET bio_th = 'Lada นักรบผู้เชื่อมต่อกับพลังโบราณ เธอปลุก Aisha ขึ้นจากการหลับใหล' WHERE slug = 'Rada';
UPDATE characters SET bio_th = 'Lady Rachel ตัว Rachel ในชุดขุนนางพร้อมความสามารถด้านภาวะผู้นำที่เพิ่มขึ้น' WHERE slug = 'Rachel2';
UPDATE characters SET bio_th = 'Laval นักรบจากดินแดนห่างไกลที่มีเทคนิคการต่อสู้อันเป็นเอกลักษณ์' WHERE slug = 'Laval';
UPDATE characters SET bio_th = 'Lead Manager Rachel ตัว Rachel ผู้ก้าวขึ้นสู่ตำแหน่งผู้นำพร้อมความสามารถที่เพิ่มขึ้น' WHERE slug = 'Rachel2Rare';
UPDATE characters SET bio_th = 'Leviathan สิ่งมีชีวิตแห่งท้องทะเลผู้ทรงพลังอย่างมหาศาลที่ได้รับร่างมนุษย์' WHERE slug = 'Leviathan';
UPDATE characters SET bio_th = 'Levine นักสู้ผู้ชำนาญที่มีเทคนิคการต่อสู้อันประณีต' WHERE slug = 'Levin';
UPDATE characters SET bio_th = 'Lhote นักรบภาคเหนือผู้ดุดันในสไตล์ของนักรบไวกิ้งโบราณ' WHERE slug = 'Viking';
UPDATE characters SET bio_th = 'Liung นักรบตะวันออกผู้ใช้ศิลปะการต่อสู้ที่ได้รับแรงบันดาลใจจากมังกร' WHERE slug = 'Liung';
UPDATE characters SET bio_th = 'Lora Constans นักรบขุนนางผู้ต่อสู้เพื่อความยุติธรรมและเกียรติยศ' WHERE slug = 'Laura';
UPDATE characters SET bio_th = 'Loraine นักสู้ผู้ชำนาญที่มีความสามารถในการต่อสู้อันหลากหลาย' WHERE slug = 'Lorraine';
UPDATE characters SET bio_th = 'THAI_TEXT' WHERE slug = 'SLUG';
UPDATE characters SET bio_th = 'Lorch นักรบและผู้บัญชาการผู้มากประสบการณ์ ภาวะผู้นำของเขาสร้างแรงบันดาลใจให้กับทหารในบังคับบัญชา' WHERE slug = 'Lorch';
UPDATE characters SET bio_th = 'Loreta นักสู้ผู้เชี่ยวชาญที่มีเทคนิคการต่อสู้อันประณีต' WHERE slug = 'Roreta';
UPDATE characters SET bio_th = 'Lynn นักรบผู้คล่องแคล่ว เป็นที่รู้จักในด้านความเร็วและความว่องไวอันน่าทึ่ง' WHERE slug = 'Lynn';
UPDATE characters SET bio_th = 'Lysette นักรบผู้ใช้เวทมนตร์ มีสไตล์การต่อสู้ที่งดงามอ่อนช้อย' WHERE slug = 'Lysette';
UPDATE characters SET bio_th = 'MBoma นักรบทรงพลังจากทวีปอันห่างไกล ความแข็งแกร่งของเขาเป็นตำนาน' WHERE slug = 'MBoma';
UPDATE characters SET bio_th = 'Maria ผู้เชี่ยวชาญด้านการรักษาและสนับสนุน ผู้ใส่ใจดูแลพันธมิตรของเธออย่างจริงจัง' WHERE slug = 'MariaMayer';
UPDATE characters SET bio_th = 'Marie หญิงสาวผู้มีพลังการรักษาเยียวยาด้วยเวทมนตร์' WHERE slug = 'Mary';
UPDATE characters SET bio_th = 'Mediator Berthe คือ Berthe ที่รับบทบาทเป็นคนกลางไกล่เกลี่ยระหว่างฝ่ายที่ขัดแย้งกัน' WHERE slug = 'BertheRare';
UPDATE characters SET bio_th = 'Meister Lorch คือ Lorch ที่ได้รับยศ Meister พร้อมความสามารถในการต่อสู้ที่เพิ่มขึ้น' WHERE slug = 'LorchRare';
UPDATE characters SET bio_th = 'Mercenary Calyce คือ Calyce ที่กลายมาเป็นทหารรับจ้าง พร้อมทักษะหน้าไม้ที่เพิ่มขึ้น' WHERE slug = 'Calyce2';
UPDATE characters SET bio_th = 'Meriel นักเวทมนตร์จิตใจอ่อนโยนที่มีพลังเวทมนตร์การรักษาอันทรงพลัง' WHERE slug = 'Meriel';
UPDATE characters SET bio_th = 'Mertis นักรบผู้เชี่ยวชาญที่มีความสามารถในการต่อสู้หลากหลาย' WHERE slug = 'Mertis';
UPDATE characters SET bio_th = 'Miha นักสู้หนุ่มสาวจากดินแดนตะวันออก' WHERE slug = 'Miha';
UPDATE characters SET bio_th = 'Miho นักรบตะวันออกผู้มีเทคนิคการต่อสู้อันเป็นเอกลักษณ์' WHERE slug = 'Miho';
UPDATE characters SET bio_th = 'Mireille นักสู้ผู้งดงามที่มีลีลาการเคลื่อนไหวดั่งการร่ายรำ' WHERE slug = 'Mireille';
UPDATE characters SET bio_th = 'Misa นักรบผู้มีความสามารถซ่อนเร้นและอดีตอันลึกลับ' WHERE slug = 'Misa';
UPDATE characters SET bio_th = 'Mistress Baselrane ผู้บัญชาการเวทมนตร์ผู้ทรงพลังที่นำทัพด้วยอำนาจและอำนาจบารมี' WHERE slug = 'Lobaselrane';
UPDATE characters SET bio_th = 'Montoro ตัวร้ายชื่อกระฉ่อนที่กลายมาเป็นตัวละครที่ผู้เล่นควบคุมได้ พลังแห่งความมืดของเขาอยู่ในมือคุณแล้ว' WHERE slug = 'MontoroPC';
UPDATE characters SET bio_th = 'Moon นักรบแห่งฟากฟ้าผู้ดึงพลังงานจากแสงจันทร์' WHERE slug = 'Moon';
UPDATE characters SET bio_th = 'Najib Sharif นักรบแห่งทะเลทรายและนักวางแผนกลยุทธ์จากดินแดนตะวันออก' WHERE slug = 'Sharif';
UPDATE characters SET bio_th = 'Navas นักรบที่เชื่อถือได้ผู้ต่อสู้เคียงข้างเพื่อนร่วมรบ' WHERE slug = 'Navas';
UPDATE characters SET bio_th = 'Nena เด็กหญิงผู้มีพลังเวทมนตร์ที่น่าประหลาดใจ' WHERE slug = 'Nena';
UPDATE characters SET bio_th = 'Neo นักรบแห่งอนาคตผู้มีเทคนิคการต่อสู้ขั้นสูง' WHERE slug = 'Neo10';
UPDATE characters SET bio_th = 'Nicole นักสู้ผู้เชี่ยวชาญที่มีเสน่ห์และความแม่นยำถึงตาย' WHERE slug = 'Nicol';
UPDATE characters SET bio_th = 'Nike化身ของเทพีแห่งชัยชนะ การปรากฏตัวของเธอรับประกันความสำเร็จ' WHERE slug = 'Nike';
UPDATE characters SET bio_th = 'Nina นักรบสาวผู้ดุดันที่มีศักยภาพสูงยิ่ง' WHERE slug = 'Nina';
UPDATE characters SET bio_th = 'Olivia นักสู้ผู้มีรสนิยมที่ผสมผสานความสง่างามเข้ากับทักษะการต่อสู้อันเฉียบขาด' WHERE slug = 'Olivia';
UPDATE characters SET bio_th = 'Patrick อัศวินผู้สูงศักดิ์ที่ต่อสู้ด้วยเกียรติยศและความรับผิดชอบอันแน่วแน่' WHERE slug = 'Patrick';
UPDATE characters SET bio_th = 'Pioneer Queen Grandma คือ Grandma ที่กลายมาเป็นราชินีผู้บุกเบิก พร้อมความสามารถด้านดาบยักษ์ที่เพิ่มขึ้น' WHERE slug = 'Grandies2';
UPDATE characters SET bio_th = 'Pirate Adelina คือ Adelina ในบทบาทกัปตันโจรสลัดผู้ยิ่งใหญ่ พร้อมทักษะดาบโค้งและปืนพกที่เพิ่มขึ้น' WHERE slug = 'AdelinaPirate';
UPDATE characters SET bio_th = 'Psyche สิ่งมีชีวิตลึกลับผู้มีพลังจิตอันทรงพลัง' WHERE slug = 'Psyche';
UPDATE characters SET bio_th = 'Queen Cerny Joshua คือ Joshua ที่ได้รับสถานะราชวงศ์ พร้อมความสามารถการต่อสู้ด้านทิพย์ที่เพิ่มขึ้น' WHERE slug = 'Joshua2';
UPDATE characters SET bio_th = 'Rachel Sheffield นักรบผู้สูงศักดิ์จากตระกูล Sheffield' WHERE slug = 'Rachel';
UPDATE characters SET bio_th = 'Rakicia นักรบผู้ดุดันจากดินแดนอันห่างไกล' WHERE slug = 'Rakicia';
UPDATE characters SET bio_th = 'Ralph นักสู้ที่เชื่อถือได้ผู้ไม่เคยถอยหนีจากความท้าทาย' WHERE slug = 'Ralph';
UPDATE characters SET bio_th = 'Ramiro นักรบผ่านศึกผู้มีประสบการณ์หลายปีบนสนามรบ' WHERE slug = 'Ramiro';
UPDATE characters SET bio_th = 'Rascel นักสู้ผู้เชี่ยวชาญที่มีเทคนิคการต่อสู้อันเป็นเอกลักษณ์' WHERE slug = 'Racel';
UPDATE characters SET bio_th = 'Raven นักรบแห่งความมืดผู้โจมตีจากเงามืด' WHERE slug = 'Raven';
UPDATE characters SET bio_th = 'Reaper Sariel คือ Sariel ที่ยอมรับพลังแห่งความตายอย่างเต็มตัว' WHERE slug = 'Sariel2';
UPDATE characters SET bio_th = 'Rebecca นักรบผู้มีพรสวรรค์ที่มีความสามารถในการต่อสู้อเนกประสงค์' WHERE slug = 'Rebecca';
UPDATE characters SET bio_th = 'THAI_TEXT' WHERE slug = 'SLUG';
UPDATE characters SET bio_th = 'Reckless Emilia นักรบสาวผู้ละทิ้งความระมัดระวัง และต่อสู้ด้วยพลังเวทย์ที่ดุเดือดและคาดเดาไม่ได้' WHERE slug = 'EmiliaLunatic';
UPDATE characters SET bio_th = 'Rescue Knight นักรบผู้สูงศักดิ์ที่อุทิศตนเพื่อช่วยเหลือผู้ตกอยู่ในอันตราย' WHERE slug = 'RescueKnight';
UPDATE characters SET bio_th = 'Rescue Officer Romina นักรบสาว Romina ผู้ดำรงตำแหน่งเจ้าหน้าที่กู้ภัย พร้อมความสามารถด้านการต่อสู้และการรักษาที่เพิ่มขึ้น' WHERE slug = 'RominaRare';
UPDATE characters SET bio_th = 'Risky นักสู้สาวผู้กล้าเสี่ยง ใช้ชีวิตอยู่บนคมดาบ สไตล์การต่อสู้ที่บ้าบิ่นของเธอมักทำให้คู่ต่อสู้ตั้งตัวไม่ทัน' WHERE slug = 'Risky';
UPDATE characters SET bio_th = 'Rob Clemens มือปืนช่ำชองจากกองทัพ มีทักษะการยิงที่เหนือกว่าคนอื่น' WHERE slug = 'RobClemens';
UPDATE characters SET bio_th = 'Romina นักรบสาวใจดี ต่อสู้เพื่อปกป้องคนที่เธอรัก' WHERE slug = 'Romina';
UPDATE characters SET bio_th = 'Ronera นักรบลึกลับผู้มีความสามารถในการต่อสู้ที่ทรงพลัง' WHERE slug = 'Ronera';
UPDATE characters SET bio_th = 'Rosa นักรบสาวในธีมดอกไม้ ความงามของเธอปกปิดทักษะอันน่าเกรงขามไว้ภายใน' WHERE slug = 'Rosa';
UPDATE characters SET bio_th = 'Rose, The Spirit สิ่งมีชีวิตลึกลับแห่งพลังงานบริสุทธิ์ ที่จุติมาในร่างมนุษย์' WHERE slug = 'Spirit';
UPDATE characters SET bio_th = 'Rosie นักสู้สาวร่าเริง ทัศนคติเชิงบวกของเธอเป็นแรงบันดาลใจให้พันธมิตร' WHERE slug = 'Rosie';
UPDATE characters SET bio_th = 'Royal Guard Delfina นักรบสาว Delfina ผู้ดำรงตำแหน่งทหารองครักษ์ชั้นยอด' WHERE slug = 'DelfinaRare';
UPDATE characters SET bio_th = 'Rubiana รูปแบบที่พัฒนาขึ้นของ Aileen ด้วยพลังและความสามารถที่เพิ่มขึ้น' WHERE slug = 'EileenRare';
UPDATE characters SET bio_th = 'Sakura นักรบสาวดอกซากุระจากแดนตะวันออก' WHERE slug = 'SakuraRare';
UPDATE characters SET bio_th = 'Sakura Hime เจ้าหญิงแห่งดอกซากุระ สไตล์การต่อสู้อันงดงามของเธอผสมผสานศิลปะการต่อสู้ตะวันออกกับพลังเวทมนตร์' WHERE slug = 'Sakura';
UPDATE characters SET bio_th = 'Sariel สิ่งมีชีวิตแห่งสวรรค์ผู้ทรงพลังเวทย์อันศักดิ์สิทธิ์' WHERE slug = 'Sariel';
UPDATE characters SET bio_th = 'Scavenger Yeganeh นักรบสาว Yeganeh ผู้กลายเป็นนักหาของเก่า ด้วยทักษะการเอาตัวรอดและการต่อสู้ที่เพิ่มขึ้น' WHERE slug = 'Yeganeh2';
UPDATE characters SET bio_th = 'Selene นักบวชสาวแห่งดวงจันทร์ ผู้ทรงพลังเวทย์การรักษาและปกป้องอันศักดิ์สิทธิ์' WHERE slug = 'Selane';
UPDATE characters SET bio_th = 'Selva นักรบแห่งป่าดงดิบ ต่อสู้ด้วยสัญชาตญาณดิบและพลังธรรมชาติ' WHERE slug = 'Selva';
UPDATE characters SET bio_th = 'Senior Magic Corps Dolores นักรบสาว Dolores ผู้บัญชาการกองกำลังเวทย์ระดับสูง ด้วยความสามารถด้านธาตุที่เพิ่มขึ้น' WHERE slug = 'Dobaselrane';
UPDATE characters SET bio_th = 'Seol Hwa นักรบสาวตะวันออกผู้เชี่ยวชาญศิลปะการต่อสู้ด้วยพลังน้ำแข็ง' WHERE slug = 'Seolhwa';
UPDATE characters SET bio_th = 'Sergeant Barrol นักรบ Barrol ผู้ได้รับการเลื่อนยศเป็นจ่าสิบเอก ด้วยทักษะการยิงที่พัฒนาขึ้น' WHERE slug = 'Barrelrare';
UPDATE characters SET bio_th = 'Sharon the Sage นักรบสาว Sharon ผู้บรรลุตำแหน่งนักปราชญ์ ด้วยความสามารถด้านเวทมนตร์ที่เพิ่มขึ้น' WHERE slug = 'Sharon2';
UPDATE characters SET bio_th = 'Sherry นักสู้สาวหนุ่มสาวและเต็มไปด้วยพลัง ด้วยความหลงใหลในการต่อสู้' WHERE slug = 'Sherry';
UPDATE characters SET bio_th = 'Sierra Rose นักรบสาว Sierra ในรูปแบบที่พัฒนาขึ้น ด้วยความสามารถในการต่อสู้ที่ดีขึ้น' WHERE slug = 'SierraLosPC';
UPDATE characters SET bio_th = 'Silaen สิ่งมีชีวิตในตำนานที่เกี่ยวข้องกับ Ziz ผู้มีพลังพิเศษเฉพาะตัว' WHERE slug = 'Ziz2';
UPDATE characters SET bio_th = 'Silver Flash Lynn นักรบสาว Lynn ผู้ได้รับฉายา Silver Flash จากความเร็วอันน่าทึ่งของเธอ' WHERE slug = 'LynnRare';
UPDATE characters SET bio_th = 'Sirius อัศวินแห่งดวงดาว เกราะและดาบจากสรวงสวรรค์ของเขานั้นเลื่องลือไปทั่ว' WHERE slug = 'hknight';
UPDATE characters SET bio_th = 'Sniper Bernelli นักรบสาว Bernelli ผู้เชี่ยวชาญการต่อสู้ระยะไกลในฐานะมือปืนซุ่มยิง' WHERE slug = 'GraceSniper';
UPDATE characters SET bio_th = 'Snowflake Berthe and Charles เวอร์ชันฤดูหนาวของ Berthe พร้อมเวทมนตร์ในธีมน้ำแข็ง' WHERE slug = 'BertheIce';
UPDATE characters SET bio_th = 'Snowflake Cherlyn นักรบสาว Cherlyn พร้อมความสามารถด้านเวทมนตร์ที่เสริมด้วยพลังน้ำแข็ง' WHERE slug = 'SherlinICE';
UPDATE characters SET bio_th = 'Snowflake Montoro เวอร์ชันธีมฤดูหนาวของ Montoro ผู้ทรงพลังน้ำแข็ง' WHERE slug = 'IceMontoro';
UPDATE characters SET bio_th = 'Soho นักรบตะวันออกผู้มีเทคนิคศิลปะการต่อสู้อันเป็นเอกลักษณ์' WHERE slug = 'Soho';
UPDATE characters SET bio_th = 'Soho The Wind นักรบ Soho ผู้เชี่ยวชาญธาตุลมในศิลปะการต่อสู้ของเขา' WHERE slug = 'SohoFighter';
UPDATE characters SET bio_th = 'Soldier of Reboldoeux ทหารผู้ซื่อสัตย์ ผู้พิทักษ์รักษาเมือง Reboldoeux' WHERE slug = 'Soldier';
UPDATE characters SET bio_th = 'Sorang นักรบตะวันออกผู้ใช้เทคนิคการต่อสู้แบบดั้งเดิม' WHERE slug = 'Sorang';
UPDATE characters SET bio_th = 'Sorscha นักรบสาวไฟแรงจากดินแดนทางเหนือ' WHERE slug = 'Sorscha';
UPDATE characters SET bio_th = 'Soso นักรบสุดเพลย์ฟูล ต่อสู้ด้วยเทคนิคที่คาดไม่ถึง' WHERE slug = 'Soso';
UPDATE characters SET bio_th = 'Spy Olivia นักรบสาว Olivia ผู้ทำงานเป็นสายลับ ด้วยทักษะการพรางตัวและการแทรกซึม' WHERE slug = 'SpyOlivia';
UPDATE characters SET bio_th = 'Student President Ludin นักรบ Ludin ในวัยเรียน ในฐานะประธานสภานักเรียน' WHERE slug = 'SLudin';
UPDATE characters SET bio_th = 'Supreme Commander Kano นักรบ Kano ผู้ก้าวขึ้นสู่ตำแหน่งผู้บัญชาการสูงสุด ด้วยเวทมนตร์ทางทะเลที่ไร้เทียมทาน' WHERE slug = 'Kano2Rare';
UPDATE characters SET bio_th = 'Sylvestia ผู้พิทักษ์ป่าผู้ทรงพลังเวทมนตร์จากธรรมชาติ' WHERE slug = 'Sylvestia';
UPDATE characters SET bio_th = 'Tiburon นักรบสุดดุดันจากท้องทะเล ดั่งฉลาม ความดุร้ายของเขาในสนามรบนั้นเลื่องลือ' WHERE slug = 'Tiburon';
UPDATE characters SET bio_th = 'Tom นักรบเรียบง่ายแต่เชี่ยวชาญ ต่อสู้ด้วยเทคนิคตรงไปตรงมาแต่ได้ผล' WHERE slug = 'Tom';
UPDATE characters SET bio_th = 'Valeria นักรบผู้สูงศักดิ์ ต่อสู้เพื่อความยุติธรรมและอิสรภาพ' WHERE slug = 'Valleria';
UPDATE characters SET bio_th = 'Valeria Vendetta นักรบสาว Valeria ผู้ออกเดินทางแก้แค้น ด้วยความสามารถด้านการต่อสู้มืดที่เพิ่มขึ้น' WHERE slug = 'Vendetta';
UPDATE characters SET bio_th = 'Van บาทหลวงศักดิ์สิทธิ์แห่ง Armonia ต่อสู้เพื่อปกป้องศรัทธาและผู้ศรัทธาทั้งหลาย' WHERE slug = 'Van';
UPDATE characters SET bio_th = 'Vanessa นักรบสาวผู้สง่างาม ทั้งความงามและทักษะการต่อสู้ของเธอต่างเลื่องลือเท่าเทียมกัน' WHERE slug = 'Vanessa';
