-- Monsters data: 630 monsters

INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Abbyssal claw Elite', 'Human', 43, 0, 'Porto Bello, The Cabin', 'dunptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Abbyssal claw', 'Human', 43, 0, 'Porto Bello, St. Cathrinas Saloon', 'missionptvbossa');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Abyss, Crazy', 'Demon', 120, 1, 'First Darkness', 'missionarmdark');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Abyss Avers', 'Demon', 150, 1, 'Armonia, Biego', 'dunarm04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Abyss Desglose', 'Demon', 150, 1, 'Armonia, El Templo', 'dunarm02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Abyss Haat', 'Demon', 150, 1, 'Armonia, Biego', 'dunarm04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AbyssSorrow', 'Demon', 150, 1, 'Armonia, En Celar', 'dunarm01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Acorchado', 'Wildlife', 118, 0, 'Tierra Putrefacta', 'btlsed01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Acorchado', 'Wildlife', 135, 0, 'Mission: Overlord of Element', 'missionbahweek');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Amok Tortoise', 'Wildlife', 53, 0, 'Thueringenwald', 'btlauch01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AncientFighter', 'Undead', 108, 0, 'Party Mission : Fury Sekhmet', 'missionsekhmetparty');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AncientFighter', 'Undead', 120, 0, 'Inside Crater', 'dungigboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AncientFighter', 'Undead', 120, 0, 'Mission : Demonic Minotauros', 'missionmasungcas02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AncientFighter', 'Undead', 122, 0, 'Castilla, Ruins', 'btlcas01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AncientFighter', 'Undead', 123, 0, 'Castilla, Ruins', 'btlcas01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ancient Jumpingfish', 'Undead', 108, 0, 'Bahama, Ancient Cave 1F', 'dunbah04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AncientKnight', 'Undead', 118, 0, 'Castilla, Ruins', 'btlcas01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AncientKnight', 'Undead', 118, 0, 'Ancient Castilla, Temple', 'btlcas03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('AncientKnight', 'Undead', 120, 0, 'Mission : Demonic Minotauros', 'missionmasungcas02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ancient Taurus', 'Wildlife', 106, 0, 'Bahama, Ancient Cave 1F', 'dunbah04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Angry Comodo', 'Wildlife', 104, 0, 'Lava Plateau of Joaquin', 'fldjaq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Anteater', 'Wildlife', 102, 0, 'Abertal', 'btltbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Apato Saurus', 'Wildlife', 100, 0, 'Ustiur, Zona Quatro', 'btlust04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Arbremon', 'Wildlife', 135, 1, 'Lucifer Castle, Secret Garden', 'btllucifer01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Armonia Bear', 'Wildlife', 125, 0, 'Armonia, Latina', 'btlarm01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Arop Elite', 'Wildlife', 85, 0, 'Ustiur, Zona Uno', 'btlust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Auch Musketeer', 'Human', 15, 0, 'Battle with Auch Soldiers', 'missionauchsoldier');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Auch Musketeer', 'Human', 100, 0, 'Secret Temple', 'missionshadowtemple');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bacchanalia Elite', 'Golem', 122, 0, 'Corazon de Gigante', 'dunsed02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bacchanalia', 'Golem', 132, 0, 'Twisted Time : Imperium Rex', 'duncasile02hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bandelier THE SABRE Elite', 'Human', 35, 0, 'Jezebel Glen', 'btlcoim01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bandelier THE bully', 'Human', 97, 0, 'Topolo Durga', 'btlttr03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bandelier THE edward', 'Human', 97, 0, 'Topolo Durga', 'btlttr03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Barrier Mehcos', 'Wildlife', 102, 0, 'Ferruccio Wall', 'btlktv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Beachball_Jackolantern', 'Golem', 75, 0, 'Island of Fire', 'btlgig01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bearworker Elite', 'Wildlife', 104, 0, 'Deprimida Valley', 'btltbk03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bearworker', 'Wildlife', 104, 0, 'Poison Yard for Christmas', 'missionxmaspoison');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bedel Buffalo', 'Wildlife', 132, 0, 'Bedel Plain', 'btlbedel01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bedel Leafing croc', 'Wildlife', 132, 0, 'Bedel Plain', 'btlbedel01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Big Rabbit', 'Wildlife', 1, 0, 'Ustiur, The Farm', 'missionustfarm');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bigfoot', 'Wildlife', 111, 0, 'Snowfield of the Ice Wizard', 'btlktv05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Black Eagle Fencer', 'Wildlife', 130, 0, 'Mission : Demonic Medusa', 'missionmasungcas03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Black Eagle Lancer', 'Wildlife', 130, 0, 'Mission : Demonic Medusa', 'missionmasungcas03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Black Eagle Shooter', 'Wildlife', 130, 0, 'Mission : Demonic Medusa', 'missionmasungcas03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Black Iron Keeper', 'Golem', 120, 1, 'Armonia, Biego', 'dunarm04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Black Iron Keeper', 'Golem', 120, 1, 'Hard : Ruler of Rage', 'missionarmfuryh');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Blackfish Elite', 'Golem', 116, 0, 'Bahama, Underground Cave 2F', 'dunbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bladeantelopes Elite', 'Wildlife', 104, 0, 'Deprimida Valley', 'btltbk03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Blizzardrevenant Elite', 'Undead', 110, 0, 'Snowfield of the Ice Wizard', 'btlktv05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bloody Hound-eater', 'Wildlife', 61, 0, 'Pradera de Ceniza', 'btljaq02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Blue Elemental', 'Golem', 123, 0, 'Imperium Rex', 'duncasile02normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bluefish', 'Golem', 135, 0, 'Mission: Overlord of Element', 'missionbahweek');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Boneless', 'Undead', 100, 0, '3rd Floor of Skulls Dungeon', 'dunust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Box', 'Misc', 13, 0, 'Armonia, Latina', 'btlarm01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Box', 'Misc', 27, 0, 'Tetra Ruins, Grand Corridor', 'dunttr01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Box', 'Misc', 42, 0, 'Porto Bello, The Cabin', 'dunptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Box', 'Misc', 65, 0, 'Rion Dungeon Corridor', 'dunalq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Box', 'Misc', 78, 0, 'Prison de Joaquin, Torture Chamber', 'dunjaq05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Box', 'Misc', 97, 0, '3rd Floor of Skulls Dungeon', 'dunust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Bribantra', 'Golem', 132, 0, 'Twisted Time : Imperium Rex', 'duncasile02hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Brown Buffalo Elite', 'Wildlife', 20, 0, 'Kings Garden', 'btlttr02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Burning Walter', 'Golem', 56, 0, 'Dr. Torsches Mansion, Reception Hall', 'duntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('CASTOR of Chaos', 'Demon', 132, 0, 'Secret Temple', 'btlshadowtemple');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('CHIMERA No.666', 'Golem', 145, 1, 'Lucifer Castle, Basement Warehouse', 'dunlucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Candlegeister', 'Golem', 130, 0, 'Trumans Secret Workshop B1F', 'dunclockmaze01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cannon tortoise', 'Wildlife', 46, 0, 'Porto Bello, Deserted Quay', 'btlptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Capella Elite', 'Golem', 82, 0, 'Prison de Joaquin, Schivarliere', 'dunjaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Capybaraground', 'Misc', 108, 0, 'Toubkal Mine', 'duntbkboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Carpenterwasp Elite', 'Wildlife', 110, 0, 'Bahama, Swamp of Eternity', 'btlbah03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Case-octopus Elite', 'Wildlife', 36, 0, 'Jezebel Glen', 'btlcoim01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Case-octopus', 'Wildlife', 36, 0, 'Attack of Escudo Pecher', 'missionescudo');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cask-octopus', 'Wildlife', 36, 0, 'Attack of Escudo Pecher', 'missionescudo');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cask', 'Misc', 11, 0, 'Al Quelt Moreza, the Nartex', 'dunalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cask', 'Misc', 30, 0, 'Tetra Catacomb', 'dunttr02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cask', 'Misc', 44, 0, 'Porto Bello, The Hold', 'dunptv03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cask', 'Misc', 74, 0, 'Prison de Joaquin, The Mohrgus', 'dunjaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cask', 'Misc', 95, 0, '2nd Floor of Skulls Dungeon', 'dunust02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cavern Ghouloftreasure Elite', 'Undead', 116, 0, 'Bahama, Underground Cave 2F', 'dunbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cavern Ghouloftreasure', 'Undead', 116, 0, 'Bahama, Underground Cave 2F', 'dunbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cavern Jumpingfish', 'Undead', 115, 0, 'Bahama, Underground Cave 1F', 'dunbah01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cavern Treasuremimic', 'Undead', 114, 0, 'Bahama, Underground Cave 1F', 'dunbah01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cehcos', 'Wildlife', 62, 0, 'Rion Dungeon Corridor', 'dunalq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Celegrimworm', 'Undead', 105, 0, 'Deprimida Valley', 'btltbk03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Celemantis', 'Golem', 103, 0, 'Via Fluvial', 'btltbk02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cerberus', 'Wildlife', 132, 0, 'Twisted Time : Imperium Rex', 'duncasile02hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cerberus', 'Wildlife', 150, 1, 'Distorted Time : Imperium Rex', 'duncasile02raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Charioteer', 'Golem', 77, 0, 'Prison de Joaquin, Torture Chamber', 'dunjaq05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ckao', 'Golem', 150, 1, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cockatrice', 'Wildlife', 65, 0, 'Rion Dungeon Hollow', 'dunalq05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cockatries Elite', 'Wildlife', 65, 0, 'Bonavista River', 'btlreb02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cockatries', 'Wildlife', 65, 0, 'Bonavista River', 'btlreb02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Crab Elite', 'Wildlife', 50, 0, 'Outside Bahia', 'fldgig');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cragen Elite', 'Demon', 100, 0, 'Scorching Plateau', 'btlktv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Crimsonwolf Elite', 'Wildlife', 18, 0, 'Cathari Falls', 'btlalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Crown Lloyd', 'Golem', 110, 0, 'Dr. Torsches Mansion, Annex', 'duntor04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Crueluz', 'Wildlife', 135, 1, 'Lucifer Castle, Moonlight Garden', 'btllucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Crying croc', 'Wildlife', 68, 0, 'Rion Dungeon Hollow', 'dunalq05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Andre Janzur', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Back Ho', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Calyce', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Eduardo', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Grace Berneli', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Grandma', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Hellena', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Jack', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Kurt', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Lorch', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Nar', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Raven', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Rio', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed SoSo', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed Yeganeh', 'Human', 120, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Cursed undead soldier', 'Undead', 100, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('DIABLO', 'Demon', 130, 1, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('DR. FRAN MOTHTEIN', 'Human', 100, 1, 'Joaquin, Corridor of Assize 1', 'missionjaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dandelion Swamp monkey Elite', 'Wildlife', 50, 0, 'Thueringenwald', 'btlauch01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dark Buffalo Elite', 'Wildlife', 49, 0, 'Thueringenwald', 'btlauch01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Darked Jormongand', 'Wildlife', 140, 1, 'Lucifer Castle, Basement Laboratory', 'dunlucifer01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Decarabia', 'Undead', 130, 1, 'Old Port of Coimbra', 'btlcoim02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Decay Celemantis', 'Golem', 105, 0, 'Mine Passage', 'duntbk02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demon Elite', 'Demon', 30, 0, 'Tetra Catacomb', 'dunttr02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Acorchado', 'Wildlife', 125, 0, 'Hard : Demonic Chaos Requiem', 'Hmissionmasungsed');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Blackfish', 'Golem', 115, 0, 'Hard : Demonic Bahama Cave', 'Hmissionmasungbah');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Dread anchor', 'Undead', 50, 0, 'Hard : Demonic Porto Bello', 'Hmissionmasungpot');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Dullahanguardian', 'Golem', 135, 0, 'Hard : Demonic Occulta Fortress', 'Hmissionmasungerc');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Dullahanlanceman', 'Golem', 135, 0, 'Hard : Demonic Occulta Fortress', 'Hmissionmasungerc');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Eldoom', 'Demon', 115, 0, 'Hard : Demonic Ice Wizards Tower', 'Hmissionmasungktv');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Escudofrapper', 'Undead', 115, 0, 'Hard : Demonic Bahama Cave', 'Hmissionmasungbah');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Gavi di Gavi', 'Undead', 55, 0, 'Demonic Porto Bello, the Hold', 'missiondunptvdb');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Ghoul Archer', 'Undead', 105, 0, 'Hard : Demonic Secret Tower', 'Hmissionmasungsct');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Ghoul Scout', 'Undead', 102, 0, 'Hard : Demonic Secret Tower', 'Hmissionmasungsct');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Giant Celegrimworm', 'Undead', 108, 0, 'Hard : Demonic Toubkal Mine', 'Hmissionmasungtbk');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Hollowed Footman', 'Golem', 70, 0, 'Hard : Demonic Dr. Torsches Mansion', 'Hmissionmasungtor');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Ironmaiden', 'Golem', 90, 0, 'Hard : Demonic Prison de Joaquin', 'Hmissionmasungjaq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Koboldchief Elder', 'Wildlife', 135, 0, 'Hard : Demonic Occulta Fortress', 'Hmissionmasungerc');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Locke', 'Golem', 115, 0, 'Hard : Demonic Bahama Cave', 'Hmissionmasungbah');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Merman', 'Human', 50, 0, 'Hard : Demonic Porto Bello', 'Hmissionmasungpot');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Nevare', 'Demon', 46, 0, 'Demonic Tetra, Catacomb', 'missiondunttrdb');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Red  Elemental', 'Golem', 125, 0, 'Hard : Demonic Chaos Requiem', 'Hmissionmasungsed');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Rusty Musescargot Rouge', 'Undead', 90, 0, 'Hard : Demonic Prison de Joaquin', 'Hmissionmasungjaq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Scarlet claw', 'Human', 50, 0, 'Hard : Demonic Porto Bello', 'Hmissionmasungpot');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Skeleton Excutioner', 'Undead', 105, 0, 'Hard : Demonic Skulls Dungeon', 'Hmissionmasungust');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Skeleton Knight', 'Undead', 105, 0, 'Hard : Demonic Skulls Dungeon', 'Hmissionmasungust');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Skeleton lancer', 'Undead', 105, 0, 'Hard : Demonic Skulls Dungeon', 'Hmissionmasungust');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Taurus', 'Wildlife', 115, 0, 'Hard : Demonic Bahama Cave', 'Hmissionmasungbah');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Tcapycruel', 'Wildlife', 105, 0, 'Hard : Demonic Toubkal Mine', 'Hmissionmasungtbk');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Tcapywarrior', 'Wildlife', 106, 0, 'Hard : Demonic Toubkal Mine', 'Hmissionmasungtbk');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Twin-headed', 'Golem', 90, 0, 'Hard : Demonic Prison de Joaquin', 'Hmissionmasungjaq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Vampire Bat lord', 'Undead', 105, 0, 'Hard : Demonic Toubkal Mine', 'Hmissionmasungtbk');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Violence Bearworker', 'Wildlife', 107, 0, 'Hard : Demonic Toubkal Mine', 'Hmissionmasungtbk');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demoniac Wraith', 'Undead', 102, 0, 'Hard : Demonic Secret Tower', 'Hmissionmasungsct');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Demonische', 'Wildlife', 55, 0, 'El Tejado Verde', 'btlauch03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dingo Elite', 'Wildlife', 84, 0, 'Ustiur, Zona Uno', 'btlust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dinodon', 'Wildlife', 90, 0, 'Ustiur, Zona Tres', 'btlust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Disease Tcapy Elite', 'Wildlife', 102, 0, 'Abertal', 'btltbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Disease Tcapy', 'Wildlife', 102, 0, 'Abertal', 'btltbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Disease Tcapyranger', 'Wildlife', 104, 0, 'Via Fluvial', 'btltbk02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Disease Tcapywarrior', 'Wildlife', 104, 0, 'Deprimida Valley', 'btltbk03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Doggy bomber', 'Wildlife', 60, 0, 'El Tejado Verde', 'btlauch03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dread anchor Elite', 'Undead', 42, 0, 'Porto Bello, The Cabin', 'dunptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dullahanattacker', 'Golem', 120, 0, 'Occulta Fortress', 'dunerc01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dullahangunner', 'Golem', 120, 0, 'Occulta Fortress', 'dunerc01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dumanon Elite', 'Undead', 45, 0, 'Porto Bello, The Hold', 'dunptv03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Dupesteen', 'Human', 85, 0, 'El Canon de Diabolica', 'btljaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Egg', 'Wildlife', 110, 0, 'Bahama, Marshlands', 'btlbah01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Eigleschvarlier Elite', 'Golem', 83, 0, '[Event Mission] Joaquin Barrier (Siege) Lv.1', 'missionthefortressoa');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Eigleschvarlier', 'Golem', 83, 0, 'Joaquin, Corridor of Assize', 'dunjaqboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Eigleschvarlier', 'Golem', 83, 0, 'Joaquin, Corridor of Assize', 'dunjaqboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Eigleschvarlier', 'Golem', 83, 0, 'Memory of Dilos Latemn', 'missionlatem');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Einwetter Elite', 'Golem', 108, 0, 'Silent Maze - 1F', 'dunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Einwetter', 'Demon', 110, 0, 'Silent Maze - 1F', 'missiondunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Einwetter', 'Golem', 110, 0, 'Silent Maze - 1F', 'dunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Einwetter', 'Golem', 110, 0, 'Silent Maze - 2F', 'dunsil02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Einwetter', 'Golem', 150, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Einwind1 Elite', 'Golem', 108, 0, 'Silent Maze - 1F', 'dunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elbiote', 'Wildlife', 110, 0, 'Frozen Plain', 'btlktv04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elbleed', 'Demon', 118, 0, 'Ice Wizards Tower - 5F', 'dunktv05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elboom', 'Demon', 112, 0, 'Ice Wizards Tower - 1F', 'dunktv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elcinos', 'Wildlife', 107, 0, 'Katovic Snowfield', 'btlktv03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Eldoom Elite', 'Demon', 115, 0, 'Ice Wizards Tower, Novias Parlor', 'dunktvboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Eldoom', 'Demon', 115, 0, 'Ice Wizards Tower - 1F', 'dunktv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Electric Walter', 'Golem', 56, 0, 'Dr. Torsches Mansion, Reception Hall', 'duntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elgoom Elite', 'Human', 116, 0, 'Ice Wizards Tower, Novias Parlor', 'missiondunktvboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elgoom', 'Demon', 116, 0, 'Ice Wizards Tower - 5F', 'dunktv05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Eliigo Elite', 'Wildlife', 110, 0, 'Frozen Plain', 'btlktv04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elite Bowgaras', 'Undead', 120, 0, 'Viron, Crow Forest', 'btlviron02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elite Fire Yus-machina', 'Golem', 130, 0, 'Vernier Mansion 2nd Floor', 'dunile02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elite Gluttony', 'Demon', 125, 0, 'Viron, Crow Forest', 'btlviron02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elite Ice Yus-machina', 'Golem', 130, 0, 'Vernier Mansion 2nd Floor', 'dunile02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elite ReaperGaras', 'Undead', 120, 0, 'Viron, Red Sunset Forest', 'btlviron01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elite Vordoi', 'Demon', 120, 0, 'Viron, Red Sunset Forest', 'btlviron01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elminor', 'Demon', 124, 1, 'Ice Wizards Tower - 4F', 'dunktv04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elminor', 'Demon', 135, 1, 'Lucifer Castle, Death Corridor', 'duncaslucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elmorc', 'Human', 106, 1, 'Tower of the Ice Wizard for Christmas', 'missionxmasktv');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elnoogard', 'Demon', 121, 0, 'Ice Wizards Tower - 5F', 'dunktv05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elnoogard', 'Human', 124, 1, 'Ice Wizards Tower, Novias Parlor', 'missiondunktvboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Elysian', 'Golem', 121, 0, 'Interna de Gigante', 'dunsed03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Eripmav Elite', 'Wildlife', 89, 0, 'Ustiur, Zona Dos', 'btlust02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Escudofrapper Elite', 'Undead', 111, 0, 'Bahama, Swamp of Eternity', 'btlbah03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Escudofrapper', 'Undead', 111, 0, 'Bahama, Swamp of Eternity', 'btlbah03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Rock', 'Misc', 100, 0, 'Gathering the Construction Rocks', 'missionjackrock');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 125, 0, 'Armonia, En Celar', 'dunarm01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 125, 0, 'Armonia, El Templo', 'dunarm02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 125, 0, 'Armonia, El Templo', 'dunarm02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 125, 0, 'Armonia, Gloria', 'dunarm03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 125, 0, 'Armonia, El Adio', 'dunarm05red');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 125, 0, 'Distorted Armonia', 'fldifarm01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 125, 0, 'Distorted Armonia, Apostadero', 'fldifarm02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 125, 0, 'Distorted Armonia, Apostadero', 'fldifarm02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 130, 0, 'Armonia, Ancient En Celar', 'dunarm01cash');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 130, 0, 'Armonia, Ancient En Celar', 'dunarm01cash');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 130, 0, 'Armonia, Gloria', 'dunarm03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 130, 0, 'Mage of Madness', 'missionarmmadness');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 146, 0, 'Executor of Hatred', 'missionarmhate');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fallen Soldier', 'Demon', 146, 0, 'Hard : Executor of Hatred', 'missionarmhateh');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fanatic Elite', 'Human', 120, 0, 'Al Quelt Moreza, Holy Water Chamber', 'missiondunalq06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fanatic', 'Human', 15, 0, 'Al Quelt Moreza Hollow', 'missionalqbossa');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire CERBERA', 'Wildlife', 98, 0, 'Whirlpool of Flame', 'btlchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Gargoyle', 'Demon', 70, 0, 'Vegas Javier', 'btlreb06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Jumeau plaque Rouge', 'Golem', 98, 0, 'Mission : Lava Leaf', 'missionchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Lazim-lam', 'Golem', 98, 0, 'Mission : Lava Leaf', 'missionchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Lesser Gargoyle', 'Golem', 98, 0, 'Mission : Lava Leaf', 'missionchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Mahrgorp', 'Wildlife', 98, 0, 'Whirlpool of Flame', 'btlchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Marcurse', 'Wildlife', 98, 0, 'Whirlpool of Flame', 'btlchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Nevare', 'Golem', 98, 0, 'Mission : Lava Leaf', 'missionchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Phobitan', 'Demon', 98, 0, 'Whirlpool of Flame', 'btlchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Phobitan', 'Golem', 98, 0, 'Mission : Lava Leaf', 'missionchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Rufus faux', 'Golem', 98, 0, 'Mission : Lava Leaf', 'missionchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Skeleton General', 'Undead', 97, 0, '3rd Floor of Skulls Dungeon', 'dunust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Skeleton', 'Undead', 107, 0, 'Lago Celeste', 'btlreb05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire  VLADIMIR', 'Golem', 100, 0, 'Mission : Lava Leaf', 'missionchainrush');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fire Zebra-eater', 'Wildlife', 107, 0, 'Lago Celeste', 'btlreb05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Flicky', 'Demon', 141, 0, 'River of Fire', 'fldalt02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fluham', 'Demon', 145, 0, 'River of Fire', 'fldalt02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Flyingfrog', 'Wildlife', 113, 0, 'Bahama, Swamp of Peril', 'btlbah04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Flying sickle', 'Wildlife', 100, 1, 'Rafflesia', 'btlrafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fordoi', 'Demon', 110, 0, 'Distorted Time : Snowfield of the Ice Wizard', 'btlktv05tomb');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Fordoi', 'Demon', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Forgotten Treasure Maiden', 'Golem', 100, 0, 'Forgotten Treasure Maiden Mission', 'missiontreasurefeso2');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Freezing Walter', 'Golem', 56, 0, 'Dr. Torsches Mansion, Reception Hall', 'duntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Frenzy', 'Human', 16, 0, 'Al Quelt Moreza Hollow', 'missionalqbossa');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gabirus Elite', 'Demon', 90, 0, 'Ustiur, Zona Tres', 'btlust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gabirus', 'Demon', 90, 0, 'Ustiur, Zona Tres', 'btlust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gavi di Gavi Elite', 'Undead', 39, 0, 'Porto Bello, The Deck', 'dunptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gavi di Ice', 'Undead', 50, 0, 'Desolate Cliff of Porto Bello', 'btlptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gavi di Light', 'Undead', 59, 0, 'El Tejado Verde', 'btlauch03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gehcos Elite', 'Wildlife', 54, 0, 'Dr. Torsches Mansion, Savage Garden', 'fldtor');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gehcos', 'Wildlife', 65, 0, 'Pradera de Ceniza', 'btljaq02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('General Teus-machina', 'Golem', 145, 1, 'Vernier Mansion, 1st Floor', 'dunile01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ghost', 'Undead', 102, 0, 'Lucifer Castle, Basement Laboratory', 'dunlucifer01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ghostbaron Elite', 'Human', 78, 0, 'El Canon de Diabolica', 'btljaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ghostbaron', 'Human', 82, 0, 'El Canon de Diabolica', 'btljaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ghostly flammer Elite', 'Golem', 82, 0, 'Joaquin Barrier Siege', 'missionthefortressoc');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ghostly friger', 'Golem', 80, 0, 'Prison de Joaquin, Schivarliere', 'dunjaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ghoul Defender', 'Undead', 104, 0, 'Secret Tower 1F', 'dunsctw01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Giant Celegrimworm Elite', 'Golem', 108, 0, 'Mission : Hellbreaker', 'missionhellbreaker');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Giant Celegrimworm', 'Undead', 108, 0, 'Mine Passage', 'duntbk02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Giant Rat', 'Wildlife', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Giant SeaStar', 'Wildlife', 85, 0, 'Island of Fire', 'btlgig01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Giant Skeleton Knightcap', 'Undead', 97, 0, '1st Floor of Skulls Dungeon', 'dunust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('GiganotoSaurus', 'Wildlife', 100, 0, 'Ustiur, Zona Quatro', 'btlust04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gimlet Elite', 'Wildlife', 85, 0, 'Ustiur, Zona Uno', 'btlust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gimlet', 'Wildlife', 100, 1, 'Rafflesia', 'btlrafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gimlet', 'Wildlife', 120, 0, 'Lucifer Castle, Moonlight Garden', 'btllucifer02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('GlacialValkyrie', 'Demon', 105, 0, 'Chaos Requiem for Christmas', 'missionxmassed');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('GlacialValkyrie', 'Demon', 105, 0, 'Chaos Requiem for Christmas', 'missionxmassed');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gluttony', 'Demon', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Godless Ghost', 'Undead', 104, 0, 'Secret Tower 3F', 'dunsctw03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Godless Ghoul Defender', 'Undead', 106, 0, 'Secret Tower 3F', 'dunsctw03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Grassland Comodo', 'Wildlife', 90, 0, 'Rio Albi', 'btlalq02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gray Buffalo', 'Wildlife', 49, 0, 'Thueringenwald', 'btlauch01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Graywolf', 'Wildlife', 5, 0, 'Ferruccio Junction', 'btlreb04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Great hornet Elite', 'Wildlife', 3, 0, 'Reboldoeux, Stone Pit', 'btlreb01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Great hornet', 'Wildlife', 3, 0, 'Reboldoeux, Stone Pit, Work Pit 2', 'missionquarry');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Great hornet', 'Wildlife', 100, 1, 'Individual Raid : Rafflesia', 'missionprivaterafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Great mandra', 'Wildlife', 100, 1, 'Individual Raid : Rafflesia', 'missionprivaterafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Green Sickle', 'Wildlife', 100, 1, 'Rafflesia', 'btlrafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Greenfish', 'Golem', 118, 0, 'Bahama, Underground Cave 2F', 'dunbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Grim-ripper', 'Demon', 100, 0, 'Mission : Chrysalis', 'raidhellvally');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Grim-ripper', 'Undead', 100, 0, 'Valley of Hell', 'missionhellvally');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Grim-ripper', 'Undead', 105, 0, 'Ferruccio Wall', 'btlktv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gullfaxi', 'Golem', 107, 0, 'Mission : Hellbreaker', 'missionhellbreaker');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Gwraig', 'Golem', 120, 0, 'Dramatic Meeting', 'missioncator03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Harrower', 'Wildlife', 80, 0, 'El Canon de Diabolica', 'btljaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Haunted-book Boss', 'Golem', 150, 1, 'Distorted Time : Imperium Rex', 'duncasile02raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Haunted-book', 'Golem', 60, 0, 'Intruder Alert!', 'missionduntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Haunted-candle Elite', 'Golem', 55, 0, 'Dr. Torsches Mansion, Savage Garden', 'fldtor');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Haunted-candle', 'Golem', 55, 0, 'Intruder Alert!', 'missionduntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Haunted-candle', 'Golem', 150, 1, 'Distorted Time : Imperium Rex', 'duncasile02raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Haunted-desk', 'Golem', 60, 0, 'Intruder Alert!', 'missionduntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Haunted-desk', 'Golem', 150, 1, 'Distorted Time : Imperium Rex', 'duncasile02raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Heaven Bacchanalia', 'Golem', 119, 0, 'Sacred Chaos Requiem', 'dunsed04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Heaven Myconid', 'Wildlife', 118, 0, 'Sacred Chaos Requiem', 'dunsed04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Heaven Vespanolla', 'Undead', 120, 1, 'Sacred Chaos Requiem', 'dunsed04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Helena Elite', 'Golem', 59, 0, 'Dr. Torsches Mansion, Grand Library', 'duntor02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Helena', 'Golem', 59, 0, 'Intruder Alert!', 'missionduntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Helena', 'Golem', 120, 0, 'Dramatic Meeting', 'missioncator03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Hell Hound', 'Wildlife', 8, 0, 'Al Quelt Moreza', 'fldalq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Hell Hound', 'Wildlife', 8, 0, 'Cleansing of Al Quelt Moreza', 'missionfldalq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Heretic Elite', 'Human', 120, 0, 'Al Quelt Moreza, Holy Water Chamber', 'missiondunalq06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Hollowed Footman Elite', 'Golem', 58, 0, 'Dr. Torsches Mansion, Reception Hall', 'duntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Hollowed Footman', 'Golem', 58, 0, 'Intruder Alert!', 'missionduntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Honeybee', 'Wildlife', 110, 0, 'Ustiur, Zona Uno', 'btlust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Hound-eater Elite', 'Wildlife', 120, 0, 'Al Quelt Moreza, Holy Water Chamber', 'missiondunalq06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Hound-eater', 'Wildlife', 100, 1, 'Rafflesia', 'btlrafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Hound Elite', 'Wildlife', 8, 0, 'Al Quelt Moreza', 'fldalq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ice Comodo', 'Wildlife', 75, 0, 'El Ruina de Memoria', 'btljaq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ice Skeleton General', 'Undead', 97, 0, '3rd Floor of Skulls Dungeon', 'dunust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ice Skeleton', 'Undead', 50, 0, 'Desolate Cliff of Porto Bello', 'btlptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ice Zebra-eater', 'Wildlife', 51, 0, 'Desolate Cliff of Porto Bello', 'btlptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Illier Magic Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Illier Magic Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Illier Magic Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Illier Magic Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Illier Magic Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Illier Magic Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Imanon Elite', 'Undead', 38, 0, 'Porto Bello, The Deck', 'dunptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Imperial Guardian', 'Human', 132, 0, 'Imperium Glory', 'duncasile03normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Imperial Guardian', 'Human', 132, 0, 'Imperium Glory', 'duncasile03normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Imperial Guardian', 'Human', 132, 0, 'Imperium Glory', 'duncasile03normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Imperial Guardian', 'Human', 132, 0, 'Imperium Glory', 'duncasile03normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Iron Keeper', 'Golem', 120, 0, 'Armonia, El Soltado', 'dunarm05blue');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Ironmaiden Elite', 'Golem', 75, 0, 'Prison de Joaquin, The Mohrgus', 'dunjaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Iskra', 'Demon', 150, 1, 'Portus', 'fldalt03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('JabberwockCap', 'Undead', 79, 0, 'Joaquin Barrier (Siege)', 'missionthefortresso');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jabberwock', 'Undead', 75, 0, 'Memory of Dilos Latemn', 'missionlatem');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jacquinbear Elite', 'Wildlife', 67, 0, 'Crater of Joaquin', 'btljaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jacquinbear', 'Wildlife', 67, 0, 'Rion Dungeon Hollow', 'dunalq05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jacquinbear', 'Wildlife', 72, 0, 'Crater of Joaquin', 'btljaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jacquingrizzly', 'Wildlife', 68, 0, 'Crater of Joaquin', 'btljaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jaquin Comodo Elite', 'Wildlife', 64, 0, 'Rion Plain', 'btlreb03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jaquin Comodo', 'Wildlife', 64, 0, 'Rion Dungeon Corridor', 'dunalq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jaquin Wild-dog', 'Wildlife', 70, 0, 'Crater of Joaquin', 'btljaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jr. Cerberus Of Dark', 'Golem', 104, 0, 'Island of Fire', 'btlgig01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jr. Cerberus Of Shock', 'Golem', 102, 0, 'Island of Fire', 'btlgig01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jumeau plaque Noir', 'Demon', 33, 0, 'Tetra Avernus Road', 'missiondunttr04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jumeau plaque', 'Demon', 104, 0, 'Ferruccio Wall', 'btlktv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Jumpingfish', 'Undead', 107, 0, 'Bahama, Swamp of Darkness', 'btlbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('KING CASTOR', 'Demon', 140, 1, 'Lucifer Castle, Basement Laboratory', 'dunlucifer01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('KING DRAGON-HEADED', 'Golem', 135, 1, 'Lucifer Castle, Basement Laboratory', 'dunlucifer01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Katovicbear', 'Wildlife', 112, 0, 'Snowfield of the Ice Wizard', 'btlktv05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('King-octopus', 'Wildlife', 37, 0, 'Porto Bello(Tutorial)', 'fldptvtuto');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('King Crab', 'Wildlife', 105, 0, 'Island of Fire', 'btlgig01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('King Gehcos', 'Wildlife', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('King Gehcos', 'Wildlife', 150, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Koboldchief Elder', 'Wildlife', 124, 0, 'Meridian of Zeia', 'btlerc01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Lady Sasha', 'Golem', 110, 0, 'Secret Laboratory of Dr. Torsche', 'missionundertor');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Leafing croc', 'Wildlife', 6, 0, 'Ferruccio Junction', 'btlreb04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Lesser Gargoyle Elite', 'Demon', 29, 0, 'Tetra Ruins, Grand Corridor', 'dunttr01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Lesser Gargoyle', 'Demon', 29, 0, 'The Tetra Ruins', 'missionrobber');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Light Skeleton Excutioner', 'Undead', 95, 0, '2nd Floor of Skulls Dungeon', 'dunust02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Light Skeleton General', 'Undead', 97, 0, '3rd Floor of Skulls Dungeon', 'dunust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Light Skeleton Knight', 'Undead', 93, 0, '1st Floor of Skulls Dungeon', 'dunust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Light Zebra-eater', 'Wildlife', 58, 0, 'El Tejado Verde', 'btlauch03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Little Goden Spider', 'Wildlife', 143, 0, 'Camellia Thea', 'fldalt01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Little Horn', 'Wildlife', 1, 0, 'Reboldoeux, Stone Pit', 'btlreb01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Little croc Elite', 'Wildlife', 4, 0, 'Ferruccio Junction', 'btlreb04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Little croc', 'Wildlife', 4, 0, 'Reboldoeux, Stone Pit, Work Pit 2', 'missionquarry');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Lloyd', 'Golem', 56, 0, 'Dr. Torsches Mansion, Reception Hall', 'duntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Lloyd', 'Golem', 110, 0, 'Dr. Torsches Mansion, Annex', 'duntor04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Lloyd', 'Golem', 120, 0, 'Mission: Dr. Torsches Mansion - Basement', 'missionduntor00');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Locke', 'Golem', 109, 0, 'Bahama, Swamp of Darkness', 'btlbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mahrgorp', 'Wildlife', 71, 0, 'Lava Plateau of Joaquin', 'fldjaq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mahrgorp', 'Wildlife', 105, 0, 'El Ruina de Memoria', 'btljaq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mandradora', 'Wildlife', 2, 0, 'Reboldoeux, Stone Pit', 'btlreb01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mandradora', 'Wildlife', 100, 1, 'Rafflesia', 'btlrafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mandradora', 'Wildlife', 120, 0, 'Lucifer Castle, Secret Garden', 'btllucifer01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mandrelrira', 'Wildlife', 6, 0, 'Ferruccio Junction', 'btlreb04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mandrelrira', 'Wildlife', 100, 1, 'Individual Raid : Rafflesia', 'missionprivaterafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Marcurse Elite', 'Wildlife', 120, 0, 'Al Quelt Moreza, Holy Water Chamber', 'missiondunalq06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Marcurse', 'Wildlife', 10, 0, 'Cleansing of Al Quelt Moreza', 'missionfldalq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Masquerader', 'Demon', 98, 0, 'Silent Maze - 1F', 'missiondunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Masquerader', 'Human', 98, 0, 'Silent Maze - 1F', 'dunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mehcos', 'Wildlife', 62, 0, 'Pradera de Ceniza', 'btljaq02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mehcos', 'Wildlife', 62, 0, 'Merchant rank promotion test', 'missionrankdc');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Merman', 'Human', 38, 0, 'Porto Bello, The Deck', 'dunptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mernam chieftain', 'Human', 43, 0, 'Porto Bello, The Deck', 'dunptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mighty Victor', 'Golem', 110, 0, 'Secret Laboratory of Dr. Torsche', 'missionundertor');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Minotauros', 'Demon', 115, 1, 'Ancient Castilla, Temple', 'btlcas03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Monegarm', 'Demon', 102, 0, 'Ferruccio Wall', 'btlktv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mouse', 'Wildlife', 1, 0, 'Underground Prison 1F', 'btlprison02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Movingrock', 'Undead', 101, 0, 'Abertal', 'btltbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mudman General', 'Undead', 96, 0, 'Ancient Skeleton Nest 1F', 'dunust04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Mudman lancer', 'Undead', 98, 0, 'Ancient Skeleton Nest 1F', 'dunust04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Fighter Elite', 'Undead', 104, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Fighter', 'Undead', 101, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Musketeer Elite', 'Undead', 105, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Musketeer', 'Undead', 101, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Scout Elite', 'Undead', 105, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Warlock Elite', 'Undead', 107, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Warlock', 'Undead', 102, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Wizard Elite', 'Undead', 106, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Muertos Wizard', 'Undead', 103, 0, 'Tierra de los Muertos', 'btllos01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Murdur Vordoi', 'Demon', 110, 1, 'Viron, Red Sunset Forest', 'btlviron01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Musescargot Elite', 'Undead', 80, 0, 'Prison de Joaquin, Schivarliere', 'dunjaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Musescargot Rouge', 'Undead', 73, 0, 'Prison de Joaquin, The Mohrgus', 'dunjaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Musescargot', 'Undead', 77, 0, 'Prison de Joaquin, Torture Chamber', 'dunjaq05');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Myconid Elite', 'Wildlife', 112, 0, 'Bahama, Swamp of Peril', 'btlbah04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Myconid', 'Wildlife', 135, 0, 'Mission: Overlord of Element', 'missionbahweek');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('NEST-HAIR HUGANOID', 'Human', 16, 0, 'Al Quelt Moreza, the Parsonage', 'dunalq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('NOSIAR CAPTAIN', 'Undead', 45, 0, 'Porto Bello, The Cabin', 'dunptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Necrobow Soldier', 'Undead', 140, 1, 'Portus', 'fldalt03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Nevare', 'Demon', 31, 0, 'The Sorceress Cherlyn', 'missioncherlyn');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Nosiar Elite', 'Undead', 41, 0, 'Porto Bello, The Deck', 'dunptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Oannes', 'Wildlife', 101, 0, 'Scorching Plateau', 'btlktv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Octopus', 'Wildlife', 102, 0, 'Scorching Plateau', 'btlktv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Oghe', 'Demon', 138, 0, 'Camellia Thea', 'fldalt01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Orge Assassin', 'Demon', 123, 0, 'Meridian of Zeia', 'btlerc01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Orge Bandit', 'Demon', 122, 0, 'Twilight of Zeia', 'btlerc02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Orge Mage', 'Demon', 110, 0, 'Reboldoeux Culverts', 'dunsub');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Orge Predators', 'Demon', 112, 0, 'Reboldoeux Culverts', 'dunsub');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Orge Werewolf Defender', 'Demon', 110, 0, 'Reboldoeux Culverts', 'dunsub');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('PASIAR CAPTAIN', 'Undead', 48, 0, 'Porto Bello, The Hold', 'dunptv03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('PHOBITAN general', 'Demon', 100, 0, 'Topolo Durga', 'btlttr03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('POLLUX of Chaos', 'Demon', 132, 0, 'Secret Temple', 'btlshadowtemple');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Palm Tree Crab Elite', 'Wildlife', 60, 0, 'Outside Bahia', 'fldgig');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Palm Tree King Crab', 'Wildlife', 80, 0, 'Island of Fire', 'btlgig01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Pasiar  Elite', 'Undead', 43, 0, 'Porto Bello, The Cabin', 'dunptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Phobitan Elite', 'Demon', 24, 0, 'Tetra Hill', 'btlttr01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Phobitan', 'Demon', 24, 0, 'Tetra Hill', 'btlttr01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Phobitan', 'Demon', 26, 0, 'Tetra Ruins', 'fldttr');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Phobitan', 'Demon', 26, 0, 'The Tetra Ruins', 'missionrobber');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Plateau anchor Elite', 'Undead', 101, 0, 'Scorching Plateau', 'btlktv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Pyg', 'Golem', 120, 0, 'Dramatic Meeting', 'missioncator03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Quest_Tree01', 'Misc', 55, 0, 'El Tejado Verde', 'btlauch03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rabiabe', 'Demon', 150, 1, 'Camellia Thea', 'fldalt01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rabioso', 'Demon', 136, 0, 'Camellia Thea', 'fldalt01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Reboldoeux Soldier', 'Human', 1, 0, 'Training Center of Soldier of Reboldoeux', 'arenacity');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Red  Elemental', 'Golem', 122, 0, 'Twisted Time : Imperium Rex', 'duncasile02hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Red  Elemental', 'Golem', 135, 0, 'Mission: Overlord of Element', 'missionbahweek');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Red SpiderCrab', 'Wildlife', 109, 0, 'Bahama, Swamp of Darkness', 'btlbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Republican', 'Human', 100, 0, 'Ferruccio Junction', 'btlreb04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Resistance, Codor', 'Human', 115, 0, 'Shelter of Resistance', 'btlbst01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Resistance, Dogi', 'Human', 115, 0, 'Shelter of Resistance', 'btlbst01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Resistance, Mullen', 'Human', 115, 0, 'Shelter of Resistance', 'btlbst01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Resistance, Queman', 'Human', 115, 0, 'Shelter of Resistance', 'btlbst01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rifle blood Navy Captain', 'Human', 125, 0, 'Kielce - Training Camp (Night)', 'fldbst02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rion Half-moon Bear', 'Wildlife', 64, 0, 'Rion Dungeon Corridor', 'dunalq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rogue : Bomb agent Elite', 'Human', 50, 0, 'Thueringenwald', 'btlauch01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rogue : Hammer agent Elite', 'Human', 52, 0, 'El Lago de Tres Hermanas', 'btlauch02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rogue : Slash agent Elite', 'Human', 52, 0, 'El Lago de Tres Hermanas', 'btlauch02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rogue : morgan Elite', 'Human', 100, 0, 'Topolo Durga', 'btlttr03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rogue : read', 'Human', 99, 0, 'Topolo Durga', 'btlttr03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rufus faux', 'Demon', 32, 0, 'The Sorceress Cherlyn', 'missioncherlyn');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rusty Eigleschvarlier', 'Golem', 81, 0, 'Prison de Joaquin, Schivarliere', 'dunjaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rusty Eigleschvarlier', 'Golem', 81, 0, 'Prison de Joaquin, Schivarliere', 'dunjaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rusty Musescargot Rouge', 'Undead', 72, 0, 'Prison de Joaquin, The Mohrgus', 'dunjaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Rusty Musescargot', 'Undead', 79, 0, 'Prison de Joaquin, Schivarliere', 'dunjaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('SHARFFENBERGER THE CURSE', 'Human', 130, 1, 'Desolate Cliff of Porto Bello', 'btlptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('SILKHAT HUGANOID', 'Human', 130, 0, 'Poison Yard', 'btlpoisonyard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Saberboar', 'Wildlife', 18, 0, 'Cathari Falls', 'btlalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sabertiger', 'Wildlife', 90, 0, 'Ustiur, Zona Uno', 'btlust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sasa Assassin', 'Wildlife', 131, 0, 'Castilla, Temple', 'btlcas02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sasa', 'Wildlife', 110, 0, 'Mission : Demonic Sphinx', 'missionmasungcas01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sasa', 'Wildlife', 131, 0, 'Ancient Castilla, Temple', 'btlcas03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sasha', 'Golem', 58, 0, 'Dr. Torsches Mansion, Reception Hall', 'duntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sasha', 'Golem', 110, 0, 'Dr. Torsches Mansion, Annex', 'duntor04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sasha', 'Golem', 120, 0, 'Mission: Dr. Torsches Mansion - Basement', 'missionduntor00');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Scarlet claw', 'Human', 40, 0, 'Attack of Escudo Pecher', 'missionescudo');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('SeaStar Elite', 'Wildlife', 65, 0, 'Outside Bahia', 'fldgig');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sehcos', 'Wildlife', 62, 0, 'Pradera de Ceniza', 'btljaq02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sehcos', 'Wildlife', 62, 0, 'Merchant rank promotion test', 'missionrankdc');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sepulveda THE bonny Elite', 'Human', 98, 0, 'Topolo Durga', 'btlttr03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Shield blood Navy Soldier', 'Human', 125, 0, 'Kielce - Training Camp (Night)', 'fldbst02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Siegmund', 'Demon', 29, 0, 'Tetra Catacomb', 'dunttr02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Silverhat Phobitan', 'Demon', 65, 0, 'Rion Dungeon Corridor', 'dunalq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Attacker Elite', 'Undead', 77, 0, 'Old Port of Coimbra', 'btlcoim02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Elite', 'Undead', 19, 0, 'Cathari Falls', 'btlalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Excutioner Elite', 'Undead', 60, 0, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Excutioner', 'Undead', 60, 0, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton General Elite', 'Undead', 61, 0, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton General', 'Undead', 61, 0, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Knight Elite', 'Undead', 58, 0, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Knight', 'Undead', 58, 0, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Musketeer Elite', 'Undead', 59, 0, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Musketeer', 'Undead', 59, 0, 'Dungeon Ruins', 'btlprison01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton Rapter Elite', 'Undead', 98, 0, 'Ustiur, Zona Quatro', 'btlust04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton', 'Undead', 19, 0, 'Cathari Falls', 'btlalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton', 'Undead', 78, 0, 'Old Port of Coimbra', 'btlcoim02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton', 'Undead', 100, 0, 'Ancient Skeleton Nest 1F', 'dunust04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton defender', 'Undead', 76, 0, 'Old Port of Coimbra', 'btlcoim02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton lancer Elite', 'Undead', 94, 0, '1st Floor of Skulls Dungeon', 'dunust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton lancer', 'Undead', 94, 0, '1st Floor of Skulls Dungeon', 'dunust01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton of revenent', 'Undead', 95, 0, 'Room of the Dead', 'dunustboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Skeleton of revenent', 'Undead', 97, 0, 'Room of the Dead', 'dunustboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Slave Chief', 'Demon', 140, 1, 'Portus', 'fldalt03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sloth', 'Undead', 120, 0, 'Lucifer Castle, Reception Hall of Oblivion', 'duncaslucifer04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sloth', 'Undead', 120, 1, 'Lucifer Castle, Reception Hall of Oblivion', 'duncaslucifer04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Snowfield Bear', 'Wildlife', 108, 0, 'Katovic Snowfield', 'btlktv03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Snowfield Lazim-lam', 'Demon', 105, 0, 'Katovic Snowfield', 'btlktv03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Snowfield Swamp monkey Elite', 'Wildlife', 109, 0, 'Frozen Plain', 'btlktv04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Snowfield wolf Elite', 'Wildlife', 106, 0, 'Katovic Snowfield', 'btlktv03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Snowman', 'Golem', 1, 0, 'Tower of the Ice Wizard for Christmas', 'missionxmasktv');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Spear blood Navy Soldier', 'Human', 125, 0, 'Kielce - Training Camp', 'fldbst01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('SpiderCrab Elite', 'Wildlife', 115, 0, 'Bahama, Underground Cave 1F', 'dunbah01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Spikedrock Elite', 'Undead', 101, 0, 'Abertal', 'btltbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Spinosaurus', 'Wildlife', 100, 0, 'Ustiur, Zona Quatro', 'btlust04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Steel anchor', 'Undead', 53, 0, 'Desolate Cliff of Porto Bello', 'btlptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Stegosaurus', 'Wildlife', 99, 0, 'Ustiur, Zona Quatro', 'btlust04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Stone Gargoyle', 'Demon', 27, 0, 'The Tetra Ruins', 'missionrobber');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Stripe Saberboar', 'Wildlife', 6, 0, 'Ferruccio Junction', 'btlreb04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Sunfla swampmon', 'Wildlife', 53, 0, 'Thueringenwald', 'btlauch01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Swamp Ghouloftreasure Elite', 'Undead', 105, 0, 'Bahama, Marshlands', 'btlbah01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Swamp Jumpingfish Elite', 'Human', 111, 0, 'Bahama, Swamp of Peril', 'btlbah04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Swamp SpiderCrab Elite', 'Wildlife', 105, 0, 'Bahama, Marshlands', 'btlbah01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Swamp SpiderCrab', 'Wildlife', 105, 0, 'Bahama, Marshlands', 'btlbah01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Swamp Treasuremimic', 'Undead', 108, 0, 'Bahama, Swamp of Darkness', 'btlbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('THE CHRYSALIS', 'Demon', 85, 0, 'Joaquin, Corridor of Assize', 'dunjaqboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Talk Monster', 'Misc', 100, 0, 'Bahama, Altar of Heaven', 'btlbah06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Taurus', 'Wildlife', 106, 0, 'Bahama, Marshlands', 'btlbah01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tcapy Elite', 'Wildlife', 104, 0, 'Toubkal Mine', 'duntbkboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tcapy', 'Wildlife', 104, 0, 'Capybara Plantation', 'duntbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tcapycruel Elite', 'Wildlife', 105, 0, 'Capybara Plantation', 'duntbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tcapycruel', 'Wildlife', 105, 0, 'Capybara Plantation', 'duntbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tcapyranger Elite', 'Golem', 105, 0, 'Mission : Hellbreaker', 'missionhellbreaker');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tcapyranger', 'Golem', 105, 0, 'Mission : Hellbreaker', 'missionhellbreaker');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tcapywarrior Elite', 'Golem', 106, 0, 'Mission : Hellbreaker', 'missionhellbreaker');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tcapywarrior', 'Golem', 106, 0, 'Mission : Hellbreaker', 'missionhellbreaker');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tendercore', 'Golem', 130, 0, 'Trumans Secret Workshop B1F', 'dunclockmaze01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('The King of meadow', 'Undead', 80, 0, 'Vegas Javier', 'btlreb06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('The Veilant', 'Golem', 142, 0, 'Mission: Joaquin Basement', 'missiondunjaqunder');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Thief Elrog', 'Human', 115, 0, 'Kielce - Night', 'bstnight');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Thief Gawein', 'Human', 115, 0, 'Kielce Night Combat', 'missionbstnight');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Thief Joel', 'Human', 115, 0, 'Kielce Night Combat', 'missionbstnight');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Thief Rufers', 'Human', 115, 0, 'Kielce - Night', 'bstnight');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Thoracotomy', 'Undead', 100, 0, '2nd Floor of Skulls Dungeon', 'dunust02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tiger hornet', 'Wildlife', 7, 0, 'Ferruccio Junction', 'btlreb04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tiger hornet', 'Wildlife', 100, 1, 'Individual Raid : Rafflesia', 'missionprivaterafflesia');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Torchere', 'Undead', 120, 0, 'Lucifer Castle, Reception Hall of Oblivion', 'duncaslucifer04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tortoise', 'Wildlife', 48, 0, 'Porto Bello, Deserted Quay', 'btlptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Treasure Merman', 'Human', 100, 0, 'Porto Bello, The Deck', 'dunptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Treasure Phobitan', 'Demon', 100, 0, 'Castilla, Ruins', 'btlcas01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Treasure Phobitan', 'Demon', 100, 0, 'Tetra Grand Chapel', 'dunttr06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Treasure Phobitan', 'Demon', 100, 0, 'Tetra Treasure Room', 'missionttrtreasurea');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Treasure Zealot', 'Human', 100, 0, 'Al Quelt Moreza Treasure Chamber', 'missionalqtreasurea');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Treasuremaiden', 'Golem', 100, 0, 'Prison de Joaquin, The Mohrgus', 'dunjaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Treasuremaiden', 'Golem', 100, 0, 'Joaquin Treasure Chamber', 'missionjaqtreasure');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Treasuremimic Elite', 'Undead', 117, 0, 'Bahama, Underground Cave 2F', 'dunbah02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('TriCeratops', 'Wildlife', 87, 0, 'Ustiur, Zona Dos', 'btlust02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Tvanjesty', 'Wildlife', 80, 0, 'El Canon de Diabolica', 'btljaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Twin-headed', 'Demon', 98, 0, 'Silent Maze - 1F', 'missiondunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Twin-headed', 'Golem', 98, 0, 'Silent Maze - 1F', 'dunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Undead soldier', 'Undead', 80, 0, 'Spirit of Joaquin', 'missionjaqque01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Underghost', 'Undead', 80, 0, 'Island of Fire', 'btlgig01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Underghost', 'Undead', 80, 0, 'Island of Fire', 'btlgig01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Underghost', 'Undead', 80, 1, 'Kielce - Night', 'bstnight');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('VLADIMIR', 'Demon', 81, 0, 'Joaquin, Corridor of Assize 1', 'missionjaq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vampire Bat Elite', 'Undead', 104, 0, 'Toubkal Mine', 'duntbkboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vampire Bat', 'Undead', 104, 0, 'Capybara Plantation', 'duntbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vampire Bat lord Elite', 'Undead', 105, 0, 'Capybara Plantation', 'duntbk01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vampire Bat lord', 'Undead', 105, 0, 'Toubkal Mine', 'duntbkboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vedanobah Elite', 'Human', 11, 0, 'Al Quelt Moreza, the Nartex', 'dunalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vedanobah', 'Human', 10, 0, 'Al Quelt Moreza', 'fldalq');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vedanobah', 'Human', 34, 0, 'Battle Colosseum', 'btlliberty2');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Veloci Raptor Elite', 'Wildlife', 89, 0, 'Ustiur, Zona Tres', 'btlust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Veloci Raptor', 'Wildlife', 89, 0, 'Ustiur, Zona Tres', 'btlust03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vespanolla', 'Undead', 120, 0, 'Tierra Putrefacta', 'btlsed01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Violence Bearworker Elite', 'Golem', 107, 0, 'Mission : Hellbreaker', 'missionhellbreaker');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Violence Bearworker', 'Golem', 107, 0, 'Mission : Hellbreaker', 'missionhellbreaker');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Visage Elite', 'Demon', 32, 0, 'Tetra Golden Road', 'dunttr03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Visage Noir', 'Demon', 32, 0, 'The Sorceress Cherlyn', 'missioncherlyn');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Visage Rouge', 'Demon', 32, 0, 'The Sorceress Cherlyn', 'missioncherlyn');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Visage', 'Demon', 103, 0, 'Ferruccio Wall', 'btlktv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Vordoi', 'Demon', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('WAHLANSCHE', 'Undead', 46, 0, 'Porto Bello, Deserted Quay', 'btlptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('WEIRD-KNIGHT', 'Golem', 83, 0, 'Prison de Joaquin, Schivarliere', 'dunjaq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('WEIRD-KNIGHT', 'Golem', 100, 0, 'Silent Maze - 1F', 'dunsil01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Walter', 'Golem', 56, 0, 'Dr. Torsches Mansion, Reception Hall', 'duntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Walter', 'Golem', 100, 0, 'Dr. Torsches Mansion, Reception Hall', 'duntor01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Walter', 'Golem', 110, 0, 'Dr. Torsches Mansion, Annex', 'duntor04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Walter', 'Golem', 120, 0, 'Mission: Dr. Torsches Mansion - Basement', 'missionduntor00');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Werebear Juggernaut', 'Wildlife', 120, 1, 'Meridian of Zeia', 'btlerc01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Werebear Slayer', 'Wildlife', 120, 1, 'Meridian of Zeia', 'btlerc01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('White Iron Keeper', 'Golem', 120, 1, 'Ruler of Rage', 'missionarmfury');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('White Iron Keeper', 'Golem', 146, 1, 'Armonia, Biego', 'dunarm04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Whitewolf Elite', 'Wildlife', 18, 0, 'Cathari Falls', 'btlalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Wild-dog', 'Wildlife', 54, 0, 'Dr. Torsches Mansion, Savage Garden', 'fldtor');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Winged-gargoyle', 'Demon', 27, 0, 'Lucifer Castle, Basement Laboratory', 'dunlucifer01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Winged-gargoyle', 'Demon', 27, 0, 'The Tetra Ruins', 'missionrobber');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Wolf', 'Wildlife', 64, 0, 'Rion Dungeon Corridor', 'dunalq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Wraig', 'Golem', 110, 0, 'Dr. Torsches Mansion, Annex', 'duntor04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Wraith', 'Undead', 104, 0, 'Secret Tower 3F', 'dunsctw03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Zahrgorp', 'Wildlife', 107, 0, 'El Ruina de Memoria', 'btljaq04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Zavi di Gavi', 'Undead', 41, 0, 'Porto Bello, The Cabin', 'dunptv02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Zealot Elite', 'Human', 13, 0, 'Al Quelt Moreza, the Parsonage', 'dunalq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Zealot', 'Human', 12, 0, 'Al Quelt Moreza, the Parsonage', 'dunalq03');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Zebra-eater Elite', 'Wildlife', 9, 0, 'Al Quelt Moreza, the Nartex', 'dunalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Zebra-eater', 'Wildlife', 9, 0, 'Al Quelt Moreza, the Nartex', 'dunalq01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Zombie-merman Elite', 'Undead', 41, 0, 'Porto Bello, The Deck', 'dunptv01');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('Zombie-merman', 'Undead', 41, 0, 'Porto Bello, St. Cathrinas Saloon', 'missionptvbossa');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('cockatricebig', 'Wildlife', 70, 0, 'Bonavista River', 'btlreb02');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('einschwer', 'Demon', 135, 1, 'Silent Maze Sanctuary', 'dunsilboss');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('forgottenclaw', 'Human', 44, 0, 'Porto Bello, Hidden Deck', 'dunptv04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('forgotteneigleschivarlier', 'Golem', 83, 0, 'Joaquin, Laboratory Block', 'dunjaq06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('forgottengargoyle', 'Demon', 31, 0, 'Tetra Grand Chapel', 'dunttr06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('forgottenhelena', 'Golem', 60, 0, 'Dr. Torsches Mansion, Annex', 'duntor04tw');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('forgottenmermanzombie', 'Undead', 45, 0, 'Porto Bello, Hidden Deck', 'dunptv04');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('forgottennevare', 'Demon', 33, 0, 'Tetra Grand Chapel', 'dunttr06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('forgottentwinheaded', 'Golem', 81, 0, 'Joaquin, Laboratory Block', 'dunjaq06');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('forgottenwalter', 'Golem', 58, 0, 'Dr. Torsches Mansion, Annex', 'duntor04tw');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Arma', 'duncasile01normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Distorted Time : Imperium Arma', 'duncasile01raid');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Twisted Time : Imperium Rex', 'duncasile02hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Twisted Time : Imperium Rex', 'duncasile02hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Twisted Time : Imperium Rex', 'duncasile02hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Rex', 'duncasile02normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Rex', 'duncasile02normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Rex', 'duncasile02normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 132, 0, 'Imperium Rex', 'duncasile02normal');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Arma', 'duncasile01hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('illier Soldier', 'Human', 138, 0, 'Twisted Time : Imperium Rex', 'duncasile02hard');
INSERT INTO monsters (name, race, level, is_boss, location, map_slug) VALUES ('maiden', 'Golem', 75, 0, 'Mystic Treasure Maiden Mission', 'missiontreasurefeso');
