-- Migration 015: Thai map names (123 maps)
-- Transliteration rules:
--   Proper nouns → Thai phonetic
--   Common words (Dungeon, Forest, Prison, Cave, etc.) → Thai translation
--   Floor numbers → ชั้น N

UPDATE maps SET name_th = 'ดันเจียนหัวกะโหลก ชั้น 2' WHERE name = '2nd Floor of Skulls Dungeon';
UPDATE maps SET name_th = 'อเบอร์ทาล' WHERE name = 'Abertal';
UPDATE maps SET name_th = 'อัล เคลท์ โมเรซา, อาร์เคด' WHERE name = 'Al Quelt Moreza, the Arcade';
UPDATE maps SET name_th = 'อัล เคลท์ โมเรซา, โบสถ์' WHERE name = 'Al Quelt Moreza, the Parsonage';
UPDATE maps SET name_th = 'คาสติยาโบราณ, วิหาร' WHERE name = 'Ancient Castilla, Temple';
UPDATE maps SET name_th = 'รังโครงกระดูกโบราณ ชั้น 2' WHERE name = 'Ancient Skeleton Nest 2F';
UPDATE maps SET name_th = 'ที่พักพิงโครงกระดูกโบราณ ชั้น 2' WHERE name = 'Ancient Skeleton Shelter 2F';
UPDATE maps SET name_th = 'อาร์โมเนีย' WHERE name = 'Armonia';
UPDATE maps SET name_th = 'อาร์โมเนีย, เอน เซลาร์โบราณ' WHERE name = 'Armonia, Ancient En Celar';
UPDATE maps SET name_th = 'อาร์โมเนีย, อโพสตาเดโร' WHERE name = 'Armonia, Apostadero';
UPDATE maps SET name_th = 'อาร์โมเนีย, เอล อาดิโอ' WHERE name = 'Armonia, El Adio';
UPDATE maps SET name_th = 'อาร์โมเนีย, เอล เทมโพล' WHERE name = 'Armonia, El Templo';
UPDATE maps SET name_th = 'อาร์โมเนีย, กลอเรีย' WHERE name = 'Armonia, Gloria';
UPDATE maps SET name_th = 'บาฮาม่า, แท่นบูชาสวรรค์' WHERE name = 'Bahama, Altar of Heaven';
UPDATE maps SET name_th = 'บาฮาม่า, ที่ซ่อนใต้ดินโบราณ ชั้น 1' WHERE name = 'Bahama, Ancient Underground Hiding Place 1F';
UPDATE maps SET name_th = 'บาฮาม่า, ป่าเทพครึ่งมนุษย์' WHERE name = 'Bahama, Demigod Forest';
UPDATE maps SET name_th = 'บาฮาม่า, หนองบึง' WHERE name = 'Bahama, Marshlands';
UPDATE maps SET name_th = 'บาฮาม่า, หนองนิรันดร์' WHERE name = 'Bahama, Swamp of Eternity';
UPDATE maps SET name_th = 'บาฮาม่า, ถ้ำใต้ดิน ชั้น 1' WHERE name = 'Bahama, Underground Cave 1F';
UPDATE maps SET name_th = 'บาฮาม่า, บ้านแม่มด' WHERE name = 'Bahama, Witchs House';
UPDATE maps SET name_th = 'บาฮาม่า, ห้องแม่มด' WHERE name = 'Bahama, Witchs Room';
UPDATE maps SET name_th = 'ที่ราบเบเดล' WHERE name = 'Bedel Plain';
UPDATE maps SET name_th = 'แม่น้ำโบนาวิสตา' WHERE name = 'Bonavista River';
UPDATE maps SET name_th = 'ทำเนียบผู้สำเร็จราชการบริสเทีย' WHERE name = 'Bristia Government General';
UPDATE maps SET name_th = 'กาเบซา เด กิกันเต' WHERE name = 'Cabeza de Gigante';
UPDATE maps SET name_th = 'ไร่คาปิบาร่า' WHERE name = 'Capybara Plantation';
UPDATE maps SET name_th = 'คาสติยา, เหมือง' WHERE name = 'Castilla, Mine';
UPDATE maps SET name_th = 'คาสติยา, ซากปรักหักพัง' WHERE name = 'Castilla, Ruins';
UPDATE maps SET name_th = 'คาสติยา, หอคอยแห่งความโกลาหล' WHERE name = 'Castilla, Tower of Chaos';
UPDATE maps SET name_th = 'ซิเต เด เรโบลดูซ์' WHERE name = 'Cite de Reboldoeux';
UPDATE maps SET name_th = 'ล็อบบี้ชั้นใต้ดินหอนาฬิกา' WHERE name = 'Clock Tower Basement Lobby';
UPDATE maps SET name_th = 'โคราซอน เด กิกันเต' WHERE name = 'Corazon de Gigante';
UPDATE maps SET name_th = 'ปล่องภูเขาไฟโจควิน' WHERE name = 'Crater of Joaquin';
UPDATE maps SET name_th = 'อัล เคลท์ โมเรซาปีศาจ, อาร์เคด' WHERE name = 'Demonic Al Quelt Moreza Hollow, Arcade';
UPDATE maps SET name_th = 'เททราปีศาจ, สุสานใต้ดิน' WHERE name = 'Demonic Tetra, Catacomb';
UPDATE maps SET name_th = 'หน้าผาร้างแห่งปอร์โต เบลโล' WHERE name = 'Desolate Cliff of Porto Bello';
UPDATE maps SET name_th = 'กาลบิดเบือน : อิมเพเรียม เร็กซ์' WHERE name = 'Distorted Time : Imperium Rex';
UPDATE maps SET name_th = 'กาลบิดเบือน : คฤหาสน์ทอร์เชส' WHERE name = 'Distorted Time : Torsches Mansion';
UPDATE maps SET name_th = 'คฤหาสน์ ดร.ทอร์เชส, อาคารผนวก' WHERE name = 'Dr. Torsches Mansion, Annex';
UPDATE maps SET name_th = 'คฤหาสน์ ดร.ทอร์เชส, ห้องรับรอง' WHERE name = 'Dr. Torsches Mansion, Reception Hall';
UPDATE maps SET name_th = 'ซากดันเจียน' WHERE name = 'Dungeon Ruins';
UPDATE maps SET name_th = 'เอล ลาโก เด เตรส แอร์มานัส' WHERE name = 'El Lago de Tres Hermanas';
UPDATE maps SET name_th = 'เอล เตฮาโด เบร์เด' WHERE name = 'El Tejado Verde';
UPDATE maps SET name_th = 'สี่แยกเฟอร์รุชโช' WHERE name = 'Ferruccio Junction';
UPDATE maps SET name_th = 'ฟรูริโอ' WHERE name = 'Frourio';
UPDATE maps SET name_th = 'รังโครงกระดูกโบราณที่ซ่อนอยู่' WHERE name = 'Hidden Ancient Skeleton Nest';
UPDATE maps SET name_th = 'หอคอยพ่อมดน้ำแข็ง - ชั้น 1' WHERE name = 'Ice Wizards Tower - 1F';
UPDATE maps SET name_th = 'หอคอยพ่อมดน้ำแข็ง - ชั้น 3' WHERE name = 'Ice Wizards Tower - 3F';
UPDATE maps SET name_th = 'หอคอยพ่อมดน้ำแข็ง - ชั้น 5' WHERE name = 'Ice Wizards Tower - 5F';
UPDATE maps SET name_th = 'อิลลิเซีย' WHERE name = 'Illisia';
UPDATE maps SET name_th = 'อิมเพเรียม กลอรี' WHERE name = 'Imperium Glory';
UPDATE maps SET name_th = 'ภายในปล่องภูเขาไฟ' WHERE name = 'Inside Crater';
UPDATE maps SET name_th = 'เกาะไฟ' WHERE name = 'Island of Fire';
UPDATE maps SET name_th = 'โจควิน, ทางเดินแห่งการพิพากษา' WHERE name = 'Joaquin, Corridor of Assize';
UPDATE maps SET name_th = 'ทุ่งหิมะคาโตวิช' WHERE name = 'Katovic Snowfield';
UPDATE maps SET name_th = 'เคียลเซ' WHERE name = 'Kielce';
UPDATE maps SET name_th = 'เคียลเซ - กลางคืน' WHERE name = 'Kielce - Night';
UPDATE maps SET name_th = 'เคียลเซ - ค่ายฝึก' WHERE name = 'Kielce - Training Camp';
UPDATE maps SET name_th = 'ลาโก เซเลสเต' WHERE name = 'Lago Celeste';
UPDATE maps SET name_th = 'ลอส โทลดอส' WHERE name = 'Los Toldos';
UPDATE maps SET name_th = 'ปราสาทลูซิเฟอร์, ห้องทดลองใต้ดิน' WHERE name = 'Lucifer Castle, Basement Laboratory';
UPDATE maps SET name_th = 'ปราสาทลูซิเฟอร์, ทางเดินมรณะ' WHERE name = 'Lucifer Castle, Death Corridor';
UPDATE maps SET name_th = 'ปราสาทลูซิเฟอร์, สวนแสงจันทร์' WHERE name = 'Lucifer Castle, Moonlight Garden';
UPDATE maps SET name_th = 'ปราสาทลูซิเฟอร์, สวนลับ' WHERE name = 'Lucifer Castle, Secret Garden';
UPDATE maps SET name_th = 'เส้นเมริเดียนแห่งเซอา' WHERE name = 'Meridian of Zeia';
UPDATE maps SET name_th = 'ภารกิจ : คริซาลิส' WHERE name = 'Mission : Chrysalis';
UPDATE maps SET name_th = 'ภารกิจ : มิโนทอรอสปีศาจ' WHERE name = 'Mission : Demonic Minotauros';
UPDATE maps SET name_th = 'ภารกิจ : เฮลล์เบรกเกอร์' WHERE name = 'Mission : Hellbreaker';
UPDATE maps SET name_th = 'ภารกิจ: ถ้ำบาฮาม่าปีศาจ' WHERE name = 'Mission: Demonic Bahama Cave';
UPDATE maps SET name_th = 'ภารกิจ: คฤหาสน์ ดร.ทอร์เชสปีศาจ' WHERE name = 'Mission: Demonic Dr. Torsches Mansion';
UPDATE maps SET name_th = 'ภารกิจ: ป้อมออคัลตาปีศาจ' WHERE name = 'Mission: Demonic Occulta Fortress';
UPDATE maps SET name_th = 'ภารกิจ: คุกโจควินปีศาจ' WHERE name = 'Mission: Demonic Prison de Joaquin';
UPDATE maps SET name_th = 'ภารกิจ: หอคอยลับปีศาจ' WHERE name = 'Mission: Demonic Secret Tower';
UPDATE maps SET name_th = 'ภารกิจ: เหมืองตูบคาลปีศาจ' WHERE name = 'Mission: Demonic Toubkal Mine';
UPDATE maps SET name_th = 'ภารกิจ: ชั้นใต้ดินโจควิน' WHERE name = 'Mission: Joaquin Basement';
UPDATE maps SET name_th = 'ป้อมออคัลตา' WHERE name = 'Occulta Fortress';
UPDATE maps SET name_th = 'ท่าเรือเก่าโคอิมบรา' WHERE name = 'Old Port of Coimbra';
UPDATE maps SET name_th = 'เปกาดิยา' WHERE name = 'Pegadilla';
UPDATE maps SET name_th = 'ท่าเรือบาเอีย' WHERE name = 'Port of Bahia';
UPDATE maps SET name_th = 'ปอร์โต เบลโล, ดาดฟ้าลับ' WHERE name = 'Porto Bello, Hidden Deck';
UPDATE maps SET name_th = 'ปอร์โต เบลโล, ห้องกัปตัน' WHERE name = 'Porto Bello, The Cabin';
UPDATE maps SET name_th = 'ปอร์โต เบลโล, ห้องเก็บของ' WHERE name = 'Porto Bello, The Hold';
UPDATE maps SET name_th = 'ปอร์ตุส' WHERE name = 'Portus';
UPDATE maps SET name_th = 'คุกโจควิน, แท่นบูชาแห่งความสิ้นหวัง' WHERE name = 'Prison de Joaquin, Altar of Despair';
UPDATE maps SET name_th = 'คุกโจควิน, ชิวาร์ลิแอร์' WHERE name = 'Prison de Joaquin, Schivarliere';
UPDATE maps SET name_th = 'คุกโจควิน, ห้องทรมาน' WHERE name = 'Prison de Joaquin, Torture Chamber';
UPDATE maps SET name_th = 'ควิริตาทิโอ, กยัลลาร์ฮอร์น' WHERE name = 'Quiritatio, Gjallarhorn';
UPDATE maps SET name_th = 'ราฟเฟลเซีย' WHERE name = 'Rafflesia';
UPDATE maps SET name_th = 'เรโบลดูซ์, ประตูราชินี' WHERE name = 'Reboldoeux, Queens Gate';
UPDATE maps SET name_th = 'เรดแฮท' WHERE name = 'Red Hat';
UPDATE maps SET name_th = 'ทางเดินดันเจียนไรออน' WHERE name = 'Rion Dungeon Corridor';
UPDATE maps SET name_th = 'ที่ราบไรออน' WHERE name = 'Rion Plain';
UPDATE maps SET name_th = 'ห้องแห่งความตาย' WHERE name = 'Room of the Dead';
UPDATE maps SET name_th = 'ถนนหลวง' WHERE name = 'Royal Road';
UPDATE maps SET name_th = 'ที่ซ่อนศักดิ์สิทธิ์แห่งเคออสเรเควียม' WHERE name = 'Sacred Chaos Requiem Hiding Place';
UPDATE maps SET name_th = 'ที่ราบสูงแผดเผา' WHERE name = 'Scorching Plateau';
UPDATE maps SET name_th = 'หอคอยลับ ชั้น 1' WHERE name = 'Secret Tower 1F';
UPDATE maps SET name_th = 'หอคอยลับ ชั้น 3' WHERE name = 'Secret Tower 3F';
UPDATE maps SET name_th = 'เขาวงกตเงียบ - ชั้น 1' WHERE name = 'Silent Maze - 1F';
UPDATE maps SET name_th = 'สถานศักดิ์สิทธิ์เขาวงกตเงียบ' WHERE name = 'Silent Maze Sanctuary';
UPDATE maps SET name_th = 'เททรา, ถนนอเวอร์นัส' WHERE name = 'Tetra Avernus Road';
UPDATE maps SET name_th = 'เททรา, ถนนทอง' WHERE name = 'Tetra Golden Road';
UPDATE maps SET name_th = 'เททรา, ที่ซ่อน' WHERE name = 'Tetra Hideout';
UPDATE maps SET name_th = 'ซากเททรา, ทางเดินใหญ่' WHERE name = 'Tetra Ruins, Grand Corridor';
UPDATE maps SET name_th = 'กาลบิดเบือน: อิมเพเรียม กลอรี' WHERE name = 'The Distorted time: Imperium Glory';
UPDATE maps SET name_th = 'ห้องโบราณวัตถุเททรา' WHERE name = 'The Tetra Antiquities Room';
UPDATE maps SET name_th = 'ทือริงเกนวาลด์' WHERE name = 'Thueringenwald';
UPDATE maps SET name_th = 'เทียร์รา ปูเตรฟัคตา' WHERE name = 'Tierra Putrefacta';
UPDATE maps SET name_th = 'ยอดหอคอยลับ' WHERE name = 'Top of Secret Tower';
UPDATE maps SET name_th = 'เหมืองตูบคาล' WHERE name = 'Toubkal Mine';
UPDATE maps SET name_th = 'ห้องทดลองลับของทรูแมน' WHERE name = 'Trumans Secret Laboratory';
UPDATE maps SET name_th = 'โรงงานลับของทรูแมน ชั้นใต้ดิน 1' WHERE name = 'Trumans Secret Workshop B1F';
UPDATE maps SET name_th = 'สนธยาแห่งเซอา' WHERE name = 'Twilight of Zeia';
UPDATE maps SET name_th = 'กาลบิดเบี้ยว : อิมเพเรียม เร็กซ์' WHERE name = 'Twisted Time : Imperium Rex';
UPDATE maps SET name_th = 'อัสเทียร์, ค่ายฐาน' WHERE name = 'Ustiur, Base Camp';
UPDATE maps SET name_th = 'อัสเทียร์, โซนสอง' WHERE name = 'Ustiur, Zona Dos';
UPDATE maps SET name_th = 'อัสเทียร์, โซนสาม' WHERE name = 'Ustiur, Zona Tres';
UPDATE maps SET name_th = 'เวกัส ฮาเวียร์' WHERE name = 'Vegas Javier';
UPDATE maps SET name_th = 'คฤหาสน์เวอร์เนียร์, ชั้น 1' WHERE name = 'Vernier Mansion, 1st Floor';
UPDATE maps SET name_th = 'เวีย ฟลูเวียล' WHERE name = 'Via Fluvial';
UPDATE maps SET name_th = 'วิรอน, ป่าหมอกเลือด' WHERE name = 'Viron, Blood Fog Forest';
UPDATE maps SET name_th = 'วิรอน, ป่าอาทิตย์อัสดงแดง' WHERE name = 'Viron, Red Sunset Forest';
UPDATE maps SET name_th = 'วังวนแห่งเปลวเพลิง' WHERE name = 'Whirlpool of Flame';
