-- Migration 016: Thai monster names (508 monsters)
-- Transliterates proper names phonetically, translates common descriptors

UPDATE monsters SET name_th = 'อะบิสซอล คลอว์' WHERE name = 'Abbyssal claw';
UPDATE monsters SET name_th = 'อะบิสซอล คลอว์ อีลีท' WHERE name = 'Abbyssal claw Elite';
UPDATE monsters SET name_th = 'อะบิส อาเวอร์ส' WHERE name = 'Abyss Avers';
UPDATE monsters SET name_th = 'อะบิส เดสกลอส' WHERE name = 'Abyss Desglose';
UPDATE monsters SET name_th = 'อะบิส ฮาท' WHERE name = 'Abyss Haat';
UPDATE monsters SET name_th = 'อะบิส บ้าคลั่ง' WHERE name = 'Abyss, Crazy';
UPDATE monsters SET name_th = 'อะบิสซอร์โรว์' WHERE name = 'AbyssSorrow';
UPDATE monsters SET name_th = 'อะคอร์ชาโด' WHERE name = 'Acorchado';
UPDATE monsters SET name_th = 'อะม็อค ทอร์ทอยส์' WHERE name = 'Amok Tortoise';
UPDATE monsters SET name_th = 'โบราณ จัมปิ้งฟิช' WHERE name = 'Ancient Jumpingfish';
UPDATE monsters SET name_th = 'โบราณ ทอรัส' WHERE name = 'Ancient Taurus';
UPDATE monsters SET name_th = 'นักรบโบราณ' WHERE name = 'AncientFighter';
UPDATE monsters SET name_th = 'อัศวินโบราณ' WHERE name = 'AncientKnight';
UPDATE monsters SET name_th = 'โคโมโด โกรธ' WHERE name = 'Angry Comodo';
UPDATE monsters SET name_th = 'แอนท์อีทเตอร์' WHERE name = 'Anteater';
UPDATE monsters SET name_th = 'อะพาโต ซอรัส' WHERE name = 'Apato Saurus';
UPDATE monsters SET name_th = 'อาร์เบรมอน' WHERE name = 'Arbremon';
UPDATE monsters SET name_th = 'อาร์โมเนีย แบร์' WHERE name = 'Armonia Bear';
UPDATE monsters SET name_th = 'อะร็อป อีลีท' WHERE name = 'Arop Elite';
UPDATE monsters SET name_th = 'ออค มัสเคทเทียร์' WHERE name = 'Auch Musketeer';
UPDATE monsters SET name_th = 'บัคคานาเลีย' WHERE name = 'Bacchanalia';
UPDATE monsters SET name_th = 'บัคคานาเลีย อีลีท' WHERE name = 'Bacchanalia Elite';
UPDATE monsters SET name_th = 'แบนเดอเลียร์ เดอะ เซเบอร์ อีลีท' WHERE name = 'Bandelier THE SABRE Elite';
UPDATE monsters SET name_th = 'แบนเดอเลียร์ เดอะ บูลลี่' WHERE name = 'Bandelier THE bully';
UPDATE monsters SET name_th = 'แบนเดอเลียร์ เดอะ เอ็ดเวิร์ด' WHERE name = 'Bandelier THE edward';
UPDATE monsters SET name_th = 'แบร์ริเออร์ เมห์คอส' WHERE name = 'Barrier Mehcos';
UPDATE monsters SET name_th = 'บีชบอล แจ็คโอแลนเทิร์น' WHERE name = 'Beachball_Jackolantern';
UPDATE monsters SET name_th = 'แบร์เวิร์คเกอร์' WHERE name = 'Bearworker';
UPDATE monsters SET name_th = 'แบร์เวิร์คเกอร์ อีลีท' WHERE name = 'Bearworker Elite';
UPDATE monsters SET name_th = 'เบเดล บัฟฟาโล' WHERE name = 'Bedel Buffalo';
UPDATE monsters SET name_th = 'เบเดล ลีฟฟิ่ง ค็อค' WHERE name = 'Bedel Leafing croc';
UPDATE monsters SET name_th = 'กระต่ายยักษ์' WHERE name = 'Big Rabbit';
UPDATE monsters SET name_th = 'บิ๊กฟุต' WHERE name = 'Bigfoot';
UPDATE monsters SET name_th = 'นักดาบ อินทรีดำ' WHERE name = 'Black Eagle Fencer';
UPDATE monsters SET name_th = 'ทหารหอก อินทรีดำ' WHERE name = 'Black Eagle Lancer';
UPDATE monsters SET name_th = 'นักยิง อินทรีดำ' WHERE name = 'Black Eagle Shooter';
UPDATE monsters SET name_th = 'ผู้พิทักษ์เหล็กดำ' WHERE name = 'Black Iron Keeper';
UPDATE monsters SET name_th = 'แบล็คฟิช อีลีท' WHERE name = 'Blackfish Elite';
UPDATE monsters SET name_th = 'เบลดแอนทีโลปส์ อีลีท' WHERE name = 'Bladeantelopes Elite';
UPDATE monsters SET name_th = 'บลิซซาร์ดเรเวแนนท์ อีลีท' WHERE name = 'Blizzardrevenant Elite';
UPDATE monsters SET name_th = 'บลัดดี้ ฮาวด์อีทเตอร์' WHERE name = 'Bloody Hound-eater';
UPDATE monsters SET name_th = 'อสูรธาตุสีน้ำเงิน' WHERE name = 'Blue Elemental';
UPDATE monsters SET name_th = 'บลูฟิช' WHERE name = 'Bluefish';
UPDATE monsters SET name_th = 'โบนเลส' WHERE name = 'Boneless';
UPDATE monsters SET name_th = 'กล่อง' WHERE name = 'Box';
UPDATE monsters SET name_th = 'บริบานตรา' WHERE name = 'Bribantra';
UPDATE monsters SET name_th = 'บัฟฟาโลน้ำตาล อีลีท' WHERE name = 'Brown Buffalo Elite';
UPDATE monsters SET name_th = 'วอลเตอร์ เพลิง' WHERE name = 'Burning Walter';
UPDATE monsters SET name_th = 'แคสเตอร์ แห่งเคออส' WHERE name = 'CASTOR of Chaos';
UPDATE monsters SET name_th = 'คิเมร่า หมายเลข 666' WHERE name = 'CHIMERA No.666';
UPDATE monsters SET name_th = 'แคนเดิลไกสเตอร์' WHERE name = 'Candlegeister';
UPDATE monsters SET name_th = 'เต่าปืนใหญ่' WHERE name = 'Cannon tortoise';
UPDATE monsters SET name_th = 'คาเพลลา อีลีท' WHERE name = 'Capella Elite';
UPDATE monsters SET name_th = 'คาปิบาร่ากราวด์' WHERE name = 'Capybaraground';
UPDATE monsters SET name_th = 'คาร์เพนเตอร์วอสป์ อีลีท' WHERE name = 'Carpenterwasp Elite';
UPDATE monsters SET name_th = 'เคส-ออคโตปุส' WHERE name = 'Case-octopus';
UPDATE monsters SET name_th = 'เคส-ออคโตปุส อีลีท' WHERE name = 'Case-octopus Elite';
UPDATE monsters SET name_th = 'แคสค์' WHERE name = 'Cask';
UPDATE monsters SET name_th = 'แคสค์-ออคโตปุส' WHERE name = 'Cask-octopus';
UPDATE monsters SET name_th = 'กูลสมบัติ ถ้ำ' WHERE name = 'Cavern Ghouloftreasure';
UPDATE monsters SET name_th = 'กูลสมบัติ ถ้ำ อีลีท' WHERE name = 'Cavern Ghouloftreasure Elite';
UPDATE monsters SET name_th = 'จัมปิ้งฟิช ถ้ำ' WHERE name = 'Cavern Jumpingfish';
UPDATE monsters SET name_th = 'หีบสมบัติเลียนแบบ ถ้ำ' WHERE name = 'Cavern Treasuremimic';
UPDATE monsters SET name_th = 'เซห์คอส' WHERE name = 'Cehcos';
UPDATE monsters SET name_th = 'เซเลกริมเวิร์ม' WHERE name = 'Celegrimworm';
UPDATE monsters SET name_th = 'เซเลแมนทิส' WHERE name = 'Celemantis';
UPDATE monsters SET name_th = 'เซอร์เบอรัส' WHERE name = 'Cerberus';
UPDATE monsters SET name_th = 'ชาริโอเทียร์' WHERE name = 'Charioteer';
UPDATE monsters SET name_th = 'ซีเกา' WHERE name = 'Ckao';
UPDATE monsters SET name_th = 'ค็อคคาทริซ' WHERE name = 'Cockatrice';
UPDATE monsters SET name_th = 'ค็อคคาทรีส์' WHERE name = 'Cockatries';
UPDATE monsters SET name_th = 'ค็อคคาทรีส์ อีลีท' WHERE name = 'Cockatries Elite';
UPDATE monsters SET name_th = 'ปู อีลีท' WHERE name = 'Crab Elite';
UPDATE monsters SET name_th = 'เครเกน อีลีท' WHERE name = 'Cragen Elite';
UPDATE monsters SET name_th = 'หมาป่าแดง อีลีท' WHERE name = 'Crimsonwolf Elite';
UPDATE monsters SET name_th = 'คราวน์ ลอยด์' WHERE name = 'Crown Lloyd';
UPDATE monsters SET name_th = 'ครูเอลูซ' WHERE name = 'Crueluz';
UPDATE monsters SET name_th = 'จระเข้ร้องไห้' WHERE name = 'Crying croc';
UPDATE monsters SET name_th = 'อันเดร จันซูร์ ต้องสาป' WHERE name = 'Cursed Andre Janzur';
UPDATE monsters SET name_th = 'แบค โฮ ต้องสาป' WHERE name = 'Cursed Back Ho';
UPDATE monsters SET name_th = 'คาลีเซ ต้องสาป' WHERE name = 'Cursed Calyce';
UPDATE monsters SET name_th = 'เอ็ดดูอาร์โด ต้องสาป' WHERE name = 'Cursed Eduardo';
UPDATE monsters SET name_th = 'เกรซ เบอร์เนลี ต้องสาป' WHERE name = 'Cursed Grace Berneli';
UPDATE monsters SET name_th = 'คุณย่า ต้องสาป' WHERE name = 'Cursed Grandma';
UPDATE monsters SET name_th = 'เฮลเลน่า ต้องสาป' WHERE name = 'Cursed Hellena';
UPDATE monsters SET name_th = 'แจ็ค ต้องสาป' WHERE name = 'Cursed Jack';
UPDATE monsters SET name_th = 'เคิร์ท ต้องสาป' WHERE name = 'Cursed Kurt';
UPDATE monsters SET name_th = 'ลอร์ช ต้องสาป' WHERE name = 'Cursed Lorch';
UPDATE monsters SET name_th = 'นาร์ ต้องสาป' WHERE name = 'Cursed Nar';
UPDATE monsters SET name_th = 'เรเวน ต้องสาป' WHERE name = 'Cursed Raven';
UPDATE monsters SET name_th = 'ริโอ ต้องสาป' WHERE name = 'Cursed Rio';
UPDATE monsters SET name_th = 'โซโซ ต้องสาป' WHERE name = 'Cursed SoSo';
UPDATE monsters SET name_th = 'เยกาเนห์ ต้องสาป' WHERE name = 'Cursed Yeganeh';
UPDATE monsters SET name_th = 'ทหารอมตะ ต้องสาป' WHERE name = 'Cursed undead soldier';
UPDATE monsters SET name_th = 'เดียโบล' WHERE name = 'DIABLO';
UPDATE monsters SET name_th = 'ดร. แฟรน มอธเทียน' WHERE name = 'DR. FRAN MOTHTEIN';
UPDATE monsters SET name_th = 'ลิงบึง แดนดิไลอ้อน อีลีท' WHERE name = 'Dandelion Swamp monkey Elite';
UPDATE monsters SET name_th = 'บัฟฟาโลมืด อีลีท' WHERE name = 'Dark Buffalo Elite';
UPDATE monsters SET name_th = 'ยอร์มอนกานด์ มืด' WHERE name = 'Darked Jormongand';
UPDATE monsters SET name_th = 'เดคาราเบีย' WHERE name = 'Decarabia';
UPDATE monsters SET name_th = 'เซเลแมนทิส ผุพัง' WHERE name = 'Decay Celemantis';
UPDATE monsters SET name_th = 'ปีศาจ อีลีท' WHERE name = 'Demon Elite';
UPDATE monsters SET name_th = 'อะคอร์ชาโด ปีศาจ' WHERE name = 'Demoniac Acorchado';
UPDATE monsters SET name_th = 'แบล็คฟิช ปีศาจ' WHERE name = 'Demoniac Blackfish';
UPDATE monsters SET name_th = 'สมอสยอง ปีศาจ' WHERE name = 'Demoniac Dread anchor';
UPDATE monsters SET name_th = 'ดูลลาฮานผู้พิทักษ์ ปีศาจ' WHERE name = 'Demoniac Dullahanguardian';
UPDATE monsters SET name_th = 'ดูลลาฮานทหารหอก ปีศาจ' WHERE name = 'Demoniac Dullahanlanceman';
UPDATE monsters SET name_th = 'เอลดูม ปีศาจ' WHERE name = 'Demoniac Eldoom';
UPDATE monsters SET name_th = 'เอสคูโดแฟรปเปอร์ ปีศาจ' WHERE name = 'Demoniac Escudofrapper';
UPDATE monsters SET name_th = 'กาวี ดิ กาวี ปีศาจ' WHERE name = 'Demoniac Gavi di Gavi';
UPDATE monsters SET name_th = 'กูลนักธนู ปีศาจ' WHERE name = 'Demoniac Ghoul Archer';
UPDATE monsters SET name_th = 'กูลลาดตระเวน ปีศาจ' WHERE name = 'Demoniac Ghoul Scout';
UPDATE monsters SET name_th = 'เซเลกริมเวิร์มยักษ์ ปีศาจ' WHERE name = 'Demoniac Giant Celegrimworm';
UPDATE monsters SET name_th = 'ฮอลโลว์ด ฟุตแมน ปีศาจ' WHERE name = 'Demoniac Hollowed Footman';
UPDATE monsters SET name_th = 'ไอรอนเมเดน ปีศาจ' WHERE name = 'Demoniac Ironmaiden';
UPDATE monsters SET name_th = 'โคบอลด์ชีฟ เอลเดอร์ ปีศาจ' WHERE name = 'Demoniac Koboldchief Elder';
UPDATE monsters SET name_th = 'ล็อค ปีศาจ' WHERE name = 'Demoniac Locke';
UPDATE monsters SET name_th = 'เมอร์แมน ปีศาจ' WHERE name = 'Demoniac Merman';
UPDATE monsters SET name_th = 'เนวาเร ปีศาจ' WHERE name = 'Demoniac Nevare';
UPDATE monsters SET name_th = 'อสูรธาตุแดง ปีศาจ' WHERE name = 'Demoniac Red  Elemental';
UPDATE monsters SET name_th = 'มูเซสคาร์ก็อต รูจ สนิม ปีศาจ' WHERE name = 'Demoniac Rusty Musescargot Rouge';
UPDATE monsters SET name_th = 'สการ์เล็ต คลอว์ ปีศาจ' WHERE name = 'Demoniac Scarlet claw';
UPDATE monsters SET name_th = 'โครงกระดูกเพชฌฆาต ปีศาจ' WHERE name = 'Demoniac Skeleton Excutioner';
UPDATE monsters SET name_th = 'โครงกระดูกอัศวิน ปีศาจ' WHERE name = 'Demoniac Skeleton Knight';
UPDATE monsters SET name_th = 'โครงกระดูกทหารหอก ปีศาจ' WHERE name = 'Demoniac Skeleton lancer';
UPDATE monsters SET name_th = 'ทอรัส ปีศาจ' WHERE name = 'Demoniac Taurus';
UPDATE monsters SET name_th = 'ทีคาปี้ครูเอล ปีศาจ' WHERE name = 'Demoniac Tcapycruel';
UPDATE monsters SET name_th = 'ทีคาปี้วอร์ริเออร์ ปีศาจ' WHERE name = 'Demoniac Tcapywarrior';
UPDATE monsters SET name_th = 'สองหัว ปีศาจ' WHERE name = 'Demoniac Twin-headed';
UPDATE monsters SET name_th = 'แวมไพร์แบทลอร์ด ปีศาจ' WHERE name = 'Demoniac Vampire Bat lord';
UPDATE monsters SET name_th = 'แบร์เวิร์คเกอร์รุนแรง ปีศาจ' WHERE name = 'Demoniac Violence Bearworker';
UPDATE monsters SET name_th = 'เรธ ปีศาจ' WHERE name = 'Demoniac Wraith';
UPDATE monsters SET name_th = 'เดโมนิชเช' WHERE name = 'Demonische';
UPDATE monsters SET name_th = 'ดิงโก อีลีท' WHERE name = 'Dingo Elite';
UPDATE monsters SET name_th = 'ดิโนดอน' WHERE name = 'Dinodon';
UPDATE monsters SET name_th = 'ทีคาปี้ โรค' WHERE name = 'Disease Tcapy';
UPDATE monsters SET name_th = 'ทีคาปี้ โรค อีลีท' WHERE name = 'Disease Tcapy Elite';
UPDATE monsters SET name_th = 'ทีคาปี้เรนเจอร์ โรค' WHERE name = 'Disease Tcapyranger';
UPDATE monsters SET name_th = 'ทีคาปี้วอร์ริเออร์ โรค' WHERE name = 'Disease Tcapywarrior';
UPDATE monsters SET name_th = 'ด็อกกี้ บอมเบอร์' WHERE name = 'Doggy bomber';
UPDATE monsters SET name_th = 'สมอสยอง อีลีท' WHERE name = 'Dread anchor Elite';
UPDATE monsters SET name_th = 'ดูลลาฮานแอทแทคเกอร์' WHERE name = 'Dullahanattacker';
UPDATE monsters SET name_th = 'ดูลลาฮานกันเนอร์' WHERE name = 'Dullahangunner';
UPDATE monsters SET name_th = 'ดูมานอน อีลีท' WHERE name = 'Dumanon Elite';
UPDATE monsters SET name_th = 'ดูเปสทีน' WHERE name = 'Dupesteen';
UPDATE monsters SET name_th = 'ไข่' WHERE name = 'Egg';
UPDATE monsters SET name_th = 'ไอเกิลชวาร์ลิเออร์' WHERE name = 'Eigleschvarlier';
UPDATE monsters SET name_th = 'ไอเกิลชวาร์ลิเออร์ อีลีท' WHERE name = 'Eigleschvarlier Elite';
UPDATE monsters SET name_th = 'ไอน์เว็ทเทอร์' WHERE name = 'Einwetter';
UPDATE monsters SET name_th = 'ไอน์เว็ทเทอร์ อีลีท' WHERE name = 'Einwetter Elite';
UPDATE monsters SET name_th = 'ไอน์วินด์1 อีลีท' WHERE name = 'Einwind1 Elite';
UPDATE monsters SET name_th = 'เอลบิโอเต' WHERE name = 'Elbiote';
UPDATE monsters SET name_th = 'เอลบลีด' WHERE name = 'Elbleed';
UPDATE monsters SET name_th = 'เอลบูม' WHERE name = 'Elboom';
UPDATE monsters SET name_th = 'เอลซิโนส' WHERE name = 'Elcinos';
UPDATE monsters SET name_th = 'เอลดูม' WHERE name = 'Eldoom';
UPDATE monsters SET name_th = 'เอลดูม อีลีท' WHERE name = 'Eldoom Elite';
UPDATE monsters SET name_th = 'วอลเตอร์ ไฟฟ้า' WHERE name = 'Electric Walter';
UPDATE monsters SET name_th = 'เอลกูม' WHERE name = 'Elgoom';
UPDATE monsters SET name_th = 'เอลกูม อีลีท' WHERE name = 'Elgoom Elite';
UPDATE monsters SET name_th = 'เอลลีโก อีลีท' WHERE name = 'Eliigo Elite';
UPDATE monsters SET name_th = 'อีลีท โบว์การัส' WHERE name = 'Elite Bowgaras';
UPDATE monsters SET name_th = 'อีลีท ยัส-มาชิน่า ไฟ' WHERE name = 'Elite Fire Yus-machina';
UPDATE monsters SET name_th = 'อีลีท กลัตโทนี่' WHERE name = 'Elite Gluttony';
UPDATE monsters SET name_th = 'อีลีท ยัส-มาชิน่า น้ำแข็ง' WHERE name = 'Elite Ice Yus-machina';
UPDATE monsters SET name_th = 'อีลีท รีเปอร์การัส' WHERE name = 'Elite ReaperGaras';
UPDATE monsters SET name_th = 'อีลีท วอร์ดอย' WHERE name = 'Elite Vordoi';
UPDATE monsters SET name_th = 'เอลมินอร์' WHERE name = 'Elminor';
UPDATE monsters SET name_th = 'เอลมอร์ค' WHERE name = 'Elmorc';
UPDATE monsters SET name_th = 'เอลนูการ์ด' WHERE name = 'Elnoogard';
UPDATE monsters SET name_th = 'เอลิเซียน' WHERE name = 'Elysian';
UPDATE monsters SET name_th = 'เอริปมาฟ อีลีท' WHERE name = 'Eripmav Elite';
UPDATE monsters SET name_th = 'เอสคูโดแฟรปเปอร์' WHERE name = 'Escudofrapper';
UPDATE monsters SET name_th = 'เอสคูโดแฟรปเปอร์ อีลีท' WHERE name = 'Escudofrapper Elite';
UPDATE monsters SET name_th = 'หินร่วง' WHERE name = 'Fallen Rock';
UPDATE monsters SET name_th = 'ทหารล่ม' WHERE name = 'Fallen Soldier';
UPDATE monsters SET name_th = 'ฟานาติค' WHERE name = 'Fanatic';
UPDATE monsters SET name_th = 'ฟานาติค อีลีท' WHERE name = 'Fanatic Elite';
UPDATE monsters SET name_th = 'ไฟ วลาดิเมียร์' WHERE name = 'Fire  VLADIMIR';
UPDATE monsters SET name_th = 'ไฟ เซอร์เบร่า' WHERE name = 'Fire CERBERA';
UPDATE monsters SET name_th = 'ไฟ การ์กอยล์' WHERE name = 'Fire Gargoyle';
UPDATE monsters SET name_th = 'ไฟ จูโม พลาค รูจ' WHERE name = 'Fire Jumeau plaque Rouge';
UPDATE monsters SET name_th = 'ไฟ ลาซิม-แลม' WHERE name = 'Fire Lazim-lam';
UPDATE monsters SET name_th = 'ไฟ การ์กอยล์น้อย' WHERE name = 'Fire Lesser Gargoyle';
UPDATE monsters SET name_th = 'ไฟ มาห์กอร์ป' WHERE name = 'Fire Mahrgorp';
UPDATE monsters SET name_th = 'ไฟ มาร์เคิร์ส' WHERE name = 'Fire Marcurse';
UPDATE monsters SET name_th = 'ไฟ เนวาเร' WHERE name = 'Fire Nevare';
UPDATE monsters SET name_th = 'ไฟ โฟบิแทน' WHERE name = 'Fire Phobitan';
UPDATE monsters SET name_th = 'ไฟ รูฟุส โฟซ์' WHERE name = 'Fire Rufus faux';
UPDATE monsters SET name_th = 'โครงกระดูก ไฟ' WHERE name = 'Fire Skeleton';
UPDATE monsters SET name_th = 'นายพลโครงกระดูก ไฟ' WHERE name = 'Fire Skeleton General';
UPDATE monsters SET name_th = 'ไฟ ซีบร้า-อีทเตอร์' WHERE name = 'Fire Zebra-eater';
UPDATE monsters SET name_th = 'ฟลิกกี้' WHERE name = 'Flicky';
UPDATE monsters SET name_th = 'ฟลูแฮม' WHERE name = 'Fluham';
UPDATE monsters SET name_th = 'เคียวบิน' WHERE name = 'Flying sickle';
UPDATE monsters SET name_th = 'กบบิน' WHERE name = 'Flyingfrog';
UPDATE monsters SET name_th = 'ฟอร์ดอย' WHERE name = 'Fordoi';
UPDATE monsters SET name_th = 'สาวสมบัติที่ถูกลืม' WHERE name = 'Forgotten Treasure Maiden';
UPDATE monsters SET name_th = 'วอลเตอร์ แช่แข็ง' WHERE name = 'Freezing Walter';
UPDATE monsters SET name_th = 'เฟรนซี่' WHERE name = 'Frenzy';
UPDATE monsters SET name_th = 'กาบิรุส' WHERE name = 'Gabirus';
UPDATE monsters SET name_th = 'กาบิรุส อีลีท' WHERE name = 'Gabirus Elite';
UPDATE monsters SET name_th = 'กาวี ดิ กาวี อีลีท' WHERE name = 'Gavi di Gavi Elite';
UPDATE monsters SET name_th = 'กาวี ดิ น้ำแข็ง' WHERE name = 'Gavi di Ice';
UPDATE monsters SET name_th = 'กาวี ดิ แสง' WHERE name = 'Gavi di Light';
UPDATE monsters SET name_th = 'เกห์คอส' WHERE name = 'Gehcos';
UPDATE monsters SET name_th = 'เกห์คอส อีลีท' WHERE name = 'Gehcos Elite';
UPDATE monsters SET name_th = 'นายพล เทอุส-มาชิน่า' WHERE name = 'General Teus-machina';
UPDATE monsters SET name_th = 'วิญญาณ' WHERE name = 'Ghost';
UPDATE monsters SET name_th = 'โกสท์บารอน' WHERE name = 'Ghostbaron';
UPDATE monsters SET name_th = 'โกสท์บารอน อีลีท' WHERE name = 'Ghostbaron Elite';
UPDATE monsters SET name_th = 'โกสท์ลี่ แฟลมเมอร์ อีลีท' WHERE name = 'Ghostly flammer Elite';
UPDATE monsters SET name_th = 'โกสท์ลี่ ฟรีเกอร์' WHERE name = 'Ghostly friger';
UPDATE monsters SET name_th = 'กูลผู้พิทักษ์' WHERE name = 'Ghoul Defender';
UPDATE monsters SET name_th = 'เซเลกริมเวิร์ม ยักษ์' WHERE name = 'Giant Celegrimworm';
UPDATE monsters SET name_th = 'เซเลกริมเวิร์ม ยักษ์ อีลีท' WHERE name = 'Giant Celegrimworm Elite';
UPDATE monsters SET name_th = 'หนู ยักษ์' WHERE name = 'Giant Rat';
UPDATE monsters SET name_th = 'ดาวทะเล ยักษ์' WHERE name = 'Giant SeaStar';
UPDATE monsters SET name_th = 'โครงกระดูกอัศวินหมวก ยักษ์' WHERE name = 'Giant Skeleton Knightcap';
UPDATE monsters SET name_th = 'กิกาโนโตซอรัส' WHERE name = 'GiganotoSaurus';
UPDATE monsters SET name_th = 'กิมเลท' WHERE name = 'Gimlet';
UPDATE monsters SET name_th = 'กิมเลท อีลีท' WHERE name = 'Gimlet Elite';
UPDATE monsters SET name_th = 'วัลคีรีน้ำแข็ง' WHERE name = 'GlacialValkyrie';
UPDATE monsters SET name_th = 'กลัตโทนี่' WHERE name = 'Gluttony';
UPDATE monsters SET name_th = 'วิญญาณไร้พระเจ้า' WHERE name = 'Godless Ghost';
UPDATE monsters SET name_th = 'กูลผู้พิทักษ์ไร้พระเจ้า' WHERE name = 'Godless Ghoul Defender';
UPDATE monsters SET name_th = 'โคโมโด ทุ่งหญ้า' WHERE name = 'Grassland Comodo';
UPDATE monsters SET name_th = 'บัฟฟาโลเทา' WHERE name = 'Gray Buffalo';
UPDATE monsters SET name_th = 'หมาป่าเทา' WHERE name = 'Graywolf';
UPDATE monsters SET name_th = 'แตนยักษ์' WHERE name = 'Great hornet';
UPDATE monsters SET name_th = 'แตนยักษ์ อีลีท' WHERE name = 'Great hornet Elite';
UPDATE monsters SET name_th = 'แมนดราใหญ่' WHERE name = 'Great mandra';
UPDATE monsters SET name_th = 'เคียวเขียว' WHERE name = 'Green Sickle';
UPDATE monsters SET name_th = 'กรีนฟิช' WHERE name = 'Greenfish';
UPDATE monsters SET name_th = 'กริม-ริปเปอร์' WHERE name = 'Grim-ripper';
UPDATE monsters SET name_th = 'กูลแฟ็กซี' WHERE name = 'Gullfaxi';
UPDATE monsters SET name_th = 'กวร์เอก' WHERE name = 'Gwraig';
UPDATE monsters SET name_th = 'แฮร์โรเวอร์' WHERE name = 'Harrower';
UPDATE monsters SET name_th = 'หนังสือผีสิง' WHERE name = 'Haunted-book';
UPDATE monsters SET name_th = 'หนังสือผีสิง บอส' WHERE name = 'Haunted-book Boss';
UPDATE monsters SET name_th = 'เทียนผีสิง' WHERE name = 'Haunted-candle';
UPDATE monsters SET name_th = 'เทียนผีสิง อีลีท' WHERE name = 'Haunted-candle Elite';
UPDATE monsters SET name_th = 'โต๊ะผีสิง' WHERE name = 'Haunted-desk';
UPDATE monsters SET name_th = 'บัคคานาเลีย สวรรค์' WHERE name = 'Heaven Bacchanalia';
UPDATE monsters SET name_th = 'ไมโคนิด สวรรค์' WHERE name = 'Heaven Myconid';
UPDATE monsters SET name_th = 'เวสปาโนลลา สวรรค์' WHERE name = 'Heaven Vespanolla';
UPDATE monsters SET name_th = 'เฮเลน่า' WHERE name = 'Helena';
UPDATE monsters SET name_th = 'เฮเลน่า อีลีท' WHERE name = 'Helena Elite';
UPDATE monsters SET name_th = 'เฮลล์ฮาวด์' WHERE name = 'Hell Hound';
UPDATE monsters SET name_th = 'นอกรีต อีลีท' WHERE name = 'Heretic Elite';
UPDATE monsters SET name_th = 'ฮอลโลว์ด ฟุตแมน' WHERE name = 'Hollowed Footman';
UPDATE monsters SET name_th = 'ฮอลโลว์ด ฟุตแมน อีลีท' WHERE name = 'Hollowed Footman Elite';
UPDATE monsters SET name_th = 'ผึ้ง' WHERE name = 'Honeybee';
UPDATE monsters SET name_th = 'ฮาวด์ อีลีท' WHERE name = 'Hound Elite';
UPDATE monsters SET name_th = 'ฮาวด์อีทเตอร์' WHERE name = 'Hound-eater';
UPDATE monsters SET name_th = 'ฮาวด์อีทเตอร์ อีลีท' WHERE name = 'Hound-eater Elite';
UPDATE monsters SET name_th = 'น้ำแข็ง โคโมโด' WHERE name = 'Ice Comodo';
UPDATE monsters SET name_th = 'โครงกระดูก น้ำแข็ง' WHERE name = 'Ice Skeleton';
UPDATE monsters SET name_th = 'นายพลโครงกระดูก น้ำแข็ง' WHERE name = 'Ice Skeleton General';
UPDATE monsters SET name_th = 'น้ำแข็ง ซีบร้า-อีทเตอร์' WHERE name = 'Ice Zebra-eater';
UPDATE monsters SET name_th = 'ทหารเวทย์ อิลลิเออร์' WHERE name = 'Illier Magic Soldier';
UPDATE monsters SET name_th = 'อิมานอน อีลีท' WHERE name = 'Imanon Elite';
UPDATE monsters SET name_th = 'ผู้พิทักษ์จักรวรรดิ' WHERE name = 'Imperial Guardian';
UPDATE monsters SET name_th = 'ผู้พิทักษ์เหล็ก' WHERE name = 'Iron Keeper';
UPDATE monsters SET name_th = 'ไอรอนเมเดน อีลีท' WHERE name = 'Ironmaiden Elite';
UPDATE monsters SET name_th = 'อิสกรา' WHERE name = 'Iskra';
UPDATE monsters SET name_th = 'แจบเบอร์ว็อค' WHERE name = 'Jabberwock';
UPDATE monsters SET name_th = 'แจบเบอร์ว็อคแคป' WHERE name = 'JabberwockCap';
UPDATE monsters SET name_th = 'แจ็คควินแบร์' WHERE name = 'Jacquinbear';
UPDATE monsters SET name_th = 'แจ็คควินแบร์ อีลีท' WHERE name = 'Jacquinbear Elite';
UPDATE monsters SET name_th = 'แจ็คควินกริซลี่' WHERE name = 'Jacquingrizzly';
UPDATE monsters SET name_th = 'จาควิน โคโมโด' WHERE name = 'Jaquin Comodo';
UPDATE monsters SET name_th = 'จาควิน โคโมโด อีลีท' WHERE name = 'Jaquin Comodo Elite';
UPDATE monsters SET name_th = 'จาควิน สุนัขป่า' WHERE name = 'Jaquin Wild-dog';
UPDATE monsters SET name_th = 'เซอร์เบอรัสน้อย แห่งมืด' WHERE name = 'Jr. Cerberus Of Dark';
UPDATE monsters SET name_th = 'เซอร์เบอรัสน้อย แห่งช็อค' WHERE name = 'Jr. Cerberus Of Shock';
UPDATE monsters SET name_th = 'จูโม พลาค' WHERE name = 'Jumeau plaque';
UPDATE monsters SET name_th = 'จูโม พลาค นัวร์' WHERE name = 'Jumeau plaque Noir';
UPDATE monsters SET name_th = 'จัมปิ้งฟิช' WHERE name = 'Jumpingfish';
UPDATE monsters SET name_th = 'ราชา แคสเตอร์' WHERE name = 'KING CASTOR';
UPDATE monsters SET name_th = 'ราชา หัวมังกร' WHERE name = 'KING DRAGON-HEADED';
UPDATE monsters SET name_th = 'คาโตวิคแบร์' WHERE name = 'Katovicbear';
UPDATE monsters SET name_th = 'ราชาปู' WHERE name = 'King Crab';
UPDATE monsters SET name_th = 'ราชา เกห์คอส' WHERE name = 'King Gehcos';
UPDATE monsters SET name_th = 'ราชา-ออคโตปุส' WHERE name = 'King-octopus';
UPDATE monsters SET name_th = 'โคบอลด์ชีฟ เอลเดอร์' WHERE name = 'Koboldchief Elder';
UPDATE monsters SET name_th = 'เลดี้ ซาชา' WHERE name = 'Lady Sasha';
UPDATE monsters SET name_th = 'ลีฟฟิ่ง ค็อค' WHERE name = 'Leafing croc';
UPDATE monsters SET name_th = 'การ์กอยล์น้อย' WHERE name = 'Lesser Gargoyle';
UPDATE monsters SET name_th = 'การ์กอยล์น้อย อีลีท' WHERE name = 'Lesser Gargoyle Elite';
UPDATE monsters SET name_th = 'โครงกระดูกเพชฌฆาต แสง' WHERE name = 'Light Skeleton Excutioner';
UPDATE monsters SET name_th = 'นายพลโครงกระดูก แสง' WHERE name = 'Light Skeleton General';
UPDATE monsters SET name_th = 'โครงกระดูกอัศวิน แสง' WHERE name = 'Light Skeleton Knight';
UPDATE monsters SET name_th = 'แสง ซีบร้า-อีทเตอร์' WHERE name = 'Light Zebra-eater';
UPDATE monsters SET name_th = 'แมงมุมทองน้อย' WHERE name = 'Little Goden Spider';
UPDATE monsters SET name_th = 'เขาน้อย' WHERE name = 'Little Horn';
UPDATE monsters SET name_th = 'จระเข้น้อย' WHERE name = 'Little croc';
UPDATE monsters SET name_th = 'จระเข้น้อย อีลีท' WHERE name = 'Little croc Elite';
UPDATE monsters SET name_th = 'ลอยด์' WHERE name = 'Lloyd';
UPDATE monsters SET name_th = 'ล็อค' WHERE name = 'Locke';
UPDATE monsters SET name_th = 'มาห์กอร์ป' WHERE name = 'Mahrgorp';
UPDATE monsters SET name_th = 'แมนดราดอร่า' WHERE name = 'Mandradora';
UPDATE monsters SET name_th = 'แมนเดรลริร่า' WHERE name = 'Mandrelrira';
UPDATE monsters SET name_th = 'มาร์เคิร์ส' WHERE name = 'Marcurse';
UPDATE monsters SET name_th = 'มาร์เคิร์ส อีลีท' WHERE name = 'Marcurse Elite';
UPDATE monsters SET name_th = 'มาสเคอเรเดอร์' WHERE name = 'Masquerader';
UPDATE monsters SET name_th = 'เมห์คอส' WHERE name = 'Mehcos';
UPDATE monsters SET name_th = 'เมอร์แมน' WHERE name = 'Merman';
UPDATE monsters SET name_th = 'เมอร์แนม หัวหน้า' WHERE name = 'Mernam chieftain';
UPDATE monsters SET name_th = 'ไมท์ตี้ วิคเตอร์' WHERE name = 'Mighty Victor';
UPDATE monsters SET name_th = 'มิโนทอรอส' WHERE name = 'Minotauros';
UPDATE monsters SET name_th = 'โมเนการ์ม' WHERE name = 'Monegarm';
UPDATE monsters SET name_th = 'หนู' WHERE name = 'Mouse';
UPDATE monsters SET name_th = 'มูฟวิ่งร็อค' WHERE name = 'Movingrock';
UPDATE monsters SET name_th = 'นายพล มัดแมน' WHERE name = 'Mudman General';
UPDATE monsters SET name_th = 'ทหารหอก มัดแมน' WHERE name = 'Mudman lancer';
UPDATE monsters SET name_th = 'นักรบ มูเอร์ทอส' WHERE name = 'Muertos Fighter';
UPDATE monsters SET name_th = 'นักรบ มูเอร์ทอส อีลีท' WHERE name = 'Muertos Fighter Elite';
UPDATE monsters SET name_th = 'มัสเคทเทียร์ มูเอร์ทอส' WHERE name = 'Muertos Musketeer';
UPDATE monsters SET name_th = 'มัสเคทเทียร์ มูเอร์ทอส อีลีท' WHERE name = 'Muertos Musketeer Elite';
UPDATE monsters SET name_th = 'ลาดตระเวน มูเอร์ทอส อีลีท' WHERE name = 'Muertos Scout Elite';
UPDATE monsters SET name_th = 'จอมเวทย์ มูเอร์ทอส' WHERE name = 'Muertos Warlock';
UPDATE monsters SET name_th = 'จอมเวทย์ มูเอร์ทอส อีลีท' WHERE name = 'Muertos Warlock Elite';
UPDATE monsters SET name_th = 'พ่อมด มูเอร์ทอส' WHERE name = 'Muertos Wizard';
UPDATE monsters SET name_th = 'พ่อมด มูเอร์ทอส อีลีท' WHERE name = 'Muertos Wizard Elite';
UPDATE monsters SET name_th = 'เมอร์เดอร์ วอร์ดอย' WHERE name = 'Murdur Vordoi';
UPDATE monsters SET name_th = 'มูเซสคาร์ก็อต' WHERE name = 'Musescargot';
UPDATE monsters SET name_th = 'มูเซสคาร์ก็อต อีลีท' WHERE name = 'Musescargot Elite';
UPDATE monsters SET name_th = 'มูเซสคาร์ก็อต รูจ' WHERE name = 'Musescargot Rouge';
UPDATE monsters SET name_th = 'ไมโคนิด' WHERE name = 'Myconid';
UPDATE monsters SET name_th = 'ไมโคนิด อีลีท' WHERE name = 'Myconid Elite';
UPDATE monsters SET name_th = 'เนสท์-แฮร์ ฮิวกานอยด์' WHERE name = 'NEST-HAIR HUGANOID';
UPDATE monsters SET name_th = 'กัปตัน โนเซียร์' WHERE name = 'NOSIAR CAPTAIN';
UPDATE monsters SET name_th = 'ทหารธนูเนโคร' WHERE name = 'Necrobow Soldier';
UPDATE monsters SET name_th = 'เนวาเร' WHERE name = 'Nevare';
UPDATE monsters SET name_th = 'โนเซียร์ อีลีท' WHERE name = 'Nosiar Elite';
UPDATE monsters SET name_th = 'โอแอนเนส' WHERE name = 'Oannes';
UPDATE monsters SET name_th = 'ปลาหมึกยักษ์' WHERE name = 'Octopus';
UPDATE monsters SET name_th = 'โอเก' WHERE name = 'Oghe';
UPDATE monsters SET name_th = 'ออร์ก นักฆ่า' WHERE name = 'Orge Assassin';
UPDATE monsters SET name_th = 'ออร์ก โจร' WHERE name = 'Orge Bandit';
UPDATE monsters SET name_th = 'ออร์ก จอมเวทย์' WHERE name = 'Orge Mage';
UPDATE monsters SET name_th = 'ออร์ก นักล่า' WHERE name = 'Orge Predators';
UPDATE monsters SET name_th = 'ออร์ก มนุษย์หมาป่าผู้พิทักษ์' WHERE name = 'Orge Werewolf Defender';
UPDATE monsters SET name_th = 'กัปตัน พาเซียร์' WHERE name = 'PASIAR CAPTAIN';
UPDATE monsters SET name_th = 'นายพล โฟบิแทน' WHERE name = 'PHOBITAN general';
UPDATE monsters SET name_th = 'พอลลักซ์ แห่งเคออส' WHERE name = 'POLLUX of Chaos';
UPDATE monsters SET name_th = 'ปูต้นปาล์ม อีลีท' WHERE name = 'Palm Tree Crab Elite';
UPDATE monsters SET name_th = 'ราชาปูต้นปาล์ม' WHERE name = 'Palm Tree King Crab';
UPDATE monsters SET name_th = 'พาเซียร์ อีลีท' WHERE name = 'Pasiar  Elite';
UPDATE monsters SET name_th = 'โฟบิแทน' WHERE name = 'Phobitan';
UPDATE monsters SET name_th = 'โฟบิแทน อีลีท' WHERE name = 'Phobitan Elite';
UPDATE monsters SET name_th = 'สมอที่ราบ อีลีท' WHERE name = 'Plateau anchor Elite';
UPDATE monsters SET name_th = 'พิก' WHERE name = 'Pyg';
UPDATE monsters SET name_th = 'ต้นไม้เควส' WHERE name = 'Quest_Tree01';
UPDATE monsters SET name_th = 'ราบิอาเบ' WHERE name = 'Rabiabe';
UPDATE monsters SET name_th = 'ราบิโอโซ' WHERE name = 'Rabioso';
UPDATE monsters SET name_th = 'ทหาร เรโบลดูซ์' WHERE name = 'Reboldoeux Soldier';
UPDATE monsters SET name_th = 'อสูรธาตุแดง' WHERE name = 'Red  Elemental';
UPDATE monsters SET name_th = 'ปูแมงมุมแดง' WHERE name = 'Red SpiderCrab';
UPDATE monsters SET name_th = 'รีพับลิกัน' WHERE name = 'Republican';
UPDATE monsters SET name_th = 'ขบถ โคดอร์' WHERE name = 'Resistance, Codor';
UPDATE monsters SET name_th = 'ขบถ โดกี' WHERE name = 'Resistance, Dogi';
UPDATE monsters SET name_th = 'ขบถ มัลเลน' WHERE name = 'Resistance, Mullen';
UPDATE monsters SET name_th = 'ขบถ เคว์แมน' WHERE name = 'Resistance, Queman';
UPDATE monsters SET name_th = 'กัปตันกองทัพเรือเลือด ไรเฟิล' WHERE name = 'Rifle blood Navy Captain';
UPDATE monsters SET name_th = 'หมีพระจันทร์ครึ่งเสี้ยว ริออน' WHERE name = 'Rion Half-moon Bear';
UPDATE monsters SET name_th = 'โร้ก : สายบอมบ์ อีลีท' WHERE name = 'Rogue : Bomb agent Elite';
UPDATE monsters SET name_th = 'โร้ก : สายค้อน อีลีท' WHERE name = 'Rogue : Hammer agent Elite';
UPDATE monsters SET name_th = 'โร้ก : สายฟัน อีลีท' WHERE name = 'Rogue : Slash agent Elite';
UPDATE monsters SET name_th = 'โร้ก : มอร์แกน อีลีท' WHERE name = 'Rogue : morgan Elite';
UPDATE monsters SET name_th = 'โร้ก : รีด' WHERE name = 'Rogue : read';
UPDATE monsters SET name_th = 'รูฟุส โฟซ์' WHERE name = 'Rufus faux';
UPDATE monsters SET name_th = 'ไอเกิลชวาร์ลิเออร์ สนิม' WHERE name = 'Rusty Eigleschvarlier';
UPDATE monsters SET name_th = 'มูเซสคาร์ก็อต สนิม' WHERE name = 'Rusty Musescargot';
UPDATE monsters SET name_th = 'มูเซสคาร์ก็อต รูจ สนิม' WHERE name = 'Rusty Musescargot Rouge';
UPDATE monsters SET name_th = 'ชาร์ฟเฟนเบอร์เกอร์ ผู้ต้องสาป' WHERE name = 'SHARFFENBERGER THE CURSE';
UPDATE monsters SET name_th = 'ซิลค์แฮท ฮิวกานอยด์' WHERE name = 'SILKHAT HUGANOID';
UPDATE monsters SET name_th = 'เซเบอร์บอร์' WHERE name = 'Saberboar';
UPDATE monsters SET name_th = 'เซเบอร์ไทเกอร์' WHERE name = 'Sabertiger';
UPDATE monsters SET name_th = 'ซาซ่า' WHERE name = 'Sasa';
UPDATE monsters SET name_th = 'ซาซ่า นักฆ่า' WHERE name = 'Sasa Assassin';
UPDATE monsters SET name_th = 'ซาชา' WHERE name = 'Sasha';
UPDATE monsters SET name_th = 'สการ์เล็ต คลอว์' WHERE name = 'Scarlet claw';
UPDATE monsters SET name_th = 'ดาวทะเล อีลีท' WHERE name = 'SeaStar Elite';
UPDATE monsters SET name_th = 'เซห์คอส' WHERE name = 'Sehcos';
UPDATE monsters SET name_th = 'เซปุลเวดา เดอะ บอนนี่ อีลีท' WHERE name = 'Sepulveda THE bonny Elite';
UPDATE monsters SET name_th = 'ทหารกองทัพเรือเลือด โล่' WHERE name = 'Shield blood Navy Soldier';
UPDATE monsters SET name_th = 'ซีกมุนด์' WHERE name = 'Siegmund';
UPDATE monsters SET name_th = 'ซิลเวอร์แฮท โฟบิแทน' WHERE name = 'Silverhat Phobitan';
UPDATE monsters SET name_th = 'โครงกระดูก' WHERE name = 'Skeleton';
UPDATE monsters SET name_th = 'โครงกระดูกแอทแทคเกอร์ อีลีท' WHERE name = 'Skeleton Attacker Elite';
UPDATE monsters SET name_th = 'โครงกระดูก อีลีท' WHERE name = 'Skeleton Elite';
UPDATE monsters SET name_th = 'โครงกระดูกเพชฌฆาต' WHERE name = 'Skeleton Excutioner';
UPDATE monsters SET name_th = 'โครงกระดูกเพชฌฆาต อีลีท' WHERE name = 'Skeleton Excutioner Elite';
UPDATE monsters SET name_th = 'นายพลโครงกระดูก' WHERE name = 'Skeleton General';
UPDATE monsters SET name_th = 'นายพลโครงกระดูก อีลีท' WHERE name = 'Skeleton General Elite';
UPDATE monsters SET name_th = 'โครงกระดูกอัศวิน' WHERE name = 'Skeleton Knight';
UPDATE monsters SET name_th = 'โครงกระดูกอัศวิน อีลีท' WHERE name = 'Skeleton Knight Elite';
UPDATE monsters SET name_th = 'โครงกระดูกมัสเคทเทียร์' WHERE name = 'Skeleton Musketeer';
UPDATE monsters SET name_th = 'โครงกระดูกมัสเคทเทียร์ อีลีท' WHERE name = 'Skeleton Musketeer Elite';
UPDATE monsters SET name_th = 'โครงกระดูกแรพเตอร์ อีลีท' WHERE name = 'Skeleton Rapter Elite';
UPDATE monsters SET name_th = 'โครงกระดูกผู้พิทักษ์' WHERE name = 'Skeleton defender';
UPDATE monsters SET name_th = 'โครงกระดูกทหารหอก' WHERE name = 'Skeleton lancer';
UPDATE monsters SET name_th = 'โครงกระดูกทหารหอก อีลีท' WHERE name = 'Skeleton lancer Elite';
UPDATE monsters SET name_th = 'โครงกระดูก แห่งเรเวแนนท์' WHERE name = 'Skeleton of revenent';
UPDATE monsters SET name_th = 'หัวหน้าทาส' WHERE name = 'Slave Chief';
UPDATE monsters SET name_th = 'สลอธ' WHERE name = 'Sloth';
UPDATE monsters SET name_th = 'หมีทุ่งหิมะ' WHERE name = 'Snowfield Bear';
UPDATE monsters SET name_th = 'ลาซิม-แลม ทุ่งหิมะ' WHERE name = 'Snowfield Lazim-lam';
UPDATE monsters SET name_th = 'ลิงบึง ทุ่งหิมะ อีลีท' WHERE name = 'Snowfield Swamp monkey Elite';
UPDATE monsters SET name_th = 'หมาป่า ทุ่งหิมะ อีลีท' WHERE name = 'Snowfield wolf Elite';
UPDATE monsters SET name_th = 'มนุษย์หิมะ' WHERE name = 'Snowman';
UPDATE monsters SET name_th = 'ทหารกองทัพเรือเลือด หอก' WHERE name = 'Spear blood Navy Soldier';
UPDATE monsters SET name_th = 'ปูแมงมุม อีลีท' WHERE name = 'SpiderCrab Elite';
UPDATE monsters SET name_th = 'สไปค์ร็อค อีลีท' WHERE name = 'Spikedrock Elite';
UPDATE monsters SET name_th = 'สไปโนซอรัส' WHERE name = 'Spinosaurus';
UPDATE monsters SET name_th = 'สมอเหล็ก' WHERE name = 'Steel anchor';
UPDATE monsters SET name_th = 'สเตโกซอรัส' WHERE name = 'Stegosaurus';
UPDATE monsters SET name_th = 'การ์กอยล์หิน' WHERE name = 'Stone Gargoyle';
UPDATE monsters SET name_th = 'เซเบอร์บอร์ลาย' WHERE name = 'Stripe Saberboar';
UPDATE monsters SET name_th = 'ซันฟลา สแวมป์มอน' WHERE name = 'Sunfla swampmon';
UPDATE monsters SET name_th = 'กูลสมบัติ บึง อีลีท' WHERE name = 'Swamp Ghouloftreasure Elite';
UPDATE monsters SET name_th = 'จัมปิ้งฟิช บึง อีลีท' WHERE name = 'Swamp Jumpingfish Elite';
UPDATE monsters SET name_th = 'ปูแมงมุม บึง' WHERE name = 'Swamp SpiderCrab';
UPDATE monsters SET name_th = 'ปูแมงมุม บึง อีลีท' WHERE name = 'Swamp SpiderCrab Elite';
UPDATE monsters SET name_th = 'หีบสมบัติเลียนแบบ บึง' WHERE name = 'Swamp Treasuremimic';
UPDATE monsters SET name_th = 'เดอะ คริสซาลิส' WHERE name = 'THE CHRYSALIS';
UPDATE monsters SET name_th = 'มอนสเตอร์พูดได้' WHERE name = 'Talk Monster';
UPDATE monsters SET name_th = 'ทอรัส' WHERE name = 'Taurus';
UPDATE monsters SET name_th = 'ทีคาปี้' WHERE name = 'Tcapy';
UPDATE monsters SET name_th = 'ทีคาปี้ อีลีท' WHERE name = 'Tcapy Elite';
UPDATE monsters SET name_th = 'ทีคาปี้ครูเอล' WHERE name = 'Tcapycruel';
UPDATE monsters SET name_th = 'ทีคาปี้ครูเอล อีลีท' WHERE name = 'Tcapycruel Elite';
UPDATE monsters SET name_th = 'ทีคาปี้เรนเจอร์' WHERE name = 'Tcapyranger';
UPDATE monsters SET name_th = 'ทีคาปี้เรนเจอร์ อีลีท' WHERE name = 'Tcapyranger Elite';
UPDATE monsters SET name_th = 'ทีคาปี้วอร์ริเออร์' WHERE name = 'Tcapywarrior';
UPDATE monsters SET name_th = 'ทีคาปี้วอร์ริเออร์ อีลีท' WHERE name = 'Tcapywarrior Elite';
UPDATE monsters SET name_th = 'เทนเดอร์คอร์' WHERE name = 'Tendercore';
UPDATE monsters SET name_th = 'ราชาแห่งทุ่งหญ้า' WHERE name = 'The King of meadow';
UPDATE monsters SET name_th = 'เดอะ เวลลันท์' WHERE name = 'The Veilant';
UPDATE monsters SET name_th = 'โจร เอลร็อก' WHERE name = 'Thief Elrog';
UPDATE monsters SET name_th = 'โจร กาเวน' WHERE name = 'Thief Gawein';
UPDATE monsters SET name_th = 'โจร โจเอล' WHERE name = 'Thief Joel';
UPDATE monsters SET name_th = 'โจร รูเฟอร์ส' WHERE name = 'Thief Rufers';
UPDATE monsters SET name_th = 'ธอราโคโทมี' WHERE name = 'Thoracotomy';
UPDATE monsters SET name_th = 'แตนลายเสือ' WHERE name = 'Tiger hornet';
UPDATE monsters SET name_th = 'ทอร์เชียร์' WHERE name = 'Torchere';
UPDATE monsters SET name_th = 'เต่า' WHERE name = 'Tortoise';
UPDATE monsters SET name_th = 'เมอร์แมน สมบัติ' WHERE name = 'Treasure Merman';
UPDATE monsters SET name_th = 'โฟบิแทน สมบัติ' WHERE name = 'Treasure Phobitan';
UPDATE monsters SET name_th = 'ซีลอท สมบัติ' WHERE name = 'Treasure Zealot';
UPDATE monsters SET name_th = 'สาวสมบัติ' WHERE name = 'Treasuremaiden';
UPDATE monsters SET name_th = 'หีบสมบัติเลียนแบบ อีลีท' WHERE name = 'Treasuremimic Elite';
UPDATE monsters SET name_th = 'ไทรเซอราทอปส์' WHERE name = 'TriCeratops';
UPDATE monsters SET name_th = 'ทีแวนเจสตี้' WHERE name = 'Tvanjesty';
UPDATE monsters SET name_th = 'สองหัว' WHERE name = 'Twin-headed';
UPDATE monsters SET name_th = 'ทหารอมตะ' WHERE name = 'Undead soldier';
UPDATE monsters SET name_th = 'อันเดอร์โกสท์' WHERE name = 'Underghost';
UPDATE monsters SET name_th = 'วลาดิเมียร์' WHERE name = 'VLADIMIR';
UPDATE monsters SET name_th = 'แวมไพร์แบท' WHERE name = 'Vampire Bat';
UPDATE monsters SET name_th = 'แวมไพร์แบท อีลีท' WHERE name = 'Vampire Bat Elite';
UPDATE monsters SET name_th = 'แวมไพร์แบทลอร์ด' WHERE name = 'Vampire Bat lord';
UPDATE monsters SET name_th = 'แวมไพร์แบทลอร์ด อีลีท' WHERE name = 'Vampire Bat lord Elite';
UPDATE monsters SET name_th = 'เวดาโนบาห์' WHERE name = 'Vedanobah';
UPDATE monsters SET name_th = 'เวดาโนบาห์ อีลีท' WHERE name = 'Vedanobah Elite';
UPDATE monsters SET name_th = 'เวโลซีแรพเตอร์' WHERE name = 'Veloci Raptor';
UPDATE monsters SET name_th = 'เวโลซีแรพเตอร์ อีลีท' WHERE name = 'Veloci Raptor Elite';
UPDATE monsters SET name_th = 'เวสปาโนลลา' WHERE name = 'Vespanolla';
UPDATE monsters SET name_th = 'แบร์เวิร์คเกอร์รุนแรง' WHERE name = 'Violence Bearworker';
UPDATE monsters SET name_th = 'แบร์เวิร์คเกอร์รุนแรง อีลีท' WHERE name = 'Violence Bearworker Elite';
UPDATE monsters SET name_th = 'วิซาจ' WHERE name = 'Visage';
UPDATE monsters SET name_th = 'วิซาจ อีลีท' WHERE name = 'Visage Elite';
UPDATE monsters SET name_th = 'วิซาจ นัวร์' WHERE name = 'Visage Noir';
UPDATE monsters SET name_th = 'วิซาจ รูจ' WHERE name = 'Visage Rouge';
UPDATE monsters SET name_th = 'วอร์ดอย' WHERE name = 'Vordoi';
UPDATE monsters SET name_th = 'วาห์ลันเช' WHERE name = 'WAHLANSCHE';
UPDATE monsters SET name_th = 'เวียร์ด-ไนท์' WHERE name = 'WEIRD-KNIGHT';
UPDATE monsters SET name_th = 'วอลเตอร์' WHERE name = 'Walter';
UPDATE monsters SET name_th = 'แวร์แบร์ จักเกอร์นอท' WHERE name = 'Werebear Juggernaut';
UPDATE monsters SET name_th = 'แวร์แบร์ สเลเยอร์' WHERE name = 'Werebear Slayer';
UPDATE monsters SET name_th = 'ผู้พิทักษ์เหล็กขาว' WHERE name = 'White Iron Keeper';
UPDATE monsters SET name_th = 'หมาป่าขาว อีลีท' WHERE name = 'Whitewolf Elite';
UPDATE monsters SET name_th = 'สุนัขป่า' WHERE name = 'Wild-dog';
UPDATE monsters SET name_th = 'การ์กอยล์ปีก' WHERE name = 'Winged-gargoyle';
UPDATE monsters SET name_th = 'หมาป่า' WHERE name = 'Wolf';
UPDATE monsters SET name_th = 'ร้าก' WHERE name = 'Wraig';
UPDATE monsters SET name_th = 'เรธ' WHERE name = 'Wraith';
UPDATE monsters SET name_th = 'ซาห์กอร์ป' WHERE name = 'Zahrgorp';
UPDATE monsters SET name_th = 'ซาวี ดิ กาวี' WHERE name = 'Zavi di Gavi';
UPDATE monsters SET name_th = 'ซีลอท' WHERE name = 'Zealot';
UPDATE monsters SET name_th = 'ซีลอท อีลีท' WHERE name = 'Zealot Elite';
UPDATE monsters SET name_th = 'ซีบร้า-อีทเตอร์' WHERE name = 'Zebra-eater';
UPDATE monsters SET name_th = 'ซีบร้า-อีทเตอร์ อีลีท' WHERE name = 'Zebra-eater Elite';
UPDATE monsters SET name_th = 'ซอมบี้-เมอร์แมน' WHERE name = 'Zombie-merman';
UPDATE monsters SET name_th = 'ซอมบี้-เมอร์แมน อีลีท' WHERE name = 'Zombie-merman Elite';
UPDATE monsters SET name_th = 'ค็อคคาทริซใหญ่' WHERE name = 'cockatricebig';
UPDATE monsters SET name_th = 'ไอน์ชเวียร์' WHERE name = 'einschwer';
UPDATE monsters SET name_th = 'คลอว์ที่ถูกลืม' WHERE name = 'forgottenclaw';
UPDATE monsters SET name_th = 'ไอเกิลชิวาร์ลิเออร์ที่ถูกลืม' WHERE name = 'forgotteneigleschivarlier';
UPDATE monsters SET name_th = 'การ์กอยล์ที่ถูกลืม' WHERE name = 'forgottengargoyle';
UPDATE monsters SET name_th = 'เฮเลน่าที่ถูกลืม' WHERE name = 'forgottenhelena';
UPDATE monsters SET name_th = 'เมอร์แมนซอมบี้ที่ถูกลืม' WHERE name = 'forgottenmermanzombie';
UPDATE monsters SET name_th = 'เนวาเรที่ถูกลืม' WHERE name = 'forgottennevare';
UPDATE monsters SET name_th = 'สองหัวที่ถูกลืม' WHERE name = 'forgottentwinheaded';
UPDATE monsters SET name_th = 'วอลเตอร์ที่ถูกลืม' WHERE name = 'forgottenwalter';
UPDATE monsters SET name_th = 'ทหาร อิลลิเออร์' WHERE name = 'illier Soldier';
UPDATE monsters SET name_th = 'สาว' WHERE name = 'maiden';
