-- 018: Raids data (130 raid bosses)
-- Auto-generated from ge-db.site scrape

INSERT INTO raids (name, slug, race, level, location, name_th) VALUES
('Abyss Abeth', 'raid-monarmdun04boss02', 'Demon', 150, 'Armonia, Biego', NULL),
('Abyss Afear', 'raid-monarmdun04boss022', 'Demon', 150, 'Armonia, Biego', NULL),
('Abyss Army', 'raid-monifarmraidboss', 'Demon', 150, 'Distorted Armonia / Distorted Armonia, Apostadero', NULL),
('Abyss Cray', 'raid-monarmdun03boss02', 'Demon', 150, 'Armonia, Gloria', NULL),
('Abyss Deathgloshe', 'raid-monarmdun02boss01', 'Demon', 150, 'Armonia, El Templo', NULL),
('Abyss Deceth', 'raid-monarmdun02boss02', 'Demon', 150, 'Armonia, El Templo', NULL),
('Abyss Gloom', 'raid-monarmdun01boss02', 'Demon', 150, 'Armonia, En Celar', NULL),
('Abyss Gorgon Shield', 'raid-mongorgonboss', 'Golem', 150, 'Lucifer Castle, Banquet Hall', NULL),
('Abyss Hassen', 'raid-monarmdun04boss012', 'Demon', 150, 'Armonia, Biego', NULL),
('Abyss Hatz', 'raid-monarmdun04boss01', 'Demon', 150, 'Armonia, Biego', NULL),
('Abyss Maddie', 'raid-monarmdun03boss01', 'Demon', 150, 'Armonia, Gloria', NULL),
('Abyss Sorrow', 'raid-monarmdun01boss01', 'Demon', 150, 'Armonia, En Celar', NULL),
('Abyss', 'raid-monarmabyss', 'Demon', 150, 'Armonia, El Adio', NULL),
('Ancient Golem Talos', 'raid-monbtlbedel01boss', 'Golem', 150, 'Bedel Plain', NULL),
('Arbremon 1', 'raid-monraidarbremon1', 'Wildlife', 135, 'Lucifer Castle, Secret Garden', NULL),
('Arbremon 1', 'raid-monraidarbremon2', 'Wildlife', 135, 'Lucifer Castle, Secret Garden', NULL),
('Argusbrain', 'raid-monfldargusbrain', 'Demon', 135, 'Cabeza de Gigante', NULL),
('Bear Infected with Abyss', 'raid-monarmmiddleboss2', 'Wildlife', 125, 'Crater of Joaquin', NULL),
('Beast, Juergen', 'raid-monordenyuruegen', 'Wildlife', 150, 'Distorted Time : Snowfield of the Ice Wizard', NULL),
('Beast, Jurgen Furholden', 'raid-monraidyuruegen', 'Wildlife', 138, 'Lucifer Castle, Moonlight Garden', NULL),
('Betrayal Sunuk', 'raid-monbrotherft2', 'Golem', 150, 'Lucifer Castle, Banquet Hall', NULL),
('Black Death Wraith', 'raid-monraidrespawndeathwraith3', 'Undead', 140, 'Lucifer Castle, Basement Laboratory', NULL),
('Blood-Drunken Quinnitula', 'raid-monalt02boss', 'Demon', 150, 'River of Fire', NULL),
('Blue Death Wraith', 'raid-monraidrespawndeathwraith2', 'Undead', 140, 'Lucifer Castle, Basement Laboratory', NULL),
('Breeze', 'raid-monraidbreeze', 'Wildlife', 100, 'Bristia, the Scar', NULL),
('Brontes', 'raid-monduneinheri01boss', 'Golem', 155, 'Quiritatio / Quiritatio, Einherjar', NULL),
('Candela', 'raid-monilecasile02b2', 'Golem', 150, 'Imperium Rex (Distorted time)', NULL),
('Cazurro', 'raid-monilecasile02b3', 'Golem', 150, 'Imperium Rex (Distorted time)', NULL),
('Chimera No. 666', 'raid-monchimeralucifer01', 'Golem', 145, 'Lucifer Castle, Basement Warehouse', NULL),
('Cruise', 'raid-monraidcrueluz', 'Wildlife', 135, 'Lucifer Castle, Moonlight Garden', NULL),
('Cursed Person', 'raid-monvironhardmelee', 'Human', 145, 'Lucifer Castle, Death Corridor', NULL),
('Cyclops', 'raid-monduneinheri01mboss', 'Golem', 155, 'Quiritatio / Quiritatio, Einherjar', NULL),
('Dark Jormongand', 'raid-monlucifer01jormongand', 'Wildlife', 140, 'Lucifer Castle, Basement Laboratory', NULL),
('Dekaravia', 'raid-monskelsc', 'Undead', 130, 'Old Port of Coimbra', NULL),
('Despicable Uni', 'raid-monilecasile01a1', 'Wildlife', 150, 'Imperium Arma (Distorted time)', NULL),
('Diablo', 'raid-monraiddiablo', 'Demon', 130, 'Dungeon Ruins', NULL),
('Distorted Patrikyon Barto Lieutenant General', 'raid-moncasile01b1boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Distorted Patrikyon Taki Lieutenant General', 'raid-moncasile01b2boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Distorted White Wolf', 'raid-moncasile02b1boss', 'Human', 150, 'Imperium Rex (Distorted time)', NULL),
('Doom Slave', 'raid-mondoomslaveraid', 'Human', 160, 'Distorted Armonia / Distorted Armonia, Apostadero', NULL),
('Dorol the Dragon Warlord', 'raid-moncasile01lastboss', 'Wildlife', 150, 'Imperium Arma (Distorted time)', NULL),
('Dullahan, Cabeza', 'raid-monarmdun02boss03', 'Undead', 150, 'Armonia, El Templo', NULL),
('Einschiever', 'raid-moneinschwerraidnew', 'Demon', 135, 'Silent Maze Sanctuary', NULL),
('Enhanced Auto Baron T', 'raid-monautobarontraid', 'Golem', 150, 'Vernier Mansion 2nd Floor', NULL),
('Evora Chief Guard, Lt. Colonel Castledorr', 'raid-moncasile01c3boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Evora Riot Squad Leader, Lt. Colonel Zero', 'raid-moncasile01c1boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Evora Search Party Leader, Wiz House Lt. Colonel', 'raid-moncasile01c2boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Evora Striking Force Leader, Lt. Colonel Colchis', 'raid-moncasile01c4boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Experimental Undertaker', 'raid-monundertakerlucifer01', 'Undead', 130, 'Lucifer Castle, Basement Warehouse', NULL),
('First Abyss Oscuras', 'raid-monoscuras', 'Demon', 150, 'Armonia, El Templo', NULL),
('Footman Sanbok', 'raid-monlucifer01raidfriend', 'Golem', 130, 'Lucifer Castle, Basement Laboratory', NULL),
('Footman Sunuk', 'raid-monlucifer01raidfriend2', 'Golem', 130, 'Lucifer Castle, Basement Laboratory', NULL),
('Goldgaras', 'raid-mongoldgaras', 'Undead', 150, 'Lucifer Castle, Banquet Hall', NULL),
('Great Gluttony', 'raid-monlucifer01greatgluttony', 'Demon', 138, 'Lucifer Castle, Basement Laboratory', NULL),
('Great Lich', 'raid-monlichbat', 'Undead', 150, 'Lucifer Castle, Banquet Hall', NULL),
('Great Monkey', 'raid-monrecallgreatmonkey', 'Wildlife', 130, 'Lucifer Castle, Secret Garden', NULL),
('Griffon', 'raid-monrecallgf', 'Wildlife', 130, 'Vegas Javier', NULL),
('Guard Dog, Serverus', 'raid-monilecasile02a1', 'Wildlife', 150, 'Imperium Rex (Distorted time)', NULL),
('Guard dog, Serverus', 'raid-moncasile01d3boss', 'Golem', 150, 'Imperium Arma (Distorted time)', NULL),
('Hell General, Cobs', 'raid-moncorpselucifer01', 'Golem', 130, 'Lucifer Castle, Basement Warehouse', NULL),
('Hell General, Marcia', 'raid-monmarcialucifer01', 'Undead', 130, 'Lucifer Castle, Basement Warehouse', NULL),
('Hell General, Veil', 'raid-monbeholderlucifer01', 'Demon', 130, 'Lucifer Castle, Basement Warehouse', NULL),
('Hell Lord', 'raid-monhelllordlucifer01', 'Golem', 145, 'Lucifer Castle, Basement Warehouse', NULL),
('Hungry Ogjeff', 'raid-monalt01boss', 'Demon', 150, 'Camellia Thea', NULL),
('Joshua Baselrane', 'raid-moncasile01e2boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Key Holder', 'raid-monkeyholder', 'Undead', 140, 'Lucifer Castle, Death Corridor', NULL),
('King Betelgeuse', 'raid-monlucifer01stage2boss', 'Golem', 135, 'Lucifer Castle, Basement Laboratory', NULL),
('King Castor', 'raid-monlucifer01raid2boss3', 'Demon', 140, 'Lucifer Castle, Basement Laboratory', NULL),
('King Dragon Head 1', 'raid-monlucifer01stage3boss', 'Golem', 135, 'Lucifer Castle, Basement Laboratory', NULL),
('King Dragon Head 2', 'raid-monlucifer01stage3boss2', 'Golem', 135, 'Lucifer Castle, Basement Laboratory', NULL),
('King Pollux', 'raid-monlucifer01raid2boss2', 'Demon', 140, 'Lucifer Castle, Basement Laboratory', NULL),
('Kranus the Great Warlord', 'raid-moncasile02d3boss', 'Golem', 150, 'Imperium Rex (Distorted time)', NULL),
('Kumba', 'raid-monrecallbear', 'Wildlife', 130, 'Lucifer Castle, Secret Garden', NULL),
('Lavid', 'raid-monordenlavid', 'Undead', 150, 'Distorted Time : Torsches Mansion', NULL),
('Livre', 'raid-monilecasile02b1', 'Golem', 150, 'Imperium Rex (Distorted time)', NULL),
('Lust Witch', 'raid-monlucifer01lustwitch03', 'Demon', 138, 'Lucifer Castle, Basement Laboratory', NULL),
('Mage of Despair', 'raid-monmagelucifer03', 'Demon', 145, 'Lucifer Castle, Basement Warehouse', NULL),
('Mage of Greed', 'raid-monmagelucifer01', 'Demon', 145, 'Lucifer Castle, Basement Warehouse', NULL),
('Mage of Pain', 'raid-monmagelucifer02', 'Demon', 145, 'Lucifer Castle, Basement Warehouse', NULL),
('Magic Corps 1st Battalion Commander, Viscount Lily', 'raid-moncasile01e1boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Magic Support Unit, Major Shana', 'raid-moncasile02d2boss', 'Human', 150, 'Imperium Rex (Distorted time)', NULL),
('Mankind-Cleansing-Weapon, Evil', 'raid-monviron2evilboss', 'Golem', 150, 'Trumans Secret Laboratory', NULL),
('Mantara', 'raid-monraidmantara', 'Wildlife', 134, 'Lucifer Castle, Moonlight Garden', NULL),
('Medeia', 'raid-monmedeia', 'Demon', 150, 'Lucifer Castle, Banquet Hall', NULL),
('Memory-Eating Navas', 'raid-monarmnecrobus', 'Demon', 150, 'Armonia, El Soltado', NULL),
('Monarch of Ghost', 'raid-moncasile02c4boss', 'Golem', 150, 'Imperium Rex (Distorted time)', NULL),
('Moon Night', 'raid-monmoonknight', 'Undead', 150, 'Lucifer Castle, Death Corridor', NULL),
('Mutated Frogfish 3', 'raid-monlucifer01stage1bossc', 'Undead', 135, 'Lucifer Castle, Basement Laboratory', NULL),
('Novia', 'raid-monraidbossktv', 'Human', 135, 'Ice Wizards Tower, Novias Parlor', NULL),
('Patrikyon Riot Squad Leader, Lt. Colonel After Shock', 'raid-moncasile01d1boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Patrikyon Search Party, Lt. Colonel Killborn', 'raid-moncasile01d2boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Patrikyon Striking Force, Lt. Colonel Max 12', 'raid-moncasile01d4boss', 'Human', 150, 'Imperium Arma (Distorted time)', NULL),
('Pluton', 'raid-monpluton', 'Demon', 150, 'Lucifer Castle, Banquet Hall', NULL),
('Queenz-eater', 'raid-monraffboss1', 'Wildlife', 130, 'Ustiur, Zona Uno', NULL),
('Reckless Blue Titans Spirit', 'raid-moncasile02c2boss', 'Golem', 150, 'Imperium Rex (Distorted time)', NULL),
('Reckless Red Titans Spirit', 'raid-moncasile02c1boss', 'Golem', 150, 'Imperium Rex (Distorted time)', NULL),
('Red Death Wraith', 'raid-monraidrespawndeathwraith1', 'Undead', 140, 'Lucifer Castle, Basement Laboratory', NULL),
('Rex Chief Guard, Colonel Mador', 'raid-moncasile02d1boss', 'Human', 150, 'Imperium Rex (Distorted time)', NULL),
('Rhinoceur', 'raid-monrhinoceru', 'Undead', 150, 'Lucifer Castle, Death Corridor', NULL),
('Roaming Cydog', 'raid-monilecasile01a2', 'Undead', 150, 'Imperium Arma (Distorted time)', NULL),
('Rose, The Heart', 'raid-monraidroseheart', 'Wildlife', 135, 'Lucifer Castle, Moonlight Garden', NULL),
('Rose, The Spirit', 'raid-monraidrosespirit', 'Wildlife', 136, 'Lucifer Castle, Moonlight Garden', NULL),
('Ruincruger of Life', 'raid-monruincrugerboss', 'Wildlife', 150, 'Bahama, Demigod Forest', NULL),
('Sauterelle', 'raid-monraidsauterelle', 'Wildlife', 137, 'Lucifer Castle, Secret Garden', NULL),
('Scary Sanbok', 'raid-monbrotherft', 'Golem', 150, 'Lucifer Castle, Banquet Hall', NULL),
('Sekhmet', 'raid-mongigboss', 'Golem', 135, 'Inside Crater', NULL),
('Sheol of Desire', 'raid-monraidlandofdeathsheol', 'Golem', 148, 'Porto Bello, Deserted Quay', NULL),
('Soltiegus', 'raid-monraidrespawn', 'Demon', 135, 'Lucifer Castle, Secret Garden', NULL),
('Soul Mothtein', 'raid-moneventsm', 'Human', 100, 'Prison de Joaquin, Torture Chamber', NULL),
('Steel Skin Divino', 'raid-monbtlbah06boss', 'Wildlife', 150, 'Bahama, Altar of Heaven', NULL),
('Stone Cortes', 'raid-monstonecorteslucifer01', 'Golem', 140, 'Lucifer Castle, Basement Warehouse', NULL),
('Straggled Combat Soldier', 'raid-monarmmiddleboss4', 'Undead', 125, 'Rio Albi', NULL),
('Straggled Guard', 'raid-monarmmiddleboss1', 'Demon', 125, 'Ustiur, Zona Tres', NULL),
('Straggled Lanceman', 'raid-monarmmiddleboss', 'Demon', 125, 'Demigod Forest', NULL),
('Straggled Peltast', 'raid-monarmmiddleboss3', 'Undead', 125, 'Thueringenwald', NULL),
('Tenacious Sicao', 'raid-monilecasile01a3', 'Golem', 150, 'Imperium Arma (Distorted time)', NULL),
('Tesserae Pharrel', 'raid-monduncaslucifer04boss', 'Human', 145, 'Lucifer Castle, Reception Hall of Oblivion', NULL),
('Testormento', 'raid-montestormentoraid', 'Human', 145, 'Prison de Joaquin, Torture Chamber', NULL),
('The Harvester', 'raid-monraidsiain', 'Undead', 125, 'Lucifer Castle, Moonlight Garden', NULL),
('Thick Face Elminor', 'raid-monelminor3', 'Demon', 135, 'Lucifer Castle, Death Corridor', NULL),
('Time and Space Portero', 'raid-monportero', 'Golem', 150, 'Lucifer Castle, Death Corridor', NULL),
('Titans Spirit Fighter', 'raid-moncasile02c3boss', 'Golem', 150, 'Imperium Rex (Distorted time)', NULL),
('Twin Pleasure Nephthys', 'raid-monnephtyslucifer01', 'Demon', 140, 'Lucifer Castle, Basement Warehouse', NULL),
('Twin Sensual Nephthys', 'raid-monnephtyslucifer02', 'Demon', 140, 'Lucifer Castle, Basement Warehouse', NULL),
('Undertaker', 'raid-monsubboss', 'Human', 114, 'Reboldoeux Culverts', NULL),
('Uraeus', 'raid-monraiduraeus', 'Wildlife', 130, 'Bahama, Underground Cave 2F', NULL),
('Vergo the Cursed', 'raid-monraidsharffen', 'Human', 130, 'Desolate Cliff of Porto Bello', NULL),
('Violent Gerero', 'raid-monrecallgr', 'Demon', 150, 'Prison de Joaquin, Gehenna Bridge', NULL),
('Wolfriner', 'raid-moncoboltlucifer01', 'Demon', 140, 'Lucifer Castle, Basement Warehouse', NULL),
('Wrath Devil', 'raid-monlucifer01raid2boss1', 'Demon', 140, 'Lucifer Castle, Basement Laboratory', NULL);