-- Migration 051: Thai names for melee weapons
-- Generated: 2026-03-16T03:33:18.340Z

-- SKIP: +10 Iskras Gray Belt(1 day) | belt (10-iskras-gray-belt-1-day)
-- SKIP: +10 Ruincrugers Hard Belt(1 day) | belt (10-ruincrugers-hard-belt-1-day)
-- SKIP: +10 Stars Guardians Belt(1 day) | belt (10-stars-guardians-belt-1-day)
UPDATE items SET name_th = 'อะบิส อาร์ม่า เข็มขัด' WHERE slug = 'abyss-arma-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า เข็มขัด (อีเวนต์)' WHERE slug = 'abyss-arma-belt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย เข็มขัด' WHERE slug = 'armonia-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย เข็มขัด (อีเวนต์)' WHERE slug = 'armonia-belt-event' AND name_th IS NULL;
-- SKIP: Belt of Artisan | belt (belt-of-artisan)
-- SKIP: Blue Belt of the Beast Legion Commander | belt (blue-belt-of-the-beast-legion-commander)
UPDATE items SET name_th = 'บริสเทีย เข็มขัด' WHERE slug = 'bristia-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'บริสเทีย เข็มขัด (อีเวนต์)' WHERE slug = 'bristia-belt-event' AND name_th IS NULL;
-- SKIP: Brontes Sturdy Belt | belt (brontes-sturdy-belt)
-- SKIP: Desapio Belt | belt (desapio-belt)
UPDATE items SET name_th = 'เดอุส มาชิน่า เข็มขัด' WHERE slug = 'deus-machina-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า เข็มขัด (อีเวนต์)' WHERE slug = 'deus-machina-belt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ เข็มขัด' WHERE slug = 'divine-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'อีวิล เข็มขัด' WHERE slug = 'evil-belt' AND name_th IS NULL;
-- SKIP: Giltines Demonic Belt | belt (giltines-demonic-belt)
-- SKIP: High Quality Belt | belt (high-quality-belt)
-- SKIP: Iskras Gray Belt | belt (iskras-gray-belt)
-- SKIP: Iskras Gray Belt (Illusion) | belt (iskras-gray-belt-illusion)
-- SKIP: Laimas Holy Belt | belt (laimas-holy-belt)
-- SKIP: Magic Belt | belt (magic-belt)
-- SKIP: Magic Belt (Event) | belt (magic-belt-event)
-- SKIP: Muertuos Belt | belt (muertuos-belt)
-- SKIP: Quiritatio Belt of Wisdom | belt (quiritatio-belt-of-wisdom)
-- SKIP: Rough Belt | belt (rough-belt)
-- SKIP: Ruincrugers Hard Belt | belt (ruincrugers-hard-belt)
-- SKIP: Ruincrugers Hard Belt (Illusion) | belt (ruincrugers-hard-belt-illusion)
-- SKIP: Stars Guardians Belt | belt (stars-guardians-belt)
-- SKIP: Stars Guardians Belt (Event) | belt (stars-guardians-belt-event)
UPDATE items SET name_th = 'สตราต้า เดวิล เข็มขัด' WHERE slug = 'strata-devil-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เข็มขัด (อีเวนต์)' WHERE slug = 'strata-devil-belt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน เข็มขัด' WHERE slug = 'valeron-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน เข็มขัด (อีเวนต์)' WHERE slug = 'valeron-belt-event' AND name_th IS NULL;
-- SKIP: Vigilar Tribes Belt | belt (vigilar-tribes-belt)
-- SKIP: Vigilar Tribes Belt (Event) | belt (vigilar-tribes-belt-event)
-- SKIP: Violantes Ashen Belt | belt (violantes-ashen-belt)
-- SKIP: Zodiac Belt | belt (zodiac-belt)
-- SKIP: Zodiac Belt (Event) | belt (zodiac-belt-event)
-- SKIP: [Dreaming] Iskra Belt | belt (dreaming-iskra-belt)
-- SKIP: [Dreaming] Ruincruger Belt | belt (dreaming-ruincruger-belt)
-- SKIP: [Dreaming] Violantes Belt | belt (dreaming-violantes-belt)
-- SKIP: [EVENT] Giltines Demonic Belt | belt (event-giltines-demonic-belt)
-- SKIP: [EVENT] Laimas Holy Belt | belt (event-laimas-holy-belt)
-- SKIP: [Lucid] Iskra Belt | belt (lucid-iskra-belt)
-- SKIP: [Lucid] Ruincruger Belt | belt (lucid-ruincruger-belt)
-- SKIP: [Lucid] Violantes Belt | belt (lucid-violantes-belt)
-- SKIP: [Reverie] Iskra Belt | belt (reverie-iskra-belt)
-- SKIP: [Reverie] Ruincruger Belt | belt (reverie-ruincruger-belt)
-- SKIP: [Reverie] Violantes Belt | belt (reverie-violantes-belt)
-- SKIP: A Maid Uniform | coat (a-maid-uniform)
UPDATE items SET name_th = 'อะบิส อาร์ม่า โค้ท' WHERE slug = 'abyss-arma-coat' AND name_th IS NULL;
-- SKIP: Albaes | coat (albaes)
-- SKIP: Amoladera Justocorps | coat (amoladera-justocorps)
-- SKIP: Amoladera Long Coat | coat (amoladera-long-coat)
-- SKIP: Amoladera Redingote | coat (amoladera-redingote)
-- SKIP: Armure Diabolique - Coat | coat (armure-diabolique-coat)
-- SKIP: Armure Diabolique - Coat (Event) | coat (armure-diabolique-coat-event)
-- SKIP: Armure Diabolique of Ziz - Coat | coat (armure-diabolique-of-ziz-coat)
-- SKIP: Armure Diabolique of Ziz - Coat (Event) | coat (armure-diabolique-of-ziz-coat-event)
-- SKIP: Astartes Coat | coat (astartes-coat)
-- SKIP: Blue Serpent Coat | coat (blue-serpent-coat)
-- SKIP: Blue Serpent Coat (No Use) | coat (blue-serpent-coat-no-use)
-- SKIP: Cinderella Coat (60 days)(No Use) | coat (cinderella-coat-60-days-no-use)
-- SKIP: Clara Mago | coat (clara-mago)
-- SKIP: Clara Mago of Cinderella | coat (clara-mago-of-cinderella)
-- SKIP: Clara Mago of Cinderella (60 days) | coat (clara-mago-of-cinderella-60-days)
-- SKIP: Coat | coat (coat)
UPDATE items SET name_th = 'โค้ทสัญญา (7 วัน)' WHERE slug = 'coat-of-contract-7-days' AND name_th IS NULL;
-- SKIP: Coat of Expert | coat (coat-of-expert)
-- SKIP: Coat of the Queen | coat (coat-of-the-queen)
-- SKIP: Consolidar Justocorps | coat (consolidar-justocorps)
-- SKIP: Consolidar Long Coat | coat (consolidar-long-coat)
-- SKIP: Consolidar Redingote | coat (consolidar-redingote)
-- SKIP: Corsair Rosso | coat (corsair-rosso)
-- SKIP: Corsair Rosso of Cinderella | coat (corsair-rosso-of-cinderella)
-- SKIP: Corsair Rosso of Cinderella (60 days) | coat (corsair-rosso-of-cinderella-60-days)
-- SKIP: Crescemento Coat | coat (crescemento-coat)
-- SKIP: Divine Le Blanc Coat | coat (divine-le-blanc-coat)
-- SKIP: Dragon Coat | coat (dragon-coat)
-- SKIP: Elite Albaes | coat (elite-albaes)
-- SKIP: Elite Calienalbino | coat (elite-calienalbino)
-- SKIP: Elite Camaryllis | coat (elite-camaryllis)
-- SKIP: Elite Coat | coat (elite-coat)
-- SKIP: Elite Deinclian | coat (elite-deinclian)
UPDATE items SET name_th = 'อีลิท Dignite โค้ท' WHERE slug = 'elite-dignite-coat' AND name_th IS NULL;
-- SKIP: Elite Dignite Coat (No Use) | coat (elite-dignite-coat-no-use)
UPDATE items SET name_th = 'อีลิท Dragon โค้ท' WHERE slug = 'elite-dragon-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง โค้ท' WHERE slug = 'elite-experimental-coat' AND name_th IS NULL;
-- SKIP: Elite Graciegote | coat (elite-graciegote)
-- SKIP: Elite Justocorps | coat (elite-justocorps)
UPDATE items SET name_th = 'อีลิท Le Blanc โค้ท' WHERE slug = 'elite-le-blanc-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Blanc โค้ท (อีเวนต์)' WHERE slug = 'elite-le-blanc-coat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Noir โค้ท' WHERE slug = 'elite-le-noir-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Noir โค้ท (อีเวนต์)' WHERE slug = 'elite-le-noir-coat-event' AND name_th IS NULL;
-- SKIP: Elite Le Noir Coat (No Use) | coat (elite-le-noir-coat-no-use)
-- SKIP: Elite Le Scarce Coat (No Use) | coat (elite-le-scarce-coat-no-use)
UPDATE items SET name_th = 'อีลิท Long โค้ท' WHERE slug = 'elite-long-coat' AND name_th IS NULL;
-- SKIP: Elite Pendera Jacket | coat (elite-pendera-jacket)
-- SKIP: Elite Redingote | coat (elite-redingote)
-- SKIP: Elite Striform | coat (elite-striform)
-- SKIP: Elite Variltorta | coat (elite-variltorta)
-- SKIP: Enhanced Dragon Coat | coat (enhanced-dragon-coat)
-- SKIP: Event Elite Le Blanc Coat (No Use) | coat (event-elite-le-blanc-coat-no-use)
-- SKIP: Event Elite Le Noir Coat (No Use) | coat (event-elite-le-noir-coat-no-use)
-- SKIP: Event Greek Croma Coat (No Use) | coat (event-greek-croma-coat-no-use)
UPDATE items SET name_th = 'อีวิล โค้ท' WHERE slug = 'evil-coat' AND name_th IS NULL;
-- SKIP: Experimental (No Use) | coat (experimental-no-use)
UPDATE items SET name_th = 'ทดลอง โค้ท' WHERE slug = 'experimental-coat' AND name_th IS NULL;
-- SKIP: Frontier Croma(Coat) | coat (frontier-croma-coat)
-- SKIP: Graciegote | coat (graciegote)
-- SKIP: Greek Croma (No Use) | coat (greek-croma-no-use)
-- SKIP: Greek Croma Coat | coat (greek-croma-coat)
-- SKIP: Greek Croma Coat (Event) | coat (greek-croma-coat-event)
-- SKIP: Justocorps | coat (justocorps)
-- SKIP: Le Blanc Coat | coat (le-blanc-coat)
-- SKIP: Le Blanc Coat (No Use) | coat (le-blanc-coat-no-use)
-- SKIP: Le Blanc of Cinderella Coat | coat (le-blanc-of-cinderella-coat)
-- SKIP: Le Blanc of Cinderella Coat (No Use) | coat (le-blanc-of-cinderella-coat-no-use)
-- SKIP: Le Blanc of Cinderella for Coat (60 days) | coat (le-blanc-of-cinderella-for-coat-60-days)
-- SKIP: Le Noir Coat | coat (le-noir-coat)
-- SKIP: Le Noir Coat (No Use) | coat (le-noir-coat-no-use)
-- SKIP: Le Pouvoir Coat | coat (le-pouvoir-coat)
-- SKIP: Le Pouvoir Coat (Not Use) | coat (le-pouvoir-coat-not-use)
-- SKIP: Le Scarce Coat | coat (le-scarce-coat)
-- SKIP: Le Scarce Coat (No Use) | coat (le-scarce-coat-no-use)
-- SKIP: Legacy - Royal Coat Armor | coat (legacy-royal-coat-armor)
UPDATE items SET name_th = 'ลีเจียน โค้ท' WHERE slug = 'legion-coat' AND name_th IS NULL;
-- SKIP: Long Coat | coat (long-coat)
-- SKIP: Nero Croma Coat | coat (nero-croma-coat)
-- SKIP: Nero Croma Coat (No Use) | coat (nero-croma-coat-no-use)
-- SKIP: Novice Coat | coat (novice-coat)
-- SKIP: Ogre Noir Coat | coat (ogre-noir-coat)
-- SKIP: Ogre Noir Coat Coat (No Use) | coat (ogre-noir-coat-coat-no-use)
-- SKIP: Old Elite Le Noir Coat | coat (old-elite-le-noir-coat)
-- SKIP: Old Greek Croma Coat | coat (old-greek-croma-coat)
-- SKIP: Old Santo De Blanc Coat | coat (old-santo-de-blanc-coat)
-- SKIP: Old Strata Devil Coat | coat (old-strata-devil-coat)
-- SKIP: Pendera Jacket | coat (pendera-jacket)
-- SKIP: Pioneer Coat | coat (pioneer-coat)
-- SKIP: Pioneer Combat Coat | coat (pioneer-combat-coat)
-- SKIP: Pioneer Mystic Coat | coat (pioneer-mystic-coat)
-- SKIP: Pioneer Old Coat | coat (pioneer-old-coat)
-- SKIP: Pioneer Practice Coat | coat (pioneer-practice-coat)
-- SKIP: Pioneer Thick Coat | coat (pioneer-thick-coat)
-- SKIP: Red Serpent Coat | coat (red-serpent-coat)
-- SKIP: Red Serpent Coat (No Use) | coat (red-serpent-coat-no-use)
-- SKIP: Redingote | coat (redingote)
-- SKIP: Rich Lord Coat | coat (rich-lord-coat)
-- SKIP: Royal Coat | coat (royal-coat)
-- SKIP: Santo De Blanc Coat | coat (santo-de-blanc-coat)
-- SKIP: Santo De Blanc Coat (Event) | coat (santo-de-blanc-coat-event)
-- SKIP: Santo De Blanc Coat (No Use) | coat (santo-de-blanc-coat-no-use)
-- SKIP: Santo De Blanc Coat (No Use) (Event) | coat (santo-de-blanc-coat-no-use-event)
-- SKIP: Sky Demons Armure Diabolique - Coat | coat (sky-demons-armure-diabolique-coat)
-- SKIP: Sky Demons Armure Diabolique - Coat (Event) | coat (sky-demons-armure-diabolique-coat-event)
-- SKIP: Strata Devil (No Use) | coat (strata-devil-no-use)
UPDATE items SET name_th = 'สตราต้า เดวิล โค้ท' WHERE slug = 'strata-devil-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล โค้ท (อีเวนต์)' WHERE slug = 'strata-devil-coat-event' AND name_th IS NULL;
-- SKIP: Strata Devil Coat (No Use) (Event) | coat (strata-devil-coat-no-use-event)
-- SKIP: Striform | coat (striform)
-- SKIP: Supreme Dignite Coat | coat (supreme-dignite-coat)
UPDATE items SET name_th = 'วาเลรอน โค้ท' WHERE slug = 'valeron-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา โค้ท' WHERE slug = 'vespanola-pioneer-support-coat' AND name_th IS NULL;
-- SKIP: [EVENT] Royal Coat | coat (event-royal-coat)
-- SKIP: +10 Stars Messengers Earring(1 day) | earring (10-stars-messengers-earring-1-day)
UPDATE items SET name_th = 'อะบิส อาร์ม่า ต่างหู' WHERE slug = 'abyss-arma-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า ต่างหู (อีเวนต์)' WHERE slug = 'abyss-arma-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย ต่างหู (อีเวนต์)' WHERE slug = 'armonia-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย ต่างหู' WHERE slug = 'armonia-earrings' AND name_th IS NULL;
-- SKIP: Beliths Corrupt Earring | earring (beliths-corrupt-earring)
UPDATE items SET name_th = 'บริสเทีย ต่างหู (อีเวนต์)' WHERE slug = 'bristia-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'บริสเทีย ต่างหู' WHERE slug = 'bristia-earrings' AND name_th IS NULL;
-- SKIP: Charisma of Reydeavaricia | earring (charisma-of-reydeavaricia)
-- SKIP: Charisma of Reydeavaricia (Event) | earring (charisma-of-reydeavaricia-event)
-- SKIP: Christinas Reinforced Earrings | earring (christinas-reinforced-earrings)
-- SKIP: Desapio Earrings | earring (desapio-earrings)
UPDATE items SET name_th = 'เดอุส มาชิน่า ต่างหู' WHERE slug = 'deus-machina-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า ต่างหู (อีเวนต์)' WHERE slug = 'deus-machina-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ ต่างหู' WHERE slug = 'divine-earrings' AND name_th IS NULL;
-- SKIP: Earring of Artisan | earring (earring-of-artisan)
-- SKIP: Enhanced Charisma of Reydeavaricia | earring (enhanced-charisma-of-reydeavaricia)
-- SKIP: Enhanced Charisma of Reydeavaricia (Event) | earring (enhanced-charisma-of-reydeavaricia-event)
-- SKIP: Enhanced Hope of Argus | earring (enhanced-hope-of-argus)
-- SKIP: Enhanced Hope of Argus (Event) | earring (enhanced-hope-of-argus-event)
-- SKIP: Enhanced Revelation of Abyss | earring (enhanced-revelation-of-abyss)
-- SKIP: Enhanced Revelation of Abyss (Event) | earring (enhanced-revelation-of-abyss-event)
-- SKIP: Enhanced Shadow of Abyss | earring (enhanced-shadow-of-abyss)
-- SKIP: Enhanced Shadow of Abyss (Event) | earring (enhanced-shadow-of-abyss-event)
-- SKIP: Enhanced Will of Argus | earring (enhanced-will-of-argus)
-- SKIP: Enhanced Will of Argus (Event) | earring (enhanced-will-of-argus-event)
UPDATE items SET name_th = 'อีวิล ต่างหู' WHERE slug = 'evil-earring' AND name_th IS NULL;
-- SKIP: Experimental Magic Earring | earring (experimental-magic-earring)
-- SKIP: Giltines Demonic Earring | earring (giltines-demonic-earring)
-- SKIP: Golden Earring | earring (golden-earring)
-- SKIP: Hamaans Ancient Star Earring (Event) | earring (hamaans-ancient-star-earring-event)
-- SKIP: High Quality Earring | earring (high-quality-earring)
-- SKIP: Hope of Argus | earring (hope-of-argus)
-- SKIP: Hope of Argus (Event) | earring (hope-of-argus-event)
-- SKIP: Laimas Holy Earring | earring (laimas-holy-earring)
UPDATE items SET name_th = 'ลีเจียน ต่างหู' WHERE slug = 'legion-earring' AND name_th IS NULL;
-- SKIP: Magic Earring (Event) | earring (magic-earring-event)
-- SKIP: Magical Earring | earring (magical-earring)
-- SKIP: Muertuos Earrings | earring (muertuos-earrings)
-- SKIP: Navas Abyssal Earring | earring (navas-abyssal-earring)
-- SKIP: Quiritatio Earrings of Judgement | earring (quiritatio-earrings-of-judgement)
-- SKIP: Revelation of Abyss | earring (revelation-of-abyss)
-- SKIP: Revelation of Abyss (Event) | earring (revelation-of-abyss-event)
-- SKIP: Shadow of Abyss | earring (shadow-of-abyss)
-- SKIP: Shadow of Abyss (Event) | earring (shadow-of-abyss-event)
-- SKIP: Silver Earring | earring (silver-earring)
-- SKIP: Stars Messengers Earring | earring (stars-messengers-earring)
-- SKIP: Stars Messengers Earring (Event) | earring (stars-messengers-earring-event)
UPDATE items SET name_th = 'สตราต้า เดวิล ต่างหู (อีเวนต์)' WHERE slug = 'strata-devil-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล ต่างหู' WHERE slug = 'strata-devil-earrings' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน ต่างหู' WHERE slug = 'valeron-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน ต่างหู (อีเวนต์)' WHERE slug = 'valeron-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา ต่างหู' WHERE slug = 'vespanola-pioneer-support-earring' AND name_th IS NULL;
-- SKIP: Vigilar Tribes Earring | earring (vigilar-tribes-earring)
-- SKIP: Vigilar Tribes Earring (Event) | earring (vigilar-tribes-earring-event)
-- SKIP: Will of Argus | earring (will-of-argus)
-- SKIP: Will of Argus (Event) | earring (will-of-argus-event)
-- SKIP: Zodiac Earring | earring (zodiac-earring)
-- SKIP: Zodiac Earring (Event) | earring (zodiac-earring-event)
-- SKIP: [Dreaming] Beliths Earring | earring (dreaming-beliths-earring)
-- SKIP: [Dreaming] Navas Earring | earring (dreaming-navas-earring)
-- SKIP: [EVENT] Giltines Demonic Earring | earring (event-giltines-demonic-earring)
-- SKIP: [EVENT] Laimas Holy Earring | earring (event-laimas-holy-earring)
-- SKIP: [Lucid] Beliths Earring | earring (lucid-beliths-earring)
-- SKIP: [Lucid] Navas Earring | earring (lucid-navas-earring)
-- SKIP: [Reverie] Beliths Earring | earring (reverie-beliths-earring)
-- SKIP: [Reverie] Navas Earring | earring (reverie-navas-earring)
-- SKIP: +10 Gereros Power Glove(1 day) | glove (10-gereros-power-glove-1-day)
-- SKIP: +10 Ogjeffs Earth-color Glove(1 day) | glove (10-ogjeffs-earth-color-glove-1-day)
-- SKIP: +10 Stars Judges Glove (1 day) | glove (10-stars-judges-glove-1-day)
UPDATE items SET name_th = 'อะบิส อาร์ม่า ถุงมือ' WHERE slug = 'abyss-arma-glove' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า ถุงมือ (อีเวนต์)' WHERE slug = 'abyss-arma-glove-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย ถุงมือ (อีเวนต์)' WHERE slug = 'armonia-glove-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย ถุงมือ' WHERE slug = 'armonia-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'บริสเทีย ถุงมือ' WHERE slug = 'bristia-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'บริสเทีย ถุงมือ (อีเวนต์)' WHERE slug = 'bristia-gloves-event' AND name_th IS NULL;
-- SKIP: Desapio Gloves | glove (desapio-gloves)
UPDATE items SET name_th = 'เดอุส มาชิน่า ถุงมือ' WHERE slug = 'deus-machina-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า ถุงมือ (อีเวนต์)' WHERE slug = 'deus-machina-gloves-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ ถุงมือ' WHERE slug = 'divine-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'อีวิล ถุงมือ' WHERE slug = 'evil-gloves' AND name_th IS NULL;
-- SKIP: Experimental Magic Glove | glove (experimental-magic-glove)
-- SKIP: Gereros Power Glove | glove (gereros-power-glove)
-- SKIP: Gereros Power Glove (Illusion) | glove (gereros-power-glove-illusion)
-- SKIP: Giltines Demonic Gloves | glove (giltines-demonic-gloves)
UPDATE items SET name_th = 'ถุงมือสัญญา (7 วัน)' WHERE slug = 'glove-of-contract-7-days' AND name_th IS NULL;
-- SKIP: Glove of Magician | glove (glove-of-magician)
-- SKIP: Gloves | glove (gloves)
-- SKIP: Gloves of Artisan | glove (gloves-of-artisan)
-- SKIP: Laimas Holy Gloves | glove (laimas-holy-gloves)
UPDATE items SET name_th = 'ลีเจียน ถุงมือ' WHERE slug = 'legion-gloves' AND name_th IS NULL;
-- SKIP: Magic Gloves | glove (magic-gloves)
-- SKIP: Magic Gloves (Event) | glove (magic-gloves-event)
-- SKIP: Muertuos Gloves | glove (muertuos-gloves)
-- SKIP: Mystic Gloves | glove (mystic-gloves)
-- SKIP: Navas Dark Gloves | glove (navas-dark-gloves)
-- SKIP: Ogjeffs Earth-color Glove | glove (ogjeffs-earth-color-glove)
-- SKIP: Ogjeffs Earth-color Glove (Illusion) | glove (ogjeffs-earth-color-glove-illusion)
-- SKIP: Pioneer Gloves | glove (pioneer-gloves)
-- SKIP: Quiritatio Unity Gloves | glove (quiritatio-unity-gloves)
-- SKIP: Stars Judges Glove | glove (stars-judges-glove)
-- SKIP: Stars Judges Gloves (Event) | glove (stars-judges-gloves-event)
UPDATE items SET name_th = 'สตราต้า เดวิล ถุงมือ' WHERE slug = 'strata-devil-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล ถุงมือ (อีเวนต์)' WHERE slug = 'strata-devil-gloves-event' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน ถุงมือ' WHERE slug = 'valeron-glove' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน ถุงมือ (อีเวนต์)' WHERE slug = 'valeron-glove-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา ถุงมือ' WHERE slug = 'vespanola-pioneer-support-gloves' AND name_th IS NULL;
-- SKIP: Vigilar Tribes Gloves | glove (vigilar-tribes-gloves)
-- SKIP: Vigilar Tribes Gloves (Event) | glove (vigilar-tribes-gloves-event)
-- SKIP: Zodiac Glove (Event) | glove (zodiac-glove-event)
-- SKIP: Zodiac Gloves | glove (zodiac-gloves)
-- SKIP: [Dreaming] Gerero Gloves | glove (dreaming-gerero-gloves)
-- SKIP: [Dreaming] Ogjeffs Gloves | glove (dreaming-ogjeffs-gloves)
-- SKIP: [EVENT] Giltines Demonic Gloves | glove (event-giltines-demonic-gloves)
-- SKIP: [EVENT] Laimas Holy Gloves | glove (event-laimas-holy-gloves)
-- SKIP: [Lucid] Gerero Gloves | glove (lucid-gerero-gloves)
-- SKIP: [Lucid] Ogjeffs Gloves | glove (lucid-ogjeffs-gloves)
-- SKIP: [Reverie] Gerero Gloves | glove (reverie-gerero-gloves)
-- SKIP: [Reverie] Ogjeffs Gloves | glove (reverie-ogjeffs-gloves)
UPDATE items SET name_th = 'อะบิส อาร์ม่า เกราะหนัง' WHERE slug = 'abyss-arma-leather-armor' AND name_th IS NULL;
-- SKIP: Amoladera Hard-leather Armor | leather (amoladera-hard-leather-armor)
-- SKIP: Amoladera Leather armor | leather (amoladera-leather-armor)
-- SKIP: Amoladera Studded-leather Armor | leather (amoladera-studded-leather-armor)
-- SKIP: Amoladera Sunset Stripe Suit | leather (amoladera-sunset-stripe-suit)
-- SKIP: Armor of Gladiator of Cinderella | leather (armor-of-gladiator-of-cinderella)
-- SKIP: Armor of the Gladiator | leather (armor-of-the-gladiator)
-- SKIP: Armure Diabolique - Leather Armor | leather (armure-diabolique-leather-armor)
-- SKIP: Armure Diabolique - Leather Armor (Event) | leather (armure-diabolique-leather-armor-event)
-- SKIP: Armure Diabolique of Behemoth - Leather Armor | leather (armure-diabolique-of-behemoth-leather-armor)
-- SKIP: Armure Diabolique of Behemoth - Leather Armor (Event) | leather (armure-diabolique-of-behemoth-leather-armor-event)
-- SKIP: Astartes Leather Armor | leather (astartes-leather-armor)
-- SKIP: Bear Suit | leather (bear-suit)
-- SKIP: Blessing of God | leather (blessing-of-god)
-- SKIP: Blue Serpent Leather Armor | leather (blue-serpent-leather-armor)
-- SKIP: Blue Serpent Leather Armor (No Use) | leather (blue-serpent-leather-armor-no-use)
-- SKIP: Bone Frame Armor | leather (bone-frame-armor)
-- SKIP: Camisa de Soldado | leather (camisa-de-soldado)
-- SKIP: Capezzolo di Pericolo | leather (capezzolo-di-pericolo)
-- SKIP: Capezzolo di Pericolo of Cinderella | leather (capezzolo-di-pericolo-of-cinderella)
-- SKIP: Capezzolo di Pericolo of Cinderella (60 days) | leather (capezzolo-di-pericolo-of-cinderella-60-days)
-- SKIP: Cinderella Le Blanc Leather Armor (60 days) | leather (cinderella-le-blanc-leather-armor-60-days)
-- SKIP: Cinderella Le Blanc Leather Armor (60 days)(No Use) | leather (cinderella-le-blanc-leather-armor-60-days-no-use)
-- SKIP: Consolidar Hard-leather Armor | leather (consolidar-hard-leather-armor)
-- SKIP: Consolidar Leather Armor | leather (consolidar-leather-armor)
-- SKIP: Consolidar Studded-leather armor | leather (consolidar-studded-leather-armor)
-- SKIP: Consolidar Sunset Stripe Suit | leather (consolidar-sunset-stripe-suit)
-- SKIP: Divine Le Blanc Leather Armor | leather (divine-le-blanc-leather-armor)
-- SKIP: Elite Arcanero Plate | leather (elite-arcanero-plate)
-- SKIP: Elite Bone Frame Armor | leather (elite-bone-frame-armor)
-- SKIP: Elite Camisa de Soldado | leather (elite-camisa-de-soldado)
-- SKIP: Elite Clarcana | leather (elite-clarcana)
UPDATE items SET name_th = 'อีลิท Dignite เกราะหนัง' WHERE slug = 'elite-dignite-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง เกราะหนัง' WHERE slug = 'elite-experimental-leather-armor' AND name_th IS NULL;
-- SKIP: Elite Hard-leather Armor | leather (elite-hard-leather-armor)
-- SKIP: Elite Inviardeco | leather (elite-inviardeco)
-- SKIP: Elite Laranja e Preto | leather (elite-laranja-e-preto)
UPDATE items SET name_th = 'อีลิท Le Blanc เกราะหนัง' WHERE slug = 'elite-le-blanc-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Blanc เกราะหนัง (อีเวนต์)' WHERE slug = 'elite-le-blanc-leather-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Noir เกราะหนัง' WHERE slug = 'elite-le-noir-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Noir เกราะหนัง (อีเวนต์)' WHERE slug = 'elite-le-noir-leather-armor-event' AND name_th IS NULL;
-- SKIP: Elite Le Noir Leather Armor (No Use) | leather (elite-le-noir-leather-armor-no-use)
-- SKIP: Elite Le Scarce Leather Armor (No Use) | leather (elite-le-scarce-leather-armor-no-use)
-- SKIP: Elite Leather Armor | leather (elite-leather-armor)
-- SKIP: Elite Leather Tunic | leather (elite-leather-tunic)
-- SKIP: Elite Piernoente | leather (elite-piernoente)
-- SKIP: Elite Rescue Suit | leather (elite-rescue-suit)
-- SKIP: Elite Ring Mail | leather (elite-ring-mail)
-- SKIP: Elite Studded-leather Armor | leather (elite-studded-leather-armor)
-- SKIP: Elite Sunset Stripe Suit | leather (elite-sunset-stripe-suit)
-- SKIP: EliteElite Dignite Leather Armor (No Use) | leather (eliteelite-dignite-leather-armor-no-use)
-- SKIP: Enhanced Bone Frame Armor | leather (enhanced-bone-frame-armor)
-- SKIP: Event Elite Le Blanc Leather Armor (No Use) | leather (event-elite-le-blanc-leather-armor-no-use)
-- SKIP: Event Elite Le Noir Leather Armor (No Use) | leather (event-elite-le-noir-leather-armor-no-use)
-- SKIP: Event Greek Croma Leather Armor (No Use) | leather (event-greek-croma-leather-armor-no-use)
UPDATE items SET name_th = 'อีวิล เกราะหนัง' WHERE slug = 'evil-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง เกราะหนัง' WHERE slug = 'experimental-leather-armor' AND name_th IS NULL;
-- SKIP: Experimental Leather Armor (No Use) | leather (experimental-leather-armor-no-use)
-- SKIP: Fanatic Suit | leather (fanatic-suit)
-- SKIP: Frontier Croma(Leather Armor) | leather (frontier-croma-leather-armor)
-- SKIP: Gladiator Armor of Cinderella (60 days) | leather (gladiator-armor-of-cinderella-60-days)
-- SKIP: Greek Croma (No Use) | leather (greek-croma-no-use)
-- SKIP: Greek Croma Leather Armor | leather (greek-croma-leather-armor)
-- SKIP: Greek Croma Leather Armor (Event) | leather (greek-croma-leather-armor-event)
-- SKIP: Grim Knight | leather (grim-knight)
-- SKIP: Hard-leather Armor | leather (hard-leather-armor)
-- SKIP: Laranja e Preto | leather (laranja-e-preto)
-- SKIP: Le Blanc (Leather Armor) | leather (le-blanc-leather-armor)
-- SKIP: Le Blanc Leather Armor (No Use) | leather (le-blanc-leather-armor-no-use)
-- SKIP: Le Blanc of Cinderella Leather Armor | leather (le-blanc-of-cinderella-leather-armor)
-- SKIP: Le Blanc of Cinderella Leather Armor (No Use) | leather (le-blanc-of-cinderella-leather-armor-no-use)
-- SKIP: Le Noir Leather Armor | leather (le-noir-leather-armor)
-- SKIP: Le Noir Leather Armor (No Use) | leather (le-noir-leather-armor-no-use)
-- SKIP: Le Pouvoir Leader Armor (Not Use) | leather (le-pouvoir-leader-armor-not-use)
-- SKIP: Le Pouvoir Leather Armor | leather (le-pouvoir-leather-armor)
-- SKIP: Le Scarce Leather Armor | leather (le-scarce-leather-armor)
-- SKIP: Le Scarce Leather Armor (No Use) | leather (le-scarce-leather-armor-no-use)
-- SKIP: Leather Armor | leather (leather-armor)
UPDATE items SET name_th = 'เกราะหนังสัญญา (7 วัน)' WHERE slug = 'leather-armor-of-contract-7-days' AND name_th IS NULL;
-- SKIP: Leather Coat of Expert | leather (leather-coat-of-expert)
-- SKIP: Leather Tunic | leather (leather-tunic)
-- SKIP: Leather Tunic from Queen | leather (leather-tunic-from-queen)
-- SKIP: Legacy - Royal Leather Armor | leather (legacy-royal-leather-armor)
UPDATE items SET name_th = 'ลีเจียน เกราะหนัง' WHERE slug = 'legion-leather-armor' AND name_th IS NULL;
-- SKIP: Light Demons Armure Diabolique - Leather Armor | leather (light-demons-armure-diabolique-leather-armor)
-- SKIP: Light Demons Armure Diabolique - Leather Armor (Event) | leather (light-demons-armure-diabolique-leather-armor-event)
-- SKIP: Nero Croma Leather Armor | leather (nero-croma-leather-armor)
-- SKIP: Nero Croma Leather Armor (No Use) | leather (nero-croma-leather-armor-no-use)
-- SKIP: Novice Leather Tunic | leather (novice-leather-tunic)
-- SKIP: Ogre Noir Mail | leather (ogre-noir-mail)
-- SKIP: Ogre Noir Mail (No Use) | leather (ogre-noir-mail-no-use)
-- SKIP: Oiled Body | leather (oiled-body)
-- SKIP: Old Elite Le Noir Leather Armor | leather (old-elite-le-noir-leather-armor)
-- SKIP: Old Greek Croma Leather Armor | leather (old-greek-croma-leather-armor)
-- SKIP: Old Strata Devil Leather Armor | leather (old-strata-devil-leather-armor)
-- SKIP: Pioneer Combat Leather Armor | leather (pioneer-combat-leather-armor)
-- SKIP: Pioneer Leather Armor | leather (pioneer-leather-armor)
-- SKIP: Pioneer Mystic Leather Armor | leather (pioneer-mystic-leather-armor)
-- SKIP: Pioneer Old Leather Armor | leather (pioneer-old-leather-armor)
-- SKIP: Pioneer Practice Leather Armor | leather (pioneer-practice-leather-armor)
-- SKIP: Pioneer Thick Leather Armor | leather (pioneer-thick-leather-armor)
-- SKIP: Red Serpent Leather Armor | leather (red-serpent-leather-armor)
-- SKIP: Red Serpent Leather Armor (No Use) | leather (red-serpent-leather-armor-no-use)
-- SKIP: Rescue Armor | leather (rescue-armor)
-- SKIP: Rescue Suit | leather (rescue-suit)
-- SKIP: Ring Mail | leather (ring-mail)
-- SKIP: Royal Leather Armor | leather (royal-leather-armor)
-- SKIP: Santo De Blanc Leather Armor | leather (santo-de-blanc-leather-armor)
-- SKIP: Santo De Blanc Leather Armor (Event) | leather (santo-de-blanc-leather-armor-event)
-- SKIP: Santo De Blanc Leather Armor (No Use) | leather (santo-de-blanc-leather-armor-no-use)
-- SKIP: Santo De Blanc Leather Armor (No Use) (Event) | leather (santo-de-blanc-leather-armor-no-use-event)
-- SKIP: Strata Devil (No Use) | leather (strata-devil-no-use)
UPDATE items SET name_th = 'สตราต้า เดวิล เกราะหนัง' WHERE slug = 'strata-devil-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เกราะหนัง (อีเวนต์)' WHERE slug = 'strata-devil-leather-armor-event' AND name_th IS NULL;
-- SKIP: Strata Devil Leather Armor (No Use) (Event) | leather (strata-devil-leather-armor-no-use-event)
-- SKIP: Studded-leather Armor | leather (studded-leather-armor)
-- SKIP: Sunset Striped Suit | leather (sunset-striped-suit)
-- SKIP: Supreme Dignite Leather | leather (supreme-dignite-leather)
UPDATE items SET name_th = 'วาเลรอน เกราะหนัง' WHERE slug = 'valeron-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา เกราะหนัง' WHERE slug = 'vespanola-pioneer-support-leather-armor' AND name_th IS NULL;
-- SKIP: [EVENT] Royal Leather Armor | leather (event-royal-leather-armor)
-- SKIP: Abyss Arma Leg-Guards | leg_guards (abyss-arma-leg-guards)
-- SKIP: Abyss Arma Leg-Guards (Event) | leg_guards (abyss-arma-leg-guards-event)
-- SKIP: Angel Leg-Guards | leg_guards (angel-leg-guards)
-- SKIP: Armonia Leg-Guards | leg_guards (armonia-leg-guards)
-- SKIP: Armonia Leg-Guards (Event) | leg_guards (armonia-leg-guards-event)
-- SKIP: Atlas Brutality | leg_guards (atlas-brutality)
-- SKIP: Atlas Brutality (Event) | leg_guards (atlas-brutality-event)
-- SKIP: Azulita of Speed | leg_guards (azulita-of-speed)
-- SKIP: Balance of Libra | leg_guards (balance-of-libra)
-- SKIP: Balance of Libra (Event) | leg_guards (balance-of-libra-event)
-- SKIP: Bristia Leg-Guards | leg_guards (bristia-leg-guards)
-- SKIP: Carbon Leg-Guards | leg_guards (carbon-leg-guards)
-- SKIP: Deus Machina Leg-guard | leg_guards (deus-machina-leg-guard)
-- SKIP: Deus Machina Leg-guard (Event) | leg_guards (deus-machina-leg-guard-event)
-- SKIP: Divine Leg-Guards | leg_guards (divine-leg-guards)
-- SKIP: Elite Balance of Libra | leg_guards (elite-balance-of-libra)
-- SKIP: Elite Balance of Libra (Event) | leg_guards (elite-balance-of-libra-event)
-- SKIP: Elite Bristia Leg-Guards | leg_guards (elite-bristia-leg-guards)
-- SKIP: Elite Bristia Leg-Guards (Event) | leg_guards (elite-bristia-leg-guards-event)
-- SKIP: Elite Experimental Leg-Guards | leg_guards (elite-experimental-leg-guards)
-- SKIP: Elite La Estrella | leg_guards (elite-la-estrella)
-- SKIP: Elite Leg-Guards | leg_guards (elite-leg-guards)
-- SKIP: Elite Leg-Guards of Storm | leg_guards (elite-leg-guards-of-storm)
-- SKIP: Elite Leg-Guards of Wind | leg_guards (elite-leg-guards-of-wind)
-- SKIP: Evil Leg-Guards | leg_guards (evil-leg-guards)
-- SKIP: Experimental Leg-Guards | leg_guards (experimental-leg-guards)
-- SKIP: Gluttony Leg-Guard | leg_guards (gluttony-leg-guard)
-- SKIP: Golden Feet | leg_guards (golden-feet)
-- SKIP: Incomplete Atlas Brutality | leg_guards (incomplete-atlas-brutality)
-- SKIP: La Estrella | leg_guards (la-estrella)
-- SKIP: Leg-Guards of Hanged Man | leg_guards (leg-guards-of-hanged-man)
-- SKIP: Leg-Guards of Raionu | leg_guards (leg-guards-of-raionu)
-- SKIP: Leg-Guards of Srutoss | leg_guards (leg-guards-of-srutoss)
-- SKIP: Leg-Guards of the Yeti | leg_guards (leg-guards-of-the-yeti)
-- SKIP: Leg-guard of Contract (7 Days) | leg_guards (leg-guard-of-contract-7-days)
-- SKIP: Legion Leg-guard | leg_guards (legion-leg-guard)
-- SKIP: Prospe Leg-Guards | leg_guards (prospe-leg-guards)
-- SKIP: Refined Vespanola Leg-Guards | leg_guards (refined-vespanola-leg-guards)
-- SKIP: Sigellight Leguard | leg_guards (sigellight-leguard)
-- SKIP: Strata Devil Leg-Guard | leg_guards (strata-devil-leg-guard)
-- SKIP: Strata Devil Leg-Guards (Event) | leg_guards (strata-devil-leg-guards-event)
-- SKIP: Tyrants Order Leg-guard | leg_guards (tyrants-order-leg-guard)
-- SKIP: Tyrants Order Leg-guard (Event) | leg_guards (tyrants-order-leg-guard-event)
-- SKIP: Valeron Leg-Guard | leg_guards (valeron-leg-guard)
-- SKIP: Valeron Leg-Guard (Event) | leg_guards (valeron-leg-guard-event)
-- SKIP: Vespanola Pioneer Support Leg-guard | leg_guards (vespanola-pioneer-support-leg-guard)
-- SKIP: Arche - Lumin | lumin (arche-lumin)
-- SKIP: Black Diamond - Lumin | lumin (black-diamond-lumin)
-- SKIP: Carpo - Lumin | lumin (carpo-lumin)
-- SKIP: Chessylite - Lumin | lumin (chessylite-lumin)
-- SKIP: Clenblaze - Lumin (30 days) | lumin (clenblaze-lumin-30-days)
-- SKIP: Coral - Lumin | lumin (coral-lumin)
-- SKIP: Eucanite - Lumin | lumin (eucanite-lumin)
-- SKIP: Eukelade - Lumin | lumin (eukelade-lumin)
-- SKIP: Fluorite - Lumin (3 days) | lumin (fluorite-lumin-3-days)
-- SKIP: Fluorite - Lumin (a days) | lumin (fluorite-lumin-a-days)
-- SKIP: Jade - Lumin (3 days) | lumin (jade-lumin-3-days)
-- SKIP: Jade - Lumin (a days) | lumin (jade-lumin-a-days)
-- SKIP: Kallichore - Lumin | lumin (kallichore-lumin)
-- SKIP: Kalyke - Lumin | lumin (kalyke-lumin)
-- SKIP: Kore - Lumin | lumin (kore-lumin)
-- SKIP: Kunzite - Lumin (3 days) | lumin (kunzite-lumin-3-days)
-- SKIP: Kunzite - Lumin (a days) | lumin (kunzite-lumin-a-days)
-- SKIP: Molderbite - Lumin (30 days) | lumin (molderbite-lumin-30-days)
-- SKIP: Onyx - Lumin | lumin (onyx-lumin)
-- SKIP: Pailite - Lumin (30 days) | lumin (pailite-lumin-30-days)
-- SKIP: Processed Bloodstone - Lumin | lumin (processed-bloodstone-lumin)
-- SKIP: Processed Garnet - Lumin | lumin (processed-garnet-lumin)
-- SKIP: Processed Lumin Catalyst | lumin (processed-lumin-catalyst)
-- SKIP: Processed Opal - Lumin | lumin (processed-opal-lumin)
-- SKIP: Processed Pearl - Lumin | lumin (processed-pearl-lumin)
-- SKIP: Processed Peridot - Lumin | lumin (processed-peridot-lumin)
-- SKIP: Processed Tanzanite - Lumin | lumin (processed-tanzanite-lumin)
-- SKIP: Processed Topaz - Lumin | lumin (processed-topaz-lumin)
-- SKIP: Processed Turquoise - Lumin | lumin (processed-turquoise-lumin)
-- SKIP: Processed Zircon - Lumin | lumin (processed-zircon-lumin)
-- SKIP: Rutelquart - Lumin (30 days) | lumin (rutelquart-lumin-30-days)
-- SKIP: Selenite - Lumin | lumin (selenite-lumin)
-- SKIP: Sodalite - Lumin (30 days) | lumin (sodalite-lumin-30-days)
-- SKIP: Superior Fluorite - Lumin | lumin (superior-fluorite-lumin)
-- SKIP: Superior Fluorite - Lumin (15 Days) | lumin (superior-fluorite-lumin-15-days)
-- SKIP: Superior Fluorite - Lumin (30 Days) | lumin (superior-fluorite-lumin-30-days)
-- SKIP: Superior Fluorite - Lumin (60 Days) | lumin (superior-fluorite-lumin-60-days)
-- SKIP: Superior Fluorite - Lumin (7 Days) | lumin (superior-fluorite-lumin-7-days)
-- SKIP: Superior Jade - Lumin | lumin (superior-jade-lumin)
-- SKIP: Superior Jade - Lumin (15 Days) | lumin (superior-jade-lumin-15-days)
-- SKIP: Superior Jade - Lumin (30 Days) | lumin (superior-jade-lumin-30-days)
-- SKIP: Superior Jade - Lumin (60 Days) | lumin (superior-jade-lumin-60-days)
-- SKIP: Superior Jade - Lumin (7 Days) | lumin (superior-jade-lumin-7-days)
-- SKIP: Superior Kunzite - Lumin | lumin (superior-kunzite-lumin)
-- SKIP: Superior Kunzite - Lumin (15 Days) | lumin (superior-kunzite-lumin-15-days)
-- SKIP: Superior Kunzite - Lumin (30 Days) | lumin (superior-kunzite-lumin-30-days)
-- SKIP: Superior Kunzite - Lumin (60 Days) | lumin (superior-kunzite-lumin-60-days)
-- SKIP: Superior Kunzite - Lumin (7 Days) | lumin (superior-kunzite-lumin-7-days)
-- SKIP: Taaffeite - Lumin | lumin (taaffeite-lumin)
-- SKIP: Abyss Arma Magic Scroll | magic_scroll (abyss-arma-magic-scroll)
-- SKIP: Abyss Arma Magic Scroll (Event) | magic_scroll (abyss-arma-magic-scroll-event)
-- SKIP: Abyss Scroll | magic_scroll (abyss-scroll)
-- SKIP: Abyss Scroll (Event) | magic_scroll (abyss-scroll-event)
-- SKIP: Armonia Grimoire | magic_scroll (armonia-grimoire)
-- SKIP: Armonia Grimoire (Event) | magic_scroll (armonia-grimoire-event)
-- SKIP: Chloes Wisdom | magic_scroll (chloes-wisdom)
-- SKIP: Chloes Wisdom (Event) | magic_scroll (chloes-wisdom-event)
-- SKIP: Crescemento Encyclopedia | magic_scroll (crescemento-encyclopedia)
-- SKIP: Deus Machina Grimoire | magic_scroll (deus-machina-grimoire)
-- SKIP: Deus Machina Grimoire (Event) | magic_scroll (deus-machina-grimoire-event)
-- SKIP: Diary of Veronif | magic_scroll (diary-of-veronif)
-- SKIP: Diary of Veronif (Event) | magic_scroll (diary-of-veronif-event)
-- SKIP: Divine Encyclopedia | magic_scroll (divine-encyclopedia)
-- SKIP: Divine Magic Book | magic_scroll (divine-magic-book)
-- SKIP: Elite Experimental Encyclopedia | magic_scroll (elite-experimental-encyclopedia)
-- SKIP: Elite Experimental Magic Scroll | magic_scroll (elite-experimental-magic-scroll)
-- SKIP: Elite Muertuors Book | magic_scroll (elite-muertuors-book)
-- SKIP: Encyclopedia | magic_scroll (encyclopedia)
-- SKIP: Encyclopedia (Event) | magic_scroll (encyclopedia-event)
-- SKIP: Encyclopedia of Contract (7 Days) | magic_scroll (encyclopedia-of-contract-7-days)
-- SKIP: Enex Ethereal Grimoire | magic_scroll (enex-ethereal-grimoire)
-- SKIP: Event Elite Muertuors Book | magic_scroll (event-elite-muertuors-book)
-- SKIP: Event Muertuors Book | magic_scroll (event-muertuors-book)
-- SKIP: Experimental Encyclopedia | magic_scroll (experimental-encyclopedia)
-- SKIP: Experimental Magic Scroll | magic_scroll (experimental-magic-scroll)
-- SKIP: Incomplete Chloes Wisdom | magic_scroll (incomplete-chloes-wisdom)
-- SKIP: Knowledge of Mechanism | magic_scroll (knowledge-of-mechanism)
-- SKIP: Legion Magic Book | magic_scroll (legion-magic-book)
-- SKIP: Magic Scroll of Wilbur | magic_scroll (magic-scroll-of-wilbur)
-- SKIP: Masterpiece Diary | magic_scroll (masterpiece-diary)
-- SKIP: Masterpiece Diary (Event) | magic_scroll (masterpiece-diary-event)
-- SKIP: Masterpiece Encyclopedia | magic_scroll (masterpiece-encyclopedia)
-- SKIP: Masterpiece Encyclopedia (Event) | magic_scroll (masterpiece-encyclopedia-event)
-- SKIP: Muertuors Book | magic_scroll (muertuors-book)
-- SKIP: Prospe Encyclopedia | magic_scroll (prospe-encyclopedia)
-- SKIP: Prospe Magic Scroll | magic_scroll (prospe-magic-scroll)
-- SKIP: Refined Vespanola Magic Scroll | magic_scroll (refined-vespanola-magic-scroll)
-- SKIP: Theory of Lawrence | magic_scroll (theory-of-lawrence)
-- SKIP: Tyrants Order Grimoire | magic_scroll (tyrants-order-grimoire)
-- SKIP: Tyrants Order Grimoire (Event) | magic_scroll (tyrants-order-grimoire-event)
-- SKIP: Valeron Magic Scroll | magic_scroll (valeron-magic-scroll)
-- SKIP: Valeron Magic Scroll (Event) | magic_scroll (valeron-magic-scroll-event)
-- SKIP: Vespanola Pioneer Support Magic Book | magic_scroll (vespanola-pioneer-support-magic-book)
-- SKIP: Witch Craft | magic_scroll (witch-craft)
-- SKIP: Witch Craft (Event) | magic_scroll (witch-craft-event)
-- SKIP: [Event] Enex Ethereal Grimoire | magic_scroll (event-enex-ethereal-grimoire)
UPDATE items SET name_th = 'อะบิส อาร์ม่า เกราะโลหะ' WHERE slug = 'abyss-arma-metal-armor' AND name_th IS NULL;
-- SKIP: Amoladera Chain Mail | metal (amoladera-chain-mail)
-- SKIP: Amoladera Scale Armor | metal (amoladera-scale-armor)
-- SKIP: Amoladera Splint Mail | metal (amoladera-splint-mail)
-- SKIP: Armor of the Pirate | metal (armor-of-the-pirate)
-- SKIP: Armure Diabolique - Metal Armor | metal (armure-diabolique-metal-armor)
-- SKIP: Armure Diabolique - Metal Armor (Event) | metal (armure-diabolique-metal-armor-event)
-- SKIP: Armure Diabolique of Behemoth - Metal Armor | metal (armure-diabolique-of-behemoth-metal-armor)
-- SKIP: Armure Diabolique of Behemoth - Metal Armor (Event) | metal (armure-diabolique-of-behemoth-metal-armor-event)
-- SKIP: Astartes Metal Armor | metal (astartes-metal-armor)
-- SKIP: Breast Plate of Idge | metal (breast-plate-of-idge)
-- SKIP: Chain Mail | metal (chain-mail)
-- SKIP: Consolidar Chain Mail | metal (consolidar-chain-mail)
-- SKIP: Consolidar Scale Armor | metal (consolidar-scale-armor)
-- SKIP: Consolidar Splint Mail | metal (consolidar-splint-mail)
-- SKIP: Divine Le Blanc Plate | metal (divine-le-blanc-plate)
-- SKIP: Elite Chain Mail | metal (elite-chain-mail)
UPDATE items SET name_th = 'อีลิท ทดลอง เกราะโลหะ' WHERE slug = 'elite-experimental-metal-armor' AND name_th IS NULL;
-- SKIP: Elite General Plate | metal (elite-general-plate)
-- SKIP: Elite Metallic Suit | metal (elite-metallic-suit)
-- SKIP: Elite Plate | metal (elite-plate)
-- SKIP: Elite Scale Armor | metal (elite-scale-armor)
-- SKIP: Elite Schvarlier Armor | metal (elite-schvarlier-armor)
-- SKIP: Elite Schvarlier Armor(Event) | metal (elite-schvarlier-armor-event)
-- SKIP: Enhanced Breast Plate of Idge | metal (enhanced-breast-plate-of-idge)
-- SKIP: Evil Plate | metal (evil-plate)
UPDATE items SET name_th = 'ทดลอง เกราะโลหะ' WHERE slug = 'experimental-metal-armor' AND name_th IS NULL;
-- SKIP: Fate of Castilla | metal (fate-of-castilla)
-- SKIP: Fate of Castilla (Event) | metal (fate-of-castilla-event)
-- SKIP: Field Plate Mail | metal (field-plate-mail)
-- SKIP: Frontier Croma(Plate mail) | metal (frontier-croma-plate-mail)
-- SKIP: Full-plate Mail | metal (full-plate-mail)
-- SKIP: General Plate | metal (general-plate)
-- SKIP: General Plate(Event) | metal (general-plate-event)
-- SKIP: Knight of the Templar | metal (knight-of-the-templar)
-- SKIP: Le Scarce Plate | metal (le-scarce-plate)
-- SKIP: Legacy - Royal Metal Armor | metal (legacy-royal-metal-armor)
UPDATE items SET name_th = 'ลีเจียน เกราะโลหะ' WHERE slug = 'legion-metal-armor' AND name_th IS NULL;
-- SKIP: Light Demons Armure Diabolique - Metal Armor | metal (light-demons-armure-diabolique-metal-armor)
-- SKIP: Light Demons Armure Diabolique - Metal Armor (Event) | metal (light-demons-armure-diabolique-metal-armor-event)
-- SKIP: Metallic Suit | metal (metallic-suit)
-- SKIP: Metallic Suit of Cinderella | metal (metallic-suit-of-cinderella)
-- SKIP: Metallic Suit of Cinderella (60 days) | metal (metallic-suit-of-cinderella-60-days)
-- SKIP: Ogre Noir Plate | metal (ogre-noir-plate)
-- SKIP: Old Fate of Castilla | metal (old-fate-of-castilla)
-- SKIP: Old General Plate | metal (old-general-plate)
-- SKIP: Old Santuario Metal Armor | metal (old-santuario-metal-armor)
-- SKIP: Old Strata Devil Plate | metal (old-strata-devil-plate)
-- SKIP: Pioneer Combat Metal Armor | metal (pioneer-combat-metal-armor)
-- SKIP: Pioneer Metal Armor | metal (pioneer-metal-armor)
-- SKIP: Pioneer Mystic Metal Armor | metal (pioneer-mystic-metal-armor)
-- SKIP: Pioneer Reinforced Metal Armor | metal (pioneer-reinforced-metal-armor)
-- SKIP: Plate Mail | metal (plate-mail)
-- SKIP: Plate of Contract (7 Days) | metal (plate-of-contract-7-days)
-- SKIP: Plate of Predge | metal (plate-of-predge)
-- SKIP: Prototype of Idge | metal (prototype-of-idge)
-- SKIP: Red Serpent Plate | metal (red-serpent-plate)
-- SKIP: Royal Metal Armor | metal (royal-metal-armor)
-- SKIP: Santuario Metal Armor | metal (santuario-metal-armor)
-- SKIP: Santuario Metal Armor (Event) | metal (santuario-metal-armor-event)
-- SKIP: Scale Armor | metal (scale-armor)
-- SKIP: Schvarlier Armor | metal (schvarlier-armor)
-- SKIP: Schvarlier Armor of Cinderella | metal (schvarlier-armor-of-cinderella)
-- SKIP: Schvarlier Armor of Cinderella (60 days) | metal (schvarlier-armor-of-cinderella-60-days)
-- SKIP: Second type of Idge | metal (second-type-of-idge)
-- SKIP: Splint Mail | metal (splint-mail)
-- SKIP: Strata Devil Plate | metal (strata-devil-plate)
-- SKIP: Strata Devil Plate (Event) | metal (strata-devil-plate-event)
-- SKIP: Supreme Dignite Plate | metal (supreme-dignite-plate)
-- SKIP: Third type of Idge | metal (third-type-of-idge)
UPDATE items SET name_th = 'วาเลรอน เกราะโลหะ' WHERE slug = 'valeron-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา เกราะโลหะ' WHERE slug = 'vespanola-pioneer-support-metal-armor' AND name_th IS NULL;
-- SKIP: [EVENT] Royal Metal Armor | metal (event-royal-metal-armor)
-- SKIP: +10 Beliths Necklace in Chaos(1 day) | necklace (10-beliths-necklace-in-chaos-1-day)
-- SKIP: +10 Evils Brooch(1 day) | necklace (10-evils-brooch-1-day)
-- SKIP: +10 Stars Surveillants Necklace(1 day) | necklace (10-stars-surveillants-necklace-1-day)
UPDATE items SET name_th = 'อะบิส อาร์ม่า สร้อยคอ' WHERE slug = 'abyss-arma-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า สร้อยคอ (อีเวนต์)' WHERE slug = 'abyss-arma-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย สร้อยคอ' WHERE slug = 'armonia-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย สร้อยคอ (อีเวนต์)' WHERE slug = 'armonia-necklace-event' AND name_th IS NULL;
-- SKIP: Beliths Necklace in Chaos | necklace (beliths-necklace-in-chaos)
UPDATE items SET name_th = 'บริสเทีย สร้อยคอ' WHERE slug = 'bristia-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'บริสเทีย สร้อยคอ (อีเวนต์)' WHERE slug = 'bristia-necklace-event' AND name_th IS NULL;
-- SKIP: Crafted Necklace of Resistance to Attribute | necklace (crafted-necklace-of-resistance-to-attribute)
-- SKIP: Crafted Necklace of Resistance to Attribute (Event) | necklace (crafted-necklace-of-resistance-to-attribute-event)
-- SKIP: Crafted Physical RES Necklace | necklace (crafted-physical-res-necklace)
-- SKIP: Crafted Physical RES Necklace (Event) | necklace (crafted-physical-res-necklace-event)
-- SKIP: Crafted Shot RES Necklace | necklace (crafted-shot-res-necklace)
-- SKIP: Crafted Shot RES Necklace (Event) | necklace (crafted-shot-res-necklace-event)
-- SKIP: Created Necklace of Resistance to Attribute | necklace (created-necklace-of-resistance-to-attribute)
-- SKIP: Created Physical RES Necklace | necklace (created-physical-res-necklace)
-- SKIP: Created Shot RES Necklace | necklace (created-shot-res-necklace)
-- SKIP: Cut Necklace of Resistance to Attribute | necklace (cut-necklace-of-resistance-to-attribute)
-- SKIP: Cut Physical RES Necklace | necklace (cut-physical-res-necklace)
-- SKIP: Cut Shot RES Necklace | necklace (cut-shot-res-necklace)
-- SKIP: Desapio Necklace | necklace (desapio-necklace)
UPDATE items SET name_th = 'เดอุส มาชิน่า สร้อยคอ' WHERE slug = 'deus-machina-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า สร้อยคอ (อีเวนต์)' WHERE slug = 'deus-machina-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ สร้อยคอ' WHERE slug = 'divine-necklace' AND name_th IS NULL;
-- SKIP: Enhanced Necklace of Resistance to Attribute | necklace (enhanced-necklace-of-resistance-to-attribute)
-- SKIP: Enhanced Physical RES Necklace | necklace (enhanced-physical-res-necklace)
-- SKIP: Enhanced Shot RES Necklace | necklace (enhanced-shot-res-necklace)
UPDATE items SET name_th = 'อีวิล สร้อยคอ' WHERE slug = 'evil-necklace' AND name_th IS NULL;
-- SKIP: Evils Brooch | necklace (evils-brooch)
-- SKIP: Evils Brooch (Illusion) | necklace (evils-brooch-illusion)
UPDATE items SET name_th = 'ทดลอง สร้อยคอ' WHERE slug = 'experimental-necklace' AND name_th IS NULL;
-- SKIP: Giltines Demonic Necklace | necklace (giltines-demonic-necklace)
-- SKIP: Laimas Holy Necklace | necklace (laimas-holy-necklace)
UPDATE items SET name_th = 'ลีเจียน สร้อยคอ' WHERE slug = 'legion-necklace' AND name_th IS NULL;
-- SKIP: Muertuos Necklace | necklace (muertuos-necklace)
-- SKIP: Necklace by Contract (7 days) | necklace (necklace-by-contract-7-days)
-- SKIP: Necklace of Resistance to Attribute | necklace (necklace-of-resistance-to-attribute)
-- SKIP: Necklace of Wise man | necklace (necklace-of-wise-man)
-- SKIP: Physical RES Necklace | necklace (physical-res-necklace)
-- SKIP: Quiritatio Pledge Necklace | necklace (quiritatio-pledge-necklace)
-- SKIP: Revenants Ominous Necklace | necklace (revenants-ominous-necklace)
-- SKIP: Sheols Necklace in Chaos (Illusion) | necklace (sheols-necklace-in-chaos-illusion)
-- SKIP: Shot RES Necklace | necklace (shot-res-necklace)
-- SKIP: Stars Surveillants Necklace | necklace (stars-surveillants-necklace)
-- SKIP: Stars Surveillants Necklace (Event) | necklace (stars-surveillants-necklace-event)
UPDATE items SET name_th = 'สตราต้า เดวิล สร้อยคอ' WHERE slug = 'strata-devil-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล สร้อยคอ (อีเวนต์)' WHERE slug = 'strata-devil-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน สร้อยคอ' WHERE slug = 'valeron-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน สร้อยคอ (อีเวนต์)' WHERE slug = 'valeron-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา สร้อยคอ' WHERE slug = 'vespanola-pioneer-support-necklace' AND name_th IS NULL;
-- SKIP: Vigilar Tribes Necklace | necklace (vigilar-tribes-necklace)
-- SKIP: Vigilar Tribes Necklace (Event) | necklace (vigilar-tribes-necklace-event)
-- SKIP: Zodiac Necklace | necklace (zodiac-necklace)
-- SKIP: Zodiac Necklace (Event) | necklace (zodiac-necklace-event)
-- SKIP: [Dreaming] Evils Brooch | necklace (dreaming-evils-brooch)
-- SKIP: [Dreaming] Sheols Necklace | necklace (dreaming-sheols-necklace)
-- SKIP: [EVENT] Giltines Demonic Necklace | necklace (event-giltines-demonic-necklace)
-- SKIP: [EVENT] Laimas Holy Necklace | necklace (event-laimas-holy-necklace)
-- SKIP: [Lucid] Evils Brooch | necklace (lucid-evils-brooch)
-- SKIP: [Lucid] Sheols Necklace | necklace (lucid-sheols-necklace)
-- SKIP: [Reverie] Evils Brooch | necklace (reverie-evils-brooch)
-- SKIP: [Reverie] Sheols Necklace | necklace (reverie-sheols-necklace)
UPDATE items SET name_th = 'อะบิส อาร์ม่า โรบ' WHERE slug = 'abyss-arma-robe' AND name_th IS NULL;
-- SKIP: Alegrias | robe (alegrias)
-- SKIP: Amoladera Pure White Robe | robe (amoladera-pure-white-robe)
-- SKIP: Amoladera Robe | robe (amoladera-robe)
-- SKIP: Amoladera Robe of Lightning | robe (amoladera-robe-of-lightning)
-- SKIP: Amoladera Robe of Storm | robe (amoladera-robe-of-storm)
-- SKIP: Amoladera Robe of Thunder | robe (amoladera-robe-of-thunder)
-- SKIP: Amoladera Robe of Wind | robe (amoladera-robe-of-wind)
-- SKIP: Armure Diabolique - Robe | robe (armure-diabolique-robe)
-- SKIP: Armure Diabolique - Robe (Event) | robe (armure-diabolique-robe-event)
-- SKIP: Armure Diabolique of Leviathan - Robe | robe (armure-diabolique-of-leviathan-robe)
-- SKIP: Armure Diabolique of Leviathan - Robe (Event) | robe (armure-diabolique-of-leviathan-robe-event)
-- SKIP: Astartes Robe | robe (astartes-robe)
-- SKIP: Blue Serpent Robe | robe (blue-serpent-robe)
-- SKIP: Consolidar Robe | robe (consolidar-robe)
-- SKIP: Consolidar Robe of Lightning | robe (consolidar-robe-of-lightning)
-- SKIP: Consolidar Robe of Storm | robe (consolidar-robe-of-storm)
-- SKIP: Consolidar Robe of Thunder | robe (consolidar-robe-of-thunder)
-- SKIP: Consolidar Robe of White | robe (consolidar-robe-of-white)
-- SKIP: Consolidar Robe of Wind | robe (consolidar-robe-of-wind)
-- SKIP: Divine Le Blanc Robe | robe (divine-le-blanc-robe)
-- SKIP: Elite Alegrias | robe (elite-alegrias)
UPDATE items SET name_th = 'อีลิท Dignite โรบ' WHERE slug = 'elite-dignite-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง โรบ' WHERE slug = 'elite-experimental-robe' AND name_th IS NULL;
-- SKIP: Elite Geniaruleano | robe (elite-geniaruleano)
-- SKIP: Elite La Ventisca | robe (elite-la-ventisca)
UPDATE items SET name_th = 'อีลิท Le Blanc โรบ' WHERE slug = 'elite-le-blanc-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Blanc โรบ (อีเวนต์)' WHERE slug = 'elite-le-blanc-robe-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Noir โรบ' WHERE slug = 'elite-le-noir-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท Le Noir โรบ (อีเวนต์)' WHERE slug = 'elite-le-noir-robe-event' AND name_th IS NULL;
-- SKIP: Elite Robe of Aurora | robe (elite-robe-of-aurora)
-- SKIP: Elite Robe of Elementalist | robe (elite-robe-of-elementalist)
-- SKIP: Elite Robe of Fire | robe (elite-robe-of-fire)
-- SKIP: Elite Robe of Hellfire | robe (elite-robe-of-hellfire)
-- SKIP: Elite Robe of Ice | robe (elite-robe-of-ice)
-- SKIP: Elite Robe of Lightning | robe (elite-robe-of-lightning)
-- SKIP: Elite Robe of Muspell | robe (elite-robe-of-muspell)
-- SKIP: Elite Robe of Neptune | robe (elite-robe-of-neptune)
-- SKIP: Elite Robe of Pluto | robe (elite-robe-of-pluto)
-- SKIP: Elite Robe of Salamander | robe (elite-robe-of-salamander)
-- SKIP: Elite Robe of Storm | robe (elite-robe-of-storm)
-- SKIP: Elite Robe of Sylphide | robe (elite-robe-of-sylphide)
-- SKIP: Elite Robe of Uranus | robe (elite-robe-of-uranus)
-- SKIP: Elite Robe of Wind | robe (elite-robe-of-wind)
-- SKIP: Elite Robe of Yeti | robe (elite-robe-of-yeti)
-- SKIP: Elite Ruidestencia | robe (elite-ruidestencia)
UPDATE items SET name_th = 'อีลิท Tempest โรบ' WHERE slug = 'elite-tempest-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'อีวิล โรบ' WHERE slug = 'evil-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง โรบ' WHERE slug = 'experimental-robe' AND name_th IS NULL;
-- SKIP: Frontier Croma(Robe) | robe (frontier-croma-robe)
-- SKIP: Greek Croma Robe | robe (greek-croma-robe)
-- SKIP: Greek Croma Robe (Event) | robe (greek-croma-robe-event)
-- SKIP: Hellfire Robe | robe (hellfire-robe)
-- SKIP: La Ventisca | robe (la-ventisca)
-- SKIP: Le Blanc Robe | robe (le-blanc-robe)
-- SKIP: Le Blanc of Cinderella Robe | robe (le-blanc-of-cinderella-robe)
-- SKIP: Le Blanc of Cinderella for Robe (60 days) | robe (le-blanc-of-cinderella-for-robe-60-days)
-- SKIP: Le Noir Robe | robe (le-noir-robe)
-- SKIP: Le Pouvoir Robe | robe (le-pouvoir-robe)
-- SKIP: Le Scarce Robe | robe (le-scarce-robe)
-- SKIP: Legacy - Royal Robe Armor | robe (legacy-royal-robe-armor)
UPDATE items SET name_th = 'ลีเจียน โรบ' WHERE slug = 'legion-robe' AND name_th IS NULL;
-- SKIP: Nero Croma Robe | robe (nero-croma-robe)
-- SKIP: Novice Robe | robe (novice-robe)
-- SKIP: Ogre Noir Robe | robe (ogre-noir-robe)
-- SKIP: Old Elite Le Noir Robe | robe (old-elite-le-noir-robe)
-- SKIP: Old Greek Croma Robe | robe (old-greek-croma-robe)
-- SKIP: Old Santo De Blanc Robe | robe (old-santo-de-blanc-robe)
-- SKIP: Old Strata Devil Robe | robe (old-strata-devil-robe)
-- SKIP: Pioneer Combat Robe | robe (pioneer-combat-robe)
-- SKIP: Pioneer Mystic Robe | robe (pioneer-mystic-robe)
-- SKIP: Pioneer Old Robe | robe (pioneer-old-robe)
-- SKIP: Pioneer Practice Robe | robe (pioneer-practice-robe)
-- SKIP: Pioneer Robe | robe (pioneer-robe)
-- SKIP: Pioneer Thick Robe | robe (pioneer-thick-robe)
-- SKIP: Red Serpent Robe | robe (red-serpent-robe)
-- SKIP: Robe | robe (robe)
UPDATE items SET name_th = 'โรบสัญญา (7 วัน)' WHERE slug = 'robe-of-contract-7-days' AND name_th IS NULL;
-- SKIP: Robe of Elementalist | robe (robe-of-elementalist)
-- SKIP: Robe of Expert | robe (robe-of-expert)
-- SKIP: Robe of Fire | robe (robe-of-fire)
-- SKIP: Robe of Ice | robe (robe-of-ice)
-- SKIP: Robe of Inferno | robe (robe-of-inferno)
-- SKIP: Robe of Lightning | robe (robe-of-lightning)
-- SKIP: Robe of Neptune | robe (robe-of-neptune)
-- SKIP: Robe of Pluto | robe (robe-of-pluto)
-- SKIP: Robe of Sea Demon | robe (robe-of-sea-demon)
-- SKIP: Robe of Sky Demon | robe (robe-of-sky-demon)
-- SKIP: Robe of Storm | robe (robe-of-storm)
-- SKIP: Robe of Superb Demon | robe (robe-of-superb-demon)
-- SKIP: Robe of Syberia | robe (robe-of-syberia)
-- SKIP: Robe of Sylph | robe (robe-of-sylph)
-- SKIP: Robe of Thunder | robe (robe-of-thunder)
-- SKIP: Robe of Uranus | robe (robe-of-uranus)
-- SKIP: Robe of Wind | robe (robe-of-wind)
-- SKIP: Robe of the Salamander | robe (robe-of-the-salamander)
-- SKIP: Robe of the Yeti | robe (robe-of-the-yeti)
-- SKIP: Rosa Matrimonio | robe (rosa-matrimonio)
-- SKIP: Rosa Matrimonio of Cinderella | robe (rosa-matrimonio-of-cinderella)
-- SKIP: Rosa Matrimonio of Cinderella (60 days) | robe (rosa-matrimonio-of-cinderella-60-days)
-- SKIP: Royal Robe | robe (royal-robe)
-- SKIP: Santo De Blanc Robe | robe (santo-de-blanc-robe)
-- SKIP: Santo De Blanc Robe (Event) | robe (santo-de-blanc-robe-event)
-- SKIP: Sea Demons Armure Diabolique - Robe | robe (sea-demons-armure-diabolique-robe)
-- SKIP: Sea Demons Armure Diabolique - Robe (Event) | robe (sea-demons-armure-diabolique-robe-event)
UPDATE items SET name_th = 'สตราต้า เดวิล โรบ' WHERE slug = 'strata-devil-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล โรบ (อีเวนต์)' WHERE slug = 'strata-devil-robe-event' AND name_th IS NULL;
-- SKIP: Supreme Dignite Robe | robe (supreme-dignite-robe)
-- SKIP: Tempest Robe | robe (tempest-robe)
-- SKIP: The Pure White Robe | robe (the-pure-white-robe)
-- SKIP: Torsche Dress | robe (torsche-dress)
UPDATE items SET name_th = 'วาเลรอน โรบ' WHERE slug = 'valeron-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา โรบ' WHERE slug = 'vespanola-pioneer-support-robe' AND name_th IS NULL;
-- SKIP: [EVENT] Royal Robe | robe (event-royal-robe)
-- SKIP: [Runestone] Ara | runestone (runestone-ara)
-- SKIP: [Runestone] Arons | runestone (runestone-arons)
-- SKIP: [Runestone] Atra | runestone (runestone-atra)
-- SKIP: [Runestone] Attle | runestone (runestone-attle)
-- SKIP: [Runestone] Audi | runestone (runestone-audi)
-- SKIP: [Runestone] Ault | runestone (runestone-ault)
-- SKIP: [Runestone] Be | runestone (runestone-be)
-- SKIP: [Runestone] Cadran | runestone (runestone-cadran)
-- SKIP: [Runestone] Cert | runestone (runestone-cert)
-- SKIP: [Runestone] Dal | runestone (runestone-dal)
-- SKIP: [Runestone] Deaton | runestone (runestone-deaton)
-- SKIP: [Runestone] Diost | runestone (runestone-diost)
-- SKIP: [Runestone] Disain | runestone (runestone-disain)
-- SKIP: [Runestone] E-core | runestone (runestone-e-core)
-- SKIP: [Runestone] Entara | runestone (runestone-entara)
-- SKIP: [Runestone] Hetu | runestone (runestone-hetu)
-- SKIP: [Runestone] Hita | runestone (runestone-hita)
-- SKIP: [Runestone] Hitar | runestone (runestone-hitar)
-- SKIP: [Runestone] Ihorn | runestone (runestone-ihorn)
-- SKIP: [Runestone] Iol | runestone (runestone-iol)
-- SKIP: [Runestone] Ios | runestone (runestone-ios)
-- SKIP: [Runestone] Jod | runestone (runestone-jod)
-- SKIP: [Runestone] Kaolt | runestone (runestone-kaolt)
-- SKIP: [Runestone] Lantal | runestone (runestone-lantal)
-- SKIP: [Runestone] Let | runestone (runestone-let)
-- SKIP: [Runestone] Nias | runestone (runestone-nias)
-- SKIP: [Runestone] Odes | runestone (runestone-odes)
-- SKIP: [Runestone] Oller | runestone (runestone-oller)
-- SKIP: [Runestone] Ollet | runestone (runestone-ollet)
-- SKIP: [Runestone] Oss | runestone (runestone-oss)
-- SKIP: [Runestone] Othe | runestone (runestone-othe)
-- SKIP: [Runestone] Rade | runestone (runestone-rade)
-- SKIP: [Runestone] Rate | runestone (runestone-rate)
-- SKIP: [Runestone] Rita | runestone (runestone-rita)
-- SKIP: [Runestone] Ron | runestone (runestone-ron)
-- SKIP: [Runestone] Runes | runestone (runestone-runes)
-- SKIP: [Runestone] Salter | runestone (runestone-salter)
-- SKIP: [Runestone] Saor | runestone (runestone-saor)
-- SKIP: [Runestone] Sera | runestone (runestone-sera)
-- SKIP: [Runestone] Shiorn | runestone (runestone-shiorn)
-- SKIP: [Runestone] Shiroa | runestone (runestone-shiroa)
-- SKIP: [Runestone] Siatra | runestone (runestone-siatra)
-- SKIP: [Runestone] Ssior | runestone (runestone-ssior)
-- SKIP: [Runestone] Tana | runestone (runestone-tana)
-- SKIP: [Runestone] Tara | runestone (runestone-tara)
-- SKIP: [Runestone] Tiziana | runestone (runestone-tiziana)
-- SKIP: [Runestone] Trocar | runestone (runestone-trocar)
-- SKIP: [Runestone] Tudes | runestone (runestone-tudes)
-- SKIP: [Runestone] Virtue | runestone (runestone-virtue)
-- SKIP: [Runestone] Zior | runestone (runestone-zior)
-- SKIP: +10 Divinos Steel Leather Boots(1 day) | shoes (10-divinos-steel-leather-boots-1-day)
-- SKIP: +10 Quinnitulas Bloody Boots(1 day) | shoes (10-quinnitulas-bloody-boots-1-day)
-- SKIP: +10 Stars Pioneers Boots(1 day) | shoes (10-stars-pioneers-boots-1-day)
UPDATE items SET name_th = 'อะบิส อาร์ม่า รองเท้าบูท' WHERE slug = 'abyss-arma-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า รองเท้าบูท (อีเวนต์)' WHERE slug = 'abyss-arma-boots-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย รองเท้าบูท' WHERE slug = 'armonia-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย รองเท้าบูท (อีเวนต์)' WHERE slug = 'armonia-boots-event' AND name_th IS NULL;
UPDATE items SET name_th = 'บริสเทีย รองเท้าบูท' WHERE slug = 'bristia-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'บริสเทีย รองเท้าบูท (อีเวนต์)' WHERE slug = 'bristia-boots-event' AND name_th IS NULL;
-- SKIP: Desapio Boots | shoes (desapio-boots)
UPDATE items SET name_th = 'เดอุส มาชิน่า รองเท้าบูท' WHERE slug = 'deus-machina-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า รองเท้าบูท (อีเวนต์)' WHERE slug = 'deus-machina-boots-event' AND name_th IS NULL;
-- SKIP: Distorted Boots of the Corrupted Knight | shoes (distorted-boots-of-the-corrupted-knight)
UPDATE items SET name_th = 'ดิไวน์ รองเท้าบูท' WHERE slug = 'divine-boots' AND name_th IS NULL;
-- SKIP: Divinos Steel Leather Boots | shoes (divinos-steel-leather-boots)
-- SKIP: Divinos Steel Leather Boots (Illusion) | shoes (divinos-steel-leather-boots-illusion)
UPDATE items SET name_th = 'อีวิล รองเท้าบูท' WHERE slug = 'evil-boots' AND name_th IS NULL;
-- SKIP: Giltines Demonic Boots | shoes (giltines-demonic-boots)
-- SKIP: Laimas Holy Boots | shoes (laimas-holy-boots)
-- SKIP: Magic Shoes | shoes (magic-shoes)
-- SKIP: Magic Shoes (Event) | shoes (magic-shoes-event)
-- SKIP: Muertuos boots | shoes (muertuos-boots)
-- SKIP: Mystic Shoes | shoes (mystic-shoes)
-- SKIP: Pioneer Shoes | shoes (pioneer-shoes)
-- SKIP: Queenitulas Bloody Boots (Illusion) | shoes (queenitulas-bloody-boots-illusion)
-- SKIP: Quinnitulas Bloody Boots | shoes (quinnitulas-bloody-boots)
-- SKIP: Quiritatio Boots of Faith | shoes (quiritatio-boots-of-faith)
-- SKIP: Shoes | shoes (shoes)
-- SKIP: Shoes of Artisan | shoes (shoes-of-artisan)
-- SKIP: Stars Pioneers Boots | shoes (stars-pioneers-boots)
-- SKIP: Stars Pioneers Boots (Event) | shoes (stars-pioneers-boots-event)
UPDATE items SET name_th = 'สตราต้า เดวิล รองเท้าบูท' WHERE slug = 'strata-devil-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล รองเท้าบูท (อีเวนต์)' WHERE slug = 'strata-devil-boots-event' AND name_th IS NULL;
-- SKIP: Swift Boots of General Wind | shoes (swift-boots-of-general-wind)
UPDATE items SET name_th = 'วาเลรอน รองเท้าบูท' WHERE slug = 'valeron-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน รองเท้าบูท (อีเวนต์)' WHERE slug = 'valeron-boots-event' AND name_th IS NULL;
-- SKIP: Vigilar Tribes Boots | shoes (vigilar-tribes-boots)
-- SKIP: Vigilar Tribes Boots (Event) | shoes (vigilar-tribes-boots-event)
-- SKIP: Violets Shabbier Boots | shoes (violets-shabbier-boots)
-- SKIP: Violets Shabby Boots | shoes (violets-shabby-boots)
-- SKIP: Zodiac Boots | shoes (zodiac-boots)
-- SKIP: Zodiac Boots (Event) | shoes (zodiac-boots-event)
-- SKIP: [Dreaming] Divino Boots | shoes (dreaming-divino-boots)
-- SKIP: [Dreaming] Quinnitulas Boots | shoes (dreaming-quinnitulas-boots)
-- SKIP: [EVENT] Giltines Demonic Boots | shoes (event-giltines-demonic-boots)
-- SKIP: [EVENT] Laimas Holy Boots | shoes (event-laimas-holy-boots)
-- SKIP: [Lucid] Divino Boots | shoes (lucid-divino-boots)
-- SKIP: [Lucid] Quinnitulas Boots | shoes (lucid-quinnitulas-boots)
-- SKIP: [Reverie] Divino Boots | shoes (reverie-divino-boots)
-- SKIP: [Reverie] Quinnitulas Boots | shoes (reverie-quinnitulas-boots)