-- Migration 054: Thai names batch 1/10
-- Generated: 2026-03-16T03:42:16.053Z

UPDATE items SET name_th = 'อาร์มชิลด์Bristia' WHERE slug = 'bristia-arm-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์มชิลด์Elite Experimental' WHERE slug = 'elite-experimental-armshield' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์มชิลด์Experimental' WHERE slug = 'experimental-arm-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'ครบรอบราชา 2015' WHERE slug = '2015-king-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกพลังลึกลับ' WHERE slug = 'a-hat-with-unknown-power' AND name_th IS NULL;
UPDATE items SET name_th = 'ความคล่องแคล่วกริฟฟอน' WHERE slug = 'agility-of-griffon' AND name_th IS NULL;
UPDATE items SET name_th = 'ขวดนักเล่นแร่แปรธาตุ' WHERE slug = 'alchemists-bottle' AND name_th IS NULL;
UPDATE items SET name_th = 'คีมนักเล่นแร่แปรธาตุ' WHERE slug = 'alchemists-pliers' AND name_th IS NULL;
UPDATE items SET name_th = 'เครื่องรางเจ้าชาย' WHERE slug = 'amulet-of-prince' AND name_th IS NULL;
UPDATE items SET name_th = 'ตาArcard Eagle' WHERE slug = 'arcard-eagle-eye' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Arcard' WHERE slug = 'arcard-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'เจาะArcard' WHERE slug = 'arcard-piercing' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArcard' WHERE slug = 'arcard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'เจาะArcard Rose' WHERE slug = 'arcard-rose-piercing' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนอาร์คบิชอป' WHERE slug = 'archbishops-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'วัตถุศักดิ์สิทธิ์อาร์โมเนีย' WHERE slug = 'armonia-halidom' AND name_th IS NULL;
UPDATE items SET name_th = 'เจตจำนงอาร์โมเนีย' WHERE slug = 'armonias-will' AND name_th IS NULL;
UPDATE items SET name_th = 'การโจมตีอุเรอุส' WHERE slug = 'assault-of-uraeus' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้กางเขนAus' WHERE slug = 'aus-cross' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ออโต้ บารอน' WHERE slug = 'auto-barons-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'ค้อนซ่อมเสริม' WHERE slug = 'auxiliary-hammer-for-repairing' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกเด็ก' WHERE slug = 'baby-cap' AND name_th IS NULL;
UPDATE items SET name_th = 'ถังเบียร์' WHERE slug = 'barrels-keg' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนังหมี' WHERE slug = 'bearskin-protector' AND name_th IS NULL;
UPDATE items SET name_th = 'ผ้าคลุมBlack' WHERE slug = 'black-cape' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Black Clover' WHERE slug = 'black-clover-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'ตาBlack Eagle' WHERE slug = 'black-eagle-eye' AND name_th IS NULL;
UPDATE items SET name_th = 'กุหลาบดำ' WHERE slug = 'black-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlack Rose' WHERE slug = 'black-rose-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'ผ้าปิดตา' WHERE slug = 'blindford' AND name_th IS NULL;
UPDATE items SET name_th = 'ตาBlood Eagle' WHERE slug = 'blood-eagle-eye' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Blood Rose' WHERE slug = 'blood-rose-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlood Rose' WHERE slug = 'blood-rose-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'ผ้าพันแผลBloody' WHERE slug = 'bloody-bandage' AND name_th IS NULL;
UPDATE items SET name_th = 'ริบบิ้นBloody Hair' WHERE slug = 'bloody-hair-ribbon' AND name_th IS NULL;
UPDATE items SET name_th = 'กุหลาบเลือด' WHERE slug = 'bloody-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'น้ำมันทาตัว' WHERE slug = 'body-oil' AND name_th IS NULL;
UPDATE items SET name_th = 'ร่างนักปราชญ์ (1 วัน)' WHERE slug = 'body-of-wiseman-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ร่างนักปราชญ์ (10 วัน)' WHERE slug = 'body-of-wiseman-10-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ร่างนักปราชญ์ (15 วัน)' WHERE slug = 'body-of-wiseman-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ร่างนักปราชญ์ (30 วัน)' WHERE slug = 'body-of-wiseman-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ร่างนักปราชญ์ (5 วัน)' WHERE slug = 'body-of-wiseman-5-days' AND name_th IS NULL;
UPDATE items SET name_th = 'สลักช่างซ่อม' WHERE slug = 'bolt-of-repairman' AND name_th IS NULL;
UPDATE items SET name_th = 'จดหมายแบรนดีน' WHERE slug = 'brandines-letter' AND name_th IS NULL;
UPDATE items SET name_th = 'บริซิงกาเม็น' WHERE slug = 'brisingamen' AND name_th IS NULL;
UPDATE items SET name_th = 'การตัดสินใจบริสเทีย' WHERE slug = 'bristias-decision' AND name_th IS NULL;
UPDATE items SET name_th = 'โนริแกฮันบกแตก' WHERE slug = 'broken-hanbok-norigae' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดแห่งความมืด' WHERE slug = 'brooch-of-darkness' AND name_th IS NULL;
UPDATE items SET name_th = 'ความโหดร้ายเวอร์โก ผู้ถูกสาป' WHERE slug = 'brutality-of-vergo-the-cursed' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดผีเสื้อ' WHERE slug = 'butterfly-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'เปลือกลูกอม' WHERE slug = 'candy-shell' AND name_th IS NULL;
UPDATE items SET name_th = 'ผ้าคลุมครอบครัว' WHERE slug = 'cape-of-the-family' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอCarlas' WHERE slug = 'carlas-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สมุดม้วนปราสาท' WHERE slug = 'castle-roll-book' AND name_th IS NULL;
UPDATE items SET name_th = 'แผนที่ดวงดาว' WHERE slug = 'celestial-map' AND name_th IS NULL;
UPDATE items SET name_th = 'โซ่วิญญาณพยาบาท' WHERE slug = 'chain-of-vindictive-spirit' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญบิ่น' WHERE slug = 'chipped-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อกโกแลตแห่งความทรงจำ' WHERE slug = 'chocolate-of-reminiscence' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Clover' WHERE slug = 'clover-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'ออราไซต์เย็น' WHERE slug = 'cold-auracite' AND name_th IS NULL;
UPDATE items SET name_th = 'เนคไทหลากสี' WHERE slug = 'colorful-necktie' AND name_th IS NULL;
UPDATE items SET name_th = 'สัญญากับเกเฮนน่า' WHERE slug = 'contract-with-gehenna' AND name_th IS NULL;
UPDATE items SET name_th = 'อุปกรณ์ทำอาหาร' WHERE slug = 'cooking-equipment' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์สัตว์ประหลาด' WHERE slug = 'creature-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Crescent' WHERE slug = 'crescent-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'ตราเวอร์เนียร์' WHERE slug = 'crest-of-vernier' AND name_th IS NULL;
UPDATE items SET name_th = 'ความเย่อหยิ่งออร์เดนดิบ' WHERE slug = 'crude-ordens-arrogance' AND name_th IS NULL;
UPDATE items SET name_th = 'ความดุร้ายออร์เดนดิบ' WHERE slug = 'crude-ordens-fury' AND name_th IS NULL;
UPDATE items SET name_th = 'ความโลภออร์เดนดิบ' WHERE slug = 'crude-ordens-greed' AND name_th IS NULL;
UPDATE items SET name_th = 'ความอิจฉาออร์เดนดิบ' WHERE slug = 'crude-ordens-jealousy' AND name_th IS NULL;
UPDATE items SET name_th = 'ความเกียจคร้านออร์เดนดิบ' WHERE slug = 'crude-ordens-sloth' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูกแก้วแห่งความตระการตา' WHERE slug = 'crystal-ball-of-dazzlement' AND name_th IS NULL;
UPDATE items SET name_th = 'คัสโทเดีย' WHERE slug = 'custodia' AND name_th IS NULL;
UPDATE items SET name_th = 'กริชนักฆ่า' WHERE slug = 'dagger-of-the-killer' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากนักเต้น' WHERE slug = 'dancers-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดDark Blood Rose' WHERE slug = 'dark-blood-rose-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'เจาะDark Rose' WHERE slug = 'dark-rose-piercing' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์ปีศาจ' WHERE slug = 'demon-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'บันทึกอิดจ์' WHERE slug = 'diary-of-idge' AND name_th IS NULL;
UPDATE items SET name_th = 'บันทึกลอเรนโซ' WHERE slug = 'diary-of-lorenzo' AND name_th IS NULL;
UPDATE items SET name_th = 'หินมิติ' WHERE slug = 'dimension-stone' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิโอ เอลปิเดส' WHERE slug = 'dio-elpides' AND name_th IS NULL;
UPDATE items SET name_th = 'ผ้าโพกหัวคนตาย' WHERE slug = 'do-rag-of-the-dead' AND name_th IS NULL;
UPDATE items SET name_th = 'ดอม เปริญง' WHERE slug = 'dom-perignon' AND name_th IS NULL;
UPDATE items SET name_th = 'การรวมตัวมังกร' WHERE slug = 'dragon-coalescence' AND name_th IS NULL;
UPDATE items SET name_th = 'ตาEagle' WHERE slug = 'eagle-eye' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Eagle Eye' WHERE slug = 'eagle-eye-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEagles' WHERE slug = 'eagles-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Elite Clover' WHERE slug = 'elite-clover-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Elite Creature' WHERE slug = 'elite-creature-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Elite Demon' WHERE slug = 'elite-demon-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'ตาElite Eagle' WHERE slug = 'elite-eagle-eye' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหูElite Executioners' WHERE slug = 'elite-executioners-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElite Executioners' WHERE slug = 'elite-executioners-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Elite Golem' WHERE slug = 'elite-golem-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่Elite Iron (1 วัน)' WHERE slug = 'elite-iron-shield-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอElite Pioneer' WHERE slug = 'elite-pioneer-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElite Snipers' WHERE slug = 'elite-snipers-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดElite Trumans' WHERE slug = 'elite-trumans-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดElite Trumans (1 วัน)' WHERE slug = 'elite-trumans-brooch-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Elite Undead' WHERE slug = 'elite-undead-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหูExecutioners' WHERE slug = 'executioners-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExecutioners' WHERE slug = 'executioners-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Magic' WHERE slug = 'flame-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอFragment of Broken' WHERE slug = 'fragment-of-broken-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'เจาะFull Moon' WHERE slug = 'full-moon-piercing' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Golem' WHERE slug = 'golem-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดGuardians' WHERE slug = 'guardians-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'ริบบิ้นHair' WHERE slug = 'hair-ribbon' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่Iron' WHERE slug = 'iron-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดKirkeh' WHERE slug = 'kirkeh-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'เจาะLunar Eclipse' WHERE slug = 'lunar-eclipse-piercing' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดLunatic' WHERE slug = 'lunatic-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagic Freezing' WHERE slug = 'magic-freezing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagic Sudden Attack' WHERE slug = 'magic-sudden-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหูMallahs' WHERE slug = 'mallahs-earrings' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Memory' WHERE slug = 'memory-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMoonlight' WHERE slug = 'moonlight-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNecklace Made of' WHERE slug = 'necklace-made-of-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'เจาะOld Arcard' WHERE slug = 'old-arcard-piercing' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Old Clover' WHERE slug = 'old-clover-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Old Creature' WHERE slug = 'old-creature-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Old Demon' WHERE slug = 'old-demon-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'ตาOld Eagle' WHERE slug = 'old-eagle-eye' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหูOld Executioners' WHERE slug = 'old-executioners-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOld Executioners' WHERE slug = 'old-executioners-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Old Golem' WHERE slug = 'old-golem-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่Old Iron' WHERE slug = 'old-iron-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอOld Pioneer' WHERE slug = 'old-pioneer-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'เจาะOld Pioneer' WHERE slug = 'old-pioneer-piercing' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOld Snipers' WHERE slug = 'old-snipers-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดOld Trumans' WHERE slug = 'old-trumans-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Old Undead' WHERE slug = 'old-undead-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'สมุดบันทึกPicture' WHERE slug = 'picture-diary' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดPigeon' WHERE slug = 'pigeon-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอPioneer' WHERE slug = 'pioneer-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'เจาะPioneer' WHERE slug = 'pioneer-piercing' AND name_th IS NULL;
UPDATE items SET name_th = 'เครื่องรางPoets' WHERE slug = 'poets-amulet' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือRubber' WHERE slug = 'rubber-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัดSakimori' WHERE slug = 'sakimori-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'สมุดบันทึกSeal Research' WHERE slug = 'seal-research-diary' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้Snipers' WHERE slug = 'snipers-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้กางเขนThe Suspicious Sects' WHERE slug = 'the-suspicious-sects-cross' AND name_th IS NULL;
UPDATE items SET name_th = 'แผนที่Treasure' WHERE slug = 'treasure-map' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มกลัดTrumans' WHERE slug = 'trumans-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'ยันต์Undead' WHERE slug = 'undead-talisman' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูกแก้วVeronifs' WHERE slug = 'veronifs-crystal-ball' AND name_th IS NULL;
UPDATE items SET name_th = 'ริบบิ้นYellow' WHERE slug = 'yellow-ribbon' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีก3rd Anniversary' WHERE slug = '3rd-anniversary-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีก3rd Anniversary (1 วัน)' WHERE slug = '3rd-anniversary-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีก3rd Anniversary (30 วัน)' WHERE slug = '3rd-anniversary-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีก3rd Anniversary (7 วัน)' WHERE slug = '3rd-anniversary-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีก3rd Anniversary (90 วัน)' WHERE slug = '3rd-anniversary-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Angel' WHERE slug = 'a-broken-angel-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Angel (1 วัน)' WHERE slug = 'a-broken-angel-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Angel (30 วัน)' WHERE slug = 'a-broken-angel-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Angel (7 วัน)' WHERE slug = 'a-broken-angel-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Angel (90 วัน)' WHERE slug = 'a-broken-angel-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Lucifer' WHERE slug = 'a-broken-lucifer-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Lucifer (1 วัน)' WHERE slug = 'a-broken-lucifer-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Lucifer (30 วัน)' WHERE slug = 'a-broken-lucifer-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Lucifer (7 วัน)' WHERE slug = 'a-broken-lucifer-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกA Broken Lucifer (90 วัน)' WHERE slug = 'a-broken-lucifer-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกAngel' WHERE slug = 'angel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกAngel (15 วัน)' WHERE slug = 'angel-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกAngel (7 วัน)' WHERE slug = 'angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกAngel (อีเวนต์)' WHERE slug = 'angel-wings-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกArch Angel' WHERE slug = 'arch-angel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกArch Angel (7 วัน)' WHERE slug = 'arch-angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Angel' WHERE slug = 'black-angel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Angel (15 วัน)' WHERE slug = 'black-angel-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Angel (7 วัน)' WHERE slug = 'black-angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Fallen Angel' WHERE slug = 'black-fallen-angel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Rose' WHERE slug = 'black-rose-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Rose (1 วัน)' WHERE slug = 'black-rose-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Rose (15 วัน)' WHERE slug = 'black-rose-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Rose (3 วัน)' WHERE slug = 'black-rose-wing-3-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Rose (30 วัน)' WHERE slug = 'black-rose-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Rose (7 วัน)' WHERE slug = 'black-rose-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack Rose (90 วัน)' WHERE slug = 'black-rose-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack and White' WHERE slug = 'black-and-white-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack and White (1 วัน)' WHERE slug = 'black-and-white-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack and White (15 วัน)' WHERE slug = 'black-and-white-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack and White (30 วัน)' WHERE slug = 'black-and-white-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack and White (365 วัน)' WHERE slug = 'black-and-white-wing-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack and White (7 วัน)' WHERE slug = 'black-and-white-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlack and White (90 วัน)' WHERE slug = 'black-and-white-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlessed Angel' WHERE slug = 'blessed-angel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlessed Angel (7 วัน)' WHERE slug = 'blessed-angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlessed Black Angel (7 วัน)' WHERE slug = 'blessed-black-angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlessed Chrysalis (7 วัน)' WHERE slug = 'blessed-chrysalis-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าBlessed Ivory (7 วัน)' WHERE slug = 'blessed-ivory-bag-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าBlessed Leaping Croc (7 วัน)' WHERE slug = 'blessed-leaping-croc-bag-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlessed White Angel (7 วัน)' WHERE slug = 'blessed-white-angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Astaroth' WHERE slug = 'blue-astaroth-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Butterfly' WHERE slug = 'blue-butterfly-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Butterfly (1 วัน)' WHERE slug = 'blue-butterfly-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Butterfly (30 วัน)' WHERE slug = 'blue-butterfly-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Butterfly (7 วัน)' WHERE slug = 'blue-butterfly-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Butterfly (90 วัน)' WHERE slug = 'blue-butterfly-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Chrysalis' WHERE slug = 'blue-chrysalis-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Rose' WHERE slug = 'blue-rose-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Rose (1 วัน)' WHERE slug = 'blue-rose-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Rose (15 วัน)' WHERE slug = 'blue-rose-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Rose (30 วัน)' WHERE slug = 'blue-rose-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Rose (7 วัน)' WHERE slug = 'blue-rose-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Rose (90 วัน)' WHERE slug = 'blue-rose-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Wish' WHERE slug = 'blue-wish-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Wish (1 วัน)' WHERE slug = 'blue-wish-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Wish (15 วัน)' WHERE slug = 'blue-wish-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Wish (30 วัน)' WHERE slug = 'blue-wish-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Wish (60 วัน)' WHERE slug = 'blue-wish-wing-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Wish (7 วัน)' WHERE slug = 'blue-wish-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBlue Wish (90 วัน)' WHERE slug = 'blue-wish-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกBule Wish (365 วัน)' WHERE slug = 'bule-wish-wing-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCastor' WHERE slug = 'castor-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCastor (1 วัน)' WHERE slug = 'castor-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCastor (30 วัน)' WHERE slug = 'castor-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCastor (7 วัน)' WHERE slug = 'castor-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCastor (90 วัน)' WHERE slug = 'castor-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกChrysalis' WHERE slug = 'chrysalis-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกChrysalis (15 วัน)' WHERE slug = 'chrysalis-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกChrysalis (7 วัน)' WHERE slug = 'chrysalis-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCrystal' WHERE slug = 'crystal-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCrystal (1 วัน)' WHERE slug = 'crystal-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCrystal (15 วัน)' WHERE slug = 'crystal-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCrystal (30 วัน)' WHERE slug = 'crystal-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกCrystal (7 วัน)' WHERE slug = 'crystal-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกDevil (5 วัน)' WHERE slug = 'devil-wing-5-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกDevil (1 วัน)' WHERE slug = 'devil-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกDevil (15 วัน)' WHERE slug = 'devil-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกDevil (30 วัน)' WHERE slug = 'devil-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกDevil (365 วัน)' WHERE slug = 'devil-wings-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกDevil (7 วัน)' WHERE slug = 'devil-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกDevil (90 วัน)' WHERE slug = 'devil-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEnhanced Angel (7 วัน)' WHERE slug = 'enhanced-angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEnhanced Black Angel (7 วัน)' WHERE slug = 'enhanced-black-angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEnhanced Crystal (15 วัน)' WHERE slug = 'enhanced-crystal-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEnhanced Crystal (30 วัน)' WHERE slug = 'enhanced-crystal-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEnhanced Crystal (90 วัน)' WHERE slug = 'enhanced-crystal-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEvent Red Astaroth (15 วัน)' WHERE slug = 'event-red-astaroth-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEvent Red Astaroth (30 วัน)' WHERE slug = 'event-red-astaroth-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEvent Red Astaroth (365 วัน)' WHERE slug = 'event-red-astaroth-wing-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEvent Red Astaroth (60 วัน)' WHERE slug = 'event-red-astaroth-wing-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEvent Red Astaroth (90 วัน)' WHERE slug = 'event-red-astaroth-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกEvent Snow Angel (7 วัน)' WHERE slug = 'event-snow-angel-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFairy (7 วัน)' WHERE slug = 'fairy-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFairy' WHERE slug = 'fairy-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFairy (1 วัน)' WHERE slug = 'fairy-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFairy (15 วัน)' WHERE slug = 'fairy-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFairy (30 วัน)' WHERE slug = 'fairy-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFairy (365 วัน)' WHERE slug = 'fairy-wings-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFairy (7 วัน)' WHERE slug = 'fairy-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFairy (90 วัน)' WHERE slug = 'fairy-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกFolded' WHERE slug = 'folded-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Butterfly' WHERE slug = 'gold-butterfly-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Butterfly (1 วัน)' WHERE slug = 'gold-butterfly-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Butterfly (30 วัน)' WHERE slug = 'gold-butterfly-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Butterfly (60 วัน)' WHERE slug = 'gold-butterfly-wing-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Butterfly (7 วัน)' WHERE slug = 'gold-butterfly-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Butterfly (90 วัน)' WHERE slug = 'gold-butterfly-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Piece (15 วัน)' WHERE slug = 'gold-piece-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Piece (30 วัน)' WHERE slug = 'gold-piece-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Piece (7 วัน)' WHERE slug = 'gold-piece-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Rose' WHERE slug = 'gold-rose-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Rose (1 วัน)' WHERE slug = 'gold-rose-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Rose (15 วัน)' WHERE slug = 'gold-rose-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Rose (3 วัน)' WHERE slug = 'gold-rose-wing-3-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Rose (30 วัน)' WHERE slug = 'gold-rose-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Rose (7 วัน)' WHERE slug = 'gold-rose-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGold Rose (90 วัน)' WHERE slug = 'gold-rose-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden Archangel' WHERE slug = 'golden-archangel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden Phoenix (1 วัน)' WHERE slug = 'golden-phoenix-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden Phoenix (15 วัน)' WHERE slug = 'golden-phoenix-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden Phoenix (30 วัน)' WHERE slug = 'golden-phoenix-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden Phoenix (365 วัน)' WHERE slug = 'golden-phoenix-wing-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden Phoenix (7 วัน)' WHERE slug = 'golden-phoenix-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden Phoenix (90 วัน)' WHERE slug = 'golden-phoenix-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden Phoenix' WHERE slug = 'golden-phoenix-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกGolden' WHERE slug = 'golden-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกHanbiton 9th Anniversary (15 วัน)' WHERE slug = 'hanbiton-9th-anniversary-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าIvory' WHERE slug = 'ivory-bag' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าIvory (15 วัน)' WHERE slug = 'ivory-bag-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าIvory (7 วัน)' WHERE slug = 'ivory-bag-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าJack O Lantern' WHERE slug = 'jack-o-lantern-bag' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าJack O Lantern (1 วัน)' WHERE slug = 'jack-o-lantern-bag-1-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าJack O Lantern (30 วัน)' WHERE slug = 'jack-o-lantern-bag-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าJack O Lantern (7 วัน)' WHERE slug = 'jack-o-lantern-bag-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าJack O Lantern (90 วัน)' WHERE slug = 'jack-o-lantern-bag-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าLeaping Croc' WHERE slug = 'leaping-croc-bag' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าLeaping Croc (15 วัน)' WHERE slug = 'leaping-croc-bag-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าLeaping Croc (7 วัน)' WHERE slug = 'leaping-croc-bag-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P' WHERE slug = 'mw-917p-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P (1 วัน)' WHERE slug = 'mw-917p-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P (15 วัน)' WHERE slug = 'mw-917p-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P (3 วัน)' WHERE slug = 'mw-917p-wing-3-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P (30 วัน)' WHERE slug = 'mw-917p-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P (365 วัน)' WHERE slug = 'mw-917p-wing-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P (60 วัน)' WHERE slug = 'mw-917p-wing-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P (7 วัน)' WHERE slug = 'mw-917p-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMW-917P (90 วัน)' WHERE slug = 'mw-917p-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าMilitary' WHERE slug = 'military-bag' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกMovement' WHERE slug = 'movement-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกOpera' WHERE slug = 'opera-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกOrphesia Celebration' WHERE slug = 'orphesia-celebration-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกOrphesia Celebration (1 วัน)' WHERE slug = 'orphesia-celebration-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกOrphesia Celebration (30 วัน)' WHERE slug = 'orphesia-celebration-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกOrphesia Celebration (7 วัน)' WHERE slug = 'orphesia-celebration-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกOrphesia Celebration (90 วัน)' WHERE slug = 'orphesia-celebration-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPhoenix (30 วัน)' WHERE slug = 'phoenix-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPhoenix' WHERE slug = 'phoenix-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPhoenix (1 วัน)' WHERE slug = 'phoenix-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPhoenix (15 วัน)' WHERE slug = 'phoenix-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPhoenix (365 วัน)' WHERE slug = 'phoenix-wings-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPhoenix (7 วัน)' WHERE slug = 'phoenix-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPhoenix (90 วัน)' WHERE slug = 'phoenix-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPioneer (15 วัน)' WHERE slug = 'pioneer-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPioneer (30 วัน)' WHERE slug = 'pioneer-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPioneer (7 วัน)' WHERE slug = 'pioneer-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPioneer' WHERE slug = 'pioneer-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPurple Bat' WHERE slug = 'purple-bat-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPurple Bat (1 วัน)' WHERE slug = 'purple-bat-wing-1-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPurple Bat (30 วัน)' WHERE slug = 'purple-bat-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPurple Bat (7 วัน)' WHERE slug = 'purple-bat-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกPurple Bat (90 วัน)' WHERE slug = 'purple-bat-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Astaroth' WHERE slug = 'red-astaroth-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Crystal' WHERE slug = 'red-crystal-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Devil' WHERE slug = 'red-devil-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Devil (30 วัน)' WHERE slug = 'red-devil-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Nebiros (1 วัน)' WHERE slug = 'red-nebiros-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Nebiros (15 วัน)' WHERE slug = 'red-nebiros-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Nebiros (3 วัน)' WHERE slug = 'red-nebiros-wing-3-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Nebiros (30 วัน)' WHERE slug = 'red-nebiros-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Nebiros (365 วัน)' WHERE slug = 'red-nebiros-wing-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Nebiros (5 วัน)' WHERE slug = 'red-nebiros-wing-5-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Nebiros (60 วัน)' WHERE slug = 'red-nebiros-wing-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Nebiros (7 วัน)' WHERE slug = 'red-nebiros-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Wish' WHERE slug = 'red-wish-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Wish (1 วัน)' WHERE slug = 'red-wish-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Wish (15 วัน)' WHERE slug = 'red-wish-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Wish (30 วัน)' WHERE slug = 'red-wish-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Wish (365 วัน)' WHERE slug = 'red-wish-wing-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Wish (60 วัน)' WHERE slug = 'red-wish-wing-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Wish (7 วัน)' WHERE slug = 'red-wish-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRed Wish (90 วัน)' WHERE slug = 'red-wish-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRose (1 วัน)' WHERE slug = 'rose-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRose (15 วัน)' WHERE slug = 'rose-wing-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRose (30 วัน)' WHERE slug = 'rose-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRose (365 วัน)' WHERE slug = 'rose-wing-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRose (7 วัน)' WHERE slug = 'rose-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRose (90 วัน)' WHERE slug = 'rose-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSerapeam (30 วัน)' WHERE slug = 'serapeam-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSilver Phoenix' WHERE slug = 'silver-phoenix-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSilver' WHERE slug = 'silver-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSivery Phoenix (7 วัน)' WHERE slug = 'sivery-phoenix-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSnow Angel' WHERE slug = 'snow-angel-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSnow Angel (1 วัน)' WHERE slug = 'snow-angel-wing-1-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSnow Angel (30 วัน)' WHERE slug = 'snow-angel-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSnow Angel (7 วัน)' WHERE slug = 'snow-angel-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSnow Angel (90 วัน)' WHERE slug = 'snow-angel-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpeedy Black Angel' WHERE slug = 'speedy-black-angel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpeedy White Angel' WHERE slug = 'speedy-white-angel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Fairy' WHERE slug = 'spring-fairy-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Fairy (1 วัน)' WHERE slug = 'spring-fairy-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Fairy (30 วัน)' WHERE slug = 'spring-fairy-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Fairy (7 วัน)' WHERE slug = 'spring-fairy-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Fairy (90 วัน)' WHERE slug = 'spring-fairy-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Wedding Rose' WHERE slug = 'spring-wedding-rose-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Wedding Rose (1 วัน)' WHERE slug = 'spring-wedding-rose-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Wedding Rose (30 วัน)' WHERE slug = 'spring-wedding-rose-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Wedding Rose (7 วัน)' WHERE slug = 'spring-wedding-rose-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSpring Wedding Rose (90 วัน)' WHERE slug = 'spring-wedding-rose-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSylph' WHERE slug = 'sylph-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSylph (1 วัน)' WHERE slug = 'sylph-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSylph (15 วัน)' WHERE slug = 'sylph-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSylph (30 วัน)' WHERE slug = 'sylph-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSylph (365 วัน)' WHERE slug = 'sylph-wings-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSylph (7 วัน)' WHERE slug = 'sylph-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกSylph (90 วัน)' WHERE slug = 'sylph-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกVergo the Cursed' WHERE slug = 'vergo-the-cursed-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกViolet Chrysalis' WHERE slug = 'violet-chrysalis-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกWCC Celebration' WHERE slug = 'wcc-celebration-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'กระเป๋าWaist' WHERE slug = 'waist-bag' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกWhite Angel' WHERE slug = 'white-angel-wings' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกWhite Angel (15 วัน)' WHERE slug = 'white-angel-wings-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกWhite Angel (7 วัน)' WHERE slug = 'white-angel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกZig (1 วัน)' WHERE slug = 'zig-wing-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกZiz' WHERE slug = 'ziz-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกZiz (30 วัน)' WHERE slug = 'ziz-wing-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกZiz (7 วัน)' WHERE slug = 'ziz-wing-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกZiz (90 วัน)' WHERE slug = 'ziz-wing-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด2 Minutes to Midnight' WHERE slug = '2-minutes-to-midnight-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด2 Minutes to Midnight (30 วัน)' WHERE slug = '2-minutes-to-midnight-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด2 Minutes to Midnight (อีเวนต์)' WHERE slug = '2-minutes-to-midnight-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAbyss Mirror' WHERE slug = 'abyss-mirror-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAbyss Mirror (1 วัน)' WHERE slug = 'abyss-mirror-costume-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAdelina Basic' WHERE slug = 'adelina-basic-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAdelina Basic (อีเวนต์)' WHERE slug = 'adelina-basic-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAdmiral Private' WHERE slug = 'admiral-private-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAgiolegion' WHERE slug = 'agiolegion-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAisha Halloween' WHERE slug = 'aisha-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAisha Halloween (อีเวนต์)' WHERE slug = 'aisha-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAither Summer' WHERE slug = 'aither-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAither Summer (อีเวนต์)' WHERE slug = 'aither-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAlbaes' WHERE slug = 'albaes-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAlbaes (30 วัน)' WHERE slug = 'albaes-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAlegrias' WHERE slug = 'alegrias-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAlegrias (30 วัน)' WHERE slug = 'alegrias-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAli Baba' WHERE slug = 'ali-baba-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAli Baba (30 วัน)' WHERE slug = 'ali-baba-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAli Baba (อีเวนต์)' WHERE slug = 'ali-baba-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAmismaratau' WHERE slug = 'amismaratau-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAmy Halloween' WHERE slug = 'amy-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAnemone' WHERE slug = 'anemone-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAnemone (อีเวนต์)' WHERE slug = 'anemone-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAngelica' WHERE slug = 'angelica-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAnis School Look (อีเวนต์)' WHERE slug = 'anis-school-look-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAnis Summer' WHERE slug = 'anis-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAnis Summer (อีเวนต์)' WHERE slug = 'anis-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดArcanero Plate' WHERE slug = 'arcanero-plate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดArchbishop Summer' WHERE slug = 'archbishop-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดArchbishop Summer (อีเวนต์)' WHERE slug = 'archbishop-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดArjerear' WHERE slug = 'arjerear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAssassin' WHERE slug = 'assassin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAsuplegion' WHERE slug = 'asuplegion-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAuch Infantry' WHERE slug = 'auch-infantry-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAuch Infantry (30 วัน)' WHERE slug = 'auch-infantry-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAuro Ohriza' WHERE slug = 'auro-ohriza-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAvalanche Femme' WHERE slug = 'avalanche-femme-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAvalanche Femme (อีเวนต์)' WHERE slug = 'avalanche-femme-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAvalanche Homme' WHERE slug = 'avalanche-homme-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดAvalanche Homme (อีเวนต์)' WHERE slug = 'avalanche-homme-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBaby Doll' WHERE slug = 'baby-doll-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBach' WHERE slug = 'bach-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBach (30 วัน)' WHERE slug = 'bach-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBattle Cook' WHERE slug = 'battle-cook-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBattle Cook (30 วัน)' WHERE slug = 'battle-cook-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBattle Smith' WHERE slug = 'battle-smith-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBattle Smith (30 วัน)' WHERE slug = 'battle-smith-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBattlefield Hero' WHERE slug = 'battlefield-hero-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBattlefield Hero (อีเวนต์)' WHERE slug = 'battlefield-hero-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBeatrice Summer' WHERE slug = 'beatrice-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBeatrice Summer (อีเวนต์)' WHERE slug = 'beatrice-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBedlah' WHERE slug = 'bedlah-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBedlah (อีเวนต์)' WHERE slug = 'bedlah-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBelle De Jour' WHERE slug = 'belle-de-jour-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBelle De Jour (อีเวนต์)' WHERE slug = 'belle-de-jour-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBellydancer (30 วัน)' WHERE slug = 'bellydancer-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBermero Fantera' WHERE slug = 'bermero-fantera-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBianca Winter' WHERE slug = 'bianca-winter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBistre' WHERE slug = 'bistre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBistre (30 วัน)' WHERE slug = 'bistre-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Banshee' WHERE slug = 'black-banshee-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Banshee (อีเวนต์)' WHERE slug = 'black-banshee-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Buffalo' WHERE slug = 'black-buffalo-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Buffalo (อีเวนต์)' WHERE slug = 'black-buffalo-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Cobra' WHERE slug = 'black-cobra-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Cobra (อีเวนต์)' WHERE slug = 'black-cobra-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Elegance' WHERE slug = 'black-elegance-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Elegance (อีเวนต์)' WHERE slug = 'black-elegance-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Pearl' WHERE slug = 'black-pearl-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Rose' WHERE slug = 'black-rose-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Rose (30 วัน)' WHERE slug = 'black-rose-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Santa Barrel' WHERE slug = 'black-santa-barrel-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack Wisteria' WHERE slug = 'black-wisteria-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlack and White' WHERE slug = 'black-and-white-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlaue Spiel' WHERE slug = 'blaue-spiel-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBler Rasto' WHERE slug = 'bler-rasto-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlue Andante' WHERE slug = 'blue-andante-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlue Andante (อีเวนต์)' WHERE slug = 'blue-andante-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlue Flame/Student President Ludin Blue Summer' WHERE slug = 'blue-flame-student-president-ludin-blue-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlue Flame/Student President Ludin Pink Summer' WHERE slug = 'blue-flame-student-president-ludin-pink-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlue Innocence' WHERE slug = 'blue-innocence-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlue Innocence (อีเวนต์)' WHERE slug = 'blue-innocence-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlue Vivace' WHERE slug = 'blue-vivace-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlue Vivace (อีเวนต์)' WHERE slug = 'blue-vivace-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlueFlame/Student President Ludin Blue Summer (อีเวนต์)' WHERE slug = 'blueflame-student-president-ludin-blue-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBlueFlame/Student President Ludin Pink Summer (อีเวนต์)' WHERE slug = 'blueflame-student-president-ludin-pink-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBone Frame Armor' WHERE slug = 'bone-frame-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBreeze Vita' WHERE slug = 'breeze-vita-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBristian Colonel' WHERE slug = 'bristian-colonel-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBristian Natural' WHERE slug = 'bristian-natural-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBristian Noble' WHERE slug = 'bristian-noble-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBrown Andante' WHERE slug = 'brown-andante-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBrown Andante (อีเวนต์)' WHERE slug = 'brown-andante-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBryan/Divine Hammer Bryan Halloween' WHERE slug = 'bryan-divine-hammer-bryan-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดBryan/Divine Hammer Bryan Halloween (อีเวนต์)' WHERE slug = 'bryan-divine-hammer-bryan-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดButler Suit' WHERE slug = 'butler-suit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดByzantikoh (30 วัน)' WHERE slug = 'byzantikoh-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดByzantkohl' WHERE slug = 'byzantkohl-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCadet Amy Halloween' WHERE slug = 'cadet-amy-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCadet Romina Summer' WHERE slug = 'cadet-romina-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCadet Romina Summer (อีเวนต์)' WHERE slug = 'cadet-romina-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCalienalbino' WHERE slug = 'calienalbino-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCamaryllis' WHERE slug = 'camaryllis-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCamisa de Soldado Blanc' WHERE slug = 'camisa-de-soldado-blanc-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCamisa de Soldado' WHERE slug = 'camisa-de-soldado-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCamisa de Soldado (30 วัน)' WHERE slug = 'camisa-de-soldado-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCanna Summer' WHERE slug = 'canna-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCanna Summer (อีเวนต์)' WHERE slug = 'canna-summer-costume-event' AND name_th IS NULL;