-- Migration 055: Thai names batch 2/10
-- Generated: 2026-03-16T03:42:16.053Z

UPDATE items SET name_th = 'ชุดCannon Shooter Claire School Look (อีเวนต์)' WHERE slug = 'cannon-shooter-claire-school-look-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCano Marine Look' WHERE slug = 'cano-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCano Marine-Look (อีเวนต์)' WHERE slug = 'cano-marine-look-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCape Pattern (อีเวนต์)' WHERE slug = 'cape-pattern-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCapezzolo di Pericolo' WHERE slug = 'capezzolo-di-pericolo-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCapybara' WHERE slug = 'capybara-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCapybara (อีเวนต์)' WHERE slug = 'capybara-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCarumia' WHERE slug = 'carumia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCarunis' WHERE slug = 'carunis-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCassandra Summer' WHERE slug = 'cassandra-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCatherine Christmas' WHERE slug = 'catherine-christmas-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCatherine Christmas (อีเวนต์)' WHERE slug = 'catherine-christmas-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCattleya' WHERE slug = 'cattleya-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCecil School Look (อีเวนต์)' WHERE slug = 'cecil-school-look-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCenturion' WHERE slug = 'centurion-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCenturion (30 วัน)' WHERE slug = 'centurion-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCerasus Bariante' WHERE slug = 'cerasus-bariante-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCharlotte Summer' WHERE slug = 'charlotte-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCharlotte Summer (อีเวนต์)' WHERE slug = 'charlotte-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCherlyn Summer' WHERE slug = 'cherlyn-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCherlyn Summer (อีเวนต์)' WHERE slug = 'cherlyn-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCherry Blossom' WHERE slug = 'cherry-blossom-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดChloe Summer' WHERE slug = 'chloe-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดChristina Summer' WHERE slug = 'christina-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดChungha Halloween' WHERE slug = 'chungha-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดChungha Halloween (อีเวนต์)' WHERE slug = 'chungha-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCinderella Le Blanc' WHERE slug = 'cinderella-le-blanc-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCineraria' WHERE slug = 'cineraria-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCineraria (30 วัน)' WHERE slug = 'cineraria-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดClaire Bikini' WHERE slug = 'claire-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดClara Mago' WHERE slug = 'clara-mago-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดClarcana' WHERE slug = 'clarcana-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดClivia Sprite' WHERE slug = 'clivia-sprite-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCoat' WHERE slug = 'coat-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCockatrice' WHERE slug = 'cockatrice-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCockatrice (30 วัน)' WHERE slug = 'cockatrice-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCockatrice (อีเวนต์)' WHERE slug = 'cockatrice-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCode Name C Summer' WHERE slug = 'code-name-c-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCode Name L Bikini' WHERE slug = 'code-name-l-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCode Name L Bikini (อีเวนต์)' WHERE slug = 'code-name-l-bikini-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCode Name T Summer' WHERE slug = 'code-name-t-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCodename T Summer (อีเวนต์)' WHERE slug = 'codename-t-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCoimbra Trooper' WHERE slug = 'coimbra-trooper-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCoimbra Trooper (30 วัน)' WHERE slug = 'coimbra-trooper-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดConductor Rio Summer' WHERE slug = 'conductor-rio-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCorchicum' WHERE slug = 'corchicum-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCorsair Arjang' WHERE slug = 'corsair-arjang-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCorsair Rosso' WHERE slug = 'corsair-rosso-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCroc Leather' WHERE slug = 'croc-leather-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCronian Nephthes' WHERE slug = 'cronian-nephthes-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCronian Nephthes (อีเวนต์)' WHERE slug = 'cronian-nephthes-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCronian Thanatos' WHERE slug = 'cronian-thanatos-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCronian Thanatos (อีเวนต์)' WHERE slug = 'cronian-thanatos-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCrusader Coat' WHERE slug = 'crusader-coat-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCrusader Coat (30 วัน)' WHERE slug = 'crusader-coat-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCrusader Daria Summer' WHERE slug = 'crusader-daria-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดCrusader Daria Summer (อีเวนต์)' WHERE slug = 'crusader-daria-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDark Blue Sleeveless' WHERE slug = 'dark-blue-sleeveless-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDark Blue Sleeveless (อีเวนต์)' WHERE slug = 'dark-blue-sleeveless-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDe Lange Souriant' WHERE slug = 'de-lange-souriant-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDe Lapith (อีเวนต์)' WHERE slug = 'de-lapith-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDebauch' WHERE slug = 'debauch-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDebauch (30 วัน)' WHERE slug = 'debauch-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDeinclian' WHERE slug = 'deinclian-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDeinclian (อีเวนต์)' WHERE slug = 'deinclian-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDelfina Summer' WHERE slug = 'delfina-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDelfina Summer (อีเวนต์)' WHERE slug = 'delfina-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDesire' WHERE slug = 'desire-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDesire (อีเวนต์)' WHERE slug = 'desire-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDespair of Abyss' WHERE slug = 'despair-of-abyss-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDevourer' WHERE slug = 'devourer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDevourer (30 วัน)' WHERE slug = 'devourer-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDevourer (อีเวนต์)' WHERE slug = 'devourer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDolores Marine Look' WHERE slug = 'dolores-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDoom Slave Summer' WHERE slug = 'doom-slave-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดDragon Coat' WHERE slug = 'dragon-coat-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดElegant Panthera Jacket' WHERE slug = 'elegant-panthera-jacket-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดElementalist Red Serpent (อีเวนต์)' WHERE slug = 'elementalist-red-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดElementalist White Santa' WHERE slug = 'elementalist-white-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดElite Le Blanc' WHERE slug = 'elite-le-blanc-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดElizabeth Summer' WHERE slug = 'elizabeth-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmerald Summer' WHERE slug = 'emerald-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmerald Summer (อีเวนต์)' WHERE slug = 'emerald-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmilia Avalanche' WHERE slug = 'emilia-avalanche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmilia Avalanche (อีเวนต์)' WHERE slug = 'emilia-avalanche-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmilia Basic' WHERE slug = 'emilia-basic-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmilia Basic (อีเวนต์)' WHERE slug = 'emilia-basic-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmilia Summer' WHERE slug = 'emilia-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmilia Summer (อีเวนต์)' WHERE slug = 'emilia-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmpirium Judith Blue Summer' WHERE slug = 'empirium-judith-blue-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmpirium Judith White Summer' WHERE slug = 'empirium-judith-white-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmpyrium Judith Blue Summer (อีเวนต์)' WHERE slug = 'empyrium-judith-blue-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEmpyrium Judith White Summer (อีเวนต์)' WHERE slug = 'empyrium-judith-white-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEnemy of Abyss' WHERE slug = 'enemy-of-abyss-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEnpermera' WHERE slug = 'enpermera-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEnpermera (อีเวนต์)' WHERE slug = 'enpermera-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Adelina Santa' WHERE slug = 'event-adelina-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Amy Halloween' WHERE slug = 'event-amy-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Asoka Santa' WHERE slug = 'event-asoka-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Berneli Santa' WHERE slug = 'event-berneli-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Bianca Winter' WHERE slug = 'event-bianca-winter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Black Santa Barrel' WHERE slug = 'event-black-santa-barrel-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Breeze Vita' WHERE slug = 'event-breeze-vita-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Cadet Amy Halloween' WHERE slug = 'event-cadet-amy-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Calyce Santa' WHERE slug = 'event-calyce-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Cassandra Summer' WHERE slug = 'event-cassandra-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Chloe Summer' WHERE slug = 'event-chloe-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Christina Summer' WHERE slug = 'event-christina-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Claire Bikini' WHERE slug = 'event-claire-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Code Name C Summer' WHERE slug = 'event-code-name-c-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Conductor Rio Summer' WHERE slug = 'event-conductor-rio-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Dolores Marine Look' WHERE slug = 'event-dolores-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Elementalist Santa' WHERE slug = 'event-elementalist-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Elizabeth Summer' WHERE slug = 'event-elizabeth-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Emilia Santa' WHERE slug = 'event-emilia-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Evil Polar Bear' WHERE slug = 'event-evil-polar-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Fenrir Summer' WHERE slug = 'event-fenrir-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Fighter Santa' WHERE slug = 'event-fighter-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Isaac Halloween' WHERE slug = 'event-isaac-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Jin Rock Star' WHERE slug = 'event-jin-rock-star-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Kevin Polar Bear' WHERE slug = 'event-kevin-polar-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Laura Rock Star' WHERE slug = 'event-laura-rock-star-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Leona Bikini' WHERE slug = 'event-leona-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Lorraine Marine Look' WHERE slug = 'event-lorraine-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Ludin Marine Look' WHERE slug = 'event-ludin-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Lynn Bikini' WHERE slug = 'event-lynn-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Meister Lorch Summer' WHERE slug = 'event-meister-lorch-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Misty Meadow' WHERE slug = 'event-misty-meadow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Montoro Polar Bear' WHERE slug = 'event-montoro-polar-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Musketeer Santa' WHERE slug = 'event-musketeer-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Nena Bikini' WHERE slug = 'event-nena-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Rachel Marine Look' WHERE slug = 'event-rachel-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Resistance Caisse Summer' WHERE slug = 'event-resistance-caisse-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Resistance JD Winter' WHERE slug = 'event-resistance-jd-winter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Romantic Spring' WHERE slug = 'event-romantic-spring-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Rosa Rock Star' WHERE slug = 'event-rosa-rock-star-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Santa Barrel' WHERE slug = 'event-santa-barrel-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Scout Santa' WHERE slug = 'event-scout-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Sherry Halloween' WHERE slug = 'event-sherry-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Sierra Summer' WHERE slug = 'event-sierra-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Snowflake Montoro Polar Bear' WHERE slug = 'event-snowflake-montoro-polar-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Valeria Santa' WHERE slug = 'event-valeria-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Violet Summer' WHERE slug = 'event-violet-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvent Wizard Santa' WHERE slug = 'event-wizard-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดEvil Polar Bear' WHERE slug = 'evil-polar-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดExecutor Anis Halloween' WHERE slug = 'executor-anis-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดExecutor Anis Halloween (อีเวนต์)' WHERE slug = 'executor-anis-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFanatic' WHERE slug = 'fanatic-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFantasma' WHERE slug = 'fantasma-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFantasma (อีเวนต์)' WHERE slug = 'fantasma-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFate of Castilla' WHERE slug = 'fate-of-castilla-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFemale Elementalist Blue Serpent (อีเวนต์)' WHERE slug = 'female-elementalist-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFemale Fighter Blue Serpent (อีเวนต์)' WHERE slug = 'female-fighter-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFemale Fighter Blue Serpent Plate (อีเวนต์)' WHERE slug = 'female-fighter-blue-serpent-plate-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFemale Musketeer Blue Serpent (อีเวนต์)' WHERE slug = 'female-musketeer-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFemale Scout Blue Serpent (อีเวนต์)' WHERE slug = 'female-scout-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFemale Wizard Blue Serpent (อีเวนต์)' WHERE slug = 'female-wizard-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFemme Fatal' WHERE slug = 'femme-fatal-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFenrir Summer' WHERE slug = 'fenrir-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดField Plate Mail' WHERE slug = 'field-plate-mail-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFighter Ogre' WHERE slug = 'fighter-ogre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFighter Red Serpent (อีเวนต์)' WHERE slug = 'fighter-red-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFighter White Santa' WHERE slug = 'fighter-white-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFigure Skate' WHERE slug = 'figure-skate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFigure Skate (อีเวนต์)' WHERE slug = 'figure-skate-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFraulein' WHERE slug = 'fraulein-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFraulein (30 วัน)' WHERE slug = 'fraulein-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFreesia' WHERE slug = 'freesia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดFreesia (อีเวนต์)' WHERE slug = 'freesia-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGaura' WHERE slug = 'gaura-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGavera' WHERE slug = 'gavera-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGeneral Plate' WHERE slug = 'general-plate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGeniaruleano' WHERE slug = 'geniaruleano-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGeniaruleano (อีเวนต์)' WHERE slug = 'geniaruleano-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGladiator Armor' WHERE slug = 'gladiator-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGloriosa' WHERE slug = 'gloriosa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGloriosa (อีเวนต์)' WHERE slug = 'gloriosa-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGold Bone Frame Armor' WHERE slug = 'gold-bone-frame-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGoldentale Magius' WHERE slug = 'goldentale-magius-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGradiatoris' WHERE slug = 'gradiatoris-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGrandies Summer' WHERE slug = 'grandies-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดGrandies Summer (อีเวนต์)' WHERE slug = 'grandies-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดHanbok' WHERE slug = 'hanbok-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดHonest Heart' WHERE slug = 'honest-heart-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดHoney Bee' WHERE slug = 'honey-bee-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดHurdy-Gurdy' WHERE slug = 'hurdy-gurdy-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดHurdy-Gurdy (30 วัน)' WHERE slug = 'hurdy-gurdy-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIbell' WHERE slug = 'ibell-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIberis' WHERE slug = 'iberis-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIberis (อีเวนต์)' WHERE slug = 'iberis-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIdge Basic' WHERE slug = 'idge-basic-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดImmortal Chief' WHERE slug = 'immortal-chief-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดImmortal Chief (30 วัน)' WHERE slug = 'immortal-chief-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIndigo 9' WHERE slug = 'indigo-9-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดInviardeco' WHERE slug = 'inviardeco-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIon Capitaine' WHERE slug = 'ion-capitaine-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIon Capitaine (อีเวนต์)' WHERE slug = 'ion-capitaine-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIris Qipao' WHERE slug = 'iris-qipao-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIsaac Halloween' WHERE slug = 'isaac-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIvory Bone-frame Armor' WHERE slug = 'ivory-bone-frame-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดIxia' WHERE slug = 'ixia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดJade Phraxi' WHERE slug = 'jade-phraxi-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดJane School Look (อีเวนต์)' WHERE slug = 'jane-school-look-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดJin Rock Star' WHERE slug = 'jin-rock-star-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดJudith Red Summer' WHERE slug = 'judith-red-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดJudith Red Summer (อีเวนต์)' WHERE slug = 'judith-red-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดJudith White Summer' WHERE slug = 'judith-white-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดJudith White Summer (อีเวนต์)' WHERE slug = 'judith-white-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดJustocorps' WHERE slug = 'justocorps-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดKalid Armor' WHERE slug = 'kalid-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดKalid Armor (30 วัน)' WHERE slug = 'kalid-armor-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดKalid Armor (อีเวนต์)' WHERE slug = 'kalid-armor-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดKane Halloween' WHERE slug = 'kane-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดKanhee Jakura' WHERE slug = 'kanhee-jakura-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดKevin Polar Bear' WHERE slug = 'kevin-polar-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดKiss Summer' WHERE slug = 'kiss-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดKiss Summer (อีเวนต์)' WHERE slug = 'kiss-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLa Chevre Cornue Fidele' WHERE slug = 'la-chevre-cornue-fidele-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLa Fleur Ecarlate' WHERE slug = 'la-fleur-ecarlate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLa Reve-comme poisson' WHERE slug = 'la-reve-comme-poisson-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLa Sensation Amicale' WHERE slug = 'la-sensation-amicale-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLa Ventisca' WHERE slug = 'la-ventisca-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLada Summer' WHERE slug = 'lada-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLada Summer (อีเวนต์)' WHERE slug = 'lada-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLady Raffles' WHERE slug = 'lady-raffles-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLady Raffles (30 วัน)' WHERE slug = 'lady-raffles-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLaranja e Preto' WHERE slug = 'laranja-e-preto-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLaranja e Preto (30 วัน)' WHERE slug = 'laranja-e-preto-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLaura Rock Star' WHERE slug = 'laura-rock-star-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLavender' WHERE slug = 'lavender-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Blanc' WHERE slug = 'le-blanc-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Lion Noble' WHERE slug = 'le-lion-noble-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Noir' WHERE slug = 'le-noir-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Reve Bleu' WHERE slug = 'le-reve-bleu-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Reve Bleu (อีเวนต์)' WHERE slug = 'le-reve-bleu-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Scarce (30 วัน)' WHERE slug = 'le-scarce-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Scarce Elementalist (30 วัน)' WHERE slug = 'le-scarce-elementalist-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Scarce Fighter (30 วัน)' WHERE slug = 'le-scarce-fighter-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Scarce Scout (30 วัน)' WHERE slug = 'le-scarce-scout-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLe Scarce Wizard (30 วัน)' WHERE slug = 'le-scarce-wizard-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLeather Armor' WHERE slug = 'leather-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLeather Tunic' WHERE slug = 'leather-tunic-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLeona Bikini' WHERE slug = 'leona-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLily' WHERE slug = 'lily-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLily (อีเวนต์)' WHERE slug = 'lily-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLinaria' WHERE slug = 'linaria-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLinaria (อีเวนต์)' WHERE slug = 'linaria-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLion Dance' WHERE slug = 'lion-dance-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLittle Princess' WHERE slug = 'little-princess-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLittle Princess (อีเวนต์)' WHERE slug = 'little-princess-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLonely Goatherd' WHERE slug = 'lonely-goatherd-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLonely Goatherd (30 วัน)' WHERE slug = 'lonely-goatherd-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLonely Goatherd (อีเวนต์)' WHERE slug = 'lonely-goatherd-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLong Coat' WHERE slug = 'long-coat-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLord Plate' WHERE slug = 'lord-plate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLord-of-Death' WHERE slug = 'lord-of-death-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLord-of-Death (อีเวนต์)' WHERE slug = 'lord-of-death-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLorraine Marine Look' WHERE slug = 'lorraine-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLudin Marine Look' WHERE slug = 'ludin-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLuxurious Disciple' WHERE slug = 'luxurious-disciple-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLuxurious Disciple (30 วัน)' WHERE slug = 'luxurious-disciple-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLynn Bikini' WHERE slug = 'lynn-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดLysette Halloween' WHERE slug = 'lysette-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMabro Metis' WHERE slug = 'mabro-metis-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMabro Peira' WHERE slug = 'mabro-peira-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMadame Relentless (อีเวนต์)' WHERE slug = 'madame-relentless-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMaid' WHERE slug = 'maid-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMale Elementalist Blue Serpent (อีเวนต์)' WHERE slug = 'male-elementalist-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMale Fighter Blue Serpent (อีเวนต์)' WHERE slug = 'male-fighter-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMale Fighter Blue Serpent Plate (อีเวนต์)' WHERE slug = 'male-fighter-blue-serpent-plate-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMale Musketeer Blue Serpent (อีเวนต์)' WHERE slug = 'male-musketeer-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMale Scout Blue Serpent (อีเวนต์)' WHERE slug = 'male-scout-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMale Wizard Blue Serpent (อีเวนต์)' WHERE slug = 'male-wizard-blue-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMarie Summer (อีเวนต์)' WHERE slug = 'marie-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMary Summer' WHERE slug = 'mary-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMeister Lorch Summer' WHERE slug = 'meister-lorch-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMetallic Suit' WHERE slug = 'metallic-suit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMireille School Look (อีเวนต์)' WHERE slug = 'mireille-school-look-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMisty Meadow' WHERE slug = 'misty-meadow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดModern Fatima' WHERE slug = 'modern-fatima-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดModern Fatima (อีเวนต์)' WHERE slug = 'modern-fatima-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMontoro Polar Bear' WHERE slug = 'montoro-polar-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMoon Halloween' WHERE slug = 'moon-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMoon Halloween (อีเวนต์)' WHERE slug = 'moon-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMusashi' WHERE slug = 'musashi-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMusashi (30 วัน)' WHERE slug = 'musashi-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMusketeer Red Serpent (อีเวนต์)' WHERE slug = 'musketeer-red-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดMusketeer White Santa' WHERE slug = 'musketeer-white-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNana Artozeia' WHERE slug = 'nana-artozeia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNarciso' WHERE slug = 'narciso-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNarciso (30 วัน)' WHERE slug = 'narciso-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNatalie Summer' WHERE slug = 'natalie-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNatalie Summer (อีเวนต์)' WHERE slug = 'natalie-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNatural Style' WHERE slug = 'natural-style-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNena Bikini' WHERE slug = 'nena-bikini-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNike Halloween' WHERE slug = 'nike-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNike Halloween (อีเวนต์)' WHERE slug = 'nike-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNinja' WHERE slug = 'ninja-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNoblesse Coat' WHERE slug = 'noblesse-coat-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNoblesse Coat (30 วัน)' WHERE slug = 'noblesse-coat-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดNoir Gangster' WHERE slug = 'noir-gangster-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดOil Body' WHERE slug = 'oil-body-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดOlga Patricia' WHERE slug = 'olga-patricia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดOrnella Summer' WHERE slug = 'ornella-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดOrnella Summer (อีเวนต์)' WHERE slug = 'ornella-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPanfilo Basic' WHERE slug = 'panfilo-basic-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPanfilo Basic (อีเวนต์)' WHERE slug = 'panfilo-basic-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPegadilla Officer' WHERE slug = 'pegadilla-officer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPegadilla Officer (อีเวนต์)' WHERE slug = 'pegadilla-officer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPendera Jacket' WHERE slug = 'pendera-jacket-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPhi Rasto' WHERE slug = 'phi-rasto-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPiernoente' WHERE slug = 'piernoente-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPigeonne' WHERE slug = 'pigeonne-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPigeonne (อีเวนต์)' WHERE slug = 'pigeonne-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPiore Rosso' WHERE slug = 'piore-rosso-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPirate' WHERE slug = 'pirate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPirate (30 วัน)' WHERE slug = 'pirate-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPlate Mail' WHERE slug = 'plate-mail-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPrepolly Basic Long Coat' WHERE slug = 'prepolly-basic-long-coat-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPrepolly Basic Long Coat (อีเวนต์)' WHERE slug = 'prepolly-basic-long-coat-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPrepolly Brio Solar' WHERE slug = 'prepolly-brio-solar-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPrepolly Brio Solar (อีเวนต์)' WHERE slug = 'prepolly-brio-solar-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPrepolly Ma-1 Jacket' WHERE slug = 'prepolly-ma-1-jacket-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPrepolly Ma-1 Jacket (อีเวนต์)' WHERE slug = 'prepolly-ma-1-jacket-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPretty Noble' WHERE slug = 'pretty-noble-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPretty Noble (อีเวนต์)' WHERE slug = 'pretty-noble-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดPrimavella' WHERE slug = 'primavella-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดQipao' WHERE slug = 'qipao-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดQipao (30 วัน)' WHERE slug = 'qipao-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRachel Marine Look' WHERE slug = 'rachel-marine-look-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRaid Phraxi' WHERE slug = 'raid-phraxi-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRainism' WHERE slug = 'rainism-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRainism (อีเวนต์)' WHERE slug = 'rainism-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRamiro Summer' WHERE slug = 'ramiro-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRamiro Summer (อีเวนต์)' WHERE slug = 'ramiro-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRed Bear Leather' WHERE slug = 'red-bear-leather-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRed Innocence' WHERE slug = 'red-innocence-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRed Innocence (อีเวนต์)' WHERE slug = 'red-innocence-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRed Liberte' WHERE slug = 'red-liberte-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRed Liberte (อีเวนต์)' WHERE slug = 'red-liberte-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRed Serpent Plate (อีเวนต์)' WHERE slug = 'red-serpent-plate-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRed Vivace' WHERE slug = 'red-vivace-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRed Vivace (อีเวนต์)' WHERE slug = 'red-vivace-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRedingote' WHERE slug = 'redingote-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRelentless Madame' WHERE slug = 'relentless-madame-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRescue Suit' WHERE slug = 'rescue-suit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดResistance Caisse Summer' WHERE slug = 'resistance-caisse-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดResistance JD Winter' WHERE slug = 'resistance-jd-winter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRevenant' WHERE slug = 'revenant-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRevenant (อีเวนต์)' WHERE slug = 'revenant-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRibe Le Blanc' WHERE slug = 'ribe-le-blanc-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe' WHERE slug = 'robe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Fire' WHERE slug = 'robe-of-fire-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Ice' WHERE slug = 'robe-of-ice-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Neptune' WHERE slug = 'robe-of-neptune-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Pluto' WHERE slug = 'robe-of-pluto-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Sea Demon' WHERE slug = 'robe-of-sea-demon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Sky Demon' WHERE slug = 'robe-of-sky-demon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Superb Demon' WHERE slug = 'robe-of-superb-demon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Uranus' WHERE slug = 'robe-of-uranus-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of White' WHERE slug = 'robe-of-white-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRobe of Wind' WHERE slug = 'robe-of-wind-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRomantic Spring' WHERE slug = 'romantic-spring-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRosa Halloween' WHERE slug = 'rosa-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRosa Matrimonio' WHERE slug = 'rosa-matrimonio-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRosa Rock Star' WHERE slug = 'rosa-rock-star-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRosacamille' WHERE slug = 'rosacamille-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRosas Halloween (อีเวนต์)' WHERE slug = 'rosas-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRose Camellia' WHERE slug = 'rose-camellia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRose Camellia (30 วัน)' WHERE slug = 'rose-camellia-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRose Patricia' WHERE slug = 'rose-patricia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRose of Sonora' WHERE slug = 'rose-of-sonora-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRose of Sonora (อีเวนต์)' WHERE slug = 'rose-of-sonora-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRosie Summer' WHERE slug = 'rosie-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRosie Summer (อีเวนต์)' WHERE slug = 'rosie-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRouge e Blue' WHERE slug = 'rouge-e-blue-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRougeannoir' WHERE slug = 'rougeannoir-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRougeannoir (อีเวนต์)' WHERE slug = 'rougeannoir-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRoyal Guard Delfina Summer' WHERE slug = 'royal-guard-delfina-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRoyal Guard Delfina Summer (อีเวนต์)' WHERE slug = 'royal-guard-delfina-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดRuidestencia' WHERE slug = 'ruidestencia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSage' WHERE slug = 'sage-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSage (30 วัน)' WHERE slug = 'sage-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSakura (30 วัน)' WHERE slug = 'sakura-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSalvia' WHERE slug = 'salvia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSanta Barrel' WHERE slug = 'santa-barrel-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSanta (30 วัน)' WHERE slug = 'santa-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSanta Nar' WHERE slug = 'santa-nar-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSanta Nar (อีเวนต์)' WHERE slug = 'santa-nar-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSanto De Blanc' WHERE slug = 'santo-de-blanc-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSantuario Metal Armor' WHERE slug = 'santuario-metal-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดScale Armor' WHERE slug = 'scale-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดScarlet Admiral' WHERE slug = 'scarlet-admiral-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSchwarseiz' WHERE slug = 'schwarseiz-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดScout Red Serpent (อีเวนต์)' WHERE slug = 'scout-red-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดScout White Santa' WHERE slug = 'scout-white-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSergeant Barrel Summer' WHERE slug = 'sergeant-barrel-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSergeant Barrel Summer (อีเวนต์)' WHERE slug = 'sergeant-barrel-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดShadow Robe' WHERE slug = 'shadow-robe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดShaman Viator (อีเวนต์)' WHERE slug = 'shaman-viator-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSherry Halloween' WHERE slug = 'sherry-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSierra Summer' WHERE slug = 'sierra-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSilverane' WHERE slug = 'silverane-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSilverane (อีเวนต์)' WHERE slug = 'silverane-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSky Blue' WHERE slug = 'sky-blue-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSky Blue (อีเวนต์)' WHERE slug = 'sky-blue-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSlend Kloria' WHERE slug = 'slend-kloria-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSlendor Peaco' WHERE slug = 'slendor-peaco-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSniper White Vent (อีเวนต์)' WHERE slug = 'sniper-white-vent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSnow Blossom' WHERE slug = 'snow-blossom-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSnow Blossom (อีเวนต์)' WHERE slug = 'snow-blossom-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSnow Flower' WHERE slug = 'snow-flower-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSnow Flower (อีเวนต์)' WHERE slug = 'snow-flower-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSnowfield Witch' WHERE slug = 'snowfield-witch-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSnowfield Witch (อีเวนต์)' WHERE slug = 'snowfield-witch-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSnowflake Montoro Polar Bear' WHERE slug = 'snowflake-montoro-polar-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSoho Basic' WHERE slug = 'soho-basic-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSoho Basic (อีเวนต์)' WHERE slug = 'soho-basic-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSpirit Cleanthes' WHERE slug = 'spirit-cleanthes-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSpirit Cleanthes (อีเวนต์)' WHERE slug = 'spirit-cleanthes-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSplender Boots Style' WHERE slug = 'splender-boots-style-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดStandard' WHERE slug = 'standard-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSteel Griffon' WHERE slug = 'steel-griffon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSteel Griffon (อีเวนต์)' WHERE slug = 'steel-griffon-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดStrata Devil' WHERE slug = 'strata-devil-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดStrata Devil Plate' WHERE slug = 'strata-devil-plate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดStriform' WHERE slug = 'striform-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดStriform (30 วัน)' WHERE slug = 'striform-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดStudded-leather Armor' WHERE slug = 'studded-leather-armor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSultan' WHERE slug = 'sultan-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSultan (30 วัน)' WHERE slug = 'sultan-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSunset Rouge' WHERE slug = 'sunset-rouge-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSunset Stripe Suit' WHERE slug = 'sunset-stripe-suit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSuperior Centurion' WHERE slug = 'superior-centurion-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSuperior Hurdy-Gurdy' WHERE slug = 'superior-hurdy-gurdy-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSweet Melody' WHERE slug = 'sweet-melody-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSybis' WHERE slug = 'sybis-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดSybis (อีเวนต์)' WHERE slug = 'sybis-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดTemptation Rose' WHERE slug = 'temptation-rose-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดTemptation of Nightmare' WHERE slug = 'temptation-of-nightmare-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดThai Fighter' WHERE slug = 'thai-fighter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดThai Fighter (30 วัน)' WHERE slug = 'thai-fighter-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดThe Elementalist' WHERE slug = 'the-elementalist-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดTorosmata Ren' WHERE slug = 'torosmata-ren-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดTorozvah Ell' WHERE slug = 'torozvah-ell-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดTorsche Dress' WHERE slug = 'torsche-dress-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดTrifolium' WHERE slug = 'trifolium-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดTrifolium (อีเวนต์)' WHERE slug = 'trifolium-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดUndercover' WHERE slug = 'undercover-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดUndercover (อีเวนต์)' WHERE slug = 'undercover-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดUntouchable' WHERE slug = 'untouchable-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดUntouchable (30 วัน)' WHERE slug = 'untouchable-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดUpsilon' WHERE slug = 'upsilon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดValkyries' WHERE slug = 'valkyries-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVan Halloween' WHERE slug = 'van-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVan Summer' WHERE slug = 'van-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVan Summer (อีเวนต์)' WHERE slug = 'van-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVans Halloween (อีเวนต์)' WHERE slug = 'vans-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVariltorta' WHERE slug = 'variltorta-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVeronica Qipao' WHERE slug = 'veronica-qipao-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVeronica Qipao (อีเวนต์)' WHERE slug = 'veronica-qipao-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVespanola Navy Admiral' WHERE slug = 'vespanola-navy-admiral-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVespanola Navy Captain' WHERE slug = 'vespanola-navy-captain-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVespanola Navy Officer' WHERE slug = 'vespanola-navy-officer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVespanola Navy Soldier' WHERE slug = 'vespanola-navy-soldier-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดViki Summer' WHERE slug = 'viki-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดViki Summer (อีเวนต์)' WHERE slug = 'viki-summer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVincent Capitaine' WHERE slug = 'vincent-capitaine-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVincent Capitaine (อีเวนต์)' WHERE slug = 'vincent-capitaine-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดViola Neve' WHERE slug = 'viola-neve-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดViolet Summer' WHERE slug = 'violet-summer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVioleta' WHERE slug = 'violeta-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVon Trapp' WHERE slug = 'von-trapp-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดVon Trapp (30 วัน)' WHERE slug = 'von-trapp-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWedding Dress' WHERE slug = 'wedding-dress-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Bear' WHERE slug = 'white-bear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Bear (30 วัน)' WHERE slug = 'white-bear-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Blossom' WHERE slug = 'white-blossom-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Cosmos' WHERE slug = 'white-cosmos-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Crocodile Leather' WHERE slug = 'white-crocodile-leather-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Dragoon Coat' WHERE slug = 'white-dragoon-coat-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Elegance' WHERE slug = 'white-elegance-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Elegance (อีเวนต์)' WHERE slug = 'white-elegance-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Liberte' WHERE slug = 'white-liberte-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Liberte (อีเวนต์)' WHERE slug = 'white-liberte-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Rose' WHERE slug = 'white-rose-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Rose (30 วัน)' WHERE slug = 'white-rose-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Vent' WHERE slug = 'white-vent-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Vent (30 วัน)' WHERE slug = 'white-vent-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWhite Vent (อีเวนต์)' WHERE slug = 'white-vent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWild Darkness' WHERE slug = 'wild-darkness-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWild Darkness (อีเวนต์)' WHERE slug = 'wild-darkness-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWind of First' WHERE slug = 'wind-of-first-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWizard Red Serpent (อีเวนต์)' WHERE slug = 'wizard-red-serpent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดWizard White Santa' WHERE slug = 'wizard-white-santa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดZaved Halloween' WHERE slug = 'zaved-halloween-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดZaved Halloween (อีเวนต์)' WHERE slug = 'zaved-halloween-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดZebra' WHERE slug = 'zebra-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุดZephyranthes' WHERE slug = 'zephyranthes-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากBeliths' WHERE slug = 'beliths-mask' AND name_th IS NULL;