-- Migration 056: Thai names batch 3/10
-- Generated: 2026-03-16T03:42:16.054Z

UPDATE items SET name_th = 'แว่นตาBernellis Beach (อีเวนต์)' WHERE slug = 'bernellis-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาBlood Navy/Supreme Commander Cano School Look' WHERE slug = 'blood-navy-supreme-commander-cano-school-look-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาBrown Boeing' WHERE slug = 'brown-boeing-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาBrown Boeing (อีเวนต์)' WHERE slug = 'brown-boeing-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากCat' WHERE slug = 'cat-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากCat (30 วัน)' WHERE slug = 'cat-mask-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากCode Name Vs' WHERE slug = 'code-name-vs-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาCode Name Vs' WHERE slug = 'code-name-vs-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากCorazons' WHERE slug = 'corazons-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากCorazons (อีเวนต์)' WHERE slug = 'corazons-mask-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาCrusader Daria Summer' WHERE slug = 'crusader-daria-summer-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาDandy' WHERE slug = 'dandy-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากEvent Code Name Vs' WHERE slug = 'event-code-name-vs-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาEvent Code Name Vs' WHERE slug = 'event-code-name-vs-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาEvent Kanes' WHERE slug = 'event-kanes-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาFemale Elementalists Beach (อีเวนต์)' WHERE slug = 'female-elementalists-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาFemale Fighters Beach (อีเวนต์)' WHERE slug = 'female-fighters-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาFemale Musketeers Beach (อีเวนต์)' WHERE slug = 'female-musketeers-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาFemale Scouts Beach (อีเวนต์)' WHERE slug = 'female-scouts-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาFemale Wizards Beach (อีเวนต์)' WHERE slug = 'female-wizards-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาGracielo School Look' WHERE slug = 'gracielo-school-look-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาGuillotine Black' WHERE slug = 'guillotine-black-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาGuillotine' WHERE slug = 'guillotine-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาGuillotine White' WHERE slug = 'guillotine-white-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาInnocence' WHERE slug = 'innocence-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาInnocence (อีเวนต์)' WHERE slug = 'innocence-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาKanes' WHERE slug = 'kanes-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาLead Manager Rachels' WHERE slug = 'lead-manager-rachels-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาLead Managers' WHERE slug = 'lead-managers-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากLead Managers' WHERE slug = 'lead-managers-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาLiberte (อีเวนต์)' WHERE slug = 'liberte-glasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาMale Elementalists Beach (อีเวนต์)' WHERE slug = 'male-elementalists-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาMale Fighters Beach (อีเวนต์)' WHERE slug = 'male-fighters-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาMale Musketeers Beach (อีเวนต์)' WHERE slug = 'male-musketeers-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาMale Scouts Beach (อีเวนต์)' WHERE slug = 'male-scouts-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาMale Wizards Beach (อีเวนต์)' WHERE slug = 'male-wizards-beach-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาNena School Look' WHERE slug = 'nena-school-look-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาRamiro Summer' WHERE slug = 'ramiro-summer-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาRamiro Summer (อีเวนต์)' WHERE slug = 'ramiro-summer-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาSquare Brio Solar' WHERE slug = 'square-brio-solar-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาSquare Brio Solar (อีเวนต์)' WHERE slug = 'square-brio-solar-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาStylish Sun' WHERE slug = 'stylish-sun-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาStylish Sun (อีเวนต์)' WHERE slug = 'stylish-sun-glasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาViki Summer' WHERE slug = 'viki-summer-sunglasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาViki Summer (อีเวนต์)' WHERE slug = 'viki-summer-sunglasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากWhite Wolf' WHERE slug = 'white-wolf-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก(Event) Purple Kids' WHERE slug = 'event-purple-kids-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผม(Event) Sierra Summer' WHERE slug = 'event-sierra-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAfro' WHERE slug = 'afro-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAfro (30 วัน)' WHERE slug = 'afro-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAfro (อีเวนต์)' WHERE slug = 'afro-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกAgiolegion' WHERE slug = 'agiolegion-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAisha Halloween' WHERE slug = 'aisha-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAisha Halloween (อีเวนต์)' WHERE slug = 'aisha-halloween-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAither Summer' WHERE slug = 'aither-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAither Summer (อีเวนต์)' WHERE slug = 'aither-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกAlbaes' WHERE slug = 'albaes-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกAlbaes (30 วัน)' WHERE slug = 'albaes-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAlcaique Academic Style' WHERE slug = 'alcaique-academic-style-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกAlegrias' WHERE slug = 'alegrias-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกAlegrias (30 วัน)' WHERE slug = 'alegrias-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAmy Halloween' WHERE slug = 'amy-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAndante' WHERE slug = 'andante-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกAngelica' WHERE slug = 'angelica-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAnis Natural' WHERE slug = 'anis-natural-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAnis Summer' WHERE slug = 'anis-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAnis Summer (อีเวนต์)' WHERE slug = 'anis-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมArchbishop Summer' WHERE slug = 'archbishop-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมArchbishop Summer (อีเวนต์)' WHERE slug = 'archbishop-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAsoka Santa' WHERE slug = 'asoka-santa-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกAsupplegion' WHERE slug = 'asupplegion-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAtra Flos' WHERE slug = 'atra-flos-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAuro Ohriza' WHERE slug = 'auro-ohriza-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAvalanche Femme Witch' WHERE slug = 'avalanche-femme-witch-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBanshee Natalie' WHERE slug = 'banshee-natalie-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBasic Adelina' WHERE slug = 'basic-adelina-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBasic Adelina (30 วัน)' WHERE slug = 'basic-adelina-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBattle Cooks' WHERE slug = 'battle-cooks-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBattle Smiths' WHERE slug = 'battle-smiths-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBear' WHERE slug = 'bear-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBear (30 วัน)' WHERE slug = 'bear-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBeatrice Summer' WHERE slug = 'beatrice-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBeatrice Summer (อีเวนต์)' WHERE slug = 'beatrice-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBeckys Three Cone' WHERE slug = 'beckys-three-cone-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'เขาBeliths' WHERE slug = 'beliths-horn' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBelle De Jour' WHERE slug = 'belle-de-jour-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBelle De Jour (อีเวนต์)' WHERE slug = 'belle-de-jour-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBelly Dancer' WHERE slug = 'belly-dancer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBelly Dancer (30 วัน)' WHERE slug = 'belly-dancer-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBianca Winter' WHERE slug = 'bianca-winter-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBlack Banshee' WHERE slug = 'black-banshee-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlack Cobra' WHERE slug = 'black-cobra-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlack Elegance' WHERE slug = 'black-elegance-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlack Elegance (อีเวนต์)' WHERE slug = 'black-elegance-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlack Pearl' WHERE slug = 'black-pearl-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlack Samurai (30 วัน)' WHERE slug = 'black-samurai-helmet-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlack Santa Barrel' WHERE slug = 'black-santa-barrel-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBlack Shaggy' WHERE slug = 'black-shaggy-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBlack Shaggy (30 วัน)' WHERE slug = 'black-shaggy-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปBlacksmith (30 วัน)' WHERE slug = 'blacksmith-cap-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปBlacksmith Lilly' WHERE slug = 'blacksmith-lilly-cap' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปBlacksmiths' WHERE slug = 'blacksmiths-cap' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlaue Hair' WHERE slug = 'blaue-hair-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlaue Spiel' WHERE slug = 'blaue-spiel-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlaue Spiel (อีเวนต์)' WHERE slug = 'blaue-spiel-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBlaze' WHERE slug = 'blaze-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBlaze (30 วัน)' WHERE slug = 'blaze-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBler Rasto' WHERE slug = 'bler-rasto-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlood Navy' WHERE slug = 'blood-navy-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBlood Navy/Supreme Commander Cano School Look' WHERE slug = 'blood-navy-supreme-commander-cano-school-look-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBlood Navy/Supreme Commander Cano School-Look (อีเวนต์)' WHERE slug = 'blood-navy-supreme-commander-cano-school-look-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBlossom' WHERE slug = 'blossom-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlue Feather' WHERE slug = 'blue-feather-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlue Innocence' WHERE slug = 'blue-innocence-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlue Innocence (อีเวนต์)' WHERE slug = 'blue-innocence-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBlue Samurai (30 วัน)' WHERE slug = 'blue-samurai-helmet-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBluish Feather (30 วัน)' WHERE slug = 'bluish-feather-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBonnet' WHERE slug = 'bonnet-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBonnet (อีเวนต์)' WHERE slug = 'bonnet-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBreeze Vita' WHERE slug = 'breeze-vita-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBrio Solar Long' WHERE slug = 'brio-solar-long-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBrio Solar Long (อีเวนต์)' WHERE slug = 'brio-solar-long-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBristian Noble' WHERE slug = 'bristian-noble-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBrown Andante' WHERE slug = 'brown-andante-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBrown Ear Mouse' WHERE slug = 'brown-ear-mouse-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBrown Ear Mouse (30 วัน)' WHERE slug = 'brown-ear-mouse-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBrown Mouse' WHERE slug = 'brown-mouse-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกBrown Mouse (30 วัน)' WHERE slug = 'brown-mouse-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBrown Pomade' WHERE slug = 'brown-pomade-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมBrown Pomade (อีเวนต์)' WHERE slug = 'brown-pomade-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากByzantkohl' WHERE slug = 'byzantkohl-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากByzantkohl (30 วัน)' WHERE slug = 'byzantkohl-mask-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCadet Amy Halloween' WHERE slug = 'cadet-amy-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCadet Romina Summer' WHERE slug = 'cadet-romina-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCadet Romina Summer (อีเวนต์)' WHERE slug = 'cadet-romina-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'มงกุฎCalienalbino' WHERE slug = 'calienalbino-crown' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCamaryllis' WHERE slug = 'camaryllis-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCamisa' WHERE slug = 'camisa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCamisa (30 วัน)' WHERE slug = 'camisa-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCanna Summer' WHERE slug = 'canna-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCanna Summer (อีเวนต์)' WHERE slug = 'canna-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCano Marine Look' WHERE slug = 'cano-marine-look-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCano Marine Look (อีเวนต์)' WHERE slug = 'cano-marine-look-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCape Pattern (อีเวนต์)' WHERE slug = 'cape-pattern-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCapybara' WHERE slug = 'capybara-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCapybara (อีเวนต์)' WHERE slug = 'capybara-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCassandra Summer' WHERE slug = 'cassandra-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCat' WHERE slug = 'cat-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCatherine Christmas' WHERE slug = 'catherine-christmas-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCattleya' WHERE slug = 'cattleya-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCattleya (อีเวนต์)' WHERE slug = 'cattleya-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCenter Part' WHERE slug = 'center-part-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCenter Part (อีเวนต์)' WHERE slug = 'center-part-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCenturion' WHERE slug = 'centurion-helm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCenturion (30 วัน)' WHERE slug = 'centurion-helm-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCenturion (อีเวนต์)' WHERE slug = 'centurion-helm-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCharlotte Summer' WHERE slug = 'charlotte-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCharlotte Summer (อีเวนต์)' WHERE slug = 'charlotte-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCharm' WHERE slug = 'charm-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCherry Blossom' WHERE slug = 'cherry-blossom-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมChloe Summer' WHERE slug = 'chloe-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมChristina Summer' WHERE slug = 'christina-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCiel Liberte' WHERE slug = 'ciel-liberte-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCiel Liberte (อีเวนต์)' WHERE slug = 'ciel-liberte-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClaire Short' WHERE slug = 'claire-short-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClaire Short (อีเวนต์)' WHERE slug = 'claire-short-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClara Mago' WHERE slug = 'clara-mago-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกClara Mago' WHERE slug = 'clara-mago-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClasse Alta - Pomade' WHERE slug = 'classe-alta-pomade-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClasse Alta - Pomade (อีเวนต์)' WHERE slug = 'classe-alta-pomade-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClasse Alta - Princess' WHERE slug = 'classe-alta-princess-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClasse Alta - Princess (อีเวนต์)' WHERE slug = 'classe-alta-princess-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClasse Alta - Snow' WHERE slug = 'classe-alta-snow-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClasse Alta - Snow (อีเวนต์)' WHERE slug = 'classe-alta-snow-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมClassic Short' WHERE slug = 'classic-short-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปClown' WHERE slug = 'clown-cap' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCockatrice' WHERE slug = 'cockatrice-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCockatrice (30 วัน)' WHERE slug = 'cockatrice-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCockatrice (อีเวนต์)' WHERE slug = 'cockatrice-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCode Name C Summer' WHERE slug = 'code-name-c-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCode Name L Vampire' WHERE slug = 'code-name-l-vampire-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCode Name T Summer (อีเวนต์)' WHERE slug = 'code-name-t-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCodename T Summer' WHERE slug = 'codename-t-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCoimbra Centurion (อีเวนต์)' WHERE slug = 'coimbra-centurion-helm-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCoimbra Trooper' WHERE slug = 'coimbra-trooper-helm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCoimbra Trooper (30 วัน)' WHERE slug = 'coimbra-trooper-helm-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมConductor Rio Summer' WHERE slug = 'conductor-rio-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCooks' WHERE slug = 'cooks-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCorsair' WHERE slug = 'corsair-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCorsair (30 วัน)' WHERE slug = 'corsair-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCowboy' WHERE slug = 'cowboy-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCowgirl' WHERE slug = 'cowgirl-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCrusader Daria Summer' WHERE slug = 'crusader-daria-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCrusader Daria Summer (อีเวนต์)' WHERE slug = 'crusader-daria-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCruz Avalanche' WHERE slug = 'cruz-avalanche-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกCute Amy' WHERE slug = 'cute-amy-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมCute Blossom' WHERE slug = 'cute-blossom-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมDe Laffitte (อีเวนต์)' WHERE slug = 'de-laffitte-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมDe Lange Souriant' WHERE slug = 'de-lange-souriant-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมDeep Blue' WHERE slug = 'deep-blue-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDeinclian' WHERE slug = 'deinclian-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมDespair of Abyss' WHERE slug = 'despair-of-abyss-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDesperado' WHERE slug = 'desperado-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDesperado (30 วัน)' WHERE slug = 'desperado-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDetective' WHERE slug = 'detective-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDetective (30 วัน)' WHERE slug = 'detective-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDetective (อีเวนต์)' WHERE slug = 'detective-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDisdasha' WHERE slug = 'disdasha-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDisdasha (30 วัน)' WHERE slug = 'disdasha-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDisdasha (อีเวนต์)' WHERE slug = 'disdasha-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDolores Marine Look' WHERE slug = 'dolores-marine-look-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกDoom Slave' WHERE slug = 'doom-slave-helm' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมDoom Slave Summer' WHERE slug = 'doom-slave-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมDoom Slave Summer (อีเวนต์)' WHERE slug = 'doom-slave-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกElementalist (30 วัน)' WHERE slug = 'elementalist-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกElementalists' WHERE slug = 'elementalists-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมElizabeth Summer' WHERE slug = 'elizabeth-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEmilia Avalanche' WHERE slug = 'emilia-avalanche-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEmilia Summer' WHERE slug = 'emilia-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEmilia Summer (อีเวนต์)' WHERE slug = 'emilia-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEmpirium Judith Summer' WHERE slug = 'empirium-judith-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEmpyrium Judith Summer (อีเวนต์)' WHERE slug = 'empyrium-judith-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEnfermera' WHERE slug = 'enfermera-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปEngineers' WHERE slug = 'engineers-cap' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEnpermera (อีเวนต์)' WHERE slug = 'enpermera-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Adelina Santa' WHERE slug = 'event-adelina-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Amy Halloween' WHERE slug = 'event-amy-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Asoka Santa' WHERE slug = 'event-asoka-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Berneli Santa' WHERE slug = 'event-berneli-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Bianca Winter' WHERE slug = 'event-bianca-winter-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Black Santa Barrel' WHERE slug = 'event-black-santa-barrel-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Breeze Vita' WHERE slug = 'event-breeze-vita-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Cadet Amy Halloween' WHERE slug = 'event-cadet-amy-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Calyce Santa' WHERE slug = 'event-calyce-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Cassandra Summer' WHERE slug = 'event-cassandra-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Catherine Christmas' WHERE slug = 'event-catherine-christmas-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Chloe Summer' WHERE slug = 'event-chloe-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Christina Summer' WHERE slug = 'event-christina-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Code Name C Summer' WHERE slug = 'event-code-name-c-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Code Name L Vampire' WHERE slug = 'event-code-name-l-vampire-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Conductor Rio Summer' WHERE slug = 'event-conductor-rio-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Dolores Marine Look' WHERE slug = 'event-dolores-marine-look-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Elizabeth Summer' WHERE slug = 'event-elizabeth-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Emilia Santa' WHERE slug = 'event-emilia-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Enpermera' WHERE slug = 'event-enpermera-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Fantasma' WHERE slug = 'event-fantasma-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Fenrir Summer' WHERE slug = 'event-fenrir-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Isaac Halloween' WHERE slug = 'event-isaac-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Jin Rock Star Pink' WHERE slug = 'event-jin-rock-star-pink-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Laura White Rock Star' WHERE slug = 'event-laura-white-rock-star-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Leona Vampire' WHERE slug = 'event-leona-vampire-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Lorraine Marine Look' WHERE slug = 'event-lorraine-marine-look-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Lynn Silver' WHERE slug = 'event-lynn-silver-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Meister Lorch Summer' WHERE slug = 'event-meister-lorch-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Misty Meadow' WHERE slug = 'event-misty-meadow-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Resistance Caisse Summer' WHERE slug = 'event-resistance-caisse-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Resistance JD Winter' WHERE slug = 'event-resistance-jd-winter-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Romantic Spring' WHERE slug = 'event-romantic-spring-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Rosa Rock Star Pink' WHERE slug = 'event-rosa-rock-star-pink-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Rudolph' WHERE slug = 'event-rudolph-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Rudolph Santa' WHERE slug = 'event-rudolph-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Santa Barrel' WHERE slug = 'event-santa-barrel-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Santa' WHERE slug = 'event-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Sherry Halloween' WHERE slug = 'event-sherry-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Sirius Short' WHERE slug = 'event-sirius-short-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Spade' WHERE slug = 'event-spade-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกEvent Valeria Santa' WHERE slug = 'event-valeria-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Vendetta Vampire' WHERE slug = 'event-vendetta-vampire-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมEvent Violet Summer' WHERE slug = 'event-violet-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมFallen Angels' WHERE slug = 'fallen-angels-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกFantasma' WHERE slug = 'fantasma-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกFantasma (อีเวนต์)' WHERE slug = 'fantasma-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมFemme Fatal' WHERE slug = 'femme-fatal-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมFemme Fatal (อีเวนต์)' WHERE slug = 'femme-fatal-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกFencers' WHERE slug = 'fencers-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมFenrir Summer' WHERE slug = 'fenrir-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGaura' WHERE slug = 'gaura-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGavera' WHERE slug = 'gavera-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGeneral (อีเวนต์)' WHERE slug = 'general-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกGeneral' WHERE slug = 'general-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกGladiators' WHERE slug = 'gladiators-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกGloriel Archbishop' WHERE slug = 'gloriel-archbishop-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกGloriel Archbishop (อีเวนต์)' WHERE slug = 'gloriel-archbishop-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGracielo School Look' WHERE slug = 'gracielo-school-look-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGracielo School-Look (อีเวนต์)' WHERE slug = 'gracielo-school-look-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGracielo Scratch' WHERE slug = 'gracielo-scratch-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGracielo Scratch (อีเวนต์)' WHERE slug = 'gracielo-scratch-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGrandies Summer' WHERE slug = 'grandies-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGrandies White Summer' WHERE slug = 'grandies-white-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGrandis Summer (อีเวนต์)' WHERE slug = 'grandis-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกGray Feather' WHERE slug = 'gray-feather-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกGray Feather (30 วัน)' WHERE slug = 'gray-feather-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGray Sheep-horn' WHERE slug = 'gray-sheep-horn-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGray Sheep-horn (30 วัน)' WHERE slug = 'gray-sheep-horn-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGray Terious' WHERE slug = 'gray-terious-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมGrayterious (30 วัน)' WHERE slug = 'grayterious-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกHalloween Pumpkin (อีเวนต์)' WHERE slug = 'halloween-pumpkin-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมHermes Elegance' WHERE slug = 'hermes-elegance-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมHermes Elegance (อีเวนต์)' WHERE slug = 'hermes-elegance-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมHissioum' WHERE slug = 'hissioum-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมHissioum (อีเวนต์)' WHERE slug = 'hissioum-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมHonest Heart' WHERE slug = 'honest-heart-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมHoney Bee' WHERE slug = 'honey-bee-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมHoney Bee (อีเวนต์)' WHERE slug = 'honey-bee-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกHouse Call' WHERE slug = 'house-call-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกHouse Call (อีเวนต์)' WHERE slug = 'house-call-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'มงกุฎIce' WHERE slug = 'ice-crown' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกIdges' WHERE slug = 'idges-helmet' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมIndigo 9' WHERE slug = 'indigo-9-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมIon Capitaine' WHERE slug = 'ion-capitaine-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมIon Capitaine (อีเวนต์)' WHERE slug = 'ion-capitaine-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกIrolina (30 วัน)' WHERE slug = 'irolina-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากIron' WHERE slug = 'iron-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากIron (30 วัน)' WHERE slug = 'iron-mask-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมIsaac Halloween' WHERE slug = 'isaac-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกIxia' WHERE slug = 'ixia-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมJD Avalanche' WHERE slug = 'jd-avalanche-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกJack O Lantern' WHERE slug = 'jack-o-lantern-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกJade Phraxi' WHERE slug = 'jade-phraxi-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกJade Phraxi (อีเวนต์)' WHERE slug = 'jade-phraxi-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกJane Detective' WHERE slug = 'jane-detective-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกJin Pink Rock Star' WHERE slug = 'jin-pink-rock-star-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมJudith Summer' WHERE slug = 'judith-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมJudith Summer (อีเวนต์)' WHERE slug = 'judith-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมJustice and Glory - Liberty' WHERE slug = 'justice-and-glory-liberty-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมJustice and Glory - Rahenne' WHERE slug = 'justice-and-glory-rahenne-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมJustice and Glory - Volonte' WHERE slug = 'justice-and-glory-volonte-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกKalid Armor' WHERE slug = 'kalid-armor-helm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกKalid Armor (30 วัน)' WHERE slug = 'kalid-armor-helm-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมKane Halloween' WHERE slug = 'kane-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมKanhee Jakura' WHERE slug = 'kanhee-jakura-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมKiss Summer' WHERE slug = 'kiss-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมKiss Summer (อีเวนต์)' WHERE slug = 'kiss-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกKorean' WHERE slug = 'korean-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกKorean (30 วัน)' WHERE slug = 'korean-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLa Veiel Delikato' WHERE slug = 'la-veiel-delikato-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLada Summer' WHERE slug = 'lada-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLada Summer (อีเวนต์)' WHERE slug = 'lada-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLaura White Rock Star' WHERE slug = 'laura-white-rock-star-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLavender' WHERE slug = 'lavender-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLe Croise' WHERE slug = 'le-croise-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLe Croix' WHERE slug = 'le-croix-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากLe Lion Noble' WHERE slug = 'le-lion-noble-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLe Reve Bleu' WHERE slug = 'le-reve-bleu-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLe Sagittaire Optimiste' WHERE slug = 'le-sagittaire-optimiste-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLe Scorpio Mystery' WHERE slug = 'le-scorpio-mystery-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLe Taruro due Vovar' WHERE slug = 'le-taruro-due-vovar-helmet' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLeona Vampire' WHERE slug = 'leona-vampire-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLepigy Suit' WHERE slug = 'lepigy-suit-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLepigy Suit (30 วัน)' WHERE slug = 'lepigy-suit-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLinaria' WHERE slug = 'linaria-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLinaria (อีเวนต์)' WHERE slug = 'linaria-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLisa Avalanche' WHERE slug = 'lisa-avalanche-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLord-of-Death' WHERE slug = 'lord-of-death-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLord-of-Death (อีเวนต์)' WHERE slug = 'lord-of-death-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกLorraine Marine Look' WHERE slug = 'lorraine-marine-look-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLudin Summer' WHERE slug = 'ludin-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLudin Summer (อีเวนต์)' WHERE slug = 'ludin-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLynn Silver' WHERE slug = 'lynn-silver-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมLysette Halloween' WHERE slug = 'lysette-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกMabro Metis' WHERE slug = 'mabro-metis-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกMabro Peira' WHERE slug = 'mabro-peira-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกMagician' WHERE slug = 'magician-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกMagician (อีเวนต์)' WHERE slug = 'magician-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมMale Fighter Capitaine' WHERE slug = 'male-fighter-capitaine-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมMarado-Sun' WHERE slug = 'marado-sun-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมMary Summer' WHERE slug = 'mary-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมMary Summer (อีเวนต์)' WHERE slug = 'mary-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกMatrimonio' WHERE slug = 'matrimonio-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกMatrimonio (30 วัน)' WHERE slug = 'matrimonio-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปMechanics' WHERE slug = 'mechanics-cap' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากMedical' WHERE slug = 'medical-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้ากากMedical (อีเวนต์)' WHERE slug = 'medical-mask-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมMeister Lorch Summer' WHERE slug = 'meister-lorch-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมMisty Meadow' WHERE slug = 'misty-meadow-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมModern Fatima' WHERE slug = 'modern-fatima-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมModern Fatima (อีเวนต์)' WHERE slug = 'modern-fatima-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมMoon Halloween' WHERE slug = 'moon-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมMoon Halloween (อีเวนต์)' WHERE slug = 'moon-halloween-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกMusketeer Tricorn (30 วัน)' WHERE slug = 'musketeer-tricorn-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมNatalie Summer' WHERE slug = 'natalie-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมNatalie Summer (อีเวนต์)' WHERE slug = 'natalie-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมNatural' WHERE slug = 'natural-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมNatural (30 วัน)' WHERE slug = 'natural-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมNena School Look' WHERE slug = 'nena-school-look-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมNena School-Look (อีเวนต์)' WHERE slug = 'nena-school-look-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกOlga Patricia' WHERE slug = 'olga-patricia-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกOpera' WHERE slug = 'opera-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกOpera (30 วัน)' WHERE slug = 'opera-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมOrnella Summer' WHERE slug = 'ornella-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมOrnella Summer (อีเวนต์)' WHERE slug = 'ornella-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกOuting' WHERE slug = 'outing-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกOuting (30 วัน)' WHERE slug = 'outing-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกOutrageous' WHERE slug = 'outrageous-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกOutrageous (30 วัน)' WHERE slug = 'outrageous-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกParty' WHERE slug = 'party-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกParty (30 วัน)' WHERE slug = 'party-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมPegadilla Officer' WHERE slug = 'pegadilla-officer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมPegadilla Officer (อีเวนต์)' WHERE slug = 'pegadilla-officer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPericolo' WHERE slug = 'pericolo-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPericolo (30 วัน)' WHERE slug = 'pericolo-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPhi Rasto' WHERE slug = 'phi-rasto-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPicnic Dress' WHERE slug = 'picnic-dress-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPicnic Dress (30 วัน)' WHERE slug = 'picnic-dress-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPiernoente' WHERE slug = 'piernoente-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมPigeonne' WHERE slug = 'pigeonne-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPink Mouse' WHERE slug = 'pink-mouse-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPink Mouse (30 วัน)' WHERE slug = 'pink-mouse-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPink Mouse (อีเวนต์)' WHERE slug = 'pink-mouse-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมPink Vivace' WHERE slug = 'pink-vivace-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมPiore Rosso' WHERE slug = 'piore-rosso-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPirates' WHERE slug = 'pirates-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPlate' WHERE slug = 'plate-helm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPlate (30 วัน)' WHERE slug = 'plate-helm-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPumpkin Opera' WHERE slug = 'pumpkin-opera-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'มงกุฎPure White' WHERE slug = 'pure-white-crown' AND name_th IS NULL;
UPDATE items SET name_th = 'มงกุฎPure White (30 วัน)' WHERE slug = 'pure-white-crown-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมPurple Accent' WHERE slug = 'purple-accent-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกPurple Kids' WHERE slug = 'purple-kids-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRabbit' WHERE slug = 'rabbit-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRabbit (30 วัน)' WHERE slug = 'rabbit-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRabbit (7 วัน)' WHERE slug = 'rabbit-hat-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRaccoon' WHERE slug = 'raccoon-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRaccoon (30 วัน)' WHERE slug = 'raccoon-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRaid Phraxi' WHERE slug = 'raid-phraxi-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRainism' WHERE slug = 'rainism-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRainism (อีเวนต์)' WHERE slug = 'rainism-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRamiro Summer' WHERE slug = 'ramiro-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRamiro Summer (อีเวนต์)' WHERE slug = 'ramiro-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRed Bear' WHERE slug = 'red-bear-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRed Bear (30 วัน)' WHERE slug = 'red-bear-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRed Innocence' WHERE slug = 'red-innocence-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRed Innocence (อีเวนต์)' WHERE slug = 'red-innocence-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRed Liberte' WHERE slug = 'red-liberte-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRed Liberte (อีเวนต์)' WHERE slug = 'red-liberte-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRed Samurai (30 วัน)' WHERE slug = 'red-samurai-helmet-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRegimental Uniform' WHERE slug = 'regimental-uniform-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRegimental Uniform (30 วัน)' WHERE slug = 'regimental-uniform-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมResistance Caisse Summer' WHERE slug = 'resistance-caisse-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมResistance JD Winter' WHERE slug = 'resistance-jd-winter-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRevenant' WHERE slug = 'revenant-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRevenant (อีเวนต์)' WHERE slug = 'revenant-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRomantic Spring' WHERE slug = 'romantic-spring-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRosa Matrimonio (30 วัน)' WHERE slug = 'rosa-matrimonio-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRosa Pink Rock Star' WHERE slug = 'rosa-pink-rock-star-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRosaju' WHERE slug = 'rosaju-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRose Blanche' WHERE slug = 'rose-blanche-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRose Blanche (อีเวนต์)' WHERE slug = 'rose-blanche-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRose Patricia' WHERE slug = 'rose-patricia-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRosie Summer' WHERE slug = 'rosie-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRosie Summer (อีเวนต์)' WHERE slug = 'rosie-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRougeannoir' WHERE slug = 'rougeannoir-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRoundtop' WHERE slug = 'roundtop-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRoundtop (30 วัน)' WHERE slug = 'roundtop-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมRuby Summer' WHERE slug = 'ruby-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRudolph' WHERE slug = 'rudolph-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRudolph (30 วัน)' WHERE slug = 'rudolph-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกRuidestencia' WHERE slug = 'ruidestencia-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSage (30 วัน)' WHERE slug = 'sage-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSages' WHERE slug = 'sages-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSaint Blaue' WHERE slug = 'saint-blaue-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSaint Blaue' WHERE slug = 'saint-blaue-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSakura (30 วัน)' WHERE slug = 'sakura-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSalamander' WHERE slug = 'salamander-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSalamander (30 วัน)' WHERE slug = 'salamander-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSanta Barrel' WHERE slug = 'santa-barrel-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSanta' WHERE slug = 'santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSanta (30 วัน)' WHERE slug = 'santa-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมScarlet Innocence' WHERE slug = 'scarlet-innocence-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมScarlet Innocence (อีเวนต์)' WHERE slug = 'scarlet-innocence-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมScavenger Yeganeh Basic' WHERE slug = 'scavenger-yeganeh-basic-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมScavenger Yeganeh Basic (อีเวนต์)' WHERE slug = 'scavenger-yeganeh-basic-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSellarsarce Bariante' WHERE slug = 'sellarsarce-bariante-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSellarsarce Bariante (อีเวนต์)' WHERE slug = 'sellarsarce-bariante-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSergeant Barrel Summer Cap' WHERE slug = 'sergeant-barrel-summer-cap-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSergeant Barrel Summer Cap (อีเวนต์)' WHERE slug = 'sergeant-barrel-summer-cap-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSergeant Barrel Summer' WHERE slug = 'sergeant-barrel-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSergeant Barrel Summer (อีเวนต์)' WHERE slug = 'sergeant-barrel-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมShaggy' WHERE slug = 'shaggy-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมShaggy (30 วัน)' WHERE slug = 'shaggy-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกShaware Camis' WHERE slug = 'shaware-camis-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกShaware Camis (30 วัน)' WHERE slug = 'shaware-camis-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกShaware Camis (อีเวนต์)' WHERE slug = 'shaware-camis-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSheep-horn' WHERE slug = 'sheep-horn-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSheep-horn (30 วัน)' WHERE slug = 'sheep-horn-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSherry Halloween' WHERE slug = 'sherry-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมShort Brown' WHERE slug = 'short-brown-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมShort Brown (30 วัน)' WHERE slug = 'short-brown-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมShort' WHERE slug = 'short-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมShort (30 วัน)' WHERE slug = 'short-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSierra Summer' WHERE slug = 'sierra-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSilky White' WHERE slug = 'silky-white-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSilky White (อีเวนต์)' WHERE slug = 'silky-white-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSilverane' WHERE slug = 'silverane-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSilverane (อีเวนต์)' WHERE slug = 'silverane-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSirius Short' WHERE slug = 'sirius-short-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSnipers' WHERE slug = 'snipers-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSnowfield Witch' WHERE slug = 'snowfield-witch-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSonora' WHERE slug = 'sonora-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSpade' WHERE slug = 'spade-hair' AND name_th IS NULL;