-- Migration 057: Thai names batch 4/10
-- Generated: 2026-03-16T03:42:16.054Z

UPDATE items SET name_th = 'หมวกSteel Griffon' WHERE slug = 'steel-griffon-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมStylish Short' WHERE slug = 'stylish-short-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSugar Snow' WHERE slug = 'sugar-snow-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSweet Melody' WHERE slug = 'sweet-melody-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSwordman (30 วัน)' WHERE slug = 'swordman-helm-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSwordmans' WHERE slug = 'swordmans-helm' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSybis' WHERE slug = 'sybis-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมSybis (อีเวนต์)' WHERE slug = 'sybis-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSylphid' WHERE slug = 'sylphid-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกSylphid (30 วัน)' WHERE slug = 'sylphid-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกTempest of Chaos' WHERE slug = 'tempest-of-chaos-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมTemptation Rose' WHERE slug = 'temptation-rose-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมTerious' WHERE slug = 'terious-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมTerious (30 วัน)' WHERE slug = 'terious-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกTricorn' WHERE slug = 'tricorn-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกTrifolium' WHERE slug = 'trifolium-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'เขาTriumph' WHERE slug = 'triumph-horn' AND name_th IS NULL;
UPDATE items SET name_th = 'เขาTriumph (30 วัน)' WHERE slug = 'triumph-horn-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกTrooper (30 วัน)' WHERE slug = 'trooper-helm-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกTroopers' WHERE slug = 'troopers-helm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกTyr' WHERE slug = 'tyr-helm' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมUnbalanced' WHERE slug = 'unbalanced-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมUndercover Black Short' WHERE slug = 'undercover-black-short-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมUndercover Black Short (อีเวนต์)' WHERE slug = 'undercover-black-short-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมUndercover Short' WHERE slug = 'undercover-short-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมUndercover Short (อีเวนต์)' WHERE slug = 'undercover-short-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมValeria Santa' WHERE slug = 'valeria-santa-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมVan Summer' WHERE slug = 'van-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมVan Summer (อีเวนต์)' WHERE slug = 'van-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกVanessa Purple' WHERE slug = 'vanessa-purple-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกVariltorta' WHERE slug = 'variltorta-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมVendetta Vampire' WHERE slug = 'vendetta-vampire-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกVespanola Royal Guard' WHERE slug = 'vespanola-royal-guard-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมViator Blue' WHERE slug = 'viator-blue-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมViator Blue (อีเวนต์)' WHERE slug = 'viator-blue-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมViator Gold' WHERE slug = 'viator-gold-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมViator Gold (อีเวนต์)' WHERE slug = 'viator-gold-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมViki Summer' WHERE slug = 'viki-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมViki Summer (อีเวนต์)' WHERE slug = 'viki-summer-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมVincent Capitaine' WHERE slug = 'vincent-capitaine-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมViolet Summer' WHERE slug = 'violet-summer-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกVioleta' WHERE slug = 'violeta-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกVioleta (อีเวนต์)' WHERE slug = 'violeta-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมVivace' WHERE slug = 'vivace-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWave Vove' WHERE slug = 'wave-vove-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWedding' WHERE slug = 'wedding-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Alegrias' WHERE slug = 'white-alegrias-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Alegrias (30 วัน)' WHERE slug = 'white-alegrias-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Bear' WHERE slug = 'white-bear-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Bear (30 วัน)' WHERE slug = 'white-bear-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWhite Blossom' WHERE slug = 'white-blossom-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWhite Cosmos' WHERE slug = 'white-cosmos-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWhite Cosmos (อีเวนต์)' WHERE slug = 'white-cosmos-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Elegance' WHERE slug = 'white-elegance-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Elegance (อีเวนต์)' WHERE slug = 'white-elegance-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Liberte' WHERE slug = 'white-liberte-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Liberte (อีเวนต์)' WHERE slug = 'white-liberte-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Rose' WHERE slug = 'white-rose-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Rose (30 วัน)' WHERE slug = 'white-rose-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Santa' WHERE slug = 'white-santa-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWhite Vivid' WHERE slug = 'white-vivid-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWhite Wave' WHERE slug = 'white-wave-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWhite Wave (30 วัน)' WHERE slug = 'white-wave-hair-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWhite Wolf' WHERE slug = 'white-wolf-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWind of First' WHERE slug = 'wind-of-first-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมWind of First (อีเวนต์)' WHERE slug = 'wind-of-first-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกWitchs' WHERE slug = 'witchs-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกYeganehs' WHERE slug = 'yeganehs-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกYeti' WHERE slug = 'yeti-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกYeti (30 วัน)' WHERE slug = 'yeti-hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'วิกYounger Look' WHERE slug = 'younger-look-wig' AND name_th IS NULL;
UPDATE items SET name_th = 'วิกYounger Look (อีเวนต์)' WHERE slug = 'younger-look-wig-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมZaved Halloween' WHERE slug = 'zaved-halloween-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมZaved Halloween (อีเวนต์)' WHERE slug = 'zaved-halloween-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินArche -' WHERE slug = 'arche-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินBlack Diamond -' WHERE slug = 'black-diamond-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินCarpo -' WHERE slug = 'carpo-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินChessylite -' WHERE slug = 'chessylite-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินClenblaze - (30 วัน)' WHERE slug = 'clenblaze-lumin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินCoral -' WHERE slug = 'coral-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินEucanite -' WHERE slug = 'eucanite-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินEukelade -' WHERE slug = 'eukelade-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินFluorite - (3 วัน)' WHERE slug = 'fluorite-lumin-3-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินJade - (3 วัน)' WHERE slug = 'jade-lumin-3-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินKallichore -' WHERE slug = 'kallichore-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินKalyke -' WHERE slug = 'kalyke-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินKore -' WHERE slug = 'kore-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินKunzite - (3 วัน)' WHERE slug = 'kunzite-lumin-3-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินMolderbite - (30 วัน)' WHERE slug = 'molderbite-lumin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินOnyx -' WHERE slug = 'onyx-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินPailite - (30 วัน)' WHERE slug = 'pailite-lumin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Bloodstone -' WHERE slug = 'processed-bloodstone-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Garnet -' WHERE slug = 'processed-garnet-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Opal -' WHERE slug = 'processed-opal-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Pearl -' WHERE slug = 'processed-pearl-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Peridot -' WHERE slug = 'processed-peridot-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Tanzanite -' WHERE slug = 'processed-tanzanite-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Topaz -' WHERE slug = 'processed-topaz-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Turquoise -' WHERE slug = 'processed-turquoise-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินProcessed Zircon -' WHERE slug = 'processed-zircon-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินRutelquart - (30 วัน)' WHERE slug = 'rutelquart-lumin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSelenite -' WHERE slug = 'selenite-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSodalite - (30 วัน)' WHERE slug = 'sodalite-lumin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Fluorite -' WHERE slug = 'superior-fluorite-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Fluorite - (15 วัน)' WHERE slug = 'superior-fluorite-lumin-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Fluorite - (30 วัน)' WHERE slug = 'superior-fluorite-lumin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Fluorite - (60 วัน)' WHERE slug = 'superior-fluorite-lumin-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Fluorite - (7 วัน)' WHERE slug = 'superior-fluorite-lumin-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Jade -' WHERE slug = 'superior-jade-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Jade - (15 วัน)' WHERE slug = 'superior-jade-lumin-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Jade - (30 วัน)' WHERE slug = 'superior-jade-lumin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Jade - (60 วัน)' WHERE slug = 'superior-jade-lumin-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Jade - (7 วัน)' WHERE slug = 'superior-jade-lumin-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Kunzite -' WHERE slug = 'superior-kunzite-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Kunzite - (15 วัน)' WHERE slug = 'superior-kunzite-lumin-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Kunzite - (30 วัน)' WHERE slug = 'superior-kunzite-lumin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Kunzite - (60 วัน)' WHERE slug = 'superior-kunzite-lumin-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินSuperior Kunzite - (7 วัน)' WHERE slug = 'superior-kunzite-lumin-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมินTaaffeite -' WHERE slug = 'taaffeite-lumin' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทAbyss Arma' WHERE slug = 'abyss-arma-magic-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทAbyss Arma (อีเวนต์)' WHERE slug = 'abyss-arma-magic-scroll-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทAbyss Scroll' WHERE slug = 'abyss-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทAbyss Scroll (อีเวนต์)' WHERE slug = 'abyss-scroll-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทArmonia Grimoire' WHERE slug = 'armonia-grimoire' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทArmonia Grimoire (อีเวนต์)' WHERE slug = 'armonia-grimoire-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทChloes Wisdom' WHERE slug = 'chloes-wisdom' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทChloes Wisdom (อีเวนต์)' WHERE slug = 'chloes-wisdom-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทCrescemento Encyclopedia' WHERE slug = 'crescemento-encyclopedia' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทDeus Machina Grimoire' WHERE slug = 'deus-machina-grimoire' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทDeus Machina Grimoire (อีเวนต์)' WHERE slug = 'deus-machina-grimoire-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทDiary of Veronif' WHERE slug = 'diary-of-veronif' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทDiary of Veronif (อีเวนต์)' WHERE slug = 'diary-of-veronif-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทDivine Encyclopedia' WHERE slug = 'divine-encyclopedia' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทDivine Magic Book' WHERE slug = 'divine-magic-book' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทElite Experimental Encyclopedia' WHERE slug = 'elite-experimental-encyclopedia' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทElite Experimental' WHERE slug = 'elite-experimental-magic-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทElite Muertuors Book' WHERE slug = 'elite-muertuors-book' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทEncyclopedia' WHERE slug = 'encyclopedia' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทEncyclopedia (อีเวนต์)' WHERE slug = 'encyclopedia-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทEncyclopedia of Contract (7 วัน)' WHERE slug = 'encyclopedia-of-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทEnex Ethereal Grimoire' WHERE slug = 'enex-ethereal-grimoire' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทEvent Elite Muertuors Book' WHERE slug = 'event-elite-muertuors-book' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทEvent Muertuors Book' WHERE slug = 'event-muertuors-book' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทExperimental Encyclopedia' WHERE slug = 'experimental-encyclopedia' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทExperimental' WHERE slug = 'experimental-magic-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทIncomplete Chloes Wisdom' WHERE slug = 'incomplete-chloes-wisdom' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทKnowledge of Mechanism' WHERE slug = 'knowledge-of-mechanism' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทLegion Magic Book' WHERE slug = 'legion-magic-book' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทMagic Scroll of Wilbur' WHERE slug = 'magic-scroll-of-wilbur' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทMasterpiece Diary' WHERE slug = 'masterpiece-diary' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทMasterpiece Diary (อีเวนต์)' WHERE slug = 'masterpiece-diary-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทMasterpiece Encyclopedia' WHERE slug = 'masterpiece-encyclopedia' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทMasterpiece Encyclopedia (อีเวนต์)' WHERE slug = 'masterpiece-encyclopedia-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทMuertuors Book' WHERE slug = 'muertuors-book' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทProspe Encyclopedia' WHERE slug = 'prospe-encyclopedia' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทProspe' WHERE slug = 'prospe-magic-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทRefined Vespanola' WHERE slug = 'refined-vespanola-magic-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทTheory of Lawrence' WHERE slug = 'theory-of-lawrence' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทTyrants Order Grimoire' WHERE slug = 'tyrants-order-grimoire' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทTyrants Order Grimoire (อีเวนต์)' WHERE slug = 'tyrants-order-grimoire-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทValeron' WHERE slug = 'valeron-magic-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทValeron (อีเวนต์)' WHERE slug = 'valeron-magic-scroll-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทVespanola Pioneer Support Magic Book' WHERE slug = 'vespanola-pioneer-support-magic-book' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทWitch Craft' WHERE slug = 'witch-craft' AND name_th IS NULL;
UPDATE items SET name_th = 'ม้วนเวทWitch Craft (อีเวนต์)' WHERE slug = 'witch-craft-event' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ม้วนเวทEnex Ethereal Grimoire' WHERE slug = 'event-enex-ethereal-grimoire' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2019 Christmas Blessing' WHERE slug = '2019-christmas-blessing-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2019 Halloween' WHERE slug = '2019-halloween-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2020 Halloween' WHERE slug = '2020-halloween-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2020 New Years' WHERE slug = '2020-new-years-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2021 Halloween' WHERE slug = '2021-halloween-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAltria Pioneers' WHERE slug = 'altria-pioneers-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDonators (30 วัน)' WHERE slug = 'donators-medal-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDonators (7 วัน)' WHERE slug = 'donators-medal-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ตราEldritch' WHERE slug = 'eldritch-mark' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGE 15th Anniversary' WHERE slug = 'ge-15th-anniversary-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGE 16th Anniversary' WHERE slug = 'ge-16th-anniversary-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGE 19th Anniversary Commemorative' WHERE slug = 'ge-19th-anniversary-commemorative-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGEs 12th Anniversary' WHERE slug = 'ges-12th-anniversary-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGEs 13rd Anniversary' WHERE slug = 'ges-13rd-anniversary-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGEs 14th Anniversary' WHERE slug = 'ges-14th-anniversary-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHomunculus' WHERE slug = 'homunculus-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMerit' WHERE slug = 'merit-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNew Pioneer (30 วัน)' WHERE slug = 'new-pioneer-medal-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSpecial GE 19th Anniversary Commemorative' WHERE slug = 'special-ge-19th-anniversary-commemorative-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSteam GE 3rd Anniversary' WHERE slug = 'steam-ge-3rd-anniversary-medal' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Abyss Door' WHERE slug = 'spirit-card-abyss-door' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Adelina the Pirate' WHERE slug = 'spirit-card-adelina-the-pirate' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Alchemist Zaved' WHERE slug = 'spirit-card-alchemist-zaved' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ancient Golem Talos' WHERE slug = 'spirit-card-ancient-golem-talos' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ankylosaurus' WHERE slug = 'spirit-card-ankylosaurus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Apatosaurus' WHERE slug = 'spirit-card-apatosaurus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Arctic Bear' WHERE slug = 'spirit-card-arctic-bear' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Autobaron' WHERE slug = 'spirit-card-autobaron' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Automaton' WHERE slug = 'spirit-card-automaton' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Bacchanalia' WHERE slug = 'spirit-card-bacchanalia' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Baron Hunter Moon' WHERE slug = 'spirit-card-baron-hunter-moon' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Belith' WHERE slug = 'spirit-card-belith' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Bigfoot' WHERE slug = 'spirit-card-bigfoot' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Breeze' WHERE slug = 'spirit-card-breeze' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Bribantra' WHERE slug = 'spirit-card-bribantra' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Brontes' WHERE slug = 'spirit-card-brontes' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Brute' WHERE slug = 'spirit-card-brute' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Capybara' WHERE slug = 'spirit-card-capybara' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Cheddare' WHERE slug = 'spirit-card-cheddare' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Cherlyn' WHERE slug = 'spirit-card-cherlyn' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Chrysalis' WHERE slug = 'spirit-card-chrysalis' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Clover' WHERE slug = 'spirit-card-clover' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Cockatrice Chilly' WHERE slug = 'spirit-card-cockatrice-chilly' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Cockatrice Flame' WHERE slug = 'spirit-card-cockatrice-flame' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Cockatrice Shocky' WHERE slug = 'spirit-card-cockatrice-shocky' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Colony' WHERE slug = 'spirit-card-colony' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Cragen' WHERE slug = 'spirit-card-cragen' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Cursed Dekaravia' WHERE slug = 'spirit-card-cursed-dekaravia' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Cyclops' WHERE slug = 'spirit-card-cyclops' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Death Goddess, Giltine' WHERE slug = 'spirit-card-death-goddess-giltine' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Deathgloshe' WHERE slug = 'spirit-card-deathgloshe' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Deceth' WHERE slug = 'spirit-card-deceth' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Diamond' WHERE slug = 'spirit-card-diamond' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Dilos Latemn' WHERE slug = 'spirit-card-dilos-latemn' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Dinodon' WHERE slug = 'spirit-card-dinodon' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Doppelganger Type 3' WHERE slug = 'spirit-card-doppelganger-type-3' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Dorol' WHERE slug = 'spirit-card-dorol' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Dr. Truman' WHERE slug = 'spirit-card-dr-truman' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Dullahan' WHERE slug = 'spirit-card-dullahan' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Eagle Head' WHERE slug = 'spirit-card-eagle-head' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Elbiote' WHERE slug = 'spirit-card-elbiote' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Elcinos' WHERE slug = 'spirit-card-elcinos' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Eliigo' WHERE slug = 'spirit-card-eliigo' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Elmorc' WHERE slug = 'spirit-card-elmorc' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Eltetah' WHERE slug = 'spirit-card-eltetah' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Eripmav' WHERE slug = 'spirit-card-eripmav' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Fallen Violante' WHERE slug = 'spirit-card-fallen-violante' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Fencer Master, Sorscha' WHERE slug = 'spirit-card-fencer-master-sorscha' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Fire Phobitan' WHERE slug = 'spirit-card-fire-phobitan' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Flealouse' WHERE slug = 'spirit-card-flealouse' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Freya' WHERE slug = 'spirit-card-freya' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Fritz' WHERE slug = 'spirit-card-fritz' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Gahbirus' WHERE slug = 'spirit-card-gahbirus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ghost Bird Wed' WHERE slug = 'spirit-card-ghost-bird-wed' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Giganotosaurus' WHERE slug = 'spirit-card-giganotosaurus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Gimlet' WHERE slug = 'spirit-card-gimlet' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Goldgaras' WHERE slug = 'spirit-card-goldgaras' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Gorgon Shield' WHERE slug = 'spirit-card-gorgon-shield' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Great Seer' WHERE slug = 'spirit-card-great-seer' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Greed' WHERE slug = 'spirit-card-greed' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Grim Ripper' WHERE slug = 'spirit-card-grim-ripper' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Heart' WHERE slug = 'spirit-card-heart' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Hellswine' WHERE slug = 'spirit-card-hellswine' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Hill Giant' WHERE slug = 'spirit-card-hill-giant' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Holy Angel Andre' WHERE slug = 'spirit-card-holy-angel-andre' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Hungry Ogjeff' WHERE slug = 'spirit-card-hungry-ogjeff' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ice Phobitan' WHERE slug = 'spirit-card-ice-phobitan' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Inferno Sekhmet' WHERE slug = 'spirit-card-inferno-sekhmet' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Jack the Engineer' WHERE slug = 'spirit-card-jack-the-engineer' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Jack-o-Lantern' WHERE slug = 'spirit-card-jack-o-lantern' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Jurgen Furholden' WHERE slug = 'spirit-card-jurgen-furholden' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Key Holder' WHERE slug = 'spirit-card-key-holder' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Kiss Fluke' WHERE slug = 'spirit-card-kiss-fluke' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Kranus' WHERE slug = 'spirit-card-kranus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] LNY Rabbit' WHERE slug = 'spirit-card-lny-rabbit' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Lavid' WHERE slug = 'spirit-card-lavid' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Lightning Phobitan' WHERE slug = 'spirit-card-lightning-phobitan' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Linker Master, Winona' WHERE slug = 'spirit-card-linker-master-winona' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Lust' WHERE slug = 'spirit-card-lust' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Lust Witch' WHERE slug = 'spirit-card-lust-witch' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Machina Evil' WHERE slug = 'spirit-card-machina-evil' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Madeira' WHERE slug = 'spirit-card-madeira' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Martial Bear' WHERE slug = 'spirit-card-martial-bear' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Masquerade' WHERE slug = 'spirit-card-masquerade' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Mind Argus' WHERE slug = 'spirit-card-mind-argus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Montoro' WHERE slug = 'spirit-card-montoro' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Moon Knight' WHERE slug = 'spirit-card-moon-knight' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Moving Rock' WHERE slug = 'spirit-card-moving-rock' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Navas the Succubus' WHERE slug = 'spirit-card-navas-the-succubus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Nena the Demigod' WHERE slug = 'spirit-card-nena-the-demigod' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Nephthys' WHERE slug = 'spirit-card-nephthys' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Norich' WHERE slug = 'spirit-card-norich' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Oannes' WHERE slug = 'spirit-card-oannes' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Octopus' WHERE slug = 'spirit-card-octopus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ogre Assassin' WHERE slug = 'spirit-card-ogre-assassin' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ogre Avenger' WHERE slug = 'spirit-card-ogre-avenger' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ogre Bandit' WHERE slug = 'spirit-card-ogre-bandit' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ogre Defender' WHERE slug = 'spirit-card-ogre-defender' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ogre Mage' WHERE slug = 'spirit-card-ogre-mage' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ogre Plunderer' WHERE slug = 'spirit-card-ogre-plunderer' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ogre Predator' WHERE slug = 'spirit-card-ogre-predator' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ogre Shooter' WHERE slug = 'spirit-card-ogre-shooter' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Oscuras' WHERE slug = 'spirit-card-oscuras' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Phantom Maderia' WHERE slug = 'spirit-card-phantom-maderia' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Plateauanchor' WHERE slug = 'spirit-card-plateauanchor' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Queen Hamaan' WHERE slug = 'spirit-card-queen-hamaan' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Queen Novia' WHERE slug = 'spirit-card-queen-novia' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Quinnitula' WHERE slug = 'spirit-card-quinnitula' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Rabbit' WHERE slug = 'spirit-card-rabbit' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Reckless Emilia' WHERE slug = 'spirit-card-reckless-emilia' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Renauld' WHERE slug = 'spirit-card-renauld' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Rescue Knight Melisa' WHERE slug = 'spirit-card-rescue-knight-melisa' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ringmaster Louis Arsene' WHERE slug = 'spirit-card-ringmaster-louis-arsene' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Ruincruger' WHERE slug = 'spirit-card-ruincruger' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Sauterelle' WHERE slug = 'spirit-card-sauterelle' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Savior Ornella' WHERE slug = 'spirit-card-savior-ornella' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Sergeant Barrol' WHERE slug = 'spirit-card-sergeant-barrol' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Servitor' WHERE slug = 'spirit-card-servitor' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Sheol of Desire' WHERE slug = 'spirit-card-sheol-of-desire' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Sierra the Witch' WHERE slug = 'spirit-card-sierra-the-witch' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Sky' WHERE slug = 'spirit-card-sky' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Sloth' WHERE slug = 'spirit-card-sloth' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Sniper Grace' WHERE slug = 'spirit-card-sniper-grace' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Soltiegus' WHERE slug = 'spirit-card-soltiegus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Soul Mothtein' WHERE slug = 'spirit-card-soul-mothtein' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Spade' WHERE slug = 'spirit-card-spade' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Spiked Rock' WHERE slug = 'spirit-card-spiked-rock' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Stars Guardian, Atlas' WHERE slug = 'spirit-card-stars-guardian-atlas' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Stars Judge, Chloe' WHERE slug = 'spirit-card-stars-judge-chloe' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Stars Messenger, Orden' WHERE slug = 'spirit-card-stars-messenger-orden' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Stars Pioneer, Stella' WHERE slug = 'spirit-card-stars-pioneer-stella' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Stars Surveillant, Charlotte' WHERE slug = 'spirit-card-stars-surveillant-charlotte' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Steel Skin Divino' WHERE slug = 'spirit-card-steel-skin-divino' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Stegosaurus' WHERE slug = 'spirit-card-stegosaurus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Stone Cortes' WHERE slug = 'spirit-card-stone-cortes' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Styracosaurus' WHERE slug = 'spirit-card-styracosaurus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Sylmaris' WHERE slug = 'spirit-card-sylmaris' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Tendercore' WHERE slug = 'spirit-card-tendercore' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Tentaceratops' WHERE slug = 'spirit-card-tentaceratops' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Tesserae Pharrel' WHERE slug = 'spirit-card-tesserae-pharrel' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Testormento' WHERE slug = 'spirit-card-testormento' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] The Harvester' WHERE slug = 'spirit-card-the-harvester' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Thief Captain Capri' WHERE slug = 'spirit-card-thief-captain-capri' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Thunder Einschiever' WHERE slug = 'spirit-card-thunder-einschiever' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Time and Space Portero' WHERE slug = 'spirit-card-time-and-space-portero' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Torchere' WHERE slug = 'spirit-card-torchere' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Toy Lloyd' WHERE slug = 'spirit-card-toy-lloyd' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Toy Sasha' WHERE slug = 'spirit-card-toy-sasha' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Toy Victor' WHERE slug = 'spirit-card-toy-victor' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Triceratops' WHERE slug = 'spirit-card-triceratops' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Triglohound' WHERE slug = 'spirit-card-triglohound' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Trilinear' WHERE slug = 'spirit-card-trilinear' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Tyrannosaurus' WHERE slug = 'spirit-card-tyrannosaurus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Undertaker' WHERE slug = 'spirit-card-undertaker' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Uraeus' WHERE slug = 'spirit-card-uraeus' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Velociraptor' WHERE slug = 'spirit-card-velociraptor' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Violante' WHERE slug = 'spirit-card-violante' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Violent Gerero' WHERE slug = 'spirit-card-violent-gerero' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Viscount Montoro' WHERE slug = 'spirit-card-viscount-montoro' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Water Maiden Aisha' WHERE slug = 'spirit-card-water-maiden-aisha' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Werewolf Assaulter' WHERE slug = 'spirit-card-werewolf-assaulter' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Werewolf Defender' WHERE slug = 'spirit-card-werewolf-defender' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Werewolf Gunner' WHERE slug = 'spirit-card-werewolf-gunner' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Werewolf Scout' WHERE slug = 'spirit-card-werewolf-scout' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] White Dragon' WHERE slug = 'spirit-card-white-dragon' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Wolfriner' WHERE slug = 'spirit-card-wolfriner' AND name_th IS NULL;
UPDATE items SET name_th = '[Spirit Card] Wrath' WHERE slug = 'spirit-card-wrath' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนABS' WHERE slug = 'abs-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนANE' WHERE slug = 'ane-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAbracadabra' WHERE slug = 'abracadabra-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAbyss Flare' WHERE slug = 'abyss-flare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAbyss Temptation' WHERE slug = 'abyss-temptation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAccelerando' WHERE slug = 'accelerando-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนเร่งความเร็ว' WHERE slug = 'acceleration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนยิงแม่น' WHERE slug = 'accuracy-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAcedia' WHERE slug = 'acedia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAcheron' WHERE slug = 'acheron-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAcid Stalker' WHERE slug = 'acid-stalker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAcrobatic Evil Slice' WHERE slug = 'acrobatic-evil-slice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAcrophobia' WHERE slug = 'acrophobia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAdagio' WHERE slug = 'adagio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAdditional Buster' WHERE slug = 'additional-buster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนเวทเพิ่มเติม' WHERE slug = 'additional-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAdditional Spire' WHERE slug = 'additional-spire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAdditional Spirit' WHERE slug = 'additional-spirit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนฝึกฝนเพิ่มเติม' WHERE slug = 'additional-training-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAdios' WHERE slug = 'adios-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAdrenaline Fever' WHERE slug = 'adrenaline-fever-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAeve' WHERE slug = 'aeve-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAgil' WHERE slug = 'agil-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAim Forward' WHERE slug = 'aim-forward-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAir Burst Dive' WHERE slug = 'air-burst-dive-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAkesia' WHERE slug = 'akesia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAllegretto' WHERE slug = 'allegretto-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนอัลเตอร์ อีโก้' WHERE slug = 'alter-ego-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAmita Break' WHERE slug = 'amita-break-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAmplify' WHERE slug = 'amplify-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAnemone' WHERE slug = 'anemone-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAngel Brake' WHERE slug = 'angel-brake-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAnkle Shot' WHERE slug = 'ankle-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAnti-Magic Shell' WHERE slug = 'anti-magic-shell-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนApocalypse' WHERE slug = 'apocalypse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAppassionato' WHERE slug = 'appassionato-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAppel' WHERE slug = 'appel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAppetit' WHERE slug = 'appetit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArarat Summon' WHERE slug = 'ararat-summon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArch Spear' WHERE slug = 'arch-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArcturus Advent' WHERE slug = 'arcturus-advent-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArik' WHERE slug = 'arik-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArme Bullet' WHERE slug = 'arme-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArme Piste' WHERE slug = 'arme-piste-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArmor Break Shot' WHERE slug = 'armor-break-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArmor Crasher' WHERE slug = 'armor-crasher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAround Excision' WHERE slug = 'around-excision-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArounding' WHERE slug = 'arounding-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArroar' WHERE slug = 'arroar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArrow of Mind' WHERE slug = 'arrow-of-mind-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAsalto' WHERE slug = 'asalto-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAsche' WHERE slug = 'asche-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAsesinato' WHERE slug = 'asesinato-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAssassinate' WHERE slug = 'assassinate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAssilio' WHERE slug = 'assilio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAsura' WHERE slug = 'asura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAter Sagitta' WHERE slug = 'ater-sagitta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAtomic Crazy Rush' WHERE slug = 'atomic-crazy-rush-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAtomic Phoenix Bomber' WHERE slug = 'atomic-phoenix-bomber-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAtomic Slash' WHERE slug = 'atomic-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAtomic Tiger-Smash' WHERE slug = 'atomic-tiger-smash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAtomic White Tiger Strikes' WHERE slug = 'atomic-white-tiger-strikes-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAttacher Bullet' WHERE slug = 'attacher-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAttaque Compose' WHERE slug = 'attaque-compose-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAurel Schabel' WHERE slug = 'aurel-schabel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAurel Shield' WHERE slug = 'aurel-shield-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAurel Shock' WHERE slug = 'aurel-shock-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAuto Baron' WHERE slug = 'auto-baron-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAvalanche' WHERE slug = 'avalanche-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBack Dash Encounter' WHERE slug = 'back-dash-encounter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBack Over-range Shot' WHERE slug = 'back-over-range-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBack Rolling Fire' WHERE slug = 'back-rolling-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBack Slider' WHERE slug = 'back-slider-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBack Stab' WHERE slug = 'back-stab-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBack Step Inferno' WHERE slug = 'back-step-inferno-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBack of the Dead' WHERE slug = 'back-of-the-dead-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBaile Soleares' WHERE slug = 'baile-soleares-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBaile de Guerra' WHERE slug = 'baile-de-guerra-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBalestra Fente' WHERE slug = 'balestra-fente-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBarrage Shots' WHERE slug = 'barrage-shots-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBarrier of Ogma' WHERE slug = 'barrier-of-ogma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBarsel' WHERE slug = 'barsel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBartor' WHERE slug = 'bartor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBattle Cook' WHERE slug = 'battle-cook-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBattle Smash' WHERE slug = 'battle-smash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBattle Smith' WHERE slug = 'battle-smith-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBayonet Assault' WHERE slug = 'bayonet-assault-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBeast' WHERE slug = 'beast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBeginners Luck' WHERE slug = 'beginners-luck-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBelladonna' WHERE slug = 'belladonna-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBelloys Hell Fire' WHERE slug = 'belloys-hell-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBenary' WHERE slug = 'benary-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBenedictus' WHERE slug = 'benedictus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBeyond Natural' WHERE slug = 'beyond-natural-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBig Bang' WHERE slug = 'big-bang-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBigtima' WHERE slug = 'bigtima-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBionet Bullet' WHERE slug = 'bionet-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBirdfall' WHERE slug = 'birdfall-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlade Stomp' WHERE slug = 'blade-stomp-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlame Smash' WHERE slug = 'blame-smash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlanche' WHERE slug = 'blanche-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlandir Cadena' WHERE slug = 'blandir-cadena-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlast Shot' WHERE slug = 'blast-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlast Stinger' WHERE slug = 'blast-stinger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlazing Burster' WHERE slug = 'blazing-burster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlazing Pillar' WHERE slug = 'blazing-pillar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlazing Shot' WHERE slug = 'blazing-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlazing Uppercut' WHERE slug = 'blazing-uppercut-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBless' WHERE slug = 'bless-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlind Flash' WHERE slug = 'blind-flash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlindly' WHERE slug = 'blindly-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlink Blow' WHERE slug = 'blink-blow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlitz Rage' WHERE slug = 'blitz-rage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlizzard' WHERE slug = 'blizzard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlood Curse' WHERE slug = 'blood-curse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlood Navy Duo' WHERE slug = 'blood-navy-duo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlood Stain' WHERE slug = 'blood-stain-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlood of Shadow' WHERE slug = 'blood-of-shadow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Dagger' WHERE slug = 'bloody-dagger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Horizon' WHERE slug = 'bloody-horizon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Overdrive' WHERE slug = 'bloody-overdrive-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Overrange Shot' WHERE slug = 'bloody-overrange-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Rain' WHERE slug = 'bloody-rain-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Weapon' WHERE slug = 'bloody-weapon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloquear' WHERE slug = 'bloquear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlow Cannon' WHERE slug = 'blow-cannon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlow Impact' WHERE slug = 'blow-impact-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlow Slash' WHERE slug = 'blow-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlowback' WHERE slug = 'blowback-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlue Dragon Heel-kick' WHERE slug = 'blue-dragon-heel-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlue Dragon Rising' WHERE slug = 'blue-dragon-rising-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBol Rune' WHERE slug = 'bol-rune-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBola Shot' WHERE slug = 'bola-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBolt Sequence' WHERE slug = 'bolt-sequence-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBondage' WHERE slug = 'bondage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBone Crash' WHERE slug = 'bone-crash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBooby Trap' WHERE slug = 'booby-trap-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBoost Magic' WHERE slug = 'boost-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBrandish' WHERE slug = 'brandish-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBreaking Storm' WHERE slug = 'breaking-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBreath Of Fire' WHERE slug = 'breath-of-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBreath of Flame' WHERE slug = 'breath-of-flame-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBreath of Hyunmoo' WHERE slug = 'breath-of-hyunmoo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBreathing' WHERE slug = 'breathing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBreathless Violation' WHERE slug = 'breathless-violation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBristian Gatling' WHERE slug = 'bristian-gatling-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBristian Roulette' WHERE slug = 'bristian-roulette-ring' AND name_th IS NULL;