-- Migration 058: Thai names batch 5/10
-- Generated: 2026-03-16T03:42:16.054Z

UPDATE items SET name_th = 'แหวนBrondge' WHERE slug = 'brondge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBuen tiro' WHERE slug = 'buen-tiro-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBuild Regeneration Ward' WHERE slug = 'build-regeneration-ward-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBuild Siegecannon-Turret' WHERE slug = 'build-siegecannon-turret-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBullet Slug' WHERE slug = 'bullet-slug-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBullet Spear' WHERE slug = 'bullet-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBullet Transmute' WHERE slug = 'bullet-transmute-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBump the Ripper' WHERE slug = 'bump-the-ripper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBurning Hands' WHERE slug = 'burning-hands-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBurst Flower' WHERE slug = 'burst-flower-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBurst Shot' WHERE slug = 'burst-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBust Grenade' WHERE slug = 'bust-grenade-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBuster Cannon Construction' WHERE slug = 'buster-cannon-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนButterfly' WHERE slug = 'butterfly-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCabo' WHERE slug = 'cabo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCaelum Frondesco' WHERE slug = 'caelum-frondesco-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCaida' WHERE slug = 'caida-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCall Giant' WHERE slug = 'call-giant-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCall Hare' WHERE slug = 'call-hare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCall Reve' WHERE slug = 'call-reve-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCall Snow Golem' WHERE slug = 'call-snow-golem-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCall Turrydog' WHERE slug = 'call-turrydog-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCall Zeppelin' WHERE slug = 'call-zeppelin-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCalmese' WHERE slug = 'calmese-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCaltrop' WHERE slug = 'caltrop-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCalvion' WHERE slug = 'calvion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCalypso' WHERE slug = 'calypso-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCamouflage' WHERE slug = 'camouflage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCanis' WHERE slug = 'canis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCannon Ball Charging' WHERE slug = 'cannon-ball-charging-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCannon Bumper' WHERE slug = 'cannon-bumper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCannon Shell Falling' WHERE slug = 'cannon-shell-falling-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCannon Shot' WHERE slug = 'cannon-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCannon Swing' WHERE slug = 'cannon-swing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCannon-Turret Construction' WHERE slug = 'cannon-turret-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCard Manipulation' WHERE slug = 'card-manipulation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCaritas' WHERE slug = 'caritas-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCarnage' WHERE slug = 'carnage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCarya' WHERE slug = 'carya-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCassina Kistlet' WHERE slug = 'cassina-kistlet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCast Net' WHERE slug = 'cast-net-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCastle Crusher' WHERE slug = 'castle-crusher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCataegis' WHERE slug = 'cataegis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCatatumbo' WHERE slug = 'catatumbo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCats Eye' WHERE slug = 'cats-eye-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCent-Ennui' WHERE slug = 'cent-ennui-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCentella' WHERE slug = 'centella-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChain Direction' WHERE slug = 'chain-direction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChain Lightning / Lightning Sphere' WHERE slug = 'chain-lightning-lightning-sphere-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChain of Elimination' WHERE slug = 'chain-of-elimination-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChanged Position' WHERE slug = 'changed-position-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCharge' WHERE slug = 'charge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCharged Bolt' WHERE slug = 'charged-bolt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCharged Bull' WHERE slug = 'charged-bull-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCharging Shot' WHERE slug = 'charging-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChartio' WHERE slug = 'chartio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCheer Up' WHERE slug = 'cheer-up-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChemical ElectricShock' WHERE slug = 'chemical-electricshock-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChemical Explosion' WHERE slug = 'chemical-explosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChemical Infection' WHERE slug = 'chemical-infection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChemical Protection' WHERE slug = 'chemical-protection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChilling Soul' WHERE slug = 'chilling-soul-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChilling Touch' WHERE slug = 'chilling-touch-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนChromatic' WHERE slug = 'chromatic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCiento Penetrar' WHERE slug = 'ciento-penetrar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCircle Frost' WHERE slug = 'circle-frost-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCircle Penetration' WHERE slug = 'circle-penetration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCircle Shot' WHERE slug = 'circle-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCircle of Flow' WHERE slug = 'circle-of-flow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClaw Back Step' WHERE slug = 'claw-back-step-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClayboute Shot' WHERE slug = 'clayboute-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClaymore' WHERE slug = 'claymore-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClean Up' WHERE slug = 'clean-up-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCleaning Time' WHERE slug = 'cleaning-time-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCleave' WHERE slug = 'cleave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClimax' WHERE slug = 'climax-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClincher' WHERE slug = 'clincher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClose Quarter Combat' WHERE slug = 'close-quarter-combat-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClose Quarter Weapon Combat' WHERE slug = 'close-quarter-weapon-combat-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCluster Bullet' WHERE slug = 'cluster-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCollen' WHERE slug = 'collen-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนColossus Break' WHERE slug = 'colossus-break-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนComita' WHERE slug = 'comita-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCommand - Elimination' WHERE slug = 'command-elimination-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCommand - Intensive Fire' WHERE slug = 'command-intensive-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCommunion' WHERE slug = 'communion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนComplete Protection' WHERE slug = 'complete-protection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนComposee Botter' WHERE slug = 'composee-botter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCon Fuoco' WHERE slug = 'con-fuoco-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCon Impeto' WHERE slug = 'con-impeto-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนConcentrate Fire' WHERE slug = 'concentrate-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนConcentration' WHERE slug = 'concentration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนConcentration Ward Construction' WHERE slug = 'concentration-ward-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนConfidibus' WHERE slug = 'confidibus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนConfusion' WHERE slug = 'confusion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนConsilium' WHERE slug = 'consilium-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนConsolidation' WHERE slug = 'consolidation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนContract' WHERE slug = 'contract-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนContre Attaques' WHERE slug = 'contre-attaques-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCooperate Shot' WHERE slug = 'cooperate-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCorona' WHERE slug = 'corona-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCorriente Estella' WHERE slug = 'corriente-estella-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCorta' WHERE slug = 'corta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCortar en Recta' WHERE slug = 'cortar-en-recta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCorte Achilles' WHERE slug = 'corte-achilles-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCoruscation' WHERE slug = 'coruscation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCounter Bullet' WHERE slug = 'counter-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCounter' WHERE slug = 'counter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCounter Step' WHERE slug = 'counter-step-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCounter-buster' WHERE slug = 'counter-buster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCovering Fire' WHERE slug = 'covering-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrazy Dance' WHERE slug = 'crazy-dance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrazy Rhapsody' WHERE slug = 'crazy-rhapsody-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrescendo' WHERE slug = 'crescendo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrescent Firing' WHERE slug = 'crescent-firing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrescent Kick' WHERE slug = 'crescent-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrescent Moon' WHERE slug = 'crescent-moon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrimson Crescent' WHERE slug = 'crimson-crescent-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrispo' WHERE slug = 'crispo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCritical Disease' WHERE slug = 'critical-disease-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCroix Fente' WHERE slug = 'croix-fente-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCross Penetration' WHERE slug = 'cross-penetration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCross Slash - Mifuyu' WHERE slug = 'cross-slash-mifuyu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCross Slash' WHERE slug = 'cross-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrouching Kick' WHERE slug = 'crouching-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrown Lloyd Control' WHERE slug = 'crown-lloyd-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCruel' WHERE slug = 'cruel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCruelmente' WHERE slug = 'cruelmente-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrystal Prison' WHERE slug = 'crystal-prison-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCul-de-sac' WHERE slug = 'cul-de-sac-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCure All' WHERE slug = 'cure-all-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCure' WHERE slug = 'cure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCurse' WHERE slug = 'curse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCut and Thrust' WHERE slug = 'cut-and-thrust-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCut upper' WHERE slug = 'cut-upper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCutting Earth' WHERE slug = 'cutting-earth-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCutting Wound' WHERE slug = 'cutting-wound-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDagger Felt' WHERE slug = 'dagger-felt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDagger Polish' WHERE slug = 'dagger-polish-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDagger Venenosa' WHERE slug = 'dagger-venenosa-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDance With Cutlass' WHERE slug = 'dance-with-cutlass-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDance of Death' WHERE slug = 'dance-of-death-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDancing Revolvers' WHERE slug = 'dancing-revolvers-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDark Judgment' WHERE slug = 'dark-judgment-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDark Penalty' WHERE slug = 'dark-penalty-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDark Spear' WHERE slug = 'dark-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDead Zone' WHERE slug = 'dead-zone-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeadly Chain / Death, from Cold' WHERE slug = 'deadly-chain-death-from-cold-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeadly Infinitum' WHERE slug = 'deadly-infinitum-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDealing' WHERE slug = 'dealing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Blow' WHERE slug = 'death-blow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Crest' WHERE slug = 'death-crest-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Cut' WHERE slug = 'death-cut-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Ninjutsu' WHERE slug = 'death-ninjutsu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Rain' WHERE slug = 'death-rain-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Sentence' WHERE slug = 'death-sentence-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Shadow Flash' WHERE slug = 'death-shadow-flash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Stunt' WHERE slug = 'death-stunt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDecapitate' WHERE slug = 'decapitate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeception' WHERE slug = 'deception-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDecision' WHERE slug = 'decision-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeep Sleep' WHERE slug = 'deep-sleep-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeep Sting' WHERE slug = 'deep-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeep Straight' WHERE slug = 'deep-straight-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDefend Mode' WHERE slug = 'defend-mode-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDefensive Tool' WHERE slug = 'defensive-tool-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDefiant Aura' WHERE slug = 'defiant-aura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeliberate Shot' WHERE slug = 'deliberate-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDelphinium' WHERE slug = 'delphinium-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeluge' WHERE slug = 'deluge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDemagical' WHERE slug = 'demagical-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDemental' WHERE slug = 'demental-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDemonic Discharge' WHERE slug = 'demonic-discharge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDemonio Mano' WHERE slug = 'demonio-mano-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDephysical' WHERE slug = 'dephysical-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDepoison' WHERE slug = 'depoison-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeprave' WHERE slug = 'deprave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeresist' WHERE slug = 'deresist-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDescent of Inuit' WHERE slug = 'descent-of-inuit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDesperados' WHERE slug = 'desperados-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDestination' WHERE slug = 'destination-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDestino' WHERE slug = 'destino-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDestroyer Mode' WHERE slug = 'destroyer-mode-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDestruction' WHERE slug = 'destruction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDestruido' WHERE slug = 'destruido-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDetection' WHERE slug = 'detection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDetection Ward Construction' WHERE slug = 'detection-ward-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDetonate' WHERE slug = 'detonate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDevastator' WHERE slug = 'devastator-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDevil Brake' WHERE slug = 'devil-brake-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDevolver Ataque' WHERE slug = 'devolver-ataque-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDiamond Sphere' WHERE slug = 'diamond-sphere-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDimension Tear' WHERE slug = 'dimension-tear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDimension Territory' WHERE slug = 'dimension-territory-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDiscordia' WHERE slug = 'discordia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDispel Magic' WHERE slug = 'dispel-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDistruction' WHERE slug = 'distruction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDivine Blast' WHERE slug = 'divine-blast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDivine Bless' WHERE slug = 'divine-bless-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDivine Shield' WHERE slug = 'divine-shield-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDivision Support' WHERE slug = 'division-support-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDiwido' WHERE slug = 'diwido-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDodge' WHERE slug = 'dodge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDoll Curse' WHERE slug = 'doll-curse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDoll Dream' WHERE slug = 'doll-dream-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDominar' WHERE slug = 'dominar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDominion Relic' WHERE slug = 'dominion-relic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDouble Firing' WHERE slug = 'double-firing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDouble Pierce' WHERE slug = 'double-pierce-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDouble Slice' WHERE slug = 'double-slice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDragante' WHERE slug = 'dragante-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDragon Kick' WHERE slug = 'dragon-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDread Worm' WHERE slug = 'dread-worm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDrive Spear' WHERE slug = 'drive-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDrug Intoxication' WHERE slug = 'drug-intoxication-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDrunken' WHERE slug = 'drunken-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDull Attack' WHERE slug = 'dull-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDust Cleaner' WHERE slug = 'dust-cleaner-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDust Devil' WHERE slug = 'dust-devil-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDust Storm' WHERE slug = 'dust-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEMP-0314' WHERE slug = 'emp-0314-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEagle Eye' WHERE slug = 'eagle-eye-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEarnest Prayer' WHERE slug = 'earnest-prayer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEarth Mental Attack' WHERE slug = 'earth-mental-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEarth Tremor' WHERE slug = 'earth-tremor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEarthquake' WHERE slug = 'earthquake-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEbram' WHERE slug = 'ebram-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEclabousser' WHERE slug = 'eclabousser-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEdella' WHERE slug = 'edella-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEdge' WHERE slug = 'edge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEffulgeo' WHERE slug = 'effulgeo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElbow Flash' WHERE slug = 'elbow-flash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectric Bluster' WHERE slug = 'electric-bluster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectric Charger' WHERE slug = 'electric-charger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectric Plasma' WHERE slug = 'electric-plasma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectric Punisher Construction' WHERE slug = 'electric-punisher-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectric Storm' WHERE slug = 'electric-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectriko' WHERE slug = 'electriko-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectrocution' WHERE slug = 'electrocution-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Kick' WHERE slug = 'elemental-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Penetration' WHERE slug = 'elemental-penetration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Power' WHERE slug = 'elemental-power-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Punch' WHERE slug = 'elemental-punch-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Spirit' WHERE slug = 'elemental-spirit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Strife' WHERE slug = 'elemental-strife-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Whisper' WHERE slug = 'elemental-whisper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElves' WHERE slug = 'elves-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEmbroil' WHERE slug = 'embroil-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnchaine' WHERE slug = 'enchaine-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnchanted Arm' WHERE slug = 'enchanted-arm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEncore' WHERE slug = 'encore-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEncounter Stroke' WHERE slug = 'encounter-stroke-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEndless Waltz' WHERE slug = 'endless-waltz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEndoscopy' WHERE slug = 'endoscopy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEndurance Melody' WHERE slug = 'endurance-melody-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnergy Boom' WHERE slug = 'energy-boom-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnergy Charge' WHERE slug = 'energy-charge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnervation' WHERE slug = 'enervation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnhanced Elemental Kick' WHERE slug = 'enhanced-elemental-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnhanced Lion Heart' WHERE slug = 'enhanced-lion-heart-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEntangled' WHERE slug = 'entangled-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEntrer en Lices' WHERE slug = 'entrer-en-lices-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnvolee' WHERE slug = 'envolee-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEos' WHERE slug = 'eos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEquiltario' WHERE slug = 'equiltario-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEraser' WHERE slug = 'eraser-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEremedium' WHERE slug = 'eremedium-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEruption' WHERE slug = 'eruption-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEscape Artist' WHERE slug = 'escape-artist-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEscape Record' WHERE slug = 'escape-record-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEscape Shot' WHERE slug = 'escape-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEspaccio' WHERE slug = 'espaccio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEspada / Sable Bolar' WHERE slug = 'espada-sable-bolar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEspada De La Rotacion' WHERE slug = 'espada-de-la-rotacion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEspada Del Viento' WHERE slug = 'espada-del-viento-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEsquive Touch' WHERE slug = 'esquive-touch-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEstigma' WHERE slug = 'estigma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEternal Tempest' WHERE slug = 'eternal-tempest-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEvasion' WHERE slug = 'evasion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExclusion' WHERE slug = 'exclusion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExecution' WHERE slug = 'execution-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExecution Shooter' WHERE slug = 'execution-shooter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExplosion Bolt' WHERE slug = 'explosion-bolt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExplosion' WHERE slug = 'explosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExpoison' WHERE slug = 'expoison-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExtensive Fetter Circle' WHERE slug = 'extensive-fetter-circle-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExtinction' WHERE slug = 'extinction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEye of Wolf' WHERE slug = 'eye-of-wolf-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFairy' WHERE slug = 'fairy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFalange Locura' WHERE slug = 'falange-locura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFallen Angel' WHERE slug = 'fallen-angel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFalling Meteorite' WHERE slug = 'falling-meteorite-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFanning Blossom' WHERE slug = 'fanning-blossom-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFanning' WHERE slug = 'fanning-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFantastic' WHERE slug = 'fantastic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFast Thinking' WHERE slug = 'fast-thinking-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFatal Blues' WHERE slug = 'fatal-blues-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFatal Move' WHERE slug = 'fatal-move-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFence Construction' WHERE slug = 'fence-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFente' WHERE slug = 'fente-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFeral Roar' WHERE slug = 'feral-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFeral Tooth' WHERE slug = 'feral-tooth-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFides' WHERE slug = 'fides-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนField Clearing' WHERE slug = 'field-clearing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนField Manual' WHERE slug = 'field-manual-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFierce Blow' WHERE slug = 'fierce-blow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFimbul' WHERE slug = 'fimbul-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFinal Advent' WHERE slug = 'final-advent-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFinal Disaster / Final Avalanche' WHERE slug = 'final-disaster-final-avalanche-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFinal Mantara' WHERE slug = 'final-mantara-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFinale' WHERE slug = 'finale-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFinis' WHERE slug = 'finis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFinishing' WHERE slug = 'finishing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFire Flower' WHERE slug = 'fire-flower-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFire Golem Control' WHERE slug = 'fire-golem-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFire Storm' WHERE slug = 'fire-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFire Vrille' WHERE slug = 'fire-vrille-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFireball' WHERE slug = 'fireball-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFirewall' WHERE slug = 'firewall-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Abyss' WHERE slug = 'flame-abyss-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Booster' WHERE slug = 'flame-booster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Dance' WHERE slug = 'flame-dance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Extrusion' WHERE slug = 'flame-extrusion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Ground' WHERE slug = 'flame-ground-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Hammer' WHERE slug = 'flame-hammer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Mallet' WHERE slug = 'flame-mallet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Protection' WHERE slug = 'flame-protection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Rampage' WHERE slug = 'flame-rampage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Riser Construction' WHERE slug = 'flame-riser-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Road' WHERE slug = 'flame-road-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Rush' WHERE slug = 'flame-rush-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Strike' WHERE slug = 'flame-strike-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Suit' WHERE slug = 'flame-suit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame of Chester' WHERE slug = 'flame-of-chester-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlare' WHERE slug = 'flare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlare Shot' WHERE slug = 'flare-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlashs Blade-From the Sky' WHERE slug = 'flashs-blade-from-the-sky-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlashs Blade-Moon and Flower' WHERE slug = 'flashs-blade-moon-and-flower-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlashs Blade-Thousand cherry blossoms' WHERE slug = 'flashs-blade-thousand-cherry-blossoms-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFloor Cleaner' WHERE slug = 'floor-cleaner-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFloral Breeze' WHERE slug = 'floral-breeze-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFloral Twister' WHERE slug = 'floral-twister-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFloren T. Buster' WHERE slug = 'floren-t-buster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlutter' WHERE slug = 'flutter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlying Wyvern' WHERE slug = 'flying-wyvern-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนForce Field' WHERE slug = 'force-field-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนForce Volley Shot' WHERE slug = 'force-volley-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFortify Aura' WHERE slug = 'fortify-aura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFortify' WHERE slug = 'fortify-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFortissimo' WHERE slug = 'fortissimo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFox Faltrie / Fox Tribinal' WHERE slug = 'fox-faltrie-fox-tribinal-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFox Form' WHERE slug = 'fox-form-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFox Hound' WHERE slug = 'fox-hound-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrapper' WHERE slug = 'frapper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFreeandis' WHERE slug = 'freeandis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFreeze to Death' WHERE slug = 'freeze-to-death-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFreeze!!' WHERE slug = 'freeze-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFreezing' WHERE slug = 'freezing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFreezing Spear' WHERE slug = 'freezing-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrenzied Thunder' WHERE slug = 'frenzied-thunder-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrenzy' WHERE slug = 'frenzy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrenzy Thunder - Electronic Hare' WHERE slug = 'frenzy-thunder-electronic-hare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFridged Stroke' WHERE slug = 'fridged-stroke-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrigid' WHERE slug = 'frigid-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrost Cloud' WHERE slug = 'frost-cloud-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrost Dust' WHERE slug = 'frost-dust-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrost Shield' WHERE slug = 'frost-shield-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrost Storm' WHERE slug = 'frost-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrozen Ball' WHERE slug = 'frozen-ball-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrozen Field' WHERE slug = 'frozen-field-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrozen Ghost' WHERE slug = 'frozen-ghost-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrozen Road' WHERE slug = 'frozen-road-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrozen Wave' WHERE slug = 'frozen-wave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFuego' WHERE slug = 'fuego-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFuga' WHERE slug = 'fuga-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFury' WHERE slug = 'fury-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFute Shot' WHERE slug = 'fute-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGabi Quake' WHERE slug = 'gabi-quake-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGatling Empowerment' WHERE slug = 'gatling-empowerment-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGazer' WHERE slug = 'gazer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGenocide' WHERE slug = 'genocide-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGenos Spear' WHERE slug = 'genos-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGet Set' WHERE slug = 'get-set-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGiant Bat / Levine Scamper' WHERE slug = 'giant-bat-levine-scamper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGiant Jet' WHERE slug = 'giant-jet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGigante Marcha' WHERE slug = 'gigante-marcha-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGigantic Hare' WHERE slug = 'gigantic-hare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGigantic Reve' WHERE slug = 'gigantic-reve-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGinnung' WHERE slug = 'ginnung-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGirandole' WHERE slug = 'girandole-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlacial Crown' WHERE slug = 'glacial-crown-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlacial Lance' WHERE slug = 'glacial-lance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlacier Anguard' WHERE slug = 'glacier-anguard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlacier Cutter' WHERE slug = 'glacier-cutter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlacier Fente' WHERE slug = 'glacier-fente-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlacier Finish' WHERE slug = 'glacier-finish-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlacier Of Session' WHERE slug = 'glacier-of-session-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlacier Sword' WHERE slug = 'glacier-sword-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlint' WHERE slug = 'glint-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlitter' WHERE slug = 'glitter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGloom Shot' WHERE slug = 'gloom-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGloomy Present' WHERE slug = 'gloomy-present-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGlorious Judgement' WHERE slug = 'glorious-judgement-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGolpe' WHERE slug = 'golpe-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGraffiti Road' WHERE slug = 'graffiti-road-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrand Pressure' WHERE slug = 'grand-pressure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrave' WHERE slug = 'grave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGreat Rotating Blade Construction' WHERE slug = 'great-rotating-blade-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrenade Buster' WHERE slug = 'grenade-buster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrenade Shot' WHERE slug = 'grenade-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrieta' WHERE slug = 'grieta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrill' WHERE slug = 'grill-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrim-Ripper' WHERE slug = 'grim-ripper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrind Accel' WHERE slug = 'grind-accel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrind Cutter' WHERE slug = 'grind-cutter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrinding' WHERE slug = 'grinding-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrizzly Shock' WHERE slug = 'grizzly-shock-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGround Flakes Rising Circle' WHERE slug = 'ground-flakes-rising-circle-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGround Shaker Construction' WHERE slug = 'ground-shaker-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGruesome' WHERE slug = 'gruesome-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGuardian' WHERE slug = 'guardian-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGula' WHERE slug = 'gula-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGun Master' WHERE slug = 'gun-master-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGun Slash' WHERE slug = 'gun-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGust Bringer' WHERE slug = 'gust-bringer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHall of Flame' WHERE slug = 'hall-of-flame-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHall of Twilight' WHERE slug = 'hall-of-twilight-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHand Trick' WHERE slug = 'hand-trick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHarpoon' WHERE slug = 'harpoon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHarsh Blaze' WHERE slug = 'harsh-blaze-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHatcher' WHERE slug = 'hatcher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHawkeye' WHERE slug = 'hawkeye-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHead Shot' WHERE slug = 'head-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHealing' WHERE slug = 'healing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHeart Breaker' WHERE slug = 'heart-breaker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHeart Burst' WHERE slug = 'heart-burst-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHeavenly Shield' WHERE slug = 'heavenly-shield-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHeavy Drinker' WHERE slug = 'heavy-drinker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHeavy Pressure' WHERE slug = 'heavy-pressure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHeavy Smashing' WHERE slug = 'heavy-smashing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHelena Control' WHERE slug = 'helena-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHell Breath' WHERE slug = 'hell-breath-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHetzen' WHERE slug = 'hetzen-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHexen Dropper' WHERE slug = 'hexen-dropper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHeze' WHERE slug = 'heze-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHidden Card' WHERE slug = 'hidden-card-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHigh Class' WHERE slug = 'high-class-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHigh Tide' WHERE slug = 'high-tide-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHighlander Soul' WHERE slug = 'highlander-soul-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHill Giant Summon' WHERE slug = 'hill-giant-summon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHold Shot' WHERE slug = 'hold-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHole of Darkness' WHERE slug = 'hole-of-darkness-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHolly Sacrifice' WHERE slug = 'holly-sacrifice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHoly Aura' WHERE slug = 'holy-aura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHoog' WHERE slug = 'hoog-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHorizon Protect' WHERE slug = 'horizon-protect-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHound' WHERE slug = 'hound-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHowling of Heaven' WHERE slug = 'howling-of-heaven-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHwoarang Spirits' WHERE slug = 'hwoarang-spirits-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHyperbolemic Shock' WHERE slug = 'hyperbolemic-shock-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Age' WHERE slug = 'ice-age-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Blood Attack' WHERE slug = 'ice-blood-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Breaker' WHERE slug = 'ice-breaker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Explosion' WHERE slug = 'ice-explosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Field' WHERE slug = 'ice-field-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Flower' WHERE slug = 'ice-flower-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Partisan' WHERE slug = 'ice-partisan-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Plasma' WHERE slug = 'ice-plasma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Road' WHERE slug = 'ice-road-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Shot' WHERE slug = 'ice-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Soul Attack' WHERE slug = 'ice-soul-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Soul Kick' WHERE slug = 'ice-soul-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Tornado Kick' WHERE slug = 'ice-tornado-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Vrille' WHERE slug = 'ice-vrille-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIcicle' WHERE slug = 'icicle-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIcy Akeron' WHERE slug = 'icy-akeron-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIcy Skin' WHERE slug = 'icy-skin-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIgnore Harm' WHERE slug = 'ignore-harm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIlardo Paharo' WHERE slug = 'ilardo-paharo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIllusion Mirror' WHERE slug = 'illusion-mirror-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIllusion Straight' WHERE slug = 'illusion-straight-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImagination Reload' WHERE slug = 'imagination-reload-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImagination' WHERE slug = 'imagination-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImber' WHERE slug = 'imber-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImmortal Spirit / Frozen Spirit' WHERE slug = 'immortal-spirit-frozen-spirit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImpact Spike' WHERE slug = 'impact-spike-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImperial Burst' WHERE slug = 'imperial-burst-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImperial Smash' WHERE slug = 'imperial-smash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImplosion' WHERE slug = 'implosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImplosive Shock' WHERE slug = 'implosive-shock-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImprove Disease' WHERE slug = 'improve-disease-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImpulse' WHERE slug = 'impulse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImuditia' WHERE slug = 'imuditia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIncising Attack' WHERE slug = 'incising-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIndicacion' WHERE slug = 'indicacion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInfernal Flames' WHERE slug = 'infernal-flames-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInferno of Revolver' WHERE slug = 'inferno-of-revolver-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInferroz' WHERE slug = 'inferroz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInfiltration' WHERE slug = 'infiltration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInfinity Shooting Star' WHERE slug = 'infinity-shooting-star-ring' AND name_th IS NULL;