-- Migration 059: Thai names batch 6/10
-- Generated: 2026-03-16T03:42:16.054Z

UPDATE items SET name_th = 'แหวนInsanity' WHERE slug = 'insanity-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInstinct' WHERE slug = 'instinct-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIntensify Aura' WHERE slug = 'intensify-aura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIntensify' WHERE slug = 'intensify-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInto The Heaven' WHERE slug = 'into-the-heaven-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInto The Hell' WHERE slug = 'into-the-hell-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInto the Darkness' WHERE slug = 'into-the-darkness-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInto the Inferno' WHERE slug = 'into-the-inferno-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInto the Sanctuary' WHERE slug = 'into-the-sanctuary-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIntoxicacion' WHERE slug = 'intoxicacion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIntrickage' WHERE slug = 'intrickage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInvertir' WHERE slug = 'invertir-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInvidia' WHERE slug = 'invidia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInvisible Stalker' WHERE slug = 'invisible-stalker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInvisible String' WHERE slug = 'invisible-string-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInvulnerable' WHERE slug = 'invulnerable-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIra' WHERE slug = 'ira-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIron Ararat Summon' WHERE slug = 'iron-ararat-summon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIskashar' WHERE slug = 'iskashar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนJudgement of Thor' WHERE slug = 'judgement-of-thor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนJudgment' WHERE slug = 'judgment-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนJuggler Cut' WHERE slug = 'juggler-cut-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนJullian' WHERE slug = 'jullian-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนJust One' WHERE slug = 'just-one-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนJustice' WHERE slug = 'justice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKaedes' WHERE slug = 'kaedes-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKaido' WHERE slug = 'kaido-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKaleidor' WHERE slug = 'kaleidor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKallour' WHERE slug = 'kallour-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKalma' WHERE slug = 'kalma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKashta' WHERE slug = 'kashta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKatore' WHERE slug = 'katore-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKing Spirit' WHERE slug = 'king-spirit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKings Majesty' WHERE slug = 'kings-majesty-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKira' WHERE slug = 'kira-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKlage' WHERE slug = 'klage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKrollonia' WHERE slug = 'krollonia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKuka' WHERE slug = 'kuka-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKukatao' WHERE slug = 'kukatao-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKunirona' WHERE slug = 'kunirona-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKurast' WHERE slug = 'kurast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKwan' WHERE slug = 'kwan-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLArc en Ciel' WHERE slug = 'larc-en-ciel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLa Fuego' WHERE slug = 'la-fuego-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLa Peurini' WHERE slug = 'la-peurini-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLado Patada' WHERE slug = 'lado-patada-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLady Sasha Control' WHERE slug = 'lady-sasha-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLama-El' WHERE slug = 'lama-el-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLamour' WHERE slug = 'lamour-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLand Cracker' WHERE slug = 'land-cracker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLapute' WHERE slug = 'lapute-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLas luces' WHERE slug = 'las-luces-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLaspina' WHERE slug = 'laspina-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLava Explosion' WHERE slug = 'lava-explosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLava Extrusion' WHERE slug = 'lava-extrusion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLava Plasma' WHERE slug = 'lava-plasma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLava Strike' WHERE slug = 'lava-strike-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLayered' WHERE slug = 'layered-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLeadership' WHERE slug = 'leadership-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLento' WHERE slug = 'lento-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLeo' WHERE slug = 'leo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLethargy' WHERE slug = 'lethargy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLevantar' WHERE slug = 'levantar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLeviathan Roar' WHERE slug = 'leviathan-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLiberate' WHERE slug = 'liberate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLibra' WHERE slug = 'libra-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLife Sentence' WHERE slug = 'life-sentence-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLight Flow' WHERE slug = 'light-flow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning Blast' WHERE slug = 'lightning-blast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning Bomb' WHERE slug = 'lightning-bomb-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning Cube' WHERE slug = 'lightning-cube-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning' WHERE slug = 'lightning-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning Rod' WHERE slug = 'lightning-rod-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning Sabre' WHERE slug = 'lightning-sabre-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning Shield' WHERE slug = 'lightning-shield-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning Spear' WHERE slug = 'lightning-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLightning Storm' WHERE slug = 'lightning-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLily of the Valley' WHERE slug = 'lily-of-the-valley-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLionheart' WHERE slug = 'lionheart-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLloyd Control' WHERE slug = 'lloyd-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLos Cremor' WHERE slug = 'los-cremor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLovely Wink' WHERE slug = 'lovely-wink-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLower-cut' WHERE slug = 'lower-cut-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLufa' WHERE slug = 'lufa-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLust Murder' WHERE slug = 'lust-murder-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLuxuria' WHERE slug = 'luxuria-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMachina Buster' WHERE slug = 'machina-buster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMachina Control' WHERE slug = 'machina-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMad Delusion' WHERE slug = 'mad-delusion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMaestro Ring / Vesta' WHERE slug = 'maestro-ring-vesta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagic Barrier' WHERE slug = 'magic-barrier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagic Earthquake' WHERE slug = 'magic-earthquake-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagic Enhance' WHERE slug = 'magic-enhance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagical Piercing' WHERE slug = 'magical-piercing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagma Explosion' WHERE slug = 'magma-explosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagma Roar' WHERE slug = 'magma-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagma Storm' WHERE slug = 'magma-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMagneta' WHERE slug = 'magneta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMajor Shot' WHERE slug = 'major-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMaketau' WHERE slug = 'maketau-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMaledisite' WHERE slug = 'maledisite-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนManato' WHERE slug = 'manato-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMargarita' WHERE slug = 'margarita-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMark' WHERE slug = 'mark-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMartus' WHERE slug = 'martus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMaskmanship' WHERE slug = 'maskmanship-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMass Cure' WHERE slug = 'mass-cure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMass Destruction' WHERE slug = 'mass-destruction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMass Evasion' WHERE slug = 'mass-evasion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMass Healing' WHERE slug = 'mass-healing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMass Invisible' WHERE slug = 'mass-invisible-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMassacre' WHERE slug = 'massacre-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMassacre Rush' WHERE slug = 'massacre-rush-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMassive Break' WHERE slug = 'massive-break-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMassive Charge' WHERE slug = 'massive-charge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMastalt' WHERE slug = 'mastalt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMatimo' WHERE slug = 'matimo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMeditation' WHERE slug = 'meditation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMelee Enhance' WHERE slug = 'melee-enhance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMelt Armor' WHERE slug = 'melt-armor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMelt Weapon' WHERE slug = 'melt-weapon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMemorization' WHERE slug = 'memorization-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMenace Shot' WHERE slug = 'menace-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMend' WHERE slug = 'mend-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMensa' WHERE slug = 'mensa-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMercede' WHERE slug = 'mercede-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMerchen' WHERE slug = 'merchen-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMerciless' WHERE slug = 'merciless-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMeteo Shower' WHERE slug = 'meteo-shower-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMeteor Strike' WHERE slug = 'meteor-strike-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMetid' WHERE slug = 'metid-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMidnight Slasher' WHERE slug = 'midnight-slasher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMiembro Invisible' WHERE slug = 'miembro-invisible-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMighty Victor Control' WHERE slug = 'mighty-victor-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMilitant' WHERE slug = 'militant-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMind Blast' WHERE slug = 'mind-blast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMind Pressure' WHERE slug = 'mind-pressure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMind Steal' WHERE slug = 'mind-steal-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMinerva' WHERE slug = 'minerva-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMinor Shot' WHERE slug = 'minor-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMiracle' WHERE slug = 'miracle-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMischief' WHERE slug = 'mischief-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMiserable Fantasma' WHERE slug = 'miserable-fantasma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMisty Claymore' WHERE slug = 'misty-claymore-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMoisson' WHERE slug = 'moisson-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMoon Decision' WHERE slug = 'moon-decision-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMorande' WHERE slug = 'morande-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMoras' WHERE slug = 'moras-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMorians Holy Grail' WHERE slug = 'morians-holy-grail-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMortal Eternity' WHERE slug = 'mortal-eternity-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMulti-Rate' WHERE slug = 'multi-rate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNaraka Form I' WHERE slug = 'naraka-form-i-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNaraka Form II' WHERE slug = 'naraka-form-ii-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNaraka Form III' WHERE slug = 'naraka-form-iii-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNaraka Form IV' WHERE slug = 'naraka-form-iv-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNaraka Form V' WHERE slug = 'naraka-form-v-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNature' WHERE slug = 'nature-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNavy Code' WHERE slug = 'navy-code-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNear Death' WHERE slug = 'near-death-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNecromancy' WHERE slug = 'necromancy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNiar' WHERE slug = 'niar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNightmare' WHERE slug = 'nightmare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNine Crystal / Nine Pro-port' WHERE slug = 'nine-crystal-nine-pro-port-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNo Trick' WHERE slug = 'no-trick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNote Scatter' WHERE slug = 'note-scatter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNumero Citas' WHERE slug = 'numero-citas-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOblivion' WHERE slug = 'oblivion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนObratio' WHERE slug = 'obratio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOccult Science' WHERE slug = 'occult-science-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOctet-stream' WHERE slug = 'octet-stream-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOne Card' WHERE slug = 'one-card-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOne For All' WHERE slug = 'one-for-all-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOpening the Door - Death' WHERE slug = 'opening-the-door-death-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOperation : A' WHERE slug = 'operation-a-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOperation : C' WHERE slug = 'operation-c-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOperation : O' WHERE slug = 'operation-o-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOperation : P' WHERE slug = 'operation-p-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOperation : S' WHERE slug = 'operation-s-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOphelia Melissa' WHERE slug = 'ophelia-melissa-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOphiuchus' WHERE slug = 'ophiuchus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOrden' WHERE slug = 'orden-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOrder Point Shot' WHERE slug = 'order-point-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOrpheus' WHERE slug = 'orpheus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOrtus Quake' WHERE slug = 'ortus-quake-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOver Light Shot' WHERE slug = 'over-light-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOver Limit' WHERE slug = 'over-limit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOver The Horizon' WHERE slug = 'over-the-horizon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOver The Sky' WHERE slug = 'over-the-sky-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOverrange Shot' WHERE slug = 'overrange-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOverwhelm' WHERE slug = 'overwhelm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOverwhelming Shot' WHERE slug = 'overwhelming-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPaeon' WHERE slug = 'paeon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPain Killer' WHERE slug = 'pain-killer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPaint Shower' WHERE slug = 'paint-shower-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPales' WHERE slug = 'pales-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPalesimento' WHERE slug = 'palesimento-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPantera Force' WHERE slug = 'pantera-force-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนParade Riposte' WHERE slug = 'parade-riposte-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนParfata' WHERE slug = 'parfata-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPassant' WHERE slug = 'passant-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPastier' WHERE slug = 'pastier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPatata' WHERE slug = 'patata-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPell Aurel Tornado / Pell Aurel Tempest' WHERE slug = 'pell-aurel-tornado-pell-aurel-tempest-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPell Lavasolt' WHERE slug = 'pell-lavasolt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPell Pochainar' WHERE slug = 'pell-pochainar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPell Sollast' WHERE slug = 'pell-sollast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPenetration Shot' WHERE slug = 'penetration-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPenta Break' WHERE slug = 'penta-break-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPenta Simeter' WHERE slug = 'penta-simeter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPenta-Train' WHERE slug = 'penta-train-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPerfect Sweep' WHERE slug = 'perfect-sweep-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPhantastorm' WHERE slug = 'phantastorm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPhoenix Swoop' WHERE slug = 'phoenix-swoop-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPhoton Splash' WHERE slug = 'photon-splash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPhoton Strike' WHERE slug = 'photon-strike-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPieno' WHERE slug = 'pieno-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPierce' WHERE slug = 'pierce-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPiercing Arrow' WHERE slug = 'piercing-arrow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPiercing Bound' WHERE slug = 'piercing-bound-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPiercing Breeze' WHERE slug = 'piercing-breeze-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPiercing Dimension' WHERE slug = 'piercing-dimension-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPirate Code' WHERE slug = 'pirate-code-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPistol Shot' WHERE slug = 'pistol-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPitiless' WHERE slug = 'pitiless-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPizzicato' WHERE slug = 'pizzicato-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPlumbullet shot' WHERE slug = 'plumbullet-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPlunge' WHERE slug = 'plunge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPlutus' WHERE slug = 'plutus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPoder' WHERE slug = 'poder-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPoena' WHERE slug = 'poena-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPoint Blank' WHERE slug = 'point-blank-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPoison Bolt' WHERE slug = 'poison-bolt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPoison Bomb' WHERE slug = 'poison-bomb-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPoison Tail' WHERE slug = 'poison-tail-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPoll Place' WHERE slug = 'poll-place-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPolluted Shot' WHERE slug = 'polluted-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPolluted Water' WHERE slug = 'polluted-water-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPommel' WHERE slug = 'pommel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPomoru / Kanine' WHERE slug = 'pomoru-kanine-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPopularna' WHERE slug = 'popularna-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPositions' WHERE slug = 'positions-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPossession' WHERE slug = 'possession-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPower Slash' WHERE slug = 'power-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPower Stroke' WHERE slug = 'power-stroke-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPower of Absinia' WHERE slug = 'power-of-absinia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPraeceps' WHERE slug = 'praeceps-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPranus / Pull Closure' WHERE slug = 'pranus-pull-closure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPray' WHERE slug = 'pray-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrea' WHERE slug = 'prea-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrecision Strike' WHERE slug = 'precision-strike-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPregarah' WHERE slug = 'pregarah-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrelude to Death' WHERE slug = 'prelude-to-death-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPreparation' WHERE slug = 'preparation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPresent' WHERE slug = 'present-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPresto' WHERE slug = 'presto-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrincipal Aura' WHERE slug = 'principal-aura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrincipal' WHERE slug = 'principal-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrincipal (30 วัน)' WHERE slug = 'principal-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPromise' WHERE slug = 'promise-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrompt Action' WHERE slug = 'prompt-action-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนProtect Shade' WHERE slug = 'protect-shade-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนProtect Weapon' WHERE slug = 'protect-weapon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนProtecting Booster' WHERE slug = 'protecting-booster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนProtection Field' WHERE slug = 'protection-field-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนProvoke' WHERE slug = 'provoke-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPsychic Bomb' WHERE slug = 'psychic-bomb-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPsychic' WHERE slug = 'psychic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPsycho Dance' WHERE slug = 'psycho-dance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPulverize' WHERE slug = 'pulverize-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPunishment' WHERE slug = 'punishment-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPunto' WHERE slug = 'punto-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPurify' WHERE slug = 'purify-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนQuadruple Action' WHERE slug = 'quadruple-action-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนQuarto Taglio' WHERE slug = 'quarto-taglio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนQuattro Firing' WHERE slug = 'quattro-firing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนQuick Boom' WHERE slug = 'quick-boom-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนQuick and Dead' WHERE slug = 'quick-and-dead-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนR.I.P.' WHERE slug = 'r-i-p-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRaeloss' WHERE slug = 'raeloss-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRage' WHERE slug = 'rage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRage of St.' WHERE slug = 'rage-of-st-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRahar' WHERE slug = 'rahar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRain Over' WHERE slug = 'rain-over-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRainbow Splasher - Mifuyu' WHERE slug = 'rainbow-splasher-mifuyu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRainbow Splasher' WHERE slug = 'rainbow-splasher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRampage' WHERE slug = 'rampage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRampunt Gardent' WHERE slug = 'rampunt-gardent-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRampunt Regardent' WHERE slug = 'rampunt-regardent-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRanchera' WHERE slug = 'ranchera-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapid Reach' WHERE slug = 'rapid-reach-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapid Shot' WHERE slug = 'rapid-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapida Ataque' WHERE slug = 'rapida-ataque-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapida' WHERE slug = 'rapida-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapidly Stab' WHERE slug = 'rapidly-stab-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapu' WHERE slug = 'rapu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRazantz' WHERE slug = 'razantz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRebound' WHERE slug = 'rebound-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRecover' WHERE slug = 'recover-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRed Crescent' WHERE slug = 'red-crescent-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRedemption' WHERE slug = 'redemption-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReditum' WHERE slug = 'reditum-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReflect Skin' WHERE slug = 'reflect-skin-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReflexion' WHERE slug = 'reflexion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRefresh Mind' WHERE slug = 'refresh-mind-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRefriger Wave' WHERE slug = 'refriger-wave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRegenerator Construction' WHERE slug = 'regenerator-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRejection' WHERE slug = 'rejection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReload Action' WHERE slug = 'reload-action-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRepulsive Arena' WHERE slug = 'repulsive-arena-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRepulsive Force' WHERE slug = 'repulsive-force-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRequiem' WHERE slug = 'requiem-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนResit' WHERE slug = 'resit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนResolution' WHERE slug = 'resolution-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRestore' WHERE slug = 'restore-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนResurrection' WHERE slug = 'resurrection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนResuscitation' WHERE slug = 'resuscitation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReturn Stroke' WHERE slug = 'return-stroke-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReverie' WHERE slug = 'reverie-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRevers Blindly' WHERE slug = 'revers-blindly-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReverse' WHERE slug = 'reverse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReverse Rolling Shot' WHERE slug = 'reverse-rolling-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRevival' WHERE slug = 'revival-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRevolucion' WHERE slug = 'revolucion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRhythm and Blues' WHERE slug = 'rhythm-and-blues-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRichards Holy Sword' WHERE slug = 'richards-holy-sword-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRicochet' WHERE slug = 'ricochet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRimite' WHERE slug = 'rimite-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRiposte' WHERE slug = 'riposte-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRise Rodia' WHERE slug = 'rise-rodia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRising Swing' WHERE slug = 'rising-swing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRitardi' WHERE slug = 'ritardi-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRoar Shot' WHERE slug = 'roar-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRoar of Dragon' WHERE slug = 'roar-of-dragon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRoasting' WHERE slug = 'roasting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRolling Thunder' WHERE slug = 'rolling-thunder-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRopera' WHERE slug = 'ropera-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRose Heart' WHERE slug = 'rose-heart-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRosemarie' WHERE slug = 'rosemarie-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRotating Blade Construction' WHERE slug = 'rotating-blade-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRudlomo' WHERE slug = 'rudlomo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRueda Ventana' WHERE slug = 'rueda-ventana-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRuidens Holy Sword' WHERE slug = 'ruidens-holy-sword-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRush' WHERE slug = 'rush-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRuthless' WHERE slug = 'ruthless-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSabre Charge' WHERE slug = 'sabre-charge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSacred Guard' WHERE slug = 'sacred-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSacred Territory' WHERE slug = 'sacred-territory-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSacredness' WHERE slug = 'sacredness-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSafety Ward Construction' WHERE slug = 'safety-ward-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSailient' WHERE slug = 'sailient-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSaint Crystal' WHERE slug = 'saint-crystal-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSaltos De Ataques' WHERE slug = 'saltos-de-ataques-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSalute' WHERE slug = 'salute-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSanctuary' WHERE slug = 'sanctuary-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSanctuary of Crescent' WHERE slug = 'sanctuary-of-crescent-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSand Dive' WHERE slug = 'sand-dive-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSand Flare' WHERE slug = 'sand-flare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSand Storm' WHERE slug = 'sand-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSandman' WHERE slug = 'sandman-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSapping Shots' WHERE slug = 'sapping-shots-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSarmado' WHERE slug = 'sarmado-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSasha Control' WHERE slug = 'sasha-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSatisfy' WHERE slug = 'satisfy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSavage Hatchet' WHERE slug = 'savage-hatchet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนScent of Death' WHERE slug = 'scent-of-death-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนScorpius' WHERE slug = 'scorpius-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSea of Angel' WHERE slug = 'sea-of-angel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSea of Devil' WHERE slug = 'sea-of-devil-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSecret Blade-Slash the Moon' WHERE slug = 'secret-blade-slash-the-moon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSecret Blade-Slash the Phoenix' WHERE slug = 'secret-blade-slash-the-phoenix-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSecreta' WHERE slug = 'secreta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSection Firing' WHERE slug = 'section-firing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSeismic wave' WHERE slug = 'seismic-wave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSeparate Collection' WHERE slug = 'separate-collection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSephia' WHERE slug = 'sephia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSept Etoiles' WHERE slug = 'sept-etoiles-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSergeant Break' WHERE slug = 'sergeant-break-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSet Shoot' WHERE slug = 'set-shoot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShadow Dawn' WHERE slug = 'shadow-dawn-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShadow Moving' WHERE slug = 'shadow-moving-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShadow Teleport' WHERE slug = 'shadow-teleport-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShadow Trigger' WHERE slug = 'shadow-trigger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShadow Walk' WHERE slug = 'shadow-walk-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShaman' WHERE slug = 'shaman-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShare Tactics' WHERE slug = 'share-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSharing' WHERE slug = 'sharing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSharp Bolt' WHERE slug = 'sharp-bolt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSharp Eyes' WHERE slug = 'sharp-eyes-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSharp Judgement' WHERE slug = 'sharp-judgement-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSharp Lightning' WHERE slug = 'sharp-lightning-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSharp Scythe' WHERE slug = 'sharp-scythe-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSharp Sphere' WHERE slug = 'sharp-sphere-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSharpened Blade' WHERE slug = 'sharpened-blade-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShaula' WHERE slug = 'shaula-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShearing Booster' WHERE slug = 'shearing-booster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShell Breaker' WHERE slug = 'shell-breaker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShield Charge' WHERE slug = 'shield-charge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShield Rush' WHERE slug = 'shield-rush-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining Ballade' WHERE slug = 'shining-ballade-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining Breaker' WHERE slug = 'shining-breaker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining Burst' WHERE slug = 'shining-burst-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining Dawn' WHERE slug = 'shining-dawn-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining Inferno' WHERE slug = 'shining-inferno-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining Machine Shot' WHERE slug = 'shining-machine-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining' WHERE slug = 'shining-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShock Field Construction' WHERE slug = 'shock-field-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShock Wave' WHERE slug = 'shock-wave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShootdown Shot' WHERE slug = 'shootdown-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShooting Blow' WHERE slug = 'shooting-blow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShooting Canon' WHERE slug = 'shooting-canon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShooting Enhance' WHERE slug = 'shooting-enhance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShooting Promotor' WHERE slug = 'shooting-promotor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShooting Scoop' WHERE slug = 'shooting-scoop-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShooting Spree' WHERE slug = 'shooting-spree-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShooting Star' WHERE slug = 'shooting-star-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShoulder Charge' WHERE slug = 'shoulder-charge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSiege Cannon Shot' WHERE slug = 'siege-cannon-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSiege Mode' WHERE slug = 'siege-mode-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSierra Ilimitada' WHERE slug = 'sierra-ilimitada-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSigma' WHERE slug = 'sigma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSilent Cradlesong' WHERE slug = 'silent-cradlesong-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSilent Dancing' WHERE slug = 'silent-dancing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSilent Move' WHERE slug = 'silent-move-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSilver Ararat' WHERE slug = 'silver-ararat-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSirma' WHERE slug = 'sirma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSkull Divider' WHERE slug = 'skull-divider-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSkull Fracture' WHERE slug = 'skull-fracture-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSkyliner' WHERE slug = 'skyliner-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSlash Down' WHERE slug = 'slash-down-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSlashing Dash - Mifuyu' WHERE slug = 'slashing-dash-mifuyu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSlaughter' WHERE slug = 'slaughter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSlide Shot' WHERE slug = 'slide-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSling' WHERE slug = 'sling-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSlow Bolt' WHERE slug = 'slow-bolt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSmoke Screen' WHERE slug = 'smoke-screen-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSnap Shot' WHERE slug = 'snap-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSnipe' WHERE slug = 'snipe-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSnow Explosion' WHERE slug = 'snow-explosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSnow Golem Control' WHERE slug = 'snow-golem-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSnow Storm' WHERE slug = 'snow-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSnowflake' WHERE slug = 'snowflake-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSonic Cross' WHERE slug = 'sonic-cross-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSonic Slice' WHERE slug = 'sonic-slice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSorting Machina' WHERE slug = 'sorting-machina-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul Burn' WHERE slug = 'soul-burn-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul Crash' WHERE slug = 'soul-crash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul Explosion' WHERE slug = 'soul-explosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul Reaper' WHERE slug = 'soul-reaper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul of Fire' WHERE slug = 'soul-of-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul of Grim' WHERE slug = 'soul-of-grim-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul of Ice' WHERE slug = 'soul-of-ice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul of Wind' WHERE slug = 'soul-of-wind-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSound of Ground' WHERE slug = 'sound-of-ground-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSparking Fox / Flame Fox' WHERE slug = 'sparking-fox-flame-fox-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpear Wheel Kick' WHERE slug = 'spear-wheel-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpell Bead' WHERE slug = 'spell-bead-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpell Hail' WHERE slug = 'spell-hail-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpell-break Rhythm' WHERE slug = 'spell-break-rhythm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpica' WHERE slug = 'spica-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpike Gatling Construction' WHERE slug = 'spike-gatling-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpike Trap' WHERE slug = 'spike-trap-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpin Combination' WHERE slug = 'spin-combination-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpin Uriela' WHERE slug = 'spin-uriela-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpirit Panther' WHERE slug = 'spirit-panther-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpiritual Shield' WHERE slug = 'spiritual-shield-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSpread Shot' WHERE slug = 'spread-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSprint' WHERE slug = 'sprint-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSt. Strike' WHERE slug = 'st-strike-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStab Slash' WHERE slug = 'stab-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStarlight Flare' WHERE slug = 'starlight-flare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStatic' WHERE slug = 'static-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSteamer' WHERE slug = 'steamer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSteel Baton' WHERE slug = 'steel-baton-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStill a Novice?' WHERE slug = 'still-a-novice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStingbringer' WHERE slug = 'stingbringer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStinger Shot' WHERE slug = 'stinger-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStone Disease' WHERE slug = 'stone-disease-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStorm Blitz' WHERE slug = 'storm-blitz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStormy Helix Circle' WHERE slug = 'stormy-helix-circle-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStrafe Charge' WHERE slug = 'strafe-charge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStrike Back' WHERE slug = 'strike-back-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStrong Acid' WHERE slug = 'strong-acid-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStunning Skewer' WHERE slug = 'stunning-skewer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSubmachine Shot' WHERE slug = 'submachine-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSuccess? Great Success!' WHERE slug = 'success-great-success-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSummary Conviction' WHERE slug = 'summary-conviction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSummon Sekhmet / Summon Cottonbear' WHERE slug = 'summon-sekhmet-summon-cottonbear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSupervia' WHERE slug = 'supervia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSupport Ballista' WHERE slug = 'support-ballista-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSupport for Blood' WHERE slug = 'support-for-blood-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSupporting Shot' WHERE slug = 'supporting-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSuppression Record' WHERE slug = 'suppression-record-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSuppressive Fire' WHERE slug = 'suppressive-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSurpassing Shot' WHERE slug = 'surpassing-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSurrounding Bat / Surronding Snowflake' WHERE slug = 'surrounding-bat-surronding-snowflake-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSuture' WHERE slug = 'suture-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSweet Dreamer' WHERE slug = 'sweet-dreamer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSwift Move' WHERE slug = 'swift-move-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSwift Shot' WHERE slug = 'swift-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSword of Tempest' WHERE slug = 'sword-of-tempest-ring' AND name_th IS NULL;