-- Migration 060: Thai names batch 7/10
-- Generated: 2026-03-16T03:42:16.054Z

UPDATE items SET name_th = 'แหวนTactics' WHERE slug = 'tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTail Crash / Fox Rampage' WHERE slug = 'tail-crash-fox-rampage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTakion Summon' WHERE slug = 'takion-summon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTaming Wolf' WHERE slug = 'taming-wolf-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTarget Check' WHERE slug = 'target-check-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTarget Focus' WHERE slug = 'target-focus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTaurus' WHERE slug = 'taurus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTearer' WHERE slug = 'tearer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTease' WHERE slug = 'tease-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTemblor' WHERE slug = 'temblor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTempest Blow' WHERE slug = 'tempest-blow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTempest Roar' WHERE slug = 'tempest-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTemple Breaker' WHERE slug = 'temple-breaker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTen Blades - Mifuyu' WHERE slug = 'ten-blades-mifuyu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTen Blades' WHERE slug = 'ten-blades-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTenacity' WHERE slug = 'tenacity-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTenderaiser' WHERE slug = 'tenderaiser-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTeneritas' WHERE slug = 'teneritas-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTete' WHERE slug = 'tete-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThe Sieger' WHERE slug = 'the-sieger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThird Eye' WHERE slug = 'third-eye-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThorn Field' WHERE slug = 'thorn-field-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThroat Piercing' WHERE slug = 'throat-piercing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThrow Explosion' WHERE slug = 'throw-explosion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThrow Weapons' WHERE slug = 'throw-weapons-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThrowing Axe' WHERE slug = 'throwing-axe-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThunder Ball' WHERE slug = 'thunder-ball-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThunder Calling' WHERE slug = 'thunder-calling-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThunder Wave' WHERE slug = 'thunder-wave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThunderer' WHERE slug = 'thunderer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThunderstorm' WHERE slug = 'thunderstorm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTibetanus Demilune' WHERE slug = 'tibetanus-demilune-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTidy Road' WHERE slug = 'tidy-road-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTierra Choque' WHERE slug = 'tierra-choque-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTitan Bullet' WHERE slug = 'titan-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTop of Sail' WHERE slug = 'top-of-sail-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTorbellino' WHERE slug = 'torbellino-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTormentum' WHERE slug = 'tormentum-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTornado Blow' WHERE slug = 'tornado-blow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTornado Flare' WHERE slug = 'tornado-flare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTornado Holding' WHERE slug = 'tornado-holding-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTornado Shock' WHERE slug = 'tornado-shock-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTornado Storm' WHERE slug = 'tornado-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTornado Vortex' WHERE slug = 'tornado-vortex-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTotani / Giga Break' WHERE slug = 'totani-giga-break-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTotte' WHERE slug = 'totte-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนToxic Breath' WHERE slug = 'toxic-breath-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนToxic Ivy' WHERE slug = 'toxic-ivy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนToxic Reaction' WHERE slug = 'toxic-reaction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTransfix' WHERE slug = 'transfix-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTreasure Golem Summon' WHERE slug = 'treasure-golem-summon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTree of Rainbow' WHERE slug = 'tree-of-rainbow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTremendous' WHERE slug = 'tremendous-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTriangle Slash' WHERE slug = 'triangle-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrick Art!' WHERE slug = 'trick-art-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrigger' WHERE slug = 'trigger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrinor' WHERE slug = 'trinor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTriple Elements' WHERE slug = 'triple-elements-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTriple Firing' WHERE slug = 'triple-firing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTriskelion' WHERE slug = 'triskelion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTronada' WHERE slug = 'tronada-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrouble' WHERE slug = 'trouble-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrouble Storm' WHERE slug = 'trouble-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrue Sight' WHERE slug = 'true-sight-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrust' WHERE slug = 'trust-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTry Slash' WHERE slug = 'try-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTsunami of Nefyre' WHERE slug = 'tsunami-of-nefyre-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTumor' WHERE slug = 'tumor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTurning Bash' WHERE slug = 'turning-bash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTurning Force' WHERE slug = 'turning-force-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTurning Slash - Mifuyu' WHERE slug = 'turning-slash-mifuyu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTutana' WHERE slug = 'tutana-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTwo Soul Kick' WHERE slug = 'two-soul-kick-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTwo Swords Dance' WHERE slug = 'two-swords-dance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTyrant Storm' WHERE slug = 'tyrant-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUltimate Dash' WHERE slug = 'ultimate-dash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUndercovering Fire' WHERE slug = 'undercovering-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cannon-Turret Construction' WHERE slug = 'upgraded-cannon-turret-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Rotating Blade Construction' WHERE slug = 'upgraded-rotating-blade-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpper Slicer' WHERE slug = 'upper-slicer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpper Swing' WHERE slug = 'upper-swing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUtanira' WHERE slug = 'utanira-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนValentia' WHERE slug = 'valentia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนValer' WHERE slug = 'valer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVampiric Session' WHERE slug = 'vampiric-session-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVanishing Flare' WHERE slug = 'vanishing-flare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVeiren and Reape' WHERE slug = 'veiren-and-reape-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVelate' WHERE slug = 'velate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVelmas' WHERE slug = 'velmas-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVenom Blade' WHERE slug = 'venom-blade-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVentaja Ligera' WHERE slug = 'ventaja-ligera-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVertical Slash' WHERE slug = 'vertical-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVictor Control' WHERE slug = 'victor-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนViento Fantasma' WHERE slug = 'viento-fantasma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนViertus' WHERE slug = 'viertus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนViolent Shooting Star' WHERE slug = 'violent-shooting-star-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนViolent Shot' WHERE slug = 'violent-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนViolent Wind Attack' WHERE slug = 'violent-wind-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVioleta' WHERE slug = 'violeta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVirtuoso' WHERE slug = 'virtuoso-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoar' WHERE slug = 'voar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoid Elemental' WHERE slug = 'void-elemental-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoid Ponata' WHERE slug = 'void-ponata-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoid Secure' WHERE slug = 'void-secure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoid Spear' WHERE slug = 'void-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoid Vacum' WHERE slug = 'void-vacum-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoidness' WHERE slug = 'voidness-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVolcanic Eruption' WHERE slug = 'volcanic-eruption-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVolcanic Marcha' WHERE slug = 'volcanic-marcha-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVolition' WHERE slug = 'volition-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVolphir' WHERE slug = 'volphir-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoltage Shower' WHERE slug = 'voltage-shower-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoltec Drive' WHERE slug = 'voltec-drive-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVolunt' WHERE slug = 'volunt-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVon Larr' WHERE slug = 'von-larr-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVortex Slash' WHERE slug = 'vortex-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVortex Slicer' WHERE slug = 'vortex-slicer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVortex Spear' WHERE slug = 'vortex-spear-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWagenlenker' WHERE slug = 'wagenlenker-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWall of Curan' WHERE slug = 'wall-of-curan-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWalter Control' WHERE slug = 'walter-control-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWanted Action' WHERE slug = 'wanted-action-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWarrior Cross - Mifuyu' WHERE slug = 'warrior-cross-mifuyu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWarrior Cross' WHERE slug = 'warrior-cross-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWater Flakes Rising Circle' WHERE slug = 'water-flakes-rising-circle-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWater Wave' WHERE slug = 'water-wave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWave Illusion' WHERE slug = 'wave-illusion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWavering Fire' WHERE slug = 'wavering-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWeathering' WHERE slug = 'weathering-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWeb' WHERE slug = 'web-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWestraid' WHERE slug = 'westraid-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWhirlwind Blow' WHERE slug = 'whirlwind-blow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWhole Cancellation' WHERE slug = 'whole-cancellation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWild Flash' WHERE slug = 'wild-flash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWild Shot' WHERE slug = 'wild-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWill of the Warrior' WHERE slug = 'will-of-the-warrior-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWind Blow' WHERE slug = 'wind-blow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWind Pressure' WHERE slug = 'wind-pressure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWindstorm' WHERE slug = 'windstorm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWire Prisoner' WHERE slug = 'wire-prisoner-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWire Shot' WHERE slug = 'wire-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWise Shots' WHERE slug = 'wise-shots-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWish' WHERE slug = 'wish-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนZenith' WHERE slug = 'zenith-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนZeppelin Attack' WHERE slug = 'zeppelin-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนZero Defect' WHERE slug = 'zero-defect-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนZero-In' WHERE slug = 'zero-in-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน+10 Oscuras Absolute (1 วัน)' WHERE slug = '10-oscuras-absolute-ring-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน+10 Queen of Valkyries Blue (1 วัน)' WHERE slug = '10-queen-of-valkyries-blue-ring-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน+10 Talos (1 วัน)' WHERE slug = '10-talos-ring-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน+10 Viscount Montoros (1 วัน)' WHERE slug = '10-viscount-montoros-ring-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAuto Barons' WHERE slug = 'auto-barons-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBeast Master' WHERE slug = 'beast-master-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDemon Hunter' WHERE slug = 'demon-hunter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExecutioner' WHERE slug = 'executioner-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGoddess Giltines Demonic' WHERE slug = 'goddess-giltines-demonic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGoddess Laimas Holy' WHERE slug = 'goddess-laimas-holy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIllusionary Auto Baron' WHERE slug = 'illusionary-auto-baron-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIllusionary Oscuras Absolute' WHERE slug = 'illusionary-oscuras-absolute-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIllusionary Talos' WHERE slug = 'illusionary-talos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIllusionary Viscount Montoros' WHERE slug = 'illusionary-viscount-montoros-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOscuras Absolute' WHERE slug = 'oscuras-absolute-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRusty Goddess Giltines Demonic (7 วัน)' WHERE slug = 'rusty-goddess-giltines-demonic-ring-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRusty Goddess Laimas Holy (7 วัน)' WHERE slug = 'rusty-goddess-laimas-holy-ring-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTalos' WHERE slug = 'talos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTruman Inanimate' WHERE slug = 'truman-inanimate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTurn Undead' WHERE slug = 'turn-undead-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVigilar Tribes' WHERE slug = 'vigilar-tribes-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVigilar Tribes (อีเวนต์)' WHERE slug = 'vigilar-tribes-ring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนViscount Montoro' WHERE slug = 'viscount-montoro-ring' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] แหวนGoddess Giltines Demonic' WHERE slug = 'event-goddess-giltines-demonic-ring' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] แหวนGoddess Laimas Holy' WHERE slug = 'event-goddess-laimas-holy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAbyss Bear Spinel' WHERE slug = 'abyss-bear-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAbyss Cray' WHERE slug = 'abyss-cray' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAbyss Grizzly Spinel' WHERE slug = 'abyss-grizzly-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAbyss Maddie' WHERE slug = 'abyss-maddie' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAbyss Soldier Spinel' WHERE slug = 'abyss-soldier-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAbyss Wolf Spinel' WHERE slug = 'abyss-wolf-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAbyssal Claw Spinel' WHERE slug = 'abyssal-claw-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAchorchado Amber (Anti-Magic Shell)' WHERE slug = 'achorchado-amber-anti-magic-shell' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAchorchado Amber (Fortify)' WHERE slug = 'achorchado-amber-fortify' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAngry Acorchado Spinel' WHERE slug = 'angry-acorchado-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAnteater Amber' WHERE slug = 'anteater-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนArop Amber' WHERE slug = 'arop-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนArop Spinel' WHERE slug = 'arop-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAuto Baron Spinel' WHERE slug = 'auto-baron-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนAvalanche Apparition Spinel' WHERE slug = 'avalanche-apparition-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBear Worker Amber' WHERE slug = 'bear-worker-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBig Encyclopedia Spinel' WHERE slug = 'big-encyclopedia-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBigfoot Amber' WHERE slug = 'bigfoot-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBlade Antelope Amber' WHERE slug = 'blade-antelope-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBlood Navy, Castleone' WHERE slug = 'blood-navy-castleone' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBlood Navy, Zero Mirror Spinel' WHERE slug = 'blood-navy-zero-mirror-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBuffalo Amber' WHERE slug = 'buffalo-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBuffalo Spinel' WHERE slug = 'buffalo-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนBuppet Amber' WHERE slug = 'buppet-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCandler Spinel' WHERE slug = 'candler-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCannon Tortoise Amber' WHERE slug = 'cannon-tortoise-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCannon Tortoise Spinel' WHERE slug = 'cannon-tortoise-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCaptain Capybara Spinel' WHERE slug = 'captain-capybara-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCastor Amber' WHERE slug = 'castor-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCastor Spinel' WHERE slug = 'castor-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCelegrim Worm Amber' WHERE slug = 'celegrim-worm-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCerbera Amber' WHERE slug = 'cerbera-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCerbera Spinel' WHERE slug = 'cerbera-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนChristmas Tree' WHERE slug = 'christmas-tree' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนClaw Amber' WHERE slug = 'claw-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCockatrice Amber' WHERE slug = 'cockatrice-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCockatrice Spinel' WHERE slug = 'cockatrice-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนComodo Amber' WHERE slug = 'comodo-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนComodo Spinel' WHERE slug = 'comodo-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCorrupt Battle Soldier''s Spinel' WHERE slug = 'corrupt-battle-soldiers-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCorrupt Shield Soldier''s Spinel' WHERE slug = 'corrupt-shield-soldiers-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนCrocodien Amber' WHERE slug = 'crocodien-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDandelion Swamp Monkey Amber' WHERE slug = 'dandelion-swamp-monkey-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDandelion Swamp Monkey Spinel' WHERE slug = 'dandelion-swamp-monkey-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDemon Amber' WHERE slug = 'demon-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDiseased Capybara Amber' WHERE slug = 'diseased-capybara-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDiseased Capybara Leader Spinel' WHERE slug = 'diseased-capybara-leader-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDiseased Capybara Ranger Amber' WHERE slug = 'diseased-capybara-ranger-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDiseased Capybara Warrior Amber' WHERE slug = 'diseased-capybara-warrior-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDoggy Panzer Amber' WHERE slug = 'doggy-panzer-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDoggy Panzer Spinel' WHERE slug = 'doggy-panzer-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDread Anchor Amber' WHERE slug = 'dread-anchor-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDread Anchor Spinel' WHERE slug = 'dread-anchor-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDumanon Amber' WHERE slug = 'dumanon-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนDumanon Spinel' WHERE slug = 'dumanon-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEater of the Queen Eggs Spinel' WHERE slug = 'eater-of-the-queen-eggs-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEater of the Queen Legs Spinel' WHERE slug = 'eater-of-the-queen-legs-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEater of the Queen Torso Spinel' WHERE slug = 'eater-of-the-queen-torso-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEigleschvarlier Amber' WHERE slug = 'eigleschvarlier-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEigleschvarlier Spinel' WHERE slug = 'eigleschvarlier-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนElcinos Amber' WHERE slug = 'elcinos-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEligo Amber' WHERE slug = 'eligo-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนElite Lightning Cockatrice Spinel' WHERE slug = 'elite-lightning-cockatrice-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนElite Vampire Bat Lord Spinel' WHERE slug = 'elite-vampire-bat-lord-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนElmorc Spinel' WHERE slug = 'elmorc-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEltetah Amber' WHERE slug = 'eltetah-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนElviot Amber' WHERE slug = 'elviot-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEripmav Amber' WHERE slug = 'eripmav-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEripmav Spinel' WHERE slug = 'eripmav-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนErrac Soldier Instructions' WHERE slug = 'errac-soldier-instructions' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEscudo Pecher Amber' WHERE slug = 'escudo-pecher-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEscudo Pecher Spinel' WHERE slug = 'escudo-pecher-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEscudo Prefer Amber' WHERE slug = 'escudo-prefer-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEvent Spinel 1' WHERE slug = 'event-spinel-1' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEvent Spinel 2' WHERE slug = 'event-spinel-2' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEvent Spinel 3' WHERE slug = 'event-spinel-3' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนEvent Spinel 4' WHERE slug = 'event-spinel-4' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนExiled Valkyrie Spinel' WHERE slug = 'exiled-valkyrie-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFanatic Amber' WHERE slug = 'fanatic-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFanatic Spinel' WHERE slug = 'fanatic-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFootman Amber' WHERE slug = 'footman-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFootman Spinel' WHERE slug = 'footman-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFrenzy Amber' WHERE slug = 'frenzy-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFrenzy Spinel' WHERE slug = 'frenzy-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFrogfish Spinel' WHERE slug = 'frogfish-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFrogfish Spinel (อีเวนต์)' WHERE slug = 'frogfish-spinel-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFury Griffon Leader Spinel' WHERE slug = 'fury-griffon-leader-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFury Griffon Spinel' WHERE slug = 'fury-griffon-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนFury Vergo the Cursed Spinel' WHERE slug = 'fury-vergo-the-cursed-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGahbirus Amber' WHERE slug = 'gahbirus-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGahbirus Spinel' WHERE slug = 'gahbirus-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGargoyle Spinel' WHERE slug = 'gargoyle-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGavi di Gavi Amber' WHERE slug = 'gavi-di-gavi-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGavi di Gavi Spinel' WHERE slug = 'gavi-di-gavi-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGavi di Light Amber' WHERE slug = 'gavi-di-light-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGehcos Amber' WHERE slug = 'gehcos-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGehcos Spinel' WHERE slug = 'gehcos-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGeneral Deus Machina Spinel' WHERE slug = 'general-deus-machina-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGeneral Guard Spinel' WHERE slug = 'general-guard-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGhost Baron Amber' WHERE slug = 'ghost-baron-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGhost Baron Spinel' WHERE slug = 'ghost-baron-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGhostly Father Amber' WHERE slug = 'ghostly-father-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGhostly Father Spinel' WHERE slug = 'ghostly-father-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGiant Amber' WHERE slug = 'giant-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGiant Comodo Amber' WHERE slug = 'giant-comodo-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGiant Comodo Spinel' WHERE slug = 'giant-comodo-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGiant Spinel' WHERE slug = 'giant-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGolden Spider Amber' WHERE slug = 'golden-spider-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGolden Spider Spinel' WHERE slug = 'golden-spider-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGrabber Amber' WHERE slug = 'grabber-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGray Wolf Boss Spinel' WHERE slug = 'gray-wolf-boss-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGrim Reaper Leader Spinel' WHERE slug = 'grim-reaper-leader-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGrim-Reaper Amber' WHERE slug = 'grim-reaper-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนGrim-ripper Spinel' WHERE slug = 'grim-ripper-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHelena Amber' WHERE slug = 'helena-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHelena Spinel' WHERE slug = 'helena-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHell Hound Spinel' WHERE slug = 'hell-hound-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHeretic Amber' WHERE slug = 'heretic-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHeretic Spinel' WHERE slug = 'heretic-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHoney Spider Amber' WHERE slug = 'honey-spider-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHoney Spider Spinel' WHERE slug = 'honey-spider-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHornet Spinel' WHERE slug = 'hornet-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHound Amber' WHERE slug = 'hound-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHound-eater Amber' WHERE slug = 'hound-eater-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนHound-eater Spinel' WHERE slug = 'hound-eater-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนImanon Amber' WHERE slug = 'imanon-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนImanon Spinel' WHERE slug = 'imanon-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนImoogi Spinel' WHERE slug = 'imoogi-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนIron Maiden Amber' WHERE slug = 'iron-maiden-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนIron Maiden Spinel' WHERE slug = 'iron-maiden-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนJabberwock Amber' WHERE slug = 'jabberwock-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนJabberwock Spinel' WHERE slug = 'jabberwock-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนJaquin Bear Amber' WHERE slug = 'jaquin-bear-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนJaquin Bear Spinel' WHERE slug = 'jaquin-bear-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนJormongand Spinel' WHERE slug = 'jormongand-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนJumeau Plaque Amber' WHERE slug = 'jumeau-plaque-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนJumeau Plaque Spinel' WHERE slug = 'jumeau-plaque-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนKing Henry Spinel' WHERE slug = 'king-henry-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนKing of Greed Spinel' WHERE slug = 'king-of-greed-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLarval Dragonwasp Amber' WHERE slug = 'larval-dragonwasp-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLarval Dragonwasp Spinel' WHERE slug = 'larval-dragonwasp-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLazim-Lam Amber' WHERE slug = 'lazim-lam-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLazim-Lam Spinel' WHERE slug = 'lazim-lam-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLeafing Croc Amber' WHERE slug = 'leafing-croc-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLeafing Croc Spinel' WHERE slug = 'leafing-croc-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLloyd Amber' WHERE slug = 'lloyd-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLloyd Spinel' WHERE slug = 'lloyd-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนLocke Amber' WHERE slug = 'locke-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMahrgorp Amber' WHERE slug = 'mahrgorp-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMandradora Amber' WHERE slug = 'mandradora-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMandradora Spinel' WHERE slug = 'mandradora-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMarcurse Amber' WHERE slug = 'marcurse-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMarcurse Spinel' WHERE slug = 'marcurse-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMasquerader Amber' WHERE slug = 'masquerader-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMasquerader Spinel' WHERE slug = 'masquerader-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMeatenderiser Spinel' WHERE slug = 'meatenderiser-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMedusa Spinel' WHERE slug = 'medusa-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMerman Amber' WHERE slug = 'merman-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMerman Spinel' WHERE slug = 'merman-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMighty Victor Spinel' WHERE slug = 'mighty-victor-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMinotauros Spinel' WHERE slug = 'minotauros-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMufasa Spinel' WHERE slug = 'mufasa-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMusescargot Amber' WHERE slug = 'musescargot-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMusescargot Spinel' WHERE slug = 'musescargot-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMystic Amber' WHERE slug = 'mystic-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนMystic Spinel' WHERE slug = 'mystic-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนNevare Amber' WHERE slug = 'nevare-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนNevare Spinel' WHERE slug = 'nevare-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนNosiar Amber' WHERE slug = 'nosiar-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนNosiar Spinel' WHERE slug = 'nosiar-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนOctopus Amber' WHERE slug = 'octopus-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนOctopus Spinel' WHERE slug = 'octopus-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนParasol' WHERE slug = 'parasol' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPasiar Amber' WHERE slug = 'pasiar-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPasiar Spinel' WHERE slug = 'pasiar-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPhobitan Amber' WHERE slug = 'phobitan-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPhobitan Chieftain Amber' WHERE slug = 'phobitan-chieftain-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPhobitan Chieftain Spinel' WHERE slug = 'phobitan-chieftain-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPhobitan General' WHERE slug = 'phobitan-general' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPhobitan Rogue Amber' WHERE slug = 'phobitan-rogue-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPhobitan Rogue Spinel' WHERE slug = 'phobitan-rogue-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPhobitan Spinel' WHERE slug = 'phobitan-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPoisonous Red Mandradora Spinel' WHERE slug = 'poisonous-red-mandradora-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPollux Amber' WHERE slug = 'pollux-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนPollux Spinel' WHERE slug = 'pollux-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนQueen Bee Spinel' WHERE slug = 'queen-bee-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนRaptor Amber' WHERE slug = 'raptor-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนRaptor Spinel' WHERE slug = 'raptor-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนRufus faux Amber' WHERE slug = 'rufus-faux-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนRufus faux Spinel' WHERE slug = 'rufus-faux-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSabel Tiger Amber' WHERE slug = 'sabel-tiger-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSabel Tiger Spinel' WHERE slug = 'sabel-tiger-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSabreboar Amber' WHERE slug = 'sabreboar-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSabreboar Spinel' WHERE slug = 'sabreboar-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSasha Amber' WHERE slug = 'sasha-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSasha Spinel' WHERE slug = 'sasha-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Amber' WHERE slug = 'skeleton-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Attacker Amber' WHERE slug = 'skeleton-attacker-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Defender Amber' WHERE slug = 'skeleton-defender-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Footman Amber' WHERE slug = 'skeleton-footman-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Footman Spinel' WHERE slug = 'skeleton-footman-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Mage Amber' WHERE slug = 'skeleton-mage-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Raptor Amber' WHERE slug = 'skeleton-raptor-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Raptor Spinel' WHERE slug = 'skeleton-raptor-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Villain Amber' WHERE slug = 'skeleton-villain-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Villain Spinel' WHERE slug = 'skeleton-villain-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Warrior Amber' WHERE slug = 'skeleton-warrior-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSkeleton Warrior Spinel' WHERE slug = 'skeleton-warrior-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSloth Spinel' WHERE slug = 'sloth-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSnowman' WHERE slug = 'snowman' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSphinx Spinel' WHERE slug = 'sphinx-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSpinel : Event1' WHERE slug = 'spinel-event1' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSpinel : Event2' WHERE slug = 'spinel-event2' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSpinel : Event3' WHERE slug = 'spinel-event3' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSpinel : Event4' WHERE slug = 'spinel-event4' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSpinel : Event5' WHERE slug = 'spinel-event5' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนStarShip No.142 Spinel' WHERE slug = 'starship-no-142-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนStarter No.122 Spinel' WHERE slug = 'starter-no-122-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนSteamer Spinel' WHERE slug = 'steamer-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTaikbin Spinel' WHERE slug = 'taikbin-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTaurus Amber' WHERE slug = 'taurus-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนThief Bully Amber' WHERE slug = 'thief-bully-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนThief Captain Capri Spinel' WHERE slug = 'thief-captain-capri-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนThief Edward Amber' WHERE slug = 'thief-edward-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนThoracotomy Amber' WHERE slug = 'thoracotomy-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนThoracotomy Spinel' WHERE slug = 'thoracotomy-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTorchere Spinel' WHERE slug = 'torchere-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTortoise Amber' WHERE slug = 'tortoise-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTortoise Spinel' WHERE slug = 'tortoise-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTwin-head Amber' WHERE slug = 'twin-head-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTwin-head Spinel' WHERE slug = 'twin-head-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTyrannosaurus Amber' WHERE slug = 'tyrannosaurus-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนTyrannosaurus Spinel' WHERE slug = 'tyrannosaurus-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนUraeus Egg Spinel' WHERE slug = 'uraeus-egg-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนUraeus Minion Spinel' WHERE slug = 'uraeus-minion-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVedanobah Amber' WHERE slug = 'vedanobah-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVedanobah Rogue Amber' WHERE slug = 'vedanobah-rogue-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVedanobah Rogue Spinel' WHERE slug = 'vedanobah-rogue-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVedanobah Spinel' WHERE slug = 'vedanobah-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVictor Amber' WHERE slug = 'victor-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVictor Spinel' WHERE slug = 'victor-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนViolent Geckos Spinel' WHERE slug = 'violent-geckos-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนViolent Mahrgorp Amber' WHERE slug = 'violent-mahrgorp-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVisage Amber' WHERE slug = 'visage-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVisage Spinel' WHERE slug = 'visage-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVladimir Amber' WHERE slug = 'vladimir-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนVladimir Spinel' WHERE slug = 'vladimir-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWahlansche Amber' WHERE slug = 'wahlansche-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWahlansche Spinel' WHERE slug = 'wahlansche-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWalter Amber' WHERE slug = 'walter-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWalter Spinel' WHERE slug = 'walter-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWasp Amber' WHERE slug = 'wasp-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWasp Spinel' WHERE slug = 'wasp-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWeird-knight Amber' WHERE slug = 'weird-knight-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWeird-knight Spinel' WHERE slug = 'weird-knight-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWild-Dog Amber' WHERE slug = 'wild-dog-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWild-Dog Spinel' WHERE slug = 'wild-dog-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWolf Amber' WHERE slug = 'wolf-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนWolf Spinel' WHERE slug = 'wolf-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนZavi di Gavi Amber' WHERE slug = 'zavi-di-gavi-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนZavi di Gavi Spinel' WHERE slug = 'zavi-di-gavi-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนZealot Amber' WHERE slug = 'zealot-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนZealot Spinel' WHERE slug = 'zealot-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนZebra-eater Amber' WHERE slug = 'zebra-eater-amber' AND name_th IS NULL;
UPDATE items SET name_th = 'ซัมมอนZebra-eater Spinel' WHERE slug = 'zebra-eater-spinel' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDark Saints Enhanced Tactics' WHERE slug = 'dark-saints-enhanced-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHealers Enhanced Tactics' WHERE slug = 'healers-enhanced-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMarionette Enhanced Tactics' WHERE slug = 'marionette-enhanced-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPure Enhanced Tactics' WHERE slug = 'pure-enhanced-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนScouts Enhanced Tactics' WHERE slug = 'scouts-enhanced-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Abyss' WHERE slug = 'upgraded-abyss-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Activator' WHERE slug = 'upgraded-activator-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Advance Garde' WHERE slug = 'upgraded-advance-garde-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Advance Garde of Grim' WHERE slug = 'upgraded-advance-garde-of-grim-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Adventure' WHERE slug = 'upgraded-adventure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Aggressive Shot' WHERE slug = 'upgraded-aggressive-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Aiming Shot' WHERE slug = 'upgraded-aiming-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Alchemy' WHERE slug = 'upgraded-alchemy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ambrosia / Icy Ambrosia' WHERE slug = 'upgraded-ambrosia-icy-ambrosia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Amicus' WHERE slug = 'upgraded-amicus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Anathema' WHERE slug = 'upgraded-anathema-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ancient Bullet' WHERE slug = 'upgraded-ancient-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ancient Elemental' WHERE slug = 'upgraded-ancient-elemental-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ancient Guard' WHERE slug = 'upgraded-ancient-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ancient Spirit' WHERE slug = 'upgraded-ancient-spirit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ancient Tactics' WHERE slug = 'upgraded-ancient-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Arbalester' WHERE slug = 'upgraded-arbalester-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Arch Sting' WHERE slug = 'upgraded-arch-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Architecture' WHERE slug = 'upgraded-architecture-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Arma' WHERE slug = 'upgraded-arma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Arnis' WHERE slug = 'upgraded-arnis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Atlas' WHERE slug = 'upgraded-atlas-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Aurel Lupus' WHERE slug = 'upgraded-aurel-lupus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Back Guard - Mifuyu' WHERE slug = 'upgraded-back-guard-mifuyu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Back-Guard' WHERE slug = 'upgraded-back-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Barbatos' WHERE slug = 'upgraded-barbatos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Barisada' WHERE slug = 'upgraded-barisada-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Battle Cook' WHERE slug = 'upgraded-battle-cook-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Battle Smith' WHERE slug = 'upgraded-battle-smith-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Beast' WHERE slug = 'upgraded-beast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Beginners Luck' WHERE slug = 'upgraded-beginners-luck-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Black Cat' WHERE slug = 'upgraded-black-cat-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Blandir Cruz' WHERE slug = 'upgraded-blandir-cruz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Blazing Blast' WHERE slug = 'upgraded-blazing-blast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Blitz Assault' WHERE slug = 'upgraded-blitz-assault-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Bloody Feast' WHERE slug = 'upgraded-bloody-feast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Bloody Punisher' WHERE slug = 'upgraded-bloody-punisher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Bloody Rose' WHERE slug = 'upgraded-bloody-rose-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Bluff' WHERE slug = 'upgraded-bluff-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Book Of Earth' WHERE slug = 'upgraded-book-of-earth-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Book Of Fire' WHERE slug = 'upgraded-book-of-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Book Of Ice' WHERE slug = 'upgraded-book-of-ice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Book of Flow' WHERE slug = 'upgraded-book-of-flow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Book of Lightning' WHERE slug = 'upgraded-book-of-lightning-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Boost Magic' WHERE slug = 'upgraded-boost-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Brandish Arm' WHERE slug = 'upgraded-brandish-arm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cannon Shooter' WHERE slug = 'upgraded-cannon-shooter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Carrier' WHERE slug = 'upgraded-carrier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cast Net' WHERE slug = 'upgraded-cast-net-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cats Eye' WHERE slug = 'upgraded-cats-eye-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cauchemar' WHERE slug = 'upgraded-cauchemar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Chapter of Mind' WHERE slug = 'upgraded-chapter-of-mind-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Chapter of Wind' WHERE slug = 'upgraded-chapter-of-wind-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cherry blossoms dancing' WHERE slug = 'upgraded-cherry-blossoms-dancing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Clabuster' WHERE slug = 'upgraded-clabuster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cleaning Time' WHERE slug = 'upgraded-cleaning-time-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cluster' WHERE slug = 'upgraded-cluster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cobra' WHERE slug = 'upgraded-cobra-ring' AND name_th IS NULL;