-- Migration 061: Thai names batch 8/10
-- Generated: 2026-03-16T03:42:16.054Z

UPDATE items SET name_th = 'แหวนUpgraded Combat Assault' WHERE slug = 'upgraded-combat-assault-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Combat Medicine' WHERE slug = 'upgraded-combat-medicine-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Combatant' WHERE slug = 'upgraded-combatant-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Concentration' WHERE slug = 'upgraded-concentration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Construction' WHERE slug = 'upgraded-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Conviction' WHERE slug = 'upgraded-conviction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Corsair' WHERE slug = 'upgraded-corsair-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Coruscation' WHERE slug = 'upgraded-coruscation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Creacion' WHERE slug = 'upgraded-creacion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Croisement' WHERE slug = 'upgraded-croisement-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cure' WHERE slug = 'upgraded-cure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Cutlass' WHERE slug = 'upgraded-cutlass-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Dadamos' WHERE slug = 'upgraded-dadamos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Dagger Polish' WHERE slug = 'upgraded-dagger-polish-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Dark Avenger' WHERE slug = 'upgraded-dark-avenger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Dark Lord' WHERE slug = 'upgraded-dark-lord-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Dark Penalty' WHERE slug = 'upgraded-dark-penalty-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Darkness' WHERE slug = 'upgraded-darkness-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Death Chopping' WHERE slug = 'upgraded-death-chopping-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Death Shadow Ninjutsu' WHERE slug = 'upgraded-death-shadow-ninjutsu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Defend Mode' WHERE slug = 'upgraded-defend-mode-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Defending Guard' WHERE slug = 'upgraded-defending-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Defending Shot' WHERE slug = 'upgraded-defending-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Defensive Construction' WHERE slug = 'upgraded-defensive-construction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Demolition Burst' WHERE slug = 'upgraded-demolition-burst-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Demolition Roar' WHERE slug = 'upgraded-demolition-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Desire' WHERE slug = 'upgraded-desire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Destino' WHERE slug = 'upgraded-destino-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Destroyer Mode' WHERE slug = 'upgraded-destroyer-mode-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Destroyer' WHERE slug = 'upgraded-destroyer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Detection' WHERE slug = 'upgraded-detection-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Diable' WHERE slug = 'upgraded-diable-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Distortion Cube' WHERE slug = 'upgraded-distortion-cube-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Dobalada corte' WHERE slug = 'upgraded-dobalada-corte-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Doll Curse' WHERE slug = 'upgraded-doll-curse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Dominate the Sky' WHERE slug = 'upgraded-dominate-the-sky-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Domination Fire' WHERE slug = 'upgraded-domination-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Domination Ice' WHERE slug = 'upgraded-domination-ice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Domination Lightning' WHERE slug = 'upgraded-domination-lightning-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Double-Gun Shot' WHERE slug = 'upgraded-double-gun-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Drawing' WHERE slug = 'upgraded-drawing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Drunken' WHERE slug = 'upgraded-drunken-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Dual Blaster' WHERE slug = 'upgraded-dual-blaster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded ESP' WHERE slug = 'upgraded-esp-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Eagle Crow' WHERE slug = 'upgraded-eagle-crow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Earth Mental Attack' WHERE slug = 'upgraded-earth-mental-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Edge' WHERE slug = 'upgraded-edge-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Efreet' WHERE slug = 'upgraded-efreet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Electrica billar' WHERE slug = 'upgraded-electrica-billar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Electronic Hare' WHERE slug = 'upgraded-electronic-hare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Electronic Kats' WHERE slug = 'upgraded-electronic-kats-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Elegance' WHERE slug = 'upgraded-elegance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Elemental Master' WHERE slug = 'upgraded-elemental-master-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Elemental Penetration' WHERE slug = 'upgraded-elemental-penetration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Enchanted Arm' WHERE slug = 'upgraded-enchanted-arm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Encore' WHERE slug = 'upgraded-encore-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Encounter shot' WHERE slug = 'upgraded-encounter-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Enhanced Tactics' WHERE slug = 'upgraded-enhanced-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Epee Garde' WHERE slug = 'upgraded-epee-garde-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Epee Garde of Grim' WHERE slug = 'upgraded-epee-garde-of-grim-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Epee Glacier' WHERE slug = 'upgraded-epee-glacier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Equites' WHERE slug = 'upgraded-equites-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Escrima' WHERE slug = 'upgraded-escrima-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Esparu' WHERE slug = 'upgraded-esparu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ever' WHERE slug = 'upgraded-ever-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Evocation Fire' WHERE slug = 'upgraded-evocation-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Evocation Ice' WHERE slug = 'upgraded-evocation-ice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Evocation Lightning' WHERE slug = 'upgraded-evocation-lightning-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Expire' WHERE slug = 'upgraded-expire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Extreme Punisher' WHERE slug = 'upgraded-extreme-punisher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Fantastic' WHERE slug = 'upgraded-fantastic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Fast Thinking' WHERE slug = 'upgraded-fast-thinking-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Fatal Blues' WHERE slug = 'upgraded-fatal-blues-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Fate Sentence' WHERE slug = 'upgraded-fate-sentence-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Femme Fatale' WHERE slug = 'upgraded-femme-fatale-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded FeralRoar' WHERE slug = 'upgraded-feralroar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Field Manual' WHERE slug = 'upgraded-field-manual-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Filo' WHERE slug = 'upgraded-filo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded First Aid' WHERE slug = 'upgraded-first-aid-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Flame Order' WHERE slug = 'upgraded-flame-order-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Flame Roar' WHERE slug = 'upgraded-flame-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Flame-Guard' WHERE slug = 'upgraded-flame-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Flare' WHERE slug = 'upgraded-flare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Fleuret Glacier' WHERE slug = 'upgraded-fleuret-glacier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Flintlock' WHERE slug = 'upgraded-flintlock-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Floresta' WHERE slug = 'upgraded-floresta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Flos' WHERE slug = 'upgraded-flos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Flying Shadow Ninjutsu' WHERE slug = 'upgraded-flying-shadow-ninjutsu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Folclore' WHERE slug = 'upgraded-folclore-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Forgotten Magic' WHERE slug = 'upgraded-forgotten-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Fortitudo' WHERE slug = 'upgraded-fortitudo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Freestyle Shot' WHERE slug = 'upgraded-freestyle-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Freeze Over' WHERE slug = 'upgraded-freeze-over-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Frenzy' WHERE slug = 'upgraded-frenzy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Fretensis' WHERE slug = 'upgraded-fretensis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Frontier' WHERE slug = 'upgraded-frontier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Frost' WHERE slug = 'upgraded-frost-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Furious' WHERE slug = 'upgraded-furious-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Gae Bulg' WHERE slug = 'upgraded-gae-bulg-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Gatling Empowerment' WHERE slug = 'upgraded-gatling-empowerment-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Geirskogul' WHERE slug = 'upgraded-geirskogul-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Gemma' WHERE slug = 'upgraded-gemma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Gigantic Blaster' WHERE slug = 'upgraded-gigantic-blaster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Gigantic Marksmanship' WHERE slug = 'upgraded-gigantic-marksmanship-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Goliath' WHERE slug = 'upgraded-goliath-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Gorgeous' WHERE slug = 'upgraded-gorgeous-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Grave' WHERE slug = 'upgraded-grave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Grill' WHERE slug = 'upgraded-grill-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Grim Guard' WHERE slug = 'upgraded-grim-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Grim-Ripper' WHERE slug = 'upgraded-grim-ripper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Grinding' WHERE slug = 'upgraded-grinding-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Guardian Structure' WHERE slug = 'upgraded-guardian-structure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Gun Master' WHERE slug = 'upgraded-gun-master-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Gun-Maestro' WHERE slug = 'upgraded-gun-maestro-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Hack and Slash' WHERE slug = 'upgraded-hack-and-slash-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Hanging Guard' WHERE slug = 'upgraded-hanging-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Healing' WHERE slug = 'upgraded-healing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Heaven and Hell of Grim' WHERE slug = 'upgraded-heaven-and-hell-of-grim-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Heaven or Hell' WHERE slug = 'upgraded-heaven-or-hell-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Heavy Stinger' WHERE slug = 'upgraded-heavy-stinger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Hermetisme' WHERE slug = 'upgraded-hermetisme-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded High Class' WHERE slug = 'upgraded-high-class-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded High Tide' WHERE slug = 'upgraded-high-tide-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded High-Guard' WHERE slug = 'upgraded-high-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Highlander Soul' WHERE slug = 'upgraded-highlander-soul-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Holy Aura' WHERE slug = 'upgraded-holy-aura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Holy Shielder' WHERE slug = 'upgraded-holy-shielder-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Hunting Blaster' WHERE slug = 'upgraded-hunting-blaster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Hwoarang Spirits' WHERE slug = 'upgraded-hwoarang-spirits-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ice Crown' WHERE slug = 'upgraded-ice-crown-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Illusion Garde' WHERE slug = 'upgraded-illusion-garde-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Illusion Gunner' WHERE slug = 'upgraded-illusion-gunner-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Imperial Guardian' WHERE slug = 'upgraded-imperial-guardian-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Imperial Tactics' WHERE slug = 'upgraded-imperial-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Incantation' WHERE slug = 'upgraded-incantation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Incantation of 3 Mudras' WHERE slug = 'upgraded-incantation-of-3-mudras-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Incursio' WHERE slug = 'upgraded-incursio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Indicacion' WHERE slug = 'upgraded-indicacion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Infernal Burn' WHERE slug = 'upgraded-infernal-burn-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Inferno' WHERE slug = 'upgraded-inferno-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Infierno Guard' WHERE slug = 'upgraded-infierno-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Infiltration' WHERE slug = 'upgraded-infiltration-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Innocentio' WHERE slug = 'upgraded-innocentio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Inroad Shot' WHERE slug = 'upgraded-inroad-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Install trap' WHERE slug = 'upgraded-install-trap-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Intoxication' WHERE slug = 'upgraded-intoxication-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Invertir' WHERE slug = 'upgraded-invertir-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Istion' WHERE slug = 'upgraded-istion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Justice' WHERE slug = 'upgraded-justice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Karima' WHERE slug = 'upgraded-karima-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Kings Majesty' WHERE slug = 'upgraded-kings-majesty-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Kneeling Shot' WHERE slug = 'upgraded-kneeling-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Lama' WHERE slug = 'upgraded-lama-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Leadership' WHERE slug = 'upgraded-leadership-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Leviathan Roar' WHERE slug = 'upgraded-leviathan-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Levitation' WHERE slug = 'upgraded-levitation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Lord-of-Death' WHERE slug = 'upgraded-lord-of-death-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Low Guard - Mifuyu' WHERE slug = 'upgraded-low-guard-mifuyu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Low-guard' WHERE slug = 'upgraded-low-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Luxuria' WHERE slug = 'upgraded-luxuria-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Machina' WHERE slug = 'upgraded-machina-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Madness' WHERE slug = 'upgraded-madness-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Maiden of Glacier' WHERE slug = 'upgraded-maiden-of-glacier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Main-Gauche Garde' WHERE slug = 'upgraded-main-gauche-garde-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Main-Gauche Garde of Grim' WHERE slug = 'upgraded-main-gauche-garde-of-grim-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Maketau' WHERE slug = 'upgraded-maketau-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Malediction' WHERE slug = 'upgraded-malediction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Manipulation' WHERE slug = 'upgraded-manipulation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Marionette' WHERE slug = 'upgraded-marionette-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Martial Arts Compendium' WHERE slug = 'upgraded-martial-arts-compendium-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Maskmanship' WHERE slug = 'upgraded-maskmanship-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Mass Healing' WHERE slug = 'upgraded-mass-healing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Matileo' WHERE slug = 'upgraded-matileo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Melt Armor' WHERE slug = 'upgraded-melt-armor-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Melt Weapon' WHERE slug = 'upgraded-melt-weapon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Memorise' WHERE slug = 'upgraded-memorise-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Mensa' WHERE slug = 'upgraded-mensa-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Messiah' WHERE slug = 'upgraded-messiah-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Middle-Guard' WHERE slug = 'upgraded-middle-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Middle-Guard Spirit' WHERE slug = 'upgraded-middle-guard-spirit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Mighty Cruz' WHERE slug = 'upgraded-mighty-cruz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Mind Steal' WHERE slug = 'upgraded-mind-steal-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Minstrel' WHERE slug = 'upgraded-minstrel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Mythos' WHERE slug = 'upgraded-mythos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Naraka' WHERE slug = 'upgraded-naraka-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Nature' WHERE slug = 'upgraded-nature-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Nine Tails' WHERE slug = 'upgraded-nine-tails-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Novice Guard' WHERE slug = 'upgraded-novice-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Novice Marksmanship' WHERE slug = 'upgraded-novice-marksmanship-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Occult Assistance' WHERE slug = 'upgraded-occult-assistance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Occult Magic' WHERE slug = 'upgraded-occult-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Outrage Shot' WHERE slug = 'upgraded-outrage-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Panther' WHERE slug = 'upgraded-panther-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Peltast' WHERE slug = 'upgraded-peltast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Penetrar Cruz' WHERE slug = 'upgraded-penetrar-cruz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Piracy' WHERE slug = 'upgraded-piracy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Placidez' WHERE slug = 'upgraded-placidez-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Plow-Guard' WHERE slug = 'upgraded-plow-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Possession Fire' WHERE slug = 'upgraded-possession-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Possession Ice' WHERE slug = 'upgraded-possession-ice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Possession Lightning' WHERE slug = 'upgraded-possession-lightning-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Power Absinia' WHERE slug = 'upgraded-power-absinia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Prelude' WHERE slug = 'upgraded-prelude-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Prid' WHERE slug = 'upgraded-prid-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Protect Weapon' WHERE slug = 'upgraded-protect-weapon-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Provoke' WHERE slug = 'upgraded-provoke-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Psychic Reve' WHERE slug = 'upgraded-psychic-reve-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Psychokinesis' WHERE slug = 'upgraded-psychokinesis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Punisher' WHERE slug = 'upgraded-punisher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Puppet Master' WHERE slug = 'upgraded-puppet-master-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Pura' WHERE slug = 'upgraded-pura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Pythonisse' WHERE slug = 'upgraded-pythonisse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Quasar' WHERE slug = 'upgraded-quasar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded R - Ultimate' WHERE slug = 'upgraded-r-ultimate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Rage' WHERE slug = 'upgraded-rage-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Raid Assault' WHERE slug = 'upgraded-raid-assault-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Railgun' WHERE slug = 'upgraded-railgun-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Rapida Espada' WHERE slug = 'upgraded-rapida-espada-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Rapiere' WHERE slug = 'upgraded-rapiere-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Rapiere of Grim' WHERE slug = 'upgraded-rapiere-of-grim-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Reasoning Journalist' WHERE slug = 'upgraded-reasoning-journalist-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Red Sprite' WHERE slug = 'upgraded-red-sprite-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Reditum' WHERE slug = 'upgraded-reditum-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Reflect Skin' WHERE slug = 'upgraded-reflect-skin-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Resuscitation' WHERE slug = 'upgraded-resuscitation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Retribution' WHERE slug = 'upgraded-retribution-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Rimite' WHERE slug = 'upgraded-rimite-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Rocking' WHERE slug = 'upgraded-rocking-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Roof-Guard' WHERE slug = 'upgraded-roof-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Rosa Secreta' WHERE slug = 'upgraded-rosa-secreta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Royal Guard' WHERE slug = 'upgraded-royal-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sabre Garde' WHERE slug = 'upgraded-sabre-garde-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sabre Glacier' WHERE slug = 'upgraded-sabre-glacier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sabre Tooth' WHERE slug = 'upgraded-sabre-tooth-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sacred Bullet' WHERE slug = 'upgraded-sacred-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sagitta' WHERE slug = 'upgraded-sagitta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Saint Shot' WHERE slug = 'upgraded-saint-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Salute' WHERE slug = 'upgraded-salute-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Salvatize' WHERE slug = 'upgraded-salvatize-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sand Storm' WHERE slug = 'upgraded-sand-storm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Savate' WHERE slug = 'upgraded-savate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Savior' WHERE slug = 'upgraded-savior-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Secret of Moonlight' WHERE slug = 'upgraded-secret-of-moonlight-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Secreto' WHERE slug = 'upgraded-secreto-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Semilunar' WHERE slug = 'upgraded-semilunar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sephia' WHERE slug = 'upgraded-sephia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Serenade' WHERE slug = 'upgraded-serenade-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sereni' WHERE slug = 'upgraded-sereni-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Shadow Assault' WHERE slug = 'upgraded-shadow-assault-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Shadow Sting' WHERE slug = 'upgraded-shadow-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Shadow Trigger' WHERE slug = 'upgraded-shadow-trigger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sharp Shooter' WHERE slug = 'upgraded-sharp-shooter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sharpened Blade' WHERE slug = 'upgraded-sharpened-blade-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Shining Sting' WHERE slug = 'upgraded-shining-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Shooting Support' WHERE slug = 'upgraded-shooting-support-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Shotgun Blaster' WHERE slug = 'upgraded-shotgun-blaster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sidewinder' WHERE slug = 'upgraded-sidewinder-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Siege Burst' WHERE slug = 'upgraded-siege-burst-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Siege' WHERE slug = 'upgraded-siege-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sight Shot' WHERE slug = 'upgraded-sight-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Silent Move' WHERE slug = 'upgraded-silent-move-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sneedronningen' WHERE slug = 'upgraded-sneedronningen-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sniper' WHERE slug = 'upgraded-sniper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sorting Machina' WHERE slug = 'upgraded-sorting-machina-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Soul Bringer' WHERE slug = 'upgraded-soul-bringer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Soul Guard' WHERE slug = 'upgraded-soul-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Soul Reaper' WHERE slug = 'upgraded-soul-reaper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Soul of Fire' WHERE slug = 'upgraded-soul-of-fire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Soul of Ice' WHERE slug = 'upgraded-soul-of-ice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Soul of Wind' WHERE slug = 'upgraded-soul-of-wind-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Split Shooter' WHERE slug = 'upgraded-split-shooter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sprint' WHERE slug = 'upgraded-sprint-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Standing Shot' WHERE slug = 'upgraded-standing-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Stave Guard' WHERE slug = 'upgraded-stave-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Storytelling' WHERE slug = 'upgraded-storytelling-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Superior Blaster' WHERE slug = 'upgraded-superior-blaster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Surgery' WHERE slug = 'upgraded-surgery-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Sweeper' WHERE slug = 'upgraded-sweeper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Swift Move' WHERE slug = 'upgraded-swift-move-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tactical Assistance' WHERE slug = 'upgraded-tactical-assistance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tactical Shot' WHERE slug = 'upgraded-tactical-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tactics' WHERE slug = 'upgraded-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tail-Guard' WHERE slug = 'upgraded-tail-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tal Lasa' WHERE slug = 'upgraded-tal-lasa-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Telekinesis' WHERE slug = 'upgraded-telekinesis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tempest' WHERE slug = 'upgraded-tempest-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tenacity' WHERE slug = 'upgraded-tenacity-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tenevra' WHERE slug = 'upgraded-tenevra-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tested Burst' WHERE slug = 'upgraded-tested-burst-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tested Guard' WHERE slug = 'upgraded-tested-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Testis' WHERE slug = 'upgraded-testis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Thanatos' WHERE slug = 'upgraded-thanatos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded The Crusader' WHERE slug = 'upgraded-the-crusader-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded The Defender' WHERE slug = 'upgraded-the-defender-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded The Elemental Lord' WHERE slug = 'upgraded-the-elemental-lord-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded The Illusionist' WHERE slug = 'upgraded-the-illusionist-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Therapy' WHERE slug = 'upgraded-therapy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Todestrieb' WHERE slug = 'upgraded-todestrieb-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Trance Robo' WHERE slug = 'upgraded-trance-robo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Trigger' WHERE slug = 'upgraded-trigger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Trikinesis' WHERE slug = 'upgraded-trikinesis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tronada Cruz' WHERE slug = 'upgraded-tronada-cruz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Trust' WHERE slug = 'upgraded-trust-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Twin Blades Spirit' WHERE slug = 'upgraded-twin-blades-spirit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Twin Sting' WHERE slug = 'upgraded-twin-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Twin blades' WHERE slug = 'upgraded-twin-blades-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Tyrving' WHERE slug = 'upgraded-tyrving-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ultimate Bloodthirsty Windstorm' WHERE slug = 'upgraded-ultimate-bloodthirsty-windstorm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Unlimited Shot' WHERE slug = 'upgraded-unlimited-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Ursus' WHERE slug = 'upgraded-ursus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Valer' WHERE slug = 'upgraded-valer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Vanguard Order' WHERE slug = 'upgraded-vanguard-order-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Velmas' WHERE slug = 'upgraded-velmas-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Vendetta' WHERE slug = 'upgraded-vendetta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Viertus' WHERE slug = 'upgraded-viertus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Vigilar' WHERE slug = 'upgraded-vigilar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Violent Wind Attack' WHERE slug = 'upgraded-violent-wind-attack-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Violeta Fero' WHERE slug = 'upgraded-violeta-fero-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Void' WHERE slug = 'upgraded-void-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Wanted' WHERE slug = 'upgraded-wanted-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Whisper' WHERE slug = 'upgraded-whisper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Wild Hammer' WHERE slug = 'upgraded-wild-hammer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Wrath Guard' WHERE slug = 'upgraded-wrath-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUpgraded Zodiac' WHERE slug = 'upgraded-zodiac-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAbyss' WHERE slug = 'abyss-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนActivator' WHERE slug = 'activator-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนActivator (30 วัน)' WHERE slug = 'activator-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAdventure' WHERE slug = 'adventure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAmbrosia / Icy Ambrosia' WHERE slug = 'ambrosia-icy-ambrosia-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAncient Bullet' WHERE slug = 'ancient-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAncient Elemental' WHERE slug = 'ancient-elemental-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAncient Guard' WHERE slug = 'ancient-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAncient Spirit' WHERE slug = 'ancient-spirit-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAncient Tactics' WHERE slug = 'ancient-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArch Sting' WHERE slug = 'arch-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArchitecture' WHERE slug = 'architecture-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArchitecture (30 วัน)' WHERE slug = 'architecture-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArma' WHERE slug = 'arma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArnis' WHERE slug = 'arnis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนArnis (30 วัน)' WHERE slug = 'arnis-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAtlas' WHERE slug = 'atlas-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนAurel Lupus' WHERE slug = 'aurel-lupus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBarbatos' WHERE slug = 'barbatos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBarisada' WHERE slug = 'barisada-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlack Cat' WHERE slug = 'black-cat-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlazing Blast' WHERE slug = 'blazing-blast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlitz Assault' WHERE slug = 'blitz-assault-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBlitz Assault (30 วัน)' WHERE slug = 'blitz-assault-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Feast' WHERE slug = 'bloody-feast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Feast (30 วัน)' WHERE slug = 'bloody-feast-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Punisher' WHERE slug = 'bloody-punisher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBloody Rose' WHERE slug = 'bloody-rose-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBluff' WHERE slug = 'bluff-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBook of Lightning' WHERE slug = 'book-of-lightning-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBrandish Arm' WHERE slug = 'brandish-arm-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนBrandish Arm (30 วัน)' WHERE slug = 'brandish-arm-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCannon Shooter' WHERE slug = 'cannon-shooter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCarrier' WHERE slug = 'carrier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCherry blossoms dancing' WHERE slug = 'cherry-blossoms-dancing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนClabuster' WHERE slug = 'clabuster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCluster' WHERE slug = 'cluster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCobra' WHERE slug = 'cobra-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCombat Assault' WHERE slug = 'combat-assault-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCombat Medicine' WHERE slug = 'combat-medicine-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCombat Medicine (30 วัน)' WHERE slug = 'combat-medicine-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนConviction' WHERE slug = 'conviction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCorsair' WHERE slug = 'corsair-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCreacion' WHERE slug = 'creacion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCroisement' WHERE slug = 'croisement-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCroisement (30 วัน)' WHERE slug = 'croisement-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCrusader (30 วัน)' WHERE slug = 'crusader-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCutlass' WHERE slug = 'cutlass-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนCutlass (30 วัน)' WHERE slug = 'cutlass-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDadamos' WHERE slug = 'dadamos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDark Avenger' WHERE slug = 'dark-avenger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDark Lord' WHERE slug = 'dark-lord-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDarkness' WHERE slug = 'darkness-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDarkness (30 วัน)' WHERE slug = 'darkness-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Chopping' WHERE slug = 'death-chopping-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Chopping (30 วัน)' WHERE slug = 'death-chopping-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDeath Shadow Ninjutsu' WHERE slug = 'death-shadow-ninjutsu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDemolition Burst' WHERE slug = 'demolition-burst-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDemolition Burst (30 วัน)' WHERE slug = 'demolition-burst-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDemolition Roar' WHERE slug = 'demolition-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDesire' WHERE slug = 'desire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDestroyer' WHERE slug = 'destroyer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDestroyer (30 วัน)' WHERE slug = 'destroyer-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDiable' WHERE slug = 'diable-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDiable (30 วัน)' WHERE slug = 'diable-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDistortion Cube' WHERE slug = 'distortion-cube-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDominate the sky' WHERE slug = 'dominate-the-sky-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDrawing' WHERE slug = 'drawing-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDual Blaster' WHERE slug = 'dual-blaster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนDual Blaster (30 วัน)' WHERE slug = 'dual-blaster-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEagle Crow' WHERE slug = 'eagle-crow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEfreet' WHERE slug = 'efreet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEfreet (30 วัน)' WHERE slug = 'efreet-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectronic Hare' WHERE slug = 'electronic-hare-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElectronic Kats' WHERE slug = 'electronic-kats-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElegance' WHERE slug = 'elegance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Master' WHERE slug = 'elemental-master-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนElemental Master (30 วัน)' WHERE slug = 'elemental-master-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnhanced Tactics' WHERE slug = 'enhanced-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEnhanced Tactics (30 วัน)' WHERE slug = 'enhanced-tactics-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEquites - Romina' WHERE slug = 'equites-romina-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEquites - Romina (30 วัน)' WHERE slug = 'equites-romina-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEquites' WHERE slug = 'equites-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEquites (30 วัน)' WHERE slug = 'equites-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนEver' WHERE slug = 'ever-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExpire' WHERE slug = 'expire-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนExtreme Punisher' WHERE slug = 'extreme-punisher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFate Sentence' WHERE slug = 'fate-sentence-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFemme Fatale' WHERE slug = 'femme-fatale-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFilo' WHERE slug = 'filo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlame Roar' WHERE slug = 'flame-roar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFleuret Glacier' WHERE slug = 'fleuret-glacier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFleuret Glacier (30 วัน)' WHERE slug = 'fleuret-glacier-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlintlock - Auch Infantry' WHERE slug = 'flintlock-auch-infantry-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlintlock - Auch Infantry (30 วัน)' WHERE slug = 'flintlock-auch-infantry-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlintlock - Rescue Knight (30 วัน)' WHERE slug = 'flintlock-rescue-knight-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlintlock - Rescue Knights' WHERE slug = 'flintlock-rescue-knights-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlintlock' WHERE slug = 'flintlock-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlintlock (30 วัน)' WHERE slug = 'flintlock-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFloresta' WHERE slug = 'floresta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlos' WHERE slug = 'flos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFlying Shadow Ninjutsu' WHERE slug = 'flying-shadow-ninjutsu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFolclore' WHERE slug = 'folclore-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFreeze Over' WHERE slug = 'freeze-over-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFretensis' WHERE slug = 'fretensis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrontier' WHERE slug = 'frontier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrost' WHERE slug = 'frost-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFrost (30 วัน)' WHERE slug = 'frost-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFurious' WHERE slug = 'furious-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนFurious (30 วัน)' WHERE slug = 'furious-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGae Bulg' WHERE slug = 'gae-bulg-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGeirskogul' WHERE slug = 'geirskogul-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGemma' WHERE slug = 'gemma-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGoliath' WHERE slug = 'goliath-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGorgeous' WHERE slug = 'gorgeous-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGorgeous (30 วัน)' WHERE slug = 'gorgeous-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGrave' WHERE slug = 'grave-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGuardian Structure' WHERE slug = 'guardian-structure-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGuardian Structure (30 วัน)' WHERE slug = 'guardian-structure-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนGun-Maestro' WHERE slug = 'gun-maestro-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHanging Guard' WHERE slug = 'hanging-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHanging Guard (30 วัน)' WHERE slug = 'hanging-guard-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHeavy Stinger' WHERE slug = 'heavy-stinger-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHermetisme' WHERE slug = 'hermetisme-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHermetisme (30 วัน)' WHERE slug = 'hermetisme-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนHoly Shielder' WHERE slug = 'holy-shielder-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIce Crown' WHERE slug = 'ice-crown-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIllusion Garde' WHERE slug = 'illusion-garde-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIllusion Gunner' WHERE slug = 'illusion-gunner-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImperial Guardian' WHERE slug = 'imperial-guardian-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนImperial Tactics' WHERE slug = 'imperial-tactics-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIncursio' WHERE slug = 'incursio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInfernal Burn' WHERE slug = 'infernal-burn-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInferno Guard' WHERE slug = 'inferno-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInferno' WHERE slug = 'inferno-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนInnocentio' WHERE slug = 'innocentio-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIntoxication' WHERE slug = 'intoxication-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนIstion' WHERE slug = 'istion-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนKarima' WHERE slug = 'karima-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLama' WHERE slug = 'lama-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนLord-of-Death' WHERE slug = 'lord-of-death-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMachina' WHERE slug = 'machina-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMadness' WHERE slug = 'madness-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMadness (30 วัน)' WHERE slug = 'madness-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMaiden of Glacier' WHERE slug = 'maiden-of-glacier-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMalediction' WHERE slug = 'malediction-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนManipulation' WHERE slug = 'manipulation-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMartial Arts Compendium' WHERE slug = 'martial-arts-compendium-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMatileo' WHERE slug = 'matileo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMessiah' WHERE slug = 'messiah-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนMythos' WHERE slug = 'mythos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNaraka' WHERE slug = 'naraka-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนNine Tails' WHERE slug = 'nine-tails-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOccult Assistance' WHERE slug = 'occult-assistance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOccult Assistance (30 วัน)' WHERE slug = 'occult-assistance-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOccult Magic' WHERE slug = 'occult-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนOccult Magic (30 วัน)' WHERE slug = 'occult-magic-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPanther' WHERE slug = 'panther-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPeltast' WHERE slug = 'peltast-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPeltast (30 วัน)' WHERE slug = 'peltast-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPiracy' WHERE slug = 'piracy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPlacidez' WHERE slug = 'placidez-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrelude' WHERE slug = 'prelude-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrelude (30 วัน)' WHERE slug = 'prelude-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPrid' WHERE slug = 'prid-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPsychic Reve' WHERE slug = 'psychic-reve-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPunisher' WHERE slug = 'punisher-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPuppet Master' WHERE slug = 'puppet-master-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPuppet Master (30 วัน)' WHERE slug = 'puppet-master-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPura' WHERE slug = 'pura-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนPythonisse' WHERE slug = 'pythonisse-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนQuasar' WHERE slug = 'quasar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRailgun' WHERE slug = 'railgun-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapida Espada' WHERE slug = 'rapida-espada-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapida Espada (30 วัน)' WHERE slug = 'rapida-espada-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapido Cruise' WHERE slug = 'rapido-cruise-ring' AND name_th IS NULL;