-- Migration 062: Thai names batch 9/10
-- Generated: 2026-03-16T03:42:16.055Z

UPDATE items SET name_th = 'แหวนRapiere' WHERE slug = 'rapiere-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapiere (30 วัน)' WHERE slug = 'rapiere-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapiere of Grim' WHERE slug = 'rapiere-of-grim-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRapiere of Grim (30 วัน)' WHERE slug = 'rapiere-of-grim-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนReasoning Journalist' WHERE slug = 'reasoning-journalist-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRed Sprite' WHERE slug = 'red-sprite-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRetribution' WHERE slug = 'retribution-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRocking' WHERE slug = 'rocking-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRosa Secreta' WHERE slug = 'rosa-secreta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRoyal Guard' WHERE slug = 'royal-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนRoyal Guard (30 วัน)' WHERE slug = 'royal-guard-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSabre Tooth' WHERE slug = 'sabre-tooth-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSabre Tooth (30 วัน)' WHERE slug = 'sabre-tooth-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSacred Bullet' WHERE slug = 'sacred-bullet-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSaint Shot' WHERE slug = 'saint-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSalvatize' WHERE slug = 'salvatize-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSavate' WHERE slug = 'savate-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSavior' WHERE slug = 'savior-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSecret of Moonlight' WHERE slug = 'secret-of-moonlight-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSecret of Moonlight (30 วัน)' WHERE slug = 'secret-of-moonlight-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSecreto' WHERE slug = 'secreto-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSemilunar' WHERE slug = 'semilunar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSemilunar (30 วัน)' WHERE slug = 'semilunar-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSereni' WHERE slug = 'sereni-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShadow Assault' WHERE slug = 'shadow-assault-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShadow Sting' WHERE slug = 'shadow-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShadow Sting (30 วัน)' WHERE slug = 'shadow-sting-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining Sting' WHERE slug = 'shining-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShining Sting (30 วัน)' WHERE slug = 'shining-sting-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนShooting Support' WHERE slug = 'shooting-support-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSneedronningen' WHERE slug = 'sneedronningen-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSniper' WHERE slug = 'sniper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSniper (30 วัน)' WHERE slug = 'sniper-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul Bringer' WHERE slug = 'soul-bringer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul Guard (30 วัน)' WHERE slug = 'soul-guard-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSoul Guard Stance' WHERE slug = 'soul-guard-stance-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSplit Shooter' WHERE slug = 'split-shooter-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSplit Shooter (30 วัน)' WHERE slug = 'split-shooter-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนStorytelling' WHERE slug = 'storytelling-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSuperior Blaster' WHERE slug = 'superior-blaster-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSuperior Blaster (30 วัน)' WHERE slug = 'superior-blaster-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSurgery' WHERE slug = 'surgery-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSweeper' WHERE slug = 'sweeper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนSweeper (30 วัน)' WHERE slug = 'sweeper-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTactical Shot' WHERE slug = 'tactical-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTal Lasa' WHERE slug = 'tal-lasa-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTelekinesis' WHERE slug = 'telekinesis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTelekinesis (30 วัน)' WHERE slug = 'telekinesis-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTempest' WHERE slug = 'tempest-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTempest (30 วัน)' WHERE slug = 'tempest-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTenevra' WHERE slug = 'tenevra-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTested Burst' WHERE slug = 'tested-burst-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTested Burst (30 วัน)' WHERE slug = 'tested-burst-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTested Guard' WHERE slug = 'tested-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTested Guard (30 วัน)' WHERE slug = 'tested-guard-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThanatos' WHERE slug = 'thanatos-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThe Crusader' WHERE slug = 'the-crusader-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThe Five Books of Martial Arts - Chapter of Flow' WHERE slug = 'the-five-books-of-martial-arts-chapter-of-flow-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนThe Five Books of Martial Arts -Martial Arts (30 วัน)' WHERE slug = 'the-five-books-of-martial-arts-martial-arts-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTherapy' WHERE slug = 'therapy-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTherapy (30 วัน)' WHERE slug = 'therapy-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTodestrieb' WHERE slug = 'todestrieb-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrance Robo' WHERE slug = 'trance-robo-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrikinesi (30 วัน)' WHERE slug = 'trikinesi-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTrikinesis' WHERE slug = 'trikinesis-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTronada Cruz' WHERE slug = 'tronada-cruz-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTronada Cruz (30 วัน)' WHERE slug = 'tronada-cruz-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTwin Sting' WHERE slug = 'twin-sting-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนTyrving' WHERE slug = 'tyrving-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUnlimited Shot' WHERE slug = 'unlimited-shot-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUnlimited Shot (30 วัน)' WHERE slug = 'unlimited-shot-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนUrsus' WHERE slug = 'ursus-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVanguard Order' WHERE slug = 'vanguard-order-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVendetta' WHERE slug = 'vendetta-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVigilar' WHERE slug = 'vigilar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVioleta Fero' WHERE slug = 'violeta-fero-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนVoid' WHERE slug = 'void-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWanted' WHERE slug = 'wanted-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWanted (30 วัน)' WHERE slug = 'wanted-ring-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWhisper' WHERE slug = 'whisper-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWild Hammer' WHERE slug = 'wild-hammer-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนWrath Guard' WHERE slug = 'wrath-guard-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวนZodiac' WHERE slug = 'zodiac-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Bangle' WHERE slug = 'abyss-bangle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Bangle (อีเวนต์)' WHERE slug = 'abyss-bangle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Bayonet' WHERE slug = 'abyss-bayonet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Bayonet (อีเวนต์)' WHERE slug = 'abyss-bayonet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Blade' WHERE slug = 'abyss-blade-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Blade (อีเวนต์)' WHERE slug = 'abyss-blade-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Broom Stick' WHERE slug = 'abyss-broom-stick-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Broom Stick (อีเวนต์)' WHERE slug = 'abyss-broom-stick-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Cannon' WHERE slug = 'abyss-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Cannon (อีเวนต์)' WHERE slug = 'abyss-cannon-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Crescent' WHERE slug = 'abyss-crescent-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Crescent (อีเวนต์)' WHERE slug = 'abyss-crescent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Crossbow' WHERE slug = 'abyss-crossbow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Cube' WHERE slug = 'abyss-cube-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Cube (อีเวนต์)' WHERE slug = 'abyss-cube-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Destruction Rifle' WHERE slug = 'abyss-destruction-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Destruction Rifle (อีเวนต์)' WHERE slug = 'abyss-destruction-rifle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Flame Bracelet' WHERE slug = 'abyss-flame-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Flame Bracelete (อีเวนต์)' WHERE slug = 'abyss-flame-bracelete-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Freezing Bracelet' WHERE slug = 'abyss-freezing-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Freezing Bracelet (อีเวนต์)' WHERE slug = 'abyss-freezing-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Grimore' WHERE slug = 'abyss-grimore-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Grimore (อีเวนต์)' WHERE slug = 'abyss-grimore-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Javelin' WHERE slug = 'abyss-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Javelin (อีเวนต์)' WHERE slug = 'abyss-javelin-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Knife (อีเวนต์)' WHERE slug = 'abyss-knife-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Knuckle' WHERE slug = 'abyss-knuckle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Knuckle (อีเวนต์)' WHERE slug = 'abyss-knuckle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Leg-Guards' WHERE slug = 'abyss-leg-guards-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Leg-guard (อีเวนต์)' WHERE slug = 'abyss-leg-guard-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Lightning Bracelet' WHERE slug = 'abyss-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Lightning Bracelete (อีเวนต์)' WHERE slug = 'abyss-lightning-bracelete-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Lute' WHERE slug = 'abyss-lute-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Lute (อีเวนต์)' WHERE slug = 'abyss-lute-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Mace' WHERE slug = 'abyss-mace-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Mace (อีเวนต์)' WHERE slug = 'abyss-mace-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Main-gauche' WHERE slug = 'abyss-main-gauche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Nife' WHERE slug = 'abyss-nife-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Pistol' WHERE slug = 'abyss-pistol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Pistol (อีเวนต์)' WHERE slug = 'abyss-pistol-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Polearm' WHERE slug = 'abyss-polearm-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Polearm (อีเวนต์)' WHERE slug = 'abyss-polearm-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Rapier' WHERE slug = 'abyss-rapier-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Rapier (อีเวนต์)' WHERE slug = 'abyss-rapier-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Record Book' WHERE slug = 'abyss-record-book-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Record Book (อีเวนต์)' WHERE slug = 'abyss-record-book-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Rod' WHERE slug = 'abyss-rod-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Rod (อีเวนต์)' WHERE slug = 'abyss-rod-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Sabre' WHERE slug = 'abyss-sabre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Sabre (อีเวนต์)' WHERE slug = 'abyss-sabre-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Scroll' WHERE slug = 'abyss-scroll-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Shotgun' WHERE slug = 'abyss-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Shotgun (อีเวนต์)' WHERE slug = 'abyss-shotgun-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Slayer' WHERE slug = 'abyss-slayer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Slayer (อีเวนต์)' WHERE slug = 'abyss-slayer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Staff' WHERE slug = 'abyss-staff-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Staff (อีเวนต์)' WHERE slug = 'abyss-staff-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Tonfa' WHERE slug = 'abyss-tonfa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAbyss Tongfa (อีเวนต์)' WHERE slug = 'abyss-tongfa-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAdventure of Spirit' WHERE slug = 'adventure-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธAltairs Cunning' WHERE slug = 'altairs-cunning-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBalance of Libra' WHERE slug = 'balance-of-libra-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBanshee Rifle' WHERE slug = 'banshee-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBearwalker Pickaxe' WHERE slug = 'bearwalker-pickaxe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBergelmir' WHERE slug = 'bergelmir-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlack Bishop' WHERE slug = 'black-bishop-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlack Dagger' WHERE slug = 'black-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlack Dragonic Javelin' WHERE slug = 'black-dragonic-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlack Dragonic Revolver' WHERE slug = 'black-dragonic-revolver-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlack Dragonic Sabre' WHERE slug = 'black-dragonic-sabre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlack Herberthe' WHERE slug = 'black-herberthe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Book Weapon' WHERE slug = 'blood-navy-book-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Bracelet Weapon' WHERE slug = 'blood-navy-bracelet-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Cannon Weapon' WHERE slug = 'blood-navy-cannon-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Dagger Weapon' WHERE slug = 'blood-navy-dagger-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Fire Bracelet Weapon' WHERE slug = 'blood-navy-fire-bracelet-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Ice Bracelet Weapon' WHERE slug = 'blood-navy-ice-bracelet-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Javelin Weapon' WHERE slug = 'blood-navy-javelin-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Knuckle Weapon' WHERE slug = 'blood-navy-knuckle-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Light Bracelet Weapon' WHERE slug = 'blood-navy-light-bracelet-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Mace Weapon' WHERE slug = 'blood-navy-mace-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Pistol Weapon' WHERE slug = 'blood-navy-pistol-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Polearm Weapon' WHERE slug = 'blood-navy-polearm-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Rapier Weapon' WHERE slug = 'blood-navy-rapier-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Rifle Weapon' WHERE slug = 'blood-navy-rifle-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Rod Weapon' WHERE slug = 'blood-navy-rod-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Sabre Weapon' WHERE slug = 'blood-navy-sabre-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Slayer Weapon' WHERE slug = 'blood-navy-slayer-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlood Navy Staff Weapon' WHERE slug = 'blood-navy-staff-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBlunder of Lykaon' WHERE slug = 'blunder-of-lykaon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBoreas' WHERE slug = 'boreas-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Bayonet' WHERE slug = 'bristia-bayonet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Blunt' WHERE slug = 'bristia-blunt-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Cannon' WHERE slug = 'bristia-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Crescent' WHERE slug = 'bristia-crescent-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Crossbow' WHERE slug = 'bristia-crossbow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Cube' WHERE slug = 'bristia-cube-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Dagger' WHERE slug = 'bristia-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Encyclopedia' WHERE slug = 'bristia-encyclopedia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Fire Bracelet' WHERE slug = 'bristia-fire-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Gaiters' WHERE slug = 'bristia-gaiters-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Great Sword' WHERE slug = 'bristia-great-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Ice bracelet' WHERE slug = 'bristia-ice-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Javelin' WHERE slug = 'bristia-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Knuckle' WHERE slug = 'bristia-knuckle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Lightning Bracelet' WHERE slug = 'bristia-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Lute' WHERE slug = 'bristia-lute-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Main-Gauche' WHERE slug = 'bristia-main-gauche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia One-handed Sword' WHERE slug = 'bristia-one-handed-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Pistol' WHERE slug = 'bristia-pistol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Polearm' WHERE slug = 'bristia-polearm-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Rapier' WHERE slug = 'bristia-rapier-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Rod' WHERE slug = 'bristia-rod-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Sabre' WHERE slug = 'bristia-sabre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Shield' WHERE slug = 'bristia-shield-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Shotgun' WHERE slug = 'bristia-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Special Bracelet' WHERE slug = 'bristia-special-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Staff' WHERE slug = 'bristia-staff-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBristia Tonfa' WHERE slug = 'bristia-tonfa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBroom' WHERE slug = 'broom-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธBroom of Little Witch' WHERE slug = 'broom-of-little-witch-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCandied Fruit' WHERE slug = 'candied-fruit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCapybara Branch' WHERE slug = 'capybara-branch-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCapybara Flowerpot Shovel' WHERE slug = 'capybara-flowerpot-shovel-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCapybara Guard' WHERE slug = 'capybara-guard-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCapybara Saw' WHERE slug = 'capybara-saw-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCapybara Sickle' WHERE slug = 'capybara-sickle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCatalog' WHERE slug = 'catalog-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCatalog (อีเวนต์)' WHERE slug = 'catalog-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCluster of Spirit' WHERE slug = 'cluster-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCocktail Strong' WHERE slug = 'cocktail-strong-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCocktail Strong (อีเวนต์)' WHERE slug = 'cocktail-strong-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธConflamme' WHERE slug = 'conflamme-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธConviction of Spirit' WHERE slug = 'conviction-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCrime Shotgun' WHERE slug = 'crime-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCrimson Blade' WHERE slug = 'crimson-blade-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCrystalin' WHERE slug = 'crystalin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCube' WHERE slug = 'cube-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCumulonimbus' WHERE slug = 'cumulonimbus-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธCutlass of Spirit' WHERE slug = 'cutlass-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDelphinus' WHERE slug = 'delphinus-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDelusion of Karas' WHERE slug = 'delusion-of-karas-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDemolition Roar of Spirit' WHERE slug = 'demolition-roar-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDiamond Dragon Bayonet' WHERE slug = 'diamond-dragon-bayonet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDiamond Dragon' WHERE slug = 'diamond-dragon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDiary' WHERE slug = 'diary-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Bracelet (อีเวนต์)' WHERE slug = 'direwolf-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Crossbow (อีเวนต์)' WHERE slug = 'direwolf-crossbow-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Dagger (อีเวนต์)' WHERE slug = 'direwolf-dagger-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Fire Bracelet (อีเวนต์)' WHERE slug = 'direwolf-fire-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Halberde (อีเวนต์)' WHERE slug = 'direwolf-halberde-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Ice Bracelet (อีเวนต์)' WHERE slug = 'direwolf-ice-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Lightning Bangle (อีเวนต์)' WHERE slug = 'direwolf-lightning-bangle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Magic Book (อีเวนต์)' WHERE slug = 'direwolf-magic-book-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Pistol (อีเวนต์)' WHERE slug = 'direwolf-pistol-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Rapier (อีเวนต์)' WHERE slug = 'direwolf-rapier-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Rifle (อีเวนต์)' WHERE slug = 'direwolf-rifle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Rod (อีเวนต์)' WHERE slug = 'direwolf-rod-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Saber (อีเวนต์)' WHERE slug = 'direwolf-saber-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Slayer (อีเวนต์)' WHERE slug = 'direwolf-slayer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Staff (อีเวนต์)' WHERE slug = 'direwolf-staff-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDirewolf Sword (อีเวนต์)' WHERE slug = 'direwolf-sword-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDisdain of Spica' WHERE slug = 'disdain-of-spica-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Book Weapon' WHERE slug = 'dragovan-book-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Bracelet Weapon' WHERE slug = 'dragovan-bracelet-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Buster Weapon' WHERE slug = 'dragovan-buster-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Cannon Weapon' WHERE slug = 'dragovan-cannon-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Crescent Weapon' WHERE slug = 'dragovan-crescent-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Crossbow Weapon' WHERE slug = 'dragovan-crossbow-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Cube Weapon' WHERE slug = 'dragovan-cube-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Dagger Weapon' WHERE slug = 'dragovan-dagger-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Fire Bracelet Weapon' WHERE slug = 'dragovan-fire-bracelet-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Ice Bracelet Weapon' WHERE slug = 'dragovan-ice-bracelet-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Legguard Weapon' WHERE slug = 'dragovan-legguard-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Lightning Bracelet Weapon' WHERE slug = 'dragovan-lightning-bracelet-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Mace Weapon' WHERE slug = 'dragovan-mace-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Main-Gauche Weapon' WHERE slug = 'dragovan-main-gauche-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Pistol Weapon' WHERE slug = 'dragovan-pistol-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Polearm Weapon' WHERE slug = 'dragovan-polearm-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Rapier Weapon' WHERE slug = 'dragovan-rapier-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Rifle Weapon' WHERE slug = 'dragovan-rifle-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Rod Weapon' WHERE slug = 'dragovan-rod-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Sabre Weapon' WHERE slug = 'dragovan-sabre-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Shotgun Weapon' WHERE slug = 'dragovan-shotgun-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Slayer Weapon' WHERE slug = 'dragovan-slayer-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Staff Weapon' WHERE slug = 'dragovan-staff-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDragovan Sword Weapon' WHERE slug = 'dragovan-sword-weapon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDuck Shield' WHERE slug = 'duck-shield-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDullahan Claymore' WHERE slug = 'dullahan-claymore-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDullahan Pistol' WHERE slug = 'dullahan-pistol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธDullahan Sword' WHERE slug = 'dullahan-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEinaptor Sword' WHERE slug = 'einaptor-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEinschiever Sword' WHERE slug = 'einschiever-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEinschiever War Hammer' WHERE slug = 'einschiever-war-hammer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Carro' WHERE slug = 'el-carro-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Colgado' WHERE slug = 'el-colgado-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Diablo' WHERE slug = 'el-diablo-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Ermitano' WHERE slug = 'el-ermitano-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Juicio' WHERE slug = 'el-juicio-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Loco' WHERE slug = 'el-loco-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Mago' WHERE slug = 'el-mago-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Sol' WHERE slug = 'el-sol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEl Sumo Sacerdote' WHERE slug = 'el-sumo-sacerdote-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElbrid Sword' WHERE slug = 'elbrid-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElectronic Kats of Spirit' WHERE slug = 'electronic-kats-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Blade (อีเวนต์)' WHERE slug = 'elemental-blade-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Bracelet (อีเวนต์)' WHERE slug = 'elemental-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Broomstick' WHERE slug = 'elemental-broomstick-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Buster (อีเวนต์)' WHERE slug = 'elemental-buster-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Dagger (อีเวนต์)' WHERE slug = 'elemental-dagger-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Fire Bracelet (อีเวนต์)' WHERE slug = 'elemental-fire-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Grimoire (อีเวนต์)' WHERE slug = 'elemental-grimoire-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Ice Bracelet (อีเวนต์)' WHERE slug = 'elemental-ice-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Javelin (อีเวนต์)' WHERE slug = 'elemental-javelin-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Leg-guard (อีเวนต์)' WHERE slug = 'elemental-leg-guard-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Lightning Bracelet (อีเวนต์)' WHERE slug = 'elemental-lightning-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Pistol (อีเวนต์)' WHERE slug = 'elemental-pistol-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Polearm (อีเวนต์)' WHERE slug = 'elemental-polearm-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Rapier (อีเวนต์)' WHERE slug = 'elemental-rapier-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Rifle (อีเวนต์)' WHERE slug = 'elemental-rifle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Rod (อีเวนต์)' WHERE slug = 'elemental-rod-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Sabre (อีเวนต์)' WHERE slug = 'elemental-sabre-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Shotgun (อีเวนต์)' WHERE slug = 'elemental-shotgun-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElemental Slayer (อีเวนต์)' WHERE slug = 'elemental-slayer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElgoom Spear' WHERE slug = 'elgoom-spear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Black Dragon' WHERE slug = 'elite-black-dragon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Bracelet of Behemoth' WHERE slug = 'elite-bracelet-of-behemoth-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Bracelet of Leviathan' WHERE slug = 'elite-bracelet-of-leviathan-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Bracelet of Ziz' WHERE slug = 'elite-bracelet-of-ziz-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Demon Slayer' WHERE slug = 'elite-demon-slayer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Grim-Wraith' WHERE slug = 'elite-grim-wraith-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Grim-stick' WHERE slug = 'elite-grim-stick-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Royal Guardian' WHERE slug = 'elite-royal-guardian-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Silver Crossbow' WHERE slug = 'elite-silver-crossbow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธElite Teorbe' WHERE slug = 'elite-teorbe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEmerald Dragon Bayonet' WHERE slug = 'emerald-dragon-bayonet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEmerald Dragon' WHERE slug = 'emerald-dragon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEncyclopedia' WHERE slug = 'encyclopedia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEscarta of Evil' WHERE slug = 'escarta-of-evil-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Adventure of Spirit' WHERE slug = 'event-adventure-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Axe of Lie' WHERE slug = 'event-axe-of-lie-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Banshee Rifle' WHERE slug = 'event-banshee-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Bayonet of Unlawful' WHERE slug = 'event-bayonet-of-unlawful-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Blade of Insincere' WHERE slug = 'event-blade-of-insincere-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Bracelet of Lust' WHERE slug = 'event-bracelet-of-lust-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Candied Fruit' WHERE slug = 'event-candied-fruit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Canon of Detractor' WHERE slug = 'event-canon-of-detractor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Cluster of Spirit' WHERE slug = 'event-cluster-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Conviction of Spirit' WHERE slug = 'event-conviction-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Crescent of Avenger' WHERE slug = 'event-crescent-of-avenger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Crimson Blade' WHERE slug = 'event-crimson-blade-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Crossbow of Apostate' WHERE slug = 'event-crossbow-of-apostate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Cutlass of Spirit' WHERE slug = 'event-cutlass-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Dagger of Greed' WHERE slug = 'event-dagger-of-greed-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Demolition Roar of Spirit' WHERE slug = 'event-demolition-roar-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Duck Shield' WHERE slug = 'event-duck-shield-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Electronic Kats of Spirit' WHERE slug = 'event-electronic-kats-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Elemental Broomstick' WHERE slug = 'event-elemental-broomstick-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Fleur De Neju' WHERE slug = 'event-fleur-de-neju-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Fleuret Glacier of Spirit' WHERE slug = 'event-fleuret-glacier-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Giant Squid' WHERE slug = 'event-giant-squid-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Grilled Corn Butter' WHERE slug = 'event-grilled-corn-butter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Grilled Skewer' WHERE slug = 'event-grilled-skewer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Grimoire of Darkness' WHERE slug = 'event-grimoire-of-darkness-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Hammer of Sloth' WHERE slug = 'event-hammer-of-sloth-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Heavy Rifle of General' WHERE slug = 'event-heavy-rifle-of-general-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Inferno Guard of Spirit' WHERE slug = 'event-inferno-guard-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Knuckle of Temptation' WHERE slug = 'event-knuckle-of-temptation-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Leg-Guard of Gluttony' WHERE slug = 'event-leg-guard-of-gluttony-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Machina of Spirit' WHERE slug = 'event-machina-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Octopus Bracelet' WHERE slug = 'event-octopus-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Octopus Fire Bracelet' WHERE slug = 'event-octopus-fire-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Octopus Ice Bracelet' WHERE slug = 'event-octopus-ice-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Octopus Lightning Bracelet' WHERE slug = 'event-octopus-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Pearl Scallop' WHERE slug = 'event-pearl-scallop-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Quasar of Spirit' WHERE slug = 'event-quasar-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Rapier of Imitator' WHERE slug = 'event-rapier-of-imitator-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Revolver of Revenger' WHERE slug = 'event-revolver-of-revenger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Rod of Pride' WHERE slug = 'event-rod-of-pride-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Sabre of Troopers' WHERE slug = 'event-sabre-of-troopers-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Shark Cannon' WHERE slug = 'event-shark-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Shotgun of Crime' WHERE slug = 'event-shotgun-of-crime-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Sugar Seahorse' WHERE slug = 'event-sugar-seahorse-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Tested Burst of Spirit' WHERE slug = 'event-tested-burst-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent The Tonfa of Wrath' WHERE slug = 'event-the-tonfa-of-wrath-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvent Zweihander of Soul' WHERE slug = 'event-zweihander-of-soul-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Bayonet' WHERE slug = 'evil-bayonet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Blunt' WHERE slug = 'evil-blunt-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Bracelet' WHERE slug = 'evil-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Cannon' WHERE slug = 'evil-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Crescent' WHERE slug = 'evil-crescent-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Crossbow' WHERE slug = 'evil-crossbow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Dagger' WHERE slug = 'evil-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Fire Bracelet' WHERE slug = 'evil-fire-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Ice Bracelet' WHERE slug = 'evil-ice-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Javelin' WHERE slug = 'evil-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Knuckle' WHERE slug = 'evil-knuckle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Leg-Guard' WHERE slug = 'evil-leg-guard-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Lightning Bracelet' WHERE slug = 'evil-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Lute' WHERE slug = 'evil-lute-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Main-Gauche' WHERE slug = 'evil-main-gauche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Pistol' WHERE slug = 'evil-pistol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Polearm' WHERE slug = 'evil-polearm-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Rapier' WHERE slug = 'evil-rapier-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Rifle' WHERE slug = 'evil-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Rod' WHERE slug = 'evil-rod-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Sabre' WHERE slug = 'evil-sabre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Shotgun' WHERE slug = 'evil-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Slayer' WHERE slug = 'evil-slayer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Staff' WHERE slug = 'evil-staff-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Sword' WHERE slug = 'evil-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธEvil Tonfa' WHERE slug = 'evil-tonfa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธFire of Palermo' WHERE slug = 'fire-of-palermo-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธFlame Edge' WHERE slug = 'flame-edge-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธFlame Thrower' WHERE slug = 'flame-thrower-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธFleudelis' WHERE slug = 'fleudelis-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธFleur De Neju' WHERE slug = 'fleur-de-neju-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธFleuret Glacier of Spirit' WHERE slug = 'fleuret-glacier-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธForest Whisper' WHERE slug = 'forest-whisper-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธFrozen Spitter' WHERE slug = 'frozen-spitter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGiant Squid' WHERE slug = 'giant-squid-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGlacial Crystal' WHERE slug = 'glacial-crystal-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGlacial Eglanche' WHERE slug = 'glacial-eglanche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGlacial Rosette' WHERE slug = 'glacial-rosette-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGolden Damascus' WHERE slug = 'golden-damascus-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGolden Feet' WHERE slug = 'golden-feet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGolden Fist' WHERE slug = 'golden-fist-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGreed Dark' WHERE slug = 'greed-dark-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGrilled Corn Butter' WHERE slug = 'grilled-corn-butter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGrilled Skewer' WHERE slug = 'grilled-skewer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGrim-shout' WHERE slug = 'grim-shout-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธGrimoire of Darkness' WHERE slug = 'grimoire-of-darkness-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Cannon' WHERE slug = 'halloween-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Cannon (อีเวนต์)' WHERE slug = 'halloween-cannon-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Fire Bracelet' WHERE slug = 'halloween-fire-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Ice Bracelet' WHERE slug = 'halloween-ice-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Large Caliber Rifle' WHERE slug = 'halloween-large-caliber-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Lightning Bracelet' WHERE slug = 'halloween-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Magic Scroll' WHERE slug = 'halloween-magic-scroll-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Magic Scroll (อีเวนต์)' WHERE slug = 'halloween-magic-scroll-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Rod' WHERE slug = 'halloween-rod-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Rod (อีเวนต์)' WHERE slug = 'halloween-rod-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Saber' WHERE slug = 'halloween-saber-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Special Bracelet' WHERE slug = 'halloween-special-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Staff' WHERE slug = 'halloween-staff-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHalloween Staff (อีเวนต์)' WHERE slug = 'halloween-staff-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHammer of Barsene' WHERE slug = 'hammer-of-barsene-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHammer of Tollero' WHERE slug = 'hammer-of-tollero-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHeavenly Craft' WHERE slug = 'heavenly-craft-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHeavy Rifle of General' WHERE slug = 'heavy-rifle-of-general-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHell Bleed' WHERE slug = 'hell-bleed-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHell Slayer' WHERE slug = 'hell-slayer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHell Spit' WHERE slug = 'hell-spit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHestia' WHERE slug = 'hestia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธHowling of Callisto' WHERE slug = 'howling-of-callisto-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIce of Sualocin' WHERE slug = 'ice-of-sualocin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIce-bar' WHERE slug = 'ice-bar-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIce-bar (อีเวนต์)' WHERE slug = 'ice-bar-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIce-cream' WHERE slug = 'ice-cream-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIce-cream (อีเวนต์)' WHERE slug = 'ice-cream-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIcicle Edge' WHERE slug = 'icicle-edge-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Blade (อีเวนต์)' WHERE slug = 'imperium-blade-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Crossbow (อีเวนต์)' WHERE slug = 'imperium-crossbow-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Fire Bracelet (อีเวนต์)' WHERE slug = 'imperium-fire-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Grimoire (อีเวนต์)' WHERE slug = 'imperium-grimoire-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Ice Bracelet (อีเวนต์)' WHERE slug = 'imperium-ice-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Lightning Bracelet (อีเวนต์)' WHERE slug = 'imperium-lightning-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Pistol (อีเวนต์)' WHERE slug = 'imperium-pistol-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Polearm (อีเวนต์)' WHERE slug = 'imperium-polearm-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Rifle (อีเวนต์)' WHERE slug = 'imperium-rifle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Sabre (อีเวนต์)' WHERE slug = 'imperium-sabre-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Slayer (อีเวนต์)' WHERE slug = 'imperium-slayer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImperium Special Bracelet (อีเวนต์)' WHERE slug = 'imperium-special-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธImpulse of Algedi' WHERE slug = 'impulse-of-algedi-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIndigo 9 Pistol' WHERE slug = 'indigo-9-pistol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIndigo 9 Rifle' WHERE slug = 'indigo-9-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธInfernal Hearts' WHERE slug = 'infernal-hearts-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธInferno Guard of Spirit' WHERE slug = 'inferno-guard-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธInsight of Antares' WHERE slug = 'insight-of-antares-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธInsincere Blade' WHERE slug = 'insincere-blade-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIntuition of Al Rischa' WHERE slug = 'intuition-of-al-rischa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธIstion Bracelet' WHERE slug = 'istion-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธJudgment of Bennu' WHERE slug = 'judgment-of-bennu-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธKnuckle of Raionu' WHERE slug = 'knuckle-of-raionu-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธKnuckle of the Yeti' WHERE slug = 'knuckle-of-the-yeti-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธKobolt Axe' WHERE slug = 'kobolt-axe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธKobolt Bone Sword' WHERE slug = 'kobolt-bone-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธKobolt Dagger' WHERE slug = 'kobolt-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธKobolt Sword' WHERE slug = 'kobolt-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธKobolt Torch' WHERE slug = 'kobolt-torch-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธKurenai' WHERE slug = 'kurenai-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Emperador' WHERE slug = 'la-emperador-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Emperatriz' WHERE slug = 'la-emperatriz-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Estrella' WHERE slug = 'la-estrella-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Flame de la mur du Ruby' WHERE slug = 'la-flame-de-la-mur-du-ruby-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Fuerza' WHERE slug = 'la-fuerza-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Justicia' WHERE slug = 'la-justicia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Konsiterapion de le Carnelian' WHERE slug = 'la-konsiterapion-de-le-carnelian-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Luna' WHERE slug = 'la-luna-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Muerte' WHERE slug = 'la-muerte-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Rueda De La Fortuna' WHERE slug = 'la-rueda-de-la-fortuna-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Sabrimite Lapislazuli' WHERE slug = 'la-sabrimite-lapislazuli-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Suma Sacerdotisa' WHERE slug = 'la-suma-sacerdotisa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa Torre' WHERE slug = 'la-torre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLa lemony de lapiel de la rune' WHERE slug = 'la-lemony-de-lapiel-de-la-rune-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLe Conjelable' WHERE slug = 'le-conjelable-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLe Perfection du Diamond' WHERE slug = 'le-perfection-du-diamond-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLeadership of Hamal' WHERE slug = 'leadership-of-hamal-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLeg-Guards of Raionu' WHERE slug = 'leg-guards-of-raionu-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLeg-Guards of the Yeti' WHERE slug = 'leg-guards-of-the-yeti-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLenergy de Opal' WHERE slug = 'lenergy-de-opal-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLife-Belt' WHERE slug = 'life-belt-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLife-Belt (อีเวนต์)' WHERE slug = 'life-belt-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLightning Gun' WHERE slug = 'lightning-gun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLightning of Rotanev' WHERE slug = 'lightning-of-rotanev-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLion Claw' WHERE slug = 'lion-claw-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLion Eye' WHERE slug = 'lion-eye-costume' AND name_th IS NULL;