-- Migration 063: Thai names batch 10/10
-- Generated: 2026-03-16T03:42:16.055Z

UPDATE items SET name_th = 'สกินอาวุธLion Heart' WHERE slug = 'lion-heart-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLollipop' WHERE slug = 'lollipop-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLollipop (อีเวนต์)' WHERE slug = 'lollipop-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLos Enamorados' WHERE slug = 'los-enamorados-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธLust Bracelet' WHERE slug = 'lust-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธMachina of Spirit' WHERE slug = 'machina-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธMini-fan' WHERE slug = 'mini-fan-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธMini-fan (อีเวนต์)' WHERE slug = 'mini-fan-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธNaiads' WHERE slug = 'naiads-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธNightingale' WHERE slug = 'nightingale-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธNoche Frigid' WHERE slug = 'noche-frigid-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธNoche Triste' WHERE slug = 'noche-triste-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOctopus Bracelet' WHERE slug = 'octopus-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOctopus Fire Bracelet' WHERE slug = 'octopus-fire-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOctopus Ice Bracelet' WHERE slug = 'octopus-ice-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOctopus Lightning Bracelet' WHERE slug = 'octopus-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOgre Blade' WHERE slug = 'ogre-blade-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOgre Long Sword' WHERE slug = 'ogre-long-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOgre Orb' WHERE slug = 'ogre-orb-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOgre Pole-axe' WHERE slug = 'ogre-pole-axe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOgre Shotgun' WHERE slug = 'ogre-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOgre Sword' WHERE slug = 'ogre-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธOld BWitchs Room' WHERE slug = 'old-bwitchs-room-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธPandermonia' WHERE slug = 'pandermonia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธPassion of Regulus' WHERE slug = 'passion-of-regulus-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธPearl Scallop' WHERE slug = 'pearl-scallop-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธPhantom Guard' WHERE slug = 'phantom-guard-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธPierce of Vengeance' WHERE slug = 'pierce-of-vengeance-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Bracelet' WHERE slug = 'prospe-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Cannon' WHERE slug = 'prospe-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Controller' WHERE slug = 'prospe-controller-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Craft' WHERE slug = 'prospe-craft-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Crescent' WHERE slug = 'prospe-crescent-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Crossbow' WHERE slug = 'prospe-crossbow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Cube' WHERE slug = 'prospe-cube-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Dagger' WHERE slug = 'prospe-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Encyclopedia' WHERE slug = 'prospe-encyclopedia-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Flame Bangle' WHERE slug = 'prospe-flame-bangle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Ice Bangle' WHERE slug = 'prospe-ice-bangle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Javelin' WHERE slug = 'prospe-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Knuckle' WHERE slug = 'prospe-knuckle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Leg-Guards' WHERE slug = 'prospe-leg-guards-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Lightning Bangle' WHERE slug = 'prospe-lightning-bangle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Magic Scroll' WHERE slug = 'prospe-magic-scroll-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Main-Gauche' WHERE slug = 'prospe-main-gauche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Pendant' WHERE slug = 'prospe-pendant-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Polearm' WHERE slug = 'prospe-polearm-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Rapier' WHERE slug = 'prospe-rapier-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Revolver' WHERE slug = 'prospe-revolver-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Rifle' WHERE slug = 'prospe-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Rod' WHERE slug = 'prospe-rod-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Rosario' WHERE slug = 'prospe-rosario-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Shamshir' WHERE slug = 'prospe-shamshir-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Shotgun' WHERE slug = 'prospe-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Slayer' WHERE slug = 'prospe-slayer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธProspe Sword' WHERE slug = 'prospe-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธPurity of Aldebaran' WHERE slug = 'purity-of-aldebaran-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธQuasar of Spirit' WHERE slug = 'quasar-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธRelief of Deneb' WHERE slug = 'relief-of-deneb-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธResurrection of Evil' WHERE slug = 'resurrection-of-evil-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธRiposte of Arachne' WHERE slug = 'riposte-of-arachne-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธRuby Dragon Bayonet' WHERE slug = 'ruby-dragon-bayonet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธRuby Dragon' WHERE slug = 'ruby-dragon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSerpent Cannon' WHERE slug = 'serpent-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSerpent Javelin' WHERE slug = 'serpent-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSerpent Main-Gauche' WHERE slug = 'serpent-main-gauche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSerpent Revolver' WHERE slug = 'serpent-revolver-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSerpent Rifle' WHERE slug = 'serpent-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSerpent Shooter' WHERE slug = 'serpent-shooter-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSerpent Spear' WHERE slug = 'serpent-spear-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธShark Cannon' WHERE slug = 'shark-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSilver Herberthe' WHERE slug = 'silver-herberthe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSteel Fort' WHERE slug = 'steel-fort-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStormbringer' WHERE slug = 'stormbringer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Bayonet' WHERE slug = 'strata-devil-bayonet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Blunt' WHERE slug = 'strata-devil-blunt-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Bracelet' WHERE slug = 'strata-devil-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Cannon' WHERE slug = 'strata-devil-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Crescent' WHERE slug = 'strata-devil-crescent-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Crossbow' WHERE slug = 'strata-devil-crossbow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Dagger' WHERE slug = 'strata-devil-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Flame Bracelet' WHERE slug = 'strata-devil-flame-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Hammer' WHERE slug = 'strata-devil-hammer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Ice Bracelet' WHERE slug = 'strata-devil-ice-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Javelin' WHERE slug = 'strata-devil-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Knuckle' WHERE slug = 'strata-devil-knuckle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Leg-Guard' WHERE slug = 'strata-devil-leg-guard-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Lightning Bracelet' WHERE slug = 'strata-devil-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Lute' WHERE slug = 'strata-devil-lute-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Main-Gauche' WHERE slug = 'strata-devil-main-gauche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Pistol' WHERE slug = 'strata-devil-pistol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Polearm' WHERE slug = 'strata-devil-polearm-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Rapier' WHERE slug = 'strata-devil-rapier-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Rifle' WHERE slug = 'strata-devil-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Rod' WHERE slug = 'strata-devil-rod-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Sabre' WHERE slug = 'strata-devil-sabre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Shield' WHERE slug = 'strata-devil-shield-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Shotgun' WHERE slug = 'strata-devil-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Slayer' WHERE slug = 'strata-devil-slayer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Staff' WHERE slug = 'strata-devil-staff-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Sword' WHERE slug = 'strata-devil-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธStrata Devil Tonfa' WHERE slug = 'strata-devil-tonfa-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSugar Seahorse' WHERE slug = 'sugar-seahorse-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSword of Knight' WHERE slug = 'sword-of-knight-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSword of the King' WHERE slug = 'sword-of-the-king-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธSword of the Queen' WHERE slug = 'sword-of-the-queen-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTempest of Aquarius' WHERE slug = 'tempest-of-aquarius-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTested Burst of Spirit' WHERE slug = 'tested-burst-of-spirit-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Axe of Lie' WHERE slug = 'the-axe-of-lie-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Canon of Detractor' WHERE slug = 'the-canon-of-detractor-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Control of Ophiuchus' WHERE slug = 'the-control-of-ophiuchus-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Crescent of Avenger' WHERE slug = 'the-crescent-of-avenger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Crossbow of Apostate' WHERE slug = 'the-crossbow-of-apostate-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Dagger of Greed' WHERE slug = 'the-dagger-of-greed-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Hammer of Sloth' WHERE slug = 'the-hammer-of-sloth-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Knuckle of Temptation' WHERE slug = 'the-knuckle-of-temptation-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Leg-Guard of Gluttony' WHERE slug = 'the-leg-guard-of-gluttony-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Rapier of Imitator' WHERE slug = 'the-rapier-of-imitator-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Revolver of Revenge' WHERE slug = 'the-revolver-of-revenge-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Rod of Pride' WHERE slug = 'the-rod-of-pride-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Tonfa of Wrath' WHERE slug = 'the-tonfa-of-wrath-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThe Zweihander of Soul' WHERE slug = 'the-zweihander-of-soul-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธThunder Edge' WHERE slug = 'thunder-edge-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธToy Hammer' WHERE slug = 'toy-hammer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธToy Hammer (อีเวนต์)' WHERE slug = 'toy-hammer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTroopers Sabre' WHERE slug = 'troopers-sabre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Axe' WHERE slug = 'tyrant-axe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Axe (อีเวนต์)' WHERE slug = 'tyrant-axe-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Bracelet' WHERE slug = 'tyrant-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Buster' WHERE slug = 'tyrant-buster-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Buster (อีเวนต์)' WHERE slug = 'tyrant-buster-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Canno (อีเวนต์)' WHERE slug = 'tyrant-canno-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Cannon' WHERE slug = 'tyrant-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Crescent' WHERE slug = 'tyrant-crescent-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Crescent (อีเวนต์)' WHERE slug = 'tyrant-crescent-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Crossbow' WHERE slug = 'tyrant-crossbow-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Crossbow (อีเวนต์)' WHERE slug = 'tyrant-crossbow-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Dagger' WHERE slug = 'tyrant-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Dagger (อีเวนต์)' WHERE slug = 'tyrant-dagger-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Flame Blacelete (อีเวนต์)' WHERE slug = 'tyrant-flame-blacelete-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Flame Bracelet' WHERE slug = 'tyrant-flame-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Grimore' WHERE slug = 'tyrant-grimore-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Grimore (อีเวนต์)' WHERE slug = 'tyrant-grimore-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Halberd' WHERE slug = 'tyrant-halberd-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Halberde (อีเวนต์)' WHERE slug = 'tyrant-halberde-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Ice Bracelet' WHERE slug = 'tyrant-ice-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Ice Bracelete (อีเวนต์)' WHERE slug = 'tyrant-ice-bracelete-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Javelin' WHERE slug = 'tyrant-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Javelin (อีเวนต์)' WHERE slug = 'tyrant-javelin-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Knuckle' WHERE slug = 'tyrant-knuckle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Knuckle (อีเวนต์)' WHERE slug = 'tyrant-knuckle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Lightning Bracelet' WHERE slug = 'tyrant-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Lightning Bracelete (อีเวนต์)' WHERE slug = 'tyrant-lightning-bracelete-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Lute' WHERE slug = 'tyrant-lute-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Lute (อีเวนต์)' WHERE slug = 'tyrant-lute-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Main-Gauche' WHERE slug = 'tyrant-main-gauche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Main-Gauche (อีเวนต์)' WHERE slug = 'tyrant-main-gauche-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Raipier (อีเวนต์)' WHERE slug = 'tyrant-raipier-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Rapier' WHERE slug = 'tyrant-rapier-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Revolver' WHERE slug = 'tyrant-revolver-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Revolver (อีเวนต์)' WHERE slug = 'tyrant-revolver-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Rifel (อีเวนต์)' WHERE slug = 'tyrant-rifel-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Rifle' WHERE slug = 'tyrant-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Rod' WHERE slug = 'tyrant-rod-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Rode (อีเวนต์)' WHERE slug = 'tyrant-rode-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Sabre (อีเวนต์)' WHERE slug = 'tyrant-sabre-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Shotgun' WHERE slug = 'tyrant-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Shotgun (อีเวนต์)' WHERE slug = 'tyrant-shotgun-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Slayer' WHERE slug = 'tyrant-slayer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Slayer (อีเวนต์)' WHERE slug = 'tyrant-slayer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Staff' WHERE slug = 'tyrant-staff-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Staff (อีเวนต์)' WHERE slug = 'tyrant-staff-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Sword' WHERE slug = 'tyrant-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธTyrant Sword (อีเวนต์)' WHERE slug = 'tyrant-sword-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธUnlawful Bayonet' WHERE slug = 'unlawful-bayonet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Blade' WHERE slug = 'vernier-blade-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Blade (อีเวนต์)' WHERE slug = 'vernier-blade-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Bracelet' WHERE slug = 'vernier-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Bracelet (อีเวนต์)' WHERE slug = 'vernier-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Broom Stick' WHERE slug = 'vernier-broom-stick-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Broom Stick (อีเวนต์)' WHERE slug = 'vernier-broom-stick-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Cannon' WHERE slug = 'vernier-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Cannon (อีเวนต์)' WHERE slug = 'vernier-cannon-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Cube' WHERE slug = 'vernier-cube-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Cube (อีเวนต์)' WHERE slug = 'vernier-cube-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Dagger' WHERE slug = 'vernier-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Dagger (อีเวนต์)' WHERE slug = 'vernier-dagger-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Fire Bracelet' WHERE slug = 'vernier-fire-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Fire Bracelet (อีเวนต์)' WHERE slug = 'vernier-fire-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Javelin' WHERE slug = 'vernier-javelin-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Javelin (อีเวนต์)' WHERE slug = 'vernier-javelin-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Knuckle' WHERE slug = 'vernier-knuckle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Knuckle (อีเวนต์)' WHERE slug = 'vernier-knuckle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Lightning Bracelet' WHERE slug = 'vernier-lightning-bracelet-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Lightning Bracelet (อีเวนต์)' WHERE slug = 'vernier-lightning-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Lute' WHERE slug = 'vernier-lute-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Lute (อีเวนต์)' WHERE slug = 'vernier-lute-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Magic Scroll' WHERE slug = 'vernier-magic-scroll-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Magic Scroll (อีเวนต์)' WHERE slug = 'vernier-magic-scroll-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Main-Gauche' WHERE slug = 'vernier-main-gauche-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Main-Gauche (อีเวนต์)' WHERE slug = 'vernier-main-gauche-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Pistol' WHERE slug = 'vernier-pistol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Pistol (อีเวนต์)' WHERE slug = 'vernier-pistol-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Polearm' WHERE slug = 'vernier-polearm-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Polearm (อีเวนต์)' WHERE slug = 'vernier-polearm-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Rifle' WHERE slug = 'vernier-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Rifle (อีเวนต์)' WHERE slug = 'vernier-rifle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Rod' WHERE slug = 'vernier-rod-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Rod (อีเวนต์)' WHERE slug = 'vernier-rod-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Sabre' WHERE slug = 'vernier-sabre-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Sabre (อีเวนต์)' WHERE slug = 'vernier-sabre-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Shield' WHERE slug = 'vernier-shield-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Shield (อีเวนต์)' WHERE slug = 'vernier-shield-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Shotgun' WHERE slug = 'vernier-shotgun-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Shotgun (อีเวนต์)' WHERE slug = 'vernier-shotgun-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Slayer' WHERE slug = 'vernier-slayer-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Slayer (อีเวนต์)' WHERE slug = 'vernier-slayer-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Staff' WHERE slug = 'vernier-staff-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธVernier Staff (อีเวนต์)' WHERE slug = 'vernier-staff-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWar Crescent' WHERE slug = 'war-crescent-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWar Prominence' WHERE slug = 'war-prominence-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWasp' WHERE slug = 'wasp-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWater Pistol' WHERE slug = 'water-pistol-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWater Pistol (อีเวนต์)' WHERE slug = 'water-pistol-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWater Rifle' WHERE slug = 'water-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWater Rifle (อีเวนต์)' WHERE slug = 'water-rifle-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWerebear Cannon' WHERE slug = 'werebear-cannon-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWerebear Mace' WHERE slug = 'werebear-mace-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWerebear Morning Star' WHERE slug = 'werebear-morning-star-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWerebear Poleaxe' WHERE slug = 'werebear-poleaxe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWerewolf Axe' WHERE slug = 'werewolf-axe-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWerewolf Rifle' WHERE slug = 'werewolf-rifle-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWerewolf Sword' WHERE slug = 'werewolf-sword-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWhite Bishop' WHERE slug = 'white-bishop-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWhite Dagger' WHERE slug = 'white-dagger-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWill of Acubens' WHERE slug = 'will-of-acubens-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWitch Craft' WHERE slug = 'witch-craft-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'สกินอาวุธWits of Gemini' WHERE slug = 'wits-of-gemini-costume' AND name_th IS NULL;