-- Migration 064: Thai names remaining v2 batch 1/9
-- Generated: 2026-03-16T03:55:14.473Z

UPDATE items SET name_th = 'อาร์มชิลด์ of Contract (7 วัน)' WHERE slug = 'arm-shield-of-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์มชิลด์ Glove of Selva' WHERE slug = 'glove-of-selva' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Black shiny Armonium Necklace.' WHERE slug = 'black-shiny-armonium-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Caisses Coat' WHERE slug = 'caisses-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Chungs Hairpin' WHERE slug = 'chungs-hairpin' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Cionas Circlet' WHERE slug = 'cionas-circlet' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Dragon Spirit' WHERE slug = 'dragon-spirit' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Eagle Eye in the Moonlight' WHERE slug = 'eagle-eye-in-the-moonlight' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Earring of Heaven' WHERE slug = 'earring-of-heaven' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elegant Corsage' WHERE slug = 'elegant-corsage' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Arcard Pierce' WHERE slug = 'elite-arcard-pierce' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Armonia Halidom.' WHERE slug = 'elite-armonia-halidom' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Armonias Will' WHERE slug = 'elite-armonias-will' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Black Rose' WHERE slug = 'elite-black-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Bloody Rose' WHERE slug = 'elite-bloody-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Bristias Decision' WHERE slug = 'elite-bristias-decision' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Eternal Life of the Rose Duchess' WHERE slug = 'elite-eternal-life-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Fire Lizard' WHERE slug = 'elite-fire-lizard' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Ice Toad' WHERE slug = 'elite-ice-toad' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Illiers Punishment' WHERE slug = 'elite-illiers-punishment' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Iron Heart' WHERE slug = 'elite-iron-heart' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Iron Heart (1 วัน)' WHERE slug = 'elite-iron-heart-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Iron Mirror' WHERE slug = 'elite-iron-mirror' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Iron Mirror (1 วัน)' WHERE slug = 'elite-iron-mirror-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Jealousy of Rose Duchess (1 วัน)' WHERE slug = 'elite-jealousy-of-rose-duchess-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Jealousy of the Rose Duchess' WHERE slug = 'elite-jealousy-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Jurgens Atone' WHERE slug = 'elite-jurgens-atone' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Jurgens Protection' WHERE slug = 'elite-jurgens-protection' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Jurgens Sharpness' WHERE slug = 'elite-jurgens-sharpness' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Lavids Dash' WHERE slug = 'elite-lavids-dash' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Lavids Dash Swift Attack' WHERE slug = 'elite-lavids-dash-swift-attack' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Lavids Dash Swift Foresight' WHERE slug = 'elite-lavids-dash-swift-foresight' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Lightning Turtle' WHERE slug = 'elite-lightning-turtle' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Memento Moris Scroll' WHERE slug = 'elite-memento-moris-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Miracle of Rose Duchess (1 วัน)' WHERE slug = 'elite-miracle-of-rose-duchess-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Miracle of the Rose Duchess' WHERE slug = 'elite-miracle-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Passion of Rose Duchess (1 วัน)' WHERE slug = 'elite-passion-of-rose-duchess-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Passion of the Rose Duchess' WHERE slug = 'elite-passion-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Perennity of Rose Duchess (1 วัน)' WHERE slug = 'elite-perennity-of-rose-duchess-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Pioneer Pierce' WHERE slug = 'elite-pioneer-pierce' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Presto' WHERE slug = 'elite-presto' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Psychic Snake' WHERE slug = 'elite-psychic-snake' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Purity of Rose Duchess (1 วัน)' WHERE slug = 'elite-purity-of-rose-duchess-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Purity of the Rose Duchess' WHERE slug = 'elite-purity-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Repairmans Bolt' WHERE slug = 'elite-repairmans-bolt' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Repairmans Nut' WHERE slug = 'elite-repairmans-nut' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Selenes Heart' WHERE slug = 'elite-selenes-heart' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Selenes Memory' WHERE slug = 'elite-selenes-memory' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Selenes Tear' WHERE slug = 'elite-selenes-tear' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Shining Rose' WHERE slug = 'elite-shining-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Trumans Stick' WHERE slug = 'elite-trumans-stick' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Trumans Stick (1 วัน)' WHERE slug = 'elite-trumans-stick-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Trumans Watch' WHERE slug = 'elite-trumans-watch' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Trumans Watch (1 วัน)' WHERE slug = 'elite-trumans-watch-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Elite Vespanolas Dauntlessness' WHERE slug = 'elite-vespanolas-dauntlessness' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Emergency Repair Tool Box' WHERE slug = 'emergency-repair-tool-box' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Enmas Gauntlets' WHERE slug = 'enmas-gauntlets' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Enochs Book' WHERE slug = 'enochs-book' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Epaulet of Vespanola Navy Admiral' WHERE slug = 'epaulet-of-vespanola-navy-admiral' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Eternal Life of the Rose Duchess' WHERE slug = 'eternal-life-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Eternal Promise' WHERE slug = 'eternal-promise' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Excruciating Memory' WHERE slug = 'excruciating-memory' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Extreme Evil - Pa' WHERE slug = 'extreme-evil-pa' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Extreme Nothingness - Pa' WHERE slug = 'extreme-nothingness-pa' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Eyeshadow' WHERE slug = 'eyeshadow' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ferruccios Will' WHERE slug = 'ferruccios-will' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Field Supply' WHERE slug = 'field-supply' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Fire Crystal' WHERE slug = 'fire-crystal' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Fire Lizard' WHERE slug = 'fire-lizard' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Firmness of Uraeus' WHERE slug = 'firmness-of-uraeus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค First-Aid Kit' WHERE slug = 'first-aid-kit' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Folded Uniform of Butler' WHERE slug = 'folded-uniform-of-butler' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Foreign Words Collection' WHERE slug = 'foreign-words-collection' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Formula of Martial Arts' WHERE slug = 'formula-of-martial-arts' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Fountain Pen' WHERE slug = 'fountain-pen' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Fragment of Cortes' WHERE slug = 'fragment-of-cortes' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Friend' WHERE slug = 'friend' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Friendly Looking Picture' WHERE slug = 'friendly-looking-picture' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Frio' WHERE slug = 'frio' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค GEs 13rd Anniversary Artifact' WHERE slug = 'ges-13rd-anniversary-artifact' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Goddess of Wind' WHERE slug = 'goddess-of-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Golden Compass' WHERE slug = 'golden-compass' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Golden-watch String' WHERE slug = 'golden-watch-string' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Gondos Crystal Marble' WHERE slug = 'gondos-crystal-marble' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Grand Saintess Rosario' WHERE slug = 'grand-saintess-rosario' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Grand Splendors' WHERE slug = 'grand-splendors' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Guardian Cloth of Heaven' WHERE slug = 'guardian-cloth-of-heaven' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Hair of Catherine' WHERE slug = 'hair-of-catherine' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Hanbok Norigae' WHERE slug = 'hanbok-norigae' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Haunted House' WHERE slug = 'haunted-house' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Heart of Selene' WHERE slug = 'heart-of-selene' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Her Photo' WHERE slug = 'her-photo' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Hethors Hammer' WHERE slug = 'hethors-hammer' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Heyran Pendant' WHERE slug = 'heyran-pendant' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Honorary Medal' WHERE slug = 'honorary-medal' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Hourglass of Dimensions' WHERE slug = 'hourglass-of-dimensions' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Hunting Trident' WHERE slug = 'hunting-trident' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ice Fox Statue' WHERE slug = 'ice-fox-statue' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ice Toad' WHERE slug = 'ice-toad' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Identification Tag' WHERE slug = 'identification-tag' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Il Principe' WHERE slug = 'il-principe' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Illiers punishment' WHERE slug = 'illiers-punishment' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Indicatore' WHERE slug = 'indicatore' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Insight of Elite Talos' WHERE slug = 'insight-of-elite-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Insight of Old Talos' WHERE slug = 'insight-of-old-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Insight of Talos' WHERE slug = 'insight-of-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Insight of Vergo the Cursed' WHERE slug = 'insight-of-vergo-the-cursed' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Intelligence of Dekaravia' WHERE slug = 'intelligence-of-dekaravia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Iron Bar with a Button' WHERE slug = 'iron-bar-with-a-button' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Iron Heart' WHERE slug = 'iron-heart' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Iron Mirror' WHERE slug = 'iron-mirror' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Iron Wall Gauntlet (Block)' WHERE slug = 'iron-wall-gauntlet-block' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Iron Wall Gauntlet (Evasion)' WHERE slug = 'iron-wall-gauntlet-evasion' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Iron Wall Gauntlet (Immunity)' WHERE slug = 'iron-wall-gauntlet-immunity' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Jealousy of the Rose Duchess' WHERE slug = 'jealousy-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Johnnys Perch' WHERE slug = 'johnnys-perch' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Journal Smeared with Ferruccio Breadcrumbs' WHERE slug = 'journal-smeared-with-ferruccio-breadcrumbs' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Jurgens Atone' WHERE slug = 'jurgens-atone' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Jurgens Protection' WHERE slug = 'jurgens-protection' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Jurgens Sharpness' WHERE slug = 'jurgens-sharpness' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Kassanos Sandglass' WHERE slug = 'kassanos-sandglass' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Kassanos Sandglass of Agility' WHERE slug = 'kassanos-sandglass-of-agility' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Kassanos Sandglass of Dexterity' WHERE slug = 'kassanos-sandglass-of-dexterity' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Kassanos Sandglass of Health' WHERE slug = 'kassanos-sandglass-of-health' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Kassanos Sandglass of Intelligence' WHERE slug = 'kassanos-sandglass-of-intelligence' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Kassanos Sandglass of Sensation' WHERE slug = 'kassanos-sandglass-of-sensation' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Kassanos Sandglass of Strength' WHERE slug = 'kassanos-sandglass-of-strength' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Kohinoor' WHERE slug = 'kohinoor' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Koko Hand Mirror' WHERE slug = 'koko-hand-mirror' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Lais Grimoire' WHERE slug = 'lais-grimoire' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Last Apocalypse' WHERE slug = 'last-apocalypse' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Lavids Dash' WHERE slug = 'lavids-dash' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Lavids Dash Swift Attack' WHERE slug = 'lavids-dash-swift-attack' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Lavids Dash Swift Foresight' WHERE slug = 'lavids-dash-swift-foresight' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Leather Sheath' WHERE slug = 'leather-sheath' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Lepin Noir' WHERE slug = 'lepin-noir' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Letter of Jesus' WHERE slug = 'letter-of-jesus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Letter to Romina' WHERE slug = 'letter-to-romina' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Leviathans Scale' WHERE slug = 'leviathans-scale' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Liberta' WHERE slug = 'liberta' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Life of Queenz-eater' WHERE slug = 'life-of-queenz-eater' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Lightning Turtle' WHERE slug = 'lightning-turtle' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Locket of Goddess' WHERE slug = 'locket-of-goddess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Lorchs Letter' WHERE slug = 'lorchs-letter' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Magical Tool Box' WHERE slug = 'magical-tool-box' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Mask of Clown' WHERE slug = 'mask-of-clown' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Masters Hammer' WHERE slug = 'masters-hammer' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Masters Red Bolt' WHERE slug = 'masters-red-bolt' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Masters Red Nut' WHERE slug = 'masters-red-nut' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Masters Spanner' WHERE slug = 'masters-spanner' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Memento Moris Scroll' WHERE slug = 'memento-moris-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Memory of Selene' WHERE slug = 'memory-of-selene' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Mer Libre' WHERE slug = 'mer-libre' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Meriels Music Book for Beginners' WHERE slug = 'meriels-music-book-for-beginners' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Mermobas Balance' WHERE slug = 'mermobas-balance' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Mind Circlet' WHERE slug = 'mind-circlet' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Miracle of the Rose Duchess' WHERE slug = 'miracle-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Mirror of Memory' WHERE slug = 'mirror-of-memory' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Misfired Cannon Ball' WHERE slug = 'misfired-cannon-ball' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Mittens' WHERE slug = 'mittens' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Moms Hairpin' WHERE slug = 'moms-hairpin' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Moonlight Masters Bolt' WHERE slug = 'moonlight-masters-bolt' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Moonlight Masters Nut' WHERE slug = 'moonlight-masters-nut' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Mortar' WHERE slug = 'mortar' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Mustache Comb' WHERE slug = 'mustache-comb' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Necklace of Elemental Force.' WHERE slug = 'necklace-of-elemental-force' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Non-partha' WHERE slug = 'non-partha' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Nut of Repairman' WHERE slug = 'nut-of-repairman' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Armonia Halidom' WHERE slug = 'old-armonia-halidom' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Armonias Will' WHERE slug = 'old-armonias-will' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Assault of Uraeus' WHERE slug = 'old-assault-of-uraeus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Black Rose' WHERE slug = 'old-black-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Bloody Rose' WHERE slug = 'old-bloody-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Bristias Decision' WHERE slug = 'old-bristias-decision' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Brutality of Vergo the Cursed' WHERE slug = 'old-brutality-of-vergo-the-cursed' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Compass' WHERE slug = 'old-compass' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Eternal Life of the Rose Duchess' WHERE slug = 'old-eternal-life-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Fire Lizard' WHERE slug = 'old-fire-lizard' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Firmness of Uraeus' WHERE slug = 'old-firmness-of-uraeus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Ice Toad' WHERE slug = 'old-ice-toad' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Illiers Punishment' WHERE slug = 'old-illiers-punishment' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Insight of Vergo the Cursed' WHERE slug = 'old-insight-of-vergo-the-cursed' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Iron Heart' WHERE slug = 'old-iron-heart' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Iron Mirror' WHERE slug = 'old-iron-mirror' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Jealousy of the Rose Duchess' WHERE slug = 'old-jealousy-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Jurgens Atone' WHERE slug = 'old-jurgens-atone' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Jurgens Protection' WHERE slug = 'old-jurgens-protection' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Jurgens Sharpness' WHERE slug = 'old-jurgens-sharpness' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Lavids Dash' WHERE slug = 'old-lavids-dash' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Lavids Dash Swift Attack' WHERE slug = 'old-lavids-dash-swift-attack' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Lavids Dash Swift Foresight' WHERE slug = 'old-lavids-dash-swift-foresight' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Life of Queenz-eater' WHERE slug = 'old-life-of-queenz-eater' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Lightning Turtle' WHERE slug = 'old-lightning-turtle' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Memento Moris Scroll' WHERE slug = 'old-memento-moris-scroll' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Military Uniform' WHERE slug = 'old-military-uniform' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Miracle of the Rose Duchess' WHERE slug = 'old-miracle-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Passion of the Rose Duchess' WHERE slug = 'old-passion-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Presto' WHERE slug = 'old-presto' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Promptness of Griffon' WHERE slug = 'old-promptness-of-griffon' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Psychic Snake' WHERE slug = 'old-psychic-snake' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Purity of the Rose Duchess' WHERE slug = 'old-purity-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Recovery of Queenz-eater' WHERE slug = 'old-recovery-of-queenz-eater' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Repairmans Bolt' WHERE slug = 'old-repairmans-bolt' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Repairmans Nut' WHERE slug = 'old-repairmans-nut' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Resistance of Dekaravia' WHERE slug = 'old-resistance-of-dekaravia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Selenes Heart' WHERE slug = 'old-selenes-heart' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Selenes Memory' WHERE slug = 'old-selenes-memory' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Selenes Tear' WHERE slug = 'old-selenes-tear' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Sensuality of Diablo' WHERE slug = 'old-sensuality-of-diablo' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Shining Rose' WHERE slug = 'old-shining-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Swiftness of Griffon' WHERE slug = 'old-swiftness-of-griffon' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Time of Diablo' WHERE slug = 'old-time-of-diablo' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Trumans Stick' WHERE slug = 'old-trumans-stick' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Trumans Watch' WHERE slug = 'old-trumans-watch' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Vespanolas Dauntlessness' WHERE slug = 'old-vespanolas-dauntlessness' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Old Wisdom of Dekaravia' WHERE slug = 'old-wisdom-of-dekaravia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Operation 1321' WHERE slug = 'operation-1321' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ordens Arrogance' WHERE slug = 'ordens-arrogance' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ordens Dream' WHERE slug = 'ordens-dream' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ordens Fury' WHERE slug = 'ordens-fury' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ordens Greed' WHERE slug = 'ordens-greed' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ordens Jealousy' WHERE slug = 'ordens-jealousy' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ordens Sloth' WHERE slug = 'ordens-sloth' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Panfilos Lunch' WHERE slug = 'panfilos-lunch' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Passion of the Rose Duchess' WHERE slug = 'passion-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pecrencia' WHERE slug = 'pecrencia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pick' WHERE slug = 'pick' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pink Scarf' WHERE slug = 'pink-scarf' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pioneers Pierce(Event (15 days))' WHERE slug = 'pioneers-pierce-event-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pioneers Pierce(Event (30 days))' WHERE slug = 'pioneers-pierce-event-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pioneers Pierce(Event - 1 Day)' WHERE slug = 'pioneers-pierce-event-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pioneers Pierce(Event - 10 Days)' WHERE slug = 'pioneers-pierce-event-10-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pioneers Pierce(Event - 5 Days)' WHERE slug = 'pioneers-pierce-event-5-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pirate Flag' WHERE slug = 'pirate-flag' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Pocket Watch' WHERE slug = 'pocket-watch' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Poor Pear Slice' WHERE slug = 'poor-pear-slice' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Portrait of Nena' WHERE slug = 'portrait-of-nena' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Power of Elite Talos' WHERE slug = 'power-of-elite-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Power of Old Talos' WHERE slug = 'power-of-old-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Power of Talos' WHERE slug = 'power-of-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Presto' WHERE slug = 'presto' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Primus' WHERE slug = 'primus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Promptness of Griffon' WHERE slug = 'promptness-of-griffon' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Proof of Defence' WHERE slug = 'proof-of-defence' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Proof of Intrepidity' WHERE slug = 'proof-of-intrepidity' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Psychic Snake' WHERE slug = 'psychic-snake' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Psychic magic ring' WHERE slug = 'psychic-magic-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Purity of the Rose Duchess' WHERE slug = 'purity-of-the-rose-duchess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Quartz Bullet' WHERE slug = 'quartz-bullet' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค ROBO R 90' WHERE slug = 'robo-r-90' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Recovery of Queenz-eater' WHERE slug = 'recovery-of-queenz-eater' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Recruiting Flyer' WHERE slug = 'recruiting-flyer' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Red Carriage' WHERE slug = 'red-carriage' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Red Hairband' WHERE slug = 'red-hairband' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Red Scarf' WHERE slug = 'red-scarf' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Regeneration and Circulation' WHERE slug = 'regeneration-and-circulation' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Remains of Water' WHERE slug = 'remains-of-water' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Resistance of Dekaravia' WHERE slug = 'resistance-of-dekaravia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ring Made of shell' WHERE slug = 'ring-made-of-shell' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ring of Queen' WHERE slug = 'ring-of-queen' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ring of Sniper' WHERE slug = 'ring-of-sniper' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ring of the Old Moon Sniper' WHERE slug = 'ring-of-the-old-moon-sniper' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Rose Kitchen Knife' WHERE slug = 'rose-kitchen-knife' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Roses Heart' WHERE slug = 'roses-heart' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ruby of Red Flame' WHERE slug = 'ruby-of-red-flame' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Sagrada Memoria' WHERE slug = 'sagrada-memoria' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Salamander Stone' WHERE slug = 'salamander-stone' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Sandglass of Soul' WHERE slug = 'sandglass-of-soul' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Saol Dark Bullet' WHERE slug = 'saol-dark-bullet' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Scale of Dragon' WHERE slug = 'scale-of-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Scope' WHERE slug = 'scope' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Secret Book : Moon Walk' WHERE slug = 'secret-book-moon-walk' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Selenes Black Heart' WHERE slug = 'selenes-black-heart' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Selenes Bolt' WHERE slug = 'selenes-bolt' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Selenes Dark Memories' WHERE slug = 'selenes-dark-memories' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Selenes Nut' WHERE slug = 'selenes-nut' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Selenes Protection' WHERE slug = 'selenes-protection' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Selenes Rose' WHERE slug = 'selenes-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Sensation of Diablo' WHERE slug = 'sensation-of-diablo' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Sensuality of Diablo' WHERE slug = 'sensuality-of-diablo' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Sewing Kit' WHERE slug = 'sewing-kit' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Shield of spearhead' WHERE slug = 'shield-of-spearhead' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Shining Rose' WHERE slug = 'shining-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Shiny Bud' WHERE slug = 'shiny-bud' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Ship in a Bottle' WHERE slug = 'ship-in-a-bottle' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Shoulder Armor of Guardian' WHERE slug = 'shoulder-armor-of-guardian' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Silver Bullet' WHERE slug = 'silver-bullet' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Sketch Book' WHERE slug = 'sketch-book' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Skill of Vergo the Cursed' WHERE slug = 'skill-of-vergo-the-cursed' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Skull necklace' WHERE slug = 'skull-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Small Wooden Sword' WHERE slug = 'small-wooden-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul Stone of Argus' WHERE slug = 'soul-stone-of-argus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul Stone of Einschiever' WHERE slug = 'soul-stone-of-einschiever' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul Stone of Novia' WHERE slug = 'soul-stone-of-novia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul Stone of Old Argus' WHERE slug = 'soul-stone-of-old-argus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul Stone of Old Einschiever' WHERE slug = 'soul-stone-of-old-einschiever' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul Stone of Old Novia' WHERE slug = 'soul-stone-of-old-novia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul Stone of Old Sekhmet' WHERE slug = 'soul-stone-of-old-sekhmet' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul Stone of Sekhmet' WHERE slug = 'soul-stone-of-sekhmet' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Soul of Fox' WHERE slug = 'soul-of-fox' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Spirit of Atrocity[Nihil]' WHERE slug = 'spirit-of-atrocity-nihil' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Spirit of Devil[Nihil]' WHERE slug = 'spirit-of-devil-nihil' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Spirit of Fox' WHERE slug = 'spirit-of-fox' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Stained Mark of Engineer Element' WHERE slug = 'stained-mark-of-engineer-element' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Stamina of Queenz-eater' WHERE slug = 'stamina-of-queenz-eater' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Strange Metal Cluster' WHERE slug = 'strange-metal-cluster' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Strategic Manual - Bloody Navy' WHERE slug = 'strategic-manual-bloody-navy' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Strength of Uraeus' WHERE slug = 'strength-of-uraeus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Surra Zarka' WHERE slug = 'surra-zarka' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Suspicious Vial' WHERE slug = 'suspicious-vial' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Swiftness of Griffon' WHERE slug = 'swiftness-of-griffon' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Symbol of Absinian Warrior' WHERE slug = 'symbol-of-absinian-warrior' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Symbol of Bear' WHERE slug = 'symbol-of-bear' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Symbol of Eagle' WHERE slug = 'symbol-of-eagle' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Symbol of Leopard' WHERE slug = 'symbol-of-leopard' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Symbol of Mankind' WHERE slug = 'symbol-of-mankind' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Symbol of Snake' WHERE slug = 'symbol-of-snake' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Symbol of Tortoise' WHERE slug = 'symbol-of-tortoise' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Taegeuk Pattern Decoration' WHERE slug = 'taegeuk-pattern-decoration' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Talt Hammer' WHERE slug = 'talt-hammer' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Tattoo Design' WHERE slug = 'tattoo-design' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Tear of Selene' WHERE slug = 'tear-of-selene' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Tenacity of Elite Talos' WHERE slug = 'tenacity-of-elite-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Tenacity of Old Talos' WHERE slug = 'tenacity-of-old-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Tenacity of Talos' WHERE slug = 'tenacity-of-talos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค The Arrogance of Aquichtus' WHERE slug = 'the-arrogance-of-aquichtus' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค The Denial of Terhea' WHERE slug = 'the-denial-of-terhea' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค The Desire of Ignisia' WHERE slug = 'the-desire-of-ignisia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค The Eye of Goddess' WHERE slug = 'the-eye-of-goddess' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค The Old Postcard' WHERE slug = 'the-old-postcard' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค The Unrest of Spirica' WHERE slug = 'the-unrest-of-spirica' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค The Vanity of Ventuamos' WHERE slug = 'the-vanity-of-ventuamos' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Thick Fur Coat' WHERE slug = 'thick-fur-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Time of Diablo' WHERE slug = 'time-of-diablo' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Token of Maid' WHERE slug = 'token-of-maid' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Toms Doctors Bag' WHERE slug = 'toms-doctors-bag' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Tooth of Megalosaur' WHERE slug = 'tooth-of-megalosaur' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Treasure Golem Piece' WHERE slug = 'treasure-golem-piece' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Trumans Stick' WHERE slug = 'trumans-stick' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Trumans Watch' WHERE slug = 'trumans-watch' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Unbound Freedom' WHERE slug = 'unbound-freedom' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Unfinished Ordens Arrogance' WHERE slug = 'unfinished-ordens-arrogance' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Unfinished Ordens Fury' WHERE slug = 'unfinished-ordens-fury' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Unfinished Ordens Greed' WHERE slug = 'unfinished-ordens-greed' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Unfinished Ordens Jealousy' WHERE slug = 'unfinished-ordens-jealousy' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Unfinished Ordens Sloth' WHERE slug = 'unfinished-ordens-sloth' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Vespanolas Dauntlessness' WHERE slug = 'vespanolas-dauntlessness' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Violantes Bloodstone' WHERE slug = 'violantes-bloodstone' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Warriors Bandag.' WHERE slug = 'warriors-bandag' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Wet Logbook' WHERE slug = 'wet-logbook' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Wheel of Parmesan Cheese' WHERE slug = 'wheel-of-parmesan-cheese' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Wisdom of Dekaravia' WHERE slug = 'wisdom-of-dekaravia' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Wonderful Andromida' WHERE slug = 'wonderful-andromida' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค Zeia Recipe Book' WHERE slug = 'zeia-recipe-book' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์ติแฟค 초월자의 낡은 거울' WHERE slug = 'null' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Anchor' WHERE slug = 'anchor' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Anchor (15 วัน)' WHERE slug = 'anchor-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Anchor (7 วัน)' WHERE slug = 'anchor-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Anchor (for Attack)' WHERE slug = 'anchor-for-attack' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Anchor - (1 วัน)' WHERE slug = 'anchor-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Anchor - (30 วัน)' WHERE slug = 'anchor-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Anchor - (90 วัน)' WHERE slug = 'anchor-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Angel Wings - (1 วัน)' WHERE slug = 'angel-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Angel Wings - (30 วัน)' WHERE slug = 'angel-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Angel Wings - (90 วัน)' WHERE slug = 'angel-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Angels and Demons' WHERE slug = 'angels-and-demons' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Angels and Demons (1 วัน)' WHERE slug = 'angels-and-demons-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Angels and Demons (30 วัน)' WHERE slug = 'angels-and-demons-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Angels and Demons (7 วัน)' WHERE slug = 'angels-and-demons-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Angels and Demons (90 วัน)' WHERE slug = 'angels-and-demons-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Archangel Wings - (1 วัน)' WHERE slug = 'archangel-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Archangel Wings - (30 วัน)' WHERE slug = 'archangel-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Archangel Wings - (90 วัน)' WHERE slug = 'archangel-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Azul Puesta de sol' WHERE slug = 'azul-puesta-de-sol' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Azul Puesta de sol - (1 วัน)' WHERE slug = 'azul-puesta-de-sol-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Azul Puesta de sol - (30 วัน)' WHERE slug = 'azul-puesta-de-sol-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Azul Puesta de sol - (7 วัน)' WHERE slug = 'azul-puesta-de-sol-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Azul Puesta de sol - (90 วัน)' WHERE slug = 'azul-puesta-de-sol-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Fortitude' WHERE slug = 'batus-fortitude' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Fortitude (1 วัน)' WHERE slug = 'batus-fortitude-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Fortitude (15 วัน)' WHERE slug = 'batus-fortitude-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Fortitude (30 วัน)' WHERE slug = 'batus-fortitude-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Fortitude (7 วัน)' WHERE slug = 'batus-fortitude-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Fortitude (90 วัน)' WHERE slug = 'batus-fortitude-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Passion' WHERE slug = 'batus-passion' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Passion (1 วัน)' WHERE slug = 'batus-passion-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Passion (15 วัน)' WHERE slug = 'batus-passion-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Passion (30 วัน)' WHERE slug = 'batus-passion-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Passion (7 วัน)' WHERE slug = 'batus-passion-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Passion (90 วัน)' WHERE slug = 'batus-passion-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Salvation' WHERE slug = 'batus-salvation' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Salvation (1 วัน)' WHERE slug = 'batus-salvation-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Salvation (30 วัน)' WHERE slug = 'batus-salvation-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Salvation (7 วัน)' WHERE slug = 'batus-salvation-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Batus Salvation (90 วัน)' WHERE slug = 'batus-salvation-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงBeijing Olympics' WHERE slug = 'beijing-olympics-flag' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Black Angel Wings - (30 วัน)' WHERE slug = 'black-angel-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Black Angel Wings - (90 วัน)' WHERE slug = 'black-angel-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Black angel Wings - (1 วัน)' WHERE slug = 'black-angel-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Anchor (7 วัน)' WHERE slug = 'blessed-anchor-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Coimbra Sign (7 วัน)' WHERE slug = 'blessed-coimbra-sign-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Flower Vase (7 วัน)' WHERE slug = 'blessed-flower-vase-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Jabberwock Armor (7 วัน)' WHERE slug = 'blessed-jabberwock-armor-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Murderous Swords (7 วัน)' WHERE slug = 'blessed-murderous-swords-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Rucksack (7 วัน)' WHERE slug = 'blessed-rucksack-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Satchel (7 วัน)' WHERE slug = 'blessed-satchel-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Tortoise Shell (7 วัน)' WHERE slug = 'blessed-tortoise-shell-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blessed Treasure Chest (7 วัน)' WHERE slug = 'blessed-treasure-chest-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Bloody Coffin' WHERE slug = 'bloody-coffin' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Bloody Coffin (1 วัน)' WHERE slug = 'bloody-coffin-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Bloody Coffin (30 วัน)' WHERE slug = 'bloody-coffin-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Bloody Coffin (7 วัน)' WHERE slug = 'bloody-coffin-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Bloody Coffin (90 วัน)' WHERE slug = 'bloody-coffin-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Bloody coffin (2 วัน)' WHERE slug = 'bloody-coffin-2-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Bloody coffin (อีเวนต์)' WHERE slug = 'bloody-coffin-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blue Chrysalis Wings - (1 วัน)' WHERE slug = 'blue-chrysalis-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blue Chrysalis Wings - (30 วัน)' WHERE slug = 'blue-chrysalis-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blue Chrysalis Wings - (7 วัน)' WHERE slug = 'blue-chrysalis-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blue Chrysalis Wings - (90 วัน)' WHERE slug = 'blue-chrysalis-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Blue Wish Wing (Event, 15 days)' WHERE slug = 'blue-wish-wing-event-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เป้Brown Lunch' WHERE slug = 'brown-lunch-pack' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Brown Lunch Pack - (1 วัน)' WHERE slug = 'brown-lunch-pack-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Brown Lunch Pack - (30 วัน)' WHERE slug = 'brown-lunch-pack-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Brown Lunch Pack - (7 วัน)' WHERE slug = 'brown-lunch-pack-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Brown Lunch Pack - (90 วัน)' WHERE slug = 'brown-lunch-pack-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Christmas Rocket' WHERE slug = 'christmas-rocket' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Chrysalis Wings - (1 วัน)' WHERE slug = 'chrysalis-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Chrysalis Wings - (30 วัน)' WHERE slug = 'chrysalis-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Chrysalis Wings - (90 วัน)' WHERE slug = 'chrysalis-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Coffin of Jack O Lantern' WHERE slug = 'coffin-of-jack-o-lantern' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Coffin of Jack O Lantern (15 วัน)' WHERE slug = 'coffin-of-jack-o-lantern-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Coffin of Jack O Lantern (30 วัน)' WHERE slug = 'coffin-of-jack-o-lantern-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Coffin of Jack O Lantern (7 วัน)' WHERE slug = 'coffin-of-jack-o-lantern-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Coffin of Jack O Lantern (1 วัน)' WHERE slug = 'coffin-of-jack-o-lantern-1-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Coffin of Jack O Lantern (90 วัน)' WHERE slug = 'coffin-of-jack-o-lantern-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Crystal Wings - 365 days' WHERE slug = 'crystal-wings-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Crystal Wings - 90 days' WHERE slug = 'crystal-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Deadly Cross' WHERE slug = 'deadly-cross' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Deadly Cross (30 วัน)' WHERE slug = 'deadly-cross-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Deadly cross (1 วัน)' WHERE slug = 'deadly-cross-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Deadly cross (2 วัน)' WHERE slug = 'deadly-cross-2-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Deadly cross (7 วัน)' WHERE slug = 'deadly-cross-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Deadly cross (90 วัน)' WHERE slug = 'deadly-cross-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Deadly cross (อีเวนต์)' WHERE slug = 'deadly-cross-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Enhanced Crystal Wing (30 Days) (อีเวนต์)' WHERE slug = 'enhanced-crystal-wing-30-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Enhanced Crystal Wing (7 days) (อีเวนต์)' WHERE slug = 'enhanced-crystal-wing-7-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Enhanced Crystal Wing (90 Days) (อีเวนต์)' WHERE slug = 'enhanced-crystal-wing-90-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Enhanced Crystal Wing(15 days) (อีเวนต์)' WHERE slug = 'enhanced-crystal-wing-15-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่Event Heroic Back (15 วัน)' WHERE slug = 'event-heroic-back-shield-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Event Rudolph Doll' WHERE slug = 'event-rudolph-doll' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Evil Spirit Deprodine' WHERE slug = 'evil-spirit-deprodine' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Evil Spirit Deprodine (30 วัน)' WHERE slug = 'evil-spirit-deprodine-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Evil Spirit Deprodine - (1 วัน)' WHERE slug = 'evil-spirit-deprodine-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Evil Spirit Deprodine - (7 วัน)' WHERE slug = 'evil-spirit-deprodine-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Evil Spirit Deprodine - (90 วัน)' WHERE slug = 'evil-spirit-deprodine-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งArchduke' WHERE slug = 'flag-of-archduke' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งArchduke - (1 วัน)' WHERE slug = 'flag-of-archduke-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งArchduke - (30 วัน)' WHERE slug = 'flag-of-archduke-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งArchduke - (7 วัน)' WHERE slug = 'flag-of-archduke-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งArchduke - (90 วัน)' WHERE slug = 'flag-of-archduke-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งEarl' WHERE slug = 'flag-of-earl' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งEarl - (1 วัน)' WHERE slug = 'flag-of-earl-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งEarl - (30 วัน)' WHERE slug = 'flag-of-earl-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งEarl - (7 วัน)' WHERE slug = 'flag-of-earl-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งEarl - (90 วัน)' WHERE slug = 'flag-of-earl-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งGrandmaster' WHERE slug = 'flag-of-grandmaster' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งGrandmaster - (1 วัน)' WHERE slug = 'flag-of-grandmaster-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งGrandmaster - (30 วัน)' WHERE slug = 'flag-of-grandmaster-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งGrandmaster - (7 วัน)' WHERE slug = 'flag-of-grandmaster-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งGrandmaster - (90 วัน)' WHERE slug = 'flag-of-grandmaster-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งKnight' WHERE slug = 'flag-of-knight' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งKnight - (1 วัน)' WHERE slug = 'flag-of-knight-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งKnight - (30 วัน)' WHERE slug = 'flag-of-knight-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งKnight - (7 วัน)' WHERE slug = 'flag-of-knight-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งKnight - (90 วัน)' WHERE slug = 'flag-of-knight-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งMarquis' WHERE slug = 'flag-of-marquis' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งMarquis - (1 วัน)' WHERE slug = 'flag-of-marquis-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งMarquis - (30 วัน)' WHERE slug = 'flag-of-marquis-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งMarquis - (7 วัน)' WHERE slug = 'flag-of-marquis-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งMarquis - (90 วัน)' WHERE slug = 'flag-of-marquis-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งViscount' WHERE slug = 'flag-of-viscount' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งViscount - (1 วัน)' WHERE slug = 'flag-of-viscount-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งViscount - (30 วัน)' WHERE slug = 'flag-of-viscount-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งViscount - (7 วัน)' WHERE slug = 'flag-of-viscount-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงแห่งViscount - (90 วัน)' WHERE slug = 'flag-of-viscount-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Flower Vase' WHERE slug = 'flower-vase' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Flower Vase (15 วัน)' WHERE slug = 'flower-vase-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Flower Vase (7 วัน)' WHERE slug = 'flower-vase-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Flower Vase - (30 วัน)' WHERE slug = 'flower-vase-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Flower Vase - (90 วัน)' WHERE slug = 'flower-vase-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Flower vase - (1 วัน)' WHERE slug = 'flower-vase-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Full Moon Rabbit Doll' WHERE slug = 'full-moon-rabbit-doll' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Full Moon Rabbit Doll (1 วัน)' WHERE slug = 'full-moon-rabbit-doll-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Full Moon Rabbit Doll (30 วัน)' WHERE slug = 'full-moon-rabbit-doll-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Full Moon Rabbit Doll (7 วัน)' WHERE slug = 'full-moon-rabbit-doll-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Full Moon Rabbit Doll (90 วัน)' WHERE slug = 'full-moon-rabbit-doll-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Giant Spider Legs' WHERE slug = 'giant-spider-legs' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Giant Spider Legs (1 วัน)' WHERE slug = 'giant-spider-legs-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Giant Spider Legs (30 วัน)' WHERE slug = 'giant-spider-legs-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Giant Spider Legs (7 วัน)' WHERE slug = 'giant-spider-legs-7-days' AND name_th IS NULL;