-- Migration 065: Thai names remaining v2 batch 2/9
-- Generated: 2026-03-16T03:55:14.474Z

UPDATE items SET name_th = 'หลัง Giant Spider Legs (90 วัน)' WHERE slug = 'giant-spider-legs-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Golden Archangel Wings - (1 วัน)' WHERE slug = 'golden-archangel-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Golden Archangel Wings - (30 วัน)' WHERE slug = 'golden-archangel-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Golden Archangel Wings - (7 วัน)' WHERE slug = 'golden-archangel-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Golden Archangel Wings - (90 วัน)' WHERE slug = 'golden-archangel-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Golden Phoenix Wings - (1 วัน)' WHERE slug = 'golden-phoenix-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Golden Phoenix Wings - (30 วัน)' WHERE slug = 'golden-phoenix-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Golden Phoenix Wings - (7 วัน)' WHERE slug = 'golden-phoenix-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Golden Phoenix Wings - (90 วัน)' WHERE slug = 'golden-phoenix-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Grave Stone' WHERE slug = 'grave-stone' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Gravestone (1 วัน)' WHERE slug = 'gravestone-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Gravestone (30 วัน)' WHERE slug = 'gravestone-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Gravestone (7 วัน)' WHERE slug = 'gravestone-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Gravestone (90 วัน)' WHERE slug = 'gravestone-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เป้Green Lunch' WHERE slug = 'green-lunch-pack' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Green Lunch Pack - (1 วัน)' WHERE slug = 'green-lunch-pack-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Green Lunch Pack - (30 วัน)' WHERE slug = 'green-lunch-pack-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Green Lunch Pack - (7 วัน)' WHERE slug = 'green-lunch-pack-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Green Lunch Pack - (90 วัน)' WHERE slug = 'green-lunch-pack-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Grindstone' WHERE slug = 'grindstone' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่Heroic Back (30 วัน)' WHERE slug = 'heroic-back-shield-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่Heroic Back (365 วัน)' WHERE slug = 'heroic-back-shield-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่Heroic' WHERE slug = 'heroic-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Horn of Baphomet' WHERE slug = 'horn-of-baphomet' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Horn of Baphomet (1 วัน)' WHERE slug = 'horn-of-baphomet-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Horn of Baphomet (15 วัน)' WHERE slug = 'horn-of-baphomet-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Horn of Baphomet (30 วัน)' WHERE slug = 'horn-of-baphomet-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Horn of Baphomet (365 วัน)' WHERE slug = 'horn-of-baphomet-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Horn of Baphomet (7 วัน)' WHERE slug = 'horn-of-baphomet-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Horn of Baphomet (90 วัน)' WHERE slug = 'horn-of-baphomet-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงIndependence Day' WHERE slug = 'independence-day-flag' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงIndependence Day (1 วัน)' WHERE slug = 'independence-day-flag-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงIndependence Day (30 วัน)' WHERE slug = 'independence-day-flag-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงIndependence Day (7 วัน)' WHERE slug = 'independence-day-flag-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงIndependence Day (90 วัน)' WHERE slug = 'independence-day-flag-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Ivory Bag - (30 วัน)' WHERE slug = 'ivory-bag-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Ivory Bag - (90 วัน)' WHERE slug = 'ivory-bag-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Ivory bag - (1 วัน)' WHERE slug = 'ivory-bag-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Jabberwock Armor' WHERE slug = 'jabberwock-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Jabberwock Armor (15 วัน)' WHERE slug = 'jabberwock-armor-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Jabberwock Armor (7 วัน)' WHERE slug = 'jabberwock-armor-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Jabberwock Armor - (30 วัน)' WHERE slug = 'jabberwock-armor-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Jabberwock Armor - (90 วัน)' WHERE slug = 'jabberwock-armor-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Jabberwock armor - (1 วัน)' WHERE slug = 'jabberwock-armor-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Leaping Croc Bag - (30 วัน)' WHERE slug = 'leaping-croc-bag-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Leaping Croc Bag - (90 วัน)' WHERE slug = 'leaping-croc-bag-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Leaping Croc bag - (1 วัน)' WHERE slug = 'leaping-croc-bag-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Leather Sack' WHERE slug = 'leather-sack' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Morado Puesta de sol' WHERE slug = 'morado-puesta-de-sol' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Morado Puesta de sol - (1 วัน)' WHERE slug = 'morado-puesta-de-sol-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Morado Puesta de sol - (30 วัน)' WHERE slug = 'morado-puesta-de-sol-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Morado Puesta de sol - (7 วัน)' WHERE slug = 'morado-puesta-de-sol-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Morado Puesta de sol - (90 วัน)' WHERE slug = 'morado-puesta-de-sol-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Mortar (7 วัน)' WHERE slug = 'mortar-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Mortar - (1 วัน)' WHERE slug = 'mortar-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Mortar - (30 วัน)' WHERE slug = 'mortar-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Mortar - (7 วัน)' WHERE slug = 'mortar-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Mortar - (90 วัน)' WHERE slug = 'mortar-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Murderous Swords' WHERE slug = 'murderous-swords' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Murderous Swords (15 วัน)' WHERE slug = 'murderous-swords-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Murderous Swords (7 วัน)' WHERE slug = 'murderous-swords-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Murderous Swords - (30 วัน)' WHERE slug = 'murderous-swords-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Murderous Swords - (90 วัน)' WHERE slug = 'murderous-swords-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Murderous swords - (1 วัน)' WHERE slug = 'murderous-swords-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Mystical Rudolph Doll (7 วัน)' WHERE slug = 'mystical-rudolph-doll-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Nobles Court - Righteous Archduke (30 วัน)' WHERE slug = 'nobles-court-righteous-archduke-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Nobles Court - Righteous Earl (30 วัน)' WHERE slug = 'nobles-court-righteous-earl-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Nobles Court - Righteous Grandmaster (30 วัน)' WHERE slug = 'nobles-court-righteous-grandmaster-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Nobles Court - Righteous Knight (30 วัน)' WHERE slug = 'nobles-court-righteous-knight-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Nobles Court - Righteous Marquis (30 วัน)' WHERE slug = 'nobles-court-righteous-marquis-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Nobles Court - Righteous Viscount (30 วัน)' WHERE slug = 'nobles-court-righteous-viscount-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ธงOlympic' WHERE slug = 'olympic-flag' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Papillon L Costume' WHERE slug = 'papillon-l-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Papillon L Costume (1 day) (อีเวนต์)' WHERE slug = 'papillon-l-costume-1-day-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Papillon L Costume (15 วัน)' WHERE slug = 'papillon-l-costume-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Papillon L Costume (15 days) (อีเวนต์)' WHERE slug = 'papillon-l-costume-15-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Papillon L Costume (30 วัน)' WHERE slug = 'papillon-l-costume-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Papillon L Costume (30 days) (อีเวนต์)' WHERE slug = 'papillon-l-costume-30-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Papillon L Costume (7 วัน)' WHERE slug = 'papillon-l-costume-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Papillon L Costume (7 days) (อีเวนต์)' WHERE slug = 'papillon-l-costume-7-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Phoenix Wings - (30 วัน)' WHERE slug = 'phoenix-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Pioneer Wing (1 day) (อีเวนต์)' WHERE slug = 'pioneer-wing-1-day-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Pioneer Wing (15 days) (อีเวนต์)' WHERE slug = 'pioneer-wing-15-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Pioneer Wing (30 days) (อีเวนต์)' WHERE slug = 'pioneer-wing-30-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Pioneer Wing (7 days) (อีเวนต์)' WHERE slug = 'pioneer-wing-7-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Randocell (Black)' WHERE slug = 'randocell-black' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Randocell (Red)' WHERE slug = 'randocell-red' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Devils Wing (7 days) (อีเวนต์)' WHERE slug = 'red-devils-wing-7-days-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เป้Red Lunch' WHERE slug = 'red-lunch-pack' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Lunch Pack - (1 วัน)' WHERE slug = 'red-lunch-pack-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Lunch Pack - (30 วัน)' WHERE slug = 'red-lunch-pack-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Lunch Pack - (7 วัน)' WHERE slug = 'red-lunch-pack-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Lunch Pack - (90 วัน)' WHERE slug = 'red-lunch-pack-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Victory Trophy' WHERE slug = 'red-victory-trophy' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Victory Trophy (1 วัน)' WHERE slug = 'red-victory-trophy-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Victory Trophy (30 วัน)' WHERE slug = 'red-victory-trophy-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Victory Trophy (7 วัน)' WHERE slug = 'red-victory-trophy-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Victory Trophy (90 วัน)' WHERE slug = 'red-victory-trophy-90days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Red Wish Wing (Event, 15 days)' WHERE slug = 'red-wish-wing-event-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Revenant' WHERE slug = 'revenant' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Revenant (1 วัน)' WHERE slug = 'revenant-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Revenant (2 วัน)' WHERE slug = 'revenant-2-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Revenant (30 วัน)' WHERE slug = 'revenant-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Revenant (7 วัน)' WHERE slug = 'revenant-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Revenant (90 วัน)' WHERE slug = 'revenant-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Revenant (อีเวนต์)' WHERE slug = 'revenant-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rojo Puesta de sol' WHERE slug = 'rojo-puesta-de-sol' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rojo Puesta de sol - (1 วัน)' WHERE slug = 'rojo-puesta-de-sol-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rojo Puesta de sol - (30 วัน)' WHERE slug = 'rojo-puesta-de-sol-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rojo Puesta de sol - (7 วัน)' WHERE slug = 'rojo-puesta-de-sol-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rojo Puesta de sol - (90 วัน)' WHERE slug = 'rojo-puesta-de-sol-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกRose (180 วัน)' WHERE slug = 'rose-wing-180-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rucksack' WHERE slug = 'rucksack' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rucksack (15 วัน)' WHERE slug = 'rucksack-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rucksack (7 วัน)' WHERE slug = 'rucksack-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rucksack - (1 วัน)' WHERE slug = 'rucksack-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rucksack - (30 วัน)' WHERE slug = 'rucksack-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rucksack - (90 วัน)' WHERE slug = 'rucksack-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rudolph Doll' WHERE slug = 'rudolph-doll' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rudolph Doll (1 วัน)' WHERE slug = 'rudolph-doll-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rudolph Doll (30 วัน)' WHERE slug = 'rudolph-doll-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rudolph Doll (7 วัน)' WHERE slug = 'rudolph-doll-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Rudolph Doll (90 วัน)' WHERE slug = 'rudolph-doll-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Satchel' WHERE slug = 'satchel' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Satchel (15 วัน)' WHERE slug = 'satchel-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Satchel (7 วัน)' WHERE slug = 'satchel-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Satchel - (1 วัน)' WHERE slug = 'satchel-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Satchel - (30 วัน)' WHERE slug = 'satchel-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Satchel - (90 วัน)' WHERE slug = 'satchel-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Shell of 1000-year-old Tortoise' WHERE slug = 'shell-of-1000-year-old-tortoise' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Shell of Tortoise' WHERE slug = 'shell-of-tortoise' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Shell of Tortoise (15 วัน)' WHERE slug = 'shell-of-tortoise-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Shell of Tortoise (7 วัน)' WHERE slug = 'shell-of-tortoise-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่แห่งPeace' WHERE slug = 'shield-of-peace' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่แห่งPeace (30 วัน)' WHERE slug = 'shield-of-peace-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่แห่งWinner' WHERE slug = 'shield-of-winner' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่แห่งWinner - (1 วัน)' WHERE slug = 'shield-of-winner-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่แห่งWinner - (30 วัน)' WHERE slug = 'shield-of-winner-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่แห่งWinner - (7 วัน)' WHERE slug = 'shield-of-winner-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่แห่งWinner - (90 วัน)' WHERE slug = 'shield-of-winner-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Sign' WHERE slug = 'sign' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Sign (15 วัน)' WHERE slug = 'sign-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Sign (7 วัน)' WHERE slug = 'sign-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Sign - (1 วัน)' WHERE slug = 'sign-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Sign - (30 วัน)' WHERE slug = 'sign-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Sign - (90 วัน)' WHERE slug = 'sign-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silverbell Flower Satchel' WHERE slug = 'silverbell-flower-satchel' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silverbell Satchel - (1 วัน)' WHERE slug = 'silverbell-satchel-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silverbell Satchel - (30 วัน)' WHERE slug = 'silverbell-satchel-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silverbell Satchel - (7 วัน)' WHERE slug = 'silverbell-satchel-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silverbell Satchel - (90 วัน)' WHERE slug = 'silverbell-satchel-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silvery Phoenix Wings - (1 วัน)' WHERE slug = 'silvery-phoenix-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silvery Phoenix Wings - (30 วัน)' WHERE slug = 'silvery-phoenix-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silvery Phoenix Wings - (7 วัน)' WHERE slug = 'silvery-phoenix-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Silvery Phoenix Wings - (90 วัน)' WHERE slug = 'silvery-phoenix-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Spring Fairy' WHERE slug = 'spring-fairy' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Sword of Freedom' WHERE slug = 'sword-of-freedom' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Sword of Freedom (30 วัน)' WHERE slug = 'sword-of-freedom-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Symbol of Pioneer King (15 วัน)' WHERE slug = 'symbol-of-pioneer-king-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Symbol of The Pioneer King (60 วัน)' WHERE slug = 'symbol-of-the-pioneer-king-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Test Back Costume' WHERE slug = 'test-back-costume' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Tortoise Shell - (1 วัน)' WHERE slug = 'tortoise-shell-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Tortoise Shell - (30 วัน)' WHERE slug = 'tortoise-shell-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Tortoise Shell - (90 วัน)' WHERE slug = 'tortoise-shell-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Treasure Chest' WHERE slug = 'treasure-chest' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Treasure Chest (15 วัน)' WHERE slug = 'treasure-chest-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Treasure Chest (7 วัน)' WHERE slug = 'treasure-chest-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Treasure Chest - (30 วัน)' WHERE slug = 'treasure-chest-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Treasure Chest - (90 วัน)' WHERE slug = 'treasure-chest-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Treasure chest - (1 วัน)' WHERE slug = 'treasure-chest-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Violet Chrysalis Wings - (1 วัน)' WHERE slug = 'violet-chrysalis-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Violet Chrysalis Wings - (30 วัน)' WHERE slug = 'violet-chrysalis-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Violet Chrysalis Wings - (7 วัน)' WHERE slug = 'violet-chrysalis-wings-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Violet Chrysalis Wings - (90 วัน)' WHERE slug = 'violet-chrysalis-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Patience' WHERE slug = 'war-gods-patience' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Patience (1 วัน)' WHERE slug = 'war-gods-patience-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Patience (15 วัน)' WHERE slug = 'war-gods-patience-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Patience (30 วัน)' WHERE slug = 'war-gods-patience-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Patience (7 วัน)' WHERE slug = 'war-gods-patience-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Patience (90 วัน)' WHERE slug = 'war-gods-patience-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Smile' WHERE slug = 'war-gods-smile' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Smile (1 วัน)' WHERE slug = 'war-gods-smile-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Smile (15 วัน)' WHERE slug = 'war-gods-smile-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Smile (30 วัน)' WHERE slug = 'war-gods-smile-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Smile (7 วัน)' WHERE slug = 'war-gods-smile-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง War Gods Smile (90 วัน)' WHERE slug = 'war-gods-smile-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Wheel of Destiny' WHERE slug = 'wheel-of-destiny' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Wheel of Destiny (1 วัน)' WHERE slug = 'wheel-of-destiny-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Wheel of Destiny (30 วัน)' WHERE slug = 'wheel-of-destiny-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Wheel of Destiny (7 วัน)' WHERE slug = 'wheel-of-destiny-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Wheel of Destiny (90 วัน)' WHERE slug = 'wheel-of-destiny-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White Angel Wings - (30 วัน)' WHERE slug = 'white-angel-wings-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White Angel Wings - (90 วัน)' WHERE slug = 'white-angel-wings-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White Cristatus' WHERE slug = 'white-cristatus' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White Victory Trophy' WHERE slug = 'white-victory-trophy' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White Victory Trophy (1 วัน)' WHERE slug = 'white-victory-trophy-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White Victory Trophy (30 วัน)' WHERE slug = 'white-victory-trophy-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White Victory Trophy (7 วัน)' WHERE slug = 'white-victory-trophy-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White Victory Trophy (90 วัน)' WHERE slug = 'white-victory-trophy-90days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง White angel Wings - (1 วัน)' WHERE slug = 'white-angel-wings-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง Wing Armor' WHERE slug = 'wing-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBirth (1 วัน)' WHERE slug = 'wing-of-birth-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBirth (15 วัน)' WHERE slug = 'wing-of-birth-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBirth (30 วัน)' WHERE slug = 'wing-of-birth-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBirth (365 วัน)' WHERE slug = 'wing-of-birth-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBirth (7 วัน)' WHERE slug = 'wing-of-birth-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBirth (90 วัน)' WHERE slug = 'wing-of-birth-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBelith' WHERE slug = 'wings-of-belith' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBelith (1 วัน)' WHERE slug = 'wings-of-belith-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBelith (30 วัน)' WHERE slug = 'wings-of-belith-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBelith (7 วัน)' WHERE slug = 'wings-of-belith-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งBelith (90 วัน)' WHERE slug = 'wings-of-belith-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งLucifer' WHERE slug = 'wings-of-lucifer' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งLucifer (1 วัน)' WHERE slug = 'wings-of-lucifer-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งLucifer (15 วัน)' WHERE slug = 'wings-of-lucifer-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งLucifer (30 วัน)' WHERE slug = 'wings-of-lucifer-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งLucifer (365 วัน)' WHERE slug = 'wings-of-lucifer-365-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งLucifer (7 วัน)' WHERE slug = 'wings-of-lucifer-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งLucifer (90 วัน)' WHERE slug = 'wings-of-lucifer-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งNavas' WHERE slug = 'wings-of-navas' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งNavas (1 วัน)' WHERE slug = 'wings-of-navas-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งNavas (15 วัน)' WHERE slug = 'wings-of-navas-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งNavas (30 วัน)' WHERE slug = 'wings-of-navas-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งNavas (7 วัน)' WHERE slug = 'wings-of-navas-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกแห่งNavas (90 วัน)' WHERE slug = 'wings-of-navas-90-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_THI_ItemName01' WHERE slug = 'back-thi-itemname01' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_THI_ItemName03' WHERE slug = 'back-thi-itemname03' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_THI_ItemName04' WHERE slug = 'back-thi-itemname04' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_THI_ItemName05' WHERE slug = 'back-thi-itemname05' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_THI_ItemName06' WHERE slug = 'back-thi-itemname06' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_THI_ItemName07' WHERE slug = 'back-thi-itemname07' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_THI_ItemName08' WHERE slug = 'back-thi-itemname08' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName01' WHERE slug = 'back-twn-itemname01' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName02' WHERE slug = 'back-twn-itemname02' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName04' WHERE slug = 'back-twn-itemname04' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName06' WHERE slug = 'back-twn-itemname06' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName07' WHERE slug = 'back-twn-itemname07' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName08' WHERE slug = 'back-twn-itemname08' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName12' WHERE slug = 'back-twn-itemname12' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName14' WHERE slug = 'back-twn-itemname14' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName15' WHERE slug = 'back-twn-itemname15' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName16' WHERE slug = 'back-twn-itemname16' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName17' WHERE slug = 'back-twn-itemname17' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName18' WHERE slug = 'back-twn-itemname18' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName19' WHERE slug = 'back-twn-itemname19' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName20' WHERE slug = 'back-twn-itemname20' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName21' WHERE slug = 'back-twn-itemname21' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName22' WHERE slug = 'back-twn-itemname22' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName23' WHERE slug = 'back-twn-itemname23' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName24' WHERE slug = 'back-twn-itemname24' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName25' WHERE slug = 'back-twn-itemname25' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName26' WHERE slug = 'back-twn-itemname26' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName27' WHERE slug = 'back-twn-itemname27' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName28' WHERE slug = 'back-twn-itemname28' AND name_th IS NULL;
UPDATE items SET name_th = 'หลัง back_TWN_ItemName29' WHERE slug = 'back-twn-itemname29' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด +10 Iskras Gray (1 วัน)' WHERE slug = '10-iskras-gray-belt-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด +10 Ruincrugers Hard (1 วัน)' WHERE slug = '10-ruincrugers-hard-belt-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด +10 Stars Guardians (1 วัน)' WHERE slug = '10-stars-guardians-belt-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด of Artisan' WHERE slug = 'belt-of-artisan' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Blue Belt of the Beast Legion Commander' WHERE slug = 'blue-belt-of-the-beast-legion-commander' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Brontes Sturdy' WHERE slug = 'brontes-sturdy-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Desapio' WHERE slug = 'desapio-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Giltines Demonic' WHERE slug = 'giltines-demonic-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด High Quality' WHERE slug = 'high-quality-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Iskras Gray' WHERE slug = 'iskras-gray-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Iskras Gray (ภาพลวง)' WHERE slug = 'iskras-gray-belt-illusion' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Laimas Holy' WHERE slug = 'laimas-holy-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Magic' WHERE slug = 'magic-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Magic (อีเวนต์)' WHERE slug = 'magic-belt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Muertuos' WHERE slug = 'muertuos-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Quiritatio Belt of Wisdom' WHERE slug = 'quiritatio-belt-of-wisdom' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Rough' WHERE slug = 'rough-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Ruincrugers Hard' WHERE slug = 'ruincrugers-hard-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Ruincrugers Hard (ภาพลวง)' WHERE slug = 'ruincrugers-hard-belt-illusion' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Stars Guardians' WHERE slug = 'stars-guardians-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Stars Guardians (อีเวนต์)' WHERE slug = 'stars-guardians-belt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Vigilar Tribes' WHERE slug = 'vigilar-tribes-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Vigilar Tribes (อีเวนต์)' WHERE slug = 'vigilar-tribes-belt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Violantes Ashen' WHERE slug = 'violantes-ashen-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Zodiac' WHERE slug = 'zodiac-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด Zodiac (อีเวนต์)' WHERE slug = 'zodiac-belt-event' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] เข็มขัด Iskra' WHERE slug = 'dreaming-iskra-belt' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] เข็มขัด Ruincruger' WHERE slug = 'dreaming-ruincruger-belt' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] เข็มขัด Violantes' WHERE slug = 'dreaming-violantes-belt' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] เข็มขัด Giltines Demonic' WHERE slug = 'event-giltines-demonic-belt' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] เข็มขัด Laimas Holy' WHERE slug = 'event-laimas-holy-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด [Lucid] Iskra' WHERE slug = 'lucid-iskra-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด [Lucid] Ruincruger' WHERE slug = 'lucid-ruincruger-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด [Lucid] Violantes' WHERE slug = 'lucid-violantes-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด [Reverie] Iskra' WHERE slug = 'reverie-iskra-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด [Reverie] Ruincruger' WHERE slug = 'reverie-ruincruger-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'เข็มขัด [Reverie] Violantes' WHERE slug = 'reverie-violantes-belt' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท บลันท์ Axe di Gavi' WHERE slug = 'elite-axe-di-gavi' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท บลันท์ Craighammer' WHERE slug = 'elite-craighammer' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท บลันท์ Dragomahawk' WHERE slug = 'elite-dragomahawk' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท บลันท์ Morgenstern' WHERE slug = 'elite-morgenstern' AND name_th IS NULL;
UPDATE items SET name_th = 'โคบอลท์ บลันท์ Torch' WHERE slug = 'kobolt-torch' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด 2022 Spring Costume - Bedel' WHERE slug = '2022-spring-costume-bedel' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด 2022 Spring Costume - Bedel (อีเวนต์)' WHERE slug = '2022-spring-costume-bedel-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด 2022 Spring Costume - Ivy' WHERE slug = '2022-spring-costume-ivy' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด 2022 Spring Costume - Ivy (อีเวนต์)' WHERE slug = '2022-spring-costume-ivy-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด 2022 Spring Costume - Maria' WHERE slug = '2022-spring-costume-maria' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด 2022 Spring Costume - Maria (อีเวนต์)' WHERE slug = '2022-spring-costume-maria-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด 2022 Spring Costume - Neo' WHERE slug = '2022-spring-costume-neo' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด 2022 Spring Costume - Neo (อีเวนต์)' WHERE slug = '2022-spring-costume-neo-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Albertos Royal Uniform' WHERE slug = 'albertos-royal-uniform' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Alkaik Academic Style' WHERE slug = 'alkaik-academic-style' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Alkaik Academic Style (อีเวนต์)' WHERE slug = 'alkaik-academic-style-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Andres Spade Ensemble' WHERE slug = 'andres-spade-ensemble' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Angies Overalls' WHERE slug = 'angies-overalls' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Anis School Look' WHERE slug = 'anis-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Antaronas Acuity' WHERE slug = 'antaronas-acuity' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Antaronas Hope' WHERE slug = 'antaronas-hope' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Antaronas Insight' WHERE slug = 'antaronas-insight' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Antaronas Loyalty' WHERE slug = 'antaronas-loyalty' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Antaronas Nobility' WHERE slug = 'antaronas-nobility' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Antaronas Passion' WHERE slug = 'antaronas-passion' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Antaronas Smile' WHERE slug = 'antaronas-smile' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Bane Beach Wear' WHERE slug = 'bane-beach-wear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Bear Suit' WHERE slug = 'bear-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Berthe School Look' WHERE slug = 'berthe-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Berthe School Look (อีเวนต์)' WHERE slug = 'berthe-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Black Charmant Costume (Code Name L)' WHERE slug = 'black-charmant-costume-code-name-l' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Black Charmant Costume (L)' WHERE slug = 'black-charmant-costume-l' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Black Scorpion' WHERE slug = 'black-scorpion' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blood Navy / Supreme Commander Cano Brown School Look' WHERE slug = 'blood-navy-supreme-commander-cano-brown-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blood Navy / Supreme Commander Cano Green School Look' WHERE slug = 'blood-navy-supreme-commander-cano-green-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blood Navy/Supreme Commander Cano Brown School-Look (อีเวนต์)' WHERE slug = 'blood-navy-supreme-commander-cano-brown-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blood Navy/Supreme Commander Cano Green School-Look (อีเวนต์)' WHERE slug = 'blood-navy-supreme-commander-cano-green-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Female Elementalist)' WHERE slug = 'blue-serpent-costume-female-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Female Fighter)' WHERE slug = 'blue-serpent-costume-female-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Female Musketeer)' WHERE slug = 'blue-serpent-costume-female-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Female Scout)' WHERE slug = 'blue-serpent-costume-female-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Female Wizard)' WHERE slug = 'blue-serpent-costume-female-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Male Elementalist)' WHERE slug = 'blue-serpent-costume-male-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Male Fighter)' WHERE slug = 'blue-serpent-costume-male-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Male Musketeer)' WHERE slug = 'blue-serpent-costume-male-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Male Scout)' WHERE slug = 'blue-serpent-costume-male-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Costume (Male Wizard)' WHERE slug = 'blue-serpent-costume-male-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Plate Costume (Female Fighter)' WHERE slug = 'blue-serpent-plate-costume-female-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Blue Serpent Plate Costume (Male Fighter)' WHERE slug = 'blue-serpent-plate-costume-male-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Brilliant Dandy Style' WHERE slug = 'brilliant-dandy-style' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Butler of Honor - Black' WHERE slug = 'butler-of-honor-black' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Butler of Honor - Black (อีเวนต์)' WHERE slug = 'butler-of-honor-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Butler of Honor - Pink' WHERE slug = 'butler-of-honor-pink' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Butler of Honor - Pink (อีเวนต์)' WHERE slug = 'butler-of-honor-pink-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Calyce Vampire Look' WHERE slug = 'calyce-vampire-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Cannon Shooter School Look' WHERE slug = 'cannon-shooter-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Capitaine Costume (Male Elementalist)' WHERE slug = 'capitaine-costume-male-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Capitaine Costume (Male Fighter)' WHERE slug = 'capitaine-costume-male-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Capitaine Costume (Male Musketeer)' WHERE slug = 'capitaine-costume-male-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Capitaine Costume (Male Scout)' WHERE slug = 'capitaine-costume-male-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Capitaine Costume (Male Wizard)' WHERE slug = 'capitaine-costume-male-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Capitaine Costume for Male Fighter (อีเวนต์)' WHERE slug = 'capitaine-costume-for-male-fighter-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Cecile School Look' WHERE slug = 'cecile-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ceremony of Blessing - Violet' WHERE slug = 'ceremony-of-blessing-violet' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ceremony of Blessing - Violet (อีเวนต์)' WHERE slug = 'ceremony-of-blessing-violet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ceremony of Blessing - White' WHERE slug = 'ceremony-of-blessing-white' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ceremony of Blessing - White (อีเวนต์)' WHERE slug = 'ceremony-of-blessing-white-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ceremony of Revenge - Black' WHERE slug = 'ceremony-of-revenge-black' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ceremony of Revenge - Black (อีเวนต์)' WHERE slug = 'ceremony-of-revenge-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ceremony of Revenge - White' WHERE slug = 'ceremony-of-revenge-white' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ceremony of Revenge - White (อีเวนต์)' WHERE slug = 'ceremony-of-revenge-white-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Character Basic Clothing' WHERE slug = 'character-basic-clothing' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Charmant Costume (Code Name L)' WHERE slug = 'charmant-costume-code-name-l' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Charmant Costume (Leona)' WHERE slug = 'charmant-costume-leona' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Classe Alta - Dress' WHERE slug = 'classe-alta-dress' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Classe Alta - Dress (อีเวนต์)' WHERE slug = 'classe-alta-dress-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Classe Alta - Jacket' WHERE slug = 'classe-alta-jacket' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Classe Alta - Jacket (อีเวนต์)' WHERE slug = 'classe-alta-jacket-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Classe Alta - Long Coat' WHERE slug = 'classe-alta-long-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Classe Alta - Long Coat (อีเวนต์)' WHERE slug = 'classe-alta-long-coat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Coa Basic Costume - Passion' WHERE slug = 'coa-basic-costume-passion' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Coa Basic Costume - Passion (อีเวนต์)' WHERE slug = 'coa-basic-costume-passion-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Coat of the Queen' WHERE slug = 'coat-of-the-queen' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) AGI +1' WHERE slug = 'costume-test-agi-1' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) AGI +2' WHERE slug = 'costume-test-agi-2' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) DEX +1' WHERE slug = 'costume-test-dex-1' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) DEX +2' WHERE slug = 'costume-test-dex-2' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) HP +1' WHERE slug = 'costume-test-hp-1' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) HP +2' WHERE slug = 'costume-test-hp-2' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) INT +1' WHERE slug = 'costume-test-int-1' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) INT +2' WHERE slug = 'costume-test-int-2' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) STR +1' WHERE slug = 'costume-test-str-1' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด (Test) STR +2' WHERE slug = 'costume-test-str-2' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Cowboy Outfit' WHERE slug = 'cowboy-outfit' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Cowgirl Outfit' WHERE slug = 'cowgirl-outfit' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด De La Flamme Blanche' WHERE slug = 'de-la-flamme-blanche' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Desperado Suit' WHERE slug = 'desperado-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Desperado Suit (30 วัน)' WHERE slug = 'desperado-suit-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Desperados suit (อีเวนต์)' WHERE slug = 'desperados-suit-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Destiny of Alter- Black' WHERE slug = 'destiny-of-alter-black' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Destiny of Alter- Black (อีเวนต์)' WHERE slug = 'destiny-of-alter-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Destiny of Alter- White' WHERE slug = 'destiny-of-alter-white' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Destiny of Alter- White (อีเวนต์)' WHERE slug = 'destiny-of-alter-white-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume (Elementalist)' WHERE slug = 'dignite-costume-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume (Fighter)' WHERE slug = 'dignite-costume-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume (Musketeer)' WHERE slug = 'dignite-costume-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume (Scout)' WHERE slug = 'dignite-costume-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume (Wizard)' WHERE slug = 'dignite-costume-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume for Elementalist (7 วัน)' WHERE slug = 'dignite-costume-for-elementalist-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume for Fighter (7 วัน)' WHERE slug = 'dignite-costume-for-fighter-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume for Musketeer (7 วัน)' WHERE slug = 'dignite-costume-for-musketeer-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume for Scout (7 วัน)' WHERE slug = 'dignite-costume-for-scout-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Dignite Costume for Wizard (7 วัน)' WHERE slug = 'dignite-costume-for-wizard-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Doom Slave Costume 2' WHERE slug = 'doom-slave-costume-2' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Doom of Carvas - Karat' WHERE slug = 'doom-of-carvas-karat' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Doom of Carvas - Karat (อีเวนต์)' WHERE slug = 'doom-of-carvas-karat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Doom of Carvas - Sault' WHERE slug = 'doom-of-carvas-sault' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Doom of Carvas - Sault (อีเวนต์)' WHERE slug = 'doom-of-carvas-sault-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Earth of Brace (Female)' WHERE slug = 'earth-of-brace-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Earth of Brace (Male)' WHERE slug = 'earth-of-brace-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look (Elementalist)' WHERE slug = 'ebony-school-look-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look (Fighter)' WHERE slug = 'ebony-school-look-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look (Musketeer)' WHERE slug = 'ebony-school-look-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look (Scout)' WHERE slug = 'ebony-school-look-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look (Wizard)' WHERE slug = 'ebony-school-look-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look for Elementalist (7 วัน)' WHERE slug = 'ebony-school-look-for-elementalist-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look for Elementalist - Limited Edition' WHERE slug = 'ebony-school-look-for-elementalist-limited-edition' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look for Fighter (7 วัน)' WHERE slug = 'ebony-school-look-for-fighter-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look for Fighter - Limited Edition' WHERE slug = 'ebony-school-look-for-fighter-limited-edition' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look for Musketeer (7 วัน)' WHERE slug = 'ebony-school-look-for-musketeer-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look for Scout (7 วัน)' WHERE slug = 'ebony-school-look-for-scout-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ebony School Look for Wizard (7 วัน)' WHERE slug = 'ebony-school-look-for-wizard-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Elementalist Beachwear' WHERE slug = 'elementalist-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Elementalist Beachwear (15 วัน)' WHERE slug = 'elementalist-beachwear-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Elementalist Beachwear (30 วัน)' WHERE slug = 'elementalist-beachwear-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Elementalist Gold School Look (3 วัน)' WHERE slug = 'elementalist-gold-school-look-3days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Elementalist White School-Look (อีเวนต์)' WHERE slug = 'elementalist-white-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Bane Beach Wear' WHERE slug = 'event-bane-beach-wear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Black Charmant Costume (Code Name L)' WHERE slug = 'event-black-charmant-costume-code-name-l' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Black Charmant Costume (Leona)' WHERE slug = 'event-black-charmant-costume-leona' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Calyce Vampire Look' WHERE slug = 'event-calyce-vampire-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Charmant Costume (Code Name L)' WHERE slug = 'event-charmant-costume-code-name-l' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Charmant Costume (Leona)' WHERE slug = 'event-charmant-costume-leona' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Elementalist' WHERE slug = 'event-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Fighter Beachwear' WHERE slug = 'event-fighter-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Grandies Vampire Look' WHERE slug = 'event-grandies-vampire-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event JD Beach Wear' WHERE slug = 'event-jd-beach-wear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Judith School Look' WHERE slug = 'event-judith-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Leona School Look' WHERE slug = 'event-leona-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Leona Vampire Look' WHERE slug = 'event-leona-vampire-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Musketeer Beachwear' WHERE slug = 'event-musketeer-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Party Dress - Spade' WHERE slug = 'event-party-dress-spade' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Patrick School Look' WHERE slug = 'event-patrick-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Santo de Blanc Costume (Elisa) (อีเวนต์)' WHERE slug = 'event-santo-de-blanc-costume-elisa-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Santo de Blanc Costume (Laura) (อีเวนต์)' WHERE slug = 'event-santo-de-blanc-costume-laura-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Santo de Blanc Costume (Lynn) (อีเวนต์)' WHERE slug = 'event-santo-de-blanc-costume-lynn-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Scout Beachwear' WHERE slug = 'event-scout-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Sirius Beach Wear' WHERE slug = 'event-sirius-beach-wear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Sirius School Look' WHERE slug = 'event-sirius-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Valeria Vendetta Vampire Look' WHERE slug = 'event-valeria-vendetta-vampire-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Van School Look' WHERE slug = 'event-van-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Vincent School Look' WHERE slug = 'event-vincent-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Event Wizard Beachwear' WHERE slug = 'event-wizard-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Fighter Beachwear' WHERE slug = 'fighter-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Fighter Beachwear (15 วัน)' WHERE slug = 'fighter-beachwear-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Fighter Beachwear (30 วัน)' WHERE slug = 'fighter-beachwear-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Fighter Gold School Look (3 วัน)' WHERE slug = 'fighter-gold-school-look-3days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Fighter White School-Look (อีเวนต์)' WHERE slug = 'fighter-white-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Flame of Rage (Female)' WHERE slug = 'flame-of-rage-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Flame of Rage (Male)' WHERE slug = 'flame-of-rage-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look (30 วัน)' WHERE slug = 'gold-school-look-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look (Elementalist)' WHERE slug = 'gold-school-look-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look (Fighter)' WHERE slug = 'gold-school-look-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look (Musketeer)' WHERE slug = 'gold-school-look-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look (Scout)' WHERE slug = 'gold-school-look-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look (Wizard)' WHERE slug = 'gold-school-look-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look for Elementalist (30 วัน)' WHERE slug = 'gold-school-look-for-elementalist-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look for Fighter (30 วัน)' WHERE slug = 'gold-school-look-for-fighter-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look for Scout (30 วัน)' WHERE slug = 'gold-school-look-for-scout-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gold School Look for Wizard (30 วัน)' WHERE slug = 'gold-school-look-for-wizard-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gracielo After School Look' WHERE slug = 'gracielo-after-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gracielo After-school School-Look (อีเวนต์)' WHERE slug = 'gracielo-after-school-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gracielo Green School Look' WHERE slug = 'gracielo-green-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Gracielo Summer School-Look (อีเวนต์)' WHERE slug = 'gracielo-summer-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Grandies Vampire Look' WHERE slug = 'grandies-vampire-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Guardian Coa Basic Costume - Justice' WHERE slug = 'guardian-coa-basic-costume-justice' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Guardian Coa Basic Costume - Justice (อีเวนต์)' WHERE slug = 'guardian-coa-basic-costume-justice-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Guardian of Altare' WHERE slug = 'guardian-of-altare' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Guardian of Altare (อีเวนต์)' WHERE slug = 'guardian-of-altare-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Hanbok Costume for Female Elementalist (30 วัน)' WHERE slug = 'hanbok-costume-for-female-elementalist-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Hanbok Costume for Female Elementalist (7 วัน)' WHERE slug = 'hanbok-costume-for-female-elementalist-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Hanbok Costume for Male Fighter (30 วัน)' WHERE slug = 'hanbok-costume-for-male-fighter-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Hanbok Costume for Male Fighter (7 วัน)' WHERE slug = 'hanbok-costume-for-male-fighter-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Hanbok Costume for Male Musketeer (30 วัน)' WHERE slug = 'hanbok-costume-for-male-musketeer-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Hanbok Costume for Male Musketeer (7 วัน)' WHERE slug = 'hanbok-costume-for-male-musketeer-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Hanbok Costume for Male Scout (30 วัน)' WHERE slug = 'hanbok-costume-for-male-scout-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Hanbok Costume for Male Scout (7 วัน)' WHERE slug = 'hanbok-costume-for-male-scout-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Heart of Imagination - Female' WHERE slug = 'heart-of-imagination-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Heart of Imagination - Male' WHERE slug = 'heart-of-imagination-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Coa' WHERE slug = 'illisia-castle-coa' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Coa (อีเวนต์)' WHERE slug = 'illisia-castle-coa-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Guardian Coa' WHERE slug = 'illisia-castle-guardian-coa' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Guardian Coa (อีเวนต์)' WHERE slug = 'illisia-castle-guardian-coa-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Guardian Ru' WHERE slug = 'illisia-castle-guardian-ru' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Guardian Ru (อีเวนต์)' WHERE slug = 'illisia-castle-guardian-ru-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Kiss' WHERE slug = 'illisia-castle-kiss' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Kiss (อีเวนต์)' WHERE slug = 'illisia-castle-kiss-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Misa' WHERE slug = 'illisia-castle-misa' AND name_th IS NULL;