-- Migration 066: Thai names remaining v2 batch 3/9
-- Generated: 2026-03-16T03:55:14.474Z

UPDATE items SET name_th = 'ชุด Illisia Castle - Misa (อีเวนต์)' WHERE slug = 'illisia-castle-misa-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Ru' WHERE slug = 'illisia-castle-ru' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Illisia Castle - Ru (อีเวนต์)' WHERE slug = 'illisia-castle-ru-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Indigo 9 (อีเวนต์)' WHERE slug = 'indigo-9-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look (30 วัน)' WHERE slug = 'ivory-school-look-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look (Elementalist)' WHERE slug = 'ivory-school-look-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look (Fighter)' WHERE slug = 'ivory-school-look-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look (Musketeer)' WHERE slug = 'ivory-school-look-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look (Scout)' WHERE slug = 'ivory-school-look-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look (Wizard)' WHERE slug = 'ivory-school-look-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look for Fighter (30 วัน)' WHERE slug = 'ivory-school-look-for-fighter-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look for Scout (30 วัน)' WHERE slug = 'ivory-school-look-for-scout-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Ivory School Look for Wizard (30 วัน)' WHERE slug = 'ivory-school-look-for-wizard-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด JD Beach Wear' WHERE slug = 'jd-beach-wear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Jane School Look' WHERE slug = 'jane-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Judith School Look' WHERE slug = 'judith-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Juliana School Look' WHERE slug = 'juliana-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Juliana School Look (อีเวนต์)' WHERE slug = 'juliana-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Justice and Glory - Activity' WHERE slug = 'justice-and-glory-activity' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Justice and Glory - Lachenne' WHERE slug = 'justice-and-glory-lachenne' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Justice and Glory - Liberty' WHERE slug = 'justice-and-glory-liberty' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Justice and Glory - Volonte' WHERE slug = 'justice-and-glory-volonte' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Kiss Basic Costume - Game' WHERE slug = 'kiss-basic-costume-game' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Kiss Basic Costume - Game (อีเวนต์)' WHERE slug = 'kiss-basic-costume-game-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด La Libra Shukre' WHERE slug = 'la-libra-shukre' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด La Virgo Delikato' WHERE slug = 'la-virgo-delikato' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Lady Baselrane - Isaac' WHERE slug = 'lady-baselrane-isaac' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Lady Baselrane - Isaac (อีเวนต์)' WHERE slug = 'lady-baselrane-isaac-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Lady Baselrane - Kael' WHERE slug = 'lady-baselrane-kael' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Lady Baselrane - Kael (อีเวนต์)' WHERE slug = 'lady-baselrane-kael-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Lady Rachel Basic Costume - Relax' WHERE slug = 'lady-rachel-basic-costume-relax' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Lady Rachel Basic Costume - Relax (อีเวนต์)' WHERE slug = 'lady-rachel-basic-costume-relax-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Lady Rachel Basic Costume - Stroll' WHERE slug = 'lady-rachel-basic-costume-stroll' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Lady Rachel Basic Costume - Stroll (อีเวนต์)' WHERE slug = 'lady-rachel-basic-costume-stroll-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Cancer de Sansivillte' WHERE slug = 'le-cancer-de-sansivillte' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Corsaire' WHERE slug = 'le-corsaire' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Corsaire (30 วัน)' WHERE slug = 'le-corsaire-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Sagittaire Optimiste' WHERE slug = 'le-sagittaire-optimiste' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Scarce Costume (Elementalist)' WHERE slug = 'le-scarce-costume-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Scarce Costume (Fighter)' WHERE slug = 'le-scarce-costume-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Scarce Costume (Musketeer)' WHERE slug = 'le-scarce-costume-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Scarce Costume (Scout)' WHERE slug = 'le-scarce-costume-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Scarce Costume (Wizard)' WHERE slug = 'le-scarce-costume-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Scorpio Misteru' WHERE slug = 'le-scorpio-misteru' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Le Taurus due Bobar' WHERE slug = 'le-taurus-due-bobar' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Leather Tunic of the Queen' WHERE slug = 'leather-tunic-of-the-queen' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Leona School Look' WHERE slug = 'leona-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Leona Vampire Look' WHERE slug = 'leona-vampire-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Magic Party Dress (อีเวนต์)' WHERE slug = 'magic-party-dress-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Magic party dress' WHERE slug = 'magic-party-dress' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Maid of Honor - Black' WHERE slug = 'maid-of-honor-black' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Maid of Honor - Black (อีเวนต์)' WHERE slug = 'maid-of-honor-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Maid of Honor - Pink' WHERE slug = 'maid-of-honor-pink' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Maid of Honor - Pink (อีเวนต์)' WHERE slug = 'maid-of-honor-pink-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Mireille School Look' WHERE slug = 'mireille-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Misa Basic Costume - Black' WHERE slug = 'misa-basic-costume-black' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Misa Basic Costume - Black (อีเวนต์)' WHERE slug = 'misa-basic-costume-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Musketeer Beachwear' WHERE slug = 'musketeer-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Musketeer Beachwear (15 วัน)' WHERE slug = 'musketeer-beachwear-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Musketeer Beachwear (30 วัน)' WHERE slug = 'musketeer-beachwear-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Musketeer Gold School Look (3 วัน)' WHERE slug = 'musketeer-gold-school-look-3days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Musketeer White School-Look (อีเวนต์)' WHERE slug = 'musketeer-white-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Mutation Costume (Elementalist)' WHERE slug = 'mutation-costume-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Mutation Costume (Fighter)' WHERE slug = 'mutation-costume-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Mutation Costume (Musketeer)' WHERE slug = 'mutation-costume-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Mutation Costume (Scout)' WHERE slug = 'mutation-costume-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Mutation Costume (Wizard)' WHERE slug = 'mutation-costume-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Naharurosa' WHERE slug = 'naharurosa' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Naharurosa (30 วัน)' WHERE slug = 'naharurosa-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Nena Brown School Look' WHERE slug = 'nena-brown-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Nena Brown School-Look (อีเวนต์)' WHERE slug = 'nena-brown-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Nena Green School Look' WHERE slug = 'nena-green-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Nena Green School-Look (อีเวนต์)' WHERE slug = 'nena-green-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด None' WHERE slug = 'none' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Olga Tribunal' WHERE slug = 'olga-tribunal' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Olympic Sportswear for Elementalist' WHERE slug = 'olympic-sportswear-for-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Olympic Sportswear for Fighter' WHERE slug = 'olympic-sportswear-for-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Olympic Sportswear for Musketeer' WHERE slug = 'olympic-sportswear-for-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Olympic Sportswear for Scout' WHERE slug = 'olympic-sportswear-for-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Olympic Sportswear for Wizard' WHERE slug = 'olympic-sportswear-for-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Elementalist Dress (Female)' WHERE slug = 'original-elementalist-dress-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Elementalist Dress (Male)' WHERE slug = 'original-elementalist-dress-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Fighter Jacket (Female)' WHERE slug = 'original-fighter-jacket-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Fighter Jacket (Male)' WHERE slug = 'original-fighter-jacket-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Musketeer Uniform (Female)' WHERE slug = 'original-musketeer-uniform-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Musketeer Uniform (Male)' WHERE slug = 'original-musketeer-uniform-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Scout Suit (Female)' WHERE slug = 'original-scout-suit-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Scout Suit (Male)' WHERE slug = 'original-scout-suit-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Wizard Coat (Female)' WHERE slug = 'original-wizard-coat-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Original Wizard Coat (Male)' WHERE slug = 'original-wizard-coat-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Overalls of Angie (30 วัน)' WHERE slug = 'overalls-of-angie-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - 100 Points' WHERE slug = 'party-dress-100-points' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Amusement Park' WHERE slug = 'party-dress-amusement-park' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Amusement Park (อีเวนต์)' WHERE slug = 'party-dress-amusement-park-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Birthday' WHERE slug = 'party-dress-birthday' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Birthday (อีเวนต์)' WHERE slug = 'party-dress-birthday-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Brother' WHERE slug = 'party-dress-brother' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Fire Ball (อีเวนต์)' WHERE slug = 'party-dress-fire-ball-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Fireball' WHERE slug = 'party-dress-fireball' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - First Step' WHERE slug = 'party-dress-first-step' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Friend' WHERE slug = 'party-dress-friend' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Friend (อีเวนต์)' WHERE slug = 'party-dress-friend-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Frist step (อีเวนต์)' WHERE slug = 'party-dress-frist-step-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Gurgle (อีเวนต์)' WHERE slug = 'party-dress-gurgle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Night (อีเวนต์)' WHERE slug = 'party-dress-night-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Spade' WHERE slug = 'party-dress-spade' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Speak (อีเวนต์)' WHERE slug = 'party-dress-speak-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Speech' WHERE slug = 'party-dress-speech' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - Zoo' WHERE slug = 'party-dress-zoo' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party Dress - night' WHERE slug = 'party-dress-night' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Party dress - Toddling (อีเวนต์)' WHERE slug = 'party-dress-toddling-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Patrick School Look' WHERE slug = 'patrick-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Princess Sakura Basic Costume - Festival' WHERE slug = 'princess-sakura-basic-costume-festival' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Princess Sakura Basic Costume - Festival (อีเวนต์)' WHERE slug = 'princess-sakura-basic-costume-festival-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Rosa Matrimonio (30 วัน)' WHERE slug = 'rosa-matrimonio-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Rose Blanche Costume - Dawn' WHERE slug = 'rose-blanche-costume-dawn' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Rose Blanche Costume - Dawn (อีเวนต์)' WHERE slug = 'rose-blanche-costume-dawn-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Rose Blanche Costume - Soul' WHERE slug = 'rose-blanche-costume-soul' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Rose Blanche Costume - Twilight (อีเวนต์)' WHERE slug = 'rose-blanche-costume-twilight-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Rose Blanche Costume- Soul (อีเวนต์)' WHERE slug = 'rose-blanche-costume-soul-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Rose Blanche Costume- Twilight' WHERE slug = 'rose-blanche-costume-twilight' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Royal Uniform of Alberto (30 วัน)' WHERE slug = 'royal-uniform-of-alberto-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Saint Allude Costume- Black (อีเวนต์)' WHERE slug = 'saint-allude-costume-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Saint Allude Costume- Pink (อีเวนต์)' WHERE slug = 'saint-allude-costume-pink-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Saint Alude Costume- Black' WHERE slug = 'saint-alude-costume-black' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Saint Alude Costume- Pink' WHERE slug = 'saint-alude-costume-pink' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Sakura Basic Costume - Sun' WHERE slug = 'sakura-basic-costume-sun' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Sakura Basic Costume - Sun (อีเวนต์)' WHERE slug = 'sakura-basic-costume-sun-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Sakura Dress' WHERE slug = 'sakura-dress' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Samurai Armor (Black)' WHERE slug = 'samurai-armor-black' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Samurai Armor (Blue)' WHERE slug = 'samurai-armor-blue' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Samurai Armor (Red)' WHERE slug = 'samurai-armor-red' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Adelina)' WHERE slug = 'santa-costume-adelina' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Asoka/Mifuyu)' WHERE slug = 'santa-costume-asoka-mifuyu' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Bernelli)' WHERE slug = 'santa-costume-bernelli' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Calyce)' WHERE slug = 'santa-costume-calyce' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Elementalist)' WHERE slug = 'santa-costume-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Emilia)' WHERE slug = 'santa-costume-emilia' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Fighter)' WHERE slug = 'santa-costume-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Musketeer)' WHERE slug = 'santa-costume-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Scout)' WHERE slug = 'santa-costume-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Valeria)' WHERE slug = 'santa-costume-valeria' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume (Wizard)' WHERE slug = 'santa-costume-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume for Elementalist (30 วัน)' WHERE slug = 'santa-costume-for-elementalist-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume for Fighter (30 วัน)' WHERE slug = 'santa-costume-for-fighter-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume for Scout (30 วัน)' WHERE slug = 'santa-costume-for-scout-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santa Costume for Wizard (30 วัน)' WHERE slug = 'santa-costume-for-wizard-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume (Anis)' WHERE slug = 'santo-de-blanc-costume-anis' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume (Battlefield Claude) (อีเวนต์)' WHERE slug = 'santo-de-blanc-costume-battlefield-claude-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume (Caisse) (อีเวนต์)' WHERE slug = 'santo-de-blanc-costume-caisse-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume (Elisa)' WHERE slug = 'santo-de-blanc-costume-elisa' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume (Ion) (อีเวนต์)' WHERE slug = 'santo-de-blanc-costume-ion-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume (Laura)' WHERE slug = 'santo-de-blanc-costume-laura' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume (Levine) (อีเวนต์)' WHERE slug = 'santo-de-blanc-costume-levine-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume (Lynn)' WHERE slug = 'santo-de-blanc-costume-lynn' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Battlefield Claude)' WHERE slug = 'santo-de-blanc-costume-battlefield-claude' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Caisse)' WHERE slug = 'santo-de-blanc-costume-caisse' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Elementalist)' WHERE slug = 'santo-de-blanc-costume-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Fighter)' WHERE slug = 'santo-de-blanc-costume-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Ion)' WHERE slug = 'santo-de-blanc-costume-ion' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Levine)' WHERE slug = 'santo-de-blanc-costume-levine' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Musketeer)' WHERE slug = 'santo-de-blanc-costume-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Scout)' WHERE slug = 'santo-de-blanc-costume-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo De Blanc Costume(Wizard)' WHERE slug = 'santo-de-blanc-costume-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santo de Blanc Costume (Anis) (อีเวนต์)' WHERE slug = 'santo-de-blanc-costume-anis-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Santuario Metal Armor Costume(Fighter)' WHERE slug = 'santuario-metal-armor-costume-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Scout Beachwear' WHERE slug = 'scout-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Scout Beachwear (15 วัน)' WHERE slug = 'scout-beachwear-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Scout Beachwear (30 วัน)' WHERE slug = 'scout-beachwear-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Scout Gold School Look (3 วัน)' WHERE slug = 'scout-gold-school-look-3days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Scout Special Dignit Costume - Female' WHERE slug = 'scout-special-dignit-costume-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Scout White School-Look (อีเวนต์)' WHERE slug = 'scout-white-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Sir Lyndons Coat' WHERE slug = 'sir-lyndons-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Sirius Beach Wear' WHERE slug = 'sirius-beach-wear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Sirius School Look' WHERE slug = 'sirius-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Slayer of Nightmare' WHERE slug = 'slayer-of-nightmare' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Slayer of Nightmare (อีเวนต์)' WHERE slug = 'slayer-of-nightmare-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Spade Ensemble of Andre (30 วัน)' WHERE slug = 'spade-ensemble-of-andre-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Spade Ensemble of Andre (อีเวนต์)' WHERE slug = 'spade-ensemble-of-andre-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Special Dignite Costume - Female' WHERE slug = 'special-dignite-costume-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Standard Costume - Broken' WHERE slug = 'standard-costume-broken' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Doom Slave)' WHERE slug = 'strata-devil-costume-doom-slave' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Doom Slave) (อีเวนต์)' WHERE slug = 'strata-devil-costume-doom-slave-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Guardian Lu)' WHERE slug = 'strata-devil-costume-guardian-lu' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Guardian Lu) (อีเวนต์)' WHERE slug = 'strata-devil-costume-guardian-lu-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Joshua, Queen Cerny Joshua)' WHERE slug = 'strata-devil-costume-joshua-queen-cerny-joshua' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Joshua, Queen Cerny Joshua) (อีเวนต์)' WHERE slug = 'strata-devil-costume-joshua-queen-cerny-joshua-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Lu)' WHERE slug = 'strata-devil-costume-lu' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Lu) (อีเวนต์)' WHERE slug = 'strata-devil-costume-lu-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Moon)' WHERE slug = 'strata-devil-costume-moon' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Moon) (อีเวนต์)' WHERE slug = 'strata-devil-costume-moon-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Sharon)' WHERE slug = 'strata-devil-costume-sharon' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Sharon) (อีเวนต์)' WHERE slug = 'strata-devil-costume-sharon-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Sirius)' WHERE slug = 'strata-devil-costume-sirius' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Sirius) (อีเวนต์)' WHERE slug = 'strata-devil-costume-sirius-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Soho, Soho the Wind)' WHERE slug = 'strata-devil-costume-soho-soho-the-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Strata Devil Costume (Soho, Soho the Wind) (อีเวนต์)' WHERE slug = 'strata-devil-costume-soho-soho-the-wind-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Sugarplum Tutu' WHERE slug = 'sugarplum-tutu' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Sugarplum Tutu (30 วัน)' WHERE slug = 'sugarplum-tutu-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Baselrane - Black' WHERE slug = 'teacher-baselrane-black' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Baselrane - Black (อีเวนต์)' WHERE slug = 'teacher-baselrane-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Baselrane - Pink' WHERE slug = 'teacher-baselrane-pink' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Baselrane - Pink (อีเวนต์)' WHERE slug = 'teacher-baselrane-pink-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Illisia - Blue' WHERE slug = 'teacher-illisia-blue' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Illisia - Blue (อีเวนต์)' WHERE slug = 'teacher-illisia-blue-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Illisia - Pink' WHERE slug = 'teacher-illisia-pink' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Illisia - Pink (อีเวนต์)' WHERE slug = 'teacher-illisia-pink-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Pey - Blue (อีเวนต์)' WHERE slug = 'teacher-pey-blue-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Pey - Red (อีเวนต์)' WHERE slug = 'teacher-pey-red-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Pey- Blue' WHERE slug = 'teacher-pey-blue' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Teacher Pey- Red' WHERE slug = 'teacher-pey-red' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Tempest of Chaos (Female)' WHERE slug = 'tempest-of-chaos-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Tempest of Chaos (Male)' WHERE slug = 'tempest-of-chaos-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Test Costume SEN+1' WHERE slug = 'test-costume-sen-1' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Test Costume SEN+2' WHERE slug = 'test-costume-sen-2' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด The Scarlet Belle' WHERE slug = 'the-scarlet-belle' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด The Scarlet Belle (30 วัน)' WHERE slug = 'the-scarlet-belle-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Traditional Costume (Male Fighter)' WHERE slug = 'traditional-costume-male-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Traditional Costume (Male Musketeer)' WHERE slug = 'traditional-costume-male-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Traditional Costume (Male Scout)' WHERE slug = 'traditional-costume-male-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Valeria Vendetta Vampire Look' WHERE slug = 'valeria-vendetta-vampire-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Van School Look' WHERE slug = 'van-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Viator Shaman' WHERE slug = 'viator-shaman' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Vincent School Look' WHERE slug = 'vincent-school-look' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Water of Abyss (Female)' WHERE slug = 'water-of-abyss-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Water of Abyss (Male)' WHERE slug = 'water-of-abyss-male' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Water of Abyss (Male) (อีเวนต์)' WHERE slug = 'water-of-abyss-male-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด White Down Jacket (อีเวนต์)' WHERE slug = 'white-down-jacket-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด White Vent Costume (Sniper)' WHERE slug = 'white-vent-costume-sniper' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Witness of History' WHERE slug = 'witness-of-history' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Witness of history (อีเวนต์)' WHERE slug = 'witness-of-history-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Wizard Beachwear' WHERE slug = 'wizard-beachwear' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Wizard Beachwear (15 วัน)' WHERE slug = 'wizard-beachwear-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Wizard Beachwear (30 วัน)' WHERE slug = 'wizard-beachwear-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Wizard Gold School Look (3 วัน)' WHERE slug = 'wizard-gold-school-look-3days' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Wizard Special Dignite Costume - Female' WHERE slug = 'wizard-special-dignite-costume-female' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Wizard White School-Look (อีเวนต์)' WHERE slug = 'wizard-white-school-look-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ชุด Yukata de Losage' WHERE slug = 'yukata-de-losage' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Agate of Blast' WHERE slug = 'agate-of-blast' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน of Chariot' WHERE slug = 'cannon-of-chariot' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Conqueror' WHERE slug = 'conqueror-cannon' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Crowood Recker' WHERE slug = 'crowood-recker' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน El Carro' WHERE slug = 'el-carro' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท แคนนอน El Carro' WHERE slug = 'elite-el-carro' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท แคนนอน Peacemaker' WHERE slug = 'elite-peacemaker' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท แคนนอน Relief of Deneb' WHERE slug = 'elite-relief-of-deneb' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท แคนนอน Relief of Deneb (อีเวนต์)' WHERE slug = 'elite-relief-of-deneb-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Florence en Lamina' WHERE slug = 'florence-en-lamina' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Incomplete Stellas Enthusiasm' WHERE slug = 'incomplete-stellas-enthusiasm' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Relief of Deneb' WHERE slug = 'relief-of-deneb' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Relief of Deneb (อีเวนต์)' WHERE slug = 'relief-of-deneb-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Stellas Enthusiasm' WHERE slug = 'stellas-enthusiasm' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน Stellas Enthusiasm (อีเวนต์)' WHERE slug = 'stellas-enthusiasm-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แคนนอน The Canon of Detractor' WHERE slug = 'the-canon-of-detractor' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท A Maid Uniform' WHERE slug = 'a-maid-uniform' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Albaes' WHERE slug = 'albaes' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Amoladera Justocorps' WHERE slug = 'amoladera-justocorps' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Amoladera Long' WHERE slug = 'amoladera-long-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Amoladera Redingote' WHERE slug = 'amoladera-redingote' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Armure Diabolique -' WHERE slug = 'armure-diabolique-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Armure Diabolique - (อีเวนต์)' WHERE slug = 'armure-diabolique-coat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Armure Diabolique of Ziz -' WHERE slug = 'armure-diabolique-of-ziz-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Armure Diabolique of Ziz - (อีเวนต์)' WHERE slug = 'armure-diabolique-of-ziz-coat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Astartes' WHERE slug = 'astartes-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Blue Serpent' WHERE slug = 'blue-serpent-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Blue Serpent Coat (No Use)' WHERE slug = 'blue-serpent-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Cinderella Coat (60 days)(No Use)' WHERE slug = 'cinderella-coat-60-days-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Clara Mago' WHERE slug = 'clara-mago' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Clara Mago of Cinderella' WHERE slug = 'clara-mago-of-cinderella' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Clara Mago of Cinderella (60 วัน)' WHERE slug = 'clara-mago-of-cinderella-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท' WHERE slug = 'coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท of Expert' WHERE slug = 'coat-of-expert' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท of the Queen' WHERE slug = 'coat-of-the-queen' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Consolidar Justocorps' WHERE slug = 'consolidar-justocorps' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Consolidar Long' WHERE slug = 'consolidar-long-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Consolidar Redingote' WHERE slug = 'consolidar-redingote' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Corsair Rosso' WHERE slug = 'corsair-rosso' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Corsair Rosso of Cinderella' WHERE slug = 'corsair-rosso-of-cinderella' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Corsair Rosso of Cinderella (60 วัน)' WHERE slug = 'corsair-rosso-of-cinderella-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Crescemento' WHERE slug = 'crescemento-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ โค้ท Le Blanc' WHERE slug = 'divine-le-blanc-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'มังกร โค้ท' WHERE slug = 'dragon-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Albaes' WHERE slug = 'elite-albaes' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Calienalbino' WHERE slug = 'elite-calienalbino' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Camaryllis' WHERE slug = 'elite-camaryllis' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท' WHERE slug = 'elite-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Deinclian' WHERE slug = 'elite-deinclian' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Dignite Coat (No Use)' WHERE slug = 'elite-dignite-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Graciegote' WHERE slug = 'elite-graciegote' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Justocorps' WHERE slug = 'elite-justocorps' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Le Noir Coat (No Use)' WHERE slug = 'elite-le-noir-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Le Scarce Coat (No Use)' WHERE slug = 'elite-le-scarce-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Pendera Jacket' WHERE slug = 'elite-pendera-jacket' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Redingote' WHERE slug = 'elite-redingote' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Striform' WHERE slug = 'elite-striform' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โค้ท Variltorta' WHERE slug = 'elite-variltorta' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Enhanced Dragon' WHERE slug = 'enhanced-dragon-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Event Elite Le Blanc Coat (No Use)' WHERE slug = 'event-elite-le-blanc-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Event Elite Le Noir Coat (No Use)' WHERE slug = 'event-elite-le-noir-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Event Greek Croma Coat (No Use)' WHERE slug = 'event-greek-croma-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง โค้ท (No Use)' WHERE slug = 'experimental-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Frontier Croma(Coat)' WHERE slug = 'frontier-croma-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Graciegote' WHERE slug = 'graciegote' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Greek Croma (No Use)' WHERE slug = 'greek-croma-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Greek Croma' WHERE slug = 'greek-croma-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Greek Croma (อีเวนต์)' WHERE slug = 'greek-croma-coat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Justocorps' WHERE slug = 'justocorps' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Blanc' WHERE slug = 'le-blanc-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Blanc Coat (No Use)' WHERE slug = 'le-blanc-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Blanc of Cinderella' WHERE slug = 'le-blanc-of-cinderella-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Blanc of Cinderella Coat (No Use)' WHERE slug = 'le-blanc-of-cinderella-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Blanc of Cinderella for (60 วัน)' WHERE slug = 'le-blanc-of-cinderella-for-coat-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Noir' WHERE slug = 'le-noir-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Noir Coat (No Use)' WHERE slug = 'le-noir-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Pouvoir' WHERE slug = 'le-pouvoir-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Pouvoir Coat (Not Use)' WHERE slug = 'le-pouvoir-coat-not-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Scarce' WHERE slug = 'le-scarce-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Le Scarce Coat (No Use)' WHERE slug = 'le-scarce-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Legacy - Royal Coat Armor' WHERE slug = 'legacy-royal-coat-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Long' WHERE slug = 'long-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Nero Croma' WHERE slug = 'nero-croma-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Nero Croma Coat (No Use)' WHERE slug = 'nero-croma-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Novice' WHERE slug = 'novice-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ โค้ท Noir' WHERE slug = 'ogre-noir-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ โค้ท Noir Coat Coat (No Use)' WHERE slug = 'ogre-noir-coat-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Old Elite Le Noir' WHERE slug = 'old-elite-le-noir-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Old Greek Croma' WHERE slug = 'old-greek-croma-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Old Santo De Blanc' WHERE slug = 'old-santo-de-blanc-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Old Strata Devil' WHERE slug = 'old-strata-devil-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Pendera Jacket' WHERE slug = 'pendera-jacket' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Pioneer' WHERE slug = 'pioneer-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Pioneer Combat' WHERE slug = 'pioneer-combat-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Pioneer Mystic' WHERE slug = 'pioneer-mystic-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Pioneer Old' WHERE slug = 'pioneer-old-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Pioneer Practice' WHERE slug = 'pioneer-practice-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Pioneer Thick' WHERE slug = 'pioneer-thick-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Red Serpent' WHERE slug = 'red-serpent-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Red Serpent Coat (No Use)' WHERE slug = 'red-serpent-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Redingote' WHERE slug = 'redingote' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Rich Lord' WHERE slug = 'rich-lord-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'ราชวงศ์ โค้ท' WHERE slug = 'royal-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Santo De Blanc' WHERE slug = 'santo-de-blanc-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Santo De Blanc (อีเวนต์)' WHERE slug = 'santo-de-blanc-coat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Santo De Blanc Coat (No Use)' WHERE slug = 'santo-de-blanc-coat-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Santo De Blanc Coat (No Use) (อีเวนต์)' WHERE slug = 'santo-de-blanc-coat-no-use-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Sky Demons Armure Diabolique -' WHERE slug = 'sky-demons-armure-diabolique-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Sky Demons Armure Diabolique - (อีเวนต์)' WHERE slug = 'sky-demons-armure-diabolique-coat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล โค้ท (No Use)' WHERE slug = 'strata-devil-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล โค้ท (No Use) (อีเวนต์)' WHERE slug = 'strata-devil-coat-no-use-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Striform' WHERE slug = 'striform' AND name_th IS NULL;
UPDATE items SET name_th = 'โค้ท Supreme Dignite' WHERE slug = 'supreme-dignite-coat' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ราชวงศ์ โค้ท' WHERE slug = 'event-royal-coat' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า คอนโทรลเลอร์' WHERE slug = 'abyss-arma-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า คอนโทรลเลอร์ (อีเวนต์)' WHERE slug = 'abyss-arma-controller-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ of Contract (7 วัน)' WHERE slug = 'controller-of-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า คอนโทรลเลอร์' WHERE slug = 'deus-machina-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า คอนโทรลเลอร์ (อีเวนต์)' WHERE slug = 'deus-machina-controller-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ Elegant' WHERE slug = 'elegant-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง คอนโทรลเลอร์' WHERE slug = 'elite-experimental-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'เอเน็กซ์ อีเธอเรียล คอนโทรลเลอร์' WHERE slug = 'enex-ethereal-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง คอนโทรลเลอร์' WHERE slug = 'experimental-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ Heavenly Marionette' WHERE slug = 'heavenly-marionette' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ Heavenly Marionette (อีเวนต์)' WHERE slug = 'heavenly-marionette-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ High Quality Silver' WHERE slug = 'high-quality-silver-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ Incomplete Stellas Nobility' WHERE slug = 'incomplete-stellas-nobility' AND name_th IS NULL;
UPDATE items SET name_th = 'ลีเจียน คอนโทรลเลอร์' WHERE slug = 'legion-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ Platinum' WHERE slug = 'platinum-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'พรอสเป คอนโทรลเลอร์' WHERE slug = 'prospe-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'เวสปาโนลาขัดเงา คอนโทรลเลอร์' WHERE slug = 'refined-vespanola-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'เงิน คอนโทรลเลอร์ Controller: Attack' WHERE slug = 'silver-controller-attack' AND name_th IS NULL;
UPDATE items SET name_th = 'เงิน คอนโทรลเลอร์ Controller: Defense' WHERE slug = 'silver-controller-defense' AND name_th IS NULL;
UPDATE items SET name_th = 'เงิน คอนโทรลเลอร์ Light' WHERE slug = 'silver-light-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ Stellas Nobility' WHERE slug = 'stellas-nobility' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ Stellas Nobility (อีเวนต์)' WHERE slug = 'stellas-nobility-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล คอนโทรลเลอร์' WHERE slug = 'strata-devil-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล คอนโทรลเลอร์ (อีเวนต์)' WHERE slug = 'strata-devil-controller-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คำสั่งทรราช คอนโทรลเลอร์' WHERE slug = 'tyrants-order-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'คำสั่งทรราช คอนโทรลเลอร์ (อีเวนต์)' WHERE slug = 'tyrants-order-controller-event' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน คอนโทรลเลอร์' WHERE slug = 'valeron-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน คอนโทรลเลอร์ (อีเวนต์)' WHERE slug = 'valeron-controller-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา คอนโทรลเลอร์' WHERE slug = 'vespanola-pioneer-support-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'คอนโทรลเลอร์ Wooden' WHERE slug = 'wooden-controller' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] เอเน็กซ์ อีเธอเรียล คอนโทรลเลอร์' WHERE slug = 'event-enex-ethereal-controller' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ Accuracy of Pegasus' WHERE slug = 'accuracy-of-pegasus' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ Accuracy of Pegasus (อีเวนต์)' WHERE slug = 'accuracy-of-pegasus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ of Ashley' WHERE slug = 'crossbow-of-ashley' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ of Temperance' WHERE slug = 'crossbow-of-temperance' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ El Loco' WHERE slug = 'el-loco' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โครสโบว์ Accuracy of Pegasus' WHERE slug = 'elite-accuracy-of-pegasus' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โครสโบว์ Accuracy of Pegasus (อีเวนต์)' WHERE slug = 'elite-accuracy-of-pegasus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โครสโบว์' WHERE slug = 'elite-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โครสโบว์ El Loco' WHERE slug = 'elite-el-loco' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท มูเอร์ทัวร์ส โครสโบว์ CrossBow' WHERE slug = 'elite-muertuors-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'อีเวนต์ อีลิท มูเอร์ทัวร์ส โครสโบว์ CrossBow' WHERE slug = 'event-elite-muertuors-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'อีเวนต์ มูเอร์ทัวร์ส โครสโบว์ CrossBow' WHERE slug = 'event-muertuors-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ Incomplete Ordens Dedication' WHERE slug = 'incomplete-ordens-dedication' AND name_th IS NULL;
UPDATE items SET name_th = 'มูเอร์ทัวร์ส โครสโบว์ CrossBow' WHERE slug = 'muertuors-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ Opal of Precision' WHERE slug = 'opal-of-precision' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ Ordens Dedication' WHERE slug = 'ordens-dedication' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ Ordens Dedication (อีเวนต์)' WHERE slug = 'ordens-dedication-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ Screw Bolt' WHERE slug = 'screw-bolt-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ The Crossbow of Apostate' WHERE slug = 'the-crossbow-of-apostate' AND name_th IS NULL;
UPDATE items SET name_th = 'โครสโบว์ Yrlight' WHERE slug = 'yrlight-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ Chloes Riddle' WHERE slug = 'chloes-riddle' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ Chloes Riddle (อีเวนต์)' WHERE slug = 'chloes-riddle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์' WHERE slug = 'cube' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ (อีเวนต์)' WHERE slug = 'cube-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ of Gridley' WHERE slug = 'cube-of-gridley' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ ILE-525' WHERE slug = 'ile-525-cube' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ ILE-525 (อีเวนต์)' WHERE slug = 'ile-525-cube-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ Incomplete Chloes Riddle' WHERE slug = 'incomplete-chloes-riddle' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ Masterpiece' WHERE slug = 'masterpiece-cube' AND name_th IS NULL;
UPDATE items SET name_th = 'คิวบ์ Masterpiece (อีเวนต์)' WHERE slug = 'masterpiece-cube-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ดาก้า Duel Structure' WHERE slug = 'duel-structure-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ดาก้า Baselard' WHERE slug = 'elite-baselard' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ดาก้า Cuspid of Steel' WHERE slug = 'elite-cuspid-of-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ดาก้า Mystic Knife' WHERE slug = 'elite-mystic-knife' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ดาก้า Pugio' WHERE slug = 'elite-pugio' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ดาก้า Small Knife' WHERE slug = 'elite-small-knife' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ดาก้า Xiphos' WHERE slug = 'elite-xiphos' AND name_th IS NULL;
UPDATE items SET name_th = 'ดาก้า Peorthlight' WHERE slug = 'peorthlight-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู +10 Stars Messengers (1 วัน)' WHERE slug = '10-stars-messengers-earring-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Beliths Corrupt' WHERE slug = 'beliths-corrupt-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Charisma of Reydeavaricia' WHERE slug = 'charisma-of-reydeavaricia' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Charisma of Reydeavaricia (อีเวนต์)' WHERE slug = 'charisma-of-reydeavaricia-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Christinas Reinforced' WHERE slug = 'christinas-reinforced-earrings' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Desapio' WHERE slug = 'desapio-earrings' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู of Artisan' WHERE slug = 'earring-of-artisan' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Charisma of Reydeavaricia' WHERE slug = 'enhanced-charisma-of-reydeavaricia' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Charisma of Reydeavaricia (อีเวนต์)' WHERE slug = 'enhanced-charisma-of-reydeavaricia-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Hope of Argus' WHERE slug = 'enhanced-hope-of-argus' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Hope of Argus (อีเวนต์)' WHERE slug = 'enhanced-hope-of-argus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Revelation of Abyss' WHERE slug = 'enhanced-revelation-of-abyss' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Revelation of Abyss (อีเวนต์)' WHERE slug = 'enhanced-revelation-of-abyss-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Shadow of Abyss' WHERE slug = 'enhanced-shadow-of-abyss' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Shadow of Abyss (อีเวนต์)' WHERE slug = 'enhanced-shadow-of-abyss-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Will of Argus' WHERE slug = 'enhanced-will-of-argus' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Enhanced Will of Argus (อีเวนต์)' WHERE slug = 'enhanced-will-of-argus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง ต่างหู Magic' WHERE slug = 'experimental-magic-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Giltines Demonic' WHERE slug = 'giltines-demonic-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ทอง ต่างหู' WHERE slug = 'golden-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Hamaans Ancient Star (อีเวนต์)' WHERE slug = 'hamaans-ancient-star-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู High Quality' WHERE slug = 'high-quality-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Hope of Argus' WHERE slug = 'hope-of-argus' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Hope of Argus (อีเวนต์)' WHERE slug = 'hope-of-argus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Laimas Holy' WHERE slug = 'laimas-holy-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Magic (อีเวนต์)' WHERE slug = 'magic-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Magical' WHERE slug = 'magical-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Muertuos' WHERE slug = 'muertuos-earrings' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Navas Abyssal' WHERE slug = 'navas-abyssal-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Quiritatio Earrings of Judgement' WHERE slug = 'quiritatio-earrings-of-judgement' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Revelation of Abyss' WHERE slug = 'revelation-of-abyss' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Revelation of Abyss (อีเวนต์)' WHERE slug = 'revelation-of-abyss-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เงา ต่างหู of Abyss' WHERE slug = 'shadow-of-abyss' AND name_th IS NULL;
UPDATE items SET name_th = 'เงา ต่างหู of Abyss (อีเวนต์)' WHERE slug = 'shadow-of-abyss-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เงิน ต่างหู' WHERE slug = 'silver-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Stars Messengers' WHERE slug = 'stars-messengers-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Stars Messengers (อีเวนต์)' WHERE slug = 'stars-messengers-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Vigilar Tribes' WHERE slug = 'vigilar-tribes-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Vigilar Tribes (อีเวนต์)' WHERE slug = 'vigilar-tribes-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Will of Argus' WHERE slug = 'will-of-argus' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Will of Argus (อีเวนต์)' WHERE slug = 'will-of-argus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Zodiac' WHERE slug = 'zodiac-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู Zodiac (อีเวนต์)' WHERE slug = 'zodiac-earring-event' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] ต่างหู Beliths' WHERE slug = 'dreaming-beliths-earring' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] ต่างหู Navas' WHERE slug = 'dreaming-navas-earring' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ต่างหู Giltines Demonic' WHERE slug = 'event-giltines-demonic-earring' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ต่างหู Laimas Holy' WHERE slug = 'event-laimas-holy-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู [Lucid] Beliths' WHERE slug = 'lucid-beliths-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู [Lucid] Navas' WHERE slug = 'lucid-navas-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู [Reverie] Beliths' WHERE slug = 'reverie-beliths-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'ต่างหู [Reverie] Navas' WHERE slug = 'reverie-navas-earring' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Amys Spectacles' WHERE slug = 'amys-spectacles' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Aurelion Sereni' WHERE slug = 'aurelion-sereni' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Bandana' WHERE slug = 'bandana' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Bandana (30 วัน)' WHERE slug = 'bandana-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Female (30 วัน)' WHERE slug = 'beach-glasses-for-female-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Female Elementalist' WHERE slug = 'beach-glasses-for-female-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Female Fighter' WHERE slug = 'beach-glasses-for-female-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Female Musketeer' WHERE slug = 'beach-glasses-for-female-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Female Scout' WHERE slug = 'beach-glasses-for-female-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Female Wizard' WHERE slug = 'beach-glasses-for-female-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Male (30 วัน)' WHERE slug = 'beach-glasses-for-male-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Male Elementalist' WHERE slug = 'beach-glasses-for-male-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Male Fighter' WHERE slug = 'beach-glasses-for-male-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Male Musketeer' WHERE slug = 'beach-glasses-for-male-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Male Scout' WHERE slug = 'beach-glasses-for-male-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beach Glasses for Male Wizard' WHERE slug = 'beach-glasses-for-male-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Beliths Mask for Events' WHERE slug = 'beliths-mask-for-events' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Bernelli Beach Sunglass' WHERE slug = 'bernelli-beach-sunglass' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Biancas Spectacles' WHERE slug = 'biancas-spectacles' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Blood Navy/Supreme Commander Cano School-Look Glass (อีเวนต์)' WHERE slug = 'blood-navy-supreme-commander-cano-school-look-glass-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Capitaine Monocle for Wizard' WHERE slug = 'capitaine-monocle-for-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Crystal Rudolph Decoration' WHERE slug = 'crystal-rudolph-decoration' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Destiny of Black Spirit' WHERE slug = 'destiny-of-black-spirit' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Destiny of Black Spirit (อีเวนต์)' WHERE slug = 'destiny-of-black-spirit-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Destiny of White Spirit' WHERE slug = 'destiny-of-white-spirit' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Destiny of White Spirit (อีเวนต์)' WHERE slug = 'destiny-of-white-spirit-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Dignified Mustache' WHERE slug = 'dignified-mustache' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Event Amys Spectacles' WHERE slug = 'event-amys-spectacles' AND name_th IS NULL;