-- Migration 067: Thai names remaining v2 batch 4/9
-- Generated: 2026-03-16T03:55:14.474Z

UPDATE items SET name_th = 'หน้า Event Biancas Spectacles' WHERE slug = 'event-biancas-spectacles' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Event Halloween Amys Spectacles' WHERE slug = 'event-halloween-amys-spectacles' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Event Halloween Cadet Amys Spectacles' WHERE slug = 'event-halloween-cadet-amys-spectacles' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Face (Test)' WHERE slug = 'face-test' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Fake Arrow' WHERE slug = 'fake-arrow' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Fake Arrow (30 วัน)' WHERE slug = 'fake-arrow-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Fake Arrow (อีเวนต์)' WHERE slug = 'fake-arrow-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Honor - Butler' WHERE slug = 'glass-of-honor-butler' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Honor - Butler (อีเวนต์)' WHERE slug = 'glass-of-honor-butler-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Honor - Maid' WHERE slug = 'glass-of-honor-maid' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Honor - Maid (อีเวนต์)' WHERE slug = 'glass-of-honor-maid-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Teacher - Baselrane' WHERE slug = 'glass-of-teacher-baselrane' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Teacher - Baselrane (อีเวนต์)' WHERE slug = 'glass-of-teacher-baselrane-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Teacher - Black Cat' WHERE slug = 'glass-of-teacher-black-cat' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Teacher - Black Cat (อีเวนต์)' WHERE slug = 'glass-of-teacher-black-cat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Teacher - Illisia' WHERE slug = 'glass-of-teacher-illisia' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Teacher - Illisia (อีเวนต์)' WHERE slug = 'glass-of-teacher-illisia-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Teacher - Pey' WHERE slug = 'glass-of-teacher-pey' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Teacher - Pey (อีเวนต์)' WHERE slug = 'glass-of-teacher-pey-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glass of Wiz' WHERE slug = 'glass-of-wiz' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Elementalist' WHERE slug = 'glasses-for-female-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Elementalist (30 วัน)' WHERE slug = 'glasses-for-female-elementalist-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Fighter' WHERE slug = 'glasses-for-female-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Fighter (30 วัน)' WHERE slug = 'glasses-for-female-fighter-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Musketeer' WHERE slug = 'glasses-for-female-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Musketeer (30 วัน)' WHERE slug = 'glasses-for-female-musketeer-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Scout' WHERE slug = 'glasses-for-female-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Scout (30 วัน)' WHERE slug = 'glasses-for-female-scout-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Wizard' WHERE slug = 'glasses-for-female-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Female Wizard (30 วัน)' WHERE slug = 'glasses-for-female-wizard-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Elementalist' WHERE slug = 'glasses-for-male-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Elementalist (30 วัน)' WHERE slug = 'glasses-for-male-elementalist-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Fighter' WHERE slug = 'glasses-for-male-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Fighter (30 วัน)' WHERE slug = 'glasses-for-male-fighter-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Musketeer' WHERE slug = 'glasses-for-male-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Musketeer (30 วัน)' WHERE slug = 'glasses-for-male-musketeer-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Scout' WHERE slug = 'glasses-for-male-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Scout (30 วัน)' WHERE slug = 'glasses-for-male-scout-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Wizard' WHERE slug = 'glasses-for-male-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Glasses for Male Wizard (30 วัน)' WHERE slug = 'glasses-for-male-wizard-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาแห่งAdriana' WHERE slug = 'glasses-of-adriana' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาแห่งMarchetti' WHERE slug = 'glasses-of-marchetti' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาแห่งVeronif' WHERE slug = 'glasses-of-veronif' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Goggles' WHERE slug = 'goggles' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Goggles (30 วัน)' WHERE slug = 'goggles-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Gracielo School-Look Glass (อีเวนต์)' WHERE slug = 'gracielo-school-look-glass-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Green Iguana' WHERE slug = 'green-iguana' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Green Iguana (30 วัน)' WHERE slug = 'green-iguana-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Halloween Amys Spectacles' WHERE slug = 'halloween-amys-spectacles' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Halloween Cadet Amys Spectacles' WHERE slug = 'halloween-cadet-amys-spectacles' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Headgear' WHERE slug = 'headgear' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Headgear (30 วัน)' WHERE slug = 'headgear-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Jane Glass' WHERE slug = 'jane-glass' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Jane School Glass' WHERE slug = 'jane-school-glass' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาJane School (อีเวนต์)' WHERE slug = 'jane-school-glasses-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Lead Manager Rachels secret hobby' WHERE slug = 'lead-manager-rachels-secret-hobby' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Liberte Glass' WHERE slug = 'liberte-glass' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Monocle' WHERE slug = 'monocle' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Nena School-Look Glass (อีเวนต์)' WHERE slug = 'nena-school-look-glass-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Octopus Cap' WHERE slug = 'octopus-cap' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Octopus Cap (30 วัน)' WHERE slug = 'octopus-cap-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Octopus Scarf' WHERE slug = 'octopus-scarf' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Phobitan Cap' WHERE slug = 'phobitan-cap' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Phobitan Cap (30 วัน)' WHERE slug = 'phobitan-cap-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Phobitan Cap (อีเวนต์)' WHERE slug = 'phobitan-cap-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Red Face Paint' WHERE slug = 'red-face-paint' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Red Face Paint (30 วัน)' WHERE slug = 'red-face-paint-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาRound-rimmed' WHERE slug = 'round-rimmed-glasses' AND name_th IS NULL;
UPDATE items SET name_th = 'แว่นตาRound-rimmed (30 วัน)' WHERE slug = 'round-rimmed-glasses-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Saint Alude Glass - Black' WHERE slug = 'saint-alude-glass-black' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Saint Alude Glass - Violet' WHERE slug = 'saint-alude-glass-violet' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า White Face Paint' WHERE slug = 'white-face-paint' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า White Face Paint (30 วัน)' WHERE slug = 'white-face-paint-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Zaveds Glasses for Study' WHERE slug = 'zaveds-glasses-for-study' AND name_th IS NULL;
UPDATE items SET name_th = 'หน้า Zaveds Glasses for Study (อีเวนต์)' WHERE slug = 'zaveds-glasses-for-study-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โบราณ เบรซเล็ตไฟ Armonia' WHERE slug = 'ancient-armonia-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ of Behemoth' WHERE slug = 'bracelet-of-behemoth' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ of Empire' WHERE slug = 'bracelet-of-empire' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Charlottes Smile' WHERE slug = 'charlottes-smile' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Charlottes Smile (อีเวนต์)' WHERE slug = 'charlottes-smile-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า เบรซเล็ตไฟ Flame' WHERE slug = 'deus-machina-flame-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า เบรซเล็ตไฟ Flame (อีเวนต์)' WHERE slug = 'deus-machina-flame-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตไฟ of Behemoth' WHERE slug = 'elite-bracelet-of-behemoth' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตไฟ of Fire' WHERE slug = 'elite-bracelet-of-fire' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตไฟ of Muspell' WHERE slug = 'elite-bracelet-of-muspell' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตไฟ of Pluto' WHERE slug = 'elite-bracelet-of-pluto' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตไฟ of hellfire' WHERE slug = 'elite-bracelet-of-hellfire' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตไฟ of the Salamander' WHERE slug = 'elite-bracelet-of-the-salamander' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง เบรซเล็ตไฟ Flame Bangle' WHERE slug = 'elite-experimental-flame-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตไฟ Fire of Palermo' WHERE slug = 'elite-fire-of-palermo' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตไฟ Fire of Palermo (อีเวนต์)' WHERE slug = 'elite-fire-of-palermo-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เอเน็กซ์ อีเธอเรียล เบรซเล็ตไฟ Flame' WHERE slug = 'enex-ethereal-flame-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง เบรซเล็ตไฟ Flame Bangle' WHERE slug = 'experimental-flame-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Fire of Palermo' WHERE slug = 'fire-of-palermo' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Fire of Palermo (อีเวนต์)' WHERE slug = 'fire-of-palermo-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Flame Bangle of Howard' WHERE slug = 'flame-bangle-of-howard' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Flame Bracelet of Contract (7 วัน)' WHERE slug = 'flame-bracelet-of-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Incomplete Charlottes Smile' WHERE slug = 'incomplete-charlottes-smile' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Kenlight' WHERE slug = 'kenlight-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'ลีเจียน เบรซเล็ตไฟ Flame' WHERE slug = 'legion-flame-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'พรอสเป เบรซเล็ตไฟ Flame Bangle' WHERE slug = 'prospe-flame-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Pyrite Bangle' WHERE slug = 'pyrite-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เวสปาโนลาขัดเงา เบรซเล็ตไฟ Flame Bangle' WHERE slug = 'refined-vespanola-flame-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตไฟ Ruby of Passion' WHERE slug = 'ruby-of-passion' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เบรซเล็ตไฟ of Fire' WHERE slug = 'strata-devil-bracelet-of-fire' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เบรซเล็ตไฟ of Fire (อีเวนต์)' WHERE slug = 'strata-devil-bracelet-of-fire-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คำสั่งทรราช เบรซเล็ตไฟ Flame' WHERE slug = 'tyrants-order-flame-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คำสั่งทรราช เบรซเล็ตไฟ Flame (อีเวนต์)' WHERE slug = 'tyrants-order-flame-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา เบรซเล็ตไฟ Fire Bangle' WHERE slug = 'vespanola-pioneer-support-fire-bangle' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] เอเน็กซ์ อีเธอเรียล เบรซเล็ตไฟ Flame' WHERE slug = 'event-enex-ethereal-flame-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ +10 Gereros Power (1 วัน)' WHERE slug = '10-gereros-power-glove-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ +10 Ogjeffs Earth-color (1 วัน)' WHERE slug = '10-ogjeffs-earth-color-glove-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ +10 Stars Judges (1 วัน)' WHERE slug = '10-stars-judges-glove-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Desapio' WHERE slug = 'desapio-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง ถุงมือ Magic' WHERE slug = 'experimental-magic-glove' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Gereros Power' WHERE slug = 'gereros-power-glove' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Gereros Power (ภาพลวง)' WHERE slug = 'gereros-power-glove-illusion' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Giltines Demonic' WHERE slug = 'giltines-demonic-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ of Magician' WHERE slug = 'glove-of-magician' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ' WHERE slug = 'gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ of Artisan' WHERE slug = 'gloves-of-artisan' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Laimas Holy' WHERE slug = 'laimas-holy-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Magic' WHERE slug = 'magic-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Magic (อีเวนต์)' WHERE slug = 'magic-gloves-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Muertuos' WHERE slug = 'muertuos-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Mystic' WHERE slug = 'mystic-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Navas Dark' WHERE slug = 'navas-dark-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Ogjeffs Earth-color' WHERE slug = 'ogjeffs-earth-color-glove' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Ogjeffs Earth-color (ภาพลวง)' WHERE slug = 'ogjeffs-earth-color-glove-illusion' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Pioneer' WHERE slug = 'pioneer-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Quiritatio Unity' WHERE slug = 'quiritatio-unity-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Stars Judges' WHERE slug = 'stars-judges-glove' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Stars Judges (อีเวนต์)' WHERE slug = 'stars-judges-gloves-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Vigilar Tribes' WHERE slug = 'vigilar-tribes-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Vigilar Tribes (อีเวนต์)' WHERE slug = 'vigilar-tribes-gloves-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Zodiac (อีเวนต์)' WHERE slug = 'zodiac-glove-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ Zodiac' WHERE slug = 'zodiac-gloves' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] ถุงมือ Gerero' WHERE slug = 'dreaming-gerero-gloves' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] ถุงมือ Ogjeffs' WHERE slug = 'dreaming-ogjeffs-gloves' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ถุงมือ Giltines Demonic' WHERE slug = 'event-giltines-demonic-gloves' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ถุงมือ Laimas Holy' WHERE slug = 'event-laimas-holy-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ [Lucid] Gerero' WHERE slug = 'lucid-gerero-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ [Lucid] Ogjeffs' WHERE slug = 'lucid-ogjeffs-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ [Reverie] Gerero' WHERE slug = 'reverie-gerero-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'ถุงมือ [Reverie] Ogjeffs' WHERE slug = 'reverie-ogjeffs-gloves' AND name_th IS NULL;
UPDATE items SET name_th = 'แองเจิล ซอร์ดใหญ่ Zweihander' WHERE slug = 'angel-zweihander' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ดใหญ่ Einschiever Sword' WHERE slug = 'einschiever-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ดใหญ่ Destruction of Steel' WHERE slug = 'elite-destruction-of-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ดใหญ่ Earthcracker' WHERE slug = 'elite-earthcracker' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ดใหญ่ Kaladbolg' WHERE slug = 'elite-kaladbolg' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ดใหญ่ Merveilleuse' WHERE slug = 'elite-merveilleuse' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ดใหญ่ Muses Gigantespada' WHERE slug = 'elite-muses-gigantespada' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ดใหญ่ Slayer' WHERE slug = 'elite-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ดใหญ่ Vident Hander' WHERE slug = 'elite-vident-hander' AND name_th IS NULL;
UPDATE items SET name_th = 'อีวิล ซอร์ดใหญ่ Killer' WHERE slug = 'evil-killer' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ดใหญ่ of Contract (7 วัน)' WHERE slug = 'greatsword-of-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ดใหญ่ Improved Great Sword of Yeganeh (7 วัน)' WHERE slug = 'improved-great-sword-of-yeganeh-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ ซอร์ดใหญ่ Long Sword' WHERE slug = 'ogre-long-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ดใหญ่ Thornlight Slayer' WHERE slug = 'thornlight-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก 2022 Spring Hair - Bedel' WHERE slug = '2022-spring-hair-bedel' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก 2022 Spring Hair - Bedel (อีเวนต์)' WHERE slug = '2022-spring-hair-bedel-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก 2022 Spring Hair - Ivy' WHERE slug = '2022-spring-hair-ivy' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก 2022 Spring Hair - Ivy (อีเวนต์)' WHERE slug = '2022-spring-hair-ivy-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก 2022 Spring Hair - Maria' WHERE slug = '2022-spring-hair-maria' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก 2022 Spring Hair - Maria (อีเวนต์)' WHERE slug = '2022-spring-hair-maria-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก 2022 Spring Hair - Neo' WHERE slug = '2022-spring-hair-neo' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก 2022 Spring Hair - Neo (อีเวนต์)' WHERE slug = '2022-spring-hair-neo-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก A Head Band of Maid (30 วัน)' WHERE slug = 'a-head-band-of-maid-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Angel Ring' WHERE slug = 'angel-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Angelica hat (อีเวนต์)' WHERE slug = 'angelica-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมAnis natural (อีเวนต์)' WHERE slug = 'anis-natural-hair-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Antarona - Adelina' WHERE slug = 'antarona-adelina' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Antarona - Caisse' WHERE slug = 'antarona-caisse' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Antarona - Charlotte' WHERE slug = 'antarona-charlotte' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Antarona - Grandies' WHERE slug = 'antarona-grandies' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Antarona - Meister Lorch' WHERE slug = 'antarona-meister-lorch' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Antarona - Sergeant Barrel' WHERE slug = 'antarona-sergeant-barrel' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Antarona - Sorang' WHERE slug = 'antarona-sorang' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Arjerear Hairband' WHERE slug = 'arjerear-hairband' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Assassin Veil' WHERE slug = 'assassin-veil' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Assassin Veil (อีเวนต์)' WHERE slug = 'assassin-veil-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Barisada Circlet' WHERE slug = 'barisada-circlet' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Baselrane Hair - Black' WHERE slug = 'baselrane-hair-black' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Baselrane Hair - Blond' WHERE slug = 'baselrane-hair-blond' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Beliths Horn for Events' WHERE slug = 'beliths-horn-for-events' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Beret of Musketeers (30 วัน)' WHERE slug = 'beret-of-musketeers-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Cat Band' WHERE slug = 'black-cat-band' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Charmant Hair (Code Name L)' WHERE slug = 'black-charmant-hair-code-name-l' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Charmant Hair (Leona)' WHERE slug = 'black-charmant-hair-leona' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Cobra hat (อีเวนต์)' WHERE slug = 'black-cobra-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Feather Beret' WHERE slug = 'black-feather-beret' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Feather Beret (30 วัน)' WHERE slug = 'black-feather-beret-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Straight Permanent (อีเวนต์)' WHERE slug = 'black-straight-permanent-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Turban' WHERE slug = 'black-turban' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Black Veil' WHERE slug = 'black-veil' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Blown Curling Perm' WHERE slug = 'blown-curling-perm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Blue Serpent Hat (Male)' WHERE slug = 'blue-serpent-hat-male' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Blue Serpent Hat for Woman' WHERE slug = 'blue-serpent-hat-for-woman' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Bristian Natural Style' WHERE slug = 'bristian-natural-style' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Bunny Band' WHERE slug = 'brown-bunny-band' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Bunny Band (30 วัน)' WHERE slug = 'brown-bunny-band-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Bunny Band (7 วัน)' WHERE slug = 'brown-bunny-band-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Plait' WHERE slug = 'brown-plait' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Plait (30 วัน)' WHERE slug = 'brown-plait-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Ponytail' WHERE slug = 'brown-ponytail' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Ponytail (30 วัน)' WHERE slug = 'brown-ponytail-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Volume Perm' WHERE slug = 'brown-volume-perm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Brown Volume Perm (30 วัน)' WHERE slug = 'brown-volume-perm-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Butler of Honor Hair - Black' WHERE slug = 'butler-of-honor-hair-black' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Butler of Honor Hair - Black (อีเวนต์)' WHERE slug = 'butler-of-honor-hair-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Butler of Honor Hair - White' WHERE slug = 'butler-of-honor-hair-white' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Butler of Honor Hair - White (อีเวนต์)' WHERE slug = 'butler-of-honor-hair-white-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปแห่งEngineer (30 วัน)' WHERE slug = 'cap-of-engineer-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปแห่งInvestigator' WHERE slug = 'cap-of-investigator' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวกแก๊ปแห่งMechanic (30 วัน)' WHERE slug = 'cap-of-mechanic-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Capitaine Hair for Male Musketeer' WHERE slug = 'capitaine-hair-for-male-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Capitaine Hair for Male Wizard' WHERE slug = 'capitaine-hair-for-male-wizard' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Capitaine Hair for male Elementalists' WHERE slug = 'capitaine-hair-for-male-elementalists' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Capitaine Hat for Male Scout' WHERE slug = 'capitaine-hat-for-male-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Carvas Hair - Karat' WHERE slug = 'carvas-hair-karat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Carvas Hair - Sault' WHERE slug = 'carvas-hair-sault' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Carvas Hat - Karat' WHERE slug = 'carvas-hat-karat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Carvas Hat - Sault' WHERE slug = 'carvas-hat-sault' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Casual Short' WHERE slug = 'casual-short' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Casual Short (อีเวนต์)' WHERE slug = 'casual-short-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Cecil Ponytail (อีเวนต์)' WHERE slug = 'cecil-ponytail-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Cecile Ponytail' WHERE slug = 'cecile-ponytail' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Centurion Wolf' WHERE slug = 'centurion-wolf' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Chapeau De Blanc' WHERE slug = 'chapeau-de-blanc' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Chapeau De Blanc (30 วัน)' WHERE slug = 'chapeau-de-blanc-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Charmant Hair (Code Name L)' WHERE slug = 'charmant-hair-code-name-l' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Charmant Hair (Leona)' WHERE slug = 'charmant-hair-leona' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Classe Alta - Homburg' WHERE slug = 'classe-alta-homburg' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Classe Alta - Homburg (อีเวนต์)' WHERE slug = 'classe-alta-homburg-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Coa Basic Hair - Passion' WHERE slug = 'coa-basic-hair-passion' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Coa Basic Hair - Passion (อีเวนต์)' WHERE slug = 'coa-basic-hair-passion-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Colonel Cut' WHERE slug = 'colonel-cut' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Colonel Cut (อีเวนต์)' WHERE slug = 'colonel-cut-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Corchicum Bandana' WHERE slug = 'corchicum-bandana' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Corona La Ventisca' WHERE slug = 'corona-la-ventisca' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Corona La Ventisca (30 วัน)' WHERE slug = 'corona-la-ventisca-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Curling Perm' WHERE slug = 'curling-perm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Curling Perm (อีเวนต์)' WHERE slug = 'curling-perm-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Cute Bob' WHERE slug = 'cute-bob' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Cute Curl' WHERE slug = 'cute-curl' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Dancing Magic - Blueberry' WHERE slug = 'dancing-magic-blueberry' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Dancing Magic - Strawberry' WHERE slug = 'dancing-magic-strawberry' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Dandy Slicked-back' WHERE slug = 'dandy-slicked-back' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Dandy Slicked-back (30 วัน)' WHERE slug = 'dandy-slicked-back-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Delfinas Bandana' WHERE slug = 'delfinas-bandana' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Destiny of Cooperation' WHERE slug = 'destiny-of-cooperation' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Elegant Cute' WHERE slug = 'elegant-cute' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมElegant' WHERE slug = 'elegant-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Event Angel Ring Hairband' WHERE slug = 'event-angel-ring-hairband' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Event Black Charmant Hair (Code Name L)' WHERE slug = 'event-black-charmant-hair-code-name-l' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Event Black Charmant Hair (Leona)' WHERE slug = 'event-black-charmant-hair-leona' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Event Charmant Hair (Code Name L)' WHERE slug = 'event-charmant-hair-code-name-l' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Event Charmant Hair (Leona)' WHERE slug = 'event-charmant-hair-leona' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Event Dancing Magic - Blueberry' WHERE slug = 'event-dancing-magic-blueberry' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Event Dancing Magic - Strawberry' WHERE slug = 'event-dancing-magic-strawberry' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Fairy (30 วัน)' WHERE slug = 'fairy-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Fairy Band' WHERE slug = 'fairy-band' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Fairy Bob' WHERE slug = 'fairy-bob' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Fox mask' WHERE slug = 'fox-mask' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Frankenstein Head - Bryan' WHERE slug = 'frankenstein-head-bryan' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gangster Hairband' WHERE slug = 'gangster-hairband' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gangster Hairband (อีเวนต์)' WHERE slug = 'gangster-hairband-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Ghair of Gunsmith (30 วัน)' WHERE slug = 'ghair-of-gunsmith-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gilded Shaggy' WHERE slug = 'gilded-shaggy' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gilded Wolf' WHERE slug = 'gilded-wolf' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gloriosa Eye Patch' WHERE slug = 'gloriosa-eye-patch' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gloriosa Eye Patch set (อีเวนต์)' WHERE slug = 'gloriosa-eye-patch-set-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gradation Shaggy (อีเวนต์)' WHERE slug = 'gradation-shaggy-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gradation Shaggy Blend' WHERE slug = 'gradation-shaggy-blend' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gradation Shaggy Blend (อีเวนต์)' WHERE slug = 'gradation-shaggy-blend-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gradation shaggy' WHERE slug = 'gradation-shaggy' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gray Dandy Slicked-back' WHERE slug = 'gray-dandy-slicked-back' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gray Dandy Slicked-back (30 วัน)' WHERE slug = 'gray-dandy-slicked-back-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gray Layered Shaggy Cut' WHERE slug = 'gray-layered-shaggy-cut' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Gray Layered Shaggy Cut (30 วัน)' WHERE slug = 'gray-layered-shaggy-cut-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Guardian Coa Basic Hair - Justice' WHERE slug = 'guardian-coa-basic-hair-justice' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Guardian Coa Basic Hair - Justice (อีเวนต์)' WHERE slug = 'guardian-coa-basic-hair-justice-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hair Band of a Maid' WHERE slug = 'hair-band-of-a-maid' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมแห่งClara Mago (30 วัน)' WHERE slug = 'hair-of-clara-mago-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ผมแห่งGunsmith' WHERE slug = 'hair-of-gunsmith' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Basic Character' WHERE slug = 'halloween-pumpkin-hat-basic-character' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Basic Character (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-basic-character-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Cano' WHERE slug = 'halloween-pumpkin-hat-cano' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Cano (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-cano-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Claire' WHERE slug = 'halloween-pumpkin-hat-claire' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Claire (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-claire-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Ludin' WHERE slug = 'halloween-pumpkin-hat-ludin' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Ludin (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-ludin-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Montoro' WHERE slug = 'halloween-pumpkin-hat-montoro' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Montoro (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-montoro-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Rachel (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-rachel-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Ramiro' WHERE slug = 'halloween-pumpkin-hat-ramiro' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Ramiro (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-ramiro-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Rose' WHERE slug = 'halloween-pumpkin-hat-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Rose (อีเวนต์)' WHERE slug = 'halloween-pumpkin-hat-rose-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Rose (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-rose-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Sorang' WHERE slug = 'halloween-pumpkin-hat-sorang' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Sorang (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-sorang-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Tiburon' WHERE slug = 'halloween-pumpkin-hat-tiburon' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Tiburon (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-tiburon-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Viki' WHERE slug = 'halloween-pumpkin-hat-viki' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Halloween Pumpkin Hat - Viki (15 วัน)' WHERE slug = 'halloween-pumpkin-hat-viki-15-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat' WHERE slug = 'hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat (30 วัน)' WHERE slug = 'hat-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat (Test)' WHERE slug = 'hat-test' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat for Armonia Saint' WHERE slug = 'hat-for-armonia-saint' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Battle Cook (30 วัน)' WHERE slug = 'hat-of-battle-cook-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Battle Smith (30 วัน)' WHERE slug = 'hat-of-battle-smith-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Clara Mago (30 วัน)' WHERE slug = 'hat-of-clara-mago-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Cook (30 วัน)' WHERE slug = 'hat-of-cook-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Fencer (30 วัน)' WHERE slug = 'hat-of-fencer-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Gladiator (30 วัน)' WHERE slug = 'hat-of-gladiator-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Pirate (30 วัน)' WHERE slug = 'hat-of-pirate-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Sniper (30 วัน)' WHERE slug = 'hat-of-sniper-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Witch (7 วัน)' WHERE slug = 'hat-of-witch-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Witch (30 วัน)' WHERE slug = 'hat-of-witch-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of Yeganeh (30 วัน)' WHERE slug = 'hat-of-yeganeh-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hat of commander of Blood Navy' WHERE slug = 'hat-of-commander-of-blood-navy' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hawkeye' WHERE slug = 'hawkeye' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hawkeye (30 วัน)' WHERE slug = 'hawkeye-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Helmet of Idge (30 วัน)' WHERE slug = 'helmet-of-idge-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Horn of Oscuras' WHERE slug = 'horn-of-oscuras' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Hunters hat' WHERE slug = 'hunters-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Inviardeco Goggles' WHERE slug = 'inviardeco-goggles' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Ivory Homburg' WHERE slug = 'ivory-homburg' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Ivory Homburg (30 วัน)' WHERE slug = 'ivory-homburg-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Kalbath Hair - Carat (อีเวนต์)' WHERE slug = 'kalbath-hair-carat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Kalbath Hair - Salt (อีเวนต์)' WHERE slug = 'kalbath-hair-salt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Kalbath Hat - Carat (อีเวนต์)' WHERE slug = 'kalbath-hat-carat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Kalbath Hat - Salt (อีเวนต์)' WHERE slug = 'kalbath-hat-salt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Korean Hat for Female Elementalist (7 วัน)' WHERE slug = 'korean-hat-for-female-elementalist-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Korean Hat for Male Fighter' WHERE slug = 'korean-hat-for-male-fighter' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Korean Hat for Male Fighter (30 วัน)' WHERE slug = 'korean-hat-for-male-fighter-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Korean Hat for Male Fighter (7 วัน)' WHERE slug = 'korean-hat-for-male-fighter-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Korean Hat for Male Musketeer' WHERE slug = 'korean-hat-for-male-musketeer' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Korean Hat for Male Musketeer (30 วัน)' WHERE slug = 'korean-hat-for-male-musketeer-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Korean Hat for Male Musketeer (7 วัน)' WHERE slug = 'korean-hat-for-male-musketeer-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก La Chevre Cornue Fidele' WHERE slug = 'la-chevre-cornue-fidele' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก La Chevre Cornue Fidele (อีเวนต์)' WHERE slug = 'la-chevre-cornue-fidele-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก La Coiffure du Monsieur Noble' WHERE slug = 'la-coiffure-du-monsieur-noble' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก La Sensation Amicale Head Dress' WHERE slug = 'la-sensation-amicale-head-dress' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Lantern Hat of Jack O (30 วัน)' WHERE slug = 'lantern-hat-of-jack-o-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Lantern Hat of Jack O (7 วัน)' WHERE slug = 'lantern-hat-of-jack-o-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Lantern Hat of Jack O - Rachel' WHERE slug = 'lantern-hat-of-jack-o-rachel' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Layered Bob' WHERE slug = 'layered-bob' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Layered Shaggy Cut' WHERE slug = 'layered-shaggy-cut' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Layered Shaggy Cut (30 วัน)' WHERE slug = 'layered-shaggy-cut-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Le Cancer de Sansibilite Bandana' WHERE slug = 'le-cancer-de-sansibilite-bandana' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Les Cheveux Declatant Beaut' WHERE slug = 'les-cheveux-declatant-beaut' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Light Hair Band' WHERE slug = 'light-hair-band' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Light Hair Band (30 วัน)' WHERE slug = 'light-hair-band-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Light Hair Band (อีเวนต์)' WHERE slug = 'light-hair-band-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Lord Plate Eye Patch' WHERE slug = 'lord-plate-eye-patch' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Magic Party Hair Style (อีเวนต์)' WHERE slug = 'magic-party-hair-style-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Magic party hair style' WHERE slug = 'magic-party-hair-style' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Maid of Honor Hair - Black' WHERE slug = 'maid-of-honor-hair-black' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Maid of Honor Hair - Black (อีเวนต์)' WHERE slug = 'maid-of-honor-hair-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Maid of Honor Hair - White' WHERE slug = 'maid-of-honor-hair-white' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Maid of Honor Hair - White (อีเวนต์)' WHERE slug = 'maid-of-honor-hair-white-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Milky Bob' WHERE slug = 'milky-bob' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Milky Bob (อีเวนต์)' WHERE slug = 'milky-bob-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Misa Basic Hair - Blonde' WHERE slug = 'misa-basic-hair-blonde' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Misa Basic Hair - Blonde (อีเวนต์)' WHERE slug = 'misa-basic-hair-blonde-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Misa Basic Hair - Brown' WHERE slug = 'misa-basic-hair-brown' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Misa Basic Hair - Brown (อีเวนต์)' WHERE slug = 'misa-basic-hair-brown-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Musketeers Beret' WHERE slug = 'musketeers-beret' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Natural Half' WHERE slug = 'natural-half' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Natural Half (อีเวนต์)' WHERE slug = 'natural-half-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Natural Style' WHERE slug = 'natural-style' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Natural Wave' WHERE slug = 'natural-wave' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Natural style (อีเวนต์)' WHERE slug = 'natural-style-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก None' WHERE slug = 'none' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Olga Tribunal - Basic' WHERE slug = 'olga-tribunal-basic' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Olga Tribunal - Hoodie' WHERE slug = 'olga-tribunal-hoodie' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Painter bere.' WHERE slug = 'painter-bere' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Pandera Call-back' WHERE slug = 'pandera-call-back' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Party Hair - Emotion (อีเวนต์)' WHERE slug = 'party-hair-emotion-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Party Hair - sensibility' WHERE slug = 'party-hair-sensibility' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Pendera Call-back (30 วัน)' WHERE slug = 'pendera-call-back-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Pey Hair - Olive' WHERE slug = 'pey-hair-olive' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Pey Hair - Wine' WHERE slug = 'pey-hair-wine' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Plait' WHERE slug = 'plait' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Plait (30 วัน)' WHERE slug = 'plait-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Ponytail' WHERE slug = 'ponytail' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Ponytail (30 วัน)' WHERE slug = 'ponytail-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Pretty Short' WHERE slug = 'pretty-short' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Princess Sakura Basic Hair - Festival' WHERE slug = 'princess-sakura-basic-hair-festival' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Princess Sakura Basic Hair - Festival (อีเวนต์)' WHERE slug = 'princess-sakura-basic-hair-festival-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rabbit Hairlace' WHERE slug = 'rabbit-hairlace' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rabbit Hairlace (30 วัน)' WHERE slug = 'rabbit-hairlace-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rabbit Hairlace (7 วัน)' WHERE slug = 'rabbit-hairlace-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rascel Natural Hair Style' WHERE slug = 'rascel-natural-hair-style' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rascel Natural Hair Style (อีเวนต์)' WHERE slug = 'rascel-natural-hair-style-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Refinement Hair Style' WHERE slug = 'refinement-hair-style' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Refinement Hair Style (อีเวนต์)' WHERE slug = 'refinement-hair-style-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rose Blanche Hat - Dawn' WHERE slug = 'rose-blanche-hat-dawn' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rose Blanche Hat - Twilight' WHERE slug = 'rose-blanche-hat-twilight' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rose Blanche Hat- Twilight (อีเวนต์)' WHERE slug = 'rose-blanche-hat-twilight-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Rose Blanche- Dawn (อีเวนต์)' WHERE slug = 'rose-blanche-dawn-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Safian De Hermes' WHERE slug = 'safian-de-hermes' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Saint Alude Hair - Gold' WHERE slug = 'saint-alude-hair-gold' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Saint Alude Hair - Gold (อีเวนต์)' WHERE slug = 'saint-alude-hair-gold-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Saint Alude Hair - Pink' WHERE slug = 'saint-alude-hair-pink' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Saint Alude Hair - Pink (อีเวนต์)' WHERE slug = 'saint-alude-hair-pink-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Sakura Basic Hair - Sun' WHERE slug = 'sakura-basic-hair-sun' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Sakura Basic Hair - Sun (อีเวนต์)' WHERE slug = 'sakura-basic-hair-sun-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Samurai Helmet (Black)' WHERE slug = 'samurai-helmet-black' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Samurai Helmet (Blue)' WHERE slug = 'samurai-helmet-blue' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Samurai Helmet (Red)' WHERE slug = 'samurai-helmet-red' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Santa Hat - Adelina' WHERE slug = 'santa-hat-adelina' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Santa Hat - Bernelli' WHERE slug = 'santa-hat-bernelli' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Santa Hat - Calyce' WHERE slug = 'santa-hat-calyce' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Santa Hat - Emilia' WHERE slug = 'santa-hat-emilia' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Scratch' WHERE slug = 'scratch' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Shaggy Bob' WHERE slug = 'shaggy-bob' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Shaggy Wolf' WHERE slug = 'shaggy-wolf' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Shapka' WHERE slug = 'shapka' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Shapka (30 วัน)' WHERE slug = 'shapka-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Snowfield Witch hat' WHERE slug = 'snowfield-witch-hat' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Snowfield Witch hat (อีเวนต์)' WHERE slug = 'snowfield-witch-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Soul of Castilla' WHERE slug = 'soul-of-castilla' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Straight Perm' WHERE slug = 'straight-perm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Stylish Sunglasses(No use)' WHERE slug = 'stylish-sunglasses-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Targan Turban' WHERE slug = 'targan-turban' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Targan Turban (30 วัน)' WHERE slug = 'targan-turban-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Teacher Baselrane Hair - Black (อีเวนต์)' WHERE slug = 'teacher-baselrane-hair-black-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Teacher Baselrane Hair - Blond (อีเวนต์)' WHERE slug = 'teacher-baselrane-hair-blond-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Teacher Illisia Hair - Aurel' WHERE slug = 'teacher-illisia-hair-aurel' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Teacher Illisia Hair - Aurel (อีเวนต์)' WHERE slug = 'teacher-illisia-hair-aurel-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Teacher Illisia Hair - Original' WHERE slug = 'teacher-illisia-hair-original' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Teacher Illisia Hair - Original (อีเวนต์)' WHERE slug = 'teacher-illisia-hair-original-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Teacher Pey Hair - Olive (อีเวนต์)' WHERE slug = 'teacher-pey-hair-olive-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Teacher Pey Hair - Wine (อีเวนต์)' WHERE slug = 'teacher-pey-hair-wine-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Tight Arrangement' WHERE slug = 'tight-arrangement' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Tight Arrangement (อีเวนต์)' WHERE slug = 'tight-arrangement-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Tortoba Manila' WHERE slug = 'tortoba-manila' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Vespanola Navy Hat - Admiral' WHERE slug = 'vespanola-navy-hat-admiral' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Vespanola Navy Hat - Soldier' WHERE slug = 'vespanola-navy-hat-soldier' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Violet Ponytail' WHERE slug = 'violet-ponytail' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Violet Ponytail (30 วัน)' WHERE slug = 'violet-ponytail-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Violet Tail' WHERE slug = 'violet-tail' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Volume Perm' WHERE slug = 'volume-perm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Volume Perm (30 วัน)' WHERE slug = 'volume-perm-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wave Curl' WHERE slug = 'wave-curl' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wave Perm' WHERE slug = 'wave-perm' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wave Perm (อีเวนต์)' WHERE slug = 'wave-perm-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wavy Hairstyle' WHERE slug = 'wavy-hairstyle' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wavy Hairstyle (30 วัน)' WHERE slug = 'wavy-hairstyle-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wavy Long Tail' WHERE slug = 'wavy-long-tail' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wavy Ponytail' WHERE slug = 'wavy-ponytail' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wavy Ponytail (อีเวนต์)' WHERE slug = 'wavy-ponytail-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wavy Shaggy (อีเวนต์)' WHERE slug = 'wavy-shaggy-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wavy Shaggy Cut' WHERE slug = 'wavy-shaggy-cut' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก White Cat Band' WHERE slug = 'white-cat-band' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก White Veil' WHERE slug = 'white-veil' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wig' WHERE slug = 'wig' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wig (30 วัน)' WHERE slug = 'wig-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wild Back' WHERE slug = 'wild-back' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wild Blare' WHERE slug = 'wild-blare' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wild Blare (อีเวนต์)' WHERE slug = 'wild-blare-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wild Layered Shaggy' WHERE slug = 'wild-layered-shaggy' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wild Short' WHERE slug = 'wild-short' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wild Tale' WHERE slug = 'wild-tale' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Will-of-the-wisp - Chungha' WHERE slug = 'will-of-the-wisp-chungha' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Witch hat of Siera' WHERE slug = 'witch-hat-of-siera' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Witchs hat (อีเวนต์)' WHERE slug = 'witchs-hat-event' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wreath' WHERE slug = 'wreath' AND name_th IS NULL;
UPDATE items SET name_th = 'หมวก Wreath (30 วัน)' WHERE slug = 'wreath-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า ไรเฟิลหนัก Large Caliber' WHERE slug = 'abyss-arma-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า ไรเฟิลหนัก Large Caliber (อีเวนต์)' WHERE slug = 'abyss-arma-large-caliber-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แอตลาส ไรเฟิลหนัก Gaze' WHERE slug = 'atlas-gaze' AND name_th IS NULL;
UPDATE items SET name_th = 'แอตลาส ไรเฟิลหนัก Gaze (อีเวนต์)' WHERE slug = 'atlas-gaze-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า ไรเฟิลหนัก Large Caliber' WHERE slug = 'deus-machina-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า ไรเฟิลหนัก Large Caliber (อีเวนต์)' WHERE slug = 'deus-machina-large-caliber-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เอเน็กซ์ อีเธอเรียล ไรเฟิลหนัก Large-Caliber' WHERE slug = 'enex-ethereal-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'อีเวนต์ อีลิท มูเอร์ทัวร์ส ไรเฟิลหนัก' WHERE slug = 'event-elite-muertuors-heavy-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'อีเวนต์ มูเอร์ทัวร์ส ไรเฟิลหนัก' WHERE slug = 'event-muertuors-heavy-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง ไรเฟิลหนัก Large Caliber' WHERE slug = 'experimental-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิลหนัก IAR-323 Large Caliber' WHERE slug = 'iar-323-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิลหนัก IBR-620 Large Caliber' WHERE slug = 'ibr-620-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิลหนัก IBR-620 Large Caliber (อีเวนต์)' WHERE slug = 'ibr-620-large-caliber-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิลหนัก ILE-525 Large Caliber' WHERE slug = 'ile-525-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิลหนัก ILE-525 Large Caliber (อีเวนต์)' WHERE slug = 'ile-525-large-caliber-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิลหนัก Incomplete Atlas Gaze' WHERE slug = 'incomplete-atlas-gaze' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิลหนัก Large Caliber Rifle of Contract (7 วัน)' WHERE slug = 'large-caliber-rifle-of-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลีเจียน ไรเฟิลหนัก Large Caliber' WHERE slug = 'legion-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'มูเอร์ทัวร์ส ไรเฟิลหนัก' WHERE slug = 'muertuors-heavy-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คำสั่งทรราช ไรเฟิลหนัก Large Caliber' WHERE slug = 'tyrants-order-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คำสั่งทรราช ไรเฟิลหนัก Large Caliber (อีเวนต์)' WHERE slug = 'tyrants-order-large-caliber-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา ไรเฟิลหนัก Large Caliber' WHERE slug = 'vespanola-pioneer-support-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] เอเน็กซ์ อีเธอเรียล ไรเฟิลหนัก Large-Caliber' WHERE slug = 'event-enex-ethereal-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Aquamarine of Purity' WHERE slug = 'aquamarine-of-purity' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง of Leviathan' WHERE slug = 'bracelet-of-leviathan' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Chloes Affection' WHERE slug = 'chloes-affection' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Chloes Affection (อีเวนต์)' WHERE slug = 'chloes-affection-event' AND name_th IS NULL;