-- Migration 068: Thai names remaining v2 batch 5/9
-- Generated: 2026-03-16T03:55:14.475Z

UPDATE items SET name_th = 'อีลิท เบรซเล็ตน้ำแข็ง Aurora' WHERE slug = 'elite-aurora-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตน้ำแข็ง of Ice' WHERE slug = 'elite-bracelet-of-ice' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตน้ำแข็ง of Leviathan' WHERE slug = 'elite-bracelet-of-leviathan' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตน้ำแข็ง of Neptune' WHERE slug = 'elite-bracelet-of-neptune' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตน้ำแข็ง of the Yeti' WHERE slug = 'elite-bracelet-of-the-yeti' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง เบรซเล็ตน้ำแข็ง Ice Bangle' WHERE slug = 'elite-experimental-ice-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตน้ำแข็ง Ice of Sualocin' WHERE slug = 'elite-ice-of-sualocin' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตน้ำแข็ง Ice of Sualocin (อีเวนต์)' WHERE slug = 'elite-ice-of-sualocin-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตน้ำแข็ง Tempest' WHERE slug = 'elite-tempest-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง เบรซเล็ตน้ำแข็ง Ice Bangle' WHERE slug = 'experimental-ice-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Ezlight' WHERE slug = 'ezlight-ice-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Ice Bangle of Meyer' WHERE slug = 'ice-bangle-of-meyer' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Ice of Sualocin' WHERE slug = 'ice-of-sualocin' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Ice of Sualocin (อีเวนต์)' WHERE slug = 'ice-of-sualocin-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Iceberg Bangle' WHERE slug = 'iceberg-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตน้ำแข็ง Incomplete Chloes Affection' WHERE slug = 'incomplete-chloes-affection' AND name_th IS NULL;
UPDATE items SET name_th = 'พรอสเป เบรซเล็ตน้ำแข็ง Ice Bangle' WHERE slug = 'prospe-ice-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เวสปาโนลาขัดเงา เบรซเล็ตน้ำแข็ง Ice Bangle' WHERE slug = 'refined-vespanola-ice-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เบรซเล็ตน้ำแข็ง of Ice' WHERE slug = 'strata-devil-bracelet-of-ice' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เบรซเล็ตน้ำแข็ง of Ice (อีเวนต์)' WHERE slug = 'strata-devil-bracelet-of-ice-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา เบรซเล็ตน้ำแข็ง Ice Bangle' WHERE slug = 'vespanola-pioneer-support-ice-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท จาวลิน Cortes' WHERE slug = 'elite-cortes' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท จาวลิน Pizarro' WHERE slug = 'elite-pizarro' AND name_th IS NULL;
UPDATE items SET name_th = 'จาวลิน Redlight Javeline' WHERE slug = 'redlight-javeline' AND name_th IS NULL;
UPDATE items SET name_th = 'เวสปาโนลาขัดเงา จาวลิน Javeline' WHERE slug = 'refined-vespanola-javeline' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท นัคเคิล' WHERE slug = 'elite-knuckle' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท นัคเคิล Steel of Destruction' WHERE slug = 'elite-steel-of-destruction' AND name_th IS NULL;
UPDATE items SET name_th = 'นัคเคิล Manaslight' WHERE slug = 'manaslight-knuckle' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Amoladera Hard-leather Armor' WHERE slug = 'amoladera-hard-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Amoladera Leather armor' WHERE slug = 'amoladera-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Amoladera Studded-leather Armor' WHERE slug = 'amoladera-studded-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Amoladera Sunset Stripe Suit' WHERE slug = 'amoladera-sunset-stripe-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Armor of Gladiator of Cinderella' WHERE slug = 'armor-of-gladiator-of-cinderella' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Armor of the Gladiator' WHERE slug = 'armor-of-the-gladiator' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Armure Diabolique -' WHERE slug = 'armure-diabolique-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Armure Diabolique - (อีเวนต์)' WHERE slug = 'armure-diabolique-leather-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Armure Diabolique of Behemoth -' WHERE slug = 'armure-diabolique-of-behemoth-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Armure Diabolique of Behemoth - (อีเวนต์)' WHERE slug = 'armure-diabolique-of-behemoth-leather-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Astartes' WHERE slug = 'astartes-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Bear Suit' WHERE slug = 'bear-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Blessing of God' WHERE slug = 'blessing-of-god' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Blue Serpent' WHERE slug = 'blue-serpent-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Blue Serpent Leather Armor (No Use)' WHERE slug = 'blue-serpent-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Bone Frame Armor' WHERE slug = 'bone-frame-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Camisa de Soldado' WHERE slug = 'camisa-de-soldado' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Capezzolo di Pericolo' WHERE slug = 'capezzolo-di-pericolo' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Capezzolo di Pericolo of Cinderella' WHERE slug = 'capezzolo-di-pericolo-of-cinderella' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Capezzolo di Pericolo of Cinderella (60 วัน)' WHERE slug = 'capezzolo-di-pericolo-of-cinderella-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Cinderella Le Blanc (60 วัน)' WHERE slug = 'cinderella-le-blanc-leather-armor-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Cinderella Le Blanc Leather Armor (60 days)(No Use)' WHERE slug = 'cinderella-le-blanc-leather-armor-60-days-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Consolidar Hard-leather Armor' WHERE slug = 'consolidar-hard-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Consolidar' WHERE slug = 'consolidar-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Consolidar Studded-leather armor' WHERE slug = 'consolidar-studded-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Consolidar Sunset Stripe Suit' WHERE slug = 'consolidar-sunset-stripe-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ เกราะหนัง Le Blanc' WHERE slug = 'divine-le-blanc-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Arcanero Plate' WHERE slug = 'elite-arcanero-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Bone Frame Armor' WHERE slug = 'elite-bone-frame-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Camisa de Soldado' WHERE slug = 'elite-camisa-de-soldado' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Clarcana' WHERE slug = 'elite-clarcana' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Hard-leather Armor' WHERE slug = 'elite-hard-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Inviardeco' WHERE slug = 'elite-inviardeco' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Laranja e Preto' WHERE slug = 'elite-laranja-e-preto' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Le Noir Leather Armor (No Use)' WHERE slug = 'elite-le-noir-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Le Scarce Leather Armor (No Use)' WHERE slug = 'elite-le-scarce-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง' WHERE slug = 'elite-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Tunic' WHERE slug = 'elite-leather-tunic' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Piernoente' WHERE slug = 'elite-piernoente' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Rescue Suit' WHERE slug = 'elite-rescue-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Ring Mail' WHERE slug = 'elite-ring-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Studded-leather Armor' WHERE slug = 'elite-studded-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะหนัง Sunset Stripe Suit' WHERE slug = 'elite-sunset-stripe-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง EliteElite Dignite Leather Armor (No Use)' WHERE slug = 'eliteelite-dignite-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Enhanced Bone Frame Armor' WHERE slug = 'enhanced-bone-frame-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Event Elite Le Blanc Leather Armor (No Use)' WHERE slug = 'event-elite-le-blanc-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Event Elite Le Noir Leather Armor (No Use)' WHERE slug = 'event-elite-le-noir-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Event Greek Croma Leather Armor (No Use)' WHERE slug = 'event-greek-croma-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง เกราะหนัง (No Use)' WHERE slug = 'experimental-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Fanatic Suit' WHERE slug = 'fanatic-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Frontier Croma(Leather Armor)' WHERE slug = 'frontier-croma-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Gladiator Armor of Cinderella (60 วัน)' WHERE slug = 'gladiator-armor-of-cinderella-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Greek Croma (No Use)' WHERE slug = 'greek-croma-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Greek Croma' WHERE slug = 'greek-croma-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Greek Croma (อีเวนต์)' WHERE slug = 'greek-croma-leather-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Grim Knight' WHERE slug = 'grim-knight' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Hard-leather Armor' WHERE slug = 'hard-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Laranja e Preto' WHERE slug = 'laranja-e-preto' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Blanc (Leather Armor)' WHERE slug = 'le-blanc-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Blanc Leather Armor (No Use)' WHERE slug = 'le-blanc-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Blanc of Cinderella' WHERE slug = 'le-blanc-of-cinderella-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Blanc of Cinderella Leather Armor (No Use)' WHERE slug = 'le-blanc-of-cinderella-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Noir' WHERE slug = 'le-noir-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Noir Leather Armor (No Use)' WHERE slug = 'le-noir-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Pouvoir Leader Armor (Not Use)' WHERE slug = 'le-pouvoir-leader-armor-not-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Pouvoir' WHERE slug = 'le-pouvoir-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Scarce' WHERE slug = 'le-scarce-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Le Scarce Leather Armor (No Use)' WHERE slug = 'le-scarce-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง' WHERE slug = 'leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Coat of Expert' WHERE slug = 'leather-coat-of-expert' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Tunic' WHERE slug = 'leather-tunic' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Tunic from Queen' WHERE slug = 'leather-tunic-from-queen' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Legacy - Royal' WHERE slug = 'legacy-royal-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Light Demons Armure Diabolique -' WHERE slug = 'light-demons-armure-diabolique-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Light Demons Armure Diabolique - (อีเวนต์)' WHERE slug = 'light-demons-armure-diabolique-leather-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Nero Croma' WHERE slug = 'nero-croma-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Nero Croma Leather Armor (No Use)' WHERE slug = 'nero-croma-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Novice Leather Tunic' WHERE slug = 'novice-leather-tunic' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ เกราะหนัง Noir Mail' WHERE slug = 'ogre-noir-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ เกราะหนัง Noir Mail (No Use)' WHERE slug = 'ogre-noir-mail-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Oiled Body' WHERE slug = 'oiled-body' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Old Elite Le Noir' WHERE slug = 'old-elite-le-noir-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Old Greek Croma' WHERE slug = 'old-greek-croma-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Old Strata Devil' WHERE slug = 'old-strata-devil-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Pioneer Combat' WHERE slug = 'pioneer-combat-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Pioneer' WHERE slug = 'pioneer-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Pioneer Mystic' WHERE slug = 'pioneer-mystic-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Pioneer Old' WHERE slug = 'pioneer-old-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Pioneer Practice' WHERE slug = 'pioneer-practice-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Pioneer Thick' WHERE slug = 'pioneer-thick-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Red Serpent' WHERE slug = 'red-serpent-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Red Serpent Leather Armor (No Use)' WHERE slug = 'red-serpent-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Rescue Armor' WHERE slug = 'rescue-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Rescue Suit' WHERE slug = 'rescue-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Ring Mail' WHERE slug = 'ring-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'ราชวงศ์ เกราะหนัง' WHERE slug = 'royal-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Santo De Blanc' WHERE slug = 'santo-de-blanc-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Santo De Blanc (อีเวนต์)' WHERE slug = 'santo-de-blanc-leather-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Santo De Blanc Leather Armor (No Use)' WHERE slug = 'santo-de-blanc-leather-armor-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Santo De Blanc Leather Armor (No Use) (อีเวนต์)' WHERE slug = 'santo-de-blanc-leather-armor-no-use-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เกราะหนัง (No Use)' WHERE slug = 'strata-devil-no-use' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เกราะหนัง (No Use) (อีเวนต์)' WHERE slug = 'strata-devil-leather-armor-no-use-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Studded-leather Armor' WHERE slug = 'studded-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Sunset Striped Suit' WHERE slug = 'sunset-striped-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะหนัง Supreme Dignite' WHERE slug = 'supreme-dignite-leather' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ราชวงศ์ เกราะหนัง' WHERE slug = 'event-royal-leather-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า สนับแข้ง Leg-Guards' WHERE slug = 'abyss-arma-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'อะบิส อาร์ม่า สนับแข้ง Leg-Guards (อีเวนต์)' WHERE slug = 'abyss-arma-leg-guards-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แองเจิล สนับแข้ง Leg-Guards' WHERE slug = 'angel-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย สนับแข้ง Leg-Guards' WHERE slug = 'armonia-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'อาร์โมเนีย สนับแข้ง Leg-Guards (อีเวนต์)' WHERE slug = 'armonia-leg-guards-event' AND name_th IS NULL;
UPDATE items SET name_th = 'แอตลาส สนับแข้ง Brutality' WHERE slug = 'atlas-brutality' AND name_th IS NULL;
UPDATE items SET name_th = 'แอตลาส สนับแข้ง Brutality (อีเวนต์)' WHERE slug = 'atlas-brutality-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Azulita of Speed' WHERE slug = 'azulita-of-speed' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Balance of Libra' WHERE slug = 'balance-of-libra' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Balance of Libra (อีเวนต์)' WHERE slug = 'balance-of-libra-event' AND name_th IS NULL;
UPDATE items SET name_th = 'บริสเทีย สนับแข้ง Leg-Guards' WHERE slug = 'bristia-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Carbon Leg-Guards' WHERE slug = 'carbon-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า สนับแข้ง Leg-guard' WHERE slug = 'deus-machina-leg-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'เดอุส มาชิน่า สนับแข้ง Leg-guard (อีเวนต์)' WHERE slug = 'deus-machina-leg-guard-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ สนับแข้ง Leg-Guards' WHERE slug = 'divine-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท สนับแข้ง Balance of Libra' WHERE slug = 'elite-balance-of-libra' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท สนับแข้ง Balance of Libra (อีเวนต์)' WHERE slug = 'elite-balance-of-libra-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท บริสเทีย สนับแข้ง Leg-Guards' WHERE slug = 'elite-bristia-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท บริสเทีย สนับแข้ง Leg-Guards (อีเวนต์)' WHERE slug = 'elite-bristia-leg-guards-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง สนับแข้ง Leg-Guards' WHERE slug = 'elite-experimental-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท สนับแข้ง La Estrella' WHERE slug = 'elite-la-estrella' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท สนับแข้ง Leg-Guards' WHERE slug = 'elite-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท สนับแข้ง Leg-Guards of Storm' WHERE slug = 'elite-leg-guards-of-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท สนับแข้ง Leg-Guards of Wind' WHERE slug = 'elite-leg-guards-of-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'อีวิล สนับแข้ง Leg-Guards' WHERE slug = 'evil-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง สนับแข้ง Leg-Guards' WHERE slug = 'experimental-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Gluttony Leg-Guard' WHERE slug = 'gluttony-leg-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'ทอง สนับแข้ง Feet' WHERE slug = 'golden-feet' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Incomplete Atlas Brutality' WHERE slug = 'incomplete-atlas-brutality' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง La Estrella' WHERE slug = 'la-estrella' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Leg-Guards of Hanged Man' WHERE slug = 'leg-guards-of-hanged-man' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Leg-Guards of Raionu' WHERE slug = 'leg-guards-of-raionu' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Leg-Guards of Srutoss' WHERE slug = 'leg-guards-of-srutoss' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Leg-Guards of the Yeti' WHERE slug = 'leg-guards-of-the-yeti' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Leg-guard of Contract (7 วัน)' WHERE slug = 'leg-guard-of-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลีเจียน สนับแข้ง Leg-guard' WHERE slug = 'legion-leg-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'พรอสเป สนับแข้ง Leg-Guards' WHERE slug = 'prospe-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'เวสปาโนลาขัดเงา สนับแข้ง Leg-Guards' WHERE slug = 'refined-vespanola-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับแข้ง Sigellight Leguard' WHERE slug = 'sigellight-leguard' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล สนับแข้ง Leg-Guard' WHERE slug = 'strata-devil-leg-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล สนับแข้ง Leg-Guards (อีเวนต์)' WHERE slug = 'strata-devil-leg-guards-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คำสั่งทรราช สนับแข้ง Leg-guard' WHERE slug = 'tyrants-order-leg-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'คำสั่งทรราช สนับแข้ง Leg-guard (อีเวนต์)' WHERE slug = 'tyrants-order-leg-guard-event' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน สนับแข้ง Leg-Guard' WHERE slug = 'valeron-leg-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'วาเลรอน สนับแข้ง Leg-Guard (อีเวนต์)' WHERE slug = 'valeron-leg-guard-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา สนับแข้ง Leg-guard' WHERE slug = 'vespanola-pioneer-support-leg-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า of Ziz' WHERE slug = 'bracelet-of-ziz' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตฟ้าผ่า of Lightning' WHERE slug = 'elite-bracelet-of-lightning' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตฟ้าผ่า of Storm' WHERE slug = 'elite-bracelet-of-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตฟ้าผ่า of Sylphide' WHERE slug = 'elite-bracelet-of-sylphide' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตฟ้าผ่า of Uranus' WHERE slug = 'elite-bracelet-of-uranus' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตฟ้าผ่า of Wind' WHERE slug = 'elite-bracelet-of-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตฟ้าผ่า of Ziz' WHERE slug = 'elite-bracelet-of-ziz' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง เบรซเล็ตฟ้าผ่า Lightning Bangle' WHERE slug = 'elite-experimental-lightning-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตฟ้าผ่า Lightning of Rotanev' WHERE slug = 'elite-lightning-of-rotanev' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตฟ้าผ่า Lightning of Rotanev (อีเวนต์)' WHERE slug = 'elite-lightning-of-rotanev-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เอเน็กซ์ อีเธอเรียล เบรซเล็ตฟ้าผ่า Electric' WHERE slug = 'enex-ethereal-electric-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง เบรซเล็ตฟ้าผ่า Lightning Bangle' WHERE slug = 'experimental-lightning-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Incomplete Ordens Tear' WHERE slug = 'incomplete-ordens-tear' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Lightening of Rotanev (อีเวนต์)' WHERE slug = 'lightening-of-rotanev-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Lightning Bangle of Porter' WHERE slug = 'lightning-bangle-of-porter' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Lightning of Rotanev' WHERE slug = 'lightning-of-rotanev' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Ordens Tear' WHERE slug = 'ordens-tear' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Ordens Tear (อีเวนต์)' WHERE slug = 'ordens-tear-event' AND name_th IS NULL;
UPDATE items SET name_th = 'พรอสเป เบรซเล็ตฟ้าผ่า Lightning Bangle' WHERE slug = 'prospe-lightning-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เวสปาโนลาขัดเงา เบรซเล็ตฟ้าผ่า Lightning Bangle' WHERE slug = 'refined-vespanola-lightning-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Sparkling Topaz' WHERE slug = 'sparkling-topaz' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เบรซเล็ตฟ้าผ่า of Lightning' WHERE slug = 'strata-devil-bracelet-of-lightning' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เบรซเล็ตฟ้าผ่า of Lightning (อีเวนต์)' WHERE slug = 'strata-devil-bracelet-of-lightning-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Tirlight' WHERE slug = 'tirlight-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตฟ้าผ่า Tourmaline of Dominance' WHERE slug = 'tourmaline-of-dominance' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา เบรซเล็ตฟ้าผ่า Lightning Bangle' WHERE slug = 'vespanola-pioneer-support-lightning-bangle' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] เอเน็กซ์ อีเธอเรียล เบรซเล็ตฟ้าผ่า Electric' WHERE slug = 'event-enex-ethereal-electric-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมิน Fluorite - Lumin (a days)' WHERE slug = 'fluorite-lumin-a-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมิน Jade - Lumin (a days)' WHERE slug = 'jade-lumin-a-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมิน Kunzite - Lumin (a days)' WHERE slug = 'kunzite-lumin-a-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูมิน Processed Lumin Catalyst' WHERE slug = 'processed-lumin-catalyst' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท Carnelian of Delight' WHERE slug = 'carnelian-of-delight' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท Chloes Melody' WHERE slug = 'chloes-melody' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท Chloes Melody (อีเวนต์)' WHERE slug = 'chloes-melody-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท Disdain of Spica' WHERE slug = 'disdain-of-spica' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท Disdain of Spica (อีเวนต์)' WHERE slug = 'disdain-of-spica-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท El Sumo Sacherdote' WHERE slug = 'el-sumo-sacherdote' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ลูท Arciliuto' WHERE slug = 'elite-arciliuto' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ลูท Criticism of Spica' WHERE slug = 'elite-criticism-of-spica' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ลูท Disdain of Spica (อีเวนต์)' WHERE slug = 'elite-disdain-of-spica-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ลูท El Sumo Sacherdote' WHERE slug = 'elite-el-sumo-sacherdote' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ลูท' WHERE slug = 'elite-lute' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ลูท Teorbe' WHERE slug = 'elite-teorbe' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท Incomplete Chloes Melody' WHERE slug = 'incomplete-chloes-melody' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท of Fortune' WHERE slug = 'lute-of-fortune' AND name_th IS NULL;
UPDATE items SET name_th = 'ลูท Wilight' WHERE slug = 'wilight-lute' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เมน-โกช' WHERE slug = 'elite-main-gauche' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เมน-โกช Poignard' WHERE slug = 'elite-poignard' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ10th Year Anniversary' WHERE slug = '10th-year-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ18th Anniversary' WHERE slug = '18th-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2017 Gold Hands' WHERE slug = '2017-gold-hands' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2017 Hot Summer' WHERE slug = '2017-hot-summer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2018 Hot Summer' WHERE slug = '2018-hot-summer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2019 Hot summer' WHERE slug = '2019-hot-summer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2020 Blessing of Christmas' WHERE slug = '2020-blessing-of-christmas' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2020 Hot Summer' WHERE slug = '2020-hot-summer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2021 Hot Summer' WHERE slug = '2021-hot-summer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2021 New Years Blessing' WHERE slug = '2021-new-years-blessing' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2022 Christmas Blessing' WHERE slug = '2022-christmas-blessing' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2022 New Years Blessing' WHERE slug = '2022-new-years-blessing' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2023 Happy New Year' WHERE slug = '2023-happy-new-year' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2024 Cool Summer (Steam)' WHERE slug = '2024-cool-summer-steam' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2024 Hot Summer(Steam)' WHERE slug = '2024-hot-summer-steam' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2025 Happy Halloween' WHERE slug = '2025-happy-halloween' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ2025 Winter Eve' WHERE slug = '2025-winter-eve' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ30 grade armor master' WHERE slug = '30-grade-armor-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ31 grade weapon master' WHERE slug = '31-grade-weapon-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ32 grade armor master' WHERE slug = '32-grade-armor-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ32 grade weapon master' WHERE slug = '32-grade-weapon-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ33 grade armor master' WHERE slug = '33-grade-armor-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ33 grade weapon master' WHERE slug = '33-grade-weapon-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ34 grade armor master' WHERE slug = '34-grade-armor-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ34 grade weapon master' WHERE slug = '34-grade-weapon-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ35 grade armor master' WHERE slug = '35-grade-armor-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ35 grade weapon master' WHERE slug = '35-grade-weapon-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ36 grade weapon master' WHERE slug = '36-grade-weapon-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ39등급 무기 장인' WHERE slug = '39' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ9th ridge' WHERE slug = '9th-ridge' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญA Rich Man' WHERE slug = 'a-rich-man' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญA large family' WHERE slug = 'a-large-family' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญA lazy afternoon of reading' WHERE slug = 'a-lazy-afternoon-of-reading' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAbsinian Warrior' WHERE slug = 'absinian-warrior' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAchieve_CHN_ItemName01' WHERE slug = 'achieve-chn-itemname01' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAchieve_CHN_ItemName02' WHERE slug = 'achieve-chn-itemname02' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAchieve_CHN_ItemName03' WHERE slug = 'achieve-chn-itemname03' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAchieve_CHN_ItemName04' WHERE slug = 'achieve-chn-itemname04' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAchieve_CHN_ItemName05' WHERE slug = 'achieve-chn-itemname05' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAchieve_CHN_ItemName06' WHERE slug = 'achieve-chn-itemname06' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAchievement Score Hunter' WHERE slug = 'achievement-score-hunter' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAffinity level max!' WHERE slug = 'affinity-level-max' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAlchemist of farm' WHERE slug = 'alchemist-of-farm' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAlways. Thank you.' WHERE slug = 'always-thank-you' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAn Avatar Born from the Ashes' WHERE slug = 'an-avatar-born-from-the-ashes' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAn opportunity that has returned!' WHERE slug = 'an-opportunity-that-has-returned' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAndre Boutique' WHERE slug = 'andre-boutique' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAndromida 3rd Anniversary' WHERE slug = 'andromida-3rd-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAndromida 3rd Anniversary (30 วัน)' WHERE slug = 'andromida-3rd-anniversary-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAndromida 3rd Grand Anniversary' WHERE slug = 'andromida-3rd-grand-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAndromida GE 1st Anniversary' WHERE slug = 'andromida-ge-1st-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAnywhere, anytime, with GE' WHERE slug = 'anywhere-anytime-with-ge' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญArmonia victorious Soldier' WHERE slug = 'armonia-victorious-soldier' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAstarte' WHERE slug = 'astarte' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAstrologer of Dongye Country' WHERE slug = 'astrologer-of-dongye-country' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAttempted to infillerate' WHERE slug = 'attempted-to-infillerate' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAttendance Check!' WHERE slug = 'attendance-check' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAutumn, Books, and Maple Leaves' WHERE slug = 'autumn-books-and-maple-leaves' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAvengers' WHERE slug = 'avengers' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญAvengers from Bristia' WHERE slug = 'avengers-from-bristia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBad Performance' WHERE slug = 'bad-performance' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBahia Mascot' WHERE slug = 'bahia-mascot' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBarbatos' WHERE slug = 'barbatos' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBat' WHERE slug = 'bat' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBeast Slayer' WHERE slug = 'beast-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBeautiful Language Signer' WHERE slug = 'beautiful-language-signer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBeekeeper' WHERE slug = 'beekeeper' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBeginner Miner' WHERE slug = 'beginner-miner' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBehemoths Wrath' WHERE slug = 'behemoths-wrath' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBeholder Slayer' WHERE slug = 'beholder-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBelt Crafting God' WHERE slug = 'belt-crafting-god' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBetrayer' WHERE slug = 'betrayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBiologist' WHERE slug = 'biologist' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlazing Ignis' WHERE slug = 'blazing-ignis' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessing of Archbishop' WHERE slug = 'blessing-of-archbishop' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessing of Christmas' WHERE slug = 'blessing-of-christmas' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessing of Goddess' WHERE slug = 'blessing-of-goddess' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessing of Halloween' WHERE slug = 'blessing-of-halloween' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessing of Sara' WHERE slug = 'blessing-of-sara' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessing of Tibar' WHERE slug = 'blessing-of-tibar' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessing of the Storm' WHERE slug = 'blessing-of-the-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessings of the 2025 New Year' WHERE slug = 'blessings-of-the-2025-new-year' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlessings of the 2026 New Year' WHERE slug = 'blessings-of-the-2026-new-year' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlood Storm of Battlefield' WHERE slug = 'blood-storm-of-battlefield' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBloody Navy' WHERE slug = 'bloody-navy' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBloody Sainquis' WHERE slug = 'bloody-sainquis' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlooming Daisy' WHERE slug = 'blooming-daisy' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlow~ spring breeze~' WHERE slug = 'blow-spring-breeze' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBlue Flame' WHERE slug = 'blue-flame' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBothered Renauld' WHERE slug = 'bothered-renauld' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBow to Me~' WHERE slug = 'bow-to-me' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBrand New World (30 วัน)' WHERE slug = 'brand-new-world-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBrash Chain Loser' WHERE slug = 'brash-chain-loser' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBrash Chain Victor' WHERE slug = 'brash-chain-victor' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBrave Blue Dragon' WHERE slug = 'brave-blue-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBristia Pioneer' WHERE slug = 'bristia-pioneer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBristian Sniper' WHERE slug = 'bristian-sniper' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBristias Guardian' WHERE slug = 'bristias-guardian' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBristias Resolution' WHERE slug = 'bristias-resolution' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBrothers and sisters, rise again...' WHERE slug = 'brothers-and-sisters-rise-again' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญBurlons Leader' WHERE slug = 'burlons-leader' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCalum Gradio' WHERE slug = 'calum-gradio' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCandy to My Ears' WHERE slug = 'candy-to-my-ears' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla Destroyer' WHERE slug = 'castilla-destroyer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla Handler' WHERE slug = 'castilla-handler' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla Hunter' WHERE slug = 'castilla-hunter' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla Troubleshooter' WHERE slug = 'castilla-troubleshooter' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, Mine Conqueror' WHERE slug = 'castilla-mine-conqueror' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, Mine Explorer' WHERE slug = 'castilla-mine-explorer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, Relic Conqueror' WHERE slug = 'castilla-relic-conqueror' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, Relic Explorer' WHERE slug = 'castilla-relic-explorer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, Ruins Conqueror' WHERE slug = 'castilla-ruins-conqueror' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, Ruins Explorer' WHERE slug = 'castilla-ruins-explorer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, Temple Conqueror' WHERE slug = 'castilla-temple-conqueror' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, Temple Explorer' WHERE slug = 'castilla-temple-explorer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, the Tower of Chaos Conqueror' WHERE slug = 'castilla-the-tower-of-chaos-conqueror' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastilla, the Tower of Chaos Explorer' WHERE slug = 'castilla-the-tower-of-chaos-explorer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCastle Student ID' WHERE slug = 'castle-student-id' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCats' WHERE slug = 'cats' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCerberus was frightened,' WHERE slug = 'cerberus-was-frightened' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Argus Slayer' WHERE slug = 'chaos-argus-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Arito Slayer' WHERE slug = 'chaos-arito-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Basilisk Slayer' WHERE slug = 'chaos-basilisk-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Chimera Slayer' WHERE slug = 'chaos-chimera-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Chrysalis Slayer' WHERE slug = 'chaos-chrysalis-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Dekaravia Slayer' WHERE slug = 'chaos-dekaravia-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Diablo Slayer' WHERE slug = 'chaos-diablo-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Dominator Slayer' WHERE slug = 'chaos-dominator-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Einschiever Slayer' WHERE slug = 'chaos-einschiever-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Elbrid Slayer' WHERE slug = 'chaos-elbrid-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Elnugad Slayer' WHERE slug = 'chaos-elnugad-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Hadeon Slayer' WHERE slug = 'chaos-hadeon-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Iron Ararat Slayer' WHERE slug = 'chaos-iron-ararat-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Lavaleaf Slayer' WHERE slug = 'chaos-lavaleaf-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Phobitan General Slayer' WHERE slug = 'chaos-phobitan-general-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Skeleton Slayer' WHERE slug = 'chaos-skeleton-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChaos Wetis Slayer' WHERE slug = 'chaos-wetis-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCharity Angel' WHERE slug = 'charity-angel' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChief Gladiator' WHERE slug = 'chief-gladiator' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChildhood Friend' WHERE slug = 'childhood-friend' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChristmas 2023' WHERE slug = 'christmas-2023' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChristmas Chef' WHERE slug = 'christmas-chef' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญChromster' WHERE slug = 'chromster' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCitizen of Illisia' WHERE slug = 'citizen-of-illisia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญClasse Alta' WHERE slug = 'classe-alta' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญClaws of Patrikyon' WHERE slug = 'claws-of-patrikyon' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCoffee is my Fuel!' WHERE slug = 'coffee-is-my-fuel' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญColony Conqueror' WHERE slug = 'colony-conqueror' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญColony Crusher' WHERE slug = 'colony-crusher' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCombatant' WHERE slug = 'combatant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญContractor' WHERE slug = 'contractor' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCook attached to Government General' WHERE slug = 'cook-attached-to-government-general' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCool Summer 2023' WHERE slug = 'cool-summer-2023' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCorrupted Star Messenger' WHERE slug = 'corrupted-star-messenger' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCosmic force is to me' WHERE slug = 'cosmic-force-is-to-me' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCould not be Defeated by the two prison officers,' WHERE slug = 'could-not-be-defeated-by-the-two-prison-officers' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCreate a troop' WHERE slug = 'create-a-troop' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCreator of miracles' WHERE slug = 'creator-of-miracles' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCrossed Destinies' WHERE slug = 'crossed-destinies' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCurse of Goddess' WHERE slug = 'curse-of-goddess' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญCurse of doll' WHERE slug = 'curse-of-doll' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDark Gemini Slayer' WHERE slug = 'dark-gemini-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDawn of Dongyeguk' WHERE slug = 'dawn-of-dongyeguk' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDeath Broker' WHERE slug = 'death-broker' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDeath-Breaker' WHERE slug = 'death-breaker' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDefeated Renauld' WHERE slug = 'defeated-renauld' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDefeated the cowards' WHERE slug = 'defeated-the-cowards' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDemon Slayer - Behemoth' WHERE slug = 'demon-slayer-behemoth' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDemon Slayer - Leviathan' WHERE slug = 'demon-slayer-leviathan' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDemon Slayer - Ziz' WHERE slug = 'demon-slayer-ziz' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDestroyed All Enemies' WHERE slug = 'destroyed-all-enemies' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDestroyed the impregnable defense,' WHERE slug = 'destroyed-the-impregnable-defense' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDeus Machina' WHERE slug = 'deus-machina' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDevilish Talent' WHERE slug = 'devilish-talent' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDevouring Beast' WHERE slug = 'devouring-beast' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDid not care about numerical inferiority,' WHERE slug = 'did-not-care-about-numerical-inferiority' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDid not receive any help from prisoners,' WHERE slug = 'did-not-receive-any-help-from-prisoners' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDionysus Apostle' WHERE slug = 'dionysus-apostle' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDo you want to know the future?' WHERE slug = 'do-you-want-to-know-the-future' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDoppelganger' WHERE slug = 'doppelganger' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDraconis' WHERE slug = 'draconis' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDragon Reincarnation Cycle' WHERE slug = 'dragon-reincarnation-cycle' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDrifter' WHERE slug = 'drifter' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDriller' WHERE slug = 'driller' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDrived the cowards out' WHERE slug = 'drived-the-cowards-out' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญDuadine' WHERE slug = 'duadine' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEarring Crafting God' WHERE slug = 'earring-crafting-god' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEffervescent Corpse' WHERE slug = 'effervescent-corpse' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEffervescent Loser' WHERE slug = 'effervescent-loser' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEffervescent Winner' WHERE slug = 'effervescent-winner' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEliminated the demons,' WHERE slug = 'eliminated-the-demons' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEmperor of Titles' WHERE slug = 'emperor-of-titles' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEnding of the year' WHERE slug = 'ending-of-the-year' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEndlessly Legendary' WHERE slug = 'endlessly-legendary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEsoterica of Valeron' WHERE slug = 'esoterica-of-valeron' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEveryone move! Im coming through~' WHERE slug = 'everyone-move-im-coming-through' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEveryone move! Im coming through~ (30 วัน)' WHERE slug = 'everyone-move-im-coming-through-30-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญExecutioner' WHERE slug = 'executioner' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญExpert Miner' WHERE slug = 'expert-miner' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญEyewitness' WHERE slug = 'eyewitness' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFaded Glyph' WHERE slug = 'faded-glyph' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFaith of Direwolf' WHERE slug = 'faith-of-direwolf' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFallen' WHERE slug = 'fallen' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFamiliar with Death' WHERE slug = 'familiar-with-death' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFeeling bored of 10 mins' WHERE slug = 'feeling-bored-of-10-mins' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFestina Lente' WHERE slug = 'festina-lente' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFiesta' WHERE slug = 'fiesta' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFighter for National Independence of Bristia' WHERE slug = 'fighter-for-national-independence-of-bristia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFlag of Pioneering' WHERE slug = 'flag-of-pioneering' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFlawless Victory' WHERE slug = 'flawless-victory' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFood researcher' WHERE slug = 'food-researcher' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFooled by Lyndon' WHERE slug = 'fooled-by-lyndon' AND name_th IS NULL;
UPDATE items SET name_th = 'ตราForbidden' WHERE slug = 'forbidden-seal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFormer Leader of WCC' WHERE slug = 'former-leader-of-wcc' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFought with Elite soldiers,' WHERE slug = 'fought-with-elite-soldiers' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFriend of Wraith' WHERE slug = 'friend-of-wraith' AND name_th IS NULL;
UPDATE items SET name_th = 'มงกุฎFrost' WHERE slug = 'frost-crown' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFrozen Forever' WHERE slug = 'frozen-forever' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญFull moon' WHERE slug = 'full-moon' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGE 8 Years Anniversary!' WHERE slug = 'ge-8-years-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGE 9 Years Anniversary' WHERE slug = 'ge-9-years-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGE is a BGM paradise!' WHERE slug = 'ge-is-a-bgm-paradise' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGP Keeper' WHERE slug = 'gp-keeper' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGP Overlord' WHERE slug = 'gp-overlord' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGP Pioneer' WHERE slug = 'gp-pioneer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGP Seven Nobles' WHERE slug = 'gp-seven-nobles' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGleichstellung' WHERE slug = 'gleichstellung' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGleichstellung Soldier' WHERE slug = 'gleichstellung-soldier' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGlove Crafting God' WHERE slug = 'glove-crafting-god' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGold Bat' WHERE slug = 'gold-bat' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGold Hands' WHERE slug = 'gold-hands' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGolem Slayer' WHERE slug = 'golem-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGood Job!' WHERE slug = 'good-job' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGranado Espada 9 Years Anniversary' WHERE slug = 'granado-espada-9-years-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGrand Master' WHERE slug = 'grand-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGrate Lord' WHERE slug = 'grate-lord' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGrief Slayer' WHERE slug = 'grief-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGuardian' WHERE slug = 'guardian' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGuardian of Evora' WHERE slug = 'guardian-of-evora' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGuardian of Patrikyon' WHERE slug = 'guardian-of-patrikyon' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGuardian of Remembrance' WHERE slug = 'guardian-of-remembrance' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญGuardian of the Festival' WHERE slug = 'guardian-of-the-festival' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHalf-Decayed' WHERE slug = 'half-decayed' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHalloween 2022' WHERE slug = 'halloween-2022' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHand of Life' WHERE slug = 'hand-of-life' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHappy Halloween' WHERE slug = 'happy-halloween' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHappy Miracle Winter' WHERE slug = 'happy-miracle-winter' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHe is back.' WHERE slug = 'he-is-back' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHealing Master' WHERE slug = 'healing-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHold Pickaxe' WHERE slug = 'hold-pickaxe' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHonorable Baselrane' WHERE slug = 'honorable-baselrane' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHonorary Ailys Investigator' WHERE slug = 'honorary-ailys-investigator' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHonorary Crusader' WHERE slug = 'honorary-crusader' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHonorary Teacher' WHERE slug = 'honorary-teacher' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHopeful Renaissance' WHERE slug = 'hopeful-renaissance' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHot Summer' WHERE slug = 'hot-summer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHot Summer 2022' WHERE slug = 'hot-summer-2022' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHot Summer 2023' WHERE slug = 'hot-summer-2023' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHowls from Gehenna' WHERE slug = 'howls-from-gehenna' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHuman Slayer' WHERE slug = 'human-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHuman weed whacker' WHERE slug = 'human-weed-whacker' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHumanity zero' WHERE slug = 'humanity-zero' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญHydro Bomber Slayer' WHERE slug = 'hydro-bomber-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญI didnt expect that..' WHERE slug = 'i-didnt-expect-that' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญI havent been charged with a crime yet' WHERE slug = 'i-havent-been-charged-with-a-crime-yet' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญI will protect the familys peace!' WHERE slug = 'i-will-protect-the-familys-peace' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญI wont forgive you in the name of Candy!' WHERE slug = 'i-wont-forgive-you-in-the-name-of-candy' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญIdea Bank' WHERE slug = 'idea-bank' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญIll sweep them all away!' WHERE slug = 'ill-sweep-them-all-away' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญIllier Hero Medal for National Salvation' WHERE slug = 'illier-hero-medal-for-national-salvation' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญIllier royal cook' WHERE slug = 'illier-royal-cook' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญIm Flying!' WHERE slug = 'im-flying' AND name_th IS NULL;