-- Migration 069: Thai names remaining v2 batch 6/9
-- Generated: 2026-03-16T03:55:14.475Z

UPDATE items SET name_th = 'เหรียญIm already dead' WHERE slug = 'im-already-dead' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญImmortal' WHERE slug = 'immortal' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญImmortal Old Soldier' WHERE slug = 'immortal-old-soldier' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญImperial Alchemy' WHERE slug = 'imperial-alchemy' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญInfinite Master' WHERE slug = 'infinite-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญInsert Master' WHERE slug = 'insert-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญInstall fish trap manual' WHERE slug = 'install-fish-trap-manual' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญInvariant' WHERE slug = 'invariant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญIs it my turn now?' WHERE slug = 'is-it-my-turn-now' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญIt’s already been 19 years.' WHERE slug = 'it-s-already-been-19-years' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญJelly Fish Slayer' WHERE slug = 'jelly-fish-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญJudge, I still...' WHERE slug = 'judge-i-still' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญJustice and Glory' WHERE slug = 'justice-and-glory' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKilled Enemy General' WHERE slug = 'killed-enemy-general' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKiller' WHERE slug = 'killer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKiller Instinct' WHERE slug = 'killer-instinct' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKiller of the Ten Nobles' WHERE slug = 'killer-of-the-ten-nobles' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKing Henry Slayer' WHERE slug = 'king-henry-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKing of Assassins' WHERE slug = 'king-of-assassins' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKing of Defeat' WHERE slug = 'king-of-defeat' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKing of Greed' WHERE slug = 'king-of-greed' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKing of Mining' WHERE slug = 'king-of-mining' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKing of Resurrection' WHERE slug = 'king-of-resurrection' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKing of Titles' WHERE slug = 'king-of-titles' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKing of Victory' WHERE slug = 'king-of-victory' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKitchen of Fire' WHERE slug = 'kitchen-of-fire' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญKnight of Londinium' WHERE slug = 'knight-of-londinium' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLate Autumn Archives' WHERE slug = 'late-autumn-archives' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLealtad' WHERE slug = 'lealtad' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLealtad Soldier' WHERE slug = 'lealtad-soldier' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLegend hunter' WHERE slug = 'legend-hunter' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLegendary Assassin' WHERE slug = 'legendary-assassin' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLegends Never Die' WHERE slug = 'legends-never-die' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLegion Special Force' WHERE slug = 'legion-special-force' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLeviathans Ire' WHERE slug = 'leviathans-ire' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLife and Death' WHERE slug = 'life-and-death' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLight Gemini Slayer' WHERE slug = 'light-gemini-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLoading images winners' WHERE slug = 'loading-images-winners' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLook at enhancement merchant' WHERE slug = 'look-at-enhancement-merchant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLorenzas Lover' WHERE slug = 'lorenzas-lover' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLosing Streak' WHERE slug = 'losing-streak' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLove and Resentment' WHERE slug = 'love-and-resentment' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLove is in the air 2025 Christmas' WHERE slug = 'love-is-in-the-air-2025-christmas' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLovely Angel' WHERE slug = 'lovely-angel' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLover of Pickaxe' WHERE slug = 'lover-of-pickaxe' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLucias Appreciation Plaque' WHERE slug = 'lucias-appreciation-plaque' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLucid Multi-color Necklace' WHERE slug = 'lucid-multi-color-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLuck of Battlefield' WHERE slug = 'luck-of-battlefield' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญLucky Man' WHERE slug = 'lucky-man' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMagnificent Contributor' WHERE slug = 'magnificent-contributor' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญManager' WHERE slug = 'manager' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMaster Combatant' WHERE slug = 'master-combatant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMaster Doctor' WHERE slug = 'master-doctor' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMaster of 37 grade weapons' WHERE slug = 'master-of-37-grade-weapons' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMaster of Everyone' WHERE slug = 'master-of-everyone' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMaster of harvest' WHERE slug = 'master-of-harvest' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMaster of the Abyss' WHERE slug = 'master-of-the-abyss' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งArtisan' WHERE slug = 'medal-of-artisan' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งBravery' WHERE slug = 'medal-of-bravery' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งGoddess' WHERE slug = 'medal-of-goddess' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งHonor' WHERE slug = 'medal-of-honor' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งOverlord' WHERE slug = 'medal-of-overlord' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งStorm' WHERE slug = 'medal-of-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งVictory' WHERE slug = 'medal-of-victory' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งWiseman' WHERE slug = 'medal-of-wiseman' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญแห่งYggdrasil' WHERE slug = 'medal-of-yggdrasil' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMedic' WHERE slug = 'medic' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMedical License' WHERE slug = 'medical-license' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMedusa Slayer' WHERE slug = 'medusa-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMilitary Cadet' WHERE slug = 'military-cadet' AND name_th IS NULL;
UPDATE items SET name_th = 'มงกุฎMini Game Triple' WHERE slug = 'mini-game-triple-crown' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMining Master' WHERE slug = 'mining-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMiracle Winter' WHERE slug = 'miracle-winter' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMiracle of Christmas' WHERE slug = 'miracle-of-christmas' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMiracle of New Year' WHERE slug = 'miracle-of-new-year' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 1 VIP' WHERE slug = 'mission-rank-1-vip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 1 VVIP' WHERE slug = 'mission-rank-1-vvip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 2 VIP' WHERE slug = 'mission-rank-2-vip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 2 VVIP' WHERE slug = 'mission-rank-2-vvip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 3 VIP' WHERE slug = 'mission-rank-3-vip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 3 VVIP' WHERE slug = 'mission-rank-3-vvip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 4 VIP' WHERE slug = 'mission-rank-4-vip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 4 VVIP' WHERE slug = 'mission-rank-4-vvip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 5 VIP' WHERE slug = 'mission-rank-5-vip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 5 VVIP' WHERE slug = 'mission-rank-5-vvip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 6 VIP' WHERE slug = 'mission-rank-6-vip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 6 VVIP' WHERE slug = 'mission-rank-6-vvip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 7 VIP' WHERE slug = 'mission-rank-7-vip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMission Rank 7 VVIP' WHERE slug = 'mission-rank-7-vvip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญModel Citizen of Illisia' WHERE slug = 'model-citizen-of-illisia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMoonlight' WHERE slug = 'moonlight' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMoonlit Chill' WHERE slug = 'moonlit-chill' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMother of Invention' WHERE slug = 'mother-of-invention' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญMother of Resurrection' WHERE slug = 'mother-of-resurrection' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNavas Kiss' WHERE slug = 'navas-kiss' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNecklace Crafting God' WHERE slug = 'necklace-crafting-god' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNew Destiny' WHERE slug = 'new-destiny' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNew Year Blessing' WHERE slug = 'new-year-blessing' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNew pioneer' WHERE slug = 'new-pioneer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNew student' WHERE slug = 'new-student' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNine Tails' WHERE slug = 'nine-tails' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNo way..' WHERE slug = 'no-way' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNo. 1 Fallen' WHERE slug = 'no-1-fallen' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNobility' WHERE slug = 'nobility' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNoblesse' WHERE slug = 'noblesse' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNoemis Lover' WHERE slug = 'noemis-lover' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNot affected by the poison gas' WHERE slug = 'not-affected-by-the-poison-gas' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNot breathing' WHERE slug = 'not-breathing' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNovice' WHERE slug = 'novice' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญNow loading..' WHERE slug = 'now-loading' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญObserver of the World' WHERE slug = 'observer-of-the-world' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญOh dear, careful or youll get sand in your eyes.' WHERE slug = 'oh-dear-careful-or-youll-get-sand-in-your-eyes' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญOne who endured burning heat' WHERE slug = 'one-who-endured-burning-heat' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญOne who listens to voice of forest' WHERE slug = 'one-who-listens-to-voice-of-forest' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญOne who woke up from a long sleep' WHERE slug = 'one-who-woke-up-from-a-long-sleep' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญOre Refining Master' WHERE slug = 'ore-refining-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญOutlaw of the Ocean' WHERE slug = 'outlaw-of-the-ocean' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญOvercame numerical inferiority,' WHERE slug = 'overcame-numerical-inferiority' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPVP Single Match Ranker' WHERE slug = 'pvp-single-match-ranker' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPVP Team Match Ranker' WHERE slug = 'pvp-team-match-ranker' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPandaemonium' WHERE slug = 'pandaemonium' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPassionate Pioneer' WHERE slug = 'passionate-pioneer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPatient Betrayer' WHERE slug = 'patient-betrayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPavluchenk Sister' WHERE slug = 'pavluchenk-sister' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPegadilla' WHERE slug = 'pegadilla' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPioneer Crossing the Galaxy' WHERE slug = 'pioneer-crossing-the-galaxy' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPioneer of Stars' WHERE slug = 'pioneer-of-stars' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPioneering Legend' WHERE slug = 'pioneering-legend' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPioneering Supporters' WHERE slug = 'pioneering-supporters' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPlease dont forgive me' WHERE slug = 'please-dont-forgive-me' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPlenty of pluck' WHERE slug = 'plenty-of-pluck' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญProof of Elite Trooper' WHERE slug = 'proof-of-elite-trooper' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญProof of Mercenary' WHERE slug = 'proof-of-mercenary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญPure Lamb' WHERE slug = 'pure-lamb' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญQueen of Valkyries Slayer' WHERE slug = 'queen-of-valkyries-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRank 1 Grand Master' WHERE slug = 'rank-1-grand-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRank 2 Grand Master' WHERE slug = 'rank-2-grand-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRank 3 Grand Master' WHERE slug = 'rank-3-grand-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRank 4 Grand Master' WHERE slug = 'rank-4-grand-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRank 5 Grand Master' WHERE slug = 'rank-5-grand-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRank 6 Grand Master' WHERE slug = 'rank-6-grand-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRank 7 Grand Master' WHERE slug = 'rank-7-grand-master' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRank8 그랜드 마스터' WHERE slug = 'rank8' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRecruiting Faction Members!' WHERE slug = 'recruiting-faction-members' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRenaulds Lover' WHERE slug = 'renaulds-lover' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRich' WHERE slug = 'rich' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRitual Brand' WHERE slug = 'ritual-brand' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRookie Assassin' WHERE slug = 'rookie-assassin' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRookie Combatant' WHERE slug = 'rookie-combatant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRookie Killer' WHERE slug = 'rookie-killer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRookie Solider' WHERE slug = 'rookie-solider' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRookie Therapist' WHERE slug = 'rookie-therapist' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญRoyal Pioneer' WHERE slug = 'royal-pioneer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSamhains Fire' WHERE slug = 'samhains-fire' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSands of Guilt' WHERE slug = 'sands-of-guilt' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSavoring the Victory' WHERE slug = 'savoring-the-victory' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSaw demon' WHERE slug = 'saw-demon' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญScent of Fall' WHERE slug = 'scent-of-fall' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSearching for a Faction!' WHERE slug = 'searching-for-a-faction' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSecured time' WHERE slug = 'secured-time' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSee the end of enhancement' WHERE slug = 'see-the-end-of-enhancement' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSeer of Souls' WHERE slug = 'seer-of-souls' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSerial Driller' WHERE slug = 'serial-driller' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญServer Beta Tester' WHERE slug = 'server-beta-tester' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญServer launch Participant' WHERE slug = 'server-launch-participant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญShadow Javelin' WHERE slug = 'shadow-javelin' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญShadowed Rune' WHERE slug = 'shadowed-rune' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญShall we start hunting?' WHERE slug = 'shall-we-start-hunting' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSharp Blue Serpent' WHERE slug = 'sharp-blue-serpent' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญShoe Crafting God' WHERE slug = 'shoe-crafting-god' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSiblings' WHERE slug = 'siblings' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSlayer' WHERE slug = 'slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSnipers Revenge' WHERE slug = 'snipers-revenge' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSocket God' WHERE slug = 'socket-god' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSoul Devastator' WHERE slug = 'soul-devastator' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSoul Mate' WHERE slug = 'soul-mate' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSpirit of Arsene' WHERE slug = 'spirit-of-arsene' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSplit Fate' WHERE slug = 'split-fate' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSprit Of Artist' WHERE slug = 'sprit-of-artist' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStand your ground.' WHERE slug = 'stand-your-ground' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStaring at Chat' WHERE slug = 'staring-at-chat' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStars Guardian' WHERE slug = 'stars-guardian' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStars Judge' WHERE slug = 'stars-judge' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStars Messenger' WHERE slug = 'stars-messenger' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStars Pioneer' WHERE slug = 'stars-pioneer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStars Surveillant' WHERE slug = 'stars-surveillant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStorm of Battlefield' WHERE slug = 'storm-of-battlefield' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStrataombre' WHERE slug = 'strataombre' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStrong Blue Dragon' WHERE slug = 'strong-blue-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStrong Coward' WHERE slug = 'strong-coward' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStronger Than You' WHERE slug = 'stronger-than-you' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStudent Council' WHERE slug = 'student-council' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญStudent Council.' WHERE slug = 'student-council' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSucceeded in infiltration' WHERE slug = 'succeeded-in-infiltration' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSuccessor of Valeron' WHERE slug = 'successor-of-valeron' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSuperstition of the number 9' WHERE slug = 'superstition-of-the-number-9' AND name_th IS NULL;
UPDATE items SET name_th = 'ดาวSurveillant of' WHERE slug = 'surveillant-of-star' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญSymponia' WHERE slug = 'symponia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTarrified military dogs,' WHERE slug = 'tarrified-military-dogs' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTasted Victory' WHERE slug = 'tasted-victory' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTeacher!' WHERE slug = 'teacher' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTempest Slayer' WHERE slug = 'tempest-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTen Nobles of Vespanola' WHERE slug = 'ten-nobles-of-vespanola' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTenacious Man' WHERE slug = 'tenacious-man' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTesla Coil Slayer' WHERE slug = 'tesla-coil-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTetra Pod Slayer' WHERE slug = 'tetra-pod-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThank you. We wont forget.' WHERE slug = 'thank-you-we-wont-forget' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Best Storyteller of GE Radio' WHERE slug = 'the-best-storyteller-of-ge-radio' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Distorted' WHERE slug = 'the-distorted' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Endurance of Arsene' WHERE slug = 'the-endurance-of-arsene' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Endurance of King of Greed' WHERE slug = 'the-endurance-of-king-of-greed' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Endurance of Oscuras' WHERE slug = 'the-endurance-of-oscuras' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Endurance of Tempest' WHERE slug = 'the-endurance-of-tempest' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe First GCC Champion' WHERE slug = 'the-first-gcc-champion' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe First GCC Second place' WHERE slug = 'the-first-gcc-second-place' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Hilt of Apostadero' WHERE slug = 'the-hilt-of-apostadero' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Hilt of Arsene' WHERE slug = 'the-hilt-of-arsene' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Hilt of Bahama' WHERE slug = 'the-hilt-of-bahama' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Hilt of Illisia' WHERE slug = 'the-hilt-of-illisia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Hilt of Lucifer Castle' WHERE slug = 'the-hilt-of-lucifer-castle' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Hilt of Quiritatio' WHERE slug = 'the-hilt-of-quiritatio' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Hilt of Torsches Mansion' WHERE slug = 'the-hilt-of-torsches-mansion' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Hilt of Zeia' WHERE slug = 'the-hilt-of-zeia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Legend' WHERE slug = 'the-legend' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Persistent Blue Snake' WHERE slug = 'the-persistent-blue-snake' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Socializer' WHERE slug = 'the-socializer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Star of the Ball' WHERE slug = 'the-star-of-the-ball' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Sweet Responsibility of This Area' WHERE slug = 'the-sweet-responsibility-of-this-area' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Void' WHERE slug = 'the-void' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe Wise Blue Snake' WHERE slug = 'the-wise-blue-snake' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe one who know the feeling of fishing' WHERE slug = 'the-one-who-know-the-feeling-of-fishing' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThe trick is that there is no trick' WHERE slug = 'the-trick-is-that-there-is-no-trick' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThey are Gods: Athena' WHERE slug = 'they-are-gods-athena' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThey are Gods: Tea Party' WHERE slug = 'they-are-gods-tea-party' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThis is nothing! Its a piece of cake!' WHERE slug = 'this-is-nothing-its-a-piece-of-cake' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญThis is the end' WHERE slug = 'this-is-the-end' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTime Paradox Finisher' WHERE slug = 'time-paradox-finisher' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTime and Budget' WHERE slug = 'time-and-budget' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTogether with Lyndon for the anniversary' WHERE slug = 'together-with-lyndon-for-the-anniversary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTop. 10 Fallen' WHERE slug = 'top-10-fallen' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTraveler from Calming Shore' WHERE slug = 'traveler-from-calming-shore' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTraveler from Lion City' WHERE slug = 'traveler-from-lion-city' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTrick or Treat' WHERE slug = 'trick-or-treat' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTrickster' WHERE slug = 'trickster' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTriumph Warrior in Distorted Armonia' WHERE slug = 'triumph-warrior-in-distorted-armonia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTwinkled brightly' WHERE slug = 'twinkled-brightly' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญTwo-Faced' WHERE slug = 'two-faced' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญUltimate' WHERE slug = 'ultimate' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญUltimate Demon Slayer' WHERE slug = 'ultimate-demon-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญUndead' WHERE slug = 'undead' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญUndead Researcher' WHERE slug = 'undead-researcher' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญUndead Slayer' WHERE slug = 'undead-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญUnrivalled Legend' WHERE slug = 'unrivalled-legend' AND name_th IS NULL;
UPDATE items SET name_th = 'ปีกValkyries' WHERE slug = 'valkyries-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVanished the demons,' WHERE slug = 'vanished-the-demons' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVespanola Navy Medal of Bravery' WHERE slug = 'vespanola-navy-medal-of-bravery' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVespanola royal cook' WHERE slug = 'vespanola-royal-cook' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVeteran' WHERE slug = 'veteran' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVeteran Combatant' WHERE slug = 'veteran-combatant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVeteran Doctor' WHERE slug = 'veteran-doctor' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVeteran Soldier' WHERE slug = 'veteran-soldier' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVirtue of Eucleia' WHERE slug = 'virtue-of-eucleia' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVismaker' WHERE slug = 'vismaker' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญVolunteer' WHERE slug = 'volunteer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWCC Japan Team' WHERE slug = 'wcc-japan-team' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWCC Korean Team' WHERE slug = 'wcc-korean-team' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWalking Dictionary' WHERE slug = 'walking-dictionary' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWalking into the World' WHERE slug = 'walking-into-the-world' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWar Contributor' WHERE slug = 'war-contributor' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWar Ender' WHERE slug = 'war-ender' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWar Hero' WHERE slug = 'war-hero' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWar Onlooker' WHERE slug = 'war-onlooker' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWar Participant' WHERE slug = 'war-participant' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWar Veteran' WHERE slug = 'war-veteran' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWhat you see isnt everything' WHERE slug = 'what-you-see-isnt-everything' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWhats scarier than a ghost~?' WHERE slug = 'whats-scarier-than-a-ghost' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWhere could they be hiding~?' WHERE slug = 'where-could-they-be-hiding' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWhite Winter' WHERE slug = 'white-winter' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWhite day' WHERE slug = 'white-day' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWhite hair and white hair' WHERE slug = 'white-hair-and-white-hair' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWiki Guider' WHERE slug = 'wiki-guider' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWinged Shoes' WHERE slug = 'winged-shoes' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWings of Evora' WHERE slug = 'wings-of-evora' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWinning Streak' WHERE slug = 'winning-streak' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWith a Cool Mind' WHERE slug = 'with-a-cool-mind' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWorld Food Day' WHERE slug = 'world-food-day' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWorld PVP Empire Knight' WHERE slug = 'world-pvp-empire-knight' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWorld PVP Kingdom Knight' WHERE slug = 'world-pvp-kingdom-knight' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWorld PVP Knight Captain' WHERE slug = 'world-pvp-knight-captain' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWorld PVP Rank 1' WHERE slug = 'world-pvp-rank-1' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWow~ Its Summer!' WHERE slug = 'wow-its-summer' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWraith' WHERE slug = 'wraith' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญWraith Proxy' WHERE slug = 'wraith-proxy' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญXanxus Lover' WHERE slug = 'xanxus-lover' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญYear of the Snake, Resolutions are good for three days' WHERE slug = 'year-of-the-snake-resolutions-are-good-for-three-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญYou already dead' WHERE slug = 'you-already-dead' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญYou are alive already' WHERE slug = 'you-are-alive-already' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญYou must give the order' WHERE slug = 'you-must-give-the-order' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญYou were brave' WHERE slug = 'you-were-brave' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญZero Victory' WHERE slug = 'zero-victory' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญZizs Wrath' WHERE slug = 'zizs-wrath' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญoh dear.' WHERE slug = 'oh-dear' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญshOixiOhs' WHERE slug = 'shoixiohs' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ나는 개척가문을 믿어~' WHERE slug = 'null' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ나크리아의 칼자루' WHERE slug = 'null' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ내 마음을 받아줘!' WHERE slug = 'null' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ미션 Rank8 VIP' WHERE slug = 'rank8-vip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ미션 Rank8 VVIP' WHERE slug = 'rank8-vvip' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ베스트 드레서' WHERE slug = 'null' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ스포트라이트' WHERE slug = 'null' AND name_th IS NULL;
UPDATE items SET name_th = 'เหรียญ위대한 이야기 작가' WHERE slug = 'null' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Amoladera Chain Mail' WHERE slug = 'amoladera-chain-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Amoladera Scale Armor' WHERE slug = 'amoladera-scale-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Amoladera Splint Mail' WHERE slug = 'amoladera-splint-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Armor of the Pirate' WHERE slug = 'armor-of-the-pirate' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Armure Diabolique -' WHERE slug = 'armure-diabolique-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Armure Diabolique - (อีเวนต์)' WHERE slug = 'armure-diabolique-metal-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Armure Diabolique of Behemoth -' WHERE slug = 'armure-diabolique-of-behemoth-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Armure Diabolique of Behemoth - (อีเวนต์)' WHERE slug = 'armure-diabolique-of-behemoth-metal-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Astartes' WHERE slug = 'astartes-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Breast Plate of Idge' WHERE slug = 'breast-plate-of-idge' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Chain Mail' WHERE slug = 'chain-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Consolidar Chain Mail' WHERE slug = 'consolidar-chain-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Consolidar Scale Armor' WHERE slug = 'consolidar-scale-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Consolidar Splint Mail' WHERE slug = 'consolidar-splint-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ เกราะโลหะ Le Blanc Plate' WHERE slug = 'divine-le-blanc-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะโลหะ Chain Mail' WHERE slug = 'elite-chain-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะโลหะ General Plate' WHERE slug = 'elite-general-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะโลหะ Metallic Suit' WHERE slug = 'elite-metallic-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะโลหะ Plate' WHERE slug = 'elite-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะโลหะ Scale Armor' WHERE slug = 'elite-scale-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะโลหะ Schvarlier Armor' WHERE slug = 'elite-schvarlier-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เกราะโลหะ Schvarlier Armor (อีเวนต์)' WHERE slug = 'elite-schvarlier-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Enhanced Breast Plate of Idge' WHERE slug = 'enhanced-breast-plate-of-idge' AND name_th IS NULL;
UPDATE items SET name_th = 'อีวิล เกราะโลหะ Plate' WHERE slug = 'evil-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Fate of Castilla' WHERE slug = 'fate-of-castilla' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Fate of Castilla (อีเวนต์)' WHERE slug = 'fate-of-castilla-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Field Plate Mail' WHERE slug = 'field-plate-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Frontier Croma(Plate mail)' WHERE slug = 'frontier-croma-plate-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Full-plate Mail' WHERE slug = 'full-plate-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ General Plate' WHERE slug = 'general-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ General Plate (อีเวนต์)' WHERE slug = 'general-plate-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Knight of the Templar' WHERE slug = 'knight-of-the-templar' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Le Scarce Plate' WHERE slug = 'le-scarce-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Legacy - Royal' WHERE slug = 'legacy-royal-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Light Demons Armure Diabolique -' WHERE slug = 'light-demons-armure-diabolique-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Light Demons Armure Diabolique - (อีเวนต์)' WHERE slug = 'light-demons-armure-diabolique-metal-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Metallic Suit' WHERE slug = 'metallic-suit' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Metallic Suit of Cinderella' WHERE slug = 'metallic-suit-of-cinderella' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Metallic Suit of Cinderella (60 วัน)' WHERE slug = 'metallic-suit-of-cinderella-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ เกราะโลหะ Noir Plate' WHERE slug = 'ogre-noir-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Old Fate of Castilla' WHERE slug = 'old-fate-of-castilla' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Old General Plate' WHERE slug = 'old-general-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Old Santuario' WHERE slug = 'old-santuario-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Old Strata Devil Plate' WHERE slug = 'old-strata-devil-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Pioneer Combat' WHERE slug = 'pioneer-combat-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Pioneer' WHERE slug = 'pioneer-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Pioneer Mystic' WHERE slug = 'pioneer-mystic-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Pioneer Reinforced' WHERE slug = 'pioneer-reinforced-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Plate Mail' WHERE slug = 'plate-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Plate of Contract (7 วัน)' WHERE slug = 'plate-of-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Plate of Predge' WHERE slug = 'plate-of-predge' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Prototype of Idge' WHERE slug = 'prototype-of-idge' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Red Serpent Plate' WHERE slug = 'red-serpent-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'ราชวงศ์ เกราะโลหะ' WHERE slug = 'royal-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Santuario' WHERE slug = 'santuario-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Santuario (อีเวนต์)' WHERE slug = 'santuario-metal-armor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Scale Armor' WHERE slug = 'scale-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Schvarlier Armor' WHERE slug = 'schvarlier-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Schvarlier Armor of Cinderella' WHERE slug = 'schvarlier-armor-of-cinderella' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Schvarlier Armor of Cinderella (60 วัน)' WHERE slug = 'schvarlier-armor-of-cinderella-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Second type of Idge' WHERE slug = 'second-type-of-idge' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Splint Mail' WHERE slug = 'splint-mail' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เกราะโลหะ Plate' WHERE slug = 'strata-devil-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เกราะโลหะ Plate (อีเวนต์)' WHERE slug = 'strata-devil-plate-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Supreme Dignite Plate' WHERE slug = 'supreme-dignite-plate' AND name_th IS NULL;
UPDATE items SET name_th = 'เกราะโลหะ Third type of Idge' WHERE slug = 'third-type-of-idge' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ราชวงศ์ เกราะโลหะ' WHERE slug = 'event-royal-metal-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ +10 Beliths Necklace in Chaos (1 วัน)' WHERE slug = '10-beliths-necklace-in-chaos-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ +10 Evils Brooch (1 วัน)' WHERE slug = '10-evils-brooch-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ +10 Stars Surveillants (1 วัน)' WHERE slug = '10-stars-surveillants-necklace-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Beliths Necklace in Chaos' WHERE slug = 'beliths-necklace-in-chaos' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Crafted Necklace of Resistance to Attribute' WHERE slug = 'crafted-necklace-of-resistance-to-attribute' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Crafted Necklace of Resistance to Attribute (อีเวนต์)' WHERE slug = 'crafted-necklace-of-resistance-to-attribute-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Crafted Physical RES' WHERE slug = 'crafted-physical-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Crafted Physical RES (อีเวนต์)' WHERE slug = 'crafted-physical-res-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Crafted Shot RES' WHERE slug = 'crafted-shot-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Crafted Shot RES (อีเวนต์)' WHERE slug = 'crafted-shot-res-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Created Necklace of Resistance to Attribute' WHERE slug = 'created-necklace-of-resistance-to-attribute' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Created Physical RES' WHERE slug = 'created-physical-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Created Shot RES' WHERE slug = 'created-shot-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Cut Necklace of Resistance to Attribute' WHERE slug = 'cut-necklace-of-resistance-to-attribute' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Cut Physical RES' WHERE slug = 'cut-physical-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Cut Shot RES' WHERE slug = 'cut-shot-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Desapio' WHERE slug = 'desapio-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Enhanced Necklace of Resistance to Attribute' WHERE slug = 'enhanced-necklace-of-resistance-to-attribute' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Enhanced Physical RES' WHERE slug = 'enhanced-physical-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Enhanced Shot RES' WHERE slug = 'enhanced-shot-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Evils Brooch' WHERE slug = 'evils-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Evils Brooch (ภาพลวง)' WHERE slug = 'evils-brooch-illusion' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Giltines Demonic' WHERE slug = 'giltines-demonic-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Laimas Holy' WHERE slug = 'laimas-holy-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Muertuos' WHERE slug = 'muertuos-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ by Contract (7 วัน)' WHERE slug = 'necklace-by-contract-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ of Resistance to Attribute' WHERE slug = 'necklace-of-resistance-to-attribute' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ of Wise man' WHERE slug = 'necklace-of-wise-man' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Physical RES' WHERE slug = 'physical-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Quiritatio Pledge' WHERE slug = 'quiritatio-pledge-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Revenants Ominous' WHERE slug = 'revenants-ominous-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Sheols Necklace in Chaos (ภาพลวง)' WHERE slug = 'sheols-necklace-in-chaos-illusion' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Shot RES' WHERE slug = 'shot-res-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Stars Surveillants' WHERE slug = 'stars-surveillants-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Stars Surveillants (อีเวนต์)' WHERE slug = 'stars-surveillants-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Vigilar Tribes' WHERE slug = 'vigilar-tribes-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Vigilar Tribes (อีเวนต์)' WHERE slug = 'vigilar-tribes-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Zodiac' WHERE slug = 'zodiac-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ Zodiac (อีเวนต์)' WHERE slug = 'zodiac-necklace-event' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] สร้อยคอ Evils Brooch' WHERE slug = 'dreaming-evils-brooch' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] สร้อยคอ Sheols' WHERE slug = 'dreaming-sheols-necklace' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] สร้อยคอ Giltines Demonic' WHERE slug = 'event-giltines-demonic-necklace' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] สร้อยคอ Laimas Holy' WHERE slug = 'event-laimas-holy-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ [Lucid] Evils Brooch' WHERE slug = 'lucid-evils-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ [Lucid] Sheols' WHERE slug = 'lucid-sheols-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ [Reverie] Evils Brooch' WHERE slug = 'reverie-evils-brooch' AND name_th IS NULL;
UPDATE items SET name_th = 'สร้อยคอ [Reverie] Sheols' WHERE slug = 'reverie-sheols-necklace' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Bronze' WHERE slug = 'bronze-pendant' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Charlottes Faith' WHERE slug = 'charlottes-faith' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Charlottes Faith (อีเวนต์)' WHERE slug = 'charlottes-faith-event' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Elegant' WHERE slug = 'elegant-pendant' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Heavenly Locket' WHERE slug = 'heavenly-locket' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Heavenly Locket (อีเวนต์)' WHERE slug = 'heavenly-locket-event' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Incomplete Charlottes Faith' WHERE slug = 'incomplete-charlottes-faith' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Old Wood' WHERE slug = 'old-wood-pendant' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Platinum' WHERE slug = 'platinum-pendant' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Pure Gold' WHERE slug = 'pure-gold-pendant' AND name_th IS NULL;
UPDATE items SET name_th = 'เงิน จี้' WHERE slug = 'silver-pendant' AND name_th IS NULL;
UPDATE items SET name_th = 'จี้ Wooden' WHERE slug = 'wooden-pendant' AND name_th IS NULL;
UPDATE items SET name_th = 'แองเจิล ปืนพก Revolvers' WHERE slug = 'angel-revolvers' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Chloes Insight' WHERE slug = 'chloes-insight' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Chloes Insight (อีเวนต์)' WHERE slug = 'chloes-insight-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Desert Storm' WHERE slug = 'desert-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก El Diablo' WHERE slug = 'el-diablo' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Beam-gun' WHERE slug = 'elite-beam-gun' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Chassepot' WHERE slug = 'elite-chassepot' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Claude Baudez Nique' WHERE slug = 'elite-claude-baudez-nique' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Echo of Steel' WHERE slug = 'elite-echo-of-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก El Diablo' WHERE slug = 'elite-el-diablo' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง ปืนพก Revolver' WHERE slug = 'elite-experimental-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Handgun' WHERE slug = 'elite-handgun' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Intuition of Al Rischa' WHERE slug = 'elite-intuition-of-al-rischa' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Intuition of Al Rischa (อีเวนต์)' WHERE slug = 'elite-intuition-of-al-rischa-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Mustang Strider' WHERE slug = 'elite-mustang-strider' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ปืนพก Revolver' WHERE slug = 'elite-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง ปืนพก Revolver' WHERE slug = 'experimental-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Flame Thrower' WHERE slug = 'flame-thrower' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Frozen Spitter' WHERE slug = 'frozen-spitter' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Hagallight Magnum' WHERE slug = 'hagallight-magnum' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Incomplete Chloes Insight' WHERE slug = 'incomplete-chloes-insight' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Intuition of Al Rischa' WHERE slug = 'intuition-of-al-rischa' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Intuition of Al Rischa (อีเวนต์)' WHERE slug = 'intuition-of-al-rischa-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Jaspards Rifling Revolver' WHERE slug = 'jaspards-rifling-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Lapis Lazuli of Accuracy' WHERE slug = 'lapis-lazuli-of-accuracy' AND name_th IS NULL;
UPDATE items SET name_th = 'ลีเจียน ปืนพก Revolver' WHERE slug = 'legion-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Lightning Gun' WHERE slug = 'lightning-gun' AND name_th IS NULL;
UPDATE items SET name_th = 'พรอสเป ปืนพก Revolver' WHERE slug = 'prospe-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'เวสปาโนลาขัดเงา ปืนพก Revolver' WHERE slug = 'refined-vespanola-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Revolver of Gerad' WHERE slug = 'revolver-of-gerad' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก Revolver of Justice' WHERE slug = 'revolver-of-justice' AND name_th IS NULL;
UPDATE items SET name_th = 'เซอร์เพนท์ ปืนพก Revolver' WHERE slug = 'serpent-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'ปืนพก The Revolver of Revenge' WHERE slug = 'the-revolver-of-revenge' AND name_th IS NULL;
UPDATE items SET name_th = 'สนับสนุนผู้บุกเบิกเวสปาโนลา ปืนพก Revolver' WHERE slug = 'vespanola-pioneer-support-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'แองเจิล โปลอาร์ม Hell Bird' WHERE slug = 'angel-hell-bird' AND name_th IS NULL;
UPDATE items SET name_th = 'โปลอาร์ม Beolight' WHERE slug = 'beolight-polearm' AND name_th IS NULL;
UPDATE items SET name_th = 'โปลอาร์ม Einschiever War Hammer' WHERE slug = 'einschiever-war-hammer' AND name_th IS NULL;
UPDATE items SET name_th = 'โปลอาร์ม Elgoom Spear' WHERE slug = 'elgoom-spear' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Beat of Steel' WHERE slug = 'elite-beat-of-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Broinac' WHERE slug = 'elite-broinac' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Great Maul' WHERE slug = 'elite-great-maul' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Guisarme' WHERE slug = 'elite-guisarme' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Gungnir' WHERE slug = 'elite-gungnir' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Harpoon' WHERE slug = 'elite-harpoon' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Muerte Balada' WHERE slug = 'elite-muerte-balada' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Muses Gigantestar' WHERE slug = 'elite-muses-gigantestar' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Muspellheim' WHERE slug = 'elite-muspellheim' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Scythe' WHERE slug = 'elite-scythe' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โปลอาร์ม Spetum' WHERE slug = 'elite-spetum' AND name_th IS NULL;
UPDATE items SET name_th = 'โปลอาร์ม Improved Brandistock (7 วัน)' WHERE slug = 'improved-brandistock-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ โปลอาร์ม Pole-axe' WHERE slug = 'ogre-pole-axe' AND name_th IS NULL;
UPDATE items SET name_th = 'เซอร์เพนท์ โปลอาร์ม Spear' WHERE slug = 'serpent-spear' AND name_th IS NULL;
UPDATE items SET name_th = 'แวร์แบร์ โปลอาร์ม Morning Star' WHERE slug = 'werebear-morning-star' AND name_th IS NULL;
UPDATE items SET name_th = 'แวร์แบร์ โปลอาร์ม Poleaxe' WHERE slug = 'werebear-poleaxe' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เรเปียร์ Calabrone' WHERE slug = 'elite-calabrone' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เรเปียร์ Candlestick' WHERE slug = 'elite-candlestick' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เรเปียร์ Epee' WHERE slug = 'elite-epee' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เรเปียร์ Purity of Aldebara (อีเวนต์)' WHERE slug = 'elite-purity-of-aldebara-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เรเปียร์' WHERE slug = 'elite-rapier' AND name_th IS NULL;
UPDATE items SET name_th = 'เรเปียร์ Inglight' WHERE slug = 'inglight-rapier' AND name_th IS NULL;
UPDATE items SET name_th = 'เรเปียร์ The Elite Sabre of Rafael' WHERE slug = 'the-elite-sabre-of-rafael' AND name_th IS NULL;
UPDATE items SET name_th = 'โบราณ ไรเฟิล Armonia' WHERE slug = 'ancient-armonia-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'แองเจิล ไรเฟิล Bayonet' WHERE slug = 'angel-bayonet' AND name_th IS NULL;