-- Migration 070: Thai names remaining v2 batch 7/9
-- Generated: 2026-03-16T03:55:14.475Z

UPDATE items SET name_th = 'แองเจิล ไรเฟิล Rod' WHERE slug = 'angel-rod-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Bayonet of Dewey' WHERE slug = 'bayonet-of-dewey' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Black Dragon' WHERE slug = 'elite-black-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Brown Bess' WHERE slug = 'elite-brown-bess' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Dragon Hunter Bayonet' WHERE slug = 'elite-dragon-hunter-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Dreyse' WHERE slug = 'elite-dreyse' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Finisher' WHERE slug = 'elite-finisher' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Finisher Bayonet' WHERE slug = 'elite-finisher-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล La Emperatriz' WHERE slug = 'elite-la-emperatriz' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล La Fuerza' WHERE slug = 'elite-la-fuerza' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Sniper Rifle Bayonet' WHERE slug = 'elite-sniper-rifle-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Tempest of Aquarius' WHERE slug = 'elite-tempest-of-aquarius' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไรเฟิล Tempest of Aquarius (อีเวนต์)' WHERE slug = 'elite-tempest-of-aquarius-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีวิล ไรเฟิล Bayonet' WHERE slug = 'evil-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Gold Dragon' WHERE slug = 'gold-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Improved Barkir (7 วัน)' WHERE slug = 'improved-barkir-rifle-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Incomplete Ordens Destruction' WHERE slug = 'incomplete-ordens-destruction' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล La Emperatriz' WHERE slug = 'la-emperatriz' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล La Fuerza' WHERE slug = 'la-fuerza' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Match-Lock Rifle 28 of Empire' WHERE slug = 'match-lock-rifle-28-of-empire' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Miquiret Steam Bayonet' WHERE slug = 'miquiret-steam-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Ordens Destruction' WHERE slug = 'ordens-destruction' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Ordens Destruction (อีเวนต์)' WHERE slug = 'ordens-destruction-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Othellight' WHERE slug = 'othellight-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล of Highrophant' WHERE slug = 'rifle-of-highrophant' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Sapphire of Concentration' WHERE slug = 'sapphire-of-concentration' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล ไรเฟิล Bayonet' WHERE slug = 'strata-devil-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล ไรเฟิล Bayonet (อีเวนต์)' WHERE slug = 'strata-devil-bayonet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Tempest of Aquarius' WHERE slug = 'tempest-of-aquarius' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Tempest of Aquarius (อีเวนต์)' WHERE slug = 'tempest-of-aquarius-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล The Black Dragon' WHERE slug = 'the-black-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล The Diamond Dragon' WHERE slug = 'the-diamond-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล The Emerald Dragon' WHERE slug = 'the-emerald-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล The Ruby Dragon' WHERE slug = 'the-ruby-dragon' AND name_th IS NULL;
UPDATE items SET name_th = 'ไรเฟิล Unlawful Bayonet' WHERE slug = 'unlawful-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Alegrias' WHERE slug = 'alegrias' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Amoladera Pure White' WHERE slug = 'amoladera-pure-white-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Amoladera' WHERE slug = 'amoladera-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Amoladera Robe of Lightning' WHERE slug = 'amoladera-robe-of-lightning' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Amoladera Robe of Storm' WHERE slug = 'amoladera-robe-of-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Amoladera Robe of Thunder' WHERE slug = 'amoladera-robe-of-thunder' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Amoladera Robe of Wind' WHERE slug = 'amoladera-robe-of-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Armure Diabolique -' WHERE slug = 'armure-diabolique-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Armure Diabolique - (อีเวนต์)' WHERE slug = 'armure-diabolique-robe-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Armure Diabolique of Leviathan -' WHERE slug = 'armure-diabolique-of-leviathan-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Armure Diabolique of Leviathan - (อีเวนต์)' WHERE slug = 'armure-diabolique-of-leviathan-robe-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Astartes' WHERE slug = 'astartes-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Blue Serpent' WHERE slug = 'blue-serpent-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Consolidar' WHERE slug = 'consolidar-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Consolidar Robe of Lightning' WHERE slug = 'consolidar-robe-of-lightning' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Consolidar Robe of Storm' WHERE slug = 'consolidar-robe-of-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Consolidar Robe of Thunder' WHERE slug = 'consolidar-robe-of-thunder' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Consolidar Robe of White' WHERE slug = 'consolidar-robe-of-white' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Consolidar Robe of Wind' WHERE slug = 'consolidar-robe-of-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ โรบ Le Blanc' WHERE slug = 'divine-le-blanc-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ Alegrias' WHERE slug = 'elite-alegrias' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ Geniaruleano' WHERE slug = 'elite-geniaruleano' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ La Ventisca' WHERE slug = 'elite-la-ventisca' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Aurora' WHERE slug = 'elite-robe-of-aurora' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Elementalist' WHERE slug = 'elite-robe-of-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Fire' WHERE slug = 'elite-robe-of-fire' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Hellfire' WHERE slug = 'elite-robe-of-hellfire' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Ice' WHERE slug = 'elite-robe-of-ice' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Lightning' WHERE slug = 'elite-robe-of-lightning' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Muspell' WHERE slug = 'elite-robe-of-muspell' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Neptune' WHERE slug = 'elite-robe-of-neptune' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Pluto' WHERE slug = 'elite-robe-of-pluto' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Salamander' WHERE slug = 'elite-robe-of-salamander' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Storm' WHERE slug = 'elite-robe-of-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Sylphide' WHERE slug = 'elite-robe-of-sylphide' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Uranus' WHERE slug = 'elite-robe-of-uranus' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Wind' WHERE slug = 'elite-robe-of-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ of Yeti' WHERE slug = 'elite-robe-of-yeti' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โรบ Ruidestencia' WHERE slug = 'elite-ruidestencia' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Frontier Croma(Robe)' WHERE slug = 'frontier-croma-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Greek Croma' WHERE slug = 'greek-croma-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Greek Croma (อีเวนต์)' WHERE slug = 'greek-croma-robe-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Hellfire' WHERE slug = 'hellfire-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ La Ventisca' WHERE slug = 'la-ventisca' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Le Blanc' WHERE slug = 'le-blanc-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Le Blanc of Cinderella' WHERE slug = 'le-blanc-of-cinderella-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Le Blanc of Cinderella for (60 วัน)' WHERE slug = 'le-blanc-of-cinderella-for-robe-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Le Noir' WHERE slug = 'le-noir-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Le Pouvoir' WHERE slug = 'le-pouvoir-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Le Scarce' WHERE slug = 'le-scarce-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Legacy - Royal Robe Armor' WHERE slug = 'legacy-royal-robe-armor' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Nero Croma' WHERE slug = 'nero-croma-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Novice' WHERE slug = 'novice-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ โรบ Noir' WHERE slug = 'ogre-noir-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Old Elite Le Noir' WHERE slug = 'old-elite-le-noir-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Old Greek Croma' WHERE slug = 'old-greek-croma-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Old Santo De Blanc' WHERE slug = 'old-santo-de-blanc-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Old Strata Devil' WHERE slug = 'old-strata-devil-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Pioneer Combat' WHERE slug = 'pioneer-combat-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Pioneer Mystic' WHERE slug = 'pioneer-mystic-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Pioneer Old' WHERE slug = 'pioneer-old-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Pioneer Practice' WHERE slug = 'pioneer-practice-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Pioneer' WHERE slug = 'pioneer-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Pioneer Thick' WHERE slug = 'pioneer-thick-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Red Serpent' WHERE slug = 'red-serpent-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ' WHERE slug = 'robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Elementalist' WHERE slug = 'robe-of-elementalist' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Expert' WHERE slug = 'robe-of-expert' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Fire' WHERE slug = 'robe-of-fire' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Ice' WHERE slug = 'robe-of-ice' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Inferno' WHERE slug = 'robe-of-inferno' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Lightning' WHERE slug = 'robe-of-lightning' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Neptune' WHERE slug = 'robe-of-neptune' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Pluto' WHERE slug = 'robe-of-pluto' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Sea Demon' WHERE slug = 'robe-of-sea-demon' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Sky Demon' WHERE slug = 'robe-of-sky-demon' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Storm' WHERE slug = 'robe-of-storm' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Superb Demon' WHERE slug = 'robe-of-superb-demon' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Syberia' WHERE slug = 'robe-of-syberia' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Sylph' WHERE slug = 'robe-of-sylph' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Thunder' WHERE slug = 'robe-of-thunder' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Uranus' WHERE slug = 'robe-of-uranus' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of Wind' WHERE slug = 'robe-of-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of the Salamander' WHERE slug = 'robe-of-the-salamander' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ of the Yeti' WHERE slug = 'robe-of-the-yeti' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Rosa Matrimonio' WHERE slug = 'rosa-matrimonio' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Rosa Matrimonio of Cinderella' WHERE slug = 'rosa-matrimonio-of-cinderella' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Rosa Matrimonio of Cinderella (60 วัน)' WHERE slug = 'rosa-matrimonio-of-cinderella-60-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ราชวงศ์ โรบ' WHERE slug = 'royal-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Santo De Blanc' WHERE slug = 'santo-de-blanc-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Santo De Blanc (อีเวนต์)' WHERE slug = 'santo-de-blanc-robe-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Sea Demons Armure Diabolique -' WHERE slug = 'sea-demons-armure-diabolique-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Sea Demons Armure Diabolique - (อีเวนต์)' WHERE slug = 'sea-demons-armure-diabolique-robe-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Supreme Dignite' WHERE slug = 'supreme-dignite-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Tempest' WHERE slug = 'tempest-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ The Pure White' WHERE slug = 'the-pure-white-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'โรบ Torsche Dress' WHERE slug = 'torsche-dress' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] ราชวงศ์ โรบ' WHERE slug = 'event-royal-robe' AND name_th IS NULL;
UPDATE items SET name_th = 'แองเจิล ไม้เท้า Wand' WHERE slug = 'angel-wand' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Broom of Little Witch' WHERE slug = 'broom-of-little-witch' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Broom of Little Witch (อีเวนต์)' WHERE slug = 'broom-of-little-witch-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Chloes Wish' WHERE slug = 'chloes-wish' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Chloes Wish (อีเวนต์)' WHERE slug = 'chloes-wish-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Control of Ophiuchus (อีเวนต์)' WHERE slug = 'control-of-ophiuchus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Crescemento' WHERE slug = 'crescemento-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'ดิไวน์ ไม้เท้า Broom Stick' WHERE slug = 'divine-broom-stick' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไม้เท้า Grim-stick' WHERE slug = 'elite-grim-stick' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไม้เท้า' WHERE slug = 'elite-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไม้เท้า The Control of Ophiuchus' WHERE slug = 'elite-the-control-of-ophiuchus' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไม้เท้า Wave of Steel' WHERE slug = 'elite-wave-of-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ไม้เท้า the Control of Ophiuchus (อีเวนต์)' WHERE slug = 'elite-the-control-of-ophiuchus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Feolight' WHERE slug = 'feolight-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Glacial Crystal' WHERE slug = 'glacial-crystal' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Incomplete Chloes Wish' WHERE slug = 'incomplete-chloes-wish' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Old BWitchs Room (อีเวนต์)' WHERE slug = 'old-bwitchs-room-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Old Witchs Room' WHERE slug = 'old-witchs-room' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Pearl of Excellence' WHERE slug = 'pearl-of-excellence' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า Purni Pumpkin' WHERE slug = 'purni-pumpkin' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า of Carla' WHERE slug = 'rod-of-carla' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า of Recluse' WHERE slug = 'rod-of-recluse' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า The Control of Ophiuchus' WHERE slug = 'the-control-of-ophiuchus' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า The Grim-stick' WHERE slug = 'the-grim-stick' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า The Rod of Armageddon' WHERE slug = 'the-rod-of-armageddon' AND name_th IS NULL;
UPDATE items SET name_th = 'ไม้เท้า The Rod of Pride' WHERE slug = 'the-rod-of-pride' AND name_th IS NULL;
UPDATE items SET name_th = 'โรซาริโอ Elegant' WHERE slug = 'elegant-rosario' AND name_th IS NULL;
UPDATE items SET name_th = 'เอเน็กซ์ อีเธอเรียล โรซาริโอ Rosary' WHERE slug = 'enex-ethereal-rosary' AND name_th IS NULL;
UPDATE items SET name_th = 'โรซาริโอ Enhanced Silver' WHERE slug = 'enhanced-silver-rosario' AND name_th IS NULL;
UPDATE items SET name_th = 'โรซาริโอ Gold' WHERE slug = 'gold-rosario' AND name_th IS NULL;
UPDATE items SET name_th = 'โรซาริโอ Gold (อีเวนต์)' WHERE slug = 'gold-rosario-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โรซาริโอ Incomplete Stellas Blessing' WHERE slug = 'incomplete-stellas-blessing' AND name_th IS NULL;
UPDATE items SET name_th = 'เงิน โรซาริโอ' WHERE slug = 'silver-rosario' AND name_th IS NULL;
UPDATE items SET name_th = 'โรซาริโอ Stellas Blessing' WHERE slug = 'stellas-blessing' AND name_th IS NULL;
UPDATE items SET name_th = 'โรซาริโอ Stellas Blessing (อีเวนต์)' WHERE slug = 'stellas-blessing-event' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] เอเน็กซ์ อีเธอเรียล โรซาริโอ Rosary' WHERE slug = 'event-enex-ethereal-rosary' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Ara' WHERE slug = 'runestone-ara' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Arons' WHERE slug = 'runestone-arons' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Atra' WHERE slug = 'runestone-atra' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Attle' WHERE slug = 'runestone-attle' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Audi' WHERE slug = 'runestone-audi' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Ault' WHERE slug = 'runestone-ault' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Be' WHERE slug = 'runestone-be' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Cadran' WHERE slug = 'runestone-cadran' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Cert' WHERE slug = 'runestone-cert' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Dal' WHERE slug = 'runestone-dal' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Deaton' WHERE slug = 'runestone-deaton' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Diost' WHERE slug = 'runestone-diost' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Disain' WHERE slug = 'runestone-disain' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] E-core' WHERE slug = 'runestone-e-core' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Entara' WHERE slug = 'runestone-entara' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Hetu' WHERE slug = 'runestone-hetu' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Hita' WHERE slug = 'runestone-hita' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Hitar' WHERE slug = 'runestone-hitar' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Ihorn' WHERE slug = 'runestone-ihorn' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Iol' WHERE slug = 'runestone-iol' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Ios' WHERE slug = 'runestone-ios' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Jod' WHERE slug = 'runestone-jod' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Kaolt' WHERE slug = 'runestone-kaolt' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Lantal' WHERE slug = 'runestone-lantal' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Let' WHERE slug = 'runestone-let' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Nias' WHERE slug = 'runestone-nias' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Odes' WHERE slug = 'runestone-odes' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Oller' WHERE slug = 'runestone-oller' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Ollet' WHERE slug = 'runestone-ollet' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Oss' WHERE slug = 'runestone-oss' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Othe' WHERE slug = 'runestone-othe' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Rade' WHERE slug = 'runestone-rade' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Rate' WHERE slug = 'runestone-rate' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Rita' WHERE slug = 'runestone-rita' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Ron' WHERE slug = 'runestone-ron' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Runes' WHERE slug = 'runestone-runes' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Salter' WHERE slug = 'runestone-salter' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Saor' WHERE slug = 'runestone-saor' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Sera' WHERE slug = 'runestone-sera' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Shiorn' WHERE slug = 'runestone-shiorn' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Shiroa' WHERE slug = 'runestone-shiroa' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Siatra' WHERE slug = 'runestone-siatra' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Ssior' WHERE slug = 'runestone-ssior' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Tana' WHERE slug = 'runestone-tana' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Tara' WHERE slug = 'runestone-tara' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Tiziana' WHERE slug = 'runestone-tiziana' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Trocar' WHERE slug = 'runestone-trocar' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Tudes' WHERE slug = 'runestone-tudes' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Virtue' WHERE slug = 'runestone-virtue' AND name_th IS NULL;
UPDATE items SET name_th = 'รูนสโตน [Runestone] Zior' WHERE slug = 'runestone-zior' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เซเบอร์ Blade' WHERE slug = 'elite-blade' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เซเบอร์ Cutlass' WHERE slug = 'elite-cutlass' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เซเบอร์ Dance of Steel' WHERE slug = 'elite-dance-of-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เซเบอร์' WHERE slug = 'elite-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เซเบอร์ di Gavi' WHERE slug = 'elite-sabre-di-gavi' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เซเบอร์ Shamshir' WHERE slug = 'elite-shamshir' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เซเบอร์ Slicer' WHERE slug = 'elite-slicer' AND name_th IS NULL;
UPDATE items SET name_th = 'เซเบอร์ Eolhlight' WHERE slug = 'eolhlight-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'เซเบอร์ Grear Gimmick of Scimitar' WHERE slug = 'grear-gimmick-of-scimitar' AND name_th IS NULL;
UPDATE items SET name_th = 'โคบอลท์ เซเบอร์ Bone' WHERE slug = 'kobolt-bone-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'เซเบอร์ Shamshir of Norris' WHERE slug = 'shamshir-of-norris' AND name_th IS NULL;
UPDATE items SET name_th = 'แอตลาส โล่ Strength' WHERE slug = 'atlas-strength' AND name_th IS NULL;
UPDATE items SET name_th = 'แอตลาส โล่ Strength (อีเวนต์)' WHERE slug = 'atlas-strength-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ Conflamme' WHERE slug = 'conflamme' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ Cumulonimbus' WHERE slug = 'cumulonimbus' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Aquila' WHERE slug = 'elite-aquila' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Arm Guard' WHERE slug = 'elite-arm-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Buckler' WHERE slug = 'elite-buckler' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Castor Wing' WHERE slug = 'elite-castor-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ La Templanza' WHERE slug = 'elite-la-templanza' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Noir Plaque' WHERE slug = 'elite-noir-plaque' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Pollux Wing' WHERE slug = 'elite-pollux-wing' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Riposte of Arachne' WHERE slug = 'elite-riposte-of-arachne' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Riposte of Arachne (อีเวนต์)' WHERE slug = 'elite-riposte-of-arachne-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Rouge Plaque' WHERE slug = 'elite-rouge-plaque' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Royal Guardian' WHERE slug = 'elite-royal-guardian' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท โล่ Templar Guard' WHERE slug = 'elite-templar-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ Event Armonia' WHERE slug = 'event-armonia-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ Incomplete Atlas Strength' WHERE slug = 'incomplete-atlas-strength' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ Infernal Hearts' WHERE slug = 'infernal-hearts' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ La Templanza' WHERE slug = 'la-templanza' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ Phantom Guard' WHERE slug = 'phantom-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ Riposte of Arachne' WHERE slug = 'riposte-of-arachne' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ Riposte of Arachne (อีเวนต์)' WHERE slug = 'riposte-of-arachne-event' AND name_th IS NULL;
UPDATE items SET name_th = 'โล่ The Grim-shout' WHERE slug = 'the-grim-shout' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า +10 Divinos Steel Leather (1 วัน)' WHERE slug = '10-divinos-steel-leather-boots-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า +10 Quinnitulas Bloody (1 วัน)' WHERE slug = '10-quinnitulas-bloody-boots-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า +10 Stars Pioneers (1 วัน)' WHERE slug = '10-stars-pioneers-boots-1-day' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Desapio' WHERE slug = 'desapio-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Distorted Boots of the Corrupted Knight' WHERE slug = 'distorted-boots-of-the-corrupted-knight' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Divinos Steel Leather' WHERE slug = 'divinos-steel-leather-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Divinos Steel Leather (ภาพลวง)' WHERE slug = 'divinos-steel-leather-boots-illusion' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Giltines Demonic' WHERE slug = 'giltines-demonic-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Laimas Holy' WHERE slug = 'laimas-holy-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Magic' WHERE slug = 'magic-shoes' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Magic (อีเวนต์)' WHERE slug = 'magic-shoes-event' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Muertuos boots' WHERE slug = 'muertuos-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Mystic' WHERE slug = 'mystic-shoes' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Pioneer' WHERE slug = 'pioneer-shoes' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Queenitulas Bloody (ภาพลวง)' WHERE slug = 'queenitulas-bloody-boots-illusion' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Quinnitulas Bloody' WHERE slug = 'quinnitulas-bloody-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Quiritatio Boots of Faith' WHERE slug = 'quiritatio-boots-of-faith' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า' WHERE slug = 'shoes' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า of Artisan' WHERE slug = 'shoes-of-artisan' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Stars Pioneers' WHERE slug = 'stars-pioneers-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Stars Pioneers (อีเวนต์)' WHERE slug = 'stars-pioneers-boots-event' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Swift Boots of General Wind' WHERE slug = 'swift-boots-of-general-wind' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Vigilar Tribes' WHERE slug = 'vigilar-tribes-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Vigilar Tribes (อีเวนต์)' WHERE slug = 'vigilar-tribes-boots-event' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Violets Shabbier' WHERE slug = 'violets-shabbier-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Violets Shabby' WHERE slug = 'violets-shabby-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Zodiac' WHERE slug = 'zodiac-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า Zodiac (อีเวนต์)' WHERE slug = 'zodiac-boots-event' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] รองเท้า Divino' WHERE slug = 'dreaming-divino-boots' AND name_th IS NULL;
UPDATE items SET name_th = '[ความฝัน] รองเท้า Quinnitulas' WHERE slug = 'dreaming-quinnitulas-boots' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] รองเท้า Giltines Demonic' WHERE slug = 'event-giltines-demonic-boots' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] รองเท้า Laimas Holy' WHERE slug = 'event-laimas-holy-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า [Lucid] Divino' WHERE slug = 'lucid-divino-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า [Lucid] Quinnitulas' WHERE slug = 'lucid-quinnitulas-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า [Reverie] Divino' WHERE slug = 'reverie-divino-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'รองเท้า [Reverie] Quinnitulas' WHERE slug = 'reverie-quinnitulas-boots' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Blunder of Lykaon' WHERE slug = 'blunder-of-lykaon' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Blunder of Lykaon (อีเวนต์)' WHERE slug = 'blunder-of-lykaon-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Burst of Spencer' WHERE slug = 'burst-of-spencer' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Charlottes Agony' WHERE slug = 'charlottes-agony' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Charlottes Agony (อีเวนต์)' WHERE slug = 'charlottes-agony-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Conqueror' WHERE slug = 'conqueror-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Crime' WHERE slug = 'crime-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ช็อตกัน Blunder of Lykaon' WHERE slug = 'elite-blunder-of-lykaon' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ช็อตกัน Blunder of Lykaon (อีเวนต์)' WHERE slug = 'elite-blunder-of-lykaon-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท บริสเทีย ช็อตกัน Shot Gun' WHERE slug = 'elite-bristia-shot-gun' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ช็อตกัน Clayshooter' WHERE slug = 'elite-clayshooter' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ช็อตกัน Imperial Shooter' WHERE slug = 'elite-imperial-shooter' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ช็อตกัน Los Enamorados' WHERE slug = 'elite-los-enamorados' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ช็อตกัน' WHERE slug = 'elite-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Improved Dread Buster (7 วัน)' WHERE slug = 'improved-dread-buster-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Improved Poison Shooter (7 วัน)' WHERE slug = 'improved-poison-shooter-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Improved Stun Gun (7 วัน)' WHERE slug = 'improved-stun-gun-7-days' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Incomplete Charlottes Agony' WHERE slug = 'incomplete-charlottes-agony' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Jalight' WHERE slug = 'jalight-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Los Enamorados' WHERE slug = 'los-enamorados' AND name_th IS NULL;
UPDATE items SET name_th = 'เซอร์เพนท์ ช็อตกัน Shooter' WHERE slug = 'serpent-shooter' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน of World' WHERE slug = 'shotgun-of-world' AND name_th IS NULL;
UPDATE items SET name_th = 'ช็อตกัน Topaz of Influence' WHERE slug = 'topaz-of-influence' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Absolute Zero / Aqua Pierce ring' WHERE slug = 'absolute-zero-aqua-pierce-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Bane Ring of Gladiator' WHERE slug = 'bane-ring-of-gladiator' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Bloody Overdrive Alpha' WHERE slug = 'bloody-overdrive-alpha' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Bolero' WHERE slug = 'bolero' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Cancion' WHERE slug = 'cancion' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Elthalion' WHERE slug = 'elthalion' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Esparu ring' WHERE slug = 'esparu-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Exclusion Ring - Vendetta' WHERE slug = 'exclusion-ring-vendetta' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Half Divide' WHERE slug = 'half-divide' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Order Ring of Lady' WHERE slug = 'order-ring-of-lady' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Pell Arkis' WHERE slug = 'pell-arkis' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Rage Ring of Wolf' WHERE slug = 'rage-ring-of-wolf' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Remolreno' WHERE slug = 'remolreno' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Rikenas' WHERE slug = 'rikenas' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Sacrifice ring' WHERE slug = 'sacrifice-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Tensenes / Cyclone ring' WHERE slug = 'tensenes-cyclone-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Will you ask for help from Admiral Saido?' WHERE slug = 'will-you-ask-for-help-from-admiral-saido' AND name_th IS NULL;
UPDATE items SET name_th = 'แองเจิล เบรซเล็ตพิเศษ' WHERE slug = 'angel-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ Ansurlight' WHERE slug = 'ansurlight-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ Assembly Logic Bangle' WHERE slug = 'assembly-logic-bangle' AND name_th IS NULL;
UPDATE items SET name_th = 'ดำ เบรซเล็ตพิเศษ Bishop' WHERE slug = 'black-bishop' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ of Empress' WHERE slug = 'bracelet-of-empress' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ of Raien' WHERE slug = 'bracelet-of-raien' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ of Three Kings' WHERE slug = 'bracelet-of-three-kings' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ El Sol' WHERE slug = 'el-sol' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตพิเศษ El Sol' WHERE slug = 'elite-el-sol' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ทดลอง เบรซเล็ตพิเศษ' WHERE slug = 'elite-experimental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท มูเอร์ทัวร์ส เบรซเล็ตพิเศษ Elemental' WHERE slug = 'elite-muertuors-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตพิเศษ Skullic Bracer' WHERE slug = 'elite-skullic-bracer' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตพิเศษ The Delphinus' WHERE slug = 'elite-the-delphinus' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท เบรซเล็ตพิเศษ the Delphinus (อีเวนต์)' WHERE slug = 'elite-the-delphinus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ Emerald of Mystery' WHERE slug = 'emerald-of-mystery' AND name_th IS NULL;
UPDATE items SET name_th = 'อีเวนต์ อีลิท มูเอร์ทัวร์ส เบรซเล็ตพิเศษ Elemental' WHERE slug = 'event-elite-muertuors-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'อีเวนต์ มูเอร์ทัวร์ส เบรซเล็ตพิเศษ Elemental' WHERE slug = 'event-muertuors-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'อีวิล เบรซเล็ตพิเศษ Elemental' WHERE slug = 'evil-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'ทดลอง เบรซเล็ตพิเศษ' WHERE slug = 'experimental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ Gold Bishop' WHERE slug = 'gold-bishop' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ Incomplete Stellas Judgement' WHERE slug = 'incomplete-stellas-judgement' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ Lust' WHERE slug = 'lust-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'มูเอร์ทัวร์ส เบรซเล็ตพิเศษ Elemental' WHERE slug = 'muertuors-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'พรอสเป เบรซเล็ตพิเศษ' WHERE slug = 'prospe-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ Stellas Judgement' WHERE slug = 'stellas-judgement' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ Stellas Judgement (อีเวนต์)' WHERE slug = 'stellas-judgement-event' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เบรซเล็ตพิเศษ' WHERE slug = 'strata-devil-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'สตราต้า เดวิล เบรซเล็ตพิเศษ (อีเวนต์)' WHERE slug = 'strata-devil-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ The Delphinus' WHERE slug = 'the-delphinus' AND name_th IS NULL;
UPDATE items SET name_th = 'เบรซเล็ตพิเศษ The Delphinus (อีเวนต์)' WHERE slug = 'the-delphinus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'ขาว เบรซเล็ตพิเศษ Bishop' WHERE slug = 'white-bishop' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา Amethyst of Awakening' WHERE slug = 'amethyst-of-awakening' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา Charlottes Patience' WHERE slug = 'charlottes-patience' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา Charlottes Patience (อีเวนต์)' WHERE slug = 'charlottes-patience-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา El Mago' WHERE slug = 'el-mago' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท คฑา El Mago' WHERE slug = 'elite-el-mago' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท คฑา Judgment of Bennu' WHERE slug = 'elite-judgment-of-bennu' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท คฑา Judgment of Bennu (อีเวนต์)' WHERE slug = 'elite-judgment-of-bennu-event' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท คฑา' WHERE slug = 'elite-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท คฑา of Gnosis' WHERE slug = 'elite-staff-of-gnosis' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท คฑา of Hypnosis' WHERE slug = 'elite-staff-of-hypnosis' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท คฑา of Simurgh' WHERE slug = 'elite-staff-of-simurgh' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา Forest Whisper' WHERE slug = 'forest-whisper' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา Incomplete Charlottes Patience' WHERE slug = 'incomplete-charlottes-patience' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา Judgement of Bennu (อีเวนต์)' WHERE slug = 'judgement-of-bennu-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา Judgment of Bennu' WHERE slug = 'judgment-of-bennu' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา Niedlight' WHERE slug = 'niedlight-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ คฑา Orb' WHERE slug = 'ogre-orb' AND name_th IS NULL;
UPDATE items SET name_th = 'คฑา of Prophet' WHERE slug = 'staff-of-prophet' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Ring of Legion Elite' WHERE slug = 'ring-of-legion-elite' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Ring of Light and Darkness' WHERE slug = 'ring-of-light-and-darkness' AND name_th IS NULL;
UPDATE items SET name_th = 'แองเจิล ซอร์ด Blade' WHERE slug = 'angel-blade' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ด Dullahan Claymore' WHERE slug = 'dullahan-claymore' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ด Dullahan' WHERE slug = 'dullahan-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ด Einaptor' WHERE slug = 'einaptor-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ด Elbrid' WHERE slug = 'elbrid-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ด Arondight' WHERE slug = 'elite-arondight' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ด Durandal' WHERE slug = 'elite-durandal' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ด Grim-Wraith' WHERE slug = 'elite-grim-wraith' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ด Katzbalger' WHERE slug = 'elite-katzbalger' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ด Penetrator' WHERE slug = 'elite-penetrator' AND name_th IS NULL;
UPDATE items SET name_th = 'อีลิท ซอร์ด Soul of Steel' WHERE slug = 'elite-soul-of-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ด Geobolight Blade' WHERE slug = 'geobolight-blade' AND name_th IS NULL;
UPDATE items SET name_th = 'อ็อกร์ ซอร์ด Blade' WHERE slug = 'ogre-blade' AND name_th IS NULL;
UPDATE items SET name_th = 'ซอร์ด Spinel of Sharpness' WHERE slug = 'spinel-of-sharpness' AND name_th IS NULL;
UPDATE items SET name_th = 'ตันฟา Urlight tonfa' WHERE slug = 'urlight-tonfa' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Back Guard Ring - Zeia Warrior' WHERE slug = 'upgraded-back-guard-ring-zeia-warrior' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Dobalada corte Ring - Scout' WHERE slug = 'upgraded-dobalada-corte-ring-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Doll Dream Ring - DEX' WHERE slug = 'upgraded-doll-dream-ring-dex' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Doll Dream Ring - INT' WHERE slug = 'upgraded-doll-dream-ring-int' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Doll Dream Ring - STR' WHERE slug = 'upgraded-doll-dream-ring-str' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Enhanced Tactics Ring - Valeria' WHERE slug = 'upgraded-enhanced-tactics-ring-valeria' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Equites Ring - Romina' WHERE slug = 'upgraded-equites-ring-romina' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Escrima Ring - Scout' WHERE slug = 'upgraded-escrima-ring-scout' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded First Aid Ring - Valeria' WHERE slug = 'upgraded-first-aid-ring-valeria' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Flintlock Ring - Auch Soldier' WHERE slug = 'upgraded-flintlock-ring-auch-soldier' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Flintlock Ring - Rescue Knight' WHERE slug = 'upgraded-flintlock-ring-rescue-knight' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Kneeling Shot Ring - Auch Infantry' WHERE slug = 'upgraded-kneeling-shot-ring-auch-infantry' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Low-Guard Ring - Asoka' WHERE slug = 'upgraded-low-guard-ring-asoka' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Upgraded Standing Shot Ring - Auch Infantry' WHERE slug = 'upgraded-standing-shot-ring-auch-infantry' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Electrica billar ring' WHERE slug = 'electrica-billar-ring' AND name_th IS NULL;
UPDATE items SET name_th = 'แหวน Enhanced Tactics Ring - Valeria' WHERE slug = 'enhanced-tactics-ring-valeria' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Abre Ignition' WHERE slug = 'abre-ignition' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Abre Ignition (อีเวนต์)' WHERE slug = 'abre-ignition-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Abyss Crossbow Costume (Event) (อีเวนต์)' WHERE slug = 'abyss-crossbow-costume-event-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Abyss Main-Gauche (อีเวนต์)' WHERE slug = 'abyss-main-gauche-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Accuracy of Pegasus' WHERE slug = 'accuracy-of-pegasus' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Agate of Blast' WHERE slug = 'agate-of-blast' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Agate of Blast (อีเวนต์)' WHERE slug = 'agate-of-blast-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Albarkar' WHERE slug = 'albarkar' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Almanac of Magic' WHERE slug = 'almanac-of-magic' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Ambassadors Sword' WHERE slug = 'ambassadors-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Ambassadors Sword (อีเวนต์)' WHERE slug = 'ambassadors-sword-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Amethyst of Awakening' WHERE slug = 'amethyst-of-awakening' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Amethyst of Awakening (อีเวนต์)' WHERE slug = 'amethyst-of-awakening-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Bayonet' WHERE slug = 'angel-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Bayonet (อีเวนต์)' WHERE slug = 'angel-bayonet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Bracelet' WHERE slug = 'angel-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Bracelet (อีเวนต์)' WHERE slug = 'angel-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Cannon (อีเวนต์)' WHERE slug = 'angel-cannon-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Crossbow (อีเวนต์)' WHERE slug = 'angel-crossbow-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Dagger (อีเวนต์)' WHERE slug = 'angel-dagger-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Halberd (อีเวนต์)' WHERE slug = 'angel-halberd-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Javelin (อีเวนต์)' WHERE slug = 'angel-javelin-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Knuckle (อีเวนต์)' WHERE slug = 'angel-knuckle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Leg-Guards' WHERE slug = 'angel-leg-guards' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Leg-Guards (อีเวนต์)' WHERE slug = 'angel-leg-guards-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Lute (อีเวนต์)' WHERE slug = 'angel-lute-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Mace (อีเวนต์)' WHERE slug = 'angel-mace-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Pistol' WHERE slug = 'angel-pistol' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Pistol (อีเวนต์)' WHERE slug = 'angel-pistol-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Polearm' WHERE slug = 'angel-polearm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Rapier (อีเวนต์)' WHERE slug = 'angel-rapier-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Rifle' WHERE slug = 'angel-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Rifle (อีเวนต์)' WHERE slug = 'angel-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Rod (อีเวนต์)' WHERE slug = 'angel-rod-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Sabre (อีเวนต์)' WHERE slug = 'angel-sabre-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Shotgun (อีเวนต์)' WHERE slug = 'angel-shotgun-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Slayer' WHERE slug = 'angel-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Slayer (อีเวนต์)' WHERE slug = 'angel-slayer-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Staff (อีเวนต์)' WHERE slug = 'angel-staff-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Sword' WHERE slug = 'angel-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Sword (อีเวนต์)' WHERE slug = 'angel-sword-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Wand' WHERE slug = 'angel-wand' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Angel Wand (อีเวนต์)' WHERE slug = 'angel-wand-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Antaronas Smile' WHERE slug = 'antaronas-smile' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Aqua Crystal' WHERE slug = 'aqua-crystal' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Aqua Crystal (อีเวนต์)' WHERE slug = 'aqua-crystal-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Aquamarine of Purity' WHERE slug = 'aquamarine-of-purity' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Aquamarine of Purity (อีเวนต์)' WHERE slug = 'aquamarine-of-purity-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Aradwha' WHERE slug = 'aradwha' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Aradwha (อีเวนต์)' WHERE slug = 'aradwha-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Astarte Escudo' WHERE slug = 'astarte-escudo' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Astarte Escudo (อีเวนต์)' WHERE slug = 'astarte-escudo-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Astarte Espada' WHERE slug = 'astarte-espada' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Astarte Espada (อีเวนต์)' WHERE slug = 'astarte-espada-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Attencion de Baselrane - D' WHERE slug = 'attencion-de-baselrane-d' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Attencion de Baselrane - D (อีเวนต์)' WHERE slug = 'attencion-de-baselrane-d-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Attencion de Baselrane - L' WHERE slug = 'attencion-de-baselrane-l' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Attencion de Baselrane - L (อีเวนต์)' WHERE slug = 'attencion-de-baselrane-l-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Authority of Valeron' WHERE slug = 'authority-of-valeron' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Authority of Valeron (อีเวนต์)' WHERE slug = 'authority-of-valeron-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Awakening of Tempest' WHERE slug = 'awakening-of-tempest' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Awakening of Tempest (อีเวนต์)' WHERE slug = 'awakening-of-tempest-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Azulita of Speed' WHERE slug = 'azulita-of-speed' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Azulita of Speed (อีเวนต์)' WHERE slug = 'azulita-of-speed-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ BFG Prototype' WHERE slug = 'bfg-prototype' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ BFG Prototype (อีเวนต์)' WHERE slug = 'bfg-prototype-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ BSR-20R' WHERE slug = 'bsr-20r' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ BSR-20R (อีเวนต์)' WHERE slug = 'bsr-20r-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Acuity' WHERE slug = 'batus-acuity' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Anguish' WHERE slug = 'batus-anguish' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Demise' WHERE slug = 'batus-demise' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Endurance' WHERE slug = 'batus-endurance' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Enthusiasm' WHERE slug = 'batus-enthusiasm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Ferocity' WHERE slug = 'batus-ferocity' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Hope' WHERE slug = 'batus-hope' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Insight' WHERE slug = 'batus-insight' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Judgment' WHERE slug = 'batus-judgment' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Loyalty' WHERE slug = 'batus-loyalty' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Nobility' WHERE slug = 'batus-nobility' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Purity' WHERE slug = 'batus-purity' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Tenacity' WHERE slug = 'batus-tenacity' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Batus Valor' WHERE slug = 'batus-valor' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Bracelet (อีเวนต์)' WHERE slug = 'black-draconic-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Crossbow (อีเวนต์)' WHERE slug = 'black-draconic-crossbow-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Dagger (อีเวนต์)' WHERE slug = 'black-draconic-dagger-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Hammer (อีเวนต์)' WHERE slug = 'black-draconic-hammer-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Javelin (อีเวนต์)' WHERE slug = 'black-draconic-javelin-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Revolver (อีเวนต์)' WHERE slug = 'black-draconic-revolver-event' AND name_th IS NULL;