-- Migration 071: Thai names remaining v2 batch 8/9
-- Generated: 2026-03-16T03:55:14.475Z

UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Rifle (อีเวนต์)' WHERE slug = 'black-draconic-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Rod (อีเวนต์)' WHERE slug = 'black-draconic-rod-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Saber (อีเวนต์)' WHERE slug = 'black-draconic-saber-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Shield (อีเวนต์)' WHERE slug = 'black-draconic-shield-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Shotgun (อีเวนต์)' WHERE slug = 'black-draconic-shotgun-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Slayer (อีเวนต์)' WHERE slug = 'black-draconic-slayer-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Spear (อีเวนต์)' WHERE slug = 'black-draconic-spear-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Staff (อีเวนต์)' WHERE slug = 'black-draconic-staff-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Draconic Sword (อีเวนต์)' WHERE slug = 'black-draconic-sword-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Blade' WHERE slug = 'black-dragonic-blade' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Bracelet' WHERE slug = 'black-dragonic-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Crossbow' WHERE slug = 'black-dragonic-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Dagger' WHERE slug = 'black-dragonic-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Hammer' WHERE slug = 'black-dragonic-hammer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Javelin' WHERE slug = 'black-dragonic-javelin' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Rapier' WHERE slug = 'black-dragonic-rapier' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Rapier (อีเวนต์)' WHERE slug = 'black-dragonic-rapier-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Revolver' WHERE slug = 'black-dragonic-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Rifle' WHERE slug = 'black-dragonic-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Rod' WHERE slug = 'black-dragonic-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Sabre' WHERE slug = 'black-dragonic-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Shield' WHERE slug = 'black-dragonic-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Shotgun' WHERE slug = 'black-dragonic-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Slayer' WHERE slug = 'black-dragonic-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Spear' WHERE slug = 'black-dragonic-spear' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Staff' WHERE slug = 'black-dragonic-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Black Dragonic Sword' WHERE slug = 'black-dragonic-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Rose Dagger' WHERE slug = 'bloody-rose-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Rose Dagger (อีเวนต์)' WHERE slug = 'bloody-rose-dagger-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Book' WHERE slug = 'bloody-vernier-book' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Broomstick' WHERE slug = 'bloody-vernier-broomstick' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Cannon' WHERE slug = 'bloody-vernier-cannon' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Cube' WHERE slug = 'bloody-vernier-cube' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Dagger' WHERE slug = 'bloody-vernier-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Elemental Bracelet' WHERE slug = 'bloody-vernier-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Fire Bracelet' WHERE slug = 'bloody-vernier-fire-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Javelin' WHERE slug = 'bloody-vernier-javelin' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Knuckle' WHERE slug = 'bloody-vernier-knuckle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Lightning Bracelet' WHERE slug = 'bloody-vernier-lightning-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Lute' WHERE slug = 'bloody-vernier-lute' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Main Gauche' WHERE slug = 'bloody-vernier-main-gauche' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Pistol' WHERE slug = 'bloody-vernier-pistol' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Polearm' WHERE slug = 'bloody-vernier-polearm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Rifle' WHERE slug = 'bloody-vernier-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Rod' WHERE slug = 'bloody-vernier-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Sabre' WHERE slug = 'bloody-vernier-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Shield' WHERE slug = 'bloody-vernier-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Shotgun' WHERE slug = 'bloody-vernier-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Slayer' WHERE slug = 'bloody-vernier-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Staff' WHERE slug = 'bloody-vernier-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bloody Vernier Sword' WHERE slug = 'bloody-vernier-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Blue Moon' WHERE slug = 'blue-moon' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Blue Moon (อีเวนต์)' WHERE slug = 'blue-moon-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Blunt of Retribution' WHERE slug = 'blunt-of-retribution' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Blunt of Retribution (อีเวนต์)' WHERE slug = 'blunt-of-retribution-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Brace Rope' WHERE slug = 'brace-rope' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Breath of Valeron' WHERE slug = 'breath-of-valeron' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Breath of Valeron (อีเวนต์)' WHERE slug = 'breath-of-valeron-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bristian Miracle' WHERE slug = 'bristian-miracle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Bristian Miracle (อีเวนต์)' WHERE slug = 'bristian-miracle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Broken Pierrot' WHERE slug = 'broken-pierrot' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Broken Rose' WHERE slug = 'broken-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Carnelian of Delight' WHERE slug = 'carnelian-of-delight' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Carnelian of Delight (อีเวนต์)' WHERE slug = 'carnelian-of-delight-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Cartona Thalia' WHERE slug = 'cartona-thalia' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Chain of Executor' WHERE slug = 'chain-of-executor' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Chain of Executor (อีเวนต์)' WHERE slug = 'chain-of-executor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Chain of Kats' WHERE slug = 'chain-of-kats' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Chain of Purification' WHERE slug = 'chain-of-purification' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Chain of Purification (อีเวนต์)' WHERE slug = 'chain-of-purification-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Christmas - Rapier' WHERE slug = 'christmas-rapier' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Christmas - Rod' WHERE slug = 'christmas-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Christmas - Sword' WHERE slug = 'christmas-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Christmas Fantasy' WHERE slug = 'christmas-fantasy' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Cold Steel' WHERE slug = 'cold-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Blunt' WHERE slug = 'deepsea-crystal-blunt' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Blunt (อีเวนต์)' WHERE slug = 'deepsea-crystal-blunt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Cannon' WHERE slug = 'deepsea-crystal-cannon' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Cannon (อีเวนต์)' WHERE slug = 'deepsea-crystal-cannon-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Crossbow' WHERE slug = 'deepsea-crystal-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Crossbow (อีเวนต์)' WHERE slug = 'deepsea-crystal-crossbow-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Dagger' WHERE slug = 'deepsea-crystal-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Dagger (อีเวนต์)' WHERE slug = 'deepsea-crystal-dagger-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Elemental Bracelet' WHERE slug = 'deepsea-crystal-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Elemental Bracelet (อีเวนต์)' WHERE slug = 'deepsea-crystal-elemental-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Fire Bracelet' WHERE slug = 'deepsea-crystal-fire-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Fire Bracelet (อีเวนต์)' WHERE slug = 'deepsea-crystal-fire-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Greatsword' WHERE slug = 'deepsea-crystal-greatsword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Greatsword (อีเวนต์)' WHERE slug = 'deepsea-crystal-greatsword-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Ice Bracelet' WHERE slug = 'deepsea-crystal-ice-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Ice Bracelet (อีเวนต์)' WHERE slug = 'deepsea-crystal-ice-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Javelin' WHERE slug = 'deepsea-crystal-javelin' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Javelin (อีเวนต์)' WHERE slug = 'deepsea-crystal-javelin-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Knuckle' WHERE slug = 'deepsea-crystal-knuckle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Knuckle (อีเวนต์)' WHERE slug = 'deepsea-crystal-knuckle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Leguard' WHERE slug = 'deepsea-crystal-leguard' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Leguard (อีเวนต์)' WHERE slug = 'deepsea-crystal-leguard-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Lightning Bracelet' WHERE slug = 'deepsea-crystal-lightning-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Lightning Bracelet (อีเวนต์)' WHERE slug = 'deepsea-crystal-lightning-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Lute' WHERE slug = 'deepsea-crystal-lute' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Lute (อีเวนต์)' WHERE slug = 'deepsea-crystal-lute-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Pistol' WHERE slug = 'deepsea-crystal-pistol' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Pistol (อีเวนต์)' WHERE slug = 'deepsea-crystal-pistol-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Polearm' WHERE slug = 'deepsea-crystal-polearm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Polearm (อีเวนต์)' WHERE slug = 'deepsea-crystal-polearm-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Rapier' WHERE slug = 'deepsea-crystal-rapier' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Rapier (อีเวนต์)' WHERE slug = 'deepsea-crystal-rapier-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Rifle' WHERE slug = 'deepsea-crystal-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Rifle (อีเวนต์)' WHERE slug = 'deepsea-crystal-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Rod' WHERE slug = 'deepsea-crystal-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Rod (อีเวนต์)' WHERE slug = 'deepsea-crystal-rod-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Sabre' WHERE slug = 'deepsea-crystal-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Sabre (อีเวนต์)' WHERE slug = 'deepsea-crystal-sabre-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Shotgun' WHERE slug = 'deepsea-crystal-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Shotgun (อีเวนต์)' WHERE slug = 'deepsea-crystal-shotgun-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Staff' WHERE slug = 'deepsea-crystal-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Staff (อีเวนต์)' WHERE slug = 'deepsea-crystal-staff-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Sword' WHERE slug = 'deepsea-crystal-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deepsea Crystal Sword (อีเวนต์)' WHERE slug = 'deepsea-crystal-sword-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Demon Executor' WHERE slug = 'demon-executor' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Demon Executor (อีเวนต์)' WHERE slug = 'demon-executor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Demonic Ruby Bracelet' WHERE slug = 'demonic-ruby-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Dernier Mer' WHERE slug = 'dernier-mer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Descent of Inuit Claw' WHERE slug = 'descent-of-inuit-claw' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Descent of Inuit Claw (อีเวนต์)' WHERE slug = 'descent-of-inuit-claw-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Deus Machina Storm Bracelet' WHERE slug = 'deus-machina-storm-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Blunt' WHERE slug = 'devil-blaze-blunt' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Blunt (อีเวนต์)' WHERE slug = 'devil-blaze-blunt-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Cannon' WHERE slug = 'devil-blaze-cannon' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Cannon (อีเวนต์)' WHERE slug = 'devil-blaze-cannon-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Crescent' WHERE slug = 'devil-blaze-crescent' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Crescent (อีเวนต์)' WHERE slug = 'devil-blaze-crescent-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Crossbow' WHERE slug = 'devil-blaze-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Crossbow (อีเวนต์)' WHERE slug = 'devil-blaze-crossbow-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Dagger' WHERE slug = 'devil-blaze-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Dagger (อีเวนต์)' WHERE slug = 'devil-blaze-dagger-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Elemental Bracelet' WHERE slug = 'devil-blaze-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Elemental Bracelet (อีเวนต์)' WHERE slug = 'devil-blaze-elemental-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Fire Bracelet' WHERE slug = 'devil-blaze-fire-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Fire Bracelet (อีเวนต์)' WHERE slug = 'devil-blaze-fire-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Greatsword' WHERE slug = 'devil-blaze-greatsword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Greatsword (อีเวนต์)' WHERE slug = 'devil-blaze-greatsword-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Ice Bracelet' WHERE slug = 'devil-blaze-ice-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Ice Bracelet (อีเวนต์)' WHERE slug = 'devil-blaze-ice-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Javelin' WHERE slug = 'devil-blaze-javelin' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Javelin (อีเวนต์)' WHERE slug = 'devil-blaze-javelin-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Knuckle' WHERE slug = 'devil-blaze-knuckle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Knuckle (อีเวนต์)' WHERE slug = 'devil-blaze-knuckle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Leguard' WHERE slug = 'devil-blaze-leguard' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Leguard (อีเวนต์)' WHERE slug = 'devil-blaze-leguard-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Lightning Bracelet' WHERE slug = 'devil-blaze-lightning-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Lightning Bracelet (อีเวนต์)' WHERE slug = 'devil-blaze-lightning-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Lute' WHERE slug = 'devil-blaze-lute' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Lute (อีเวนต์)' WHERE slug = 'devil-blaze-lute-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Main Gauche' WHERE slug = 'devil-blaze-main-gauche' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Main Gauche (อีเวนต์)' WHERE slug = 'devil-blaze-main-gauche-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Pistol' WHERE slug = 'devil-blaze-pistol' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Pistol (อีเวนต์)' WHERE slug = 'devil-blaze-pistol-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Polearm' WHERE slug = 'devil-blaze-polearm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Polearm (อีเวนต์)' WHERE slug = 'devil-blaze-polearm-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Rapier' WHERE slug = 'devil-blaze-rapier' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Rapier (อีเวนต์)' WHERE slug = 'devil-blaze-rapier-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Rifle' WHERE slug = 'devil-blaze-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Rifle (อีเวนต์)' WHERE slug = 'devil-blaze-rifle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Rod' WHERE slug = 'devil-blaze-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Rod (อีเวนต์)' WHERE slug = 'devil-blaze-rod-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Sabre' WHERE slug = 'devil-blaze-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Sabre (อีเวนต์)' WHERE slug = 'devil-blaze-sabre-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Shotgun' WHERE slug = 'devil-blaze-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Shotgun (อีเวนต์)' WHERE slug = 'devil-blaze-shotgun-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Staff' WHERE slug = 'devil-blaze-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Staff (อีเวนต์)' WHERE slug = 'devil-blaze-staff-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Sword' WHERE slug = 'devil-blaze-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Sword (อีเวนต์)' WHERE slug = 'devil-blaze-sword-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Tonfa' WHERE slug = 'devil-blaze-tonfa' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Devil Blaze Tonfa (อีเวนต์)' WHERE slug = 'devil-blaze-tonfa-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Diamond of Perfection (อีเวนต์)' WHERE slug = 'diamond-of-perfection-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Diogmos' WHERE slug = 'diogmos' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Disaster of Aquichtus' WHERE slug = 'disaster-of-aquichtus' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Disaster of Aquichtus (อีเวนต์)' WHERE slug = 'disaster-of-aquichtus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Disfade' WHERE slug = 'disfade' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Disfade (อีเวนต์)' WHERE slug = 'disfade-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Dragon Fist' WHERE slug = 'dragon-fist' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ El Hadad' WHERE slug = 'el-hadad' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Electric Buster' WHERE slug = 'electric-buster' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Electric Buster (อีเวนต์)' WHERE slug = 'electric-buster-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Eliminator' WHERE slug = 'eliminator' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Eliminator (อีเวนต์)' WHERE slug = 'eliminator-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Emerald of Mystery' WHERE slug = 'emerald-of-mystery' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Emerald of Mystery (อีเวนต์)' WHERE slug = 'emerald-of-mystery-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Enhanced Silver-Baron' WHERE slug = 'enhanced-silver-baron' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Enigma' WHERE slug = 'enigma' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Enigma (อีเวนต์)' WHERE slug = 'enigma-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Enpate' WHERE slug = 'enpate' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Enpate (อีเวนต์)' WHERE slug = 'enpate-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Essence of Cuberic' WHERE slug = 'essence-of-cuberic' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Essence of Cuberic (อีเวนต์)' WHERE slug = 'essence-of-cuberic-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Eternal Revenge' WHERE slug = 'eternal-revenge' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Eternal Revenge (อีเวนต์)' WHERE slug = 'eternal-revenge-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Almanac of Magic' WHERE slug = 'event-almanac-of-magic' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Alvarkar' WHERE slug = 'event-alvarkar' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Brace Rope' WHERE slug = 'event-brace-rope' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Broken Pierrot' WHERE slug = 'event-broken-pierrot' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Broken Rose' WHERE slug = 'event-broken-rose' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Cartona Thalia' WHERE slug = 'event-cartona-thalia' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Cold Steel' WHERE slug = 'event-cold-steel' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Demonic Ruby Bracelet' WHERE slug = 'event-demonic-ruby-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Dernier Mer' WHERE slug = 'event-dernier-mer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Diogmos' WHERE slug = 'event-diogmos' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event El Hadad' WHERE slug = 'event-el-hadad' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Facade' WHERE slug = 'event-facade' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Favor Flavor' WHERE slug = 'event-favor-flavor' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Foolish Nuns Scripture' WHERE slug = 'event-foolish-nuns-scripture' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event GPSG' WHERE slug = 'event-gpsg' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Glacier' WHERE slug = 'event-glacier' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Griffe de Glace' WHERE slug = 'event-griffe-de-glace' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Gypsophila' WHERE slug = 'event-gypsophila' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Horndal' WHERE slug = 'event-horndal' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Justitia' WHERE slug = 'event-justitia' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Lagaratore' WHERE slug = 'event-lagaratore' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Leon Blanca' WHERE slug = 'event-leon-blanca' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Liuto Di Amaneti' WHERE slug = 'event-liuto-di-amaneti' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Live Again' WHERE slug = 'event-live-again' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Luz' WHERE slug = 'event-luz' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Mahrus' WHERE slug = 'event-mahrus' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Neuter' WHERE slug = 'event-neuter' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Qliphoth' WHERE slug = 'event-qliphoth' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Rosanera' WHERE slug = 'event-rosanera' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Siucoatl' WHERE slug = 'event-siucoatl' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Spellbook of Crepa' WHERE slug = 'event-spellbook-of-crepa' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Tonarita Bianca' WHERE slug = 'event-tonarita-bianca' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Tri-Eine' WHERE slug = 'event-tri-eine' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Event Vertical Slur' WHERE slug = 'event-vertical-slur' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Affection' WHERE slug = 'evils-affection' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Aversion' WHERE slug = 'evils-aversion' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Desires' WHERE slug = 'evils-desires' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Despair' WHERE slug = 'evils-despair' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Fear' WHERE slug = 'evils-fear' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Impatience' WHERE slug = 'evils-impatience' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Inferiority' WHERE slug = 'evils-inferiority' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Puzzlement' WHERE slug = 'evils-puzzlement' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Risk' WHERE slug = 'evils-risk' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Strain' WHERE slug = 'evils-strain' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Temptation' WHERE slug = 'evils-temptation' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils Void' WHERE slug = 'evils-void' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Evils freedom from distraction' WHERE slug = 'evils-freedom-from-distraction' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Facade' WHERE slug = 'facade' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Favalier of Beluna (อีเวนต์)' WHERE slug = 'favalier-of-beluna-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Favor Flavor' WHERE slug = 'favor-flavor' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Fealty of Terhea (อีเวนต์)' WHERE slug = 'fealty-of-terhea-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Florence en Lamina' WHERE slug = 'florence-en-lamina' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Florence en Lamina (อีเวนต์)' WHERE slug = 'florence-en-lamina-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Frozen Spire Bracelet' WHERE slug = 'frozen-spire-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Frozen Spire Bracelet - Event' WHERE slug = 'frozen-spire-bracelet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ GPSG' WHERE slug = 'gpsg' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Garnet of Nature (อีเวนต์)' WHERE slug = 'garnet-of-nature-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Glacier' WHERE slug = 'glacier' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Glow of Goddess' WHERE slug = 'glow-of-goddess' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Glow of Goddess (อีเวนต์)' WHERE slug = 'glow-of-goddess-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Bishop' WHERE slug = 'gold-bishop' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Blut' WHERE slug = 'gold-dragonic-blut' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Bracelet' WHERE slug = 'gold-dragonic-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Crossbow' WHERE slug = 'gold-dragonic-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Dagger' WHERE slug = 'gold-dragonic-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Javelin' WHERE slug = 'gold-dragonic-javelin' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Polearm' WHERE slug = 'gold-dragonic-polearm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Rapier' WHERE slug = 'gold-dragonic-rapier' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Revolver' WHERE slug = 'gold-dragonic-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Rifle' WHERE slug = 'gold-dragonic-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Rod' WHERE slug = 'gold-dragonic-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Sabre' WHERE slug = 'gold-dragonic-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Shield' WHERE slug = 'gold-dragonic-shield' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Shotgun' WHERE slug = 'gold-dragonic-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Slayer' WHERE slug = 'gold-dragonic-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Staff' WHERE slug = 'gold-dragonic-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gold Dragonic Sword' WHERE slug = 'gold-dragonic-sword' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Golden Revolver' WHERE slug = 'golden-revolver' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Grande Mujer' WHERE slug = 'grande-mujer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Grande Mujer (อีเวนต์)' WHERE slug = 'grande-mujer-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Griffe de Glace' WHERE slug = 'griffe-de-glace' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Gypsophila' WHERE slug = 'gypsophila' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Haggle' WHERE slug = 'haggle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Haggle (อีเวนต์)' WHERE slug = 'haggle-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Book' WHERE slug = 'halloween-spirit-book' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Cannon' WHERE slug = 'halloween-spirit-cannon' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Elemental Bracelet' WHERE slug = 'halloween-spirit-elemental-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Fire Bracelet' WHERE slug = 'halloween-spirit-fire-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Heavy Rifle' WHERE slug = 'halloween-spirit-heavy-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Ice Bracelet' WHERE slug = 'halloween-spirit-ice-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Lightning Bracelet' WHERE slug = 'halloween-spirit-lightning-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Rod' WHERE slug = 'halloween-spirit-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Sabre' WHERE slug = 'halloween-spirit-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Halloween Spirit Staff' WHERE slug = 'halloween-spirit-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Heart of Barbatos' WHERE slug = 'heart-of-barbatos' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Heart of Barbatos (อีเวนต์)' WHERE slug = 'heart-of-barbatos-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Horn of Kapeluna' WHERE slug = 'horn-of-kapeluna' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Horn of Kapeluna (อีเวนต์)' WHERE slug = 'horn-of-kapeluna-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Horndal' WHERE slug = 'horndal' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Instrumento de Poder' WHERE slug = 'instrumento-de-poder' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Instrumento de Poder (อีเวนต์)' WHERE slug = 'instrumento-de-poder-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Introduction to Alchemy' WHERE slug = 'introduction-to-alchemy' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Introduction to Alchemy for Events' WHERE slug = 'introduction-to-alchemy-for-events' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Intuition of Terhea' WHERE slug = 'intuition-of-terhea' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Intuition of Terhea (อีเวนต์)' WHERE slug = 'intuition-of-terhea-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Iresh' WHERE slug = 'iresh' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Iresh (อีเวนต์)' WHERE slug = 'iresh-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Istion Bracelet (อีเวนต์)' WHERE slug = 'istion-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Jade of Patience (อีเวนต์)' WHERE slug = 'jade-of-patience-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Jasper of Aggression (อีเวนต์)' WHERE slug = 'jasper-of-aggression-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Justitia' WHERE slug = 'justitia' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Kiberiti' WHERE slug = 'kiberiti' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Kiberiti (อีเวนต์)' WHERE slug = 'kiberiti-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Kotetsu' WHERE slug = 'kotetsu' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ La Banjeresse' WHERE slug = 'la-banjeresse' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ La Vangresse for Events' WHERE slug = 'la-vangresse-for-events' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lagaratore' WHERE slug = 'lagaratore' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lamentation of Aquichtus (อีเวนต์)' WHERE slug = 'lamentation-of-aquichtus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lapis Lazuli of Accuracy' WHERE slug = 'lapis-lazuli-of-accuracy' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lapis Lazuli of Accuracy (อีเวนต์)' WHERE slug = 'lapis-lazuli-of-accuracy-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lavals Pressure' WHERE slug = 'lavals-pressure' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lavals Pressure (อีเวนต์)' WHERE slug = 'lavals-pressure-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Legacy of Bornos' WHERE slug = 'legacy-of-bornos' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Legacy of Canopor' WHERE slug = 'legacy-of-canopor' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Legendary Spearfish Polearm' WHERE slug = 'legendary-spearfish-polearm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Leon Blanca' WHERE slug = 'leon-blanca' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Liuto Di Amaneti' WHERE slug = 'liuto-di-amaneti' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Live Again' WHERE slug = 'live-again' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lord-of-Death' WHERE slug = 'lord-of-death' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lord-of-Death (อีเวนต์)' WHERE slug = 'lord-of-death-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lunar Secret Blade' WHERE slug = 'lunar-secret-blade' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Lunar Secret Blade (อีเวนต์)' WHERE slug = 'lunar-secret-blade-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Luz' WHERE slug = 'luz' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Mahrus' WHERE slug = 'mahrus' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Majestas' WHERE slug = 'majestas' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Majestas (อีเวนต์)' WHERE slug = 'majestas-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Malachite of Sublimity (อีเวนต์)' WHERE slug = 'malachite-of-sublimity-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Memory Archive' WHERE slug = 'memory-archive' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Memory Archive (อีเวนต์)' WHERE slug = 'memory-archive-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Memory Storage' WHERE slug = 'memory-storage' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Memory Storage (อีเวนต์)' WHERE slug = 'memory-storage-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Memory of the Past' WHERE slug = 'memory-of-the-past' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Memory of the Past (อีเวนต์)' WHERE slug = 'memory-of-the-past-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Moonstone of Harmony (อีเวนต์)' WHERE slug = 'moonstone-of-harmony-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Neuter' WHERE slug = 'neuter' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ None' WHERE slug = 'none' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Obsidian of Destruction (อีเวนต์)' WHERE slug = 'obsidian-of-destruction-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Opal of Precision' WHERE slug = 'opal-of-precision' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Opal of Precision (อีเวนต์)' WHERE slug = 'opal-of-precision-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Paavalie of Belluna' WHERE slug = 'paavalie-of-belluna' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Partner for events!' WHERE slug = 'partner-for-events' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Partner!' WHERE slug = 'partner' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pearl of Excellence' WHERE slug = 'pearl-of-excellence' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pearl of Excellence (อีเวนต์)' WHERE slug = 'pearl-of-excellence-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Peridot of Defiant (อีเวนต์)' WHERE slug = 'peridot-of-defiant-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Philosophy of Ventuamos (อีเวนต์)' WHERE slug = 'philosophy-of-ventuamos-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pierce of Vengeance' WHERE slug = 'pierce-of-vengeance' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Crossbow Costume for Event' WHERE slug = 'pioneer-crossbow-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Dagger Costume for Event' WHERE slug = 'pioneer-dagger-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Flame Bracelet Costume for Event' WHERE slug = 'pioneer-flame-bracelet-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Ice Bracelet Costume for Event' WHERE slug = 'pioneer-ice-bracelet-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Lightning Bracelet Costume for Event' WHERE slug = 'pioneer-lightning-bracelet-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Magic Book Costume for Event' WHERE slug = 'pioneer-magic-book-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Pistol Costume for Event' WHERE slug = 'pioneer-pistol-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Polearm Costume for event' WHERE slug = 'pioneer-polearm-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Rapier Costume for Event' WHERE slug = 'pioneer-rapier-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Rifle Costume for Event' WHERE slug = 'pioneer-rifle-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Rod Costume for Event' WHERE slug = 'pioneer-rod-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Saber Costume for Event' WHERE slug = 'pioneer-saber-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Slayer Costume for Event' WHERE slug = 'pioneer-slayer-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Special Bracelet Costume for event' WHERE slug = 'pioneer-special-bracelet-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Staff Costume for Event' WHERE slug = 'pioneer-staff-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Pioneer Sword Costume for Event' WHERE slug = 'pioneer-sword-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Protection of Terhea (อีเวนต์)' WHERE slug = 'protection-of-terhea-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Qliphoth' WHERE slug = 'qliphoth' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Queen of Flame' WHERE slug = 'queen-of-flame' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Queen of Flame (อีเวนต์)' WHERE slug = 'queen-of-flame-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Repression of Spirica' WHERE slug = 'repression-of-spirica' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Repression of Spirica (อีเวนต์)' WHERE slug = 'repression-of-spirica-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Rod of Savior' WHERE slug = 'rod-of-savior' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Rod of Savior (อีเวนต์)' WHERE slug = 'rod-of-savior-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Rosanera' WHERE slug = 'rosanera' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Ruby of Passion' WHERE slug = 'ruby-of-passion' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Ruby of Passion (อีเวนต์)' WHERE slug = 'ruby-of-passion-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Sage Wall' WHERE slug = 'sage-wall' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Sage Wall (อีเวนต์)' WHERE slug = 'sage-wall-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Saint Gloriel' WHERE slug = 'saint-gloriel' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Saint Gloriel (อีเวนต์)' WHERE slug = 'saint-gloriel-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Sanctuary of Barisada' WHERE slug = 'sanctuary-of-barisada' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Sanctuary of Barisada (อีเวนต์)' WHERE slug = 'sanctuary-of-barisada-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Sapphire of Concentration' WHERE slug = 'sapphire-of-concentration' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Sapphire of Concentration (อีเวนต์)' WHERE slug = 'sapphire-of-concentration-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Scalpel' WHERE slug = 'scalpel' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Scalpel (อีเวนต์)' WHERE slug = 'scalpel-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Secret of Aquichtus (อีเวนต์)' WHERE slug = 'secret-of-aquichtus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Seolhwas Flaming Blade' WHERE slug = 'seolhwas-flaming-blade' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Seolhwas Flaming Blade (อีเวนต์)' WHERE slug = 'seolhwas-flaming-blade-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Shaten Faust' WHERE slug = 'shaten-faust' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Shield of Retribution' WHERE slug = 'shield-of-retribution' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Shield of Retribution (อีเวนต์)' WHERE slug = 'shield-of-retribution-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Shwarz Messer' WHERE slug = 'shwarz-messer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silence of Ignisia' WHERE slug = 'silence-of-ignisia' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silence of Ignisia (อีเวนต์)' WHERE slug = 'silence-of-ignisia-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silhouette - Erebus' WHERE slug = 'silhouette-erebus' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silhouette - Erebus (อีเวนต์)' WHERE slug = 'silhouette-erebus-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silhouette - Plama' WHERE slug = 'silhouette-plama' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silhouette - Plama (อีเวนต์)' WHERE slug = 'silhouette-plama-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silhouette - Reclamo' WHERE slug = 'silhouette-reclamo' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silhouette - Reclamo (อีเวนต์)' WHERE slug = 'silhouette-reclamo-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silhouette - Tonytra' WHERE slug = 'silhouette-tonytra' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Silhouette - Tonytra (อีเวนต์)' WHERE slug = 'silhouette-tonytra-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Siucoatle' WHERE slug = 'siucoatle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Specialized Navy Shotgun' WHERE slug = 'specialized-navy-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Specialized Navy Shotgun - Event' WHERE slug = 'specialized-navy-shotgun-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Spellbook of Crepa' WHERE slug = 'spellbook-of-crepa' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Spinel of Sharpness' WHERE slug = 'spinel-of-sharpness' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Spinel of Sharpness (อีเวนต์)' WHERE slug = 'spinel-of-sharpness-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Spirit of Cuberic' WHERE slug = 'spirit-of-cuberic' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Spirit of Cuberic (อีเวนต์)' WHERE slug = 'spirit-of-cuberic-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Staff of Prophet' WHERE slug = 'staff-of-prophet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Staff of Prophet (อีเวนต์)' WHERE slug = 'staff-of-prophet-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Staff of Savior' WHERE slug = 'staff-of-savior' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Staff of Savior (อีเวนต์)' WHERE slug = 'staff-of-savior-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Bayonet' WHERE slug = 'standard-bayonet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Bayonet (Sakura)' WHERE slug = 'standard-bayonet-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Blade (Sakura)' WHERE slug = 'standard-blade-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Blunt' WHERE slug = 'standard-blunt' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Bracelet' WHERE slug = 'standard-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Cannon' WHERE slug = 'standard-cannon' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Cannon (Sakura)' WHERE slug = 'standard-cannon-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Crossbow' WHERE slug = 'standard-crossbow' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Crossbow (Sakura)' WHERE slug = 'standard-crossbow-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Dagger' WHERE slug = 'standard-dagger' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Dagger (Sakura)' WHERE slug = 'standard-dagger-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Greatsword (Sakura)' WHERE slug = 'standard-greatsword-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Halberd (Sakura)' WHERE slug = 'standard-halberd-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Javelin' WHERE slug = 'standard-javelin' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Javelin (Sakura)' WHERE slug = 'standard-javelin-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Knuckle' WHERE slug = 'standard-knuckle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Knuckle (Sakura)' WHERE slug = 'standard-knuckle-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Leg-Guard' WHERE slug = 'standard-leg-guard' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Legguard (Sakura)' WHERE slug = 'standard-legguard-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Lute' WHERE slug = 'standard-lute' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Lute (Sakura)' WHERE slug = 'standard-lute-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Mace (Sakura)' WHERE slug = 'standard-mace-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Pistol' WHERE slug = 'standard-pistol' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Pistol (Sakura)' WHERE slug = 'standard-pistol-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Polearm' WHERE slug = 'standard-polearm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Rapier' WHERE slug = 'standard-rapier' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Rapier (Sakura)' WHERE slug = 'standard-rapier-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Rifle' WHERE slug = 'standard-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Rifle (Sakura)' WHERE slug = 'standard-rifle-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Rod' WHERE slug = 'standard-rod' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Rod (Sakura)' WHERE slug = 'standard-rod-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Saber (Sakura)' WHERE slug = 'standard-saber-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Sabre' WHERE slug = 'standard-sabre' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Shotgun' WHERE slug = 'standard-shotgun' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Shotgun (Sakura)' WHERE slug = 'standard-shotgun-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Slayer' WHERE slug = 'standard-slayer' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Staff' WHERE slug = 'standard-staff' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Staff (Sakura)' WHERE slug = 'standard-staff-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Wand' WHERE slug = 'standard-wand' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard Wand (Sakura)' WHERE slug = 'standard-wand-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Standard bracelet (Sakura)' WHERE slug = 'standard-bracelet-sakura' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Sword of Command' WHERE slug = 'sword-of-command' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Sword of Command (อีเวนต์)' WHERE slug = 'sword-of-command-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tam Kar' WHERE slug = 'tam-kar' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tam Kar (อีเวนต์)' WHERE slug = 'tam-kar-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tartarus of Goddess' WHERE slug = 'tartarus-of-goddess' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tartarus of Goddess (อีเวนต์)' WHERE slug = 'tartarus-of-goddess-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tenacity of Ventuamos' WHERE slug = 'tenacity-of-ventuamos' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tenacity of Ventuamos (อีเวนต์)' WHERE slug = 'tenacity-of-ventuamos-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ The Fealty of Terhea' WHERE slug = 'the-fealty-of-terhea' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ The Foolish Nuns Scripture' WHERE slug = 'the-foolish-nuns-scripture' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ The Lamentation of Aquichtus' WHERE slug = 'the-lamentation-of-aquichtus' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ The Philosophy of Ventuamos' WHERE slug = 'the-philosophy-of-ventuamos' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ The Protection of Terhea' WHERE slug = 'the-protection-of-terhea' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ The Secret of Aquichtus' WHERE slug = 'the-secret-of-aquichtus' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Thousand Cherry Blossoms - Killing Demons (อีเวนต์)' WHERE slug = 'thousand-cherry-blossoms-killing-demons-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Thousand Cherry Blossoms - Killing Warriors (อีเวนต์)' WHERE slug = 'thousand-cherry-blossoms-killing-warriors-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Thousand cherry blossoms - Killing demons' WHERE slug = 'thousand-cherry-blossoms-killing-demons' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Thousand cherry blossoms - Killing warriors' WHERE slug = 'thousand-cherry-blossoms-killing-warriors' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tonarita Bianca' WHERE slug = 'tonarita-bianca' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tooth of Quetzalcoatl' WHERE slug = 'tooth-of-quetzalcoatl' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tooth of Quetzalcoatl (อีเวนต์)' WHERE slug = 'tooth-of-quetzalcoatl-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tooth of Tezpoca' WHERE slug = 'tooth-of-tezpoca' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tooth of Tezpoca (อีเวนต์)' WHERE slug = 'tooth-of-tezpoca-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Topaz of Influence' WHERE slug = 'topaz-of-influence' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Topaz of Influence (อีเวนต์)' WHERE slug = 'topaz-of-influence-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tormentor of Bristia' WHERE slug = 'tormentor-of-bristia' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tormentor of Bristia (อีเวนต์)' WHERE slug = 'tormentor-of-bristia-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tourmaline of Dominance' WHERE slug = 'tourmaline-of-dominance' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tourmaline of Dominance (อีเวนต์)' WHERE slug = 'tourmaline-of-dominance-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tri-Eine' WHERE slug = 'tri-eine' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tyrant Bracelet (อีเวนต์)' WHERE slug = 'tyrant-bracelet-costume-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tyrving of Diarin' WHERE slug = 'tyrving-of-diarin' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tyrving of Diarin (อีเวนต์)' WHERE slug = 'tyrving-of-diarin-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tyrving of Diren' WHERE slug = 'tyrving-of-diren' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Tyrving of Diren (อีเวนต์)' WHERE slug = 'tyrving-of-diren-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ VPR-822 Rifle' WHERE slug = 'vpr-822-rifle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ VPR-822 Rifle (อีเวนต์)' WHERE slug = 'vpr-822-rifle-event' AND name_th IS NULL;