-- Migration 072: Thai names remaining v2 batch 9/9
-- Generated: 2026-03-16T03:55:14.475Z

UPDATE items SET name_th = 'คอสตูมอาวุธ Vertical Slur' WHERE slug = 'vertical-slur' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Broom Stick Costume for Event' WHERE slug = 'vigilar-broom-stick-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Cannon Costume for Event' WHERE slug = 'vigilar-cannon-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Crossbow Costume for Event' WHERE slug = 'vigilar-crossbow-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Dagger Costume for Event' WHERE slug = 'vigilar-dagger-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Lute Costume for Event' WHERE slug = 'vigilar-lute-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Pistol Costume for Event' WHERE slug = 'vigilar-pistol-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Polearm Costume for Event' WHERE slug = 'vigilar-polearm-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Rapier Costume for Event' WHERE slug = 'vigilar-rapier-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Rifle Costume for Event' WHERE slug = 'vigilar-rifle-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Saber Costume for Event' WHERE slug = 'vigilar-saber-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Shotgun Costume for Event' WHERE slug = 'vigilar-shotgun-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Slayer Costume for Event' WHERE slug = 'vigilar-slayer-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Special Bracelet Costume for Event' WHERE slug = 'vigilar-special-bracelet-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Vigilar Sword Costume for Event' WHERE slug = 'vigilar-sword-costume-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Violantes Bracelet' WHERE slug = 'violantes-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Violantes Bracelet for Event' WHERE slug = 'violantes-bracelet-for-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Void Walker - Meteor' WHERE slug = 'void-walker-meteor' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Void Walker - Meteor (อีเวนต์)' WHERE slug = 'void-walker-meteor-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Void Walker - Ray' WHERE slug = 'void-walker-ray' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Void Walker - Ray (อีเวนต์)' WHERE slug = 'void-walker-ray-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Void Walker - Tempest' WHERE slug = 'void-walker-tempest' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Void Walker - Tempir (อีเวนต์)' WHERE slug = 'void-walker-tempir-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Void Walker - Tesla' WHERE slug = 'void-walker-tesla' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Void Walker - Tesla (อีเวนต์)' WHERE slug = 'void-walker-tesla-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Wail of Einschiever' WHERE slug = 'wail-of-einschiever' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Wail of Einschiever (Left)' WHERE slug = 'wail-of-einschiever-left' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Wail of Einschiever (Right)' WHERE slug = 'wail-of-einschiever-right' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Wing of Quetzalcoatl' WHERE slug = 'wing-of-quetzalcoatl' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Wing of Quetzalcoatl (อีเวนต์)' WHERE slug = 'wing-of-quetzalcoatl-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Zaveds Research Diary' WHERE slug = 'zaveds-research-diary' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ Zaveds Research Diary (อีเวนต์)' WHERE slug = 'zaveds-research-diary-event' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Atlas Brutality' WHERE slug = 'costume-atlas-brutality' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Atlas Dignity' WHERE slug = 'costume-atlas-dignity' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Atlas Ferocity' WHERE slug = 'costume-atlas-ferocity' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Atlas Gaze' WHERE slug = 'costume-atlas-gaze' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Atlas Salvation' WHERE slug = 'costume-atlas-salvation' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Atlas Strength' WHERE slug = 'costume-atlas-strength' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Atlas Weight' WHERE slug = 'costume-atlas-weight' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Charlottes Agony' WHERE slug = 'costume-charlottes-agony' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Charlottes Faith' WHERE slug = 'costume-charlottes-faith' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Charlottes Passion' WHERE slug = 'costume-charlottes-passion' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Charlottes Patience' WHERE slug = 'costume-charlottes-patience' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Charlottes Raid' WHERE slug = 'costume-charlottes-raid' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Charlottes Sharpness' WHERE slug = 'costume-charlottes-sharpness' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Charlottes Smile' WHERE slug = 'costume-charlottes-smile' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Chloes Affection' WHERE slug = 'costume-chloes-affection' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Chloes Insight' WHERE slug = 'costume-chloes-insight' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Chloes Melody' WHERE slug = 'costume-chloes-melody' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Chloes Riddle' WHERE slug = 'costume-chloes-riddle' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Chloes Wisdom' WHERE slug = 'costume-chloes-wisdom' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Chloes Wish' WHERE slug = 'costume-chloes-wish' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Ordens Breath' WHERE slug = 'costume-ordens-breath' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Ordens Dedication' WHERE slug = 'costume-ordens-dedication' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Ordens Destruction' WHERE slug = 'costume-ordens-destruction' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Ordens Hatred' WHERE slug = 'costume-ordens-hatred' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Ordens Lament' WHERE slug = 'costume-ordens-lament' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Ordens Oblivion' WHERE slug = 'costume-ordens-oblivion' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Ordens Tear' WHERE slug = 'costume-ordens-tear' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Stellas Blessing' WHERE slug = 'costume-stellas-blessing' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Stellas Enthusiasm' WHERE slug = 'costume-stellas-enthusiasm' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Stellas Judgement' WHERE slug = 'costume-stellas-judgement' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Stellas Nobility' WHERE slug = 'costume-stellas-nobility' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Stellas Purity' WHERE slug = 'costume-stellas-purity' AND name_th IS NULL;
UPDATE items SET name_th = 'คอสตูมอาวุธ [Costume] Stellas Valor' WHERE slug = 'costume-stellas-valor' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] คอสตูมอาวุธ Enex Ethereal Controller' WHERE slug = 'event-enex-ethereal-controller' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] คอสตูมอาวุธ Enex Ethereal Electric Bracelet' WHERE slug = 'event-enex-ethereal-electric-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] คอสตูมอาวุธ Enex Ethereal Flame Bracelet' WHERE slug = 'event-enex-ethereal-flame-bracelet' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] คอสตูมอาวุธ Enex Ethereal Large-Caliber Rifle' WHERE slug = 'event-enex-ethereal-large-caliber-rifle' AND name_th IS NULL;
UPDATE items SET name_th = '[อีเวนต์] คอสตูมอาวุธ Enex Ethereal Rosary' WHERE slug = 'event-enex-ethereal-rosary' AND name_th IS NULL;