-- Migration 025: Enchantments table + data from ge-db.site
-- Source: https://ge-db.site/andromida/Enchantment.php

CREATE TABLE IF NOT EXISTS enchantments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  chance TEXT NOT NULL,
  UNIQUE(category, name)
);

CREATE INDEX IF NOT EXISTS idx_enchantments_category ON enchantments(category);
-- Enchantment data: 182 entries
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', 'ATK 30-40% Up', '1 in 2');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', 'ATK SPD 15-30% Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', 'Critical +5-10', '1 in 9');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', '6-12% Chance to [Poison] Enemy during attack', '1 in 9');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', '6-12% Chance to [Stun] Enemy during attack', '1 in 9');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', 'Additional Fire ATK +25-50', '1 in 9');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', 'Additional Ice ATK +25-50', '1 in 9');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', 'Additional Lightning ATK +25-50', '1 in 9');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', '+25-50 Mental Attribute, Additional ATK', '1 in 9');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', 'A.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', '+50-100% ATK to Humans', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', '+50-100% ATK to Wildlife', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', '+50-100% ATK to Demons', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', '+50-100% ATK to Undead', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Melee', '+50-100% ATK to Lifeless', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'ATK 40-40% Up', '1 in 2');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'ATK SPD 15-30% Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'Critical +10-15', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'Accuracy +10-20', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', '5-10% Chance to [Fear] Enemy during attack', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'Attack causes [Darkness] with 5-10%', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'Additional Fire ATK +25-50', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'Additional Ice ATK +25-50', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'Additional Lightning ATK +25-50', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', '+25-50 Mental Attribute, Additional ATK', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', 'A.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', '+50-100% ATK to Humans', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', '+50-100% ATK to Wildlife', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', '+50-100% ATK to Demons', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', '+50-100% ATK to Undead', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shoot', '+50-100% ATK to Lifeless', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', 'ATK 30-40% Up', '1 in 2');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', 'ATK SPD 15-30% Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', 'MaxSP 12-25% Up', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', 'Attack causes [Darkness] with 5-10%', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', '+40-80 Mental Attribute, Additional ATK', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', 'A.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', '+50-100% ATK to Humans', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', '+50-100% ATK to Wildlife', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', '+50-100% ATK to Demons', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', '+50-100% ATK to Undead', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Psy', '+50-100% ATK to Lifeless', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Fire', 'ATK 30-40% Up', '1 in 2');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Fire', 'ATK SPD 15-30% Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Fire', 'MaxSP 12-25% Up', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Fire', 'During attack, [Burn] enemy by 5-10%', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Fire', 'Additional Fire ATK +40-80', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Fire', 'A.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ice', 'ATK 30-40% Up', '1 in 2');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ice', 'ATK SPD 15-30% Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ice', 'MaxSP 12-25% Up', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ice', 'During attack, [Freeze] enemy by 5-10%', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ice', 'Additional Ice ATK +40-80', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ice', 'A.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Lght', 'ATK 30-40% Up', '1 in 2');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Lght', 'ATK SPD 15-30% Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Lght', 'MaxSP 12-25% Up', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Lght', 'During attack, [Shock] enemy by 5-10%', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Lght', 'Additional Lightning ATK +40-80', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Lght', 'A.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'DEF 15-20 Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'Evasion 10-15 Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'Movement Speed 10-20% Up', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'Fire RES +8-15', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'Ice RES +8-15', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'Lightning RES +8-15', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'Debuff RES +10-15', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'Mental RES +10-15', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'MaxHP 15-25% Up', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armor', 'D.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'DEF 8-15 Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'Evasion 5-10 Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'Movement Speed 10-20% Up', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'Fire RES +10-20', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'Ice RES +10-20', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'Lightning RES +10-20', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'Debuff RES +10-20', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'Mental RES +10-20', '1 in 7');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'MaxHP 10-20% Up', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Clothe', 'D.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'DEF 5-5 Up', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Fire RES +5-8', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Ice RES +5-8', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Lightning RES +5-8', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Block +7-10', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Humanoid ATK Damage -15-25%', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Wildlife ATK Damage -15-25%', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Demon ATK Damage -15-25%', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Undead ATK Damage -15-25%', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'Lifeless ATK Damage -15-25%', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Shield', 'D.R. +2-2', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Glove', 'DEF 3-5 Up', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Glove', 'ATK SPD 5-10% Up', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Glove', 'Accuracy +3-5', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Glove', 'MaxSP 5-10% Up', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Boots', 'DEF 3-5 Up', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Boots', 'Movement Speed 5-10% Up', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Boots', 'Evasion 3-5 Up', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Boots', 'MaxHP 5-10% Up', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Rosario', 'DEF 3-5 Up', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Rosario', 'Fire RES +4-8', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Rosario', 'Ice RES +4-8', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Rosario', 'Lightning RES +4-8', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Rosario', 'MaxHP 10-15% Up', '1 in 20');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Rosario', 'MaxSP 15-20% Up', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Rosario', 'D.R. +2-2', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', 'ATK 30-40% Up', '1 in 2');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', 'ATK SPD 15-30% Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', 'MaxSP 12-25% Up', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', 'Attack causes [Darkness] with 5-10%', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', '+40-80 Mental Attribute, Additional ATK', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', 'A.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', '+50-100% ATK to Humans', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', '+50-100% ATK to Wildlife', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', '+50-100% ATK to Demons', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', '+50-100% ATK to Undead', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Book', '+50-100% ATK to Lifeless', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'ATK 30-40% Up', '1 in 2');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'ATK SPD 15-30% Up', '1 in 8');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'Critical +8-15', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'Accuracy +10-20', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', '5-10% Chance to [Fear] Enemy during attack', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'Attack causes [Darkness] with 5-10%', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'Additional Fire ATK +25-50', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'Additional Ice ATK +25-50', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'Additional Lightning ATK +25-50', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', '+25-50 Mental Attribute, Additional ATK', '1 in 10');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', 'A.R. +2-3', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', '+50-100% ATK to Humans', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', '+50-100% ATK to Wildlife', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', '+50-100% ATK to Demons', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', '+50-100% ATK to Undead', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Crossbow', '+50-100% ATK to Lifeless', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armsld', 'DEF 5-5 Up', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armsld', 'Block +5-10', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armsld', 'Lightning RES +4-8', '1 in 6');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Armsld', 'A.R. +1-1', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Etc', 'MaxSP 15-25% Up', '1 in 4');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Etc', 'Summon ATK Level +2-2', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Etc', 'Summon DEF Level +2-2', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Neck1', 'Max HP +750-1000', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Neck1', 'Max SP +75-100', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Neck1', 'STR +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Neck1', 'AGI +1-1', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Neck1', 'HP +1-1', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Neck1', 'DEX +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Neck1', 'INT +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Neck1', 'SEN +1-1', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Belt1', 'Max HP +750-1000', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Belt1', 'DEF 3-5 Up', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Belt1', 'STR +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Belt1', 'AGI +1-1', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Belt1', 'HP +1-1', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Belt1', 'DEX +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Belt1', 'INT +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Belt1', 'SEN +1-1', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ear1', 'Max HP +500-1000', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ear1', 'Max SP +25-50', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ear1', 'STR +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ear1', 'AGI +1-1', '1 in 150');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ear1', 'HP +1-1', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ear1', 'DEX +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ear1', 'INT +1-1', '1 in 200');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Ear1', 'SEN +1-1', '1 in 100');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'A.R. +1-1', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'D.R. +1-1', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'ATK SPD 10-10% Up', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'ATK 10-10% Up', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'Max HP +1500-1500', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'Max SP +300-300', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'DEF 10-10 Up', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'Additional Fire ATK +30-30', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'Additional Ice ATK +30-30', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'Additional Lightning ATK +30-30', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', '+30-30 Mental Attribute, Additional ATK', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', '+10-10% ATK to Humans', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', '+10-10% ATK to Wildlife', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', '+10-10% ATK to Demons', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', '+15-15% ATK to Undead', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', '+15-15% ATK to Lifeless', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', 'Penetration +3-3', 'Always');
INSERT OR IGNORE INTO enchantments (category, name, chance) VALUES ('Back', '5-5% damage restores HP', 'Always');
