UPDATE statuses SET description_th = 'Excalibur...' WHERE id = 62;
UPDATE statuses SET description_th = 'Argapo' WHERE id = 97;
UPDATE statuses SET description_th = 'เร่งความเร็วกระสุน' WHERE id = 290;
UPDATE statuses SET description_th = 'แหวน Clayboute Shot' WHERE id = 440;
UPDATE statuses SET description_th = 'ความมุ่งมั่น' WHERE id = 573;
UPDATE statuses SET description_th = 'Ectoplasm' WHERE id = 627;
UPDATE statuses SET description_th = 'ไฟฟ้าสถิต' WHERE id = 642;
UPDATE statuses SET description_th = 'buff ช้าง' WHERE id = 647;
UPDATE statuses SET description_th = 'หมอกทองหนาทึบ' WHERE id = 773;
UPDATE statuses SET description_th = 'โอ้ Ludin...' WHERE id = 1286;
UPDATE statuses SET description_th = 'พรของ Ornella' WHERE id = 1300;
UPDATE statuses SET description_th = 'ความโกรธของ Tsukuyomi' WHERE id = 1481;
UPDATE statuses SET description_th = 'ปลดปล่อย' WHERE id = 1520;
UPDATE statuses SET description_th = 'Ripuka' WHERE id = 1550;
UPDATE statuses SET description_th = 'Sordicula' WHERE id = 1684;
UPDATE statuses SET description_th = 'อาวุธวิญญาณ' WHERE id = 1692;
UPDATE statuses SET description_th = 'แหวน Clayboute Shot' WHERE id = 1788;
UPDATE statuses SET description_th = 'Tortazo Strike' WHERE id = 1829;
UPDATE statuses SET description_th = 'buff tooltip' WHERE id = 1846;
UPDATE statuses SET description_th = 'Wed Resemble' WHERE id = 1913;
UPDATE statuses SET description_th = 'Xenofluxus' WHERE id = 1956;
