-- Final batch: minimal labels for bracket-only entries
UPDATE statuses SET description_th = 'ADrive' WHERE id = 8;
UPDATE statuses SET description_th = 'Abyssos' WHERE id = 14;
UPDATE statuses SET description_th = 'Additional Magic' WHERE id = 26;
UPDATE statuses SET description_th = 'Additional Spire' WHERE id = 28;
UPDATE statuses SET description_th = 'Additional Spirit' WHERE id = 29;
UPDATE statuses SET description_th = 'Adrastea' WHERE id = 32;
UPDATE statuses SET description_th = 'Aegis' WHERE id = 34;
UPDATE statuses SET description_th = 'Aim Forward' WHERE id = 45;
UPDATE statuses SET description_th = 'Air Strike Ready' WHERE id = 47;
UPDATE statuses SET description_th = 'Air Strike Request' WHERE id = 48;
UPDATE statuses SET description_th = 'Almighty' WHERE id = 59;
UPDATE statuses SET description_th = 'Amplification' WHERE id = 65;
UPDATE statuses SET description_th = 'Ancient Authority' WHERE id = 68;
UPDATE statuses SET description_th = 'Ancient Insight' WHERE id = 71;
UPDATE statuses SET description_th = 'Ancient Protection' WHERE id = 74;
UPDATE statuses SET description_th = 'Ancient Valor' WHERE id = 75;
UPDATE statuses SET description_th = 'Andromida Return' WHERE id = 77;
UPDATE statuses SET description_th = 'Anti Personnel' WHERE id = 86;
UPDATE statuses SET description_th = 'Armadra' WHERE id = 101;
UPDATE statuses SET description_th = 'Armas' WHERE id = 102;
UPDATE statuses SET description_th = 'Armonia Warrior' WHERE id = 104;
UPDATE statuses SET description_th = 'Armor Grinding' WHERE id = 108;
UPDATE statuses SET description_th = 'Artery Amputation' WHERE id = 112;
UPDATE statuses SET description_th = 'Assassinate' WHERE id = 115;
UPDATE statuses SET description_th = 'Assault Signal' WHERE id = 116;
UPDATE statuses SET description_th = 'Awaken Arm' WHERE id = 130;
UPDATE statuses SET description_th = 'Awakening' WHERE id = 131;
UPDATE statuses SET description_th = 'BF Magnum' WHERE id = 132;
UPDATE statuses SET description_th = 'Battle Direction' WHERE id = 142;
UPDATE statuses SET description_th = 'Battle Weakening' WHERE id = 143;
UPDATE statuses SET description_th = 'Beginners Luck' WHERE id = 149;
UPDATE statuses SET description_th = 'Awakening' WHERE id = 150;
UPDATE statuses SET description_th = 'Bless of En Celar' WHERE id = 179;
UPDATE statuses SET description_th = 'Bless of Portus' WHERE id = 180;
UPDATE statuses SET description_th = 'Blessing of Flame' WHERE id = 197;
UPDATE statuses SET description_th = 'Blessing of Lyndon' WHERE id = 208;
UPDATE statuses SET description_th = 'Bloody Defensive' WHERE id = 243;
UPDATE statuses SET description_th = 'Blue Sephia' WHERE id = 249;
UPDATE statuses SET description_th = 'Boosting Package' WHERE id = 253;
UPDATE statuses SET description_th = 'Bulls Eye' WHERE id = 293;
UPDATE statuses SET description_th = 'Cannot Fly' WHERE id = 311;
UPDATE statuses SET description_th = 'Carga' WHERE id = 312;
UPDATE statuses SET description_th = 'Checking' WHERE id = 376;
UPDATE statuses SET description_th = 'Circle Penetration' WHERE id = 394;
UPDATE statuses SET description_th = 'Circle of Flow' WHERE id = 395;
UPDATE statuses SET description_th = 'Cognizance' WHERE id = 402;
UPDATE statuses SET description_th = 'Collection' WHERE id = 408;
UPDATE statuses SET description_th = 'Combat-ready' WHERE id = 438;
UPDATE statuses SET description_th = 'Containment ATK' WHERE id = 454;
UPDATE statuses SET description_th = 'Converge' WHERE id = 463;
UPDATE statuses SET description_th = 'Coruscation' WHERE id = 479;
UPDATE statuses SET description_th = 'CounterAttack 2' WHERE id = 502;
UPDATE statuses SET description_th = 'Course meals' WHERE id = 506;
UPDATE statuses SET description_th = 'Curse of Doll' WHERE id = 519;
UPDATE statuses SET description_th = 'Curse of Montoro' WHERE id = 522;
UPDATE statuses SET description_th = 'Cut Tolerance' WHERE id = 527;
UPDATE statuses SET description_th = 'DEF Penetration' WHERE id = 528;
UPDATE statuses SET description_th = 'Death Is Coming' WHERE id = 543;
UPDATE statuses SET description_th = 'Declino' WHERE id = 547;
UPDATE statuses SET description_th = 'Defect' WHERE id = 551;
UPDATE statuses SET description_th = 'Defensive Aurora' WHERE id = 554;
UPDATE statuses SET description_th = 'Demonic Authority' WHERE id = 564;
UPDATE statuses SET description_th = 'Descent of Inuit' WHERE id = 566;
UPDATE statuses SET description_th = 'Despair' WHERE id = 567;
UPDATE statuses SET description_th = 'Destroyer Mode' WHERE id = 569;
UPDATE statuses SET description_th = 'Detective Ts Analyzing Table' WHERE id = 572;
UPDATE statuses SET description_th = 'Dice' WHERE id = 578;
UPDATE statuses SET description_th = 'Dice' WHERE id = 579;
UPDATE statuses SET description_th = 'Dice' WHERE id = 580;
UPDATE statuses SET description_th = 'Dice' WHERE id = 581;
UPDATE statuses SET description_th = 'Dice' WHERE id = 582;
UPDATE statuses SET description_th = 'Dice' WHERE id = 583;
UPDATE statuses SET description_th = 'Direttore' WHERE id = 586;
UPDATE statuses SET description_th = 'Displayed' WHERE id = 590;
UPDATE statuses SET description_th = 'Dodge' WHERE id = 598;
UPDATE statuses SET description_th = 'Doll Dream' WHERE id = 599;
UPDATE statuses SET description_th = 'Dorsata' WHERE id = 601;
UPDATE statuses SET description_th = 'Electrification' WHERE id = 640;
UPDATE statuses SET description_th = 'Endorphin Fever' WHERE id = 655;
UPDATE statuses SET description_th = 'Enthusiastic' WHERE id = 678;
UPDATE statuses SET description_th = 'Eternal Fire' WHERE id = 684;
UPDATE statuses SET description_th = 'Excido' WHERE id = 698;
UPDATE statuses SET description_th = 'Extreme' WHERE id = 709;
UPDATE statuses SET description_th = 'Extreme - AGI' WHERE id = 710;
UPDATE statuses SET description_th = 'Extreme - Casting' WHERE id = 712;
UPDATE statuses SET description_th = 'Extreme - DEF' WHERE id = 714;
UPDATE statuses SET description_th = 'Extreme - DEX' WHERE id = 715;
UPDATE statuses SET description_th = 'Extreme - HP' WHERE id = 716;
UPDATE statuses SET description_th = 'Extreme - HP Regen' WHERE id = 718;
UPDATE statuses SET description_th = 'Extreme - INT' WHERE id = 719;
UPDATE statuses SET description_th = 'Extreme - Move SPD' WHERE id = 723;
UPDATE statuses SET description_th = 'Extreme - SEN' WHERE id = 724;
UPDATE statuses SET description_th = 'Extreme - STR' WHERE id = 725;
UPDATE statuses SET description_th = 'Fast Building' WHERE id = 736;
UPDATE statuses SET description_th = 'Fast Thinking' WHERE id = 738;
UPDATE statuses SET description_th = 'Flame Booster' WHERE id = 759;
UPDATE statuses SET description_th = 'Florence' WHERE id = 769;
UPDATE statuses SET description_th = 'Floreo' WHERE id = 770;
UPDATE statuses SET description_th = 'Focusing' WHERE id = 772;
UPDATE statuses SET description_th = 'Fortify Aura I' WHERE id = 776;
UPDATE statuses SET description_th = 'Fortify Aura II' WHERE id = 777;
UPDATE statuses SET description_th = 'Fox Transform' WHERE id = 779;
UPDATE statuses SET description_th = 'Fret' WHERE id = 792;
UPDATE statuses SET description_th = 'Frost Shield' WHERE id = 795;
UPDATE statuses SET description_th = 'Game ongoing' WHERE id = 817;
UPDATE statuses SET description_th = 'Heaven' WHERE id = 820;
UPDATE statuses SET description_th = 'Ghostly Blade' WHERE id = 823;
UPDATE statuses SET description_th = 'Glacier Slowdown' WHERE id = 827;
UPDATE statuses SET description_th = 'Goblin Dance' WHERE id = 834;
UPDATE statuses SET description_th = 'Goblin Mark' WHERE id = 835;
UPDATE statuses SET description_th = 'Grace of Fire' WHERE id = 846;
UPDATE statuses SET description_th = 'Grizz Roar' WHERE id = 857;
UPDATE statuses SET description_th = 'Guard of Cyclops' WHERE id = 863;
UPDATE statuses SET description_th = 'New Years Blessing' WHERE id = 1271;
UPDATE statuses SET description_th = 'Nightmare' WHERE id = 1273;
UPDATE statuses SET description_th = 'Oracle' WHERE id = 1295;
UPDATE statuses SET description_th = 'PREP' WHERE id = 1309;
UPDATE statuses SET description_th = 'Pain Barrier' WHERE id = 1312;
UPDATE statuses SET description_th = 'Pathos' WHERE id = 1326;
UPDATE statuses SET description_th = 'Pathos' WHERE id = 1328;
UPDATE statuses SET description_th = 'Pathos' WHERE id = 1330;
UPDATE statuses SET description_th = 'Penetration' WHERE id = 1335;
UPDATE statuses SET description_th = 'Physical Cancel' WHERE id = 1343;
UPDATE statuses SET description_th = 'Physical RES' WHERE id = 1345;
UPDATE statuses SET description_th = 'Pioneer Premium' WHERE id = 1353;
UPDATE statuses SET description_th = 'Power Magic' WHERE id = 1391;
UPDATE statuses SET description_th = 'Principal Aura I' WHERE id = 1410;
UPDATE statuses SET description_th = 'Principal Aura II' WHERE id = 1411;
UPDATE statuses SET description_th = 'Quatanaru' WHERE id = 1456;
UPDATE statuses SET description_th = 'Quiritatios Scar' WHERE id = 1468;
UPDATE statuses SET description_th = 'Rapid' WHERE id = 1486;
UPDATE statuses SET description_th = 'Rapu' WHERE id = 1487;
UPDATE statuses SET description_th = 'Armor Grinding' WHERE id = 1488;
UPDATE statuses SET description_th = 'Red Lightning' WHERE id = 1501;
UPDATE statuses SET description_th = 'Red Sephia' WHERE id = 1505;
UPDATE statuses SET description_th = 'Resolution' WHERE id = 1529;
UPDATE statuses SET description_th = 'Punishment' WHERE id = 1540;
UPDATE statuses SET description_th = 'Returnee' WHERE id = 1541;
UPDATE statuses SET description_th = 'Ritenuto' WHERE id = 1553;
UPDATE statuses SET description_th = 'Rush' WHERE id = 1563;
UPDATE statuses SET description_th = 'Salesman' WHERE id = 1577;
UPDATE statuses SET description_th = 'Scenario' WHERE id = 1586;
UPDATE statuses SET description_th = 'Seiol' WHERE id = 1596;
UPDATE statuses SET description_th = 'Sekhmets Bullet' WHERE id = 1597;
UPDATE statuses SET description_th = 'Sekhmets Burn' WHERE id = 1599;
UPDATE statuses SET description_th = 'Shadow Trigger' WHERE id = 1615;
UPDATE statuses SET description_th = 'Shell Breaker' WHERE id = 1620;
UPDATE statuses SET description_th = 'Shield Block' WHERE id = 1622;
UPDATE statuses SET description_th = 'Shining Trigger' WHERE id = 1626;
UPDATE statuses SET description_th = 'Shooting Cancel' WHERE id = 1632;
UPDATE statuses SET description_th = 'Shooting Weakening' WHERE id = 1636;
UPDATE statuses SET description_th = 'Shrinking' WHERE id = 1642;
UPDATE statuses SET description_th = 'Shrouded in Darkness' WHERE id = 1644;
UPDATE statuses SET description_th = 'Sinfonia' WHERE id = 1655;
UPDATE statuses SET description_th = 'Sorry!' WHERE id = 1685;
UPDATE statuses SET description_th = 'Soul Reapers Blessing' WHERE id = 1689;
UPDATE statuses SET description_th = 'Spirit of Fox' WHERE id = 1695;
UPDATE statuses SET description_th = 'Spasticity' WHERE id = 1702;
UPDATE statuses SET description_th = 'Welcome' WHERE id = 1703;
UPDATE statuses SET description_th = 'Spirit Panther' WHERE id = 1709;
UPDATE statuses SET description_th = 'Soul of Fox' WHERE id = 1710;
UPDATE statuses SET description_th = 'Staccato' WHERE id = 1716;
UPDATE statuses SET description_th = 'Static' WHERE id = 1727;
UPDATE statuses SET description_th = 'Stigma' WHERE id = 1732;
UPDATE statuses SET description_th = 'Stitch' WHERE id = 1734;
UPDATE statuses SET description_th = 'Story Event Buff' WHERE id = 1736;
UPDATE statuses SET description_th = 'Strength of Cerberus' WHERE id = 1740;
UPDATE statuses SET description_th = 'Supporting Order' WHERE id = 1758;
UPDATE statuses SET description_th = 'Switch Tactics - OFF' WHERE id = 1767;
UPDATE statuses SET description_th = 'Switch Tactics - ON' WHERE id = 1768;
UPDATE statuses SET description_th = 'Synergy' WHERE id = 1771;
UPDATE statuses SET description_th = 'Taabu' WHERE id = 1775;
UPDATE statuses SET description_th = 'Taken' WHERE id = 1787;
UPDATE statuses SET description_th = 'Tempest Force' WHERE id = 1798;
UPDATE statuses SET description_th = 'Titan Bullet' WHERE id = 1822;
UPDATE statuses SET description_th = 'Tolerance' WHERE id = 1823;
UPDATE statuses SET description_th = 'Tooth Marks' WHERE id = 1825;
UPDATE statuses SET description_th = 'Tormentum' WHERE id = 1828;
UPDATE statuses SET description_th = 'Tradition' WHERE id = 1835;
UPDATE statuses SET description_th = 'Transcend Time' WHERE id = 1838;
UPDATE statuses SET description_th = 'Trick or Treat' WHERE id = 1841;
UPDATE statuses SET description_th = 'Vanguard Formation' WHERE id = 1873;
UPDATE statuses SET description_th = 'Vestige of Shadows' WHERE id = 1878;
UPDATE statuses SET description_th = 'VitalAttack' WHERE id = 1886;
UPDATE statuses SET description_th = 'Volcanic Ash' WHERE id = 1888;
UPDATE statuses SET description_th = 'Von Larr' WHERE id = 1889;
UPDATE statuses SET description_th = 'Wakening' WHERE id = 1894;
UPDATE statuses SET description_th = 'Wall of Curan' WHERE id = 1895;
UPDATE statuses SET description_th = 'Wanderer' WHERE id = 1896;
UPDATE statuses SET description_th = 'Weapon Block' WHERE id = 1906;
UPDATE statuses SET description_th = 'Weapon Enhancement' WHERE id = 1908;
UPDATE statuses SET description_th = 'Weapon Master' WHERE id = 1909;
UPDATE statuses SET description_th = 'Welcome' WHERE id = 1914;
UPDATE statuses SET description_th = 'Weza' WHERE id = 1917;
UPDATE statuses SET description_th = 'What does the Family mean to you?' WHERE id = 1918;
UPDATE statuses SET description_th = 'White Day' WHERE id = 1921;
UPDATE statuses SET description_th = 'Wildfire' WHERE id = 1927;
UPDATE statuses SET description_th = 'Will of Guardian' WHERE id = 1937;
UPDATE statuses SET description_th = 'Will to Live' WHERE id = 1941;
UPDATE statuses SET description_th = 'World PvP Manual' WHERE id = 1950;
UPDATE statuses SET description_th = 'Yusmachinas Curse' WHERE id = 1960;
UPDATE statuses SET description_th = 'Yusmachinas Haste' WHERE id = 1961;
UPDATE statuses SET description_th = 'thanksgiving Liquor' WHERE id = 1971;
