-- Batch 27: C section continued (407-478)

UPDATE statuses SET description_th = 'รวบรวมและส่งมอบไอเทมที่ Sherry ร้องขอโดยเอาชนะมอนสเตอร์ประเภทปีศาจ' WHERE id = 407;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้ 50%' WHERE id = 416;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้ 20%' WHERE id = 435;
UPDATE statuses SET description_th = 'เพิ่มความเร็วเคลื่อนที่ขณะต่อสู้' WHERE id = 437;
UPDATE statuses SET description_th = 'เพิ่มบล็อกมากเป็นเวลา 10 วินาที แต่จำกัดสกิลและความเร็วเคลื่อนที่' WHERE id = 439;
UPDATE statuses SET description_th = 'ดนตรีเข้มข้นเสียงสูงเพิ่มความสามารถในการต่อสู้' WHERE id = 441;
UPDATE statuses SET description_th = 'ดนตรีเข้มข้นเสียงต่ำเพิ่มความสามารถในการต่อสู้' WHERE id = 442;
UPDATE statuses SET description_th = 'เพิ่มความแม่นยำและอัตราคริติคอลชั่วคราว' WHERE id = 443;
UPDATE statuses SET description_th = 'ลดดาเมจเดี่ยวอย่างมาก' WHERE id = 444;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตียิงในรัศมี' WHERE id = 445;
UPDATE statuses SET description_th = 'เพิ่มความสามารถต้านทานตามประเภทเกราะศัตรู' WHERE id = 446;
UPDATE statuses SET description_th = 'SP ไม่ฟื้นฟูชั่วคราว และไม่สามารถใช้สกิล' WHERE id = 447;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะ ความเร็วเคลื่อนที่ และลดเวลาร่ายสกิล' WHERE id = 450;
UPDATE statuses SET description_th = 'เพิ่มอัตราเจาะเกราะต่อศัตรูชั่วคราว' WHERE id = 451;
UPDATE statuses SET description_th = 'HP ลดอย่างต่อเนื่อง ถ้ายกเลิก จะแพร่กระจายไปยังศัตรูใกล้เคียง' WHERE id = 452;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่ และจำกัดการใช้สกิล' WHERE id = 453;
UPDATE statuses SET description_th = 'ละเว้นพลังป้องกัน 80 และการหลบ' WHERE id = 455;
UPDATE statuses SET description_th = 'ดาเมจเพิ่มจาก Celine' WHERE id = 458;
UPDATE statuses SET description_th = 'เพิ่มความสามารถฟื้นฟูร่างกาย' WHERE id = 461;
UPDATE statuses SET description_th = 'ปิดใช้งาน พลังป้องกัน -50 บล็อกและหลบไม่ทำงาน' WHERE id = 462;
UPDATE statuses SET description_th = 'เกรดโจมตี +1, ดาเมจมอนสเตอร์ +50%, เจาะเกราะไฟเพิ่มตาม INT' WHERE id = 464;
UPDATE statuses SET description_th = 'A.R. +1, ดาเมจมอนสเตอร์ +50%, เจาะเกราะไฟ +1 ต่อ 5 INT เพิ่ม' WHERE id = 465;
UPDATE statuses SET description_th = 'เกรดโจมตี +1, พลังโจมตี +30%, ความเร็วเคลื่อนที่และขีดจำกัดเพิ่ม' WHERE id = 466;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +30%, ความเร็วเคลื่อนที่และขีดจำกัดเพิ่ม' WHERE id = 467;
UPDATE statuses SET description_th = 'ฟื้นฟู HP/SP +100, ดาเมจมอนสเตอร์ +5%, ความเร็วเคลื่อนที่เพิ่ม' WHERE id = 468;
UPDATE statuses SET description_th = 'เพิ่มความเร็วโจมตีและเคลื่อนที่ 10% ชั่วคราว' WHERE id = 469;
UPDATE statuses SET description_th = 'เพิ่มธาตุน้ำแข็งให้อาวุธทื่อ' WHERE id = 470;
UPDATE statuses SET description_th = 'ปืนกำลังเย็นตัว ไม่สามารถใช้สกิล แต่โจมตีปกติได้' WHERE id = 471;
UPDATE statuses SET description_th = 'D.R. +1 (เกิน Lv.11), พลังป้องกัน +1%, ภูมิคุ้มกัน +2, เวลาร่าย -1.5%' WHERE id = 472;
UPDATE statuses SET description_th = 'ดาเมจสกิล x1.3 ระดับ buff -1 เมื่อสกิลโดน' WHERE id = 473;
UPDATE statuses SET description_th = 'ละเว้นพลังป้องกัน 60, ละเว้นบล็อก, ละเว้น 50% พลังป้องกันโล่, 50% สตั้น' WHERE id = 474;
UPDATE statuses SET description_th = 'ละเว้นพลังป้องกัน 80, ละเว้นบล็อก, ละเว้น 50% พลังป้องกันโล่' WHERE id = 475;
UPDATE statuses SET description_th = '[Lv 10] เกรดป้องกัน +1, อัตราหลบ +40, ความเร็วเคลื่อนที่ +20%' WHERE id = 476;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่ชั่วคราว ได้รับดาเมจเพิ่ม' WHERE id = 477;
UPDATE statuses SET description_th = 'ละเว้นพลังป้องกัน 50, ละเว้นหลบ, 10% โอกาส [Slow] ต่อ PvP' WHERE id = 478;
UPDATE statuses SET description_th = 'เพิ่มต้านทานทั้งหมดของตัวละคร' WHERE id = 364;
UPDATE statuses SET description_th = 'ลดดาเมจสกิลของตัวละคร' WHERE id = 370;
