-- Batch 21: T-U section (1773-1853)

UPDATE statuses SET description_th = 'ได้รับพิษ otite ต้านทานสายฟ้าลด' WHERE id = 1773;
UPDATE statuses SET description_th = 'buff ระดับ Autobaron T เพิ่มพลังโจมตี ความเร็วโจมตี เจาะเกราะ' WHERE id = 1774;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันทีมด้วยยุทธวิธี' WHERE id = 1776;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์สแตนซ์ 30%' WHERE id = 1777;
UPDATE statuses SET description_th = 'พลังป้องกัน +20, ภูมิคุ้มกัน +10, HP สูงสุด +20000, ดาเมจทั้งหมด -5%' WHERE id = 1789;
UPDATE statuses SET description_th = 'โฟกัสเป้าหมาย เพิ่มคริติคอล' WHERE id = 1790;
UPDATE statuses SET description_th = 'DEX +10, A.R. +2, ความแม่นยำ +20, เจาะเกราะ +50, ดาเมจมอนสเตอร์เพิ่ม' WHERE id = 1791;
UPDATE statuses SET description_th = 'เจาะเกราะ +15' WHERE id = 1794;
UPDATE statuses SET description_th = 'เพิ่ม HP สูงสุด และ SP สูงสุด' WHERE id = 1795;
UPDATE statuses SET description_th = 'ลดพลังป้องกันทั้งหมด' WHERE id = 1796;
UPDATE statuses SET description_th = 'ทำงานเมื่อโจมตีปกติโดนเป้าหมาย เพิ่มดาเมจโจมตีปกติ' WHERE id = 1797;
UPDATE statuses SET description_th = 'เพิ่มบล็อก หลบ พลังป้องกัน HP สูงสุดทันที แต่ลดความเร็วเคลื่อนที่' WHERE id = 1799;
UPDATE statuses SET description_th = 'ลด A.R., D.R., พลังโจมตี, พลังป้องกันอย่างผิดปกติ' WHERE id = 1800;
UPDATE statuses SET description_th = 'ดาเมจเวทย์ที่ได้รับ -10%, ดาเมจยิงที่ได้รับ +10%' WHERE id = 1802;
UPDATE statuses SET description_th = 'ลดเวลาถูกผลักกลับ' WHERE id = 1803;
UPDATE statuses SET description_th = 'A.R. +1, D.R. +1, ความเร็วเคลื่อนที่ +5%' WHERE id = 1804;
UPDATE statuses SET description_th = 'A.R. +1, D.R. +1, ดาเมจเวทย์ -10%, มีโอกาส debuff ศัตรูที่โจมตี' WHERE id = 1807;
UPDATE statuses SET description_th = 'ละเว้นค่าต้านทานธาตุของเป้าหมาย 3 จุด' WHERE id = 1808;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี ดาเมจคริติคอล ระยะ และระยะกว้าง' WHERE id = 1809;
UPDATE statuses SET description_th = 'เจาะเกราะสายฟ้า +7, พลังป้องกัน +3, ภูมิคุ้มกัน +3, ต้านทานสายฟ้า +5' WHERE id = 1810;
UPDATE statuses SET description_th = 'A.R. +1, D.R. +1, พลังโจมตี +25%, พลังป้องกัน +10, ดาเมจมอนสเตอร์ +60%' WHERE id = 1811;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้' WHERE id = 1812;
UPDATE statuses SET description_th = 'ลดเวลา cooldown สกิล -2 วินาที' WHERE id = 1813;
UPDATE statuses SET description_th = 'เร่งความเร็วเร็วเกินไป ต้องรอก่อนใช้อีกครั้ง' WHERE id = 1814;
UPDATE statuses SET description_th = 'เพิ่มความเร็วโจมตีและเคลื่อนที่เกินขีดจำกัด' WHERE id = 1815;
UPDATE statuses SET description_th = 'เพิ่ม cooldown สกิล +5 วินาที' WHERE id = 1816;
UPDATE statuses SET description_th = 'การกระทำถูกเปลี่ยนแปลงในพื้นที่กาลอวกาศผิดปกติ' WHERE id = 1817;
UPDATE statuses SET description_th = 'เพิ่มฟังก์ชัน Auto Baron' WHERE id = 1820;
UPDATE statuses SET description_th = 'พลังโจมตีเวทย์ +10%, เจาะเกราะเวทย์ +10, ดาเมจมอนสเตอร์ +20%' WHERE id = 1821;
UPDATE statuses SET description_th = 'พลังโจมตี +100%, ดาเมจคริติคอล +50%, คริติคอล +30, เจาะเกราะกายภาพ +20' WHERE id = 1824;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีหลายค่า เพิ่มค่าประสบการณ์การต่อสู้และสแตนซ์' WHERE id = 1826;
UPDATE statuses SET description_th = '[Lv 1] [อากาศ] D.R. -1, ต้านทานจิต -2 [พื้นดิน] D.R. -1, ต้านทานจิตลด' WHERE id = 1827;
UPDATE statuses SET description_th = 'เพิ่มค่าส่วนใหญ่' WHERE id = 1830;
UPDATE statuses SET description_th = 'ดาเมจที่ได้รับทั้งหมดลด และดาเมจสกิลเกินค่าหนึ่งจะลดลง' WHERE id = 1832;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่และพลังป้องกัน' WHERE id = 1833;
UPDATE statuses SET description_th = 'เพิ่มดาเมจต่อมอนสเตอร์' WHERE id = 1834;
UPDATE statuses SET description_th = 'เพิ่มความสามารถตามคู่มือฝึก' WHERE id = 1836;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์ ค่าประสบการณ์สแตนซ์ อัตราดรอป 20%' WHERE id = 1837;
UPDATE statuses SET description_th = 'ล่องหน ศัตรูมองไม่เห็น ไม่สามารถใช้สกิลบางตัว สามารถตรวจจับได้' WHERE id = 1839;
UPDATE statuses SET description_th = 'ภายใต้การปกป้องของ Treasure Golem อัตราดรอปไอเทมเพิ่มอย่างมาก' WHERE id = 1840;
UPDATE statuses SET description_th = '[ระดับ 10] ดาเมจยิง +20%, พลังป้องกัน -10%' WHERE id = 1842;
UPDATE statuses SET description_th = 'จากศรัทธาอันแรงกล้า ดาเมจมอนสเตอร์เพิ่ม' WHERE id = 1843;
UPDATE statuses SET description_th = 'ลดดาเมจประชิด ยิง เวทย์' WHERE id = 1844;
UPDATE statuses SET description_th = 'ละเว้นค่าต้านทานธาตุของเป้าหมาย 2 จุด' WHERE id = 1845;
UPDATE statuses SET description_th = 'เพิ่มความสามารถโจมตีอย่างรุนแรง' WHERE id = 1847;
UPDATE statuses SET description_th = 'มอบเอฟเฟกต์พิเศษให้สมาชิกทีม' WHERE id = 1848;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและดาเมจคริติคอล' WHERE id = 1850;
UPDATE statuses SET description_th = '[มอนสเตอร์] D.R. -1, [PvP] D.R. -2, HP สูงสุด -50%' WHERE id = 1851;
UPDATE statuses SET description_th = 'พลังโจมตี -3%' WHERE id = 1852;
UPDATE statuses SET description_th = 'ละเว้นต้านทานไฟ' WHERE id = 1853;
