-- Batch 19: S section (1591-1653)

UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะ' WHERE id = 1591;
UPDATE statuses SET description_th = 'เพิ่มฟื้นฟู HP' WHERE id = 1592;
UPDATE statuses SET description_th = 'ผนึกมอนสเตอร์' WHERE id = 1593;
UPDATE statuses SET description_th = 'ดาเมจประชิดที่ได้รับ +1% (ครึ่งหนึ่งสำหรับ PvP)' WHERE id = 1594;
UPDATE statuses SET description_th = 'ละเว้นค่าต้านทานธาตุของเป้าหมาย 2 จุด' WHERE id = 1595;
UPDATE statuses SET description_th = 'พลังป้องกัน -3, ภูมิคุ้มกัน -1, ต้านทานทั้งหมด -5, ต้านทาน debuff -5 ต่อระดับ' WHERE id = 1601;
UPDATE statuses SET description_th = 'ป้องกันล้มลงโดยลดดาเมจสกิลธาตุ' WHERE id = 1602;
UPDATE statuses SET description_th = 'พลังโจมตี +100%, ความแม่นยำ +10, เจาะเกราะกายภาพ +10, A.R. +1' WHERE id = 1603;
UPDATE statuses SET description_th = '[PvP] D.R. -1, ความเร็วเคลื่อนที่ -30%, ภูมิคุ้มกัน -10 [มอนสเตอร์] D.R. -1, พลังโจมตีลด' WHERE id = 1604;
UPDATE statuses SET description_th = 'ทำดาเมจโดยละเว้นประเภทเกราะ' WHERE id = 1605;
UPDATE statuses SET description_th = 'เพิ่มเวลาร่ายสกิล ลดความเร็วเคลื่อนที่และพลังป้องกัน ลด SP ชั่วคราว' WHERE id = 1606;
UPDATE statuses SET description_th = 'ภูมิคุ้มกัน -3, พลังป้องกัน -3, ดาเมจเพิ่มสำหรับ Violante และ Shades' WHERE id = 1607;
UPDATE statuses SET description_th = 'สิ่งเรียกของ Violante จะโจมตีศัตรูนี้' WHERE id = 1608;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน ถ้าเอาชนะศัตรูจะแรงขึ้น' WHERE id = 1609;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีโดยรวบรวมเงาศัตรู' WHERE id = 1610;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี ถ้าเอาชนะศัตรูจะแรงขึ้น' WHERE id = 1611;
UPDATE statuses SET description_th = 'ซ่อนตัวในความมืดโดยรวบรวมเงาศัตรู' WHERE id = 1612;
UPDATE statuses SET description_th = 'SP +100 ต่อระดับ, เจาะเกราะสายฟ้า +1 ต่อระดับ, คริติคอล +1 ต่อระดับ' WHERE id = 1613;
UPDATE statuses SET description_th = 'เจาะเกราะ +5, ความเร็วโจมตี +10%, คริติคอล +10 ไม่ซ้อนกับ White Claw' WHERE id = 1616;
UPDATE statuses SET description_th = 'เพิ่มความแม่นยำ ความเร็วโจมตี และเจาะเกราะชั่วคราว' WHERE id = 1617;
UPDATE statuses SET description_th = 'INT +10, ความเร็วร่ายสกิล -10%' WHERE id = 1618;
UPDATE statuses SET description_th = 'พลังโจมตี +10%, เจาะเกราะ +10, คริติคอล +10, ดาเมจคริติคอล +20%' WHERE id = 1619;
UPDATE statuses SET description_th = 'ภายใต้การปกป้องของ Sheol ความสามารถในการต่อสู้เพิ่มอย่างมาก' WHERE id = 1621;
UPDATE statuses SET description_th = 'ยกเลิกดาเมจที่ได้รับทั้งหมด' WHERE id = 1623;
UPDATE statuses SET description_th = 'เพิ่ม D.R. พลังป้องกัน และต้านทานเวทย์' WHERE id = 1624;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี ความเร็วโจมตี และความเร็วเคลื่อนที่ชั่วคราว' WHERE id = 1625;
UPDATE statuses SET description_th = 'A.R. +1 ถ้าเก็บเหรียญถึงจบจะได้รับค่าประสบการณ์เพิ่ม' WHERE id = 1627;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +25%, โจมตีปกติใส่ [Surveillance]' WHERE id = 1629;
UPDATE statuses SET description_th = 'ละเว้นดาเมจโจมตียิงและฟื้นฟู HP เท่ากับดาเมจ' WHERE id = 1630;
UPDATE statuses SET description_th = 'DEX, AGI และคริติคอลเพิ่ม' WHERE id = 1631;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตียิง' WHERE id = 1633;
UPDATE statuses SET description_th = 'เพิ่มสกิลโจมตียิง' WHERE id = 1635;
UPDATE statuses SET description_th = 'ลดช่วงห่างโจมตียิงด้วยการหายใจสั้น' WHERE id = 1637;
UPDATE statuses SET description_th = 'ปลดปล่อยพลัง Abyss เพิ่มพลังโจมตี ความเร็วโจมตี พลังป้องกัน ต้านทานเวทย์' WHERE id = 1638;
UPDATE statuses SET description_th = 'เพิ่ม HP ด้วยเสียงตะโกน' WHERE id = 1639;
UPDATE statuses SET description_th = 'ระยะเวลา: 300 วินาที ยิ่ง PC ใกล้มากยิ่งแรง' WHERE id = 1641;
UPDATE statuses SET description_th = 'จำกัดระยะมองเห็น ความเร็วเคลื่อนที่ -12%' WHERE id = 1643;
UPDATE statuses SET description_th = 'ตรวจสอบ colony ที่เริ่มล้อม ดาเมจจาก Castle Crusher ลดอย่างมาก' WHERE id = 1645;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่และพลังป้องกัน แต่เพิ่มพลังโจมตี ความเร็วโจมตี ความแม่นยำ คริติคอล' WHERE id = 1646;
UPDATE statuses SET description_th = 'ตรวจสอบ colony ที่เริ่มล้อม ดาเมจจาก Castle Crusher ลดอย่างมาก' WHERE id = 1647;
UPDATE statuses SET description_th = 'ตรวจสอบ colony ที่เริ่มล้อม ดาเมจจาก Castle Crusher ลดอย่างมาก' WHERE id = 1648;
UPDATE statuses SET description_th = 'จุดเปลวไฟอันแรงกล้าในหัวใจ Pioneer' WHERE id = 1649;
UPDATE statuses SET description_th = 'มองเห็นถูกบัง ลดความแม่นยำและความเร็วเคลื่อนที่อย่างมาก' WHERE id = 1650;
UPDATE statuses SET description_th = 'ไม่ถูกโจมตีตรงจากศัตรู' WHERE id = 1653;
