-- Batch 18: R remainder + S start (1521-1590)

UPDATE statuses SET description_th = 'พลังโจมตี -10%, ภูมิคุ้มกัน -5, หลบ -10, แม่นยำ -10' WHERE id = 1521;
UPDATE statuses SET description_th = 'พลังโจมตี +15%, เจาะเกราะ +7, ดาเมจมอนสเตอร์ +10%, สถานะทั้งหมด +5' WHERE id = 1522;
UPDATE statuses SET description_th = 'พลังป้องกัน -300, ต้านทานทั้งหมด -75, บล็อก -75, หลบ -75' WHERE id = 1523;
UPDATE statuses SET description_th = '[Lv 10] A.R. +1, เจาะเกราะ +15, ดาเมจมอนสเตอร์เพิ่ม' WHERE id = 1526;
UPDATE statuses SET description_th = '[Lv 10] A.R. +1, เจาะเกราะ +28, ดาเมจมอนสเตอร์เพิ่ม' WHERE id = 1527;
UPDATE statuses SET description_th = 'เพิ่มต้านทานเวทย์ทั้งหมด' WHERE id = 1528;
UPDATE statuses SET description_th = 'พลังโจมตี +10%, ดาเมจมอนสเตอร์ +20%, เจาะเกราะจิตเพิ่ม' WHERE id = 1530;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +20%, ดาเมจมอนสเตอร์ +40%' WHERE id = 1531;
UPDATE statuses SET description_th = 'A.R. เพิ่มตามสัดส่วนระดับ buff พลังโจมตีเพิ่ม' WHERE id = 1532;
UPDATE statuses SET description_th = 'เพิ่มฟื้นฟู HP และพลังป้องกัน' WHERE id = 1533;
UPDATE statuses SET description_th = 'เพิ่มอัตราฟื้นฟู HP และ SP' WHERE id = 1534;
UPDATE statuses SET description_th = 'ฟื้นฟู HP/SP อย่างรวดเร็วตลอดระยะเวลา' WHERE id = 1535;
UPDATE statuses SET description_th = 'จิตวิญญาณถูกกักโดย Navas ลดพลังโจมตี ความเร็วโจมตี เพิ่มดาเมจที่ได้รับ' WHERE id = 1536;
UPDATE statuses SET description_th = 'จำกัดการใช้สกิลและไอเทมด้วยพลัง Abyss' WHERE id = 1538;
UPDATE statuses SET description_th = 'พลังป้องกันเพิ่ม ความแม่นยำเพิ่ม เจาะเกราะกายภาพเพิ่ม ดาเมจทั้งหมด -15%' WHERE id = 1539;
UPDATE statuses SET description_th = 'เต้นรำน่าเกลียดของ Reve ลดพลังโจมตี เวลาร่ายสกิล และต้านทานจิต' WHERE id = 1542;
UPDATE statuses SET description_th = 'สกิลที่ 4 ของสแตนซ์ [Peacefulness]' WHERE id = 1543;
UPDATE statuses SET description_th = 'ลุกขึ้นและยืนหยัดชั่วขณะ' WHERE id = 1544;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี' WHERE id = 1546;
UPDATE statuses SET description_th = 'พลังป้องกัน +2, ดาเมจมอนสเตอร์ +10%, เจาะเกราะ +1, สถานะทั้งหมด +1 ต่อระดับ' WHERE id = 1548;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและเจาะเกราะสายฟ้า' WHERE id = 1549;
UPDATE statuses SET description_th = 'ยกเลิก debuff และเพิ่มต้านทาน' WHERE id = 1551;
UPDATE statuses SET description_th = 'ลดความเร็วโจมตีและเคลื่อนที่ชั่วคราว' WHERE id = 1552;
UPDATE statuses SET description_th = 'ลดพลังโจมตีและ A.R.' WHERE id = 1554;
UPDATE statuses SET description_th = 'ดนตรีจากใจของ DoTre' WHERE id = 1555;
UPDATE statuses SET description_th = 'ตรึงศัตรูไว้ และลด HP อย่างต่อเนื่อง' WHERE id = 1556;
UPDATE statuses SET description_th = 'ตรึงศัตรูไว้ และลด HP อย่างต่อเนื่อง' WHERE id = 1557;
UPDATE statuses SET description_th = 'ป้องกันโจมตีเวทย์และ debuff จากศัตรู เพิ่มต้านทานไฟ น้ำแข็ง สายฟ้า' WHERE id = 1558;
UPDATE statuses SET description_th = 'ตัวละครที่ได้รับมอบหมาย Mission Rotation' WHERE id = 1559;
UPDATE statuses SET description_th = 'พลังโจมตี +7%, เจาะเกราะ +15, ดาเมจมอนสเตอร์ +10%, สถานะทั้งหมด +5' WHERE id = 1560;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและความเร็วโจมตี' WHERE id = 1561;
UPDATE statuses SET description_th = 'อยู่ใน Rumble Fight กฎการต่อสู้แตกต่าง' WHERE id = 1562;
UPDATE statuses SET description_th = 'ค่า SEN: กำหนดเวลาร่ายสกิลและพลังโจมตีสิ่งเรียก' WHERE id = 1564;
UPDATE statuses SET description_th = 'ความแม่นยำ +10, เจาะเกราะกายภาพ +10, A.R. +1' WHERE id = 1565;
UPDATE statuses SET description_th = 'เพิ่ม HP สูงสุดตาม HP และพลังป้องกันของโล่ ลดดาเมจที่ได้รับ' WHERE id = 1567;
UPDATE statuses SET description_th = 'สร้างโล่ป้องกันพันธมิตร' WHERE id = 1568;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี ความแม่นยำ และคริติคอลชั่วคราว' WHERE id = 1569;
UPDATE statuses SET description_th = 'สามารถใช้สกิล Sad Ending ได้' WHERE id = 1570;
UPDATE statuses SET description_th = 'ในพื้นที่ปลอดภัย ไม่สามารถโจมตีหรือถูกโจมตี' WHERE id = 1571;
UPDATE statuses SET description_th = 'เวทย์ลึกลับเปิดใช้งาน เพิ่มประสิทธิภาพโจมตี/ป้องกัน' WHERE id = 1572;
UPDATE statuses SET description_th = 'เพิ่มความสามารถของ Hildegard' WHERE id = 1573;
UPDATE statuses SET description_th = 'ละเว้นพลังป้องกัน +2% ต่อระดับ (สูงสุด 10), A.R. +1, พลังโจมตีเพิ่ม' WHERE id = 1574;
UPDATE statuses SET description_th = 'เจาะเกราะ +2, เวลาร่าย -3%, ดาเมจโจมตีปกติ +20% ต่อระดับ' WHERE id = 1575;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน/ภูมิคุ้มกัน/ความเร็วเคลื่อนที่' WHERE id = 1576;
UPDATE statuses SET description_th = 'เพิ่มความสามารถป้องกัน สามารถเอาชนะศัตรูได้' WHERE id = 1578;
UPDATE statuses SET description_th = 'ลดความแม่นยำ หยุดเคลื่อนไหวจากพายุทราย ตัวละครบินตกลงมา' WHERE id = 1579;
UPDATE statuses SET description_th = 'ได้รับสิทธิ์เข้าดันเจี้ยนสวรรค์' WHERE id = 1580;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +10%, เจาะเกราะ +5, ภูมิคุ้มกัน +5, คริติคอลเพิ่ม' WHERE id = 1581;
UPDATE statuses SET description_th = 'ฟื้นฟู HP/SP อย่างรวดเร็วตลอดระยะเวลา' WHERE id = 1582;
UPDATE statuses SET description_th = 'D.R. -2 จำกัดการใช้สกิลและยาเวท' WHERE id = 1583;
UPDATE statuses SET description_th = 'ล่องหน พลังโจมตี -25%, ความเร็วเคลื่อนที่ -25%' WHERE id = 1585;
UPDATE statuses SET description_th = 'สกิลที่ใช้จะแรงขึ้นตามสัดส่วนระดับ buff' WHERE id = 1587;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี' WHERE id = 1588;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน' WHERE id = 1589;
UPDATE statuses SET description_th = 'เพิ่มภูมิคุ้มกัน' WHERE id = 1590;
