-- Batch 17: R section (1471-1520)

UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้และสแตนซ์ 30%' WHERE id = 1471;
UPDATE statuses SET description_th = 'ต้านทานจิต -5' WHERE id = 1472;
UPDATE statuses SET description_th = 'พลังโจมตี +10% ต่อระดับ, เจาะเกราะ +3, ความเร็วโจมตี +3%' WHERE id = 1473;
UPDATE statuses SET description_th = 'สิ่งเรียกของ Isaac จะโจมตีศัตรูนี้' WHERE id = 1474;
UPDATE statuses SET description_th = '[Lv 1] พลังโจมตี +40%, ดาเมจมอนสเตอร์ +20%, บล็อก +10, ดาเมจประชิด -10%' WHERE id = 1475;
UPDATE statuses SET description_th = 'ระยะเวลา: 20 วินาที ความเร็วเคลื่อนที่ -10%' WHERE id = 1476;
UPDATE statuses SET description_th = 'D.R. -1, พลังป้องกัน -15, [PvP] ความเร็วเคลื่อนที่ -90%, ระยะเวลา: 10 วินาที' WHERE id = 1477;
UPDATE statuses SET description_th = 'ลดดาเมจสกิลของ Queen Eater' WHERE id = 1478;
UPDATE statuses SET description_th = 'เพิ่มดาเมจตามดาเมจที่ได้รับขณะอยู่ในสถานะ Rage' WHERE id = 1479;
UPDATE statuses SET description_th = 'เพิ่มความเร็วเคลื่อนที่และความเร็วโจมตี' WHERE id = 1482;
UPDATE statuses SET description_th = 'ต้านทาน debuff -30, [PvP] ความเร็วเคลื่อนที่ -30%' WHERE id = 1483;
UPDATE statuses SET description_th = 'พลังเวทย์มหากาพย์ล้อมรอบร่างกาย' WHERE id = 1484;
UPDATE statuses SET description_th = 'เตรียมโจมตีถัดไปหลังโจมตีต่อเนื่อง' WHERE id = 1489;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีชั่วคราว และละเว้นพลังป้องกันศัตรูเพิ่ม' WHERE id = 1490;
UPDATE statuses SET description_th = 'ดาเมจ PvP +5% เมื่อโดนศัตรูใน [Visual Confusion]' WHERE id = 1491;
UPDATE statuses SET description_th = 'ดาเมจ PvP +5% เมื่อโดนศัตรูใน [Visual Confusion]' WHERE id = 1492;
UPDATE statuses SET description_th = 'เพิ่ม D.R. และเจาะเกราะ' WHERE id = 1493;
UPDATE statuses SET description_th = 'กลายเป็นเป้าหมายของ Reaper' WHERE id = 1494;
UPDATE statuses SET description_th = 'พิจารณาผลลัพธ์ที่ดีที่สุดตามสถานการณ์' WHERE id = 1495;
UPDATE statuses SET description_th = 'A.R. +2, D.R. +2, พลังป้องกัน +10, HP +3000' WHERE id = 1496;
UPDATE statuses SET description_th = 'เพิ่ม D.R. +1' WHERE id = 1497;
UPDATE statuses SET description_th = 'เพิ่มฟื้นฟู SP' WHERE id = 1499;
UPDATE statuses SET description_th = 'เพิ่มความสามารถโจมตี แต่ลด HP อย่างต่อเนื่อง' WHERE id = 1500;
UPDATE statuses SET description_th = 'เพิ่มความเร็วเคลื่อนที่อย่างรวดเร็วชั่วคราว' WHERE id = 1503;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีเป็นเวลา 30 วินาที' WHERE id = 1504;
UPDATE statuses SET description_th = 'ยิงกระสุนที่มีพลังศักดิ์สิทธิ์' WHERE id = 1506;
UPDATE statuses SET description_th = 'ฟื้นฟูสภาพที่เสียหาย และไม่ได้รับดาเมจชั่วคราว' WHERE id = 1507;
UPDATE statuses SET description_th = 'ฉีดพลังวิญญาณเข้าดาบ' WHERE id = 1508;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตีเพิ่ม, เจาะเกราะไฟเพิ่ม, บล็อกเพิ่ม' WHERE id = 1509;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตีเพิ่ม, เจาะเกราะสายฟ้าเพิ่ม, บล็อกเพิ่ม' WHERE id = 1510;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตีเพิ่ม, เจาะเกราะจิตเพิ่ม, บล็อกเพิ่ม' WHERE id = 1511;
UPDATE statuses SET description_th = 'ลดพลังโจมตี' WHERE id = 1512;
UPDATE statuses SET description_th = 'ลดความแม่นยำ' WHERE id = 1513;
UPDATE statuses SET description_th = 'ลดพลังป้องกัน' WHERE id = 1514;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันและต้านทานธาตุ สะท้อนดาเมจ 50%' WHERE id = 1515;
UPDATE statuses SET description_th = 'BFG กำลังเย็นตัว ไม่สามารถโจมตีปกติหรือใช้สกิลได้' WHERE id = 1516;
UPDATE statuses SET description_th = 'เพิ่มอัตราฟื้นฟู HP และ SP ในรัศมี' WHERE id = 1517;
UPDATE statuses SET description_th = '[Lv 10] STR +5, CON +5, พลังโจมตี +20%, ดาเมจมอนสเตอร์ +20%' WHERE id = 1519;
