-- Batch 20: S section continued (1654-1724)

UPDATE statuses SET description_th = 'พลังโจมตี -10%, ความเร็วโจมตี -15%' WHERE id = 1654;
UPDATE statuses SET description_th = 'พลังโจมตี -10%, ความเร็วโจมตี -15%' WHERE id = 1656;
UPDATE statuses SET description_th = 'พลังป้องกัน +20, ภูมิคุ้มกัน +10, HP สูงสุด +30000, ดาเมจทั้งหมด -10%, D.R. +1' WHERE id = 1657;
UPDATE statuses SET description_th = 'คริติคอลทำงานขณะใช้สกิล' WHERE id = 1658;
UPDATE statuses SET description_th = 'ล่องหนถูกยกเลิก เข้าสู่โหมดรอ ไม่สามารถโจมตีหรือใช้สกิล' WHERE id = 1659;
UPDATE statuses SET description_th = 'ห้ามใช้สกิลตลอดระยะเวลา' WHERE id = 1662;
UPDATE statuses SET description_th = 'ภูมิคุ้มกัน -5, ต้านทานสายฟ้า -10' WHERE id = 1663;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี เพิ่มเจาะเกราะกายภาพสำหรับ Vanessa' WHERE id = 1664;
UPDATE statuses SET description_th = 'ไม่สามารถเคลื่อนไหว และเดินไปที่อื่น' WHERE id = 1667;
UPDATE statuses SET description_th = 'เพิ่มภูมิคุ้มกัน' WHERE id = 1668;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่ มอนสเตอร์ลดพลังโจมตีและความเร็วโจมตีด้วย' WHERE id = 1669;
UPDATE statuses SET description_th = 'ได้กลิ่นเลือดและตื่นเต้น เพิ่มพลังโจมตีและฟื้นฟู HP' WHERE id = 1671;
UPDATE statuses SET description_th = 'เพิ่มดาเมจมอนสเตอร์ 10%, ความเร็วโจมตี 10%' WHERE id = 1672;
UPDATE statuses SET description_th = 'A.R. +1, เวลาร่าย -50%, ดาเมจทั้งหมด -10%' WHERE id = 1673;
UPDATE statuses SET description_th = 'สกิลสแตนซ์ Sneedronninge จะแรงขึ้น' WHERE id = 1674;
UPDATE statuses SET description_th = 'ล่องหน ได้รับ [Sniper Patience] หลังหมดล่องหน' WHERE id = 1675;
UPDATE statuses SET description_th = 'เกรดป้องกัน +1, ดาเมจที่ได้รับ -10%' WHERE id = 1676;
UPDATE statuses SET description_th = 'D.R. +1, พลังป้องกัน +20, ภูมิคุ้มกัน +20, ต้านทาน +20' WHERE id = 1677;
UPDATE statuses SET description_th = 'ขณะล่องหน ความเร็วเคลื่อนที่ +30%' WHERE id = 1678;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +15%, เจาะเกราะ +5, คริติคอล +10, ความแม่นยำ +10' WHERE id = 1679;
UPDATE statuses SET description_th = 'เกล็ดหิมะทำดาเมจต่อเนื่องให้ศัตรูรอบข้าง' WHERE id = 1680;
UPDATE statuses SET description_th = 'D.R. -1, พลังป้องกัน -12, ความเร็วโจมตี -12%' WHERE id = 1683;
UPDATE statuses SET description_th = 'หมุนเวียนสนามแม่เหล็กที่ชาร์จไว้' WHERE id = 1686;
UPDATE statuses SET description_th = 'เพิ่มความสามารถเกินขีดจำกัดทางกายภาพ' WHERE id = 1687;
UPDATE statuses SET description_th = 'พลังโจมตี -30%, เจาะเกราะ -20' WHERE id = 1688;
UPDATE statuses SET description_th = 'ฟื้นฟู SP 300 ทุก 3 วินาที เป็นเวลา 15 วินาที' WHERE id = 1690;
UPDATE statuses SET description_th = 'เมื่อใช้สกิลโจมตี พลังโจมตีเพิ่มตามสัดส่วน SP สูงสุด และดูดซับ SP' WHERE id = 1693;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีไฟ ต้านทานไฟ และโอกาส [Burn] และความแม่นยำ' WHERE id = 1694;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี ความเร็วโจมตี และคริติคอล' WHERE id = 1696;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและภูมิคุ้มกัน' WHERE id = 1697;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีน้ำแข็ง ต้านทานน้ำแข็ง และโอกาส [Freeze]' WHERE id = 1698;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะกายภาพ การหลบ ภูมิคุ้มกัน และต้านทาน debuff' WHERE id = 1699;
UPDATE statuses SET description_th = 'ส่งศัตรูและพันธมิตรไปมิติอื่น' WHERE id = 1700;
UPDATE statuses SET description_th = 'ระยะเวลา 10 วินาที ฟื้นฟู HP เป้าหมายไม่ได้รับผลกระทบ' WHERE id = 1701;
UPDATE statuses SET description_th = 'ดาเมจสกิล +20% ต่อระดับ (สูงสุดระดับ 10)' WHERE id = 1704;
UPDATE statuses SET description_th = 'ไม่สามารถร่ายสกิลได้' WHERE id = 1705;
UPDATE statuses SET description_th = 'เพิ่มต้านทาน debuff ชั่วคราว ลดดาเมจเวทย์ที่ได้รับ' WHERE id = 1706;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีต่อมอนสเตอร์' WHERE id = 1707;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะจิต A.R. และภูมิคุ้มกัน ยกเลิกเมื่อเปลี่ยนสแตนซ์' WHERE id = 1711;
UPDATE statuses SET description_th = 'เพิ่มต้านทาน debuff และต้านทานจิตชั่วคราว' WHERE id = 1712;
UPDATE statuses SET description_th = 'ความเร็วเคลื่อนที่เพิ่มอย่างรวดเร็วชั่วครู่' WHERE id = 1713;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่ และมีเอฟเฟกต์เพิ่มสำหรับสกิลถัดไปของ Hildegard' WHERE id = 1715;
UPDATE statuses SET description_th = 'สกิลสแตนซ์ Inferno จะแรงขึ้น' WHERE id = 1717;
UPDATE statuses SET description_th = 'ความแม่นยำ +100, เวลาร่าย -20%, โจมตีปกติรับประกันคริติคอล' WHERE id = 1718;
UPDATE statuses SET description_th = 'พร้อมสำหรับการกระทำถัดไป' WHERE id = 1719;
UPDATE statuses SET description_th = 'โหมดรอหลังยกเลิกล่องหน ไม่สามารถใช้สกิลชั่วคราว' WHERE id = 1720;
UPDATE statuses SET description_th = 'D.R. +1, พลังป้องกัน +10, ภูมิคุ้มกัน +25, ละเว้น debuff' WHERE id = 1722;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +10%, เจาะเกราะ +25, ละเว้น [BLK] และ [Parry]' WHERE id = 1723;
UPDATE statuses SET description_th = 'สามารถเข้า Quiritatio, Einherjar ได้' WHERE id = 1724;
