-- Batch 9: E-section (620-690)

UPDATE statuses SET description_th = 'เพิ่มอัตราเจาะเกราะจากอาวุธและสแตนซ์เป็นระยะเวลาหนึ่ง' WHERE id = 620;
UPDATE statuses SET description_th = 'เพิ่มอัตราดรอปไอเทม 10%' WHERE id = 621;
UPDATE statuses SET description_th = 'เพิ่มความสามารถตัวเองผ่านพลังศักดิ์สิทธิ์' WHERE id = 622;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและพลังป้องกัน' WHERE id = 623;
UPDATE statuses SET description_th = 'เพิ่ม D.R. และพลังป้องกันอย่างมาก' WHERE id = 624;
UPDATE statuses SET description_th = 'HP สูงสุด +24000, ฟื้นฟู HP ธรรมชาติ +7200' WHERE id = 625;
UPDATE statuses SET description_th = 'HP สูงสุด +24000, ฟื้นฟู HP ธรรมชาติ +7200' WHERE id = 626;
UPDATE statuses SET description_th = 'ใช้กระสุนลูกศรคม' WHERE id = 628;
UPDATE statuses SET description_th = '[PvP]: ความเร็วโจมตี -30%, ความเร็วเคลื่อนที่ -20%, เวลาร่าย +20%, พลังป้องกัน -20%, ภูมิคุ้มกัน -10%' WHERE id = 630;
UPDATE statuses SET description_th = 'โจมตีของเป้าหมายเพิ่มธาตุสายฟ้า และต้านทานสายฟ้าเพิ่ม' WHERE id = 631;
UPDATE statuses SET description_th = 'เพิ่มค่าโจมตีโดยดูดซับพลังรอบข้าง' WHERE id = 632;
UPDATE statuses SET description_th = 'พลังป้องกัน -50%, ความเร็วเคลื่อนที่ -50%' WHERE id = 634;
UPDATE statuses SET description_th = 'เพิ่มธาตุสายฟ้าชั่วคราว และเพิ่มต้านทานสายฟ้า' WHERE id = 635;
UPDATE statuses SET description_th = '[PvP]: ความเร็วโจมตี -30%, ความเร็วเคลื่อนที่ -20%, เวลาร่าย +20%, พลังป้องกัน -20%, ภูมิคุ้มกัน -10%' WHERE id = 637;
UPDATE statuses SET description_th = 'ลดพลังป้องกันและความเร็วเคลื่อนที่' WHERE id = 638;
UPDATE statuses SET description_th = 'ลดพลังป้องกันและความเร็วเคลื่อนที่' WHERE id = 641;
UPDATE statuses SET description_th = 'โจมตีเวทย์ละเว้นค่าต้านทานของศัตรูบางส่วนชั่วคราว' WHERE id = 643;
UPDATE statuses SET description_th = 'เพิ่มความสามารถโดยดูดซับพลังธาตุทั้งหมด ยกเลิกเมื่อเปลี่ยนสแตนซ์' WHERE id = 644;
UPDATE statuses SET description_th = 'เพิ่มสกิลเวทย์โดยรวบรวมพลังธาตุทั้งหมด ยกเลิกเมื่อเปลี่ยนสแตนซ์' WHERE id = 646;
UPDATE statuses SET description_th = '[ระดับ 12] D.R. -1, ต้านทานไฟ และพลังป้องกัน -12' WHERE id = 648;
UPDATE statuses SET description_th = 'สกิลงานของ Isaac' WHERE id = 650;
UPDATE statuses SET description_th = 'พลังโจมตีสายฟ้าเพิ่มอย่างมากเป็นเวลา 90 วินาที' WHERE id = 651;
UPDATE statuses SET description_th = 'เพิ่มระดับสกิลสแตนซ์ +1' WHERE id = 652;
UPDATE statuses SET description_th = 'พลังโจมตี +10%, ดาเมจมอนสเตอร์ +10%, คริติคอล +10, ความแม่นยำ +10' WHERE id = 653;
UPDATE statuses SET description_th = 'HP สูงสุดและพลังป้องกันเพิ่ม และดาเมจที่ได้รับสะสม' WHERE id = 656;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันชั่วคราว ลดดาเมจจากมอนสเตอร์' WHERE id = 657;
UPDATE statuses SET description_th = 'สถานะทั้งหมดเพิ่ม หลบสกิลยิง โจมตีปกติดาเมจ 2 เท่า' WHERE id = 658;
UPDATE statuses SET description_th = 'ลดพลังโจมตี ความเร็วโจมตี และความเร็วเคลื่อนที่ 50% และลด HP 30%' WHERE id = 659;
UPDATE statuses SET description_th = 'ลดพลังโจมตี ความเร็วโจมตี และความเร็วเคลื่อนที่ 50% และลด HP 30%' WHERE id = 660;
UPDATE statuses SET description_th = 'ลด HP อย่างต่อเนื่อง' WHERE id = 661;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีต่อประเภทปีศาจ' WHERE id = 662;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีต่อประเภทมนุษย์' WHERE id = 663;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีต่อประเภทไม่มีชีวิต' WHERE id = 664;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีต่อประเภทอมตะ' WHERE id = 665;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีต่อประเภทสัตว์ป่า' WHERE id = 666;
UPDATE statuses SET description_th = 'เพิ่มสถานะทั้งหมดของสมาชิกทั้งหมดชั่วคราว' WHERE id = 667;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันและ D.R.' WHERE id = 668;
UPDATE statuses SET description_th = 'เพิ่มความสามารถทางกายภาพสูงสุด' WHERE id = 669;
UPDATE statuses SET description_th = 'เพิ่มความสามารถส่วนใหญ่ 20% ไม่ซ้อนกับ Touch of Heaven' WHERE id = 670;
UPDATE statuses SET description_th = 'กันตายขณะ Zealot ทำงาน' WHERE id = 674;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +10%, สถานะทั้งหมด +7, SP สูงสุด +1000, ลดดาเมจกายภาพ +10%' WHERE id = 675;
UPDATE statuses SET description_th = 'เป้าหมายถูกกักไว้บนพื้นชั่วคราว ลด HP อย่างต่อเนื่อง' WHERE id = 676;
UPDATE statuses SET description_th = 'พาบรรยากาศสูงสุดสู่จุดสุดยอด' WHERE id = 677;
UPDATE statuses SET description_th = 'เพิ่มความสามารถทางกายภาพชั่วคราว' WHERE id = 679;
UPDATE statuses SET description_th = 'ยกเลิก debuff และเพิ่มต้านทาน' WHERE id = 680;
UPDATE statuses SET description_th = 'เพิ่มความสามารถทุกส่วนโดยปลุกสัญชาตญาณงู' WHERE id = 681;
UPDATE statuses SET description_th = 'สถานะทั้งหมดเพิ่มขึ้น' WHERE id = 682;
UPDATE statuses SET description_th = '[ระดับ 1/2/3]: ดาเมจมอนสเตอร์ +30/60/100%, ดาเมจสกิล +30/60/100%' WHERE id = 683;
UPDATE statuses SET description_th = '[Dealer] พลังโจมตี +50%, HP +10, เจาะเกราะ +10' WHERE id = 685;
UPDATE statuses SET description_th = '[Tanker] พลังโจมตี +25%, HP +10, ภูมิคุ้มกัน +10' WHERE id = 686;
