-- Batch 14: M-N section (1186-1280)

UPDATE statuses SET description_th = 'ทำเครื่องหมายจุดอ่อนศัตรู เพิ่มดาเมจโจมตียิง' WHERE id = 1189;
UPDATE statuses SET description_th = 'เพิ่ม HP สูงสุด' WHERE id = 1191;
UPDATE statuses SET description_th = 'เพิ่ม SP สูงสุด' WHERE id = 1195;
UPDATE statuses SET description_th = 'ผ่านศรัทธา ไกล่เกลี่ยระหว่างตัวเองกับศัตรู' WHERE id = 1196;
UPDATE statuses SET description_th = 'ดาเมจทั้งหมด -5%, บล็อก +10, หลบ +10' WHERE id = 1197;
UPDATE statuses SET description_th = 'ฟื้นฟู HP และ SP เพิ่มชั่วคราว' WHERE id = 1198;
UPDATE statuses SET description_th = 'ประเภทเกราะกลาง' WHERE id = 1199;
UPDATE statuses SET description_th = 'ดาเมจสกิลเพิ่ม 3 เท่า (PvP)' WHERE id = 1200;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีประชิด' WHERE id = 1201;
UPDATE statuses SET description_th = 'STR, HP และความแม่นยำเพิ่ม' WHERE id = 1205;
UPDATE statuses SET description_th = 'ลดประสิทธิภาพเกราะ' WHERE id = 1207;
UPDATE statuses SET description_th = 'ลดประสิทธิภาพอาวุธ' WHERE id = 1208;
UPDATE statuses SET description_th = 'ลดเวลาร่ายสกิลอย่างมาก' WHERE id = 1213;
UPDATE statuses SET description_th = 'เพิ่มดาเมจ' WHERE id = 1216;
UPDATE statuses SET description_th = 'เพิ่ม HP สูงสุดตาม INT' WHERE id = 1217;
UPDATE statuses SET description_th = 'เพิ่มดาเมจมอนสเตอร์และดาเมจคริติคอลชั่วคราว' WHERE id = 1218;
UPDATE statuses SET description_th = 'ถูกสาปโดย Merman' WHERE id = 1219;
UPDATE statuses SET description_th = '[Lv 10] เจาะเกราะจิต +100, ภูมิคุ้มกัน +60' WHERE id = 1220;
UPDATE statuses SET description_th = '[Lv 10] ความเร็วโจมตี -100%, ความเร็วเคลื่อนที่ -100%, เวลาร่าย +100%' WHERE id = 1221;
UPDATE statuses SET description_th = 'ดาเมจประชิด -20%, ดาเมจระยะไกล +20%, ดาเมจเวทย์ -20%' WHERE id = 1222;
UPDATE statuses SET description_th = 'ดูดซับจิตวิญญาณศัตรูและใช้สกิลทรงพลัง' WHERE id = 1223;
UPDATE statuses SET description_th = 'อ่านจุดอ่อนศัตรูด้วยตาใจ ใช้ป้องกันกลับด้าน' WHERE id = 1224;
UPDATE statuses SET description_th = 'เจาะเกราะจิต +7, ต้านทานทั้งหมด +5' WHERE id = 1225;
UPDATE statuses SET description_th = 'เผาผลาญ SP ศัตรูเพื่อสร้างดาเมจเพิ่ม' WHERE id = 1226;
UPDATE statuses SET description_th = 'ชำระล้างรอบตัว' WHERE id = 1227;
UPDATE statuses SET description_th = 'HP สูงสุด +500' WHERE id = 1229;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +15%, ดาเมจมอนสเตอร์ +50%, เจาะเกราะ +15' WHERE id = 1230;
UPDATE statuses SET description_th = '[Lv 10] HP สูงสุด +10000, SP สูงสุด +1000, สถานะทั้งหมด +5, ดาเมจที่ได้รับ -10%' WHERE id = 1231;
UPDATE statuses SET description_th = 'โจมตีเป็น splash SP ไม่ลด ความเร็วเคลื่อนที่เพิ่ม' WHERE id = 1232;
UPDATE statuses SET description_th = 'เพิ่ม A.R. และต้านทานจิต' WHERE id = 1233;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและต้านทานจิต' WHERE id = 1234;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะและต้านทานจิต' WHERE id = 1235;
UPDATE statuses SET description_th = 'เพิ่มความเร็วเคลื่อนที่และโจมตีของมอนสเตอร์อย่างมาก' WHERE id = 1236;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันและ D.R. ของมอนสเตอร์อย่างมาก' WHERE id = 1237;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและ A.R. ของมอนสเตอร์อย่างมาก' WHERE id = 1238;
UPDATE statuses SET description_th = 'เพิ่มฟื้นฟูและต้านทานของมอนสเตอร์อย่างมาก' WHERE id = 1239;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี ความเร็วเคลื่อนที่ และอัตราฟื้นฟู HP/SP' WHERE id = 1240;
UPDATE statuses SET description_th = 'เพิ่มดาเมจสกิล เจาะเกราะ ละเว้นพลังป้องกัน ลดเวลาร่าย' WHERE id = 1244;
UPDATE statuses SET description_th = 'เพิ่มความสามารถโจมตีของ Bianca' WHERE id = 1246;
UPDATE statuses SET description_th = 'มุ่งมั่นทำความสะอาด ความสามารถทั้งหมดเพิ่ม' WHERE id = 1247;
UPDATE statuses SET description_th = 'ทำให้จิตใจสงบอย่างค่อยเป็นค่อยไปตลอดระยะเวลา' WHERE id = 1252;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะกายภาพและเวทย์' WHERE id = 1254;
UPDATE statuses SET description_th = 'สกิลถัดไปลดเวลาร่าย' WHERE id = 1255;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่ม' WHERE id = 1256;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่ม' WHERE id = 1257;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่มและดาเมจสกิลเพิ่มเติม' WHERE id = 1258;
UPDATE statuses SET description_th = 'พลังป้องกันเพิ่ม' WHERE name LIKE 'Navy Code - Step 4%' AND description_th IS NULL;
UPDATE statuses SET description_th = 'เกราะมืดดูดซับพลังรอบข้าง' WHERE name = 'Nebula' AND description_th IS NULL;
UPDATE statuses SET description_th = 'หลับ ไม่สามารถเคลื่อนไหว' WHERE name = 'Night Mare' AND description_th IS NULL;
UPDATE statuses SET description_th = 'ค่าประสบการณ์ x2 ชั่วคราว' WHERE name = 'Noble Flair' AND description_th IS NULL;
