-- Batch 12: J-K-L section (1057-1119)

UPDATE statuses SET description_th = 'พลังโจมตี +3%, ความเร็วเคลื่อนที่ +5%' WHERE id = 1057;
UPDATE statuses SET description_th = 'พลังโจมตี +2%, เจาะเกราะ +5, ฟื้นฟู HP +200' WHERE id = 1058;
UPDATE statuses SET description_th = 'เพิ่มความสามารถโจมตี' WHERE id = 1059;
UPDATE statuses SET description_th = 'เชื่อมต่อกับตัวละครอื่น เมื่อถูกโจมตี ตัวละครที่เชื่อมต่อจะได้รับดาเมจด้วย' WHERE id = 1060;
UPDATE statuses SET description_th = 'ไม่สามารถใช้ไอเทมได้ชั่วคราว' WHERE id = 1061;
UPDATE statuses SET description_th = 'มีเอฟเฟกต์หลากหลาย' WHERE id = 1063;
UPDATE statuses SET description_th = '[Lv 1] A.R. +1, พลังโจมตี +25%, สถานะทั้งหมด +5, เจาะเกราะกายภาพ +7' WHERE id = 1064;
UPDATE statuses SET description_th = 'ลดพลังป้องกันและต้านทานธาตุชั่วคราว' WHERE id = 1065;
UPDATE statuses SET description_th = 'ลดพลังป้องกัน' WHERE id = 1066;
UPDATE statuses SET description_th = 'ลดต้านทาน' WHERE id = 1067;
UPDATE statuses SET description_th = 'เพิ่มต้านทานเวทย์และความเร็วเคลื่อนที่ ต้านทานเวทย์สูง' WHERE id = 1068;
UPDATE statuses SET description_th = 'ความสามารถทั้งหมด +5, เจาะเกราะ +5, ภูมิคุ้มกัน +5, ดาเมจมอนสเตอร์ +20%' WHERE id = 1069;
UPDATE statuses SET description_th = 'เพิ่มความสามารถ' WHERE id = 1071;
UPDATE statuses SET description_th = 'พลังโจมตี +12%, เจาะเกราะ +15, ภูมิคุ้มกัน +10, พลังป้องกัน +10, ดาเมจมอนสเตอร์ +40%, HP สูงสุด -10%' WHERE id = 1072;
UPDATE statuses SET description_th = 'เพิ่มความสามารถตัวเองและส่งคำตัดสินประหารให้ศัตรูที่โจมตี' WHERE id = 1074;
UPDATE statuses SET description_th = 'ดาเมจทั้งหมด +3% ต่อระดับ (สูงสุด 10) ดาเมจบอสมอนสเตอร์เพิ่ม' WHERE id = 1075;
UPDATE statuses SET description_th = 'ระยะเวลา: 20 วินาที ความเร็วโจมตี -10%' WHERE id = 1076;
UPDATE statuses SET description_th = 'D.R. -1, ต้านทานธาตุ -10, ไม่สามารถใช้ไอเทม ระยะเวลา: 10 วินาที' WHERE id = 1077;
UPDATE statuses SET description_th = 'เลือกไพ่ เอฟเฟกต์จะเปลี่ยนตามชนิดไพ่ที่หยิบ' WHERE id = 1078;
UPDATE statuses SET description_th = 'A.R. +1, เจาะเกราะ +10, ดาเมจสกิลเพิ่มตาม buff' WHERE id = 1079;
UPDATE statuses SET description_th = 'A.R. +1, เจาะเกราะ +10, ดาเมจสกิลเพิ่มตาม buff' WHERE id = 1080;
UPDATE statuses SET description_th = 'A.R. +1, เจาะเกราะ +10, ดาเมจสกิลเพิ่มตาม buff' WHERE id = 1081;
UPDATE statuses SET description_th = 'ความหวานสุดขีด HP และ SP เพิ่มขึ้นเรื่อยๆ' WHERE id = 1082;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีตามสัดส่วนผกผันกับ HP ตัวเอง' WHERE id = 1083;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีอย่างมาก ลดเวลาร่ายสกิลมาก' WHERE id = 1084;
UPDATE statuses SET description_th = 'STR, AGI, HP และ D.R. เพิ่มขึ้น' WHERE id = 1085;
UPDATE statuses SET description_th = 'ดาเมจ +10%, ละเว้นพลังป้องกัน 50, ละเว้นบล็อก' WHERE id = 1086;
UPDATE statuses SET description_th = 'D.R. -1, พลังป้องกัน -5, ต้านทานไฟ -5 ต่อระดับ' WHERE id = 1087;
UPDATE statuses SET description_th = 'A.R., STR, AGI และ HP เพิ่ม' WHERE id = 1089;
UPDATE statuses SET description_th = '[Lv 1] ความเร็วเคลื่อนที่ +15%, ขีดจำกัดความเร็ว +15%, ดาเมจทั้งหมด -5%' WHERE id = 1090;
UPDATE statuses SET description_th = 'ดาเมจสกิลเพิ่มตามสัดส่วน INT รวม (สูงสุด 250%)' WHERE id = 1091;
UPDATE statuses SET description_th = '[ระดับ 10] ความเร็วโจมตี -20%, เวลาร่ายสกิล -50%' WHERE id = 1092;
UPDATE statuses SET description_th = 'โจมตีถัดไปของ Kael ละเว้นภูมิคุ้มกันศัตรูเท่ากับ AGI เพิ่มเติม' WHERE id = 1093;
UPDATE statuses SET description_th = 'ดาเมจเวทย์ +5%, D.R. -1, ภูมิคุ้มกัน -10, ต้านทานทั้งหมด -3' WHERE id = 1094;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน 200 เป็นเวลา 90 วินาที' WHERE id = 1095;
UPDATE statuses SET description_th = 'เจาะเกราะไฟ +7, พลังโจมตี +5%' WHERE id = 1096;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันเวทย์ 70 เป็นเวลา 90 วินาที' WHERE id = 1097;
UPDATE statuses SET description_th = 'เพิ่มธาตุไฟชั่วคราว และต้านทานไฟเพิ่ม' WHERE id = 1098;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +18%, พลังป้องกัน +12, ภูมิคุ้มกัน +6, HP สูงสุด +15000' WHERE id = 1099;
UPDATE statuses SET description_th = 'เพิ่มความสามารถด้วยทักษะผู้นำ' WHERE id = 1100;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +100%' WHERE id = 1101;
UPDATE statuses SET description_th = 'ได้รับสิทธิ์เข้า Forgotten Territories' WHERE id = 1102;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +30%, เวลาร่าย -10%' WHERE id = 1103;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้ +30% หายเมื่อเปลี่ยนพื้นที่' WHERE id = 1104;
UPDATE statuses SET description_th = 'เพิ่มความสามารถทั้งหมด +10' WHERE id = 1105;
UPDATE statuses SET description_th = 'พลังโจมตีเวทย์ +15%, เจาะเกราะเวทย์ +15, ดาเมจมอนสเตอร์ +30%' WHERE id = 1106;
UPDATE statuses SET description_th = 'buff เสริมจากปลาสามสี' WHERE id = 1107;
UPDATE statuses SET description_th = 'สามารถเคลื่อนที่ในอากาศได้' WHERE id = 1108;
UPDATE statuses SET description_th = 'เพิ่มธาตุสายฟ้าให้อาวุธทื่อ' WHERE id = 1118;
UPDATE statuses SET description_th = 'ความเร็วเคลื่อนที่ โจมตี และร่ายสกิล -50% ลดต้านทานไฟ' WHERE id = 1119;
