-- Batch 13: L-M section (1110-1185)

-- Light Demons Protection series
UPDATE statuses SET description_th = 'การปกป้องจากปีศาจแสง — ต้านทานทั้งหมด' WHERE id = 1110;
UPDATE statuses SET description_th = 'การปกป้องจากปีศาจแสง — พลังโจมตี' WHERE id = 1111;
UPDATE statuses SET description_th = 'การปกป้องจากปีศาจแสง — ความเร็วโจมตี' WHERE id = 1112;
UPDATE statuses SET description_th = 'การปกป้องจากปีศาจแสง — พลังป้องกัน' WHERE id = 1113;
UPDATE statuses SET description_th = 'การปกป้องจากปีศาจแสง — ต้านทานไฟ' WHERE id = 1114;
UPDATE statuses SET description_th = 'การปกป้องจากปีศาจแสง — ฟื้นฟู HP' WHERE id = 1115;
UPDATE statuses SET description_th = 'การปกป้องจากปีศาจแสง — ภูมิคุ้มกัน' WHERE id = 1116;
UPDATE statuses SET description_th = 'การปกป้องจากปีศาจแสง — อัตรา' WHERE id = 1117;

UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีโดยเสริมลูกบอลสายฟ้าด้วยพลังศัตรู' WHERE id = 1120;
UPDATE statuses SET description_th = 'ลดธาตุสายฟ้า buff จะหายเมื่อซ้อนทับ' WHERE id = 1121;
UPDATE statuses SET description_th = 'ดาเมจที่ได้รับ -20%, ดาเมจมอนสเตอร์ +75%' WHERE id = 1122;
UPDATE statuses SET description_th = 'ปกป้องผู้ใช้จากทุกการโจมตี' WHERE id = 1123;
UPDATE statuses SET description_th = 'โล่ฟ้าผ่าปกป้องผู้ร่าย' WHERE id = 1124;
UPDATE statuses SET description_th = 'แบ่งปันประสบการณ์การต่อสู้' WHERE id = 1126;
UPDATE statuses SET description_th = 'STR +3, พลังป้องกัน +3, ภูมิคุ้มกัน +3, ฟื้นฟู HP อย่างรวดเร็ว' WHERE id = 1127;
UPDATE statuses SET description_th = 'ใช้พลังอมตะ' WHERE id = 1129;
UPDATE statuses SET description_th = 'พลังโจมตีประชิด +10%, เจาะเกราะกายภาพ +10, ดาเมจมอนสเตอร์ +20%' WHERE id = 1131;
UPDATE statuses SET description_th = 'เล็งดีขึ้นด้วยการหายใจบางๆ ยาวๆ' WHERE id = 1132;
UPDATE statuses SET description_th = 'HP และ SP เพิ่มอย่างต่อเนื่องจากความรักอันหวาน' WHERE id = 1133;
UPDATE statuses SET description_th = 'พลังโจมตี +6%, เจาะเกราะ +12, ภูมิคุ้มกัน +5, พลังป้องกัน +5, ดาเมจมอนสเตอร์ +30%' WHERE id = 1135;
UPDATE statuses SET description_th = 'เพิ่มอัตราดรอปและค่าประสบการณ์ 10%' WHERE id = 1136;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์ 20% เป็นเวลา 10 นาที หายเมื่อเปลี่ยนพื้นที่' WHERE id = 1137;
UPDATE statuses SET description_th = 'เพิ่มอัตราดรอปไอเทม 5%' WHERE id = 1139;
UPDATE statuses SET description_th = 'ละเว้นต้านทาน 10 ต่อระดับ สำหรับสกิล [Caelestis]' WHERE id = 1143;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี ความเร็วโจมตี และ A.R.' WHERE id = 1144;
UPDATE statuses SET description_th = 'ตรวจจับพลังเวทย์รอบข้าง ดูดซับพลังที่ตรวจพบ' WHERE id = 1145;
UPDATE statuses SET description_th = 'ถูกครอบงำด้วยความบ้าคลั่ง' WHERE id = 1146;
UPDATE statuses SET description_th = 'เจาะเกราะ +2, เวลาร่าย -3%, ดาเมจโจมตีปกติ +20% ต่อระดับ' WHERE id = 1147;
UPDATE statuses SET description_th = 'แสดงจำนวนกระสุนที่บรรจุ' WHERE id = 1148;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันและต้านทานเวทย์' WHERE id = 1149;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่ม' WHERE id = 1151;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่ม' WHERE id = 1152;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่ม' WHERE id = 1153;
UPDATE statuses SET description_th = 'เมื่อละเว้นสกิลเวทย์ศัตรูผ่าน Ropera buff สกิลถัดไปจะแรงขึ้น' WHERE id = 1155;
UPDATE statuses SET description_th = 'ระเบิดสายฟ้าที่สร้างลมกระโชกแรงถูกติดตั้ง ความเร็วเคลื่อนที่ลด' WHERE id = 1156;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีเวทย์' WHERE id = 1157;
UPDATE statuses SET description_th = 'ลดพลังโจมตีและป้องกันอย่างมาก แพร่กระจายไปยังตัวละครอื่น' WHERE id = 1160;
UPDATE statuses SET description_th = 'ละเว้นดาเมจโจมตีเวทย์ และฟื้นฟู HP เท่ากับดาเมจ' WHERE id = 1162;
UPDATE statuses SET description_th = '[Lv 1] พลังโจมตี -5%, ความเร็วโจมตี -5%, ความเร็วเคลื่อนที่ -15%' WHERE id = 1163;
UPDATE statuses SET description_th = 'เจาะเกราะ +15 หายเมื่อใช้สกิล' WHERE id = 1164;
UPDATE statuses SET description_th = 'ต้านทานทั้งหมด -15 หายเมื่อโดนสกิลจากสแตนซ์ [Arcane Master]' WHERE id = 1166;
UPDATE statuses SET description_th = 'ลดต้านทานเวทย์ทั้งหมด' WHERE id = 1167;
UPDATE statuses SET description_th = 'ลด HP อย่างต่อเนื่องจาก Navas' WHERE id = 1168;
UPDATE statuses SET description_th = '10% โอกาสลดดาเมจเวทย์อย่างมาก' WHERE id = 1169;
UPDATE statuses SET description_th = 'ลดต้านทานไฟ น้ำแข็ง สายฟ้า และจิตชั่วคราว' WHERE id = 1170;
UPDATE statuses SET description_th = 'บล็อกพลังเวทย์ด้วยสนามแม่เหล็ก ไม่สามารถใช้เวทย์ได้' WHERE id = 1171;
UPDATE statuses SET description_th = '[Lv 1] เวลาร่าย -10%, ความเร็วเคลื่อนที่ +20%' WHERE id = 1172;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +40%, ความแม่นยำ +30, คริติคอล +20' WHERE id = 1173;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +40%, ความแม่นยำ +30, คริติคอล +20' WHERE id = 1174;
UPDATE statuses SET description_th = 'ทุกคนคุกเข่าต่อหน้าศักดิ์ศรีของราชวงศ์' WHERE id = 1175;
UPDATE statuses SET description_th = 'HP สูงสุด +1000' WHERE id = 1176;
UPDATE statuses SET description_th = 'HP สูงสุด/SP สูงสุดเพิ่ม ดาเมจทั้งหมดลด' WHERE id = 1179;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +15%, ความเร็วโจมตี +5% แต่ D.R. -1, พลังป้องกัน -10' WHERE id = 1183;
UPDATE statuses SET description_th = 'ลดเวลาร่ายสกิล และมีโอกาสใส่ [Marking] ให้ศัตรู' WHERE id = 1184;
UPDATE statuses SET description_th = 'พลังโจมตี -50%, พลังป้องกัน -50% ถ้าได้รับอีกครั้ง จะเข้าสถานะตาย' WHERE id = 1185;
