-- Batch 26: C section (313-420)

UPDATE statuses SET description_th = '[Lv 1-9] [Ziz] เวลาร่าย -30%, ดาเมจมอนสเตอร์ +100%, ความเร็วเคลื่อนที่ +10%' WHERE id = 319;
UPDATE statuses SET description_th = 'ลดดาเมจ PvP ที่ได้รับ' WHERE id = 355;
UPDATE statuses SET description_th = 'ลดดาเมจจากมอนสเตอร์' WHERE id = 356;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะเวทย์ของตัวละคร' WHERE id = 357;
UPDATE statuses SET description_th = 'เพิ่ม HP สูงสุดของตัวละคร' WHERE id = 358;
UPDATE statuses SET description_th = 'เพิ่ม SP สูงสุดของตัวละคร' WHERE id = 359;
UPDATE statuses SET description_th = 'เพิ่มดาเมจมอนสเตอร์ของตัวละคร' WHERE id = 360;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะกายภาพของตัวละคร' WHERE id = 362;
UPDATE statuses SET description_th = 'เพิ่มดาเมจ PvP ของตัวละคร' WHERE id = 363;
UPDATE statuses SET description_th = 'ไม่สามารถใช้ตัวละครนี้ได้ในขณะนี้' WHERE id = 368;
UPDATE statuses SET description_th = 'เพิ่มความสามารถพื้นฐานของ Testormento' WHERE id = 371;
UPDATE statuses SET description_th = 'เพิ่มความสามารถกองทัพอย่างรวดเร็ว' WHERE id = 372;
UPDATE statuses SET description_th = 'ชาร์จพลังปืน โจมตีปกติเท่านั้น ละเว้นพลังป้องกันศัตรู' WHERE id = 373;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีสายฟ้าและเจาะเกราะสายฟ้า' WHERE id = 374;
UPDATE statuses SET description_th = 'ความเร็วเคลื่อนที่เพิ่ม' WHERE id = 375;
UPDATE statuses SET description_th = 'A.R. เพิ่ม และโจมตีปกติแรงขึ้น' WHERE id = 377;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +10%, เจาะเกราะ +5, ภูมิคุ้มกัน +5, ความแม่นยำ +10%, ความเร็วเคลื่อนที่ +10%' WHERE id = 378;
UPDATE statuses SET description_th = 'เพิ่มความสามารถทางกายภาพและภูมิคุ้มกัน' WHERE id = 379;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและ A.R. แต่ลดความเร็วโจมตีและเคลื่อนที่' WHERE id = 380;
UPDATE statuses SET description_th = 'เมื่อใช้สกิล เพิ่มดาเมจตาม SP ที่เหลือ' WHERE id = 381;
UPDATE statuses SET description_th = 'โจมตีของเป้าหมายเพิ่มธาตุน้ำแข็ง และต้านทานน้ำแข็งเพิ่ม' WHERE id = 382;
UPDATE statuses SET description_th = 'เพิ่ม A.R. พลังโจมตี ความเร็วโจมตี เจาะเกราะ หลบ คริติคอล' WHERE id = 383;
UPDATE statuses SET description_th = 'เปราะบางมาก พังง่าย' WHERE id = 384;
UPDATE statuses SET description_th = 'พลังโจมตี +5%, พลังป้องกัน +10, เจาะเกราะ +3, สถานะทั้งหมด +3' WHERE id = 385;
UPDATE statuses SET description_th = 'พลังโจมตี +2%, ความเร็วโจมตี +10%, คริติคอล +10' WHERE id = 386;
UPDATE statuses SET description_th = 'พลังโจมตี +7%, ดาเมจมอนสเตอร์ +7%, เจาะเกราะ +3' WHERE id = 387;
UPDATE statuses SET description_th = 'พลังโจมตี +7%, ดาเมจมอนสเตอร์ +3%, สถานะทั้งหมด +5' WHERE id = 388;
UPDATE statuses SET description_th = 'พลังโจมตียิง +10%, ความแม่นยำ +10' WHERE id = 389;
UPDATE statuses SET description_th = 'พลังโจมตี +5%, เจาะเกราะกายภาพ +5, ภูมิคุ้มกัน -5' WHERE id = 390;
UPDATE statuses SET description_th = 'เจาะเกราะเวทย์ +5, ภูมิคุ้มกัน +5, ความเร็วเคลื่อนที่ +5%, ขีดจำกัดความเร็ว +2%' WHERE id = 391;
UPDATE statuses SET description_th = 'จะสามารถเล่นดนตรีเข้มข้นได้ดีขึ้น' WHERE id = 392;
UPDATE statuses SET description_th = 'ความเร็วโจมตี -10%, ความเร็วเคลื่อนที่ -10%, D.R. -1' WHERE id = 393;
UPDATE statuses SET description_th = 'วัตถุกำลังทำความสะอาด' WHERE id = 396;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีเพื่อมุ่งมั่นทำความสะอาด แต่ความเร็วโจมตีลด' WHERE id = 397;
UPDATE statuses SET description_th = 'ระยะเวลา: 10 วินาที ดาเมจมอนสเตอร์ +25%' WHERE id = 398;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและพลังชีวิตสูงสุด' WHERE id = 399;
UPDATE statuses SET description_th = 'ความสามารถโจมตีและใช้สกิลถูกปิดชั่วคราว' WHERE id = 401;
UPDATE statuses SET description_th = 'ถูกวิญญาณแค้นเข้าสิง เพิ่มความสามารถสูงสุด' WHERE id = 403;
UPDATE statuses SET description_th = 'ลดความเร็วโจมตีและเคลื่อนที่ สิ่งเรียกลดดาเมจด้วย' WHERE id = 404;
UPDATE statuses SET description_th = 'พลังป้องกัน -5, ต้านทานน้ำแข็ง -15' WHERE id = 406;
