-- Batch 24: B section — Bleeding/Bless/Blessing series (177-229)

UPDATE statuses SET description_th = 'พลังโจมตี/ความเร็วเคลื่อนที่ลดอย่างมาก HP ลดอย่างต่อเนื่อง' WHERE id = 177;
UPDATE statuses SET description_th = 'เวทย์ศักดิ์สิทธิ์ไหลผ่านอาวุธชั่วคราว หายเมื่อเปลี่ยนสแตนซ์' WHERE id = 178;
UPDATE statuses SET description_th = 'ฟื้นฟู HP/SP อย่างรวดเร็วตลอดระยะเวลา' WHERE id = 181;
UPDATE statuses SET description_th = 'เพิ่มฟื้นฟู HP และ SP ค่าประสบการณ์การต่อสู้และสแตนซ์เพิ่ม' WHERE id = 183;
UPDATE statuses SET description_th = 'HP สูงสุด +10000, ฟื้นฟู HP +500, พลังป้องกัน +20, ต้านทานทั้งหมด +10, ภูมิคุ้มกันเพิ่ม' WHERE id = 184;
UPDATE statuses SET description_th = 'เพิ่มความเร็วโจมตีและเคลื่อนที่' WHERE id = 185;
UPDATE statuses SET description_th = 'เพิ่ม A.R. และ D.R. +1' WHERE id = 186;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี' WHERE id = 188;
UPDATE statuses SET description_th = 'เพิ่ม A.R., D.R., พลังโจมตี และเจาะเกราะ' WHERE id = 189;
UPDATE statuses SET description_th = 'เจาะเกราะ +3, คริติคอล +7, คริติคอลสูงสุด +7, ดาเมจคริติคอล +7%' WHERE id = 192;
UPDATE statuses SET description_th = 'ความสามารถจะดีขึ้น' WHERE id = 193;
UPDATE statuses SET description_th = 'เจาะเกราะ +7, ดาเมจมอนสเตอร์ +10%' WHERE id = 194;
UPDATE statuses SET description_th = 'ค่าประสบการณ์/สแตนซ์ +200%, อัตราดรอป +10%, พลังโจมตี +2%, ความเร็วโจมตี +2%' WHERE id = 195;
UPDATE statuses SET description_th = 'พลังโจมตีและความเร็วเคลื่อนที่เพิ่ม 10%' WHERE id = 196;
UPDATE statuses SET description_th = 'เพิ่มอัตราดรอป Luxurious Red Cloth Piece' WHERE id = 198;
UPDATE statuses SET description_th = 'เพิ่มอัตราดรอป Luxurious Bell' WHERE id = 199;
UPDATE statuses SET description_th = 'ถ้ามี Mandarin หรือ Rose the Heart อยู่ใกล้ พลังโจมตีเพิ่ม' WHERE id = 200;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี เจาะเกราะ และ A.R.' WHERE id = 201;
UPDATE statuses SET description_th = 'Hare จับตาดู Dolores' WHERE id = 202;
UPDATE statuses SET description_th = 'เพิ่มฟื้นฟู HP SP พลังป้องกัน และ HP สูงสุดชั่วคราว' WHERE id = 203;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +7%, เจาะเกราะ +3, ภูมิคุ้มกัน +3, พลังป้องกัน +7, คริติคอลเพิ่ม' WHERE id = 204;
UPDATE statuses SET description_th = 'พรจากหัวหน้าฝ่าย' WHERE id = 205;
UPDATE statuses SET description_th = 'HP สูงสุด +7%, พลังป้องกัน +10, ภูมิคุ้มกัน +10' WHERE id = 206;
UPDATE statuses SET description_th = 'ค่าประสบการณ์/สแตนซ์ +200%, อัตราดรอป +10%, พลังป้องกัน +2, ภูมิคุ้มกัน +2' WHERE id = 207;
UPDATE statuses SET description_th = 'เพิ่ม A.R. หรือเจาะเกราะ' WHERE id = 209;
UPDATE statuses SET description_th = 'เพิ่มอัตราดรอป Red Socks' WHERE id = 210;
UPDATE statuses SET description_th = 'เพิ่มสถานะ' WHERE id = 212;
UPDATE statuses SET description_th = 'ลดดาเมจที่ได้รับ' WHERE id = 213;
UPDATE statuses SET description_th = 'ลดดาเมจจากโจมตีประชิดอย่างมาก' WHERE id = 214;
UPDATE statuses SET description_th = 'Reve จับตาดู Lorraine' WHERE id = 215;
UPDATE statuses SET description_th = 'ความสามารถจะดีขึ้น' WHERE id = 216;
UPDATE statuses SET description_th = 'เพิ่ม HP ด้วยพร' WHERE id = 217;
UPDATE statuses SET description_th = 'ลดดาเมจประชิด ยิง เวทย์' WHERE id = 219;
UPDATE statuses SET description_th = 'ได้รับพลังต้านกองทัพ Abyss ด้วยพรของ Sara' WHERE id = 220;
UPDATE statuses SET description_th = 'รับพรมนุษย์หิมะ ความเร็วโจมตี +10% สุขสันต์วันคริสต์มาส' WHERE id = 221;
UPDATE statuses SET description_th = 'ลูกบอลสายฟ้าปกป้อง Eileen' WHERE id = 222;
UPDATE statuses SET description_th = '[Lv 1] ยกเลิกขีดจำกัดความเร็วเคลื่อนที่' WHERE id = 223;
UPDATE statuses SET description_th = 'เพิ่มภูมิคุ้มกันและเจาะเกราะ' WHERE id = 224;
UPDATE statuses SET description_th = 'ฟื้นฟู HP/SP +100/+50, พลังโจมตี +5%, เจาะเกราะ +5, สถานะทั้งหมด +5' WHERE id = 225;
UPDATE statuses SET description_th = 'รับพรต้นคริสต์มาส พลังโจมตีเพิ่ม 10%' WHERE id = 226;
UPDATE statuses SET description_th = 'พลังโจมตี +20%, ความเร็วโจมตี +10% ดาเมจสกิล x3 เมื่อเป้าหมายมี [Frozen Storm]' WHERE id = 227;
UPDATE statuses SET description_th = 'พลังโจมตี +25%, ภูมิคุ้มกัน +5, เจาะเกราะสายฟ้า +20' WHERE id = 228;
