-- Batch 25: B remainder (230-290)

UPDATE statuses SET description_th = 'ลดดาเมจจาก Oscuras' WHERE id = 230;
UPDATE statuses SET description_th = 'ฟื้นฟู HP ทุกวินาที' WHERE id = 231;
UPDATE statuses SET description_th = 'ห้ามใช้สกิลบางตัว' WHERE id = 234;
UPDATE statuses SET description_th = 'มองเห็นถูกบัง ความแม่นยำ -50 ความเร็วเคลื่อนที่ -50%' WHERE id = 236;
UPDATE statuses SET description_th = 'ลด HP/SP พลังป้องกัน และความเร็วเคลื่อนที่ชั่วคราว' WHERE id = 237;
UPDATE statuses SET description_th = 'ฟื้นฟู HP อย่างผิดปกติ' WHERE id = 238;
UPDATE statuses SET description_th = 'ฟื้นฟู HP อย่างผิดปกติ' WHERE id = 239;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีตามปริมาณเลือดที่เสีย' WHERE id = 240;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี' WHERE id = 241;
UPDATE statuses SET description_th = 'เพิ่มบล็อกและภูมิคุ้มกัน' WHERE id = 242;
UPDATE statuses SET description_th = 'เมื่อโจมตีสกิลสำเร็จภายในเวลาจำกัด พลังโจมตีจะแรงขึ้น' WHERE id = 244;
UPDATE statuses SET description_th = 'อ่อนแอต่อโจมตีประชิด' WHERE id = 245;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและเจาะเกราะ ลดเวลาร่ายสกิล' WHERE id = 246;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน' WHERE id = 247;
UPDATE statuses SET description_th = 'เพิ่มความเร็วโจมตีเป็นเวลา 30 วินาที' WHERE id = 248;
UPDATE statuses SET description_th = 'เพิ่ม HP สูงสุดและ SP สูงสุด' WHERE id = 251;
UPDATE statuses SET description_th = 'เพิ่มดาเมจเวทย์ให้สมาชิกทีมทั้งหมด' WHERE id = 252;
UPDATE statuses SET description_th = 'INT +10, SEN +10, เจาะเกราะ +10, ภูมิคุ้มกัน +10' WHERE id = 256;
UPDATE statuses SET description_th = 'D.R. +1, ภูมิคุ้มกัน +20, พลังป้องกัน +20' WHERE id = 257;
UPDATE statuses SET description_th = 'A.R. +1, เจาะเกราะ +20, พลังโจมตี +25%' WHERE id = 258;
UPDATE statuses SET description_th = 'เพิ่มความสามารถโจมตี สามารถเอาชนะศัตรูได้' WHERE id = 259;
UPDATE statuses SET description_th = 'ถูกควบคุมโดยผู้อื่น' WHERE id = 260;
UPDATE statuses SET description_th = 'เพิ่ม HP ชั่วคราว' WHERE id = 261;
UPDATE statuses SET description_th = 'ความเร็วเคลื่อนที่ -50%' WHERE id = 262;
UPDATE statuses SET description_th = 'ความเร็วเคลื่อนที่ -20%, ความเร็วโจมตี -15%' WHERE id = 263;
UPDATE statuses SET description_th = 'ดาเมจที่ได้รับ +5%' WHERE id = 264;
UPDATE statuses SET description_th = 'พลังป้องกัน -20' WHERE id = 265;
UPDATE statuses SET description_th = 'พลังป้องกัน -10, HP สูงสุด -10%' WHERE id = 266;
UPDATE statuses SET description_th = 'พลังโจมตี -10%, ความเร็วโจมตี -20%' WHERE id = 267;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +20%, พลังโจมตีประชิด +40%, พลังป้องกัน +15, STR +15, ละเว้น debuff' WHERE id = 268;
UPDATE statuses SET description_th = 'เพิ่มสมาธิก่อนการต่อสู้ผ่านการบรรยายสรุป' WHERE id = 269;
UPDATE statuses SET description_th = 'เพิ่ม D.R. เอฟเฟกต์ลดลงตามเวลา' WHERE id = 270;
UPDATE statuses SET description_th = 'พลังโจมตี +7% และพลังป้องกัน +7' WHERE id = 272;
UPDATE statuses SET description_th = 'A.R. +1, D.R. +1, SP สูงสุด +10%' WHERE id = 282;
UPDATE statuses SET description_th = 'ลดประสิทธิภาพเกราะ' WHERE id = 283;
UPDATE statuses SET description_th = 'ลดประสิทธิภาพอาวุธ' WHERE id = 285;
UPDATE statuses SET description_th = 'ระยะเวลา: 120 วินาที A.R. +1, พลังโจมตี +10%, เจาะเกราะ +10, พลังป้องกัน +10, ภูมิคุ้มกัน +5' WHERE id = 286;
UPDATE statuses SET description_th = 'สถานะถูกเปลี่ยนแปลง' WHERE id = 287;
UPDATE statuses SET description_th = 'เพิ่มความสามารถจาก buff สัตว์เลี้ยง' WHERE id = 288;
