-- Batch 11: H-I section (867-946)

UPDATE statuses SET description_th = 'HP สูงสุดและการฟื้นฟู HP' WHERE id = 867;
UPDATE statuses SET description_th = 'พลังป้องกัน -2 ต่อระดับ เป้าหมายหยุดเคลื่อนไหว 8 วินาที' WHERE id = 868;
UPDATE statuses SET description_th = 'พลังป้องกันลด และไม่สามารถเคลื่อนที่ได้ชั่วคราว' WHERE id = 869;
UPDATE statuses SET description_th = 'เต้นรำน่าเกลียดของกระต่าย ลดพลังโจมตี ความเร็วเคลื่อนที่ และต้านทานสายฟ้า' WHERE id = 870;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้/สแตนซ์ เพิ่มดาเมจมอนสเตอร์ ลดดาเมจจากมอนสเตอร์' WHERE id = 871;
UPDATE statuses SET description_th = 'เพิ่มความเร็วเคลื่อนที่ 15% เป็นเวลา 10 นาที' WHERE id = 872;
UPDATE statuses SET description_th = 'เพิ่มความแม่นยำและความเร็วโจมตีชั่วคราว' WHERE id = 876;
UPDATE statuses SET description_th = 'ฟื้นฟู HP 1500 ทุก 3 วินาที เป็นเวลา 15 วินาที' WHERE id = 877;
UPDATE statuses SET description_th = 'ระยะเวลา: 10 วินาที ดาเมจมอนสเตอร์ +50%' WHERE id = 879;
UPDATE statuses SET description_th = 'A.R. +1, โจมตีปกติ x1.5 เท่า เพิ่มดาเมจสกิล Spartan' WHERE id = 880;
UPDATE statuses SET description_th = 'เพิ่มธาตุไฟให้อาวุธทื่อ' WHERE id = 881;
UPDATE statuses SET description_th = 'A.R. +1, D.R. +1, พลังโจมตี +20%, บล็อกเพิ่ม' WHERE id = 884;
UPDATE statuses SET description_th = 'A.R. +2, ดาเมจมอนสเตอร์ +100%' WHERE id = 885;
UPDATE statuses SET description_th = 'A.R. +2, พลังโจมตี +100%, ดาเมจมอนสเตอร์เพิ่ม' WHERE id = 886;
UPDATE statuses SET description_th = 'โจมตีปกติรับประกันคริติคอล' WHERE id = 887;
UPDATE statuses SET description_th = 'เวลาร่ายสกิล -50% สกิลถัดไปรับประกันคริติคอล' WHERE id = 888;
UPDATE statuses SET description_th = 'A.R. +1, D.R. +1, พลังโจมตี +20%, บล็อกเพิ่ม' WHERE id = 889;
UPDATE statuses SET description_th = 'A.R. +2, ดาเมจมอนสเตอร์ +100%' WHERE id = 890;
UPDATE statuses SET description_th = 'A.R. +2, พลังโจมตี +100%, ดาเมจมอนสเตอร์เพิ่ม' WHERE id = 891;
UPDATE statuses SET description_th = 'ใช้พลังศักดิ์สิทธิ์ทั้งหมด เพิ่ม D.R.' WHERE id = 892;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีอย่างมากสำหรับยุทธวิธีเชิงรุก' WHERE id = 894;
UPDATE statuses SET description_th = 'ดาเมจเพิ่มเติมตามสัดส่วน HP ทำให้โจมตีหนักขึ้น' WHERE id = 896;
UPDATE statuses SET description_th = 'A.R. +1, D.R. +1, พลังโจมตี +50%, ภูมิคุ้มกัน +10, STR +10, HP +10, ละเว้นพลังป้องกัน' WHERE id = 897;
UPDATE statuses SET description_th = 'A.R. +1, D.R. +1' WHERE id = 898;
UPDATE statuses SET description_th = '[Lv.10] พลังโจมตี +30%, ความแม่นยำ +10, ความเร็วเคลื่อนที่ -20%' WHERE id = 899;
UPDATE statuses SET description_th = 'ละเว้นค่าต้านทานธาตุของเป้าหมาย 5 จุด' WHERE id = 901;
UPDATE statuses SET description_th = 'ไม่สามารถเคลื่อนที่ได้' WHERE id = 902;
UPDATE statuses SET description_th = 'ไม่สามารถเคลื่อนที่ได้' WHERE id = 903;
UPDATE statuses SET description_th = 'เพิ่มความสามารถพันธมิตรด้วยการเสียสละตัวเอง' WHERE id = 904;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันจากพลังศักดิ์สิทธิ์' WHERE id = 905;
UPDATE statuses SET description_th = 'พลังโจมตี -30%, เวลาร่าย -40%, ความเร็วเคลื่อนที่ -30%, สกิลของ Laura เข้มข้นขึ้น' WHERE id = 908;
UPDATE statuses SET description_th = 'ค่าประสบการณ์ +20%' WHERE id = 912;
UPDATE statuses SET description_th = 'ลดดาเมจที่ได้รับบางส่วน' WHERE id = 913;
UPDATE statuses SET description_th = 'พลังศักดิ์สิทธิ์ก่อตัวใน Barisada' WHERE id = 914;
UPDATE statuses SET description_th = 'ลดพลังโจมตี ความเร็วเคลื่อนที่ และเพิ่มเวลาร่ายสกิล' WHERE id = 915;
UPDATE statuses SET description_th = 'ฟื้นฟู HP +600, A.R. +5, D.R. +5, พลังโจมตี +50%, พลังป้องกัน +50' WHERE id = 916;
UPDATE statuses SET description_th = 'ดาเมจคริติคอลที่ได้รับ -10%, ดาเมจระยะไกล -10%, ต้านทาน debuff เพิ่ม' WHERE id = 917;
UPDATE statuses SET description_th = 'พลังโจมตีเวทย์ +10%, เจาะเกราะ +10, เวลาร่าย -2%, ดาเมจมอนสเตอร์ +15%' WHERE id = 918;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและคริติคอลชั่วคราว' WHERE id = 920;
UPDATE statuses SET description_th = 'ไม่สามารถใช้สกิลชั่วคราว และลดพลังโจมตีและความเร็วโจมตี' WHERE id = 921;
UPDATE statuses SET description_th = 'ลดสถานะทั้งหมดอย่างมากเนื่องจากความหิว' WHERE id = 922;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีจิตและต้านทาน เพิ่มโอกาส [Darkness]' WHERE id = 923;
UPDATE statuses SET description_th = 'debuff โซน Lake of Eternity' WHERE id = 926;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีเวทย์และต้านทานเวทย์' WHERE id = 930;
UPDATE statuses SET description_th = 'ไม่สามารถทำอะไรได้ ลดการหลบ บล็อก และต้านทานสายฟ้า' WHERE id = 931;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะน้ำแข็ง' WHERE id = 932;
UPDATE statuses SET description_th = 'สร้างสถานะที่ไม่ได้รับดาเมจจากศัตรูชั่วคราว' WHERE id = 933;
UPDATE statuses SET description_th = 'น้ำไหลทำดาเมจให้ศัตรูใกล้เคียง' WHERE id = 934;
UPDATE statuses SET description_th = 'ไม่สามารถทำอะไรได้ บล็อก/หลบ/ต้านทานสายฟ้า -50' WHERE id = 935;
UPDATE statuses SET description_th = 'เพิ่มธาตุน้ำแข็งชั่วคราว และเพิ่มต้านทานน้ำแข็ง' WHERE id = 936;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีน้ำแข็งและต้านทานน้ำแข็งชั่วคราว' WHERE id = 937;
UPDATE statuses SET description_th = 'สร้างเกราะน้ำแข็งเพิ่มความสามารถป้องกัน' WHERE id = 938;
UPDATE statuses SET description_th = 'ภูมิคุ้มกัน -1 ต่อระดับสกิล ความตายกำลังมา ดาเมจเพิ่มจากสแตนซ์ [Ignisia]' WHERE id = 939;
UPDATE statuses SET description_th = 'พลังป้องกัน -1 ต่อระดับสกิล ชีวิตกำลังละลาย ดาเมจเพิ่มจากสแตนซ์ [Ignisia]' WHERE id = 940;
UPDATE statuses SET description_th = 'D.R. -1 สัมผัสพลัง ดาเมจเพิ่มจากสแตนซ์ [Ignisia]' WHERE id = 941;
UPDATE statuses SET description_th = 'พลังโจมตี -1 ต่อระดับสกิล ความเงียบคือไฟ ดาเมจเพิ่มจากสแตนซ์ [Ignisia]' WHERE id = 942;
UPDATE statuses SET description_th = 'ได้รับการป้องกันที่ละเว้นโจมตีเวทย์อันตรายจากศัตรู' WHERE id = 943;
UPDATE statuses SET description_th = 'เพิ่ม INT และ A.R. ตลอดระยะเวลา' WHERE id = 945;
UPDATE statuses SET description_th = 'สกิลที่ 2 ของสแตนซ์ [Peacefulness]' WHERE id = 946;
