-- Batch 34: Final A-M entries (complete)

UPDATE statuses SET description_th = 'เพิ่มต้านทานเวทย์' WHERE id = 1002;
UPDATE statuses SET description_th = 'เพิ่มความเร็วเคลื่อนที่ +5%' WHERE id = 1004;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะกายภาพ' WHERE id = 1006;
UPDATE statuses SET description_th = 'A.R. เพิ่ม +1' WHERE id = 1007;
UPDATE statuses SET description_th = 'D.R. เพิ่ม +1' WHERE id = 1008;
UPDATE statuses SET description_th = 'ละเว้นพลังป้องกันศัตรู 1% ต่อ Lv.4 ดาเมจสกิลเพิ่ม 20%' WHERE id = 1009;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +25%, ดาเมจมอนสเตอร์ +200%, เจาะเกราะจิตเพิ่ม' WHERE id = 1011;
UPDATE statuses SET description_th = 'A.R. +2, พลังโจมตี +30%, เจาะเกราะสายฟ้า +30, มีโอกาสสร้าง minion' WHERE id = 1012;
UPDATE statuses SET description_th = 'D.R. -1, ต้านทาน -1 ต่อระดับ, ดาเมจไฟ x2' WHERE id = 1013;
UPDATE statuses SET description_th = 'สร้างโล่ดูดซับดาเมจ' WHERE id = 1015;
UPDATE statuses SET description_th = 'พิจารณาผลลัพธ์ที่ดีที่สุดตามสถานการณ์' WHERE id = 1016;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี ดาเมจมอนสเตอร์ และความแม่นยำ' WHERE id = 1018;
UPDATE statuses SET description_th = 'ภูมิคุ้มกัน -1 ต่อระดับสกิล ความตายกำลังมา ดาเมจเพิ่มจากสแตนซ์ [Ignisia]' WHERE id = 1019;
UPDATE statuses SET description_th = 'ถูกหลอกหลอนโดยเศษเงา' WHERE id = 1020;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีธาตุ' WHERE id = 1022;
UPDATE statuses SET description_th = 'D.R. -1, ต้านทานน้ำแข็ง -1 ต่อระดับ, พลังโจมตี -2% ต่อระดับ' WHERE id = 1023;
UPDATE statuses SET description_th = 'HP สูงสุดเพิ่ม' WHERE id = 1024;
UPDATE statuses SET description_th = 'HP สูงสุดเพิ่ม' WHERE id = 1025;
UPDATE statuses SET description_th = 'HP สูงสุดเพิ่ม' WHERE id = 1026;
UPDATE statuses SET description_th = 'HP สูงสุดเพิ่ม' WHERE id = 1027;
UPDATE statuses SET description_th = 'HP สูงสุดเพิ่ม' WHERE id = 1028;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้ 100%' WHERE id = 1030;
UPDATE statuses SET description_th = 'ค่า INT: เพิ่มพลังโจมตีเวทย์และต้านทานเวทย์' WHERE id = 1031;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีชั่วคราว' WHERE id = 1032;
UPDATE statuses SET description_th = 'ได้รับอัตรา favor เพิ่มจากเควส Bristia' WHERE id = 1035;
UPDATE statuses SET description_th = 'มีโอกาสใส่ [Poison] ให้ศัตรูชั่วคราว' WHERE id = 1036;
UPDATE statuses SET description_th = 'เพิ่มความสามารถโจมตีและโอกาส debuff จากสกิลเพิ่ม' WHERE id = 1040;
UPDATE statuses SET description_th = 'ใช้พลังเวทย์มืดล่องหนจากศัตรู แต่ได้รับ penalty มาก' WHERE id = 1043;
UPDATE statuses SET description_th = 'กันตายชั่วคราว แต่จำกัดการใช้ไอเทม' WHERE id = 1044;
UPDATE statuses SET description_th = 'ยกเลิกสถานะล่องหน' WHERE id = 1051;
UPDATE statuses SET description_th = 'ตรวจจับศัตรูทั้งหมดรอบข้าง' WHERE id = 1052;
UPDATE statuses SET description_th = 'กันตายชั่วคราว แต่จำกัดการใช้ไอเทม' WHERE id = 1053;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้/สแตนซ์ และดาเมจมอนสเตอร์ ลดดาเมจจากมอนสเตอร์' WHERE id = 1054;
UPDATE statuses SET description_th = 'ความสามารถของ Elizabeth จะเพิ่มขึ้นชั่วคราว' WHERE id = 1055;
UPDATE statuses SET description_th = 'พลังป้องกันเวทย์ของ Miha และ Gin ลด แต่ความแม่นยำสกิลของ Miho และ Jin เพิ่ม' WHERE id = 1188;
UPDATE statuses SET description_th = '[ระดับ 10] Seolhwa เรียก clone ดาเมจทั้งหมด -5%' WHERE id = 1241;
UPDATE statuses SET description_th = 'กระต่ายที่เหยียดหยามหมาป่า' WHERE id = 833;
UPDATE statuses SET description_th = 'JD ดูหมกมุ่นอยู่ แต่ดูเหมือนจะมีรอยยิ้มลึกลับ' WHERE id = 1972;
