-- Batch 15: P section (1310-1400)

UPDATE statuses SET description_th = 'กำลังตั้งค่าสถานะและไอเทม' WHERE id = 1310;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่ และลด HP อย่างต่อเนื่อง' WHERE id = 1311;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้ สแตนซ์ อัตราเก็บของ 20% หายเมื่อเปลี่ยนพื้นที่' WHERE id = 1313;
UPDATE statuses SET description_th = 'A.R. +1' WHERE id = 1314;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +10%, พลังโจมตี +12%, เจาะเกราะ +12, สถานะทั้งหมด +5' WHERE id = 1315;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +30%, พลังโจมตี +20%, เจาะเกราะ +12, สถานะทั้งหมด +5' WHERE id = 1316;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +40%, พลังโจมตี +25%, เจาะเกราะ +15, สถานะทั้งหมด +5' WHERE id = 1317;
UPDATE statuses SET description_th = 'ลด SP ทั้งหมดชั่วคราว ไม่สามารถทำอะไรได้ขณะ Panic' WHERE id = 1318;
UPDATE statuses SET description_th = 'หยุดเคลื่อนไหว การหลบและบล็อกลดเป็น 0' WHERE id = 1319;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่ โจมตี และร่ายสกิล ถึง Lv.10 ไม่สามารถเคลื่อนไหว' WHERE id = 1320;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่ โจมตี และร่ายสกิล ถึง Lv.10 ไม่สามารถเคลื่อนไหว' WHERE id = 1322;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน 10% และเพิ่มฟื้นฟู HP' WHERE id = 1323;
UPDATE statuses SET description_th = 'ศักยภาพซ่อนเร้นเปิดจิตใจปรารถนาสันติ' WHERE id = 1324;
UPDATE statuses SET description_th = 'ภูมิคุ้มกัน +2 ต่อระดับ (สูงสุด 10), D.R. +1, พลังโจมตี +50%' WHERE id = 1325;
UPDATE statuses SET description_th = 'โจมตี Lt. General Batro ดาเมจเพิ่มทั้งรับและให้' WHERE id = 1332;
UPDATE statuses SET description_th = 'เพิ่มฟื้นฟู HP และต้านทาน ใส่สถานะหลับให้ศัตรู' WHERE id = 1333;
UPDATE statuses SET description_th = 'พลังโจมตี ความเร็วโจมตี ความเร็วเคลื่อนที่ -50%' WHERE id = 1334;
UPDATE statuses SET description_th = 'พลังโจมตี -1%, พลังป้องกัน -1' WHERE id = 1336;
UPDATE statuses SET description_th = 'A.R. -1, พลังโจมตี -5%, เจาะเกราะไฟ -10' WHERE id = 1337;
UPDATE statuses SET description_th = 'ลดความแม่นยำ 30 และเพิ่มเวลาร่ายสกิล 30% (PvP)' WHERE id = 1338;
UPDATE statuses SET description_th = 'กลายเป็นหิน ไม่สามารถเคลื่อนไหวหรือทำอะไรได้ชั่วคราว' WHERE id = 1339;
UPDATE statuses SET description_th = 'กลายเป็นหิน ไม่สามารถเคลื่อนไหวหรือทำอะไรได้ชั่วคราว' WHERE id = 1340;
UPDATE statuses SET description_th = '[Lv 10] HP สูงสุด +20%, ดาเมจที่ได้รับ -10%, ภูมิคุ้มกัน +10, ดาเมจมอนสเตอร์ +100%' WHERE id = 1341;
UPDATE statuses SET description_th = 'ลดพลังป้องกัน' WHERE id = 1342;
UPDATE statuses SET description_th = '10% โอกาสลดดาเมจกายภาพอย่างมาก' WHERE id = 1344;
UPDATE statuses SET description_th = 'ละเว้นดาเมจกายภาพประชิดและฟื้นฟู HP เท่ากับดาเมจ' WHERE id = 1346;
UPDATE statuses SET description_th = 'ประสบการณ์ความตาย ภูมิคุ้มกัน -15, พลังโจมตี -15%, ความเร็วโจมตี -15%, พลังป้องกัน -15' WHERE id = 1347;
UPDATE statuses SET description_th = 'ดนตรีเงียบและเร็วเพิ่มพลังป้องกัน' WHERE id = 1348;
UPDATE statuses SET description_th = 'ลด HP อย่างต่อเนื่อง' WHERE id = 1349;
UPDATE statuses SET description_th = 'เพิ่มความเร็วโจมตี' WHERE id = 1350;
UPDATE statuses SET description_th = 'เพิ่มสถานะทั้งหมด +5' WHERE id = 1351;
UPDATE statuses SET description_th = 'รู้สึกถึงความหลงใหลของ Pioneer' WHERE id = 1354;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้/สแตนซ์ ดาเมจมอนสเตอร์ ลดดาเมจจากมอนสเตอร์' WHERE id = 1355;
UPDATE statuses SET description_th = 'เพิ่มอัตราดรอปไอเทม' WHERE id = 1356;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์' WHERE id = 1357;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์สแตนซ์' WHERE id = 1358;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้ +50% เป็นเวลา 8 ชั่วโมง' WHERE id = 1359;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้ +50% เป็นเวลา 10 ชั่วโมง' WHERE id = 1360;
UPDATE statuses SET description_th = 'ค่าประสบการณ์เพิ่ม ดาเมจมอนสเตอร์ +30% อัตราดรอปเพิ่ม' WHERE id = 1361;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +2%, ค่าประสบการณ์ +2%, อัตราดรอป +2%' WHERE id = 1362;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +4%, ค่าประสบการณ์ +4%, อัตราดรอป +4%' WHERE id = 1363;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +6%, ค่าประสบการณ์ +6%, อัตราดรอป +6%' WHERE id = 1364;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +10%, ค่าประสบการณ์ +10%, อัตราดรอป +10%' WHERE id = 1365;
UPDATE statuses SET description_th = 'ละเว้นพลังป้องกันศัตรูเพิ่มเติม' WHERE id = 1366;
UPDATE statuses SET description_th = 'ความเร็วโจมตีและเคลื่อนที่เกินขีดจำกัดได้' WHERE id = 1367;
UPDATE statuses SET description_th = 'ค่าประสบการณ์ +200%, ค่าประสบการณ์สแตนซ์ +200%, อัตราดรอป +100%' WHERE id = 1368;
UPDATE statuses SET description_th = 'รู้สึกถึงความหลงใหลของ Pioneer' WHERE id = 1369;
UPDATE statuses SET description_th = 'ความเร็วเคลื่อนที่ +5%, ขีดจำกัดความเร็ว +10%' WHERE id = 1370;
UPDATE statuses SET description_th = 'ละเว้นพลังป้องกันศัตรูเพิ่มเติม' WHERE id = 1371;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่ม' WHERE id = 1372;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่ม' WHERE id = 1373;
UPDATE statuses SET description_th = 'พลังโจมตีเพิ่มและดาเมจสกิลเพิ่มเติม' WHERE id = 1374;
UPDATE statuses SET description_th = 'ไม่มีความเมตตาต่อศัตรู' WHERE id = 1375;
UPDATE statuses SET description_th = 'เพิ่มดาเมจสกิล Plan A' WHERE id = 1377;
UPDATE statuses SET description_th = 'เพิ่มดาเมจสกิล Plan B' WHERE id = 1378;
UPDATE statuses SET description_th = 'เพิ่มดาเมจสกิล Plan C' WHERE id = 1379;
UPDATE statuses SET description_th = 'ความสามารถทั้งหมดของ Van เพิ่มขึ้น' WHERE id = 1380;
