-- Batch 8: D-section (528-600)

UPDATE statuses SET description_th = 'ค่า DEX: เพิ่มพลังโจมตีไรเฟิลและอัตราคริติคอล' WHERE id = 529;
UPDATE statuses SET description_th = 'โจมตีปกติมีโอกาสทำบาดแผลสาหัส' WHERE id = 530;
UPDATE statuses SET description_th = 'โจมตีปกติมีโอกาสใส่ [พิษ] ให้ศัตรู' WHERE id = 531;
UPDATE statuses SET description_th = 'จิตวิญญาณฮีโร่ถูกกระตุ้น' WHERE id = 532;
UPDATE statuses SET description_th = 'เรียก Daneb Phantom ออกมา' WHERE id = 533;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +20%, ดาเมจมอนสเตอร์ +20%' WHERE id = 534;
UPDATE statuses SET description_th = 'สิ่งเรียกของ Simon Ayende ประเภทมนุษย์/เกราะเบา' WHERE id = 535;
UPDATE statuses SET description_th = 'ลด HP อย่างต่อเนื่องตลอดระยะเวลา' WHERE id = 536;
UPDATE statuses SET description_th = 'ไม่สามารถเคลื่อนที่ได้ชั่วคราว และ HP สูงสุดลดลง' WHERE id = 538;
UPDATE statuses SET description_th = 'เข้าสู่ความมืดและซ่อนร่างชั่วคราว' WHERE id = 539;
UPDATE statuses SET description_th = 'ความแม่นยำของเป้าหมายลดลงต่ำสุดชั่วคราว' WHERE id = 540;
UPDATE statuses SET description_th = 'เพิ่ม A.R., INT, พลังโจมตี, เจาะเกราะ และพลังป้องกัน ความเร็วเคลื่อนที่ลด' WHERE id = 542;
UPDATE statuses SET description_th = 'ตัดสินประหาร ดาเมจต่อ Scavenger เพิ่มขึ้น' WHERE id = 544;
UPDATE statuses SET description_th = 'D.R. เพิ่มอย่างมาก และไม่ถูกกำหนดเป้าหมายโจมตี' WHERE id = 545;
UPDATE statuses SET description_th = 'ได้รับดาเมจตรงที่ละเว้นพลังป้องกันและต้านทานเมื่อถูกโจมตี' WHERE id = 546;
UPDATE statuses SET description_th = 'ลดความสามารถของศัตรูอย่างรวดเร็ว' WHERE id = 548;
UPDATE statuses SET description_th = '[ระดับ 10] ภูมิคุ้มกัน -5, พลังโจมตี -10%' WHERE id = 549;
UPDATE statuses SET description_th = 'หลับลึก ยกเลิกเมื่อได้รับดาเมจ' WHERE id = 550;
UPDATE statuses SET description_th = '[Lv 1] D.R. -2, ละเว้นพลังป้องกัน -7%, ดาเมจยิง -24%, ความเร็วเคลื่อนที่ -20' WHERE id = 552;
UPDATE statuses SET description_th = '[พันธมิตร]: พลังป้องกัน -20, ต้านทาน -15, ภูมิคุ้มกัน -10 [ศัตรู]: ภูมิคุ้มกันต่อ [Stitch]' WHERE id = 553;
UPDATE statuses SET description_th = 'ความสามารถป้องกันของ Erika เพิ่มขึ้น ได้รับ [Strike Conversion]' WHERE id = 555;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน บล็อก และภูมิคุ้มกัน' WHERE id = 556;
UPDATE statuses SET description_th = 'มอนสเตอร์ได้รับดาเมจจากผู้เล่นน้อยลง' WHERE id = 557;
UPDATE statuses SET description_th = 'อาจถูกปนเปื้อนจากพลังเสื่อม' WHERE id = 558;
UPDATE statuses SET description_th = 'พลังโจมตี +30%, ดาเมจคริติคอล +15%, คริติคอล +10, เจาะเกราะกายภาพเพิ่ม' WHERE id = 559;
UPDATE statuses SET description_th = 'พลังโจมตี +2% ต่อระดับ (สูงสุด 100%), โจมตีปกติ +1% ต่อระดับ' WHERE id = 560;
UPDATE statuses SET description_th = 'เพิ่ม A.R. +1 และ D.R. +1' WHERE id = 561;
UPDATE statuses SET description_th = 'โจมตีปกติมีโอกาสใส่ [Lily of the Valley] ให้ตัวเอง' WHERE id = 562;
UPDATE statuses SET description_th = 'A.R., D.R., ความคล่องตัว และภูมิคุ้มกันเพิ่ม' WHERE id = 563;
UPDATE statuses SET description_th = 'เพิ่มความเร็วโจมตี ความเร็วเคลื่อนที่' WHERE id = 565;
UPDATE statuses SET description_th = 'เพิ่มภูมิคุ้มกัน' WHERE id = 568;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี เจาะเกราะกายภาพ บล็อก ภูมิคุ้มกัน A.R.' WHERE id = 570;
UPDATE statuses SET description_th = 'เพิ่มโจมตีปกติ 1.5 เท่า และเพิ่มสกิลโจมตี 1 เท่า' WHERE id = 571;
UPDATE statuses SET description_th = 'ปลดปล่อยพันธนาการที่รัดมือทั้งสองข้างของ Hildegard' WHERE id = 574;
UPDATE statuses SET description_th = 'ผู้ร่ายและเป้าหมายรับดาเมจสกิล 50% และดาเมจที่แบ่ง' WHERE id = 575;
UPDATE statuses SET description_th = 'ลด A.R., D.R., พลังโจมตี, พลังป้องกัน และความแม่นยำ' WHERE id = 576;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่จากศักดิ์ศรีบอสมอนสเตอร์' WHERE id = 584;
UPDATE statuses SET description_th = 'เพิ่มเวทย์ไฟโดยรับแก่นแท้ของไฟ' WHERE id = 585;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +5%, เจาะเกราะสายฟ้า +10, เวลาร่ายสกิล -10%, SP +1000' WHERE id = 587;
UPDATE statuses SET description_th = 'ไฟฟ้าหมด ไม่สามารถใช้สกิลได้' WHERE id = 588;
UPDATE statuses SET description_th = 'ลดการฟื้นฟู SP ชั่วคราว' WHERE id = 589;
UPDATE statuses SET description_th = 'ขึ้นอยู่กับประเภทป้องกันของศัตรู จะนำไปสู่การต่อสู้ที่ได้เปรียบ' WHERE id = 591;
