-- Batch 22: U-V-W-Z section (1854-1972)

UPDATE statuses SET description_th = 'ต้านทานสายฟ้า -5' WHERE id = 1854;
UPDATE statuses SET description_th = 'พลังป้องกัน -10' WHERE id = 1855;
UPDATE statuses SET description_th = 'ละเว้นโจมตีทั้งหมดชั่วคราว' WHERE id = 1856;
UPDATE statuses SET description_th = 'ภูมิคุ้มกัน -3, พลังป้องกัน -3 ดาเมจเพิ่มจาก Violante และสิ่งเรียกของ Christine' WHERE id = 1858;
UPDATE statuses SET description_th = 'พลังโจมตี +10%, ความเร็วโจมตี +20%' WHERE id = 1859;
UPDATE statuses SET description_th = 'ระยะเวลา 2 วินาที ตรวจจับล่องหน พลังป้องกัน -5' WHERE id = 1860;
UPDATE statuses SET description_th = 'ได้สิ่งจำเป็นสำหรับการเอาชีวิตรอด' WHERE id = 1861;
UPDATE statuses SET description_th = 'D.R. +999 ชั่วคราว' WHERE id = 1862;
UPDATE statuses SET description_th = 'ไม่สามารถเคลื่อนที่ได้' WHERE id = 1863;
UPDATE statuses SET description_th = 'ไม่สามารถโจมตี ใช้สกิล และควบคุม (PvP)' WHERE id = 1865;
UPDATE statuses SET description_th = 'เพิ่มระยะโจมตี' WHERE id = 1866;
UPDATE statuses SET description_th = 'เพิ่มโจมตีปกติ' WHERE id = 1867;
UPDATE statuses SET description_th = 'เพิ่มสกิลโจมตี' WHERE id = 1868;
UPDATE statuses SET description_th = 'สั่งปฏิบัติการฉุกเฉิน' WHERE id = 1869;
UPDATE statuses SET description_th = 'เพิ่มความสามารถทางกายภาพโดยรวม' WHERE id = 1870;
UPDATE statuses SET description_th = 'เพิ่มเอฟเฟกต์ให้โจมตีถัดไปของ Freya สกิล Kashta' WHERE id = 1871;
UPDATE statuses SET description_th = 'พลังโจมตี +4%, พลังโจมตียิง +5%, มีโอกาสใส่ [Bleeding] เมื่อโจมตีปกติ' WHERE id = 1872;
UPDATE statuses SET description_th = 'เพิ่มดาเมจเวทย์ให้สมาชิกทีมทั้งหมด' WHERE id = 1874;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่และพลังป้องกัน ลด HP อย่างต่อเนื่อง' WHERE id = 1875;
UPDATE statuses SET description_th = 'ขว้างธาตุเสื่อมหลายชิ้นไปที่ศัตรู' WHERE id = 1876;
UPDATE statuses SET description_th = 'A.R. และ D.R. -1 ได้รับดาเมจเพิ่มจากสกิลของ Gabriella' WHERE id = 1877;
UPDATE statuses SET description_th = 'เพิ่มความสามารถ แต่จำกัดการใช้สกิลและไอเทม' WHERE id = 1879;
UPDATE statuses SET description_th = 'หมุนเวียนจิตวิญญาณนักสู้ที่ซ่อนอยู่ ทำให้คมแหลม' WHERE id = 1880;
UPDATE statuses SET description_th = '[Lv 1] พลังโจมตี -1%, พลังป้องกัน -1, หลบ -1, บล็อก -1' WHERE id = 1881;
UPDATE statuses SET description_th = 'เพิ่มความสามารถโจมตีอย่างรุนแรง' WHERE id = 1882;
UPDATE statuses SET description_th = 'ดนตรีเงียบและเร็วเพิ่มพลังป้องกัน' WHERE id = 1883;
UPDATE statuses SET description_th = 'ดาเมจยิงที่ได้รับ +20%' WHERE id = 1884;
UPDATE statuses SET description_th = 'ใส่ [Decay] ให้ศัตรู ทำดาเมจเพิ่มเติมต่อโจมตี' WHERE id = 1885;
UPDATE statuses SET description_th = 'HP และ SP ลด ไม่สามารถใช้ไอเทมตลอดระยะเวลา' WHERE id = 1887;
UPDATE statuses SET description_th = 'HP เพิ่มอย่างมาก' WHERE id = 1891;
UPDATE statuses SET description_th = 'ปลุก Reng เตรียมพร้อมรบ' WHERE id = 1892;
UPDATE statuses SET description_th = 'พลังโจมตี +4%, พลังโจมตีเวทย์ +5%, มีโอกาสใส่ [Venom] เมื่อโจมตีปกติ' WHERE id = 1893;
UPDATE statuses SET description_th = 'ลดความสามารถทางกายภาพ ได้รับดาเมจเพิ่มจากสกิล [Spartan]' WHERE id = 1897;
UPDATE statuses SET description_th = 'ความเร็วเคลื่อนที่ +50%, ความเร็วโจมตี +50% ขีดจำกัดความเร็วปลด buff หายเมื่อโจมตี' WHERE id = 1898;
UPDATE statuses SET description_th = 'เพิ่ม A.R. และ D.R. +2' WHERE id = 1899;
UPDATE statuses SET description_th = 'พลังโจมตียิง +10%, เจาะเกราะ +10, ความเร็วโจมตี +10%' WHERE id = 1900;
UPDATE statuses SET description_th = 'คุณกำลังเฝ้าดู' WHERE id = 1901;
UPDATE statuses SET description_th = 'เพิ่มฟื้นฟู HP และต้านทานอย่างมาก' WHERE id = 1903;
UPDATE statuses SET description_th = 'เพิ่มการหลบ สามารถหลบโจมตียิงได้ด้วย' WHERE id = 1904;
UPDATE statuses SET description_th = 'ลด A.R. -1' WHERE id = 1905;
UPDATE statuses SET description_th = 'ประสิทธิภาพอาวุธ -2% ต่อระดับ [มอนสเตอร์ 50%] A.R. -1 ที่ระดับ 10+' WHERE id = 1907;
UPDATE statuses SET description_th = 'ตกลงพื้นและหยุดเคลื่อนไหวชั่วคราว' WHERE id = 1911;
UPDATE statuses SET description_th = 'เพิ่มความเร็วโจมตีชั่วคราว หายเมื่อเปลี่ยนสแตนซ์' WHERE id = 1916;
UPDATE statuses SET description_th = 'สกิลโจมตีถัดไปเปลี่ยนเป็นดาเมจเวทย์ หรือเพิ่มดาเมจสกิล' WHERE id = 1919;
UPDATE statuses SET description_th = 'ภูมิคุ้มกัน +5, ความเร็วเคลื่อนที่ +10%, พลังป้องกัน +10 ไม่ซ้อนกับ Damnation' WHERE id = 1920;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันของเป้าหมายเป็นเวลา 30 วินาที' WHERE id = 1923;
