-- Batch 16: P remainder + Q (1381-1450)

UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี/ดาเมจมอนสเตอร์' WHERE id = 1381;
UPDATE statuses SET description_th = 'สวมหน้ากากกันแก๊ส ความสามารถมอนสเตอร์ไม่ลด' WHERE id = 1383;
UPDATE statuses SET description_th = 'ลด A.R., บล็อก และพลังป้องกันเป็นเวลา 5 นาที' WHERE id = 1385;
UPDATE statuses SET description_th = 'ดาเมจจากมอนสเตอร์ -1% ต่อระดับ สะท้อนดาเมจเวทย์ 50%' WHERE id = 1386;
UPDATE statuses SET description_th = '[PvP] ความเร็วโจมตี -100%, ฟื้นฟู HP -50%, ต้านทานน้ำแข็ง -20' WHERE id = 1387;
UPDATE statuses SET description_th = 'ได้รับการป้องกันที่ละเว้นโจมตีเวทย์อันตราย ดาเมจเพิ่ม' WHERE id = 1388;
UPDATE statuses SET description_th = 'เพิ่มความสามารถสูงสุดด้วยการถูกวิญญาณเข้าสิง' WHERE id = 1389;
UPDATE statuses SET description_th = 'HP สูงสุดเพิ่ม ดาเมจสกิลที่ได้รับลด' WHERE id = 1390;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี' WHERE id = 1392;
UPDATE statuses SET description_th = 'ลดความเร็วโจมตี ความเร็วเคลื่อนที่ พลังป้องกัน ต้านทานเวทย์ และความแม่นยำ' WHERE id = 1393;
UPDATE statuses SET description_th = 'พลังป้องกันเป็น 0 เป็นเวลา 20 วินาที' WHERE id = 1394;
UPDATE statuses SET description_th = 'เพิ่มเกรดโจมตีและป้องกัน +1, ความเร็วโจมตี +10%, ความเร็วเคลื่อนที่ +15%' WHERE id = 1395;
UPDATE statuses SET description_th = 'ความเร็วเคลื่อนที่ลดครึ่งเป็นเวลา 10 วินาที พลังป้องกันไม่ทำงาน' WHERE id = 1396;
UPDATE statuses SET description_th = 'ลดความเร็วโจมตีและเคลื่อนที่ชั่วคราว' WHERE id = 1397;
UPDATE statuses SET description_th = 'หยุดเคลื่อนไหว' WHERE id = 1398;
UPDATE statuses SET description_th = 'พลังอันยิ่งใหญ่มอบให้ครู' WHERE id = 1399;
UPDATE statuses SET description_th = 'เพิ่มดาเมจโจมตีปกติ และมีโอกาสใส่ [True Sight] ให้ศัตรู' WHERE id = 1400;
UPDATE statuses SET description_th = 'เปลี่ยนแผนตามสถานการณ์ขณะโจมตีปกติ' WHERE id = 1401;
UPDATE statuses SET description_th = 'เพิ่มอัตราค่าประสบการณ์และดรอปไอเทม 15%' WHERE id = 1402;
UPDATE statuses SET description_th = 'พลังป้องกัน -300, ต้านทานทั้งหมด -75, บล็อก -75, หลบ -75' WHERE id = 1404;
UPDATE statuses SET description_th = 'สะสมดาเมจที่ถูกโจมตีในปริมาณที่กำหนด' WHERE id = 1405;
UPDATE statuses SET description_th = 'เพิ่มความสามารถพื้นฐานอย่างแรงที่สุด' WHERE id = 1408;
UPDATE statuses SET description_th = '[PvP] พลังโจมตี -5%, พลังป้องกัน -10, ภูมิคุ้มกัน -5, ความเร็วเคลื่อนที่ -10% (D.R. -1 ที่ระดับ 11+)' WHERE id = 1412;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี เจาะเกราะ ต้านทานเวทย์สูง แต่อ่อนแอต่อกายภาพ' WHERE id = 1413;
UPDATE statuses SET description_th = 'ลดเวลาร่ายสกิลชั่วคราว' WHERE id = 1414;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน ปิดใช้งาน ลด HP อย่างต่อเนื่อง' WHERE id = 1415;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน ปิดใช้งาน ลด HP อย่างต่อเนื่อง' WHERE id = 1416;
UPDATE statuses SET description_th = 'เพิ่มความแม่นยำ ความเร็วโจมตี และโอกาสละเว้นพลังป้องกัน' WHERE id = 1417;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี พลังป้องกัน และ D.R.' WHERE id = 1418;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกัน ภูมิคุ้มกัน ลดดาเมจทั้งหมด' WHERE id = 1419;
UPDATE statuses SET description_th = 'ยิงกระสุนที่มีพลังศักดิ์สิทธิ์' WHERE id = 1420;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและดาเมจมอนสเตอร์' WHERE id = 1421;
UPDATE statuses SET description_th = 'พลังป้องกัน +10, ภูมิคุ้มกัน +10, บล็อก +10, หลบ +10, เวลาล้มลง -50%' WHERE id = 1422;
UPDATE statuses SET description_th = 'ปกป้องตัวละคร 1 วินาที' WHERE id = 1423;
UPDATE statuses SET description_th = 'ดาเมจสกิลวงกว้างลดอย่างมาก' WHERE id = 1424;
UPDATE statuses SET description_th = 'พลังป้องกัน +10, ภูมิคุ้มกัน +10, บล็อก +10, หลบ +10, เวลาล้มลง -50%' WHERE id = 1426;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันชั่วคราว แต่ไม่สามารถใช้สกิล' WHERE id = 1427;
UPDATE statuses SET description_th = 'สั่งป้องกันในสนามรบ' WHERE id = 1429;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันและ HP สูงสุดในรัศมี' WHERE id = 1430;
UPDATE statuses SET description_th = 'เพิ่มความสามารถด้วยพลัง Abyss 01' WHERE id = 1432;
UPDATE statuses SET description_th = 'เพิ่มความสามารถด้วยพลัง Abyss 02' WHERE id = 1433;
UPDATE statuses SET description_th = 'เพิ่มความสามารถด้วยพลัง Abyss 03' WHERE id = 1434;
UPDATE statuses SET description_th = 'เพิ่มความสามารถด้วยพลัง Abyss 04' WHERE id = 1435;
UPDATE statuses SET description_th = 'เพิ่มความสามารถด้วยพลัง Abyss 05' WHERE id = 1436;
UPDATE statuses SET description_th = 'ได้รับสิทธิ์เข้า Ancient Shelter' WHERE id = 1437;
UPDATE statuses SET description_th = 'D.R. +1, HP สูงสุด +1500' WHERE id = 1438;
UPDATE statuses SET description_th = 'สามารถเข้า Quiritatio, Einherjar ได้' WHERE id = 1439;
UPDATE statuses SET description_th = 'สามารถเข้า Distorted Time, Imperium Arma ได้' WHERE id = 1440;
UPDATE statuses SET description_th = 'เพิ่มความสามารถตามระดับ Family' WHERE id = 1441;
UPDATE statuses SET description_th = 'ลดดาเมจจากสกิลโจมตีของ Argus Brain' WHERE id = 1442;
UPDATE statuses SET description_th = 'ระยะเวลา: 4 วินาที พลังโจมตี +3%, เจาะเกราะ +1, ภูมิคุ้มกัน +1' WHERE id = 1443;
UPDATE statuses SET description_th = 'เพิ่มความสามารถหลากหลาย' WHERE id = 1444;
UPDATE statuses SET description_th = 'HP สูงสุด +1000' WHERE id = 1445;
UPDATE statuses SET description_th = 'อัตราดรอป +40%, ดาเมจที่ให้ +10%, พลังป้องกัน -10' WHERE id = 1446;
UPDATE statuses SET description_th = 'ปกป้องจากสกิลประชิด/ยิงของ PvP ที่เกินค่า HP' WHERE id = 1447;
