-- Batch 10: F-G-H section (733-830)

UPDATE statuses SET description_th = 'ผ่านศรัทธาในพระเจ้า ความรู้สึกเจ็บปวดจะหายไป' WHERE id = 733;
UPDATE statuses SET description_th = 'ลดดาเมจ Gullfaxis เพิ่ม D.R. +2' WHERE id = 734;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +30%, เจาะเกราะ +20, ดาเมจมอนสเตอร์ +30%' WHERE id = 735;
UPDATE statuses SET description_th = 'เพิ่ม A.R. เวลาร่ายสกิล และเจาะเกราะ' WHERE id = 737;
UPDATE statuses SET description_th = 'โจมตีปกติทุกครั้งทำบาดแผลสาหัสให้ศัตรู' WHERE id = 739;
UPDATE statuses SET description_th = 'เพิ่ม HP ด้วยพลังธรรมชาติ' WHERE id = 743;
UPDATE statuses SET description_th = 'เพิ่มโอกาสได้รับไอเทม 30%' WHERE id = 744;
UPDATE statuses SET description_th = 'จิตวิญญาณนักสู้รวมเข้า Barisada' WHERE id = 750;
UPDATE statuses SET description_th = 'อนุมัติการโจมตีครั้งสุดท้าย' WHERE id = 751;
UPDATE statuses SET description_th = 'เพิ่มความสามารถอาวุธปืนสูงสุด' WHERE id = 752;
UPDATE statuses SET description_th = 'ไม่สามารถทำอะไรได้ HP สูงสุด -30% ต้านทานน้ำแข็งลดเป็น 0 ลด HP อย่างต่อเนื่อง' WHERE id = 753;
UPDATE statuses SET description_th = 'เพิ่มเจาะเกราะไฟ' WHERE id = 754;
UPDATE statuses SET description_th = 'เพิ่ม A.R. และพลังโจมตีอย่างมาก' WHERE id = 755;
UPDATE statuses SET description_th = 'A.R. +1, พลังโจมตี +30%, ละเว้นพลังป้องกันศัตรู 3%' WHERE id = 756;
UPDATE statuses SET description_th = 'ชาร์จพลังไฟ' WHERE id = 760;
UPDATE statuses SET description_th = 'ห่อหุ้มร่างด้วยเปลวเพลิง เพิ่มความสามารถป้องกัน' WHERE id = 761;
UPDATE statuses SET description_th = 'ลดเอฟเฟกต์การรักษาทั้งหมดด้วยตราเวทย์มรณะ' WHERE id = 762;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +50%' WHERE id = 764;
UPDATE statuses SET description_th = 'ฝูงค้างคาวทำดาเมจต่อเนื่องให้ศัตรูใกล้เคียง' WHERE id = 766;
UPDATE statuses SET description_th = 'D.R. -1, ต้านทานน้ำแข็ง -1 ต่อระดับ, พลังโจมตี -2% ต่อระดับ' WHERE id = 768;
UPDATE statuses SET description_th = 'ฟื้นฟู SP +100, A.R. +1 ที่ Lv.10+, เจาะเกราะน้ำแข็ง +3 ต่อระดับ' WHERE id = 771;
UPDATE statuses SET description_th = 'ลดความเร็วเคลื่อนที่ตามประเภทเกราะ' WHERE id = 774;
UPDATE statuses SET description_th = 'เพิ่ม HP สูงสุดเป็นระยะเวลาหนึ่ง' WHERE id = 775;
UPDATE statuses SET description_th = 'ละเว้นค่าต้านทานธาตุของเป้าหมาย 4 จุด' WHERE id = 778;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตี อัตราหลบ และอัตราคริติคอล' WHERE id = 781;
UPDATE statuses SET description_th = 'คลั่ง เพิ่มสถานะทั้งหมด' WHERE id = 783;
UPDATE statuses SET description_th = 'ปลดปล่อยสถานะทั้งหมดที่ถูกกักไว้ในร่างกาย' WHERE id = 784;
UPDATE statuses SET description_th = 'จะได้รับอิสรภาพแห่งจิตวิญญาณ' WHERE id = 785;
UPDATE statuses SET description_th = 'หยุดเคลื่อนไหว 10 วินาที การหลบและบล็อกไม่ทำงาน ต้านทานสายฟ้าลด' WHERE id = 787;
UPDATE statuses SET description_th = 'พลังโจมตี +10%, ความเร็วโจมตี +10%' WHERE id = 789;
UPDATE statuses SET description_th = 'พลังโจมตี +10%, ความเร็วโจมตี +20%' WHERE id = 790;
UPDATE statuses SET description_th = 'เพิ่มความเร็วโจมตี ความเร็วเคลื่อนที่ และพลังโจมตี' WHERE id = 791;
UPDATE statuses SET description_th = 'ลดความเร็วโจมตีและเพิ่มเวลาร่ายสกิล' WHERE id = 793;
UPDATE statuses SET description_th = 'ลดความเร็วโจมตีและเพิ่มเวลาร่ายสกิล' WHERE id = 797;
UPDATE statuses SET description_th = 'ชาร์จพลังน้ำแข็ง ยกเลิกเมื่อเปลี่ยนสแตนซ์' WHERE id = 798;
UPDATE statuses SET description_th = 'ดาเมจมอนสเตอร์ +12%, พลังโจมตี +12%, เจาะเกราะ +12, สถานะทั้งหมด +7' WHERE id = 799;
UPDATE statuses SET description_th = 'เพิ่มบล็อกเป็นเวลา 90 วินาที' WHERE id = 800;
UPDATE statuses SET description_th = 'ชาร์จพลังน้ำแข็ง' WHERE id = 803;
UPDATE statuses SET description_th = 'เพิ่มเอฟเฟกต์สกิล STR +5, พลังโจมตี +10%, เจาะเกราะ +15' WHERE id = 804;
UPDATE statuses SET description_th = 'พลังโจมตี +5%, ต้านทานทั้งหมด +5, ฟื้นฟู HP/SP +15%' WHERE id = 805;
UPDATE statuses SET description_th = 'เพิ่มพลังป้องกันและการหลบ' WHERE id = 806;
UPDATE statuses SET description_th = 'เพิ่มความสามารถทางกายภาพ' WHERE id = 807;
UPDATE statuses SET description_th = 'เพิ่มพลังโจมตีและ A.R. ของมอนสเตอร์อย่างมาก' WHERE id = 808;
UPDATE statuses SET description_th = 'ความเร็วโจมตีและเคลื่อนที่เพิ่มชั่วคราว แต่พลังป้องกันลด' WHERE id = 812;
UPDATE statuses SET description_th = 'เพิ่มค่าประสบการณ์การต่อสู้/สแตนซ์ ดาเมจมอนสเตอร์ และลดดาเมจจากมอนสเตอร์' WHERE id = 813;
UPDATE statuses SET description_th = 'บล็อกน้ำแข็งทำให้เย็นตัวเอง เพิ่มความสามารถโจมตี' WHERE id = 815;
UPDATE statuses SET description_th = 'เพิ่มดาเมจจาก Cecil และเป้าหมาย crossfire จาก Grey' WHERE id = 816;
UPDATE statuses SET description_th = 'ได้รับพลังเหนือธรรมชาติผ่านคำสาบานต่อพระเจ้า แต่ถ้าผิดคำสาบานจะเสียพลัง' WHERE id = 818;
UPDATE statuses SET description_th = 'สร้างปาฏิหาริย์ผ่านพลังศักดิ์สิทธิ์ ลดดาเมจจากมอนสเตอร์' WHERE id = 819;
UPDATE statuses SET description_th = 'โจมตีฝ่ายเดียวโดยไม่ถูกตรวจจับโดยศัตรู' WHERE id = 821;
